Ameliore la documentation pour MacOS.
zestedesavoir/zds-site pull request #3854
Opened 2016-10-14 19:54 UTC by GerardPaligot

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | évolution
| Ticket(s) (_issue(s)_) concerné(s)  | N/A

J'ai récemment installé un environnement de dev sur un nous macOS et il se trouve qu'il y avait des choses obsolètes. J'ai donc fais une mise à jour de la documentation et du Makefile. (:

2016-10-14 20:01 UTC, sandhose reviewed
Globalement j'approuve. J'ai review à la va-vite, d'où le fait que c'est un peu court et que ça peut paraître un peu sec, mais c'est pas l'intention derrière 🦄  (je répondrais plus en détail plus tard, pas le temps maintenant c: )

2016-10-14 20:01 UTC, sandhose commented on Makefile
> +	brew install gettext && \
Pourquoi séparer ?

2016-10-14 20:01 UTC, sandhose commented on doc/source/install/backend-os-x-install.rst
> +  xcode-select --install
Homebrew le fait tout seul à l'install, pas la peine

2016-10-14 20:01 UTC, sandhose commented on doc/source/install/backend-os-x-install.rst
> +  brew install python --framework
Pas certain que ça soit nécessaire ? Le python système est relativement à jour

2016-10-14 20:01 UTC, sandhose commented on doc/source/install/backend-os-x-install.rst
> +  wget https://bootstrap.pypa.io/get-pip.py
`pip` est dans la recette python dans hombrew. Donc soit on utilise la version système, et du coup, c'est effectivement nécessaire d'installer pip comme ça, soit on utilise la version d'homebrew et c'est pas la peine

2016-10-14 20:01 UTC, sandhose commented on doc/source/install/backend-os-x-install.rst
> +  echo "source /usr/local/bin/virtualenvwrapper.sh" >> ~/.bash_profile && source /usr/local/bin/virtualenvwrapper.sh
Et pour ceux qu'utilisent pas bash ? :(

2016-10-14 20:01 UTC, sandhose commented on doc/source/install/backend-os-x-install.rst
> +  echo "source /usr/local/bin/virtualenvwrapper.sh" >> ~/.bash_profile && source /usr/local/bin/virtualenvwrapper.sh
Hmm, je vois pas comment il est installé `virtualenvwrapper`, la :(

2016-10-14 20:10 UTC, vhf requested changes

2016-10-14 20:10 UTC, vhf commented on Makefile
> +	brew install geoip && \
J'ai pas souvenir que ce soit nécessaire.

2016-10-14 20:10 UTC, vhf commented on doc/source/install/backend-os-x-install.rst
> +  make install-osx
C'est un pré-requis.

2016-10-14 20:10 UTC, vhf commented on doc/source/install/backend-os-x-install.rst
> +  echo "source /usr/local/bin/virtualenvwrapper.sh" >> ~/.bash_profile && source /usr/local/bin/virtualenvwrapper.sh
Ajouter des choses au bashrc ou bash_profile ET les exporter dans le shell courant au fur et à mesure n'est pas utile, on peut simplement `source`r le profile après l'avoir modifié.

2016-10-14 20:10 UTC, vhf commented on doc/source/install/backend-os-x-install.rst
> +Installation des des dépendances front et back
```diff
-Installation des des dépendances front et back
+Installation des dépendances front et back
```

2016-10-14 20:10 UTC, vhf commented on doc/source/install/backend-os-x-install.rst
> +Lancer un virtualenv :
Je trouve pas le terme "lancer" approprié. "Entrer dans" ou "activer", puis "sortir de" ou "désactiver" serait plus compréhensible.

2016-10-14 20:10 UTC, vhf commented on doc/source/install/backend-os-x-install.rst
> +  make install-front
Est-ce que tu as testé ? A priori `brew install node` installe node 6, et ZdS ne fonctionne pas avec node 6.

2016-10-14 20:12 UTC, vhf commented
Cool de rafraichir un peu tout ça ! Je suppose que t'as fait ça depuis ton nouvel environnement ? J'ai cette impression parce que je sais pas si c'est volontaire ou pas mais ton commit est pas signé comme d'habitude, t'as peut-être oublié de configurer ton git…

2016-10-14 20:19 UTC, GerardPaligot commented on Makefile
> +	brew install gettext && \
Parce que j'ai écris les instructions au fur et à mesure. On peut fusionner si ça te perturbe. ^^

2016-10-14 20:19 UTC, GerardPaligot commented on doc/source/install/backend-os-x-install.rst
> +  xcode-select --install
Euh non. oO

2016-10-14 20:21 UTC, GerardPaligot commented on doc/source/install/backend-os-x-install.rst
> +  brew install python --framework
Non, ce n'est pas nécessaire mais ça permet de mieux contrôler ton environnement. Par exemple, si j'utilise le python système, j'étais obligé d'utiliser sudo pour installer `pip` et donc, certaines dépendances de ZdS devenaient pénibles à installer.

2016-10-14 20:22 UTC, GerardPaligot commented on doc/source/install/backend-os-x-install.rst
> +  wget https://bootstrap.pypa.io/get-pip.py
Bien vu, je vais retirer ça mais faut se fixer sur [cette question](https://github.com/zestedesavoir/zds-site/pull/3854#discussion_r83490531) alors.

2016-10-14 20:23 UTC, GerardPaligot commented on doc/source/install/backend-os-x-install.rst
> +  echo "source /usr/local/bin/virtualenvwrapper.sh" >> ~/.bash_profile && source /usr/local/bin/virtualenvwrapper.sh
Comment ça ?

2016-10-14 20:24 UTC, GerardPaligot commented on doc/source/install/backend-os-x-install.rst
> +  echo "source /usr/local/bin/virtualenvwrapper.sh" >> ~/.bash_profile && source /usr/local/bin/virtualenvwrapper.sh
Il est installé par la commande `make install-osx`. Là c'est de la config nécessaire pour `virtualenvwrapper` ([doc](https://virtualenvwrapper.readthedocs.io/en/latest/)).

2016-10-14 20:24 UTC, GerardPaligot commented on Makefile
> +	brew install geoip && \
A une époque c'était le cas en tout cas, comment on peut vérifier ?

2016-10-14 20:25 UTC, GerardPaligot commented on doc/source/install/backend-os-x-install.rst
> +  make install-osx
Tout à fait, tu veux mettre cette commande en avant ?

2016-10-14 20:27 UTC, GerardPaligot commented on doc/source/install/backend-os-x-install.rst
> +  echo "source /usr/local/bin/virtualenvwrapper.sh" >> ~/.bash_profile && source /usr/local/bin/virtualenvwrapper.sh
Je ne comprends pas trop. :/

2016-10-14 20:27 UTC, GerardPaligot commented on doc/source/install/backend-os-x-install.rst
> +Lancer un virtualenv :
Je vais modifier ça.

2016-10-14 20:28 UTC, GerardPaligot commented on doc/source/install/backend-os-x-install.rst
> +  make install-front
Si, merci à @sandhose [PR](https://github.com/zestedesavoir/zds-site/pull/3818).

2016-10-14 20:29 UTC, vhf commented on doc/source/install/backend-os-x-install.rst
> +  xcode-select --install
Si. Tu peux regarder la source du script qui install homebrew pour vérifier.

2016-10-14 20:30 UTC, vhf commented on doc/source/install/backend-os-x-install.rst
> +  echo "source /usr/local/bin/virtualenvwrapper.sh" >> ~/.bash_profile && source /usr/local/bin/virtualenvwrapper.sh
@sandhose et moi n'utilisons pas bash. Du coup ces instructions n'auraient aucun effet. Mais on peut partir du principe que les gens qui utilisent pas bash savent se débrouiller avec ce genre de trucs, à mon avis.

2016-10-14 20:30 UTC, GerardPaligot commented
C'est pas faux, faut que je pense à configurer mon Git sur le projet zds-site. (:

2016-10-14 20:31 UTC, vhf commented on Makefile
> +	brew install geoip && \
Tu peux le désinstaller et vérifier que ZdS fonctionne. C'est nécessaire en prod pour avoir la localisation des IP dans les profils des membres, mais en local a priorio t'auras jamais d'IPs externes. En tout cas j'ai jamais installé ça sur ma machine.

2016-10-14 20:31 UTC, vhf commented on doc/source/install/backend-os-x-install.rst
> +  make install-osx
Oui, je pense que la section "Pré-requis" serait adéquate.

2016-10-14 20:32 UTC, GerardPaligot commented on doc/source/install/backend-os-x-install.rst
> +  xcode-select --install
Si bizarre parce que j'ai du lancer cette commande après l'installation de Homebrew.

2016-10-14 20:33 UTC, vhf commented on doc/source/install/backend-os-x-install.rst
> +  brew install python --framework
En fait on utilise virtualenv exprès pour éviter d'avoir à installer des trucs globalement. Pas besoin de `sudo pip` dans un virtualenv.

2016-10-14 20:34 UTC, GerardPaligot commented on doc/source/install/backend-os-x-install.rst
> +  brew install python --framework
Tu as un moyen pour installer un python dans le virtualenv ? Ca pourrait être cool ça.

2016-10-14 21:58 UTC, vhf commented on doc/source/install/backend-os-x-install.rst
> +  brew install python --framework
Non, mais c'est pas vraiment ça le but. Le but c'est que `pip` n'installe pas ses trucs globalement ce qui requiert `sudo`, mais plutôt les installer dans un environnement virtuel, avec `virtualenv`.

Faut peser le pour et le contre, moi j'ai rien contre installer python avec brew par exemple. Faut juste choisir, soit on installe python avec brew, soit on utilise le python du système par contre il faut installer pip.

2016-10-14 22:02 UTC, vhf commented on doc/source/install/backend-os-x-install.rst
> +  echo "source /usr/local/bin/virtualenvwrapper.sh" >> ~/.bash_profile && source /usr/local/bin/virtualenvwrapper.sh
Ce que tu ne comprends pas c'est ce que font ces lignes (les 2 qui commencent par `echo`), ou c'est pourquoi elles sont pas optimales ?

2016-10-14 22:05 UTC, vhf commented on doc/source/install/backend-os-x-install.rst
> +  make install-front
Ouais d'accord, donc sur `dev` ça devrait passer (j'ai pas testé), merci!

2016-10-14 23:08 UTC, sandhose commented on doc/source/install/backend-os-x-install.rst
> +  echo "source /usr/local/bin/virtualenvwrapper.sh" >> ~/.bash_profile && source /usr/local/bin/virtualenvwrapper.sh
ack, j'avais pas vu

2016-10-14 23:12 UTC, sandhose commented on doc/source/install/backend-os-x-install.rst
> +  export PATH=/usr/local/bin:/usr/local/sbin:${PATH}
Hmm, m'étonnerait pas que homebrew fasse ça de basse. À vérifier.

2016-10-14 23:15 UTC, sandhose commented on doc/source/install/backend-os-x-install.rst
> +  brew install python --framework
Je pense que du coup, passer sur le python brew, c'est plus safe, étant donné qu'il est à jour même sur les vieilles versions de macOS. Et ça installe pip.

2016-10-14 23:17 UTC, sandhose commented on doc/source/install/backend-os-x-install.rst
> +- Installer `XCode <http://itunes.apple.com/us/app/xcode/id497799835?ls=1&mt=12>`_ :
Du coup, pas la peine non plus. C'est juste les command-line tools qui sont requis, pas toute l'app.

2016-10-14 23:17 UTC, sandhose commented on Makefile
> +	brew install gettext && \
Bah, pas spécialement que ça me perturbe, juste que c'est plus long (homebrew est assez lent comme ça, pas besoin de lui faire lancer N fois tout son truc d'init)

2016-10-14 23:19 UTC, sandhose commented
Pour le coup, j'vais ptêtre faire une vm macOS vierge pour tester ça vraiment *from scratch*, voir ce que ça donne

2016-10-15 08:00 UTC, GerardPaligot commented on doc/source/install/backend-os-x-install.rst
> +  xcode-select --install
J'ai laissé pour l'instant. Ca pourra être retiré si vous en avez pas eu besoin pendant la QA. (:

2016-10-15 08:00 UTC, GerardPaligot commented on doc/source/install/backend-os-x-install.rst
> +  brew install python --framework
J'ai laissé et donné un avertissement sur l'install de `pip`.

2016-10-15 08:01 UTC, GerardPaligot commented on doc/source/install/backend-os-x-install.rst
> +  make install-osx
Je comprends pas pourquoi ce commentaire n'a pas été fermé parce que cette commande a été déplacée.

2016-10-15 08:01 UTC, GerardPaligot commented on doc/source/install/backend-os-x-install.rst
> +  export PATH=/usr/local/bin:/usr/local/sbin:${PATH}
Malheureusement non. J'ai cherché longtemps avant de savoir pourquoi mon python utilisé n'était pas celui de Homebrew mais toujours celui du système.

2016-10-15 08:02 UTC, GerardPaligot commented
Vos retours ont été intégrés. @sandhose si tu as l'occasion de faire une QA sur un système clean, je suis preneur bien entendu ! (:

2016-10-15 08:34 UTC, vhf requested changes
Presque bon ! Ok pour le python de homebrew et l'avertissement sur `pip`.

2016-10-15 08:34 UTC, vhf commented on doc/source/install/backend-os-x-install.rst
> +- Si vous avez décidé de ne pas installer un nouveau python et que vous utilisez celui de base du système, installer pip :
`installez`

2016-10-15 08:34 UTC, vhf commented on doc/source/install/backend-os-x-install.rst
> +  # Il se peut que votre system n'utilise pas la nouvelle version de Python. Si c'est le cas, lancez la commande suivante.
`système`

2016-10-15 08:42 UTC, GerardPaligot commented
Done. Je veux pas dire mais l'install macOS est hyper light maintenant, c'est cool ! (:

2016-10-15 09:01 UTC, vhf commented on doc/source/install/backend-os-x-install.rst
> +  echo "source /usr/local/bin/virtualenvwrapper.sh" >> ~/.bash_profile && source /usr/local/bin/virtualenvwrapper.sh
Je suis toujours pas satisfait par ces exports alors qu'un source suffit. Est-ce que tu as vu mon commentaire hier ?

2016-10-15 09:05 UTC, vhf commented on doc/source/install/backend-os-x-install.rst
> +  echo "source /usr/local/bin/virtualenvwrapper.sh" >> ~/.bash_profile && source /usr/local/bin/virtualenvwrapper.sh
[Celui-ci](https://github.com/zestedesavoir/zds-site/pull/3854#discussion_r83492142)

2016-10-15 12:58 UTC, GerardPaligot commented on doc/source/install/backend-os-x-install.rst
> +  echo "source /usr/local/bin/virtualenvwrapper.sh" >> ~/.bash_profile && source /usr/local/bin/virtualenvwrapper.sh
Ah non.

> Ce que tu ne comprends pas c'est ce que font ces lignes (les 2 qui commencent par echo), ou c'est pourquoi elles sont pas optimales ?

Pourquoi elles ne sont pas optimales

2016-10-15 13:06 UTC, vhf commented on doc/source/install/backend-os-x-install.rst
> +  echo "source /usr/local/bin/virtualenvwrapper.sh" >> ~/.bash_profile && source /usr/local/bin/virtualenvwrapper.sh
Le but du bash_profile ou d'un bashrc c'est justement d'éviter à avoir à exporter ou sourcer ces trucs un par un dans le shell courant. Y'a pas d'intérêt à faire ça là manuellement, c'est des longues commandes, ça complique.

2016-10-15 13:19 UTC, GerardPaligot commented on doc/source/install/backend-os-x-install.rst
> +  echo "source /usr/local/bin/virtualenvwrapper.sh" >> ~/.bash_profile && source /usr/local/bin/virtualenvwrapper.sh
Tu voudrais faire quoi ?

```bash
echo "export WORKON_HOME=$HOME/.virtualenvs" >> ~/.bash_profile
echo "source /usr/local/bin/virtualenvwrapper.sh" >> ~/.bash_profile
source ~/.bash_profile
```

2016-10-15 13:27 UTC, vhf commented on doc/source/install/backend-os-x-install.rst
> +  echo "source /usr/local/bin/virtualenvwrapper.sh" >> ~/.bash_profile && source /usr/local/bin/virtualenvwrapper.sh
Ouais, c'est nettement plus simple et logique non ?

2016-10-15 13:34 UTC, GerardPaligot commented on doc/source/install/backend-os-x-install.rst
> +  echo "source /usr/local/bin/virtualenvwrapper.sh" >> ~/.bash_profile && source /usr/local/bin/virtualenvwrapper.sh
Ca me va très bien, je change ça.

2016-10-16 12:47 UTC, GerardPaligot commented
PR mise à jour.

2016-10-16 17:59 UTC, GerardPaligot commented
Ici, il manque plus que la QA de @sandhose ? Si oui, ça serait top de la faire rapidement. (:

2016-10-19 08:49 UTC, sandhose commented
C'est OK si ça se fait (au plus tard) que lundi prochain ?

2016-10-19 09:35 UTC, GerardPaligot commented
Aucun problème pour moi. (:

2016-10-25 09:38 UTC, GerardPaligot commented
@sandhose Tu as eu du temps ?
@vhf La review n'est toujours pas ok pour toi ?

2016-10-25 12:13 UTC, vhf approved these changes

2016-10-25 12:13 UTC, vhf commented
Si @GerardPaligot merci !

2016-10-28 21:37 UTC, vhf commented
Merci !

2016-10-28 21:37 UTC, merged