Ajout d'un bouton "nouveau sujet" dans l'accueil et d'un champ de catagorie dans le TopicForm
zestedesavoir/zds-site pull request #3863
Opened 2016-10-17 23:15 UTC by taoufik07

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | correction de bug / nouvelle fonctionnalité / évolution
| Ticket(s) (_issue(s)_) concerné(s)  | (ex #1337)

### QA

* Instruction 1 (ex : lancez `python manage.py migrate` et `npm run gulp build`)
* Instruction 2
* etc

2016-10-18 06:22 UTC, pierre-24 commented
J'ai du mal à comprendre exactement ce qui foire, mais pour commencer, j'ai l'impression que t'as rajouté à peu près la vue qu'il fallait, mais t'as pas édité [le formulaire qui allait avec](https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/forms.py#L17). D'où le fait que "section" existe pas, probablement (si je lis bien ce que Travis raconte).

2016-10-18 16:52 UTC, taoufik07 commented
En faite je l'ai nomme caregorie dans le formulaire

2016-10-18 16:54 UTC, taoufik07 commented
https://github.com/taoufik07/zds-site/commit/3b319272c544f99b35db271009a9e88f5026a300     scroll un peu et tu vas voir le nouveau champ dans TopicFrm

2016-10-18 17:17 UTC, pierre-24 commented
J'avais pas vu. 

Alors à mon avis, ce qui se passe, c'est que t'as pas encore modifié les tests pour envoyer ladite "section", et donc les tests plantent (semblerai que tu doivent chipoter pour faire comprendre à ton formulaire que quand on passe `?forum=pk`, il faut que ce forum soit sélectionné, sinon rien n'est sélectionné). Typiquement, il faudrait que tu rajoute quelques lignes dans la fonction [`clean()` du formulaire](https://github.com/taoufik07/zds-site/commit/3b319272c544f99b35db271009a9e88f5026a300#diff-749de4bb0278bfda580569fed2be642aR76) pour être sur que le champ "section" ne soit pas vide ou alors qu'il soit remplis avec la valeur de `request.GET['section']`. À toi de voir ce que tu imagines.

D'ailleurs, n'oublie pas d'écrire un petit test ;)

2016-10-18 17:42 UTC, taoufik07 commented
Ok, des que je rentre,  je verrai ce qui plante

2016-10-18 20:14 UTC, pierre-24 commented on .gitignore
> +settings.py
Ça, tu ne peux pas faire ;)

2016-10-18 20:16 UTC, pierre-24 commented on zds/settings.py
> +    #'zds.middlewares.ForceHttpsMembersMiddleware.ForceHttpsMembersMiddleware',
J'ai pas compris pourquoi tu as fais ça :)

2016-10-18 20:20 UTC, taoufik07 commented on .gitignore
> +settings.py
oui, parce que je travaille en locale donc j'ai fait quelques désactiver quelques middlewares  pour que ca fonctionne chez moi

2016-10-18 20:21 UTC, taoufik07 commented on zds/settings.py
> +    #'zds.middlewares.ForceHttpsMembersMiddleware.ForceHttpsMembersMiddleware',
je travaille en locale donc j'ai  désactivé quelques middlewares pour que ca fonctionne chez moi

2016-10-19 06:28 UTC, pierre-24 commented on zds/forum/forms.py
> +        section = cleaned_data.get('section')
Ça ne suffit pas. Comme tu as mis le champ en `required`, le code ne va même pas jusque là. La solution, pour moi, c'est de ne pas mettre de *required* sur le champ, et ici de faire : 

```
if not section:
    forum_pk = request.GET['forum']
    if not forum_pk:
        raise ...
```

2016-10-19 06:59 UTC, pierre-24 commented
Ok. Bon. 

À priori ton code fonctionne, je viens de tester vite fait. Sauf que ce qui me dérange et que j'arrivais pas à comprendre, c'est que les tests ne passent pas (et tant que t'as pas un petit "v" vers à coté de ton commit, la PR ne peut pas être mergée). Ce qui se passe, c'est qu'il faut que tu rajoute `"section": forum.pk` un peu partout dans les tests, par exemple [ici](https://github.com/taoufik07/zds-site/blob/dev/zds/forum/tests/tests_views.py#L337). Ça permettra de régler une partie des erreurs présentes dans [ce log](https://travis-ci.org/zestedesavoir/zds-site/jobs/168734576). 

Sinon, n'oublie pas d'enlever les commentaires que tu as rajouté. D'ailleurs, à priori, tu n'as pas créé de nouvelle branche pour faire tes modifications. `git checkout -b TA_BRANCHE upstream/dev` est la commande qui te permet de créer une branche spécifique à ton problème. Je te renvois vers [ce topic](https://zestedesavoir.com/forums/sujet/324/comment-contribuer-comprendre-comment-suivre-le-workflow/) pour plus d'informations :)

2016-10-19 11:20 UTC, taoufik07 commented
Les tests ne marchent pas parce que mes mofidications ont change le comportement du site.

2016-10-19 12:01 UTC, pierre-24 commented
> Les tests ne marchent pas parce que mes modifications ont change le comportement du site.

Ce qui est normal quand on implémente une nouvelle fonctionnalité. Mais du coup, il faut changer les tests en conséquences (et c'est ce que tu as fait, c'est très bien).

Alors, tu y es presque, à priori. D'une part, y'a un test qui passe pas encore (`FAIL: test_creation_topic (zds.notification.tests.NotificationForumTest)`), j'ai pas regardé pourquoi, d'autre part, il y a plusieurs erreurs de "formatage". En fait, on utilise un outil (flake8), qui vérifie qu'on respecte les "bonnes" règles de formatage de python. Dans ton cas,

```
./zds/settings.py:114:5: E265 block comment should start with '# '
./zds/settings.py:116:5: E265 block comment should start with '# '
./zds/forum/forms.py:85:1: W293 blank line contains whitespace
./zds/forum/views.py:188:1: E302 expected 2 blank lines, found 1
./zds/forum/views.py:202:1: W293 blank line contains whitespace
./zds/forum/views.py:213:1: W293 blank line contains whitespace
./zds/forum/views.py:218:121: E501 line too long (140 > 120 characters)
./zds/forum/views.py:220:1: W293 blank line contains whitespace
./zds/forum/views.py:232:30: E203 whitespace before ':'
./zds/forum/views.py:258:1: E302 expected 2 blank lines, found 1
./zds/forum/views.py:291:22: E203 whitespace before ':'
./zds/forum/views.py:309:34: E203 whitespace before ':'
./zds/forum/tests/tests.py:179:14: E121 continuation line under-indented for hanging indent
./zds/forum/tests/tests.py:181:14: E123 closing bracket does not match indentation of opening bracket's line
```

... Des erreurs d'indentations, des espaces en trop ou pas assez. Tu peux tester toi même que ton code est conforme avec `flake8 zds/` dans ton terminal préféré. On a pour principe de ne pas accepter de code qui ne passe pas ce test là, juste pour que tout le monde écrive plus ou moins pareil ;)

Et dernière chose, n'oublie pas d'enlever tes modifs à `settings.py` et `.gitignore`. 

Courage :)

2016-10-19 12:04 UTC, pierre-24 commented
Ah, non, j'ai encore oublié un truc. Il faut que tu rajoutes un test à toi pour tester la fonctionnalité que tu implémente: typiquement, le fait que tu puisses poster dans un forum comme ça, que l'oubli du paramètre `section` fait planter le machin, et que ce paramètre n'est pas redondant avec `?forum=xxx` (auquel cas, si je suis bien, il fait rien planter).

2016-10-19 12:14 UTC, GerardPaligot requested changes

2016-10-19 12:14 UTC, GerardPaligot commented on zds/forum/views.py
> +                return None
Si `forum_pk` est à `None`, il faut jetter une 404.

2016-10-19 12:14 UTC, GerardPaligot commented on zds/forum/views.py
> +            return None
Même chose, si le forum n'existe pas, c'est une 404.

2016-10-19 12:14 UTC, GerardPaligot commented on zds/forum/views.py
> +            self.object = self.get_object()
Si `self.object` est initialisé par `get_object`, comment sa valeur peut changer de `None` ?

2016-10-19 12:14 UTC, GerardPaligot commented on zds/forum/views.py
> +            self.object = get_object_or_404(Forum, pk=form.data['section'])
`self.object` n'est pas censé être le forum ?

2016-10-19 12:14 UTC, GerardPaligot commented on zds/forum/forms.py
> +    section = forms.ModelChoiceField(
Je ne comprends pas ce qu'est une section. On va devoir spécifier tout le temps le forum dans lequel nous sommes ?

2016-10-19 12:23 UTC, taoufik07 commented on zds/forum/forms.py
> +    section = forms.ModelChoiceField(
> Je ne comprends pas ce qu'est une section. On va devoir spécifier tout le temps le forum dans lequel nous sommes ?

Si on clique sur **"nouveau sujet"** depuis un forum le forum sera sélectionner automatiquement avec la possibilité de changer le forum sans devoir copier le text ouvrir une nouvelle onglet et cliquer sur **"Tous les sujet"** puis sur le bon forum et coller le text
Si on clique sur **"nouveau sujet"** depuis la page d'accueil l'utilisateur doit sélectionner le forum

2016-10-19 12:30 UTC, taoufik07 commented on zds/forum/views.py
> +            self.object = self.get_object()
il se peut que le forum soit  dans l'url si l'utilisateur a cliqué sur **"nouveau sujet"** depuis le forum => **get_object != None** ou bien aucun forum n'est spécifié s'il vient d'autre part => **get_object==None** et l'utilisateur  doit  le sélectionner manuellement

2016-10-19 12:32 UTC, taoufik07 commented on zds/forum/views.py
> +                return None
si forum_pk est à None je permet le choix d'un forum depuis le champ que j'ai ajouté

2016-10-19 12:35 UTC, GerardPaligot commented on zds/forum/views.py
> +                return None
Pourquoi ne pas avoir réutilisé le paramètre `forum` dans ce cas ?

2016-10-19 12:37 UTC, GerardPaligot commented on zds/forum/forms.py
> +    section = forms.ModelChoiceField(
Donc le bon forum est sélectionné automatiquement quand on vient des forums, c'est cool ça ! (:

2016-10-19 12:38 UTC, pierre-24 commented on zds/forum/forms.py
> +    section = forms.ModelChoiceField(
Rien à voir, mais hier quand j'ai fait le test avec ton code, ce fameux bouton "nouveau sujet" n'était pas encore présent sur la page des forums ;) (tu l'as peut être rajouté depuis).

2016-10-19 12:39 UTC, taoufik07 commented on zds/forum/views.py
> +            return None
Oui, oui
par exemple on forum_pk =  X et x est un entier valide mais le forum n'existe pas au lieu de 404 je laisse le champ catégorie(section) vide

2016-10-19 12:40 UTC, taoufik07 commented on zds/forum/forms.py
> +    section = forms.ModelChoiceField(
nn il existe depuis toujours

2016-10-19 12:41 UTC, taoufik07 commented on zds/forum/views.py
> +                return None
??

2016-10-19 12:42 UTC, pierre-24 commented on zds/forum/forms.py
> +    section = forms.ModelChoiceField(
Me suis mal exprimé. Effectivement, il est en page d’accueil, mais pourquoi pas aussi sur la page de la liste des forums, du coup ? ([celle là, donc](https://zestedesavoir.com/forums/))

2016-10-19 12:44 UTC, taoufik07 commented on zds/forum/forms.py
> +    section = forms.ModelChoiceField(
Give that man a jar of cookies !!
je vais le faire

2016-10-19 13:00 UTC, GerardPaligot commented on zds/forum/views.py
> +                return None
J'ai besoin d'une information en prérequis à cette information. Si je comprends bien, nous avons un paramètre GET `forum` et un autre paramètre POST `section` mais pour la même information. C'est bien ça ?

2016-10-19 13:25 UTC, taoufik07 commented on zds/forum/views.py
> +                return None
oui

2016-10-19 13:51 UTC, vhf requested changes
Merci pour cette PR ! Quelques remarques cosmétiques pour ma part.

2016-10-19 13:51 UTC, vhf commented on zds/forum/forms.py
> +        label=_("Categorie"),
```diff
-        label=_("Categorie"),
+        label=_(u'Catégorie'),
```

2016-10-19 13:51 UTC, vhf commented on zds/forum/tests/tests.py
> +                'section': self.forum12.pk
```diff
-                'section': self.forum12.pk
+                'section': self.forum12.pk,
```

2016-10-19 13:51 UTC, vhf commented on zds/forum/tests/tests.py
> +             'section': 'abc'
```diff
-             'section': 'abc'
+             'section': 'abc',
```

2016-10-19 13:51 UTC, vhf commented on zds/forum/tests/tests.py
> +             'section': 'abc'
```diff
-             'section': 'abc'
+             'section': 'abc',
```

2016-10-19 13:51 UTC, vhf commented on zds/forum/tests/tests.py
> +                'section': self.forum11.pk
```diff
-                'section': self.forum11.pk
+                'section': self.forum11.pk,
```

2016-10-19 13:51 UTC, vhf commented on zds/forum/tests/tests.py
> +                'section': self.forum12.pk
```diff
-                'section': self.forum12.pk
+                'section': self.forum12.pk,
```

2016-10-19 13:51 UTC, vhf commented on zds/forum/tests/tests_views.py
> +            'section': forum.pk
```diff
-            'section': forum.pk
+            'section': forum.pk,
```

2016-10-19 13:51 UTC, vhf commented on zds/forum/tests/tests_views.py
> +            'section': forum.pk
```diff
-            'section': forum.pk
+            'section': forum.pk,
```

2016-10-19 13:51 UTC, vhf commented on zds/forum/tests/tests_views.py
> +            'section': forum.pk
```diff
-            'section': forum.pk
+            'section': forum.pk,
```

2016-10-19 13:51 UTC, vhf commented on zds/forum/tests/tests_views.py
> +            'section': forum.pk
```diff
-            'section': forum.pk
+            'section': forum.pk,
```

2016-10-19 13:51 UTC, vhf commented on zds/forum/tests/tests_views.py
> +            'section': forum.pk
```diff
-            'section': forum.pk
+            'section': forum.pk,
```

2016-10-19 13:51 UTC, vhf commented on zds/forum/tests/tests_views.py
> +            'section': forum.pk
```diff
-            'section': forum.pk
+            'section': forum.pk,
```

2016-10-19 13:51 UTC, vhf commented on zds/forum/tests/tests_views.py
> +            'section': forum.pk
```diff
-            'section': forum.pk
+            'section': forum.pk,
```

2016-10-19 13:51 UTC, vhf commented on zds/notification/tests.py
> +                'section': self.forum12.pk
```diff
-                'section': self.forum12.pk
+                'section': self.forum12.pk,
```

2016-10-19 14:00 UTC, taoufik07 commented on zds/notification/tests.py
> +                'section': self.forum12.pk
Merci, je vais les appliquées :)

2016-10-19 14:27 UTC, taoufik07 commented on zds/notification/tests.py
> +                'section': self.forum12.pk
done ;)

2016-10-19 14:37 UTC, GerardPaligot commented on zds/forum/views.py
> +                return None
Est-ce qu'il n'y aurait pas moyen de nommer `section` du POST en `forum` et de gérer le paramètre par `self.request.REQUEST.get('forum')` pour quelque chose de transparent ?

2016-10-19 14:45 UTC, taoufik07 commented on zds/forum/views.py
> +                return None
oui, je peux nommer **section** en **forum**

2016-10-19 14:51 UTC, vhf commented on zds/notification/tests.py
> +                'section': self.forum12.pk
T'en as oublié quelques-uns, regarde ici: https://github.com/zestedesavoir/zds-site/pull/3863#pullrequestreview-4873033

Les commentaires qui s'affichent encore sont ceux que tu n'as pas pris en compte. :)

Les commentaires pris en compte portent un "_Show outdated_" à droite sur la ligne.

2016-10-19 14:55 UTC, GerardPaligot commented on zds/forum/views.py
> +                return None
Cool parce que j'ai mis du temps avant de comprendre que c'était la même chose. Pour la maintenance, ça sera bien mieux.

2016-10-19 17:47 UTC, taoufik07 commented on zds/notification/tests.py
> +                'section': self.forum12.pk
maintenant je vois et maintenant ?

2016-10-19 19:42 UTC, vhf commented on zds/notification/tests.py
> +                'section': self.forum12.pk
<img width="678" alt="screen shot 2016-10-19 at 21 41 29" src="https://cloud.githubusercontent.com/assets/2022803/19534627/d8d3bddc-9644-11e6-8f0c-4005819bd071.png">

T'es super, merci ! :)

2016-10-19 19:42 UTC, vhf approved these changes

2016-10-19 21:20 UTC, taoufik07 commented on zds/notification/tests.py
> +                'section': self.forum12.pk
merci à vous aussi :)

2016-10-20 17:22 UTC, taoufik07 commented
Dans ces derniers commits ([d40ad4a](https://github.com/zestedesavoir/zds-site/pull/3863/commits/d40ad4ae36c3223594a5bdde3fe5f6153c31e44b),  	[13a71fc](https://github.com/zestedesavoir/zds-site/pull/3863/commits/13a71fcad1f259edac8c17fec2242c49bbe04359), [07be3da](https://github.com/zestedesavoir/zds-site/pull/3863/commits/07be3dab4cebc01f2b147d1b2c63e02ab0d9b39c), 	[61dec8e](https://github.com/zestedesavoir/zds-site/pull/3863/commits/61dec8e6704e11a3cb871083268ed4f49f7d9d78), [e08db85](https://github.com/zestedesavoir/zds-site/pull/3863/commits/e08db8528cc4164ab9ba4679676dd6c0c3812b29), [4868bdc](https://github.com/zestedesavoir/zds-site/pull/3863/commits/4868bdc9750a4fe2b4d6b632038bddc36178f802)), j'ai accompli :

1. Renommer le champ **"section"**(catégorie)  en **"forum"**(catégorie)  ( Merci @GerardPaligot ).
2. Ecriture des tests.
3. Ajout du bouton **"nouveau sujet"** dans la page _zds.com/forums/{{forum}}/_ (Merci @pierre-24 ).
4. Exclusion des forums sans permission de lecture dans le champ **"forum"**(catégorie) .

A faire :

1. Modification du style du champ **"forum"**(catégorie).

Si vous avez des remarques ou autres modifications n’hésiter pas à me le dire :wink:.

2016-10-20 17:37 UTC, pierre-24 requested changes

2016-10-20 17:37 UTC, pierre-24 commented on zds/forum/tests/tests.py
> +             'forum': 'abc',
si tu met `'?forum=abc'``en paramètre GET, est ce que tu as besoin de préciser le POST ? (vraie question)

2016-10-20 17:37 UTC, pierre-24 commented on zds/forum/tests/tests.py
> +             'forum': 'abc',
Là, il me semble que tu court-circuite le test, qui est "si on précise rien en GET, ça doit planter". C'est même pas forcément logique que tu te prenne une 404 ici, si ?

2016-10-20 17:37 UTC, pierre-24 commented on zds/forum/tests/tests.py
> +        self.assertEqual(result.status_code, 200)
... Et là, c'est encore moins logique pour moi: pourquoi tu te prend une 200 si tu ne précise aucune des 2? Au mieux ça devrait être une 404, au pire une 302, non ?

2016-10-20 17:37 UTC, pierre-24 commented on zds/forum/tests/tests_views.py
> +    # By me,
Pas de commentaires inutiles ;)

2016-10-20 17:37 UTC, pierre-24 commented on zds/forum/tests/tests_views.py
> +        response = self.client.get(reverse('topic-new') + '?forum={}'.format(178903))
tu devrait tester en `follow=False` et probablement obtenir une 302.

2016-10-20 17:37 UTC, pierre-24 commented on zds/forum/tests/tests_views.py
> +        self.assertEqual(302, response.status_code)
Ce test devrait ce terminer en comptant le nombre de topic avant et après ton ajout, pour assurer le ledit topic a bien été créé (`self.assertEqual(Topic.objects.all().count(), xxx)`)

2016-10-20 17:37 UTC, pierre-24 commented on .gitignore
> +settings.py
Tu n'as pas enlevé ça :-)

2016-10-20 17:37 UTC, pierre-24 commented on zds/forum/forms.py
> +        self.fields['forum'].queryset = Forum.objects.exclude(group__in=Group.objects.filter(user=self.user).all())
Bien vu ;)

2016-10-20 17:47 UTC, taoufik07 commented on zds/forum/tests/tests.py
> +             'forum': 'abc',
Non,

2016-10-20 17:49 UTC, taoufik07 commented on zds/forum/tests/tests.py
> +             'forum': 'abc',
C'est ce qui se passe

2016-10-20 17:51 UTC, taoufik07 commented on zds/forum/tests/tests.py
> +        self.assertEqual(result.status_code, 200)
Si je ne précise aucune des deux je laisse le choix à l'utilisateur de sélectionner un forum depuis le champ.
( Je pense que je vais faire de même si forum=LEVIDE )

2016-10-20 17:53 UTC, taoufik07 commented on zds/forum/tests/tests_views.py
> +    # By me,
Désolé

2016-10-20 17:56 UTC, pierre-24 commented on zds/forum/tests/tests.py
> +        self.assertEqual(result.status_code, 200)
Ah, oui, juste. Là, je t'autorise à mettre un commentaire, parce que c'est pas évident :)

2016-10-20 17:57 UTC, taoufik07 commented on zds/forum/tests/tests.py
> +             'forum': 'abc',
Retourne un 404

2016-10-20 17:59 UTC, taoufik07 commented on zds/forum/tests/tests.py
> +             'forum': 'abc',
Si on précise rein en GET, ça doit laissé le choix à l'utilisateur, je vais le corriger

2016-10-20 18:01 UTC, pierre-24 commented on zds/forum/tests/tests.py
> +             'forum': 'abc',
Oui. Et même remarque au dessus, du coup !

2016-10-20 18:03 UTC, taoufik07 commented on zds/forum/tests/tests.py
> +        self.assertEqual(result.status_code, 200)
Oui capitaine !

2016-10-20 18:03 UTC, taoufik07 commented on zds/forum/tests/tests.py
> +             'forum': 'abc',
Yep

2016-10-20 19:11 UTC, taoufik07 commented on zds/forum/tests/tests_views.py
> +        response = self.client.get(reverse('topic-new') + '?forum={}'.format(178903))
en faite si le pk est un int qui n'existe pas dans la bd je laisse le champ vide sans faire aucune redirection, si vous pensez qu'une redirection c'est mieux je la ferai

2016-10-20 19:13 UTC, pierre-24 commented on zds/forum/tests/tests_views.py
> +        response = self.client.get(reverse('topic-new') + '?forum={}'.format(178903))
Je suis partagé ... @vhf ? Est ce qu'on lève une erreur ou pas ?

2016-10-20 19:14 UTC, pierre-24 commented on zds/forum/tests/tests_views.py
> +        response = self.client.get(reverse('topic-new') + '?forum={}'.format(178903))
et @GerardPaligot ? (qui connait bien le module)

2016-10-20 21:59 UTC, taoufik07 commented on zds/forum/views.py
> +                return None
C'est fait  :)

2016-10-20 23:29 UTC, taoufik07 commented on zds/forum/tests/tests_views.py
> +        self.assertEqual(302, response.status_code)
C'est fait

2016-10-21 06:43 UTC, pierre-24 approved these changes

2016-10-25 20:25 UTC, GerardPaligot requested changes

2016-10-25 20:25 UTC, GerardPaligot commented on zds/forum/forms.py
> +        self.fields['forum'].queryset = Forum.objects.exclude(group__in=Group.objects.filter(user=self.user).all())
Cette vérification ne semble pas être faite à la soumission du formulaire. Il serait donc possible de créer des sujets dans des forums privés si on ne soumet pas par le site.

2016-10-25 20:25 UTC, GerardPaligot commented on zds/forum/views.py
> +        if self.object is not None:
Dans la mesure où nous appelons `self.get_object()` dans la méthode `dispatch`, je ne comprends toujours pas ces 3 lignes. Comment pouvons-nous récupérer un résultat la deuxième fois pour une même requête ?

2016-10-25 20:25 UTC, GerardPaligot commented on zds/forum/views.py
> +            self.object = get_object_or_404(Forum, pk=form.data['forum'])
Simple question : Est-ce que `form.data['forum']` peut-il aussi être accédé par `request.POST['forum']` dans ce cas ci ?

2016-10-26 17:32 UTC, taoufik07 commented on zds/forum/views.py
> +        if self.object is not None:
mm, vous avez raison, je vais supprimer les lignes 221 et 222

2016-10-26 19:22 UTC, taoufik07 commented on zds/forum/views.py
> +            self.object = get_object_or_404(Forum, pk=form.data['forum'])
j'ai pas bien compris

2016-10-28 16:45 UTC, taoufik07 commented on zds/forum/forms.py
> +        self.fields['forum'].queryset = Forum.objects.exclude(group__in=Group.objects.filter(user=self.user).all())
Je pense pas que c'est une verfication, elle permet juste de filtrer la liste des forums en se basant sur la permission de lecture, la vraie verification se fait dans la vue

2016-11-20 17:09 UTC, GerardPaligot commented
Avant la QA, @taoufik07 pourrais-tu rebase pour être certain de tester une version mergeable et sans risque de régression entre maintenant et le rebase ?

Merci beaucoup ! (:

2017-09-02 19:38 UTC, gcodeur commented
@taoufik07 : es-tu toujours intéressé par cette pull request ?

2017-09-30 19:53 UTC, sandhose commented
Étant donné l'absence de réponse, je ferme la PR. Si tu veux la reprendre, n'hésites pas à la ré-ouvrir.

2017-09-30 19:56 UTC, closed without merging