Fix bug on no tag
zestedesavoir/zds-site pull request #3875
Opened 2016-10-19 20:09 UTC by artragis

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | correction de bug 
| Ticket(s) (_issue(s)_) concerné(s)  | (j'ai pas encore créé, c'est une alerte sentry)

### QA

* créez un tuto
* ne lui donnez pas de tag
* vérifiez que ça bug pas et que le tuto est créé sans ses tags.

2016-10-19 20:32 UTC, pierre-24 commented
Je crois que ça ira : 

![screenshot from 2016-10-19 22 32 14](https://cloud.githubusercontent.com/assets/7889675/19536352/f37d4458-964b-11e6-823f-35e4a3de6bc2.png)

2016-10-19 20:44 UTC, GerardPaligot commented
Je voudrais être chiant, je dirais qu'il manque un TU. (:

2016-10-19 20:47 UTC, pierre-24 commented
Je suis d'accord ;)

2016-10-19 21:32 UTC, vhf commented
Merci @artragis . Outre le test manquant, j'ai quelques questions : 

* Est-ce que ce bug a été introduit par cette release ou est-il antérieur ?
* Ne vaudrait-il pas mieux modifier [cette ligne](https://github.com/artragis/zds-site/commit/d8c34257f75e845054cdcd1dbb7bb776ba3f31a4#diff-ec82b3a079c8b6115716953cfd70ad93R70) pour y mettre …`(raw_string=''):` ?
* S'il n'y a que ce bug mineur dans la RC4, est-ce que vous seriez contre faire cette PR sur `dev` pour s'éviter une 5e RC ?

2016-10-20 05:33 UTC, artragis commented
Etant donné que je l'ai introduit, j'ai la casi certitude que oui c'est 
du pur v20.


Le 19/10/2016 à 23:32, victor felder a écrit :
>
> Merci @artragis <https://github.com/artragis> . Outre le test 
> manquant, j'ai quelques questions :
>
>   * Est-ce que ce bug a été introduit par cette release ou est-il
>     antérieur ?
>   * Ne vaudrait-il pas mieux modifier cette ligne
>     <https://github.com/artragis/zds-site/commit/d8c34257f75e845054cdcd1dbb7bb776ba3f31a4#diff-ec82b3a079c8b6115716953cfd70ad93R70>
>     pour y mettre …|(raw_string=''):| ?
>   * S'il n'y a que ce bug mineur dans la RC4, est-ce que vous seriez
>     contre faire cette PR sur |dev| pour s'éviter une 5e RC ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/3875#issuecomment-254947272>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xa-lTVg_KylznqtLNYaS0rnFz5zdks5q1ox_gaJpZM4KbZo_>.
>

2016-10-20 15:08 UTC, pierre-24 commented
On en profiterai pas pour rajouter  #3880 ?

2016-10-20 19:00 UTC, vhf commented
Je pense qu'il vaut la peine d'en profiter pour retravailler un peu ce validateur de tag et la pertinence des messages qu'il retourne.

Exemple de logique [ici](https://github.com/vhf/zds-site/commit/34dbd973ac44c0476187b02ef53fa8b6bab7062d). Comme ça on dit à l'utilisateur directement quels tags sont trop longs, et on lui dit aussi quand un ou des tags, et le cas échéant le ou lesquels, contiennent des caractères pas autorisés. C'est mieux que de les virer sans avertir.

2016-10-20 19:06 UTC, pierre-24 commented
Je suis d'accord. Après, faut voir si on veut ça pour le bugfix ou pour plus tard

2016-10-20 19:10 UTC, vhf commented
Je pense que vu que le gros du travail est fait et qu'il manque juste l'intégration un peu plus propre du brouillon dont je donne le lien, y a pas de raison de pas faire passer le tout ici.

2016-10-21 07:19 UTC, vhf requested changes
- intégrer la validation utf8 au validateur de tags.

2016-10-21 07:19 UTC, vhf commented on zds/tutorialv2/forms.py
> +        # because tags are not mandatory
Commentaire inutile.

2016-10-21 07:19 UTC, vhf commented on zds/utils/tests/tests_models.py
> +    def test_validator(self):
Ce test n'est pas bon. Une implémentation évidente de la méthode testée ici serait `def validate_raw_string(): return True`

2016-10-21 12:14 UTC, artragis commented
utf8mb4 validé + refonte du validateur pour que ça soit beau et pythonique.

2016-10-21 12:18 UTC, vhf approved these changes

2016-10-21 12:18 UTC, vhf commented
Merci @artragis ! @pierre-24 quand t'es motiv, QA ?

@GerardPaligot tu vois d'autres trucs à régler pour la v20 ou je peux RC ?

2016-10-21 12:29 UTC, pierre-24 commented
Tout dépend à quel point tu considère #3842 comme bloquant :)

2016-10-21 12:47 UTC, pierre-24 commented
QA: NOK!

+ Si je met pour tags "test,😄", j'obtient "object of type 'function' has no len()" dans 
"zds/utils/forms.py in validate_length" (à la ligne 85). Ça, c'est parce que `_` n'est pas défini dans la fonction.
+ Mettons que je mette `raw_string` à la place de ce fameux `_`, eh bien j'ai les deux erreurs, dont la première 2 fois:
    ![screenshot from 2016-10-21 14 38 29](https://cloud.githubusercontent.com/assets/7889675/19598628/12e1dfce-979c-11e6-81b6-ee59b9096353.png)

    En même temps, [la ligne 93](https://github.com/zestedesavoir/zds-site/pull/3875/files#diff-ec82b3a079c8b6115716953cfd70ad93R93) fait **tout** les tests sur **tout** les tags. Donc forcément, on se tape toutes les erreurs à la suite.  Si c'est ce que tu recherches, alors précise quel tag est fautif dans l'erreur :)
+ Et en fait, la logique de la ligne `if len(_) <= Tag._meta.get_field("title").max_length:` est à l'envers, ça devrait être `>=` (d'où les erreurs "le tag est trop long").
+ Sinon, j'ai toujours bien "Assurez-vous que cette valeur comporte au plus 64 caractères (actuellement 599).", donc ça, c'est bon !

2016-10-21 13:14 UTC, vhf commented
Je comprends pas pourquoi travis est pas passé par ici.

2016-10-21 13:24 UTC, pierre-24 commented
Parce qu'il semblerai [qu'internet soit cassé](https://twitter.com/ow/status/789454135456333824).

2016-10-21 15:23 UTC, artragis commented
logically fixed

2016-10-21 15:44 UTC, pierre-24 commented on zds/utils/forms.py
> +        if len(raw_string) <= Tag._meta.get_field("title").max_length:
T'as oublié d'inverser la  condition ;)

2016-10-21 15:45 UTC, pierre-24 commented on zds/utils/forms.py
> +        if len(raw_string) <= Tag._meta.get_field("title").max_length:
... Et si les erreurs doivent ce suivre, il faudrait les faire finir par `.` (avec un espace après le point)

2016-10-22 11:55 UTC, vhf requested changes

2016-10-22 11:55 UTC, vhf commented on zds/utils/forms.py
> +            return self.validate_string_list([])
Pourquoi pas `return True` ?

2016-10-22 11:55 UTC, vhf commented on zds/utils/tests/tests_models.py
> +        raw_string = u"☢☢☢☢☢☢,bla"
Remplace `☢` par `🐙`. Le premier est pas utf8mb4, le second l'est. On peut pas vraiment éviter ça malheureusement.

2016-10-22 13:37 UTC, artragis commented on zds/utils/forms.py
> +            return self.validate_string_list([])
question d'évolutivité : si demain pour une raison aussi saugrenue soit-elle on décide qu'une liste vide est invalide ça retournera false.
De plus c'est juste ici de la sémantique "si tu mets None ou autre chose qu'un string, on le considère comme un string vide".

2016-10-22 13:45 UTC, pierre-24 commented
QA OK. On est parti :)

2016-10-22 13:47 UTC, merged

2016-10-25 19:01 UTC, artragis commented
il faudra donc attendre demain que je m'y mette dans des bonnes conditions.


Le 20/10/2016 à 21:00, victor felder a écrit :
>
> Je pense qu'il vaut la peine d'en profiter pour retravailler un peu ce 
> validateur de tag et la pertinence des messages qu'il retourne.
>
> Exemple de logique ici 
> <https://github.com/vhf/zds-site/commit/34dbd973ac44c0476187b02ef53fa8b6bab7062d>. 
> Comme ça on dit à l'utilisateur directement quels tags sont trop 
> longs, et on lui dit aussi quand un ou des tags, et le cas échéant le 
> ou lesquels, contiennent des caractères pas autorisés. C'est mieux que 
> de les virer sans avertir.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/3875#issuecomment-255197394>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xSyCuknXpwtbZFFVx86W0Q99CntKks5q17pqgaJpZM4KbZo_>.
>

2016-10-25 19:03 UTC, vhf commented
Je suis pas sûr de savoir de quoi tu parles @artragis, mais si c'est à propos de #3895 rien d'urgent, a priori ce sera pour la v21.

2016-10-25 19:07 UTC, artragis commented
hum, on appelle ça le cache de thunderbird qui finit par se réveiller dès que la connexion est stable il semblerait. Car ce message je l'ai envoyé non pas il y a cinq minutes mais il y a plusieurs jours.

Les problèmes récents de DNS sont peut être en cause.