Marque le MP de réservation du staff comme lue.
zestedesavoir/zds-site pull request #3885
Opened 2016-10-21 21:36 UTC by GerardPaligot

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | correction de bug
| Ticket(s) (_issue(s)_) concerné(s)  | #3842 

### QA

* Réservez un contenu en validation
* Constatez un MP marqué comme lu.

2016-10-21 21:38 UTC, pierre-24 commented
..  Tout simplement ^^

2016-10-21 22:54 UTC, vhf requested changes
Est-ce que tu peux en profiter pour faire un search and replace de `never_privateread` dans toute la codebase pour utiliser un nom explicite ?

Je suppose que cette function vérifie qu'un `PrivateTopic` n'a pas été lu par un utilisateur ? Si oui, quelque chose comme `is_privatetopic_unread` ?

2016-10-21 22:54 UTC, vhf commented on zds/tutorialv2/tests/tests_views.py
> +        # Check that the staff haven't a notification for its reservation and the private topic should be read.
Je suppose que ça veut dire ça :

> Check that the staff user doesn't have a notification for their notification and their private topic is read.

C'est juste ?

2016-10-22 17:05 UTC, GerardPaligot commented on zds/tutorialv2/tests/tests_views.py
> +        # Check that the staff haven't a notification for its reservation and the private topic should be read.
Ma phrase n'est pas bonne ?

2016-10-22 17:23 UTC, vhf commented on zds/tutorialv2/tests/tests_views.py
> +        # Check that the staff haven't a notification for its reservation and the private topic should be read.
Non.

* `the staff haven't a notification` est incompréhensible, soit il manque un verbe (`the staff haven't baked a cake`) soit le pluriel est faux et au singulier ça donnerait `the staff user has no cake` ou `the staff user doesn't have a cake`
* `for its reservation` le staff n'est pas un objet
* `the private topic should be read` ici `should` n'est pas cohérent avec le verbe de modalité précédent

2016-10-23 19:59 UTC, GerardPaligot commented
Commentaire updated.

2016-10-24 17:56 UTC, vhf commented
@GerardPaligot, des nouvelles ici ? Tu as le temps de t'en occuper ?

2016-10-24 19:18 UTC, GerardPaligot commented
J'aime pas les refactos pour le bug fix mais tu semblais y tenir. Par contre, PyCharm est vraiment naze pour le refacto des méthodes dans les templates alors je mesure pas bien les effets de bord.

2016-10-24 19:26 UTC, vhf approved these changes

2016-10-24 21:10 UTC, pierre-24 commented
> J'aime pas les refactos pour les bug fix mais tu semblais y tenir. 

Moi non plus, du coup j'ai été tester un peu partout. Le fait que les tests passent me rassure aussi.

Bref. QA OK, on avance !

2016-10-24 21:10 UTC, merged

2016-10-25 18:25 UTC, firm1 commented
Je pense que pour le coup le comportement n'est pas très logique. Pourquoi
marquer un MP lu alors que ce n'est pas le cas ?
J'ai presque l'impression que l'on essaye de transformer la réalité pour ne
pas avoir a résoudre le problème technique.

Dans ce cas, on peut se poser la question "A quoi sert ce MP ?" s'il n'est
même pas destiné a être lu ?

Le ven. 21 oct. 2016 23:50, Coveralls notifications@github.com a écrit :

> [image: Coverage Status] https://coveralls.io/builds/8454265
> 
> Coverage increased (+0.002%) to 87.619% when pulling _941dac4
> https://github.com/zestedesavoir/zds-site/commit/941dac4f5c39923aac6167abff8c6441f1a130c0
> on GerardPaligot:fix_3842_ into _c84d091
> https://github.com/zestedesavoir/zds-site/commit/c84d0919e2f53ab2834d576389306389e99e87aa
> on zestedesavoir:release-v20_.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/zestedesavoir/zds-site/pull/3885#issuecomment-255473998,
> or mute the thread
> https://github.com/notifications/unsubscribe-auth/AFyPX8iR3hx__5lTtaDZ6dcBcyIznvqHks5q2TOwgaJpZM4KdnHt
> .

2016-10-25 18:31 UTC, vhf commented
@firm1 peux-tu stp copier-coller ton message ici #3842

2016-10-25 19:01 UTC, GerardPaligot commented
@firm1 Il n'y a **aucun problème technique**. La solution est tout aussi simple pour la génération d'une notification que pour la mise en lecture automatique du MP.

D'ailleurs, dans le [premier message de ton issue](https://github.com/zestedesavoir/zds-site/issues/3842), tu proposes les 2 solutions et tu ne reviens plus vers nous malgré [ma relance](https://github.com/zestedesavoir/zds-site/issues/3842#issuecomment-254050056).

Mais comme d'habitude, tu viens après comme un cheveu sur la soupe une fois que la solution est fusionnée dans le dépôt (ici même dans la dernière RC) ou au dernier moment quand la personne chargée de la QA est sur le point de fusionner et c'est chiant. **Vraiment**.

Pour répondre à ta question : Ce MP est surtout destiné aux auteurs qui sont informés que leur contenu est réservé. Le membre du staff lui sait déjà qu'il a réservé le contenu alors pourquoi le notifier ?

2016-10-25 19:08 UTC, pierre-24 commented
Par contre, et puisqu'il s'agit du MP de suivit, il pourra être réemployé par le validateur pour faire par de ces remarques et communiquer avec l'auteur, d'ou le fait qu'il soit utile de le conserver.

2016-10-25 19:35 UTC, vhf commented
Les questions posées ici par @firm1 sont de bonnes questions, comme toutes les questions. Ça a permis à @GerardPaligot d'y apporter une réponse convaincante. Cette réponse documente le choix fait dans cette PR.

Par contre @GerardPaligot ça va pas de s'énerver comme ça, va prendre l'air avant de répondre la prochaine fois.

2016-10-25 19:38 UTC, GerardPaligot commented
@vhf Haha. (':

2016-10-26 09:37 UTC, firm1 commented
Ah je m'excuse, j'ai rédigé mon message il y'a belle lurette, le jour ou la PR a été envoyée. Mais il est parti un peu trop tard visiblement.

Pour ma défense ta relance n'était pas vraiment une (y'avait pas de question pour moi) :) 

Mais sur le fond du problème, ça ne me parait pas logique d'avoir une notification qui passe non lue toute seule. On ne la remarque pas en tant que valido, ce qui nous pousse à aller créer un nouveau topic plutot que d'utiliser ce MP déjà existant.