Trie les tutoriels qui ont besoin d’aide par date de mise à jour
zestedesavoir/zds-site pull request #3899
Opened 2016-10-26 14:01 UTC by Karnaj

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | évolution
| Ticket(s) (_issue(s)_) concerné(s)  | #2872

### QA

- Créer plusieurs tutoriels avec une demande d’aide (deux devraient suffire). 
- Vérifier que les tutoriels sont bien triés par ordre chronologique sur la page d’aide.

2016-10-26 15:19 UTC, vhf requested changes
Cool ! Il va falloir rebaser sur `dev` pour que les tests travis passent.

2016-10-26 15:19 UTC, vhf commented on zds/tutorialv2/views/views_contents.py
> +            .order_by('-update_date')
Est-ce que tu peux mettre `order_by` avant `all` stp ?

2016-10-27 16:32 UTC, Karnaj commented
Mon test ne passe pas, mais tout me semble correct. Quelqu’un voit le problème ?

2016-10-27 17:44 UTC, vhf commented on zds/tutorialv2/tests/tests_views.py
> +        )
D'après travis: 

`./zds/tutorialv2/tests/tests_views.py:2631:10: W291 trailing whitespace`

2016-10-27 22:36 UTC, Karnaj commented on zds/tutorialv2/tests/tests_views.py
> +        )
Oui, mais il y a aussi [cette assertion][https://github.com/Karnaj/zds-site/blob/c0433fbea3be63036f33b7880e6c2d7eaad46186/zds/tutorialv2/tests/tests_views.py#L2634) qui ne passe pas avec l’erreur `AssertionError: <PublishableContent: Mon contenu No92> != <PublishableContent: Mon contenu No91>`.

2016-10-27 22:40 UTC, vhf requested changes

2016-10-27 22:40 UTC, vhf commented on zds/tutorialv2/tests/tests_views.py
> +        an_help = HelpWritingFactory()
"a_help" en anglais, pas "an_help" ;)

2016-10-27 22:41 UTC, vhf commented on zds/tutorialv2/tests/tests_views.py
> +        an_help = HelpWritingFactory()
Tu peux aussi remplacer "tutoriels" par "tutorials" dans le commentaire de la ligne précédente.

2016-10-30 14:56 UTC, pierre-24 commented
Ton propre test ne passe pas :)

2016-10-30 15:16 UTC, Karnaj commented
Et je ne vois pas pourquoi. Normalement, ils sont bien triés par date de mise à jour, donc quand j’échange les dates de mise à jour des deux tutoriels dans mon test, l’ordre devrait être changé.

2016-10-30 21:41 UTC, pierre-24 commented
Oh, j'ai trouvé. Ça, c'est vicieux. En fait, `update_date` [est changé par la méthode `save()`](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/models/models_database.py#L146). 

Du coup ton test peut difficilement fonctionner. En fait, je crois que la seule méthode pour faire ça convenablement, c'est un `sleep(2)` entre les `save()` pour être sur. Je suis évidement pas fan, mais j'ai pas de meilleure idée à cette heure-ci.

2016-10-30 21:42 UTC, pierre-24 commented
Preuve que c'est plus l'heure que je réfléchisse, il suffit de passer `update_date=False` au `save()`. Et ça doit fonctionner :)

2016-10-30 22:12 UTC, Karnaj commented
Super, ça corrige bien le problème. Le test restant qui ne passe pas est lié à [cette issue](https://github.com/zestedesavoir/zds-site/issues/3924)

2016-11-01 08:54 UTC, pierre-24 commented
QA: OK ici :)

2016-11-01 08:54 UTC, merged