Nouvelle version markdown
zestedesavoir/zds-site pull request #3945
Opened 2016-11-06 21:27 UTC by cgabard

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | correction de bug
| Ticket(s) (_issue(s)_) concerné(s)  | -

### QA

Beaucoup de modifications mais pas d'évolutions, seulement (beaucoup) de corrections de bugs !  Ne pas hésiter à un peu tout vérifier.

2016-11-07 09:55 UTC, GerardPaligot commented
Congrats @cgabard pour ce taff ! J'ai hâte de débloquer du temps pour développer le ping.

Tu aurais une doc technique quelque part pour l'usage du ping dans zds-site ?

2016-11-07 10:02 UTC, cgabard commented
Je ne sais pas trop comment quels fonctions sont utilisés par qui dans zds-site mais en soit il faut : 

 - passer au markdown une fonction `is_pingeable` qui doit renvoyer `True/False` si le nom d'utilisateur peut être la cible d'un ping. Je l'ai propagé un peu partout dans le fichier "emarkdown". Reste a savoir "où" on va limiter le ping : forum uniquement ? Contenu aussi ? Bref il faut que le paramètre ne soit pas à `None` quand on veut permettre le ping
 - Après le traitement, la fonction `render_markdown` appel une fonction `process_pings` que j'ai créé pour l'exemple toujours dans le même fichier. Elle va recevoir un `set` des pseudos qui ont été détecté dans le message. Ici j'imagine que tu va devoir créer les notifs.

J'ai assez peu de connaissance du fonctionnement du site mais avec ça tu devrais pouvoir t'en sortir : il faut fournir une fonction qui dit si le nom est valide et le markdown renvoie les noms trouvés en plus du texte.

2016-11-07 10:05 UTC, cgabard commented
N'hésite pas à me dire/contacter si tu as des questions et/ou si tu as besoin d'autre chose pour te faciliter la vie. Globalement c'est la reprise de ton commit légèrement complété.

2016-11-07 10:07 UTC, cgabard commented
Hum, il y a un truc qui me gène actuellement et je crois que je vais changer un détail. Je pense que la fonction va devoir me renvoyer une url si le ping est possible et `None` sinon à la place d'un `True/False`. Ça évitera que le markdown contienne des références lié aux urls de zds (et donc de devoir tout changer si on les mets à jour). De plus ça permettra que si un jour du veux pouvoir pinger autre chose que des users, les seuls modifs à faire soient du coté zds a priori.

Tu en pense quoi ?

2016-11-07 10:39 UTC, GerardPaligot commented
Que c'est une super idée. (:

2016-11-07 11:47 UTC, vhf requested changes

2016-11-07 11:47 UTC, vhf commented on zds/utils/templatetags/emarkdown.py
> +def get_markdown_instance(inline=False, js_support=False, is_pingeable=None):
Plutôt `pingable`, donc ici `is_pingable`, que `pingeable` ;)

Idem plus bas.

2016-11-07 14:51 UTC, cgabard commented on zds/utils/templatetags/emarkdown.py
> +def get_markdown_instance(inline=False, js_support=False, is_pingeable=None):
Oui du coup la fonction/paramètre va probablement être renommée `ping_url` ou un truc du genre.

2016-11-09 20:06 UTC, cgabard commented
Ok, nouvelle version. La seule différence est que la fonction, maintenant nommée `ping_url` qui peut être fournit doit renvoyer une chaîne de caractère constituant l'url cible du ping depuis le nom ou renvoyer `None` si la cible ne peut pas être "pingé".

Le reste c'est du ressort de zds et n'a pas besoin de venir dans cette PR

2016-11-12 20:05 UTC, GerardPaligot commented
@cgabard Alors on a un bug dans Python-ZMarkdown. J'ai commencé à développer les notifications pour les pings et j'ai donc voulu passer ma fonction à l'extension `ZdsExtension` mais bizarrement [ici](https://github.com/zestedesavoir/Python-ZMarkdown/blob/master-zds/markdown/extensions/zds.py#L45) `self.getConfigs().get('ping_url', None)` me renvoyait toujours `True`.

J'ai un peu regardé comment sont placées les valeurs dans le dictionnaire `configs` et je suis tombé sur [ces lignes](https://github.com/zestedesavoir/Python-ZMarkdown/blob/master-zds/markdown/extensions/__init__.py#L46-L47). Comme on a pas encore placé la fonction dans le dictionnaire, `self.config[key][0]` renvoi `None` et convertit ma fonction en boolean.

Voilà. J'espère que j'ai été clair. (:

2016-11-14 20:41 UTC, cgabard commented
@vhf ta "request change" est réglé.

Pour moi c'est pret pour la QA.

Je laisse @GerardPaligot donner des indications sur la QA du ping, c'est lui qui s'en est occupé !

2016-11-14 20:42 UTC, pierre-24 commented
Ok. Par contre, QA faisant, va falloir rebaser :-°

2016-11-14 20:43 UTC, cgabard commented
@GerardPaligot tu veux t'en occuper vu que ce sont tes modifs ou tu veux que je le fasse ?

2016-11-14 21:00 UTC, cgabard commented
@pierre-24 Bon j'ai fait le rebase

2016-11-14 21:11 UTC, cgabard commented
Bon bin j'ai raté mon rebase on dirait...

2016-11-14 21:14 UTC, vhf approved these changes

2016-11-14 21:18 UTC, vhf commented on zds/utils/models.py
> +        for username in md_instance.metadata.get("ping", []):
Je serais très favorable à un garde-fou, quitte à le retirer plus tard, voire à l'avoir dans les settings.

Je connais des sites communautaires qui ont introduit un système de ping similaire, et très vite des marioles en ont profité pour pinger 500 membres par messages.

Est-ce qu'on pourrait limiter à 10 ou 15 le nombres d'utilisateurs pingés dans un même message ? Genre les 10-15 premiers sont pingés, pas les suivants ? Vu qu'on a une limite d'un post par 15 minutes, ça me semblerait assez judicieux.

2016-11-14 22:32 UTC, vhf commented on zds/notification/models.py
> +        assert hasattr(answer, "get_notification_title")
`'`

2016-11-14 22:32 UTC, vhf commented on zds/notification/receivers.py
> +    user = kwargs.get('user')
Que se passe-t-il s'il manque un de ces deux ou ces deux arguments ?

2016-11-14 22:32 UTC, vhf commented on zds/notification/receivers.py
> +    by_email = kwargs.get('by_email')
Idem ici ?

2016-11-14 22:45 UTC, vhf commented on zds/notification/receivers.py
> +    by_email = kwargs.get('by_email')
A quel moment est-ce que `by_email` peut être `True` ?

2016-11-14 22:46 UTC, vhf commented on zds/notification/models.py
> +        return _(u'{0} vous a mentionné sur {1}.').format(answer.author, answer.get_notification_title())
Je pense les tests plantent à cause de cette ligne.

2016-11-14 22:52 UTC, GerardPaligot commented on zds/utils/models.py
> +        for username in md_instance.metadata.get("ping", []):
La limite des 15 minutes n'est appliquable que sur un sujet. Tu peux créer plusieurs sujets et faire chier des membres avec des pings dans chacun de ces sujets.

C'est un problème.

2016-11-14 22:53 UTC, GerardPaligot commented on zds/notification/receivers.py
> +    by_email = kwargs.get('by_email')
Aujourd'hui, pas possible.

2016-11-14 22:54 UTC, vhf commented on zds/notification/receivers.py
> +    by_email = kwargs.get('by_email')
Du coup si c'est pas utile, il vaut mieux l'enlever.

2016-11-14 22:54 UTC, GerardPaligot commented on zds/notification/models.py
> +        return _(u'{0} vous a mentionné sur {1}.').format(answer.author, answer.get_notification_title())
J'étais quasiment certain que les tests ont passés un moment et cette ligne y était.

Tu serais dire pourquoi tu penses que c'est cette ligne qui pose problème ?

2016-11-14 22:56 UTC, vhf commented on zds/utils/models.py
> +        for username in md_instance.metadata.get("ping", []):
Yep. Mais je pense que ça vaut la peine d'implémenter cette limite de pingables/message dans cette PR.

Je pensais pas particulièrement à des gens qui veulent embêter, je pensais plus à des gens qui font du bruit en utilisant 'correctement' cette feature, correctement d'après son implémentation.

Si quelqu'un veut embêter et ping par exemple tous les membres sauf le staff dans un message, ça sera embêtant pour tous les membres et pas rapidement détectable par le staff. Si quelqu'un veut embêter en créant 1000 topics, tout le monde le verra et il sera vite viré.

2016-11-14 22:57 UTC, vhf commented on zds/notification/models.py
> +        assert hasattr(answer, "get_notification_title")
(idem ici `zds/notification/models.py`)

2016-11-14 23:02 UTC, vhf commented on zds/notification/models.py
> +        return _(u'{0} vous a mentionné sur {1}.').format(answer.author, answer.get_notification_title())
Les logs travis disent `TypeError: int() argument must be a string or a number, not 'SimpleLazyObject'`, et je pense que si tu vires l'i18n ici ça passe. Mais j'ai pas tiré ta PR en local pour tester, c'est qu'une hypothèse.

Et il vaut pas virer l'i18n si c'est le cas, il faut trouver une meilleure solution.

2016-11-15 07:35 UTC, vhf commented on zds/forum/views.py
> +            signals.content_read.send(sender=post.__class__, instance=post, user=self.request.user)
Plutôt ici. Quand l'utilisateur n'est pas connecté, `request.user` est un SimpleLazyObject.

2016-11-15 07:36 UTC, vhf commented on zds/notification/models.py
> +        return _(u'{0} vous a mentionné sur {1}.').format(answer.author, answer.get_notification_title())
En fait je reviens sur mon idée, c'est probablement pas là.

2016-11-15 08:25 UTC, GerardPaligot commented on zds/forum/views.py
> +            signals.content_read.send(sender=post.__class__, instance=post, user=self.request.user)
Oh bien vu. Je corrige ça dès que possible.

2016-11-15 08:29 UTC, GerardPaligot commented on zds/notification/receivers.py
> +    by_email = kwargs.get('by_email')
Le signal `new_content` est utilisé pour d'autres modèles et `by_email` n'est pas forcément à `True` dans ces cas là.

2016-11-15 08:30 UTC, GerardPaligot commented on zds/notification/receivers.py
> +    user = kwargs.get('user')
Sans doute un comportement non souhaité. La meilleure solution est l'invocation d'`assert` pour vérifier que les valeurs sont bien renseignées ?

2016-11-15 08:30 UTC, GerardPaligot commented on zds/utils/models.py
> +        for username in md_instance.metadata.get("ping", []):
L'argument se tient. Je fais ça dès que possible.

2016-11-17 14:27 UTC, cgabard commented on zds/utils/models.py
> +        for username in md_instance.metadata.get("ping", []):
Petite question : Est-ce que l'on veut que les pings sans notification (car la limite atteinte) soient tout de même transformés en liens vers les auteurs ? Si oui pas de soucis, sinon il faudra une modif dans le markdown.

Au passage, on pourrait pas imaginer créer une alerte de validation automatiquement si la limite haute est atteinte ? Comme ça les modos seraient au courant que quelqu'un a mit plein de monde.

Enfin, vous en avez pas parlé mais coté markdown je renvoie un "set" et non une liste. Ça ne devrait pas avoir d'impact mais j'ai oublié de prévenir (ça me semblait le plus logique, l'ordre et le nombre de fois où une personne est pingué n'a pas d'intéret pour zds). La conséquence est aussi que plusieurs citations de la meme personne dans un meme message ne provoquera qu'une seule notif.

2016-11-20 12:05 UTC, cgabard commented
Selon @GerardPaligot les tests vont fails mais il ne sait pas pourquoi, si quelqu'un a une idée...

2016-11-20 12:06 UTC, GerardPaligot commented on zds/notification/receivers.py
> +    user = kwargs.get('user')
Done.

2016-11-20 12:09 UTC, GerardPaligot commented
Plusieurs choses à savoir sur les 2 fails :

- Ils étaient déjà présent avant mes nouveaux commits sur les retours de @vhf.
- Impossible de reproduire en local. Ca ne fail que sur Travis.
- Avant mon rebase par rapport à la branche de @cgabard, j'étais au vert.

Ce dernier point peut être important, je soupçonne de plus en plus la dernière mise à jour de Python-ZMarkdown.

2016-11-20 12:21 UTC, cgabard commented
Travis dit qu'il y a un conflit de migration.

2016-11-20 12:23 UTC, vhf commented on zds/utils/models.py
> +        for username in list(md_instance.metadata.get("ping", []))[:settings.ZDS_APP['comment']['max_pings']]:
`'` ici, pas `"`

2016-11-20 12:28 UTC, vhf commented on zds/notification/migrations/0013_pingsubscription.py
> +        ('notification', '0012_auto_20160703_2255'),
`0013_clean_notifications` au lieu de `0012_…` ici

2016-11-20 12:28 UTC, vhf commented on zds/notification/migrations/0013_pingsubscription.py
> +        ('notification', '0012_auto_20160703_2255'),
Et renommer le fichier `0014_…`

Après ça devrait mieux passer.

2016-11-20 12:33 UTC, cgabard commented on zds/utils/models.py
> +        for username in list(md_instance.metadata.get("ping", []))[:settings.ZDS_APP['comment']['max_pings']]:
ok, je vais le faire

2016-11-20 12:33 UTC, cgabard commented on zds/notification/migrations/0013_pingsubscription.py
> +        ('notification', '0012_auto_20160703_2255'),
ok, je vais le faire

2016-11-20 12:34 UTC, GerardPaligot commented on zds/notification/migrations/0013_pingsubscription.py
> +        ('notification', '0012_auto_20160703_2255'),
@cgabard Faudrait que tu rebases ta branche et que tu fasses cette modification si possible. `0013_clean_notifications` n'est pas encore présent sur ta branche.

2016-11-20 12:39 UTC, cgabard commented on zds/utils/models.py
> +        for username in list(md_instance.metadata.get("ping", []))[:settings.ZDS_APP['comment']['max_pings']]:
done

2016-11-20 12:39 UTC, cgabard commented on zds/notification/migrations/0013_pingsubscription.py
> +        ('notification', '0012_auto_20160703_2255'),
Oui j'ai vu, et c'est fait

2016-11-20 14:46 UTC, cgabard commented
Alors je ne sais pas pour les autres mais pour cette erreur : https://travis-ci.org/zestedesavoir/zds-site/jobs/177418980#L597 il est probable que ce soit dut aux changement typographique : le markdown va maintenant mettre un espace insécable avant le point d'exclamation

2016-11-20 15:01 UTC, vhf commented
Bien vu @cgabard ! Tu peux ajouter l'espace insécable dans le test stp ?

https://github.com/cgabard/zds-site/blob/87d51a0187c31c116197884a8dd32a2f755e93cb/zds/mp/tests/tests_views.py#L567

2016-11-20 15:09 UTC, cgabard commented
Bon c'est seulement ton deuxième liens qu'il faut modifier, je viens de le faire

2016-11-20 15:34 UTC, cgabard commented
Ok le deuxième test semble être le meme problème

2016-11-20 16:15 UTC, cgabard commented
Ça y est les tests sont bon !

2016-11-20 18:07 UTC, GerardPaligot commented
Avant de merger les notifications du ping, @gustavi et @vhf voudrait attendre que le module des notifications soient plus stable. Mais la mise à jour de Python-ZMarkdown reste très intéressante au vu des très nombreux bug fixes que tu as développé.

Cela pourrait être intéressé d'avoir une PR ping et une PR mise à jour de Python-ZMarkdown à mon avis.

2016-11-20 18:25 UTC, cgabard commented
Il suffit de passer `None` à la fonction de ping pour les désactiver en
réalité ou au pire la laisser mais ne pas traiter les résultats : ça fera
les liens vers les profils mais ne générera pas les notifs. À vous de voir
ce que vous préférez. Je peux faire les modifications.

Le dim. 20 nov. 2016 19:07, Gérard Paligot <notifications@github.com> a
écrit :

> Avant de merger les notifications du ping, @gustavi
> <https://github.com/gustavi> et @vhf <https://github.com/vhf> voudrait
> attendre que le module des notifications soient plus stable. Mais la mise à
> jour de Python-ZMarkdown reste très intéressante au vu des très nombreux
> bug fixes que tu as développé.
>
> Cela pourrait être intéressé d'avoir une PR ping et une PR mise à jour de
> Python-ZMarkdown à mon avis.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/3945#issuecomment-261794156>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AF0jfDgTd7yJnab5PzKXeqaB1pAiu42Rks5rAIx3gaJpZM4Kqr3q>
> .
>

2016-11-20 20:11 UTC, firm1 commented
C'est normal qu'il y ait pas de test sur le ping ici ? ça éviterai des regressions dans le futur.

2016-11-20 20:20 UTC, cgabard commented
Je ne sais pas, c'est pas moi qui m'occupe du code sur les ping dans zds. Ceci dit ils veulent les désactiver pour l'instant, j'attends juste de savoir comment pour faire la modif.

@vhf @gustavi j'en fait quoi sur cette PR ?

2016-11-20 21:15 UTC, vhf commented
> Il suffit de passer `None` à la fonction de ping pour les désactiver en réalité ou au pire la laisser mais ne pas traiter les résultats : ça fera les liens vers les profils mais ne générera pas les notifs

C'est parfait pour nous. Y'a des trucs à adapter de notre côté pour supporter cette nouvelle version de zmarkdown ?

Si c'est le cas et que c'est déjà géré dans cette PR, pour moi on peut mettre un feature flag sur les pings et merger cette PR, quand elle aura les tests qui vont bien. Si c'est pas le cas, autant laisser la PR ouverte en attendant la release v21 et on fait passer les pings après si tout est stable.

2016-11-20 21:21 UTC, cgabard commented
Non il n'y a aucune contre indication à merger cette pr. On peut facilement
désactiver les pings des deux façons sans conséquences (autre que quelques
recherches de regex)

Le dim. 20 nov. 2016 22:15, victor felder <notifications@github.com> a
écrit :

> Il suffit de passer None à la fonction de ping pour les désactiver en
> réalité ou au pire la laisser mais ne pas traiter les résultats : ça fera
> les liens vers les profils mais ne générera pas les notifs
>
> C'est parfait pour nous. Y'a des trucs à adapter de notre côté pour
> supporter cette nouvelle version de zmarkdown ?
>
> Si c'est le cas et que c'est déjà géré dans cette PR, pour moi on peut
> mettre un feature flag sur les pings et merger cette PR, quand elle aura
> les tests qui vont bien. Si c'est pas le cas, autant laisser la PR ouverte
> en attendant la release v21 et on fait passer les pings après si tout est
> stable.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/3945#issuecomment-261806332>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AF0jfN6gwif0WTLa_yX1EAfokz4ROezRks5rALiBgaJpZM4Kqr3q>
> .
>

2016-11-20 22:18 UTC, vhf commented
Super !

Alors je propose que vous ajoutiez un feature flag dans le settings.py qui soit True par défaut pour activer les pings.

Si le flag n'est pas True, on met simplement `ping_url = None` [juste avant cette ligne](https://github.com/zestedesavoir/zds-site/pull/3945/files#diff-357416f7359afef7a8915d076461dad1R31).

Comme ça on a les pings derrière le flag, et travis passe dessus, et on s'évite un gros rebase, et on s'évite de l'instabilité en prod.

2016-11-21 07:34 UTC, vhf commented on zds/settings.py
> +        'max_pings': 15
`,`

2016-11-21 08:55 UTC, cgabard commented on zds/settings.py
> +        'max_pings': 15
J'ai pas compris ce commentaire.

2016-11-21 08:57 UTC, cgabard commented
Je vais m'occuper des modifs. Je vais faire ça dans la semaine, je vais en profiter pour mettre a jour le markdown car je suis tombé sur deux petits bug genant hier. Du coup je vais intégrer les modifs ici et désactiver les "nouveautés" (j'en ferait un ticket a part car il y a des modifs de codes à faire).

Du coup je vais rajouter un `enable_ping` à `False` et virer le support en conséquence.

2016-11-21 09:12 UTC, WinXaito commented on zds/settings.py
> +        'max_pings': 15
Il aimerait juste que tu ajoutes une virgule à la fin, comme après le `'home_number': 6,`

2016-11-21 09:19 UTC, vhf commented
Je sais pas si on est sur la même longueur d'onde @cgabard .

Cette PR est bien pour moi, et c'est volontiers si tu la modifies avec une nouvelle version du markdown qui répare les 2 petits bugs que t'as trouvé. Par contre je comprends pas bien l'idée d'une autre PR ou de désactiver les nouveautés hors des settings.

Je propose de garder le tout, mais de simplement désactiver le ping dans les settings du projet zds-site. Une variable dans les settings, et un check dans le code qui mets `ping_url` à `None` si les settings disent que le ping est désactivé.

Comme ça on profite de toutes les nouveautés, le ping est simplement désactivé côté `zds-site`, et pas besoin de changer le code du Markdown pour ça. :)

2016-11-21 09:40 UTC, cgabard commented
En fait il se trouve que depuis j'ai avancé sur le markdown et avec la version qui arriverait cela rajouterai des ancres sur les titres. Le truc est que j'aimerai pas l'activer pour l'instant car dans l'idéal pour ça, et pour les footnote, il faudrait a minima que le code zds fournisse un identifiant unique aux extrait à transformer (l'idée étant d'éviter les collisions d'id et de références quand il y a plusieurs extraits sur une meme page, dans un tuto ou sur le forum). Comme ça demande d'autre dev back, et que c'est le plus simple pour moi, je pensais le désactiver temporairement.

Coté zds je ferait ce que tu as proposé pour les ping. Pour zds il n'y aurait que les corrections de bugs (et les modifs typographiques) qui seraient activés par cette PR. Le reste (ping et ancres) seraient dispo mais désactiver pour permettre leur développement a part.

2016-11-21 09:52 UTC, cgabard commented
Bref on est bien sur la même longueur d'onde, la mise a jour pour corriger les bugs va juste m'obliger a pousser une autre nouvelle feature que je vais désactiver dans cette PR.

2016-11-22 19:59 UTC, cgabard commented
Ok, on va attendre les tests mais normalement les pings sont désactivés et zmarkdown à jour

2016-11-24 08:40 UTC, cgabard commented
Quelqu'un pour QA ça ? A priori il a juste a vérifier que le markdown fonctionne et que le ping ne fonctionne pas.

D'ailleurs pour le ping, faudra bien vérifier que la prévisualisation n'en génère pas. Mais bref c'est hors-scope de cette PR du coup.

2016-11-24 08:42 UTC, pierre-24 commented
C'est noté, QA pour probablement ce soir, sauf si quelqu'un est plus motivé d'ici là :)

2016-11-24 20:55 UTC, pierre-24 commented
Bon, 

+ les tableaux, OK, mon imagination tordue ne m'as pas permis de trouver un bug :)
+ Pour ce qui est des légendes, OK. À part que rajouter une légende à un tableau ne semble plus le centrer (à noter que j'ai des ennuis avec CSS, donc c'est peut être simplement moi) : 

![screenshot from 2016-11-24 21 40 55](https://cloud.githubusercontent.com/assets/7889675/20609731/64c9e020-b290-11e6-9675-5d03fc477eb8.png)

+ Pour ce qui est de la typo, c'est peut être simplement chrome qui transforme les caractères `&#machin;`, mais j'ai pas l'impression que ça fonctionne pour l'ajout d'espaces insécables :

![screenshot from 2016-11-24 21 35 34](https://cloud.githubusercontent.com/assets/7889675/20609742/9a7dd424-b290-11e6-8907-f81dc7728130.png)

2016-11-24 21:30 UTC, vhf commented
Oui chrome les transforme. Essaie d'afficher la source au lieu d'utiliser l'inspecteur. Si c'est une entité HTML, tu la verras dans la source. Si c'est pas le cas et que c'est unicode, tu peux copier-coller le caractère dans https://codepoints.net/ et regarder ce que c'est.

2016-11-27 20:30 UTC, pierre-24 commented
Ok, effectivement, quand on regarde le code de la page, ça le fait bien :)

![screenshot from 2016-11-27 21 29 13](https://cloud.githubusercontent.com/assets/7889675/20651599/a625ebc2-b4e8-11e6-85ce-cb3286034478.png)

Donc si on me confirme que mon bug de tableau est bien dû à mon CSS défaillant, on est bon :)

2016-11-29 17:41 UTC, vhf commented
@pierre-24 j'ai pas d'info sur le tableau, du coup je merge et si le build est correct sur la beta, c'est bon.

Je te rappellerai de bien vérifier direct sur la beta, parce que je sais pas exactement quel est le problème que t'as rencontré.

2016-11-29 18:00 UTC, artragis commented
y'a du rebase à faire.

2016-11-29 18:21 UTC, cgabard commented
Si quelqu'un veut le faire car je ne sais pas quand j'aurais un pc sous la
main pour le faire

Le mar. 29 nov. 2016 19:00, artragis <notifications@github.com> a écrit :

> y'a du rebase à faire.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/3945#issuecomment-263647756>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AF0jfJz97TWxMbG78rxeT0eqwNiy_mb3ks5rDGhCgaJpZM4Kqr3q>
> .
>

2016-11-29 18:24 UTC, vhf commented
Closed via 9709f1b0fe10c7c63730a1513b1f06d72dbf882b, nécessaire à la résolution de conflit de cette PR.

Merci @cgabard pour l'énorme travail, et @GerardPaligot pour l'énorme travail (2). Et @pierre-24 pour la QA. Ce sera en beta dès que le build est terminé.

2016-11-29 18:25 UTC, closed without merging

2016-11-29 20:03 UTC, cgabard commented
Il semble en effet y avoir un problème de centrage : https://scaleway.zestedesavoir.com/forums/sujet/7457/test-tableaux/#p132984

MAIS c'est encore pire en prod car la légende ne s'applique meme pas.

En inspectant vite fait, je comprends pas trop le soucis de CSS. Je suis pas persuadé que ce soit la faute du markdown

2016-11-29 20:07 UTC, pierre-24 commented
Tient, y'a aussi un problème avec les tableaux (#3879). Mais c'est probablement pas la faute de ZMarkdown, parce qu'il y a bien le `<figure>`, donc il fait bien son boulot.

(d'où elle sort, cette adresse ?)

2016-11-29 20:10 UTC, cgabard commented
> (d'où elle sort, cette adresse ?)

C'est @vhf qui l'a mise sur le topic de beta