ZEP-13 : Tribunes libres
zestedesavoir/zds-site pull request #3993
Opened 2016-11-20 11:57 UTC by vhf

PR rédigée par @gustavi : 

| Q | R |
| --- | --- |
| Type de modification | nouvelle fonctionnalité |
| Ticket(s) (_issue(s)_) concerné(s) | ZEP-13 |
### Présentation

Vous en avez rêvez, elle est là ! Cette PR ajoute le support des Tribunes libres à Zeste de Savoir.
### QA

Il faut faire un **énorme code review** mais également tester le site et tout ce qui a été ajouté. Devant la complexité du code du module `zds.tutorialv2` j'ai obligatoirement oublié certaines choses ou mal codé d'autres. Il faut également tester la recherche comme il faut (j'ai fait du copier/coller mais je ne sais pas si ça fonctionne bien).

**LA QA PEUT ÊTRE FAITE !**
### Avant de merger, les derniers détails
- Ajouter une icône pour les tribunes (si un dev front peut me hl via MP/IRC/ici)

**Toutes les remarques/critiques sont les bienvenues**, j'ai essayé de faire du code modulable pour qu'on puisse facilement le modifier.

---

Remarques de @vhf : 

* Nous avons une branche de ce repo exprès pour cette nouveauté !
* Ceux qui souhaitent donc participer à la résolution de bugs ou à améliorer cette PR sont les bienvenus,
* Faites une PR avec pour `base branch` la branche `zds-site/zep-13-b`, et vos commits une fois mergés rejoindront automatiquement cette PR. :)

2016-11-20 12:05 UTC, SpaceFox commented
\o/

Le 20 novembre 2016 à 12:57, victor felder <notifications@github.com> a
écrit :

> PR rédigée par @gustavi <https://github.com/gustavi> :
> Q R
> Type de modification nouvelle fonctionnalité
> Ticket(s) (*issue(s)*) concerné(s) ZEP-13 Présentation
>
> Vous en avez rêvez, elle est là ! Cette PR ajoute le support des Tribunes
> libres à Zeste de Savoir.
> QA
>
> Il faut faire un *énorme code review* mais également tester le site et
> tout ce qui a été ajouté. Devant la complexité du code du module
> zds.tutorialv2 j'ai obligatoirement oublié certaines choses ou mal codé
> d'autres. Il faut également tester la recherche comme il faut (j'ai fait du
> copier/coller mais je ne sais pas si ça fonctionne bien).
>
> *LA QA PEUT ÊTRE FAITE !*
> Avant de merger, les derniers détails
>
>    - Ajouter une icône pour les tribunes (si un dev front peut me hl via
>    MP/IRC/ici)
>
> *Toutes les remarques/critiques sont les bienvenues*, j'ai essayé de
> faire du code modulable pour qu'on puisse facilement le modifier.
> ------------------------------
>
> Remarques de @vhf <https://github.com/vhf> :
>
>    - Nous avons une branche de ce repo exprès pour cette nouveauté !
>    - Ceux qui souhaitent donc participer à la résolution de bugs ou à
>    améliorer cette PR sont les bienvenus,
>    - Faites une PR avec pour base branch la branche zds-site/zep-13-b, et
>    vos commits une fois mergés rejoindront automatiquement cette PR. :)
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/zestedesavoir/zds-site/pull/3993
> Commit Summary
>
>    - ZEP-13 : ajout des tribunes libres
>    - ZEP-13 : changement des affichages et messages pour les TL
>    - ZEP-13 : moderation des billets
>    - ZEP-13 : ajout de la promotion des billets en articles
>    - ZEP-13 : page de validation des billets pour le staff
>    - ZEP-13 : ajout de la recherche
>    - ZEP-13 : documentation
>    - ZEP-13 : fixtures
>    - ZEP-13 : corrections diverses
>    - ZEP-13 : ajout de tests unitaires
>    - constant.py: retrait des offsets explicite pour simplifier la
>    maintenance
>    - ZEP-13 : corrections diverses
>    - Lint et i18n
>    - add munin graph for tribunes (#3985)
>    - Corrections RC2
>
> File Changes
>
>    - *M* README.md
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-0> (1)
>    - *M* assets/scss/components/_header-dropdown.scss
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-1> (2)
>    - *M* assets/scss/layout/_header.scss
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-2> (2)
>    - *M* doc/source/back-end/contents.rst
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-3> (6)
>    - *M* templates/base.html
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-4>
>    (84)
>    - *M* templates/gallery/gallery/list.html
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-5> (4)
>    - *M* templates/home.html
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-6>
>    (63)
>    - *M* templates/member/messages/active_account.md
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-7> (1)
>    - *M* templates/member/profile.html
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-8>
>    (48)
>    - *M* templates/member/settings/unregister.html
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-9> (4)
>    - *M* templates/pages/eula.html
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-10>
>    (14)
>    - *M* templates/tutorialv2/base.html
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-11>
>    (18)
>    - *M* templates/tutorialv2/base_online.html
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-12>
>    (9)
>    - *M* templates/tutorialv2/includes/warn_typo.part.html
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-13>
>    (2)
>    - *M* templates/tutorialv2/index.html
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-14>
>    (46)
>    - *M* templates/tutorialv2/index_online.html
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-15>
>    (16)
>    - *A* templates/tutorialv2/messages/opinion_promotion.md
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-16>
>    (12)
>    - *A* templates/tutorialv2/messages/validation_opinion.md
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-17>
>    (13)
>    - *M* templates/tutorialv2/validation/index.html
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-18>
>    (9)
>    - *A* templates/tutorialv2/validation/opinions.html
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-19>
>    (86)
>    - *M* templates/tutorialv2/view/container_online.html
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-20>
>    (4)
>    - *M* templates/tutorialv2/view/content.html
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-21>
>    (226)
>    - *M* templates/tutorialv2/view/content_online.html
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-22>
>    (82)
>    - *M* zds/member/models.py
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-23>
>    (26)
>    - *M* zds/member/views.py
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-24>
>    (2)
>    - *M* zds/munin/views.py
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-25>
>    (18)
>    - *M* zds/pages/views.py
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-26>
>    (2)
>    - *M* zds/search/constant.py
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-27>
>    (48)
>    - *M* zds/search/forms.py
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-28>
>    (6)
>    - *M* zds/settings.py
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-29>
>    (6)
>    - *M* zds/tutorialv2/factories.py
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-30>
>    (2)
>    - *M* zds/tutorialv2/feeds.py
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-31>
>    (16)
>    - *M* zds/tutorialv2/forms.py
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-32>
>    (124)
>    - *M* zds/tutorialv2/managers.py
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-33>
>    (35)
>    - *A* zds/tutorialv2/migrations/0014_auto_20160418_1837.py
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-34>
>    (24)
>    - *A* zds/tutorialv2/migrations/0015_publishablecontent_sha_approved.py
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-35>
>    (19)
>    - *A* zds/tutorialv2/migrations/0016_publishablecontent_
>    promotion_content.py
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-36>
>    (20)
>    - *M* zds/tutorialv2/mixins.py
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-37>
>    (26)
>    - *M* zds/tutorialv2/models/__init__.py
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-38>
>    (57)
>    - *M* zds/tutorialv2/models/models_database.py
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-39>
>    (57)
>    - *M* zds/tutorialv2/models/models_versioned.py
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-40>
>    (44)
>    - *M* zds/tutorialv2/tests/tests_views.py
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-41>
>    (339)
>    - *M* zds/tutorialv2/urls/__init__.py
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-42>
>    (1)
>    - *M* zds/tutorialv2/urls/urls_contents.py
>    <https://github.com/zestedesavoir/zds-site/pull/3993/files#diff-43>
>    (6)
>    - *A* zds/tutorialv2/urls/urls_opinions.py
>    <https://github.com/zestedesavoir/zds-site [...]

2016-11-20 14:22 UTC, vhf commented
Compilation de feedbacks

* [ ] Il faudrait pouvoir signaler un billet au staff

2016-11-20 17:30 UTC, vhf commented
Les tests sont certainement cassés, pas eu le temps de m'occuper d'eux, j'ai juste implémenter le truc sans m'occuper des tests. Je fais ça plus tard.

2016-11-20 17:42 UTC, firm1 commented
Problème de libellé dans la recherche.

Lien : https://beta.zestedesavoir.com/rechercher/?q=pymeteo

Problème : une tribune est identifiée comme étant un article dans les résultats.

Capture : 

![capture d ecran de 2016-11-20 18-38-45](https://cloud.githubusercontent.com/assets/6066015/20464873/128d5130-af51-11e6-9784-d25889f89176.png)

2016-11-20 17:45 UTC, firm1 commented
Problème les tribunes n'apparaissent pas dans le sitemap.xml.

https://beta.zestedesavoir.com/sitemap.xml

2016-11-22 20:00 UTC, artragis requested changes

2016-11-22 20:00 UTC, artragis commented on doc/source/install/configs/munin/zds.conf
> +[zds_total_articles]
ah bah du coup il faut effectivement ajouter l'url des stats pour les tribunes, sorry les gens.

2016-11-22 20:00 UTC, artragis commented on doc/source/install/configs/nginx/sites-available/zestedesavoir
> +	return 301 https://$server_name$request_uri;
Habile.

2016-11-22 20:00 UTC, artragis commented on templates/gallery/gallery/list.html
> +                        {% elif content.type == "OPINION" %}
pour plus de cohérence : 

```twig
{% if content.is_article %}
    {% trans "à l'article" %}
{% elif content.is_tutorial %}
    {% trans "au tutoriel" %}
{% elif content.is_opinion %}
    {% trans "au billet" %}
{% else %}
    {% trans "au contenu" %}
{% endif %}
```

2016-11-22 20:00 UTC, artragis commented on templates/misc/message.part.html
> +            {% for alert in message.alerts_on_this_comment.all %}
Pas mal le refacto <3.

2016-11-22 20:00 UTC, artragis commented on templates/tutorialv2/includes/warn_typo.part.html
> +            {% if content.type == 'ARTICLE' %}
Comme tout à l'heure ça serait bien d'utiliser les content.is_XXX

2016-11-22 20:00 UTC, artragis commented on templates/tutorialv2/index.html
> +    {% elif opinions != None %}
`elif opinions` suffit.

2016-11-22 20:00 UTC, artragis commented on templates/tutorialv2/index.html
> +                {% elif opinions != None %}
`elif opinions` suffit.

2016-11-22 20:00 UTC, artragis commented on templates/tutorialv2/index.html
> +    {% elif opinions != None %}
`elif opinions` suffit.

2016-11-22 20:00 UTC, artragis commented on templates/tutorialv2/index.html
> +                        {% if tutorials != None %}
`elif tutorials` suffit.

2016-11-22 20:00 UTC, artragis commented on zds/forum/feeds.py
> +            if 'forum' in obj and 'tag' in obj:
Quitte à faire des changements : 

```python

posts =  Post.objects.filter(topic__forum__group__isnull=True)
if 'forum' in obj:
    posts = posts.filter(topic__forum__pk=int(obj['forum']))
if 'tag' in obj:
    posts = posts.filter(topic__tags__pk__in=[obj['tag']])
posts = posts.order_by('-pubdate')[:settings.ZDS_APP['forum']['posts_per_page']]

2016-11-22 20:00 UTC, artragis commented on zds/forum/feeds.py
> +            topics = Topic.objects.filter(forum__group__isnull=True)
<3

2016-11-22 20:00 UTC, artragis commented on zds/tutorialv2/forms.py
> +class PublicationForm(forms.Form):
Etant donnée la taille du fichier, ça serait pas plus mal de créer un dossier `forms` dans lequel on a `validated_forms.py`, `commons.py` et `without_validation.py`?

2016-11-22 20:00 UTC, artragis commented on zds/tutorialv2/models/models_database.py
> +    def required_validation_before(self):
`requires_validation_before`

2016-11-22 20:00 UTC, artragis commented on zds/tutorialv2/models/models_database.py
> +    # def alerts_on_this_content(self):
Si c'est du code commenté, c'est qu'il faut le supprimer, tu ne crois pas?

2016-11-22 20:00 UTC, artragis commented on zds/tutorialv2/utils.py
> +def clone_repo(old_path, new_path):
petite doc? C'est un utilitaire par trop intéressant pour passer à côté.

2016-11-22 20:00 UTC, artragis commented on zds/utils/management/commands/load_fixtures.py
> +                    if to_do < 2:
Impossible
En effet to_do est supérieur à 1 donc il appartient à [2, +inf[.

2016-11-22 21:20 UTC, vhf commented on doc/source/install/configs/nginx/sites-available/zestedesavoir
> +	return 301 https://$server_name$request_uri;
(Déjà en prod et sur la beta, au passage. ;))

2016-11-26 21:18 UTC, Emeric54 commented
> L'auteur visionnant son propre billet publié n'a pas de lien direct pour l'éditer (faut passer par le menu > mes billets)

On peut ajouter ça, mais il faut noter que c'est également le cas pour les tutoriels et les articles.

2016-12-14 20:26 UTC, GCodeur commented
Petit bug niveau front (présent aussi sur les autres types de contenu d'ailleurs) : quand on a aucun contenu, voici le résultat :

![Capture d'écran](https://www.pixenli.com/images/1481/1481746339009224200.png)

2016-12-22 13:29 UTC, GCodeur commented
J'ai le comportement suivant en ce qui concerne les demandes d'aide :

- lorsque l'on crée une tribune, on n'a pas de case pour l'aide, mais les labels sont, eux, bien affichés (pour ça, je crois que c'est déjà signalé) ;
- lorsque l'on modifie une tribune, les cases sont présentes, mais n'ont aucun effet. `Rédacteur` est toujours coché (en ce qui me concerne du moins).

2016-12-26 15:15 UTC, firm1 commented
- [ ] Problème de vocabulaire
- [ ] Incompréhension sur la home
- [ ] La lecture zen est brisée
- [ ] La recherche avancée est cassée
- [ ] Le cache ne semble pas invalidé à la dé-publication d'un billet

# Problèmes d'expérience utilisateur

## Problème de vocabulaire

Lorsqu'on clique dans la Topbar sur "Tribunes" puis "Toutes les Tribunes", on arrive sur une page intitulée "Tous les billets".

![Problème de vocab](/media/galleries/241/ed4efc27-b5b6-4723-baec-86fff903f9e9.png)

ça ne me parait pas super niveau expérience utilisater, car on est passé du vocabulaire "tribune" à "billet" sans transitions.

Proposition : Renommer dans la topbar "toutes les tribunes" par "Tous les billets". Ainsi on part du principe que la tribune est constituée des billets tout simplement.

## Incompréhension sur la home

Sur la page d'accueil on n'affiche que les tribunes validées par le staff, on est d'accord et c'est ce qu'on veut. Le problème c'est que cette zone est titrée "Derniers billets " et on a un bouton à coté qui nous dit "Tous les billets". Quand on clique sur tous les billets on voit  effectivement tous les billets, même ceux qui ne sont pas approuvés par le staff.

![home tribunes](/media/galleries/241/f796319f-dfe9-403a-a091-9e94c54a3dba.png)

Si on se mets deux secondes dans la peau d'un membre qui n'était pas là le jour de la spécification de cette ZEP, ou quelqu'un qui vient sur le site pour la première fois, on s'attend à ce qu'en cliquant sur "tous les billets" le billet le plus récents soit le même que ce qui a été affiché sur la page d'accueil. Or ici ce n'est pas le cas, puisque des billets peuvent être publiés et ne pas apparaître sur la Home.

Proposition : renommer "Derniers billets" de la page d'accueil en "Derniers billets (approuvés par l'équipe)". Bon il y'a un petit travail coté css à faire pour designer différemment la mention "approuvés par l'équipe" pour pas que ça prenne trop de place.

# Problème techniques de front

## La lecture zen est brisée

En lisant un billet en mode zen, je suis perturbé par un bout de la sidebar qui s'en est allé en bas à droite.

![lecture zen](/media/galleries/241/36c3f6b9-1e6b-4f5a-8222-c89ddf1503db.png)

# Problèmes techniques coté back-end

## La recherche avancée est cassée

[[information]]
| Quelqu'un a déjà déclaré ce problème quelque part si ma mémoire est bonne.

Lorsqu'on recherche un contenu en filtrant sur un type, le résultat renvoyé n'est plus lié au filtre comme demandé.

## Le cache ne semble pas invalidé à la dé-publication d'un billet

[[information]]
| Le problème semble toucher tous les types de contenu

J'ai dé-publié le seul billet de la catégorie histoire sur la beta. Cependant la topbar continue de présenter cette catégorie comme s'il y'avait encore du contenu publié à l'intérieur. Il faudrait idéalement invalider le cache à la dé-publication d'un contenu (tout comme s'est fait à la validation d'un contenu).

Pour l'instant je me suis arrêté là.

2016-12-26 17:24 UTC, pierre-24 commented
Comme j'ai dit, toute la recherche est cassée, sauf que je croyais qu'on avais un ticket, et on l'as pas. Je vais de suite en créer un :)

2017-01-02 18:21 UTC, GCodeur commented
Deux petites remarques :

2017-01-02 18:25 UTC, GCodeur commented
Petite remarque : est-ce que `Billets validés` ne serait pas mieux que `Billets choisis`, car je trouve que ça donne l'impression que c'est une sélection de l'équipe du site, alors que, si j'ai bien compris, cette validation n'existe que pour des raisons de sécurité/légalité ?

2017-01-02 18:37 UTC, vhf commented
@GCodeur je ne suis pas au courant de cette raison de sécurité ou légalité. Il s'agit de billets choisis par l'équipe de ZdS, pas de "validation" au sens de la validation des articles ou tutoriels.

2017-01-02 18:42 UTC, GCodeur commented
En fait, je pensais à [ce message](https://zestedesavoir.com/forums/sujet/7250/venez-tester-les-tribunes/?page=4#p136575). J'ai peut-être mal compris, mais j'avais considéré que les billets devraient être forcément approuvés ou dépubliés, mais qu'il n'y aurait pas de billets laissés tel quel. Alors que `Billets choisis` me faisait davantage penser à une sélection.

2017-01-02 18:51 UTC, vhf commented
D'accord, je vois le malentendu. Les billets ne subissent pas de validation. Certains sont choisis par l'équipe, ceux-ci s'affichent en page d'accueil. Les autres, donc ceux qui ne sont pas choisis par l'équipe, ne s'affichent pas en page d'accueil. Tous les billets, à l'exception de ceux qui seraient dépubliés par l'équipe, sont visibles sur la tribune de leur auteur.

2017-01-02 18:56 UTC, GCodeur commented
Ah d'accord, je n'avais pas compris ça, merci pour l'info.

> sont visibles sur la tribune de leur auteur.

Ainsi que sur la page `Tous les billets` du coup, non ?

PS : ça n'a pas vraiment de rapport, mais la RC5 actuellement en ligne ajoute le bouton `Tout marquer comme lu`, sauf que celui-ci provoque une erreur 404. Je ne savais pas trop où le rapporter et j'imagine que c'est spécifique à cette release, mais je le signale dans le doute.

2017-01-02 19:10 UTC, GerardPaligot commented
Petit souci graphique sur la page "Mes billets" :

<img width="288" alt="capture d ecran 2017-01-02 a 20 06 15" src="https://cloud.githubusercontent.com/assets/1913901/21594810/4c3242f4-d127-11e6-8365-88df8ceb2c0f.png">

D'ailleurs, il me semblait qu'une [icone](https://github.com/zestedesavoir/zds-site/pull/3606#issuecomment-242962177) avait été réalisé pour représenter les tribunes. C'est dommage de pas l'utiliser.

2017-01-02 19:37 UTC, GerardPaligot commented
J'ai tenté de supprimer à l'instant un auteur sur l'un de mes billets et j'ai obtenu une 500.

2017-01-02 19:42 UTC, GerardPaligot commented
J'ai publié une tribune et lorsque je clique sur l'un des tags que j'ai utilisé, je ne retrouve pas mon billet dans la liste. D'ailleurs, la liste est vide.

2017-01-02 19:45 UTC, artragis commented
peux-tu dire quelle est l'url que tu obtiens sur les tags et les catégories stp?

2017-01-02 19:46 UTC, GerardPaligot commented
Bien sûr :

Mon billet : https://beta.zestedesavoir.com/tribunes/1691/mon-premier-billet/

Clique sur n'importe quel tag ou catégorie en tête du billet mais si tu veux direct des exemples dans ce message :

https://beta.zestedesavoir.com/contenus/?tag=toto3 et https://beta.zestedesavoir.com/contenus/?category=autres-informatique

2017-01-02 19:48 UTC, GerardPaligot commented
Je ne sais pas si c'est voulu ou non mais j'ai l'impression que les billets sont rangés dans les catégories que quand ils font l'objet d'une mise en avant par le staff, chose étrange puisqu'on parle pas là d'une validation mais simplement d'une mise en avant.

2017-01-02 19:52 UTC, GerardPaligot commented
Quand j'applique un filtre sur la liste de mes billets (j'ai le choix entre "Brouillon" ou "Publié"), la liste disparait et ne me permet donc pas de supprimer un filtre ou de le modifier.

Exemple d'URL : https://beta.zestedesavoir.com/contenus/tribunes/67/?filter=redaction

Edit : Le bug ne s'applique que avec le filtre "redaction"

2017-01-02 19:54 UTC, GerardPaligot commented
Quand je me rends sur le billet de la mort de Aabu, j'ai un bandeau vert dans l'en-tête : 
https://beta.zestedesavoir.com/tribunes/1689/billet-dela-mort/

2017-01-02 19:56 UTC, GCodeur commented
C'est peut-être dû au signalement que j'ai fait dessus. D'ailleurs, à propos de ce signalement, le titre du message privé est buggé.

![Capture](https://www.pixenli.com/images/1483/1483386971011511300.png)

2017-01-02 19:57 UTC, vhf commented
> Je ne sais pas si c'est voulu ou non mais j'ai l'impression que les billets sont rangés dans les catégories que quand ils font l'objet d'une mise en avant par le staff

C'est un choix conscient, oui.

2017-01-02 20:10 UTC, artragis commented
Hein c'est stupide.


Le 02/01/2017 à 20:57, victor felder a écrit :
>
>     Je ne sais pas si c'est voulu ou non mais j'ai l'impression que
>     les billets sont rangés dans les catégories que quand ils font
>     l'objet d'une mise en avant par le staff
>
> C'est un choix conscient, oui.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/3993#issuecomment-270014147>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xYI7f1t62oDLYCoImD2LQIG4sjT4ks5rOVaVgaJpZM4K3hNH>.
>

2017-01-02 20:11 UTC, artragis commented
Histoire d'être plus locace : le principe même des tribunes c'est qu'on 
n'ait pas de validation sauf pour mettre en avant. Le classement dans 
les catégorie n'est pas une mise en avant.


Le 02/01/2017 à 20:57, victor felder a écrit :
>
>     Je ne sais pas si c'est voulu ou non mais j'ai l'impression que
>     les billets sont rangés dans les catégories que quand ils font
>     l'objet d'une mise en avant par le staff
>
> C'est un choix conscient, oui.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/3993#issuecomment-270014147>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xYI7f1t62oDLYCoImD2LQIG4sjT4ks5rOVaVgaJpZM4K3hNH>.
>

2017-01-02 20:31 UTC, GerardPaligot commented
Il m'est impossible de suivre mon contenu : https://beta.zestedesavoir.com/tribunes/1691/mon-premier-billet-edite/

2017-01-02 21:25 UTC, Emeric54 commented
Pas seulement pour toi @GerardPaligot, c'est impossible pour moi également.

Par contre, on suit correctement le contenu lorsque l'on y poste un commentaire. Mais du coup, il est impossible de ne plus le suivre.

2017-01-02 21:36 UTC, artragis commented
à confirmer mais ça devrait être fixé par ma PR 
https://github.com/zestedesavoir/zds-site/pull/4107


Le 02/01/2017 à 22:25, Emeric54 a écrit :
>
> Pas seulement pour toi @GerardPaligot 
> <https://github.com/GerardPaligot>, c'est impossible pour moi également.
>
> Par contre, on suit correctement le contenu lorsque l'on y poste un 
> commentaire. Mais du coup, il est impossible de ne plus le suivre.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/3993#issuecomment-270021869>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xV2QwK7lvaUSX12CfMxsDqFLmlBXks5rOWs5gaJpZM4K3hNH>.
>

2017-01-15 20:13 UTC, vhf commented on templates/tutorialv2/index.html
> +    {% elif opinions != None %}
Il semblerait que non. :)

2017-01-15 20:15 UTC, artragis commented on templates/tutorialv2/index.html
> +    {% elif opinions != None %}
anéfé. je clos.

2017-01-15 20:15 UTC, artragis commented on templates/tutorialv2/index.html
> +    {% elif opinions != None %}
ok contrairement à gitlab, on peut pas "marquer comme résolu" un commentaire sur gh...

2017-02-02 13:45 UTC, DevHugo commented
@vhf @gustavi on fait quoi ici ?  Y'a eu un super travail qui a été fait, et ça serait vraiment complètement con de le gâcher. 

J'ai un peu de temps en ce moment, je veux faire, mais faut qu'on soit tous d'accord sur le plan d'action

2017-02-02 13:46 UTC, pierre-24 commented
De toute facon, la première étape, c'est de merger les différentes PRs liées :)

2017-02-02 14:00 UTC, DevHugo commented
Si tu veux vhf, je peux te proposer que tu me laisse les droits sur la branche, je merge les deux dernières PR et je rebase. Comme ça, tu auras moins de chose à faire.

2017-02-02 18:14 UTC, vhf commented
Volontiers @DevHugo , je t'ai donné accès.

Le gros du travail, c'est de comprendre ce que veut la communauté. Il y a eu des tas de débats suite à la n-ème relance du topic invitant la communauté à tester les tribunes, et c'est @gustavi qui devait se charger de les lire et d'établir la liste des choses à ajouter/enlever/modifier pour que ça corresponde à la ZEP, à son auteur, et à ce que veut la communauté.

Parallèlement, il est déjà possible de traiter les choses listées dans la PR. Il y a des checkboxes. :)

2017-02-02 22:56 UTC, DevHugo commented
Merci, du coup, je vais commencer à regarder à partir demain.

2017-04-01 13:47 UTC, DevHugo commented
Je suis désolé, j'ai pas eu de temps alors que  j'aurais du en avoir. Mille excuses.

2017-04-02 13:02 UTC, pierre-24 commented
Bug localisé et fix trouvé. Le problème était du coté d'élasticsearch. Ce qui m'inquiète un tout petit peu plus, c'est qu'il aurait du survenir avant, donc il faut que je creuse un petit peu.

2017-04-02 13:21 UTC, artragis commented
Bien joué!

Le 2 avr. 2017 15:02, "Pierre Beaujean" <notifications@github.com> a écrit :

> Bug localisé et fix trouvé. Le problème était du coté d'élasticsearch. Ce
> qui m'inquiète un tout petit peu plus, c'est qu'il aurait du survenir
> avant, donc il faut que je creuse un petit peu.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/3993#issuecomment-290985037>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABc_xe5rIZWceY69d8JMDUROqZcn6ZyQks5rr5xogaJpZM4K3hNH>
> .
>

2017-04-10 18:01 UTC, artragis commented
Du coup, on merge. Bravo tout le monde.

2017-04-10 18:02 UTC, artragis approved these changes

2017-04-10 19:58 UTC, merged