3237 previsualisation biographie
zestedesavoir/zds-site pull request #4004
Opened 2016-11-22 19:16 UTC by Anto59290

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                |  évolution
| Ticket(s) (_issue(s)_) concerné(s)  | #3237 

Ajout de la previsualisation de la biographie. Avant cette PR le champ a previsualiser devait forcement s'appeller text. Aujourd'hui on reste compatible, mais on peut aussi utiliser une classe css pour marquer le champ a previsualiser. Sera utile pour la previsualisation des intros et des conclusions de contenu (a venir). Du coup il faut reconstruire le front.

 
### QA

* lancez `npm run gulp build` pour le front
* Verifier que l'apercu de la biographie fonctionne bien
* Les autres apercu (mp,forum, etc.) doivent toujours fonctionner.

2016-11-23 19:41 UTC, pierre-24 commented
Rapport de QA: NOK

![screenshot from 2016-11-23 20 34 57](https://cloud.githubusercontent.com/assets/7889675/20576040/5b5cef34-b1bc-11e6-961e-a08ce2e7e865.png)

+ Le bouton de prévisualisation se trouve en bas de la page et non juste en dessous de la zone de texte. En soi, c'est le comportement par défaut donc t'y peux rien, mais en l'occurence, ce bouton est très loin de la zone de texte. J'ai peur que la seule manière d'y arriver, c'est, d'une manière ou d'une autre, placer deux formulaires sur la même page, ou dédier une page à la bibliographie
+ En l'occurence, la prévisualisation ne fonctionne pas, probablement parce que  [ici](https://github.com/zestedesavoir/zds-site/pull/4004/files#diff-9b5e7d46af0767956371dda732687da8R126), on devrait avoir `bibliography` et pas `text` :)
+ Une petite erreur de lint reportée par Travis, rien de grave

Courage :)

2016-11-23 19:46 UTC, vhf requested changes

2016-11-23 19:46 UTC, vhf commented on assets/js/ajax-actions.js
> +            {var text = $form.find(".preview-source").val();}
Le style ici devrait être : 
```js
if (true) {
    var x;
}
```

et non 

```js
if ()
    {var x;}
```

2016-11-23 19:46 UTC, vhf commented on assets/js/ajax-actions.js
> +            text,
Celle ligne ne me semble pas nécessaire. `text` est déjà déclaré ligne 221 ou 223.

2016-11-23 23:03 UTC, Anto59290 commented
Merci pour les retours. Alors pour le bouton apercu ça me parait très chaud de le déplacer. Je pense que c'est se prendre la tête pour pas grande chose ... Je vais essayer de regarder mais faire une page a part pour la bio me semble un peu tout much (en terme d'usage j'entends). Passer par deux forms, pourquoi pas, mais ca me parait tendu. Je vais peut être essayer de dégager le bouton et de recréer son comportement. En essayant que ça soit pas trop dégueux ^^  .

2016-11-24 07:05 UTC, pierre-24 commented
Si tu fais un truc pas trop dégeu, un minimum générique, et non plus lié à un formulaire mais à une zone de texte, ce "truc" pourrait être réemployé à d'autres endroits (tels qu'intro/conclusion dans le module des contenus), donc si t'as une idée, surtout lance toi :)

2016-11-24 21:39 UTC, gustavi commented on zds/member/views.py
> +        if "preview" in request.POST:
```diff
-        if "preview" in request.POST:
+        if 'preview' in request.POST:
```

2016-11-24 22:39 UTC, Anto59290 commented on zds/member/views.py
> +        if "preview" in request.POST:
Roh bien vu ;)

2016-12-18 14:33 UTC, Anto59290 commented
Je ferme ici et réouvre une PR plus globale.

2016-12-18 14:33 UTC, closed without merging