Licences
zestedesavoir/zds-site pull request #4007
Opened 2016-11-22 21:16 UTC by vhf

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | évolution
| Ticket(s) (_issue(s)_) concerné(s)  | -

L'orthographe 'license' étant très largement privilégiée (dans les textes des licence que nous proposons, sur github, presque partout en fait), j'ai renommé le modèle.

Le but de cette PR est de revoir notre système de choix de licence, notamment pour que les auteurs doivent choisir une licence au lieu de se contenter du défaut sans trop se poser la question.

### QA

* Vérifier que choisir une licence est obligatoire pour créer un tutoriel
* Tester la modification de licence d'un contenu existant

2016-11-22 21:34 UTC, artragis requested changes
Je ne vois pas pourquoi tu changes ça, car même si on veut jouer à la guéguerre anglais vs français, la règle dit : 

>In American English, license is both a noun and a verb, and licence isn’t used. For example, one who is licensed to drive has a driver’s license. In all the other main varieties of English, licence is the noun, and license is the verb. So, for instance, one who is licensed to perform dental surgery has a dental surgeon’s licence.

Donc, en bons français qui n'apprend pas l'anglais américain, disons du haut de notre hypothèse adhoc que nous avons codé ce module en anglais britanique.

Blague à part, je ne vois pas où on a mis "Vérifier que choisir une licence est obligatoire pour créer un tutoriel".

Enfin comme je le disais, la présence de "tout droit réservé" est une obligation car par défaut le droit d'auteur s'applique et que nous laissons aussi la liberté aux gens de ne pas rendre libre leur contenu. Très peu le font alors laissons comme ça.

Je suis en faveur de refuser cette PR.

Sinon, il manque aussi un bout de doc pour montrer dans la doc technique que le manifest doit changer.

2016-11-22 21:34 UTC, artragis commented on zds/tutorialv2/utils.py
> +        if 'license' in json:
une petite fonction permettrait sûrement d'éviter cette duplication de code?

2016-11-22 21:34 UTC, artragis commented on zds/utils/models.py
> +class License(models.Model):
Quitte à changer, ça serait bien de passer ça avec le décorateur django qui dit que __str__ c'est comme unicode, ça facilitera le passage à py3

2016-11-22 21:34 UTC, artragis commented on zds/tutorialv2/utils.py
> +        dct['license'] = content.license.code
tu vas péter silencieusement zest writer là.

2016-11-22 21:34 UTC, artragis commented on zds/settings.py
> +                'title': u"License Creative Commons",
en français, ça prend un c :p

2016-11-22 21:43 UTC, cgabard commented
> Enfin comme je le disais, la présence de "tout droit réservé" est une obligation car par défaut le droit d'auteur s'applique et que nous laissons aussi la liberté aux gens de ne pas rendre libre leur contenu.

Oui c'est pour ça que le choix par défaut était ça. Cependant notre objectif étant de promouvoir la diffusion sous contenu libre et ouvert, je trouve pas ça déconnant d'inciter les auteurs à y réfléchir et de choisir en connaissance de cause.

2016-11-22 21:43 UTC, firm1 commented on zds/tutorialv2/utils.py
> +        dct['license'] = content.license.code
Merci @artragis de l'avoir noté, je vais surveiller cette PR.

2016-11-22 21:44 UTC, artragis commented
Les validateurs font déjà ce boulot non? (du moins je le fais)

2016-11-22 21:45 UTC, vhf commented on zds/tutorialv2/utils.py
> +        dct['license'] = content.license.code
Bien vu !

2016-11-22 21:48 UTC, SpaceFox commented
Je passe juste pour dire que mon correcteur orthographique anglais est en
anglais britanique, et que donc il ne faut pas vous étonner si vous voyez
des commits à mon nom en en_GB.

Pour le reste je m'en fous tant que l'utilisateur a un choix clair à
disposition.

Le 22 nov. 2016 10:43 PM, "Christophe Gabard" <notifications@github.com> a
écrit :

> Enfin comme je le disais, la présence de "tout droit réservé" est une
> obligation car par défaut le droit d'auteur s'applique et que nous laissons
> aussi la liberté aux gens de ne pas rendre libre leur contenu.
>
> Oui c'est pour ça que le choix par défaut était ça. Cependant notre
> objectif étant de promouvoir la diffusion sous contenu libre et ouvert, je
> trouve pas ça déconnant d'inciter les auteurs à y réfléchir et de choisir
> en connaissance de cause.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/4007#issuecomment-262374487>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFhKnN5K8x0TLlCM2siCa999OtRKZ_2Qks5rA2HqgaJpZM4K580y>
> .
>

2016-11-22 21:48 UTC, vhf commented
Arius dit que mettre une licence par défaut pose les problèmes que tu soulignes, @artragis . Par contre il ne voit pas de problème avec cette PR.

Pour le en_UK vs en_US, je trouve mieux d'utiliser la forme habituellement utilisée quand il s'agit de licences. La forme utilisée dans les textes des licences, et celle utilisée sur notre repo : https://github.com/zestedesavoir/zds-site/blob/dev/LICENSE et ailleurs.

2016-11-22 21:49 UTC, artragis requested changes

2016-11-22 21:49 UTC, artragis commented on doc/source/back-end/contents_manifest.rst
> +La version 2.0 est la version actuellement utilisée.
2.0.1 du coup non?

2016-11-22 21:49 UTC, artragis commented on doc/source/back-end/contents_manifest.rst
> +        * v2.0.1 : le champ ``licence`` se nomme désormais ``license``
Du coup selon la règle de nomination, tu dois dire que tu supportes le mot `licence` quand même et que tu le renseigne quand même dans le manifeste.

2016-11-22 21:49 UTC, artragis commented on zds/tutorialv2/management/commands/upgrade_manifest_to_v2.py
> +            versioned.license = License.objects.filter(code=versioned.license).first()
Don't forget to handle `None` si tu veux absolument uen licence

2016-11-22 21:49 UTC, artragis commented on zds/tutorialv2/management/commands/upgrade_manifest_to_v2.py
>              versioned.version = "2.0"
2.0.1

2016-11-22 21:56 UTC, artragis requested changes

2016-11-22 21:56 UTC, artragis commented on zds/tutorialv2/utils.py
> +    def get_license(json):
un petit docstring?

2016-11-22 21:56 UTC, artragis commented on zds/tutorialv2/utils.py
> +        return False
étant donné que `first()` retourne `None` ne serait-il pas plus cohérent de retourner `none` plutôt que `False`

2016-11-22 21:59 UTC, vhf commented on zds/tutorialv2/utils.py
> +        return False
On peut, ouais.

2016-11-22 22:00 UTC, vhf commented on zds/tutorialv2/utils.py
> +    def get_license(json):
Je suis pas sûr. C'est un truc privé ici, et je pense qu'il y a pas d'autre cas où c'est utilisable.

D'autres avis ?

2016-11-22 22:00 UTC, vhf commented on zds/tutorialv2/management/commands/upgrade_manifest_to_v2.py
> +            versioned.license = License.objects.filter(code=versioned.license).first()
Me semble avoir respecté la sémantique du code original, je vais regarder.

2016-11-22 22:10 UTC, vhf commented
J'avais pas pensé qu'il n'y avait pas moyen d'exporter de façon backward compatible. Du coup j'ai revert ça et on reprendra au pire, si un jour il y a une `v3`.

2016-11-22 22:15 UTC, vhf commented
> Oui c'est pour ça que le choix par défaut était ça. Cependant notre objectif étant de promouvoir la diffusion sous contenu libre et ouvert, je trouve pas ça déconnant d'inciter les auteurs à y réfléchir et de choisir en connaissance de cause.

C'est exactement mon intention avec cette PR. Si c'est pas clair, la situation actuelle est : 

- Si je fais aucun choix dans le menu "licence", c'est l'option pré-sélectionnée qui passe, et cette option est "tous droits réservés"

La situation avec cette PR, c'est : 

- Si je fais aucun choix dans le menu "licence", le formulaire me dit de choisir quelque chose dans le menu "licence". Les options restent les mêmes, dont la non-licence nommée "tous droits réservés".

2016-11-23 14:12 UTC, cgabard commented
> "partant du principe que si le champ licence est vide c'est qu'il y a pas de licence."

Il me semble que ça n'a pas été fait car en droit français ce n'est pas possible. "Rien d'indiqué == tout droit réservé" (ce qui explique le choix par défaut). Donc le fonctionnement actuel n'est pas déconnant.

Perso je soutient la PR. On verra si ça devient chiant mais j'ai toujours trouvé dommage ce fonctionnement. On ne fait *rien* pour inciter les auteurs à choisir une licence libre. J'ai déjà vu dans les historiques de tutos des gens changer de licence simplement parce qu'ils avaient pas fait attention à la création.

Si le champs n'est pas plus mit en avant ou si il n'y a pas de procédure pour inciter les gens à en choisir, je pense que c'est une bonne idée d'essayer.

Ce qui serait intéréssant serait peut être à la mise en prod de regarder les licence choisis sur les contenus créés les 2-3 derniers mois (incluant les en rédaction et non publiés) et de le regarder de nouveaux dans 2-3 mois. Ça nous donnerait une métrique clair de l'intéret de cette modif : Si le chiffre ne change presque pas, autant le virer. Mais si ça incite les gens à choisir une licence libre, alors c'est que c'est utile.

2016-11-23 14:35 UTC, vhf commented
Justement, vu que sans indication contraire par défaut c'est tous droits
réservés, je trouve bizarre d'inclure ça dans les choix de licence. ;)

Je suis pas particulièrement en faveur de changer ça maintenant, mais je
trouverais plus cohérent que si l'auteur choisi une licence celle-ci
s'applique, sinon c'est tous droits réservés. Plutôt que de devoir
explicitement indiquer qu'on veut ce que la loi considère comme allant de
soi sauf indication contraire.

2016-11-23 16:10 UTC, vhf commented
Pour référence future : 

```sql
SELECT NOW();
+---------------------+
| NOW()               |
+---------------------+
| 2016-11-23 17:09:09 |
+---------------------+

SELECT count(*), l.code FROM tutorialv2_publishablecontent AS t INNER JOIN utils_licence AS l ON t.licence_id = l.id WHERE t.creation_date > DATE_SUB(NOW(), INTERVAL 3 MONTH) GROUP BY l.code;
+----------+------------------------+
| count(*) | code                   |
+----------+------------------------+
|        3 | CC 0                   |
|       13 | CC BY                  |
|        3 | CC BY-NC               |
|        2 | CC BY-NC-ND            |
|       14 | CC BY-NC-SA            |
|        4 | CC BY-SA               |
|       65 | Tous droits réservés   |
+----------+------------------------+
```

2016-11-28 21:31 UTC, pierre-24 commented
Rapport de QA: OK, MAIS.

En fait, Django choisi d’afficher la dernière licence de la liste comme choix par défaut, donc va savoir pourquoi ... Ça ne change rien :(

2016-11-28 21:33 UTC, vhf commented
Curieux. Tu peux me faire un screenshot de la liste ? Et si possible voir où se trouve la mention "Choisir une licence" ?

2016-11-28 22:01 UTC, pierre-24 commented
Et donc, QA OK, sur contenu nouvellement créé et ancien.

2016-11-28 22:01 UTC, merged