3237 Refonte du preview de plusieurs modules (biographie et contenus)
zestedesavoir/zds-site pull request #4087
Opened 2016-12-18 14:38 UTC by Anto59290

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | nouvelle fonctionnalité / évolution
| Ticket(s) (_issue(s)_) concerné(s)  | #3237 #4027 #3333 

### QA

* Reconstruire le front (changement dans le JS). Pour éviter les problèmes de cache j'ai réalisé les test en navigation privée.
* Vérifier que le preview de la biographie du membre est dispo
* Vérifier que l'on peut faire une preview de l'intro et de la conclusion d'un contenu
* Vérifier que les différents preview de contenu (charpitre, partie, etc.) se font sans rechargement de la page.
* Vérifier que le preview fonctionne toujours ailleurs (forum, mp, etc.)
* Quand vous testez un preview le markdown et les formules doivent fonctionner.

2016-12-24 12:33 UTC, artragis commented on zds/member/tests/tests_views.py
> +        self.assertEqual(200, response.status_code)
Un petit texte montrant la présence d'une bonne donnée serait agréable. Du coup je pense qu'il faudrait ajouter un élément à styler dans `biography`.

2017-01-08 17:10 UTC, artragis commented on zds/member/views.py
> +            if request.is_ajax():
serait-il possible de mettre `if 'preview' in request.POST and request.is_ajax()` afin de limiter le nombre de branches et la profondeur de l'indentation?

2017-01-08 17:11 UTC, artragis commented on zds/member/views.py
> +            if request.is_ajax():
(mauvaise manip : je remets mon commentaire) : ça serait bien de mettre fusionner les deux conditions.

2017-01-08 17:11 UTC, artragis commented on zds/tutorialv2/tests/tests_views.py
> +            }, HTTP_X_REQUESTED_WITH='XMLHttpRequest')
intéressant, je savais pas qu'on pouvais faire ça comme ça <3

2017-01-08 17:12 UTC, artragis commented on zds/tutorialv2/tests/tests_views.py
> +        self.assertTrue('<strong>markdown</strong>' in result_string)
`self.assertIn('<strong>markdown</strong>', result_string, 'We need the biography to be properly formatted')`

2017-01-08 17:13 UTC, Anto59290 commented on zds/member/views.py
> +            if request.is_ajax():
L'homme qui Code Review plus vite que son ombre :+1:

2017-01-08 17:17 UTC, Anto59290 commented on zds/tutorialv2/tests/tests_views.py
> +        self.assertTrue('<strong>markdown</strong>' in result_string)
C'est mieux en effet. Je m'étais basé sur ce qui est réalisé dans `test_add_note`, mais ce que tu propose est plus propre.

2017-01-08 17:20 UTC, artragis requested changes

2017-01-08 17:20 UTC, artragis commented on zds/tutorialv2/views/views_contents.py
> +                print(request.POST)
Je pense que ceci est une marque de debug.

si tu veux mettre une marque de debug, tu peux faire quelque chose comme : 

```python
logger.debug('Preview Mode %(preview)s with %(text)s', **request.POST)
```

2017-01-08 17:20 UTC, artragis commented on zds/tutorialv2/views/views_contents.py
> +        if form.is_valid():
je me demande à quel point il ne serait pas utile d'ajouter un petit message d'avertissement grâce à la méthode `messages.warning(self.request, 'ton message')` dans le cas où form n'est pas valide.

2017-01-08 17:20 UTC, artragis commented on zds/tutorialv2/views/views_contents.py
> +                content = render_to_response('misc/previsualization.part.html', {'text': request.POST.get('text')})
tu es sûr que c'est un render_to_response que tu veux, pas un render_to_string?

2017-01-08 17:20 UTC, artragis commented on zds/tutorialv2/views/views_contents.py
> +
oO pep8

2017-01-08 17:20 UTC, artragis commented on zds/tutorialv2/views/views_contents.py
> +        if 'preview' not in self.request.POST:
est-ce vraiment nécessaire?

2017-01-09 13:22 UTC, Anto59290 commented
Je crois que cette fois-ci je touche au but. J'ai pris en compte tous les commentaire. Le build fail à cause de l'erreur npm qui touche tout le monde.

2017-01-09 13:24 UTC, pierre-24 commented
Ok, je QA ça dès que j'ai 5 minutes (sauf si quelqu'un est plus motivé que moi)

2017-01-10 21:18 UTC, pierre-24 commented
Rapport de QA: OK, c'est *nickel* :)

Par contre, je vais faire mpn chiant : dans la partie tuto, tu répète énormément de fois le même bout de code : 

```diff
+    def post(self, request, *args, **kwargs):
 +        form = self.form_class(request.POST)
 +
 +        if 'preview' in request.POST:
 +            self.form_invalid(form)
 +            if request.is_ajax():
 +                content = render_to_string('misc/previsualization.part.html', {'text': request.POST.get('text')})
 +                return StreamingHttpResponse(content)
 +
 +        if form.is_valid():
 +            return self.form_valid(form)
```

Je me dis que ça serait sympa d'en faire un *mixin* ([comme celui là](https://github.com/Anto59290/zds-site/blob/f8dc0e78c6c8992cb988525448ff6421fec825f7/zds/tutorialv2/mixins.py#L161)), genre `FormWithPreview`. Je pense que ça serait un plus, et je suis désolé que ça te fasse un truc en plus à faire.

Le nec plus ultra aurait été de l'utiliser aussi dans les autres vues (forum et membre), mais elles sont pas en CBV, donc je m'en contenterai ;)

2017-01-11 05:48 UTC, Anto59290 commented
Bien vu ! Je n'y avais pas pensé. Je regarde cette affaire de mixin et propose une nouvelle version aujourd'hui ou demain ;)

2017-01-12 13:05 UTC, pierre-24 commented on zds/tutorialv2/mixins.py
> +        if form.is_valid():
Pour toute ce qui suis, pourquoi pas un `return super(FormWithPreview,self).post(request, *args, **kwargs)`, en fait ?

2017-01-12 13:06 UTC, pierre-24 commented on zds/tutorialv2/mixins.py
> +        if form.is_valid():
(oui, désolé, je pose des questions au fur et à mesure que ça me vient :-° )

2017-01-12 13:42 UTC, Anto59290 commented on zds/tutorialv2/mixins.py
> +        if form.is_valid():
Je te suis plus là. Tu veux remplacer quoi par `return super(FormWithPreview,self).post(request, *args, **kwargs)` ?

2017-01-12 13:57 UTC, pierre-24 commented on zds/tutorialv2/mixins.py
> +        if form.is_valid():
Toute la suite:

```diff
+        if form.is_valid():
+            return self.form_valid(form)
+        else:
+            messages.warning(self.request, _(u'Le formulaire est invalide.'))
+
+        return render(request, self.template_name, {'form': form})
```

Parce que là, j'ai juste l'impression que tu réécris [le code de la vue](https://ccbv.co.uk/projects/Django/1.8/django.views.generic.edit/FormView/#post) telle qu'il serait exécuté si tu faisais un `super(...)`. 

En faisant ça, on se prémunit contre un changement possible dans des versions futures de Django. Je pense que c'est mieux (sauf si tu as une bonne raison de le faire :) )

2017-01-12 14:04 UTC, Anto59290 commented on zds/tutorialv2/mixins.py
> +        if form.is_valid():
Ok, je comprend mieux. J'avais manqué ton **return** ça me paraissait bizarre du coup.

2017-01-12 14:15 UTC, Anto59290 commented
@pierre-24 : Voilà qui est fait. Merci pour la code review et les idées d'améliorations.

2017-01-12 19:03 UTC, pierre-24 commented
Ok pour moi, c'est parti :)

2017-01-12 19:03 UTC, merged

2017-01-12 19:45 UTC, vhf reviewed
Salut ! Est-ce qu'il serait encore possible de corriger ça dans une nouvelle PR ?

Merci !

2017-01-12 19:45 UTC, vhf commented on assets/js/ajax-actions.js
> +            {
Cette `{` devrait être à la ligne précédente.

2017-01-12 19:45 UTC, vhf commented on assets/js/ajax-actions.js
> +                var textSource = $btn.parent().prev().find(".preview-source");
Ça devrait être `var $textSource = …` ici.

2017-01-12 19:45 UTC, vhf commented on assets/js/ajax-actions.js
> +            {
`} else {`

2017-01-12 19:45 UTC, vhf commented on assets/js/ajax-actions.js
> +                if (textSource === null)
Tu es sûr que `textSource` peut être `null` ?

Il ne me semble pas.

2017-01-12 19:50 UTC, Anto59290 commented
Bien vu @vhf, je fait une PR prenant en compte tes remarques.