Fix 2743 : Ajout du temps de lecture aux contenus publiés
zestedesavoir/zds-site pull request #4093
Opened 2016-12-22 11:21 UTC by Anto59290

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | nouvelle fonctionnalité
| Ticket(s) (_issue(s)_) concerné(s)  | #2743 

### QA

* **Avant de tirer la branche créer un tutoriel avec un minimum de contenu (quelques faux paragraphes feront l'affaire) et valider le.** 
* Récupérez la branche (il est parfois nécessaire de redemarre l'appication pour que les nouveaux filtres soient pris en compte)
* Appliquez la migration
* Appliquez le script adjust_nb_letters
* Vérifiez que sur la page d'intro du tutoriel le temps de lecture estimé est bien affiché
* Créer un contenu avec un minimum de paragraphes et validez le 
* Vérifiez que sur la page du contenu le temps de lecture estimé est bien affiché

Je **crois qu'il me reste juste à éditer le fichier de mise à jour** pour expliquer les détails de la migration et du script.

Bonne QA !

2016-12-24 12:00 UTC, vhf requested changes
Super, merci !

Il va falloir internationaliser `minute_to_duration` :)

2016-12-24 12:29 UTC, artragis requested changes

2016-12-24 12:29 UTC, artragis commented on zds/tutorialv2/models/models_database.py
> +            logging.warning("could not get file %s to compute nb letters (error=%s)", md_file_path, e)
Salut,
c'est une très bonne chose de mettre du logging. Par contre pour une meilleure intégration à nos outils de reporting, il vaut mieux utiliser un logger personnalisé que le logger root.

Ainsi, en haut de page, après la liste des imports, il faut faire `logger = logging.getLogger('zds.tutorialv2')` et remplacer `logging.warning` par `logger.warning`.

2016-12-24 12:29 UTC, artragis commented on zds/tutorialv2/models/models_database.py
> +            current_content = PublishedContent.objects.filter(content_pk=self.content_pk, must_redirect=False).first()
Très bonne pratique.

2016-12-24 12:29 UTC, artragis commented on zds/tutorialv2/tests/tests_views.py
> +        self.assertEqual(published.get_nb_letter(md_file_path), 553)
C'est une bonne chose que tu aies ajouté ce test. Par contre je ne suis pas certain que rendre encore plus long qu'il ne l'est celui-là est mieux. D'autant que là on a typiquement un test unitaire alors que le gros test est un truc pas du tout unitaire.

2016-12-24 12:29 UTC, artragis commented on zds/tutorialv2/views/views_published.py
> +        context['reading_time'] = self.object.public_version.nb_letter / settings.ZDS_APP['content']['sec_per_minute']
juste pour être sûr : est-ce normal que la division soit une division entière et non une division flotante?

2016-12-24 12:29 UTC, artragis commented on zds/utils/templatetags/minute_to_duration.py
> +        import math
Salut,

étant donné qu'il n'y a pas de dépendance cyclique, nous préférons importer toutes les lib en tête de fichier. Cela augmente la lisibilité et cela permet à nos IDE de "folder" toute la partie import pour être plus confortable.

2016-12-24 12:29 UTC, artragis commented on zds/utils/templatetags/minute_to_duration.py
> +        if arg != 'long':
il serait préférable de renommer cette variable pour qu'on comprenne son but véritable.

2016-12-24 12:29 UTC, artragis commented on zds/utils/templatetags/minute_to_duration.py
> +
Je ne suis pas trop pour mettre des lignes après le else. On ne le fait casi jamais dans le code.

2016-12-24 12:29 UTC, artragis commented on zds/utils/templatetags/minute_to_duration.py
> +                hourSplitter = (len(durationString) > 0 and nextDurSplitter or '')
Avouons-le cette condition n'est pas très lisible.

2016-12-24 12:29 UTC, artragis commented on zds/utils/templatetags/minute_to_duration.py
> +        return 'Inconnu'
Il manque l'utilisation de ugettext ici. C'est ça que vhf ententait par "internationaliser".

2016-12-24 12:32 UTC, Anto59290 commented
Merci @artragis pour le code review, très complet ! Je note et intègre tes retours.

2016-12-24 13:12 UTC, Anto59290 commented on zds/utils/templatetags/minute_to_duration.py
> +                hourSplitter = (len(durationString) > 0 and nextDurSplitter or '')
On peut même dire que c'est incompréhensible.

2016-12-24 14:18 UTC, Anto59290 commented on zds/tutorialv2/views/views_published.py
> +        context['reading_time'] = self.object.public_version.nb_letter / settings.ZDS_APP['content']['sec_per_minute']
Alors j'ai bien refléchi suite à ton commentaire, j'allais changer ça en float quand je me suis rendu compte que ça n'aurait pas de sens.  Ici je travaille avec un nombre de minutes entière car je n'affiche pas un temps de lecture précis à la seconde. Si on passait en divison flottante les secondes "rajoutées" serait jetées par le template tag minute_to_duration.

2016-12-24 15:40 UTC, artragis commented
Ok,

comme je le disais c'était juste pour être certain. Comme je me posais 
la question, je préférais te la transmettre car c'est toi le codeur, tu 
as tout ce qu'il faut en tête maintenant.


Le 24/12/2016 à 15:18, Anto59290 a écrit :
>
> *@Anto59290* commented on this pull request.
>
> ------------------------------------------------------------------------
>
> In zds/tutorialv2/views/views_published.py 
> <https://github.com/zestedesavoir/zds-site/pull/4093>:
>
> > @@ -128,6 +128,8 @@ def get_context_data(self, **kwargs):
>           context['isantispam'] = self.object.antispam()
>           context['pm_link'] = self.object.get_absolute_contact_url(_(u'À propos de'))
>           context['subscriber_count'] = ContentReactionAnswerSubscription.objects.get_subscriptions(self.object).count()
> +        # We need reading time expressed in seconds
> +        context['reading_time'] = self.object.public_version.nb_letter / settings.ZDS_APP['content']['sec_per_minute']
>
> Alors j'ai bien refléchi suite à ton commentaire, j'allais changer ça 
> en float quand je me suis rendu compte que ça n'aurait pas de sens. 
> Ici je travaille avec un nombre de minutes entière car je n'affiche 
> pas un temps de lecture précis à la seconde. Si on passait en divison 
> flottante les secondes "rajoutées" serait jetées par le template tag 
> minute_to_duration.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4093>, or mute the 
> thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xYFEDVDGKR7dANtfTgnJlb9-X9nJks5rLSm6gaJpZM4LT4xq>.
>

2016-12-24 15:42 UTC, Anto59290 commented
Tous les retours sont intégrés. 
J'ai corrigé au passage cette typo : 
`article = PublishedContentFactory(type="ARTILCE", author_list=[self.user_author])`

C'est assez bizarre que ça puisse passer les tests vu que le type passé en argument n'est pas existant dans la collection de types possible.

2016-12-24 15:45 UTC, artragis commented
Les factory ne check pas le type. Ce sont des outils de test, on est 
sensé maîtriser ce qu'on fait.


Le 24/12/2016 à 16:42, Anto59290 a écrit :
>
> Tous les retours sont intégrés.
> J'ai corrigé au passage cette typo :
> |article = PublishedContentFactory(type="ARTILCE", 
> author_list=[self.user_author])|
>
> C'est assez bizarre que ça puisse passer les tests vu que le type 
> passé en argument n'est pas existant dans la collection de types possible.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4093#issuecomment-269089120>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xSbN3mlVLDG9p5v_SDvFRmaGJPqEks5rLT1agaJpZM4LT4xq>.
>

2017-01-08 01:53 UTC, AmarOk1412 commented
QA pour moi : **OK**,
merci @Anto59290

2017-01-08 07:54 UTC, merged

2017-01-08 08:09 UTC, pierre-24 commented
Zut. Pour une raison qui m'échappe, un test qui passait bien ne passe plus :s

2017-01-08 09:49 UTC, pierre-24 commented
Mmh. Si, en fait. Le contenu ne peut pas faire en permanence 178 caractères, et ce pour deux raisons : le titre est inclu (et celui si est généré avec un numéro, qui dépend du nombre de tests qui sont passés avant) et la date est incluse (le nombre de lettre dans le mois n'est jamais le même). Je tente un fix.

2017-01-21 16:45 UTC, vhf commented
@Anto59290 J'ai un problème avec la commande, cf. ci-dessous. Tu as une idée ?

```
(zdsenv)zds@zds-beta:/opt/zds/zds-site$ python manage.py adjust_nb_letters
Traceback (most recent call last):
  File "manage.py", line 57, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/zds/zds-site/zds/tutorialv2/management/commands/adjust_nb_letters.py", line 16, in handle
    logging.info('content %s got %d letters', content.title(), content.nb_letter)
  File "/opt/zds/zds-site/zds/tutorialv2/models/models_database.py", line 598, in title
    return self.load_public_version().title
  File "/opt/zds/zds-site/zds/tutorialv2/models/models_database.py", line 636, in load_public_version
    self.versioned_model = self.content.load_version(sha=self.sha_public, public=self)
  File "/opt/zds/zds-site/zds/tutorialv2/models/models_database.py", line 340, in load_version
    raise NotAPublicVersion
zds.tutorialv2.models.models_versioned.NotAPublicVersion
```

2017-01-21 17:05 UTC, pierre-24 commented
Pas moyen de savoir de quel contenu ils s'agit ? (Est ce que ça le fait de
suite ou est ce que d'autres fonctionnent ?)

On Jan 21, 2017 5:45 PM, "victor felder" <notifications@github.com> wrote:

> @Anto59290 <https://github.com/Anto59290> J'ai un problème avec la
> commande, cf. ci-dessous. Tu as une idée ?
>
> (zdsenv)zds@zds-beta:/opt/zds/zds-site$ python manage.py adjust_nb_letters
> Traceback (most recent call last):
>   File "manage.py", line 57, in <module>
>     execute_from_command_line(sys.argv)
>   File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
>     utility.execute()
>   File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/opt/zds/zdsenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
>     output = self.handle(*args, **options)
>   File "/opt/zds/zds-site/zds/tutorialv2/management/commands/adjust_nb_letters.py", line 16, in handle
>     logging.info('content %s got %d letters', content.title(), content.nb_letter)
>   File "/opt/zds/zds-site/zds/tutorialv2/models/models_database.py", line 598, in title
>     return self.load_public_version().title
>   File "/opt/zds/zds-site/zds/tutorialv2/models/models_database.py", line 636, in load_public_version
>     self.versioned_model = self.content.load_version(sha=self.sha_public, public=self)
>   File "/opt/zds/zds-site/zds/tutorialv2/models/models_database.py", line 340, in load_version
>     raise NotAPublicVersion
> zds.tutorialv2.models.models_versioned.NotAPublicVersion
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/4093#issuecomment-274272834>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHhjC94qv5LCkdKDvjijH0e8-cftfkOyks5rUjYkgaJpZM4LT4xq>
> .
>

2017-01-21 17:18 UTC, vhf commented
Il pourrait s'agir de ceci : https://zestedesavoir.com/articles/5/les-nombres-flottants-logarithmiques/

2017-01-21 17:22 UTC, Anto59290 commented
J'ai pas d'idée particulière qui me vienne à l'esprit. Par contre je peux télécharger l'archive de ce tuto et essayer en local avec pour voir si je peut reproduire ;)

2017-01-21 18:02 UTC, pierre-24 commented
Mmmh. Cette erreur sort quand on donne un sha (miaw) qui ne correspond pas
à la version publique, donc je vote pour une bizarrerie au niveau de la
BDD.  Après, je dis ça au vu de la stacktrace, je peu me tromper.

On Jan 21, 2017 6:22 PM, "Anto59290" <notifications@github.com> wrote:

> J'ai pas d'idée particulière qui me vienne à l'esprit. Par contre je peux
> télécharger l'archive de ce tuto et essayer en local avec pour voir si je
> peut reproduire ;)
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/4093#issuecomment-274275021>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHhjCyIIG1UcLVDJqpcbVyQqwlZjk1vUks5rUj6_gaJpZM4LT4xq>
> .
>

2017-01-31 21:35 UTC, vhf commented
Faudra penser à régler ce problème. La recherche ne peut pas fonctionner sans cette correction. Pour le moment je fix ça à la main sur la beta, mais c'est pas viable.

2017-02-01 06:06 UTC, Anto59290 commented
Perso, j'ai pas trop d'idée d'où ça peut venir. Sans plus d'infos ça va être compliqué à régler.

2017-02-01 07:03 UTC, Anto59290 commented
Tu fix ça comment quand tu t'en occupes ?

2017-02-01 07:05 UTC, vhf commented
Je wrap tout le contenu du for de la commande à lancer dans un Try / Except.