Recherche via Elasticsearch
zestedesavoir/zds-site pull request #4096
Opened 2016-12-24 13:40 UTC by pierre-24

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | évolution
| Ticket(s) (_issue(s)_) concerné(s)  | #3748 #3725 #3625 #3549 #3386 #3393 #3310 #2769 

**Joyeux noël, zeste de savoir !** Ça fait 2 mois que je me suis proposé, mais cette fois-ci, c'est officiel, je m'y attaque. But du jeu : virer Solr et utiliser elasticsearch !

### Pourquoi ?

+ Possibilité de booster des champs ou des types de document ;
+ Possibilité d'utiliser des `analyzer` et des `tokenizer` particulièrement puissants ;
+ Possibilité d'indexer facilement des classes qui ne sont pas de Django
+ (...)

### Comment ?

+ En virant solr et haystack, et en se basant directement sur les API's ["bas niveau"](https://github.com/elastic/elasticsearch-py) et ["plus haut niveau"](https://github.com/elastic/elasticsearch-dsl-py) directement écrites en python et maintenues par l'équipe d'elastic *itself* (ce qui évite d'avoir à attendre la mise à jour, puisque l'API est mise à niveau en même temps que le produit) ;
+ En faisant un peu de CBV, avec un *mixin* et des méthodes à surclasser (depuis la ZEP-12, je suis accro)
+ En tapant les différents types dans le même *index* d'elastisearch (les différents modèles étant différenciés par leur *type*) afin de pouvoir facilement faire des recherches sur tout les modèles en même temps (même si elastic permet de la recherche multiindex).
+ En implémentant un mécanisme pour ne réindexer que ce qui est vraiment necessaire (donc juste les données qui ont changé).
+ En tentant d'éviter un maximum les allez-retour entre BDD "traditionnelle" et elastic, au niveau de l'indexation et au niveau de la recherche elle-même (dans l'idéal, la recherche ne devrait faire aucun appel à la BDD, juste à elastic, quitte à stocker des infos supplémentaires dans elastic avec `index="not_analyzed"`).
+ En indexant enfin de manière correcte les contenus, sans devoir repasser par la BDD.

### TODO

Pour le moment, j'ai fait comme avec la ZEP-12, je travaille sur `zds/search2/` pour éviter les *rebases* trop chiants (même si il y en aura).

- [x] les *mixins*
- [x] le mécanisme de *flagging*
- [x] les commandes d'indexations
- [ ] le modèle et la vue de recherche (en combinant les dizaines de champs à considérer)
- [ ] la documentation (utilisateur **et** code!)
- [ ] la sécurité (faudrait implémenter un `.htaccess`, *help*) et le passage par *systemd* (*help!*).
- [ ] définitevement virer solr et haystack.

### À discuter

- [ ] Qu'est ce qu'on indexe comme modèle ?
- [ ] Qu'est ce qu'on indexe comme champ pour chacun de ces modèles ?
- [ ] Qu'est ce qu'on booste comment ?
- [ ] Qu'est ce qu'on utilise comme *tokenizer* et *analyzer* ?
- [ ] Est ce qu'on en profite pour modifier le front de la recherche ?
- [ ] Est ce que si tout fonctionne, on peut récupérer la barre en page d’accueil (quitte à *tuner* le comportement pour favoriser la recherche par mots-clés).

Sujet sur le forum à venir, probablement demain, sauf si @vhf préfère pas.

### QA

Pour le moment, c'est pas facile à tester, parce qu'il y a que l'indexation qui est implémentée, sur un nombre ridiculement faible de champs.

+ Téléchargez et installez [elasticsearch](https://www.elastic.co/downloads/elasticsearch) et [kibana](https://www.elastic.co/downloads/kibana). Installez et lancez le premier (port 9200) puis le second (port 5601).
+ Mettez à jour vos *requirements* et vos *migrations*
+ Indexez les *topics* et *post* des forums (seules données indexées pour le moment) à l'aide de `python ./manage.py es_manager index-all` (le nombre de ligne correspond au nombre de données indexées). Une fois que c'est fait, vous pouvez vous amuser à créer des *topics* et des *posts* et utiliser `python ./manage.py es_manager index-flagged` pour mettre à jour elastic. Normalement, vous devez remarquer que le nombre de ligne est moins important ;)

--------

**Pour jouer avec les données indexées**

Dans kibana (s'il est démarré), en navigant vers [http://localhost:5601/app/kibana#/dev_tools/console?_g=()](http://localhost:5601/app/kibana#/dev_tools/console?_g=()) vous pouvez jouer avec `GET /zds_search/_search`

Par exemple, pour visualiser toutes les données indexées:

```
GET /zds_search/_search
{
  "query": {
    "match_all": {
    }
  }
}
```

Pour resortir tout les post contenant "test" ou les topics dont le titre contient "test" (heureusement, y'a une API python pour écrire ce genre de recherches simplement, parce que ça devient vite l'horreur).

```
GET /zds_search/_search
{
  "query": {
    "bool": {
      "should": [
        {"match": {"title":"test"}},
        {"match": {"text":"test"}}
      ]
    }
  }
}
```

... Et ainsi de suite si vous connaissez un peu elastic.

2016-12-24 13:41 UTC, pierre-24 commented on requirements.txt
> +elasticsearch>=2.0.0,<3.0.0
Bon, ça, c'est moche, faut que je me fixe une version et que je m'y tienne.

2016-12-24 13:55 UTC, Anto59290 commented
Salut Pierre,

C'est surement pas la priorité mais tu peux noter ça dans quel modèle indexer : #2807.

2016-12-24 14:36 UTC, pierre-24 commented
C'est noté ;)

2016-12-24 15:43 UTC, artragis commented on requirements.txt
> +elasticsearch>=2.0.0,<3.0.0
Tu es en dev, tu mettras la dernière version en date lorsque le WIP sera terminée. (pip freeze tout ça)

2016-12-24 16:00 UTC, artragis requested changes

2016-12-24 16:00 UTC, artragis commented on zds/forum/migrations/0011_auto_20161224_1310.py
> +from __future__ import unicode_literals
tu sais que je t'aime toi.

2016-12-24 16:00 UTC, artragis commented on zds/search2/models.py
> +class ESDjangoIndexableMixin(ESIndexableMixin, models.Model):
Je ne suis pas trop pour dire que c'est un modèle puisque sa sémantique c'est "Mixin".

Maintenant ma relecture ne fait que commencer, peut-être me fourvoie-je.

2016-12-24 16:00 UTC, artragis commented on zds/search2/management/commands/es_manager.py
> +        elif options['action'] == 'index-flagged':
Du coup j'ai pas compris cette notion de "flagged". Peux-tu l'expliquer?

2016-12-24 16:00 UTC, artragis commented on zds/search2/models.py
> +        for base in cls.__bases__:
serait-il possible d'ajouter un `logger.debug("will iter into %s", cls.__bases__)` avant la boucle et un `logger.debug("content type is %", content_type")` lorsque la boucle est matchée.

de plus en mode "micro optimisation mais au moins on comprend explicitement la volonté du développeur", peux-tu ajouter un "break" s'il te plait?

2016-12-24 16:00 UTC, artragis commented on zds/search2/models.py
> +        m = Mapping(self.get_es_content_type())
Sûrement dû au fait que c'est le début du développement. Mais ce n'est jamais une bonne chose de garder des variable monolettrales. (c'est noël,  offrons un nouveau mot à notre langue :p)

2016-12-24 16:00 UTC, artragis commented on zds/search2/models.py
> +            if exclude_field and field in exclude_field:
afin de faire en sorte que cette condition fonctionne aussi dans le cas où exclude_field vaut None, je propose:

```python
excluded_fields = excluded_fields or []  # please note the renaming into excluded_field, let's offer vhf a christmas english code
for field in fields:
    if field in excluded_fields:
        continue
    # next
```

2016-12-24 16:00 UTC, artragis commented on zds/search2/models.py
> +            v = getattr(self, field, None)
Même si le "v" est une sémantique habituelle de "value", je pense que renommer en "value" ne coûtera pas trop cher et rendra le code pérenne.

2016-12-24 16:00 UTC, artragis commented on zds/search2/models.py
> +            print(hit)
oh? un print. Il faudra le remplacer par un log.info/log.debug.

2016-12-24 16:48 UTC, Anto59290 commented
Petite question : comment vas-tu gérer les topics/forums privés dans la recherche. Ne pas les indexer du tout ? Ou alors les indexer et choisir de les afficher en fonction de l'utilisateur (staff ou non) ? J'imagine que ça va peut être t'obliger à indexer des champs supplémentaires ?

2016-12-24 16:50 UTC, SpaceFox commented
Fonctionnellement il faut tout indexer et masquer les résultats auxquels
l'utilisateur n'a pas droit. Sinon la recherche est pétée pour les
utilisateurs avec des droits spéciaux.

Le 24 déc. 2016 5:48 PM, "Anto59290" <notifications@github.com> a écrit :

> Petite question : comment vas-tu gérer les topics/forums privés dans la
> recherche. Ne pas les indexer du tout ? Ou alors les indexer et choisir de
> les afficher en fonction de l'utilisateur (staff ou non) ? J'imagine que ça
> va peut être t'obliger à indexer des champs supplémentaires ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-269091532>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFhKnFPwK_OEiUQkoDlIHEuRI-VHnjMWks5rLUzOgaJpZM4LVOk9>
> .
>

2016-12-24 16:53 UTC, artragis commented
Autre technique : on indexe tout dont le champ groupe si l'utilisateur 
ne fait pas partie d'un groupe on ne requête que les éléments qui n'ont 
pas de groupe. Sinon, on prend tous ceux qui n'ont pas de groupe ou dont 
l'un des groupes est le groupe de l'utilisateur.

Le langage de requêtage elasticsearch le permet.


Le 24/12/2016 à 17:50, SpaceFox a écrit :
> Fonctionnellement il faut tout indexer et masquer les résultats auxquels
> l'utilisateur n'a pas droit. Sinon la recherche est pétée pour les
> utilisateurs avec des droits spéciaux.
>
> Le 24 déc. 2016 5:48 PM, "Anto59290" <notifications@github.com> a écrit :
>
> > Petite question : comment vas-tu gérer les topics/forums privés dans la
> > recherche. Ne pas les indexer du tout ? Ou alors les indexer et 
> choisir de
> > les afficher en fonction de l'utilisateur (staff ou non) ? J'imagine 
> que ça
> > va peut être t'obliger à indexer des champs supplémentaires ?
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > 
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-269091532>,
> > or mute the thread
> > 
> <https://github.com/notifications/unsubscribe-auth/AFhKnFPwK_OEiUQkoDlIHEuRI-VHnjMWks5rLUzOgaJpZM4LVOk9>
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-269091600>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xQB6-8Kr48LJRwqgsb7o239MWnWKks5rLU1GgaJpZM4LVOk9>.
>

2016-12-24 16:59 UTC, artragis commented
**attention ceci est une réflexion à chaud d'une perssonne qui n'a pas l'expérience ou l'expertise nécessaire dans elasticsearch.**

Pour ce qui est des tokenizers : il me semble que @cgabard a rendu le moteur de markdown capable de gérer un AST ou du moins de générer des méta info bien sympa. On pourrait donc wrapper ce système dans un adaptateur qui permettrait de générer un tokenizing intéressant qui boosterait les mot en fonctions de : 

- est-ce dans le titre principal (s'applique à : contenu, partie, chapitre, extrait, topic)
- est-ce dans un titre textuel (élément qui commence par # ou ## => plus il y a de # plus la priorité est faible) 
- est-ce un paragraphe/le titre d'un tableau/d'une figure

2016-12-24 17:23 UTC, vhf commented
Faisable, mais je propose qu'on s'y penche dans un 2e temps. :+1:

2016-12-24 17:33 UTC, artragis commented
Clairement .  mon message était juste pour dire qu'elasticsearch n'offrait
aucun blocage pour cette problématique là. vue la quantité de texte dans
zds on pourrait presque avoir une stack 100% elasticsearch sans passer par
sql.

Le 24 déc. 2016 6:23 PM, "victor felder" <notifications@github.com> a
écrit :

> Faisable, mais je propose qu'on s'y penche dans un 2e temps. 👍
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-269092953>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABc_xdvbpbrUizWk44dnXk_ce97Cdw46ks5rLVT5gaJpZM4LVOk9>
> .
>

2016-12-24 23:59 UTC, pierre-24 commented on zds/search2/models.py
> +class ESDjangoIndexableMixin(ESIndexableMixin, models.Model):
Je sais plus trop si j'ai vraiment besoin de mettre le `model.Model` (parce que je surclasse `save()`, par exemple) ou si c'est juste une facilité. Je crois que j'ai changé d'avis à un moment mais que j'ai pas tout modifié. Je testerai :)

2016-12-24 23:59 UTC, pierre-24 commented on zds/search2/models.py
> +            print(hit)
Oui :)

2016-12-25 00:01 UTC, pierre-24 commented on zds/search2/management/commands/es_manager.py
> +        elif options['action'] == 'index-flagged':
Ben en gros, ça évite de réindexer ce qui est déjà indexé et qui à priori n'a pas changé. Lorsqu'on récupère les objets à indexer, on ne récupère que ceux qui sont à `es_flagged=True`. C'est le `must_reindex` de solr, que d'ailleurs j'aurais probablement du appeller pour ça, mais je me suis fourvoyé avec l'option coté solr, qui s'appelle `--only-flagged`.

2016-12-25 00:03 UTC, pierre-24 commented
W Petite question : comment vas-tu gérer les topics/forums privés dans la recherche. Ne pas les indexer du tout ? Ou alors les indexer et choisir de les afficher en fonction de l'utilisateur (staff ou non) ? J'imagine que ça va peut être t'obliger à indexer des champs supplémentaires ?

Je vais dans le sens des réponses de @SpaceFox et  @artragis , tout dois être indexé. Mais comme je dis, faut que je lance un topic avec une réflexion globale sur le sujet :)

2016-12-25 00:04 UTC, pierre-24 commented on zds/forum/migrations/0011_auto_20161224_1310.py
> +from __future__ import unicode_literals
<3

2016-12-25 00:04 UTC, pierre-24 commented on zds/search2/models.py
> +        for base in cls.__bases__:
Oui ;)

2016-12-25 00:05 UTC, pierre-24 commented on zds/search2/models.py
> +            if exclude_field and field in exclude_field:
ah, et très objectivement, je le comprend comme `exclude a field` et pas comme `a field is exluded`. Mais chui pas bien dans ma tête :p

2016-12-25 00:13 UTC, pierre-24 commented on zds/search2/models.py
> +class ESDjangoIndexableMixin(ESIndexableMixin, models.Model):
Ouais, je confirme, si je le met pas, j'ai des ennuis. Du coup, soit je change le mot `Mixin` pour autre chose, soit je trouve une autre manière de dériver `save()`

2016-12-25 00:49 UTC, vhf commented on zds/search2/models.py
> +            if exclude_field and field in exclude_field:
"Exclude a field" est une action, ça pourrait être une fonction ou méthode. Ici la variable contient "an excluded field". ;)

2016-12-25 09:08 UTC, artragis commented on zds/search2/models.py
> +class ESDjangoIndexableMixin(ESIndexableMixin, models.Model):
Bah plutôt que Mixin je pense que "Abstract" est une bonne chose. D'autant que tu utilises l'attribut de django "abstract = True".

2016-12-25 16:05 UTC, vhf commented
A choisir, je préfère qu'on ouvre une issue pour discuter de ça plutôt qu'un topic, ça permet d'avoir un lien entre la PR, le repo et la discussion justifiant les choix qu'on fera. :)

2016-12-25 16:34 UTC, pierre-24 commented
M'en doutais que t'allais dire ça :p

Je le fais, parce que j'ai envie d’essayer, mais je trouve que la question "qu'est ce que vous voulez comme résultat d'une recherche" (sans les détails techniques) devrait également être posée sur le forum. @FanJiyong , je te laisse décider de ça :-)

2016-12-27 13:02 UTC, artragis commented on zds/search2/management/commands/es_manager.py
> +        elif options['action'] == 'index-flagged':
Merci :+1:

2016-12-27 13:04 UTC, artragis commented on zds/search2/models.py
> +        """Create a document as formatted in a ``_bulk`` operation. Formatting is done based on action.
very good idea

2016-12-27 13:08 UTC, artragis commented on zds/search2/models.py
> +        if action == 'update':
elif est ici plus logique

2016-12-27 13:08 UTC, artragis commented on zds/tutorialv2/models/models_database.py
> +class FakeChapter(AbstractESIndexable):
Juste : pourquoi Fake?

2016-12-27 14:32 UTC, pierre-24 commented on zds/search2/models.py
> +        if action == 'update':
Yup :)

2016-12-27 14:32 UTC, pierre-24 commented on zds/tutorialv2/models/models_database.py
> +class FakeChapter(AbstractESIndexable):
Bonne question. Parce que c'est pas le vrai conteneur mais une version *batarde* ?

2016-12-27 14:34 UTC, pierre-24 commented on zds/search2/models.py
> +        """Create a document as formatted in a ``_bulk`` operation. Formatting is done based on action.
Je fais ce que je peux pour pas tuer ES ;)

2016-12-27 21:00 UTC, artragis commented on zds/tutorialv2/models/models_database.py
> +class FakeChapter(AbstractESIndexable):
En re re relisant, j'ai compris: c'est une sorte de chapitre fantôme que tu utilisais pour toujours avoir un chapitre même quand on a un article.

2016-12-28 09:23 UTC, artragis requested changes

2016-12-28 09:23 UTC, artragis commented on zds/search2/management/commands/es_manager.py
> +            'action', type=str, help='action to perform, either "setup", "clear", "index-all" or "index-flagged"')
Sais-tu que l'argument "choices" existe et te permettra de définir les options disponibles?

2016-12-28 10:45 UTC, pierre-24 commented on zds/search2/management/commands/es_manager.py
> +            'action', type=str, help='action to perform, either "setup", "clear", "index-all" or "index-flagged"')
Non. Et pourtant, dieu sais que j'utilise `argparse` :-°

2016-12-28 10:52 UTC, artragis commented
j'ai découvert ça hier avec uncollègue :p

Le 28/12/2016 à 11:45, Pierre Beaujean a écrit :
>
> *@pierre-24* commented on this pull request.
>
> ------------------------------------------------------------------------
>
> In zds/search2/management/commands/es_manager.py 
> <https://github.com/zestedesavoir/zds-site/pull/4096>:
>
> >      def add_arguments(self, parser):
> -        parser.add_argument('action', type=str)
> +        parser.add_argument(
> +            'action', type=str, help='action to perform, either "setup", "clear", "index-all" or "index-flagged"')
>
> Non. Et pourtant, dieu sais que j'utilise |argparse| :-°
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4096>, or mute the 
> thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xaqeBAdLmnFib2loqepoyeDmGES2ks5rMj3jgaJpZM4LVOk9>.
>

2016-12-29 16:53 UTC, pierre-24 commented
Bon, ça avance. Cette fois, on peut commencer à exploiter ES pour chercher ... N'importe comment puisque c'est pas *boosté*. Mais on peut :)

2016-12-30 10:39 UTC, artragis commented on zds/search2/views.py
> +                    if model == 'topic':
Je ne sais pas si c'est ce qu'il y aurait de mieux mais du coup pourquoi pas : 

`part_querysets.append(get_attr("get_queryset_{}s".format(model), self))`

2016-12-30 11:36 UTC, pierre-24 commented on zds/search2/views.py
> +                    if model == 'topic':
Pour le principe, je préfère :)

2016-12-30 19:26 UTC, pierre-24 commented
Bon. Côté code, c'est à peu près tout, à l'un ou l'autre détail près ('faut que je rajoute des lignes de log un peu partout). Donc c'est le moment de commencer à me taper dessus :) 

C'est aussi à peu près fonctionnel, donc si vous avez un peu de temps à perdre, n'hésitez pas. Elasticsearch est vraiment pas compliqué à installer, en tout cas sous Linux. Si il y a des aventuriers qui veulent tester sous Windows, avec plaisir, j'en aurai besoin pour la doc :)

2016-12-31 08:31 UTC, artragis commented
>la sécurité (faudrait implémenter un .htaccess, help) et le passage par systemd (help!).

on n'utilise pas apache donc .htaccess ne semble pas approprié.

pour ce qui est de systemd, que désires-tu mettre en place? Ca me déplairait pas de te faire une PR pour t'aider sur ce point.

2016-12-31 08:49 UTC, pierre-24 commented
> on n'utilise pas apache donc .htaccess ne semble pas approprié.

... Ou équivalent. Je veux dire que part défaut, si on laisse le port 9200 ouvert, n'importe qui pourrait faire n'importe quoi sur notre BDD elasticsearch. Faut donc un mécanisme "à la .htaccess" qui demande login et mot de passe :) (tout ça parce que leur extention qui fait le coup, [x-pack](https://www.elastic.co/products/x-pack), est payante). 

> pour ce qui est de systemd, que désires-tu mettre en place? Ca me déplairait pas de te faire une PR pour t'aider sur ce point.

Ben la même chose que pour solr, donc un service, sauf que j'ai aucune idée de comment ça se fait :-°

2016-12-31 10:09 UTC, artragis commented
Ok, je m'occupe du systemd. et ça suffira logiquement, puisqu'il suffira 
de dire à systemd que le port n'est bindé que sur 127.0.0.1 plutôt que 
sur 0.0.0.0.


Le 31/12/2016 à 09:49, Pierre Beaujean a écrit :
>
>     on n'utilise pas apache donc .htaccess ne semble pas approprié.
>
> ... Ou équivalent. Je veux dire que part défaut, si on laisse le port 
> 9200 ouvert, n'importe qui pourrait faire n'importe quoi sur notre BDD 
> elasticsearch. Faut donc un mécanisme "à la .htaccess" qui demande 
> login et mot de passe :) (tout ça parce que leur extention qui fait le 
> coup, x-pack <https://www.elastic.co/products/x-pack>, est payante).
>
>     pour ce qui est de systemd, que désires-tu mettre en place? Ca me
>     déplairait pas de te faire une PR pour t'aider sur ce point.
>
> Ben la même chose que pour solr, donc un service, sauf que j'ai aucune 
> idée de comment ça se fait :-°
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-269856104>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xcA_MwnltUd8-7vwd3RmxjWRCfGpks5rNhcFgaJpZM4LVOk9>.
>

2016-12-31 10:39 UTC, firm1 commented
> Ou équivalent. Je veux dire que part défaut, si on laisse le port 9200 ouvert, n'importe qui pourrait faire n'importe quoi sur notre BDD elasticsearch. Faut donc un mécanisme "à la .htaccess" qui demande login et mot de passe :) (tout ça parce que leur extention qui fait le coup, x-pack, est payante).

Pour le coup, si on garde ES sur le même serveur que l'app django comme c'est le cas avec Solr aujourd'hui, il suffit de laisser ES qui bind sur `127.0.0.1` [comme c'est le cas par défaut sur les récentes versions d'ES](https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html#network.host).

On a donc pas besoin d'implémenter une sorte de htaccess puisque ES ne sera pas atteignable en dehors du serveur.

2016-12-31 11:10 UTC, pierre-24 commented
> On a donc pas besoin d'implémenter une sorte de htaccess puisque ES ne sera pas atteignable en dehors du serveur.

Ça marche. Tient, toi, t'as déjà joué avec ES, en vrai ? Parce que j'ai pas vraiment d'idée concernant le nombre de *shards* et de *replicas*. J'ai laissé 5 et 1, mais j'ai mon pauvre *set* d'une centaine de données, rien de comparable avec les quelques milliers de posts, par exemple :)

2016-12-31 11:41 UTC, SpaceFox commented
Il suffit surtout de ne.pas ouvrir le port…

Le 31 déc. 2016 12:10 PM, "Pierre Beaujean" <notifications@github.com> a
écrit :

> On a donc pas besoin d'implémenter une sorte de htaccess puisque ES ne
> sera pas atteignable en dehors du serveur.
>
> Ça marche. Tient, toi, t'as déjà joué avec ES, en vrai ? Parce que j'ai
> pas vraiment d'idée concernant le nombre de *shards* et de *replicas*.
> J'ai laissé 5 et 1, mais j'ai mon pauvre *set* d'une centaine de données,
> rien de comparable avec les quelques milliers de posts, par exemple :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-269860321>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFhKnJ4pz1Iu_R4JjqKGWDhKpJLWziaWks5rNjg7gaJpZM4LVOk9>
> .
>

2016-12-31 11:55 UTC, firm1 commented
> Parce que j'ai pas vraiment d'idée concernant le nombre de shards et de replicas. J'ai laissé 5 et 1, mais j'ai mon pauvre set d'une centaine de données, rien de comparable avec les quelques milliers de posts, par exemple :)

Techniquement il n y aura qu'un nœud (on a pas besoin d'un cluster ici) donc la question du nombre de repliqua est réglée. 1 répliqua parce que 1 nœud.

Pour le nombre de shard, vu que tu as l'air de _bulker_ souvent, 3 shard devrait suffire. Pas besoin d'aller jusqu'a 5, car sur un noeud, ça n'a pas vraiment d'intéret, car tu recopie 5 fois inutilement ton information.

2016-12-31 12:54 UTC, pierre-24 commented
> 1 répliqua parce que 1 nœud.

J'avais compris que si un réplica, faut au moins 2 noeuds (mon statuts est toujours jaune quoiqu'il arrive, j'ai cru que c'était la raison).

> Pour le nombre de shard, vu que tu as l'air de bulker souvent, 3 shard devrait suffire. Pas besoin d'aller jusqu'a 5, car sur un noeud, ça n'a pas vraiment d'intéret, car tu recopie 5 fois inutilement ton information.

Ok, merci. Je vais mettre ça dans le `settings.py` d'une manière ou d'une autre, et on pourra tuner au besoin (par contre, si on change, on doit tout réindexer).

2017-01-02 13:54 UTC, pierre-24 commented
Grâce à @Situphen on a même droit à une petite amélioration du formulaire, pour qu'il aie plus le look de la recherche en page d’accueil:

![screenshot from 2017-01-02 14 54 28](https://cloud.githubusercontent.com/assets/7889675/21590355/62e48880-d0fb-11e6-8f50-0e5726fa832b.png)

(oui, avec les suggestions, c'est gratuit)

![screenshot from 2017-01-02 14 49 35](https://cloud.githubusercontent.com/assets/7889675/21590340/4e24afec-d0fb-11e6-8b80-fdb345483593.png)

2017-01-02 18:12 UTC, artragis commented
Pour ce qui est de systemd.
Il semblerait que par défaut elastic search soit fourni avec un bon fichier de type systemd.

Il suffira donc de faire 

```bash
sudo systemctl enable elasticsearch
sudo systemctl start elasticsearch
```

Ces lignes doivent suffir à être ajoutée dans le fichier update.md.

2017-01-02 18:37 UTC, pierre-24 commented
... Même si on prend ES du site et pas du gestionnaire de paquets ?

2017-01-02 18:46 UTC, artragis commented
>Même si on prend ES du site et pas du gestionnaire de paquets ?

hein?

2017-01-02 18:48 UTC, pierre-24 commented
Chui vraiment une quiche en systemd, mais d'ou qu'il sort le "bon fichier de type systemd", pour le demander autrement ?

2017-01-02 19:02 UTC, artragis commented
dans les package par défaut il est généré. Il ressemble à ça : 

```
[Unit]
Description=ElasticSearch 
After=syslog.target network.target remote-fs.target nss-lookup.target

[Service]
Type=forking
EnvironmentFile=/etc/default/elasticsearch
User=elasticsearch
Group=elasticsearch
PIDFile=/var/run/elasticsearch/elasticsearch.pid
ExecStart=/usr/share/elasticsearch/bin/elasticsearch -d -p /var/run/elasticsearch/elasticsearch.pid -Des.default.config=$CONF_FILE -Des.default.path.home=$ES_HOME -Des.default.path.logs=$LOG_DIR -Des.default.path.data=$DATA_DIR -Des.default.path.work=$WORK_DIR -Des.default.path.conf=$CONF_DIR
# See MAX_OPEN_FILES in /etc/default/elasticsearch
LimitNOFILE=65535
# See MAX_LOCKED_MEMORY in /etc/default/elasticsearch, use "infinity" when     MAX_LOCKED_MEMORY=unlimited and using bootstrap.mlockall: true
#LimitMEMLOCK=infinity
# Shutdown delay in seconds, before process is tried to be killed with KILL (if configured)
TimeoutStopSec=20

[Install]
WantedBy=multi-user.target

```

2017-01-02 21:23 UTC, firm1 commented
Pour répondre aux interrogation sur systemd. Comme le précise @artragis sur debian, le package `deb` contient la configuration `systemd` qui va bien, avec même un fichier `init.d` en fallback si vous voulez. Ce qui permet de démarrer/arrêter le service elasticsearch. 

Par contre, là ou @pierre-24 a raison de s'inquiéter, c'est qu'il faudrait une configuration systemd qui rajoute les commandes d'indexations dans le calendrier systemd de manière à ce que l'indexation se lance de manière périodique par systemd. Si le nom des commandes n'a pas changé, il n'ya rien besoin de faire, si par contre il y'a de nouvelles commandes d'indexation (`python manage.py blabla`) penser à les rajouter dans le calendrier et ne pas oublier supprimer les commandes obsolètes.

2017-01-02 21:46 UTC, pierre-24 commented
> c'est qu'il faudrait une configuration systemd qui rajoute les commandes d'indexations dans le calendrier systemd de manière à ce que l'indexation se lance de manière périodique par systemd. Si le nom des commandes n'a pas changé, il n'ya rien besoin de faire, si par contre il y'a de nouvelles commandes d'indexation (python manage.py blabla) penser à les rajouter dans le calendrier et ne pas oublier supprimer les commandes obsolètes.

... Évidement que les commandes ont changés :) En plus, je sais pas trop quel version de ES est dispo dans les dépôts, je comptais utiliser la version disponible sur le site, soit la 5.1 avec laquelle je vais mes tests actuellement.

2017-01-02 22:04 UTC, firm1 commented
Je viens de vérifier sur une debian8. la version disponible que j'ai en stable est la version `1.0.3`. C'est à dire une antiquité comparé à la version actuelle.

Le plus simple/efficace je pense pour la prod sera de télécharger le fichier deb, et de faire un `apt-get install`. Attention la version 5.1 a comme prérequis Java8 sur le serveur, il faudra penser à l'installer (si ce n'est pas déjà fait)

2017-01-02 22:08 UTC, vhf commented
On a la `1.6.2` dans les backports. Je crois pas qu'on puisse aller plus haut. Je suis d'avis de bien tester sur `1.6.2` et si c'est pas complètement impossible de modifier la PR en conséquence pour que ça passe sur `1.6.2`.

2017-01-02 22:16 UTC, SpaceFox commented
La 1.6.2 n'est déjà plus supportée, et de mémoire le passage à la v2 a
changé pas mal de choses (cf
https://en.wikipedia.org/wiki/Elasticsearch#History)

2017-01-02 23:08 GMT+01:00 victor felder <notifications@github.com>:

> On a la 1.6.2 dans les backports. Je crois pas qu'on puisse aller plus
> haut. Je suis d'avis de bien tester sur 1.6.2 et si c'est pas
> complètement impossible de modifier la PR en conséquence pour que ça passe
> sur 1.6.2.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-270025379>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFhKnOtQACwt0yUfhn4G3IRG1HR3yjVJks5rOXVFgaJpZM4LVOk9>
> .
>

2017-01-03 06:36 UTC, artragis commented
Surtout qu'on est en version 5.X en officiel.

Effectivement va falloir installer elasticsearch à la main.

Je regarde pour créer les bons fichiers systemd et je te fais une PR.


Le 02/01/2017 à 23:16, SpaceFox a écrit :
> La 1.6.2 n'est déjà plus supportée, et de mémoire le passage à la v2 a
> changé pas mal de choses (cf
> https://en.wikipedia.org/wiki/Elasticsearch#History)
>
> 2017-01-02 23:08 GMT+01:00 victor felder <notifications@github.com>:
>
> > On a la 1.6.2 dans les backports. Je crois pas qu'on puisse aller plus
> > haut. Je suis d'avis de bien tester sur 1.6.2 et si c'est pas
> > complètement impossible de modifier la PR en conséquence pour que ça 
> passe
> > sur 1.6.2.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > 
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-270025379>,
> > or mute the thread
> > 
> <https://github.com/notifications/unsubscribe-auth/AFhKnOtQACwt0yUfhn4G3IRG1HR3yjVJks5rOXVFgaJpZM4LVOk9>
> > .
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-270026044>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xWa_sNIahTxKR67qysGuMbhu5FdNks5rOXdUgaJpZM4LVOk9>.
>

2017-01-03 06:54 UTC, vhf commented
J'ai l'impression que c'est une situation typique avec Debian. Je préfère éviter d'utiliser des paquets pas supportés par Debian pour être certain d'avoir les màj de sécurité. Seulement les trucs dans les paquets Debian sont supportés par Debian mais plus par leur auteur.

Ok pour la version que vous voulez, à condition d'utiliser le repo officiel d'ES. Mais du coup tout va bien, il semble que 5.1 y soit : https://www.elastic.co/guide/en/beats/libbeat/current/setup-repositories.html

2017-01-03 06:56 UTC, pierre-24 commented
1.6 ? Si j'avais voulu utiliser cette version, j'aurais utilisé Haystack :o 

Je vais tester l'installation par *repo* (j'avoue que j'avais pas fais comme ça) et je vous dis quoi :)

2017-01-03 07:37 UTC, pierre-24 commented
Question pour @vhf (ou autre qui a accès à la prod): quelle est la version de debian qu'on utilise ?

2017-01-03 07:39 UTC, vhf commented
8.6 @pierre-24

2017-01-03 07:40 UTC, pierre-24 commented
Merci, je vais me faire une VM avec ça pour tester :)

2017-01-03 12:31 UTC, artragis commented
Mais quoi qu'il arrive faut prendre la version 5.1, c'est useless de downgrader aussi fort.

2017-01-03 12:44 UTC, pierre-24 commented
De toute façon, ça irais pas. J'utilise des fonctionnalités qui sont au moins de la version 2.0, et parfois même de la 5.0 (par exemple, les champs sont passés de "string" à "text" en version 5.0 pour ne nommer que celui là). Donc *downgrader*, c'est non :)

2017-01-03 15:51 UTC, pierre-24 commented
Bon, si il y a des gens doués en orthographe qui veulent bien relire la doc, vous êtes les bienvenus :)

2017-01-03 18:53 UTC, vhf commented on doc/source/back-end/search2.rst
> +**L'indexation** des données consiste à **rassembler toutes les données** sur lesquelles l'utilisateur va **pouvoir rechercher**. Elle est faite au préalable.
… les données **dans** lesquelles …

2017-01-03 19:15 UTC, vhf requested changes
Première volée :)

Je m'occupe des autres fichiers plus tard.

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> +**L'indexation** des données consiste à **rassembler toutes les données** sur lesquelles l'utilisateur va **pouvoir rechercher**. Elle est faite au préalable.
… les données **dans** lesquelles …

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> +Celle-ci est faite de telle façon qu'on puisse rechercher sur les éléments suivants :
… rechercher **dans** …

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> + - Les contenus (article et tutoriels) ainsi que leur chapitres (s'il s'agit d'un moyen ou *big*-tuto);
… **leurs** chapitres …

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> + - Les réponses au sujets.
… **aux** sujets.

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> +Cette indexation est réalisée à intervalle régulier (et de manière à n'indexer que les données qui ont changé).
… ont **changées**).

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> +L'utilisateur peut utiliser la recherche, en utilisant la recherche de `l'en-tête  <../front-end/structure-du-site.html#l-en-tete>`_, ou de la page d'acceil, si elle est disponible.
… utiliser la recherche en passant par l'en-tête …, ou par ~~de~~ la page d'**accueil** …

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> +Des critères de recherche, peuvent être ajoutés sur la page de recherche.
Des critères de recherche peuvent être ajoutés …

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> +Il est possible de l'interoger à travers une interface de type REST à laquelle ont communique via des requêtes écrites en JSON.
**interroger**

à laquelle **on** communique

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> +Ce projet propose également des API `bas <https://github.com/elastic/elasticsearch-py>`_ et `plus haut <https://github.com/elastic/elasticsearch-dsl-py>`_ niveau en python pour interagir avec le serv
**maintenues**

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> +Ancienement, ZdS utilisait `Haystack <https://django-haystack.readthedocs.io/>`_, pour communiquer avec `Solr <http://lucene.apache.org/solr/>`_ (équivalent à Elasticsearch), mais ces solutions ont é
**Anciennement**, ZdS utilisait Haystack<> pour communiquer… ont été abandonnées<> par manque …

`<>`: pas de virgule ici

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> +Ces différents filtres permettent d'éliminer le superflu afin de ce concentrer sur l'essentiel (les *tokens* obtenus).
afin de **se** concentrer

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> +Par la suite, ES réalise une table (un *index*) reliant ses *tokens* aux documents, qu'il utilise pour la recherche.
(un *index inversé*)

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> ++ Enlève les tags HTML (en pratique, l'indexation du texte ce fait systématiquement sur le contenu parsé en HTML et non sur le texte en *markdown*) ;
**se** fait systématiquement

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> ++ Utilise une série de *token filter* orientés pour comprendre le français, parmis lequels un *stopper* (pour enlever les prépositions, déterminants, ...) et un *stemmer* (qui se charge, à partir d'u
**parmi lesquels**

**tous les quatres**

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> +Ces facteurs de *boosts* sont modifiables, soit directement dans le code de ZdS pour ce qui concernet les facteur de *boost* sur les champs (voir ci-dessous), soit dans le ``settings.py`` en ce qui c
ce qui **concerne** les **facteurs**

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> +La configuration de la connection et de l'*index* se fait dans le ``settings.py``, à l'aide des deux variables suivantes:
de la **connexion**

deux variable suivantes` `:

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> +La première permet de configurer la connection à Elasticsearch. ``default`` est l'*alias* de connection, au cas ou il serait nécessaire d'utiliser plusieurs *clusters*.
la **connexion**

de **connexion**

au cas **où**

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> +où ``'results_per_page'`` est le nombre de résultat affichés, ``'indexables'`` défini les différents types de documents indexés et ``'boosts'`` les différents facteurs de *boost* appliqués dans certa
le nombre de **résultats**

**définit** les différents types

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> +Chacune des valeurs multiplie le score (donc l'agrandit si elles sont supérieures à 1 et le diminue si elles sont inférieures à 1).
si **elle est supérieure** … si **elle est inférieure**

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> ++ ``clear`` : supprimme l'*index* du *cluster* d'ES et marque toutes les données comme "à indexer" ;
**supprime** l'index

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> +      Le caractère "à indexer" est fonction des actions effectuées sur l'objet Django (typiquement, à chaque fois que la méthode ``save()`` est appellée, l'objet est indiqué comme "à indexer").
est **appelée**

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> +    Le code est écrit de telle manière à ce que l'id utilisé par ES (champ ``_id``) corresponde au *pk* du modèle (via la variable ``es_id``).
(on utilise généralement *la* `pk` en français, pas *le* `pk` ;) )

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> +Différentes fonctions peuvent ou doivent ensuite être surchargées. Parmis ces dernières,
**Parmi** ces dernières,

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> ++ ``get_es_mapping()``, qui permet de définir le *mapping* de votre document, c'est à dire quel champs seront indexés, avec quels types. Par exemple,
**quels** champs seront **indexés avec** quels types.

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> +            Ainsi, tout les champs ``title`` doivent être de type ``Text(boost=1.5)`` et ``tags`` de type ``Keyword(boost=2.0)``.
**tous les champs**

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> +      Dans cet exemple (issus de la classe ``Post``), on voit que certains champs ne peuvent être directement indexés car ils appartientent au *topic* et au *forum* correspondant. Il sont donc exclus
**issu** de la classe

on les **remplit**

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> +Cela s'effectue comme suis (par exemple pour la classe ``Post``):
comme **suit**

2017-01-03 19:15 UTC, vhf commented on doc/source/back-end/search2.rst
> +En particulier, c'est la méthode ``get_es_indexable()`` qui est modifiée, profitant du fait qe cette fonction peut retourner n'importe quel type de document à indexer.
de fait **que** cette

2017-01-03 19:18 UTC, vhf commented
Moi je suis ok pour utiliser n'importe quelle version d'ES tant qu'elle est installable par un repo `apt` officiel et maintenu. Je veux juste pas devoir tenir à jour indépendamment un soft de plus sur nos serveurs. :)

2017-01-03 19:34 UTC, vhf requested changes
And voila!

2017-01-03 19:34 UTC, vhf commented on doc/source/install/install-es.rst
> +Pour démmarer Elasticsearch, ouvrez un *shell* (ou un *powershell*) et rendez vous dans le dossier ``elasticsearch-5.1.1``.
Pour **démarrer**

et **rendez-vous**

2017-01-03 19:34 UTC, vhf commented on doc/source/install/install-es.rst
> +Executez ensuite la commande suivante:
**Exécutez** ensuite la commande suivante` `:

2017-01-03 19:34 UTC, vhf commented on doc/source/install/install-es.rst
> +Pour tester que tout fonctionne, quand Elasticsearch est démarré, rendez vous sur la page `http://localhost:9200/ <http://localhost:9200/>`_.
**rendez-vous**

2017-01-03 19:34 UTC, vhf commented on doc/source/install/install-es.rst
> +Si c'est le cas, vous pouvez indexer les données à l'aide de la commande ``es_manager``, comme suis :
comme **suit** :

2017-01-03 19:34 UTC, vhf commented on doc/source/install/install-es.rst
> +    Si Elasticsearch n'est pas démmaré, le message suivant apparait.
n'est pas **démarré**

2017-01-03 19:34 UTC, vhf commented on doc/source/install/install-es.rst
> +Plus d'informations sur la commande la commande ``es_manager`` sont disponibles sur la page `concernant la recherche sur ZdS <../back-end/search2.html#indexer-les-donnees-de-zds>`_.
sur la commande ~~la commande~~

2017-01-03 22:06 UTC, pierre-24 commented
Merci @vhf, j'essaye de changer ça dès que je peux :)

2017-01-05 21:54 UTC, pierre-24 commented
Bon, ben ... C'est bon pour moi :)

Pour les courageux, la QA est ouverte (c'est vraiment pas compliqué, d'installer ES, je vous promet). Pour les autres, on se voit ... Après la ZEP-13, c'est ça @vhf ?

2017-01-06 13:51 UTC, pierre-24 commented
Ah. Voilà. Je l'ai enfin eue mon augmentation de *coverage*. M'enfin <3

2017-01-08 21:58 UTC, vhf approved these changes

2017-01-08 21:58 UTC, vhf commented
Super boulot @pierre-24 . Vu le progrès ici, on va probablement pouvoir faire passer ça devant les tribunes. 👍

2017-01-08 22:47 UTC, vhf requested changes
J'ai tout relu, juste quelques commentaires.

Super boulot, c'est 'achement propre et cool. Ça va vraiment faire beaucoup de bien, cette PR !

Et GG pour les tests et le coverage ! 👍

2017-01-08 22:47 UTC, vhf commented on assets/scss/pages/_home.scss
> +            // Rules to don't be hidden by the .home .search-box::before background-image
Ici et ligne 250, 338, 373 : 

`// Rules to avoid being overridden by .home .search-box::before background-image`

2017-01-08 22:47 UTC, vhf commented on doc/source/install/install-es.rst
> +    Il n'y a pas de procédure d'installation officielle d'Elasticsearch sous Mac OSX, même si il semblerait qu'il soit possible d'utiliser *brew* pour ce faire.
(OS X s'appelle désormais macOS)

On peut utiliser homebrew pour installer Elasticsearch : 

```
❯ brew install elasticsearch
[…]
==> Downloading https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.1.tar.gz
######################################################################## 100.0%
[…]
==> Summary
🍺  /usr/local/Cellar/elasticsearch/5.1.1: 98 files, 35.2M, built in 9 seconds
```

2017-01-08 22:47 UTC, vhf commented on doc/source/install/install-es.rst
> +Pour démarer Elasticsearch, utilisez
démarrer

2017-01-08 22:47 UTC, vhf commented on doc/source/install/install-es.rst
> +Vous devriez observer une réponse du même genre que celle-ci:
celle-ci` `:

2017-01-08 22:47 UTC, vhf commented on doc/source/install/install-es.rst
> +En particulier, vous ne devriez pas observer de message d'erreur:
d'erreur` `:

2017-01-08 22:47 UTC, vhf commented on doc/source/install/install-es.rst
> +Pour réindexer les nouvelles données, utilisez la commande suivante:
suivante` `:

2017-01-08 22:47 UTC, vhf commented on templates/search/search.html
> +            <button type="submit" class="ico-after ico-search" title='{% trans "Lancer la recherche" %}'></button>
Ici et ligne précédente, plutôt des `"` pour les attributs HTML ?

2017-01-08 22:47 UTC, vhf commented on templates/search2/includes/post.part.html
> +        Dans le topic « {{ search_result.topic_title }} »
i18n manquant ici

2017-01-08 22:47 UTC, vhf commented on templates/search2/includes/publishedcontent.part.html
> +            {% trans "Tutoriel publié" %}
Je crois que je préférerais qu'on teste explicitement qu'il s'agit d'un tutoriel ici, et que le `else` affiche `trans "Contenu publié"`

2017-01-08 22:47 UTC, vhf commented on zds/forum/models.py
> +        """Overridden to and prefetch tags and forum
Plutôt *Overridden to prefetch …* ?

2017-01-08 22:47 UTC, vhf commented on zds/searchv2/forms.py
> +                suggestions = ', '.join(random.sample(suggestions_file.readlines(), 5)) + '...'
Je pense que `…` serait préférable à `...` :)

2017-01-08 22:47 UTC, vhf commented on zds/searchv2/forms.py
> +            suggestions = 'Mathématiques, Droit, UDK, Langues, Python...'
Idem pour `.../…`. Possible d'avoir de l'i18n ici ?

2017-01-08 22:47 UTC, vhf commented on zds/searchv2/management/commands/es_manager.py
> +        Also, its mapping needs to be defined before the one of PublishedContent for parenting reasons (!!!).
Yay for useful docstrings! 💯

2017-01-08 22:47 UTC, vhf commented on zds/searchv2/urls.py
> +    url(r'^opensearch\.xml$', opensearch, name='opensearch'),
J'ai rapidement googlé et j'ai pas trouvé : à quoi sert `opensearch.xml` ?

2017-01-08 22:47 UTC, vhf commented on zds/searchv2/views.py
> +            messages.warning(self.request, _(u'Impossible de ce connecter à Elasticsearch'))
*Impossible de **se** connecter …*

2017-01-08 22:47 UTC, vhf commented on zds/searchv2/views.py
> +            # find forums where the user is allowed to visit
```diff
-            # find forums where the user is allowed to visit
+            # find forums the user is allowed to visit
```

2017-01-08 22:47 UTC, vhf commented on zds/searchv2/views.py
> +            if len(models) == 0:
Plutôt `if not models:` ?

2017-01-08 22:47 UTC, vhf commented on zds/settings.py
> +        }
On est assez adeptes des trailing commas dans notre codebase, et à mon avis à raison. Par contre je vais pas insister là-dessus dans cette PR, c'est plus une remarque en passant. Si tu veux les ajouter là où ça pourrait donner un diff plus clean dans le futur, c'est volontiers, sinon tant pis. (Je pense par exemple à l.554,560,566,569,576,577, mais pas particulièrement 578.)

2017-01-08 22:47 UTC, vhf commented on zds/tutorialv2/models/models_database.py
> +    which is not available in elasticsearch python API (thought the documentation says the opposite), so it passes
*though*

2017-01-08 22:47 UTC, vhf commented on zds/tutorialv2/models/models_database.py
> +    directly trough the connection layer.
*through*

(English is hard. It can be understood through tough thorough thought, though.)

2017-01-08 22:47 UTC, vhf commented on zds/tutorialv2/models/models_database.py
> +    PublishedContnent is created. To avoid doubles, the previous ones must be removed from ES.
*PublishedContent*

*To avoid **duplicates**,*

2017-01-08 22:47 UTC, vhf commented on zds/tutorialv2/models/models_database.py
> +    In mapping, the class define PublishedContent as its parent. Also, indexing is done by the parent.
*define**s***

2017-01-08 22:47 UTC, vhf commented on zds/tutorialv2/models/models_database.py
> +        self.es_id = main_container.slug + '__' + chapter.slug  # both slugs are unique by design, so id remains unique
Est-ce que cet `id` se retrouve face à l'utilisateur à un moment ? Si c'est pas le cas, il vaudrait mieux se baser sur les `pk` que sur les slugs. En l'état oui nos slugs sont aussi uniques, mais c'est pas sûr que ça soit toujours le cas. Quand on à affaire à un slug, on part généralement pas du principe qu'il est unique, c'est pas dans le concept usuel d'un slug. ZdS fait un peu différemment, mais j'ai peur que si ça devait changer ailleurs on se retrouverait avec des trucs très dur à débugger (et surtout très long à détecter qu'il y a effectivement un bug).

2017-01-08 22:47 UTC, vhf commented on zds/utils/templatetags/elasticsearch.py
> +    """Strip HTML, then transform back into html with only highlighting.
*with highlighted fragments only* ?

2017-01-09 07:27 UTC, pierre-24 commented on doc/source/install/install-es.rst
> +    Il n'y a pas de procédure d'installation officielle d'Elasticsearch sous Mac OSX, même si il semblerait qu'il soit possible d'utiliser *brew* pour ce faire.
Ok, cool :)  Et t'as des infos pour Java 8 ?

2017-01-09 07:27 UTC, pierre-24 commented on zds/searchv2/urls.py
> +    url(r'^opensearch\.xml$', opensearch, name='opensearch'),
Ben, [à ça](http://zds-site.readthedocs.io/fr/latest/utils/opensearch.html), je crois ?!?

2017-01-09 07:29 UTC, pierre-24 commented on zds/tutorialv2/models/models_database.py
> +    directly trough the connection layer.
I have so many problem with these ones. Also, this docstring not true anymore :-°

2017-01-09 07:31 UTC, pierre-24 commented on zds/tutorialv2/models/models_database.py
> +        self.es_id = main_container.slug + '__' + chapter.slug  # both slugs are unique by design, so id remains unique
Autant j'ai aucun problème avec ça pour le `main_container`, autant la raison de ce bricolage provient du fait que les chapitres ... N'ont pas de `pk`. Du coup, ben ...

2017-01-09 07:31 UTC, pierre-24 commented on zds/utils/templatetags/elasticsearch.py
> +    """Strip HTML, then transform back into html with only highlighting.
Toutafé.

2017-01-09 07:33 UTC, pierre-24 commented
Merci pour le *review*, @vhf , je fais ça dès que j'ai du temps (à mon avis ce soir, mais après Sherlock).

2017-01-09 07:34 UTC, pierre-24 commented on zds/settings.py
> +        }
ça coute pas grand chose à rajouter ;)

2017-01-09 07:47 UTC, SpaceFox commented on doc/source/install/install-es.rst
> +    Par défaut, Elasticsearch requiert au moins 2 Gio de mémoire pour démarrer.
Ça veut dire qu'il faudra monter la RAM du serveur, parce qu'on est déjà limite (cf les problèmes MySQL de l'autre jour) et que Solr ne consomme pas autant.

PS : attention à l'impact sur le coût du serveur, la RAM n'est pas donnée chez Gandi !

2017-01-09 08:08 UTC, pierre-24 commented on doc/source/install/install-es.rst
> +    Par défaut, Elasticsearch requiert au moins 2 Gio de mémoire pour démarrer.
... Ou bien que je suis [un idiot qui a pas été dans la *config* de ES pour changer ça](https://www.elastic.co/guide/en/elasticsearch/guide/current/_limiting_memory_usage.html) (parce que 2 Gio par défaut, ça me semble beaucoup pour mes quelques malheureuses données en bêta).

Comme je sais pas trop ce qu'on a réellement besoin en terme de ressource, j'avoue que je comptais chipoter ça quand on serait en bêta et faire quelques test de performance.

2017-01-09 09:35 UTC, firm1 commented on doc/source/install/install-es.rst
> +    Par défaut, Elasticsearch requiert au moins 2 Gio de mémoire pour démarrer.
ça m'étonnerait qu'il faille 2Go de RAM pour ce que l'on souhaite faire. Je fais tourner un ES dans le même genre avec une heap_size à 768 Mo pour de la recherche avec environ 1Go de donne indexées par jour, mais peut-être moins sollicitée que ce zds.
Il faudra ajuster ce paramètre en beta.

2017-01-09 09:38 UTC, pierre-24 commented on doc/source/install/install-es.rst
> +    Par défaut, Elasticsearch requiert au moins 2 Gio de mémoire pour démarrer.
Probablement. En fait, j'ai dit ça parce que j'avais pas réussi à démarrer ES dans ma VM avec 2 Gio de mémoire vive (je me suis fait engueuler par ES comme quoi il en voulait au moins 2 Gio), d'où le **par défaut**. Du coup, je vais rajouter comment changer ça dans la documentation.

2017-01-09 09:39 UTC, pierre-24 commented on doc/source/install/install-es.rst
> +    Par défaut, Elasticsearch requiert au moins 2 Gio de mémoire pour démarrer.
Bon, ceci dit, si il y a déjà des problèmes de MySQL, même si ES devait consommer 512 Mio, le commentaire de @SpaceFox reste valable.

2017-01-09 09:45 UTC, SpaceFox commented on doc/source/install/install-es.rst
> +    Par défaut, Elasticsearch requiert au moins 2 Gio de mémoire pour démarrer.
Pour info, présentement Solr a un index de 187 Mio, a un Xmx de 768 Mio et son processus occupe réellement 467 Mio en RAM.

2017-01-09 09:49 UTC, firm1 commented on .travis.yml
> + - elasticsearch
je vois qu'on installe déjà es à la ligne 52, donc pas la peine de le rajouter ici, si ce n'est pour biaiser le comportement

2017-01-09 10:11 UTC, pierre-24 commented on .travis.yml
> + - elasticsearch
J'avoue avoir purement, simplement et méchamment [suivi la documentation](https://docs.travis-ci.com/user/database-setup/#ElasticSearch). J'ai peur que si je change pas ça, Travis oublie de faire un truc en rapport avec elasticsearch, mais je peux me tromper.

2017-01-09 13:31 UTC, DevHugo commented on doc/source/install/install-es.rst
> +    Il n'y a pas de procédure d'installation officielle d'Elasticsearch sous Mac OSX, même si il semblerait qu'il soit possible d'utiliser *brew* pour ce faire.
De mémoire, j'avais fait ça:

```
brew update
brew cask install java
```

2017-01-09 14:28 UTC, firm1 commented on .travis.yml
> + - elasticsearch
non, c'est juste que l'instruction dans `services` va installer et loader ES pour travis avec la dernière version dispo dans travis. Mais vu que toi tu souhaite la dernière version, tu la réinstalle par la suite.

Donc supprimer cette instruction ne changerai pas grand chose au comportement. Et si ça change quelque chose, ça signifie que travis fait quelque chose avant toi, et vaudrait mieux savoir quoi pour la déploiement en prod.

2017-01-09 14:37 UTC, pierre-24 commented on .travis.yml
> + - elasticsearch
En effet. De toute façon, ça coute rien de tester :)

2017-01-09 14:38 UTC, pierre-24 commented on .travis.yml
> + - elasticsearch
(enfin, si, ça représente 20 minutes d'attente)

2017-01-09 20:07 UTC, pierre-24 commented on doc/source/install/install-es.rst
> +    Par défaut, Elasticsearch requiert au moins 2 Gio de mémoire pour démarrer.
J'ai mis un petit mot à ce sujet :)

2017-01-09 20:16 UTC, pierre-24 commented on .travis.yml
> + - elasticsearch
Ok, ça à l'air de marcher :)

2017-01-09 20:19 UTC, pierre-24 commented
Voilà, tout y est : les corrections de @vhf, la mémoire, le `pip freeze` et le `update.md`. Et y'a juste Travis qui fait son grincheux à cause de `npm`.

2017-01-14 17:10 UTC, DevHugo commented
Tu veux qu'on fasse quoi comme QA @pierre-24 ?

Je peux tester déjà ces scénario là ?

- Publication de mini tutoriel, tutoriel, big tutoriel et article ?
- Nouvelle publication avec une suppression de partie/chapitre/extrait ? 
- Nouvelle publication avec un ajout de partie/chapitre/extrait ?  
- Suppression d'une publication d'un contenu (tutoriel et article) ?
- Ajout de sujet et de messages dans le forum ainsi que leurs indexations ?
- Indexation d'un sujet ou message masqué ?
- Indexation d'un sujet supprimé ?
- …

2017-01-14 17:22 UTC, pierre-24 commented
Oui. Tout les trucs tordus auquel tu pourrais penser, quoi :)

2017-01-14 18:31 UTC, Situphen commented on doc/source/back-end/forum.rst
> +Tout d'abord, il y a une posibilité de faire de la modération par sujet. Ici, cette modération s'effectue grâce aux liens se trouvant dans la *sidebar* (zone se trouvant sur le côté gauche de la page
"sidebar" --> "barre latérale" ? :)

2017-01-15 09:29 UTC, sandhose approved these changes
Cay bô.

2017-01-15 09:29 UTC, sandhose commented on assets/scss/components/_search-box.scss
> +        margin-left: 50px;
C'est ce truc qui fait le décalage à cause de Clem sur la home. Il faudrait donc mettre cette margin que sur la home. (la home a une classe `.home` sur le body)

2017-01-15 09:29 UTC, sandhose commented on zds/notification/tests/tests_tricky.py
> +        if os.path.isdir(settings.ZDS_APP['content']['repo_private_path']):
Haha, le ptit fix qu'on ajoute en plein milieu d'une grosse PR <3

2017-01-15 09:29 UTC, sandhose commented on zds/searchv2/forms.py
> +        try:
Ce genre de trucs, ça peut pas être chargé une fois en RAM, plutôt que devoir lire sur le disque à chaque requête ? Genre dans le settings.py ou quelque chose ?

2017-01-15 09:29 UTC, sandhose commented on zds/searchv2/management/commands/es_manager.py
> +        elif options['action'] == 'index-all':
Hm, `es_manager` en `snakecase`, et les subcommands en `kebabcase` ? 😕

2017-01-15 09:29 UTC, sandhose commented on zds/searchv2/models.py
> +                        'keywords': ['javafx', 'haskell', 'groovy', 'powershell', 'latex', 'linux', 'windows']
Hm, ça me paraît très arbitraire, et très hard-codé, tout ça ; c'est quoi, exactement ?

2017-01-15 10:08 UTC, artragis commented on zds/searchv2/models.py
> +                        'keywords': ['javafx', 'haskell', 'groovy', 'powershell', 'latex', 'linux', 'windows']
j'ai tendance à dire que ce sont quelques mots clefs qui ont du mal à être traduit en français car ça ne fait pas partie de notre dictionnaires. Je pense que @pierre-24 devrait mettre ces mots dans le settings.py histoire qu'on puisse faire évoluer ça bien plus facilement.

2017-01-15 10:09 UTC, artragis commented on zds/searchv2/forms.py
> +        try:
bah c'est un fichier de test, il faut donc teardown/setup le truc à chaque nouveau test.

2017-01-15 10:11 UTC, artragis commented on doc/source/back-end/forum.rst
> +Tout d'abord, il y a une posibilité de faire de la modération par sujet. Ici, cette modération s'effectue grâce aux liens se trouvant dans la *sidebar* (zone se trouvant sur le côté gauche de la page
outre le fait que dans nos templates on appelle ça "sidebar", le mot anglais n'enlève pas la compréhension et le mot français n'en ajoute pas.

2017-01-15 10:26 UTC, pierre-24 commented on doc/source/back-end/forum.rst
> +Tout d'abord, il y a une posibilité de faire de la modération par sujet. Ici, cette modération s'effectue grâce aux liens se trouvant dans la *sidebar* (zone se trouvant sur le côté gauche de la page
Ouais mais bon, ça me tuera pas de mettre "barre latérale". Je vais mettre les deux, tient.

2017-01-15 10:27 UTC, pierre-24 commented on zds/notification/tests/tests_tricky.py
> +        if os.path.isdir(settings.ZDS_APP['content']['repo_private_path']):
En fait, ça finissait par me poser problème, donc c'est "presque pas" un "ptit fix" :p

2017-01-15 10:27 UTC, pierre-24 commented on assets/scss/components/_search-box.scss
> +        margin-left: 50px;
Pataper, c'est @Situphen qui a chipoté à ça. En français, il faut faire quoi pour le corriger ?

2017-01-15 10:28 UTC, pierre-24 commented on zds/searchv2/forms.py
> +        try:
T'as raison, mais j'avoue que là, j'ai rien inventé. Je garde ça comme évolution :)

2017-01-15 10:32 UTC, pierre-24 commented on zds/searchv2/management/commands/es_manager.py
> +        elif options['action'] == 'index-all':
Mmh, tu marques un point. Bon, le `snakecase`, ça a l'air d'être une norme dans nos commandes, donc je vais pas toucher à ça, et du coup passer mes subcomandes de même.

2017-01-15 10:35 UTC, pierre-24 commented on zds/searchv2/models.py
> +                        'keywords': ['javafx', 'haskell', 'groovy', 'powershell', 'latex', 'linux', 'windows']
En très cours, on à un *stemmer* dans la *stack* d'analyse de ES, qui, d'un mot, en extrait la "racine". Par exemple, de "programme" ou "programmer", il va en extraire la même racine, "program". C'est très bien dans la plupart des cas, **sauf** quand il commence à s'attaquer aux noms propres. Cette liste est justement des noms que j'aimerai que ES n'analyse pas et laisse tel quels (sinon, par exemple, il comprend "linux" comme "lin", ce qui n'as plus de sens).

Quand à l'idée de mettre ça dans le `settings.py`, yep, pourquoi pas :)

2017-01-15 11:09 UTC, pierre-24 commented
@DevHugo : tu peux aussi tester que certaines choses restes faisables quand ES n'est pas actif, au cas ou.

2017-01-15 11:26 UTC, DevHugo commented on zds/searchv2/models.py
> +                        'keywords': ['javafx', 'haskell', 'groovy', 'powershell', 'latex', 'linux', 'windows']
Tu prend toutes la configuration et tu met dans un fichier séparé, c'est plus facile/rapide à faire pour toi !

2017-01-15 11:30 UTC, DevHugo commented
Ok, je fait la QA dans la semaine.

2017-01-15 11:31 UTC, pierre-24 commented on zds/searchv2/models.py
> +                        'keywords': ['javafx', 'haskell', 'groovy', 'powershell', 'latex', 'linux', 'windows']
Je peux, mais pas certains. Je rappelle que chipoter à ça, c'est devoir réindexer l'entièreté du contenu, sinon ça ne fonctionne pas :p

2017-01-17 18:38 UTC, DevHugo commented
Dans les trucs pas grave, il manque les miniatures pour les contenu

Résultat d'un contenu sur la branche : 

![prodsearchresult](https://cloud.githubusercontent.com/assets/6099338/22034380/6678fc2c-dcec-11e6-99ff-9aed15128b44.png)

R2sultat sur la prod : 

![branchesearchresult](https://cloud.githubusercontent.com/assets/6099338/22034374/620769da-dcec-11e6-9941-8a4eb70a3a23.png)

2017-01-17 20:06 UTC, DevHugo commented
@pierre-24 , c'est fait, voir plus haut.

2017-01-17 20:23 UTC, artragis commented
wahou, ça c'est de la review @DevHugo !!

2017-01-17 20:25 UTC, pierre-24 commented
Merci @DevHugo.

Beaucoup des "bugs" sont en fait des choix de ma part, donc n'hésitez pas à donner votre avis là dessus.

**Pour 1** : C'est presque voulu, en fait. Je trouvais que ça faisait tache de mettre une miniature pour ça (j'ai l'impression que ça les met en avant par rapport aux autres) et pas pour le reste. Bon, après, ça me coûte rien de la mettre :)

**Pour 2** :  en effet. Je vais tester si y'a pas moyen de mettre les critères en dessous de la barre, du coup (c'est de toute façon quelque chose que je voulais essayer).

**Pour 3 (et 4 et 5 et 7)**: "*c'est pas un bug, c'est une fonctionnalité*" : puisque je n'indexe plus les extraits séparément mais le chapitre en une fois, c'est évidement impossible. Peut-être que je me trompe, mais ça me semble pas trop grave. Si ?

**Pour 6** : c'est un effet de bord du point précédent, j'ai considérer que si un terme étant présent dans une introduction/conclusion de big-tuto, il serait probablement présent dans  les chapitres de celle-ci. Pour moi, si un terme est présent dans ces parties là, autant lire le tuto ou le chapitre correspondant. On peut ceci dit imaginer que l'intro/la conclusion d'un tuto booste celui-ci, mais ça laisse le cas des parties qui est un peu plus chiant.

**Pour 8** : encore un effet de bord de la décision précédente (donc plus de parties et plus de sections). Par contre, c'est vrai qu'on ne peut plus discriminer sur article/tuto. Vous voulez garder ça ?

2017-01-17 20:26 UTC, artragis commented
Pour le 1, justement pierre, le but est de mettre en avant les tutos 
dans la recherche.


Le 17/01/2017 à 21:25, Pierre Beaujean a écrit :
>
> Merci @DevHugo <https://github.com/DevHugo>.
>
> Beaucoup des "bugs" sont en fait des choix de ma part, donc n'hésitez 
> pas à donner votre avis là dessus.
>
> *Pour 1* : C'est presque voulu, en fait. Je trouvais que ça faisait 
> tache de mettre une miniature pour ça (j'ai l'impression que ça les 
> met en avant par rapport aux autres) et pas pour le reste. Bon, après, 
> ça me coûte rien de la mettre :)
>
> *Pour 2* : en effet. Je vais tester si y'a pas moyen de mettre les 
> critères en dessous de la barre, du coup (c'est de toute façon quelque 
> chose que je voulais essayer).
>
> *Pour 3 (et 4 et 5 et 7)*: "/c'est pas un bug, c'est une 
> fonctionnalité/" : puisque je n'indexe plus les extraits séparément 
> mais le chapitre en une fois, c'est évidement impossible. Peut-être 
> que je me trompe, mais ça me semble pas trop grave. Si ?
>
> *Pour 6* : c'est un effet de bord du point précédent, j'ai considérer 
> que si un terme étant présent dans une introduction/conclusion de 
> big-tuto, il serait probablement présent dans les chapitres de 
> celle-ci. Pour moi, si un terme est présent dans ces parties là, 
> autant lire le tuto ou le chapitre correspondant. On peut ceci dit 
> imaginer que l'intro/la conclusion d'un tuto booste celui-ci, mais ça 
> laisse le cas des parties qui est un peu plus chiant.
>
> *Pour 8* : encore un effet de bord de la décision précédente (donc 
> plus de parties et plus de sections). Par contre, c'est vrai qu'on ne 
> peut plus discriminer sur article/tuto. Vous voulez garder ça ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-273288925>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xfb6AYycxTyitphJPUh5M9P6DX-eks5rTSOjgaJpZM4LVOk9>.
>

2017-01-17 20:28 UTC, pierre-24 commented
> Pour le 1, justement pierre, le but est de mettre en avant les tutos dans la recherche.

Tout à fait d'accord, mais les chapitres de big-tutos, qui me semblent pertinent, n'ont pas de miniature, par exemple. Ou bien je met la miniature du tuto ?

2017-01-17 20:28 UTC, artragis commented
Oui.


Le 17/01/2017 à 21:28, Pierre Beaujean a écrit :
>
>     Pour le 1, justement pierre, le but est de mettre en avant les
>     tutos dans la recherche.
>
> Tout à fait d'accord, mais les chapitres de big-tutos, qui me semblent 
> pertinent, n'ont pas de miniature, par exemple. Ou bien je met la 
> miniature du tuto ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-273289746>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xdw95Hj6KWPSD5_xTFmNc4mBCFovks5rTSRcgaJpZM4LVOk9>.
>

2017-01-17 20:30 UTC, artragis commented on zds/tutorialv2/models/models_database.py
> +from elasticsearch_dsl import Mapping, Q
pour éviter tout problème future, serait-il possible de faire

```python
from elasticsearch_dsl import Mapping
from elasticsearch_dsl import Q as ES_Q
```

comme Q est aussi un truc de l'ORM django et qu'on est dans lefichier models_database, ça arrivera un jour ou l'autre

2017-01-17 21:13 UTC, vhf commented
@FanJiyong : https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-273288925

2017-01-17 21:14 UTC, pierre-24 commented
Anéfé, c'est plus simple, on sera fixé :)

On 01/17/2017 10:13 PM, victor felder wrote:
>
> @FanJiyong <https://github.com/FanJiyong> : #4096 (comment) 
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-273288925>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-273301184>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/AHhjC7wRQ3YHMSLKJmcL7BuhGhT03OiTks5rTS7rgaJpZM4LVOk9>.
>

2017-01-18 00:09 UTC, DevHugo commented
Je m'en doutait que c'était des choix, je voulais juste que tous le monde soit bien conscient que c'est différent de ce qu'il y'a aujourd'hui. Je ne me permet pas de juger mais je dit juste, attention, c'est différent !

> Pour 1 : C'est presque voulu, en fait. Je trouvais que ça faisait tache de mettre une miniature pour ça 
> (j'ai l'impression que ça les met en avant par rapport aux autres) et pas pour le reste. 

Je trouve que c'était pas mal, car ça permettait justement de repérer rapidement les contenus. Dans le module de recherche avant, les contenus n'était pas dans les premiers résultats, ça permettait de les différencier facilement.

> Ou alors on met une "miniature" (avec des images pour topic/message/...) pour tout ?

Ça a un côté esthétique de faire ça aussi, on peut mettre un placeholder. Ou trouver un truc un peu plus esthétique. 

> Le 6, c'est un effet de bord du point précédent, j'ai considérer que si un terme étant présent dans une > introduction/conclusion de big-tuto, il serait probablement présent dans les chapitres de celle-ci. 

C'est compréhensible, mais d'un point de vue utilisateur, ça fait bizarre que tu puisse rechercher dans toutes les introductions de tous types de contenus sauf celle-ci. J'ai vraiment cru à un bug pour celle-ci.

Maintenant reste à tester toute la partie, re-publication de tutoriel mais ça c'est pour la fin de la semaine.

2017-01-18 07:56 UTC, pierre-24 commented
>  Je ne me permet pas de juger mais je dit juste, attention, c'est différent !

Pas de problème :)

> [...] Ça a un côté esthétique de faire ça aussi, on peut mettre un placeholder. Ou trouver un truc un peu plus esthétique.

Ouais. [voir cette discussion](https://zestedesavoir.com/forums/sujet/3363/quelques-ameliorations-pour-la-page-de-recherche/). Donc si il y a des gens qui ont un sens du *design* dans le coin (pas moi, par exemple), allez-y :)

> En même temps, je me dit que la conclusion sert souvent d'ouverture, des liens vers d'autre type de contenus qui auraient pas été forcément dans le tuto.

Pas faux, je vais y réfléchir :)

> Tu as pensé au robot.txt, si y'a des nouvelles url ?

Y'en a pas, mais bien vu.

> Si un jour, on veut indexer les extraits, cela posera t-il des soucis majeurs ?

Pas spécialement, on peut réutiliser le même "truc" que pour les chapitres. C'est juste que c'est pas du HTML et que donc il faut le parser, et qu'il faut pas oublier de gérer la suppression =)

2017-01-18 10:45 UTC, FanJiyong commented
Salut à tous

Tous les points remonter me semble totalement pertinent.

Le point numéro 1 : on reaffiche les miniatures, même si ça fait tâche en
l'état.

Point 2 tt le monde semble OK la dessus. À corriger donc.

Point numéro 3,4 ,5 et 7 : si je cherche une information en particulier et
que ça me l'affiche dans les résultats et que je me retrouve sur une autre
page que celle où j'ai le résultat, c'est pour moi un souci de
comportement.


Point 6 et 8

"Pour moi, si un terme est présent dans ces parties là, autant lire le tuto
ou le chapitre correspondant. "

Ça me semble bien effectivement. Cependant il faut bien diriger sur la page
en question, pas 5 page en arrière.





Le 18 janv. 2017 8:56 AM, "Pierre Beaujean" <notifications@github.com> a
écrit :

> Je ne me permet pas de juger mais je dit juste, attention, c'est différent
> !
>
> Pas de problème :)
>
> [...] Ça a un côté esthétique de faire ça aussi, on peut mettre un
> placeholder. Ou trouver un truc un peu plus esthétique.
>
> Ouais. voir cette discussion
> <https://zestedesavoir.com/forums/sujet/3363/quelques-ameliorations-pour-la-page-de-recherche/>.
> Donc si il y a des gens qui ont un sens du *design* dans le coin (pas
> moi, par exemple), allez-y :)
>
> En même temps, je me dit que la conclusion sert souvent d'ouverture, des
> liens vers d'autre type de contenus qui auraient pas été forcément dans le
> tuto.
>
> Pas faux, je vais y réfléchir :)
>
> Tu as pensé au robot.txt, si y'a des nouvelles url ?
>
> Y'en a pas, mais bien vu.
>
> Si un jour, on veut indexer les extraits, cela posera t-il des soucis
> majeurs ?
>
> Pas spécialement, on peut réutiliser le même "truc" que pour les
> chapitres. C'est juste que c'est pas du HTML et que donc il faut le parser,
> et qu'il faut pas oublier de gérer la suppression =)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-273407686>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AOc7tCE4-OoBJBE1POlMj2SYKw5wt31Aks5rTcW3gaJpZM4LVOk9>
> .
>

2017-01-18 12:21 UTC, DevHugo commented
Juste pour bien clarifier la chose et donner un exemple concret.

La situation aujourd'hui, si on recherche par exemple, "Langages d'acteurs" (c'est un des mots clés qui est dans un extrait), la recherche permet de rediriger jusqu'à l'extrait concerné.

Dans notre [exemple](https://zestedesavoir.com/rechercher/?q=+langages+%C3%A0+acteurs), on sera redirigé [dans le bon extrait](https://zestedesavoir.com/articles/1329/decouverte-du-langage-pony/#7-pony-est-il-le-bon-outil-pour-vous). 

Si maintenant, on prend le comportement introduit par la PR, on sera redirigé sur le chapitre en entier donc [ici](https://zestedesavoir.com/articles/1329/decouverte-du-langage-pony/).

Après même sans indexer les extraits, quand on affiche le chapitre, on pourrait surligner les passages concernés avec du JS. C'est "assez simple à faire", suffit juste de passer dans l'URL le passage concerné ou autrement (tu as bien l'info dans elasticsearch ? normalement, oui, vu que tu affiche, la description). Suffit juste de rechercher dans le texte affiché en JS, le passage concerné, et d'ajouter un span avec la bonne classe css.

2017-01-18 12:23 UTC, pierre-24 commented
@FanJiyong : en fait, on se retrouve sur la bonne page (sur le bon chapitre). Mais par exemple, pas dans au milieu de la page si le mot clé y est, mais au début de celle-ci.

2017-01-18 12:58 UTC, FanJiyong commented
@Pierre OK parfait alors. Ça peut être casse pied d'être directement
rediriger dans le contenu.

Le mer. 18 janv. 2017 à 13:23, Pierre Beaujean <notifications@github.com> a
écrit :

> @FanJiyong <https://github.com/FanJiyong> : en fait, on se retrouve sur
> la bonne page (sur le bon chapitre). Mais par exemple, pas dans au milieu
> de la page si le mot clé y est, mais au début de celle-ci.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-273461863>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AOc7tD--Z68uUoUfuaTX209qgX5OzOP5ks5rTgQogaJpZM4LVOk9>
> .
>

2017-01-18 19:53 UTC, pierre-24 commented on assets/scss/components/_search-box.scss
> +        margin-left: 50px;
Mmmh, je viens de tester, et ça empêche pas la clem' de nowel ou d'halloween de fonctionner :)

2017-01-18 20:21 UTC, pierre-24 commented
Bon, j'ai fait ça : 

![screenshot from 2017-01-18 21 18 12](https://cloud.githubusercontent.com/assets/7889675/22081460/f41c967e-ddc3-11e6-9837-c0ad89f76524.png)

Je me répete, mais si il y a quelqu'un de plus doué en graphisme et en design que moi, qu'il n'hésite pas ;)

2017-01-18 20:50 UTC, artragis commented
Et si tu vérifies bien qu'en cochant les case on a bien le bon 
comportement tu pourras fixer une issue reporté par firm1 et que je ne 
retrouve plus.


Le 18/01/2017 à 21:21, Pierre Beaujean a écrit :
>
> Bon, j'ai fait ça :
>
> screenshot from 2017-01-18 21 18 12 
> <https://cloud.githubusercontent.com/assets/7889675/22081460/f41c967e-ddc3-11e6-9837-c0ad89f76524.png>
>
> Je me répete, mais si il y a quelqu'un de plus doué en graphisme et en 
> design que moi, qu'il n'hésite pas ;)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-273590171>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xda2bm40_Z5lIuIEnTkkidxg80xWks5rTnQzgaJpZM4LVOk9>.
>

2017-01-18 20:51 UTC, pierre-24 commented
J'ai même un test unitaire pour ça ;)

2017-01-18 20:53 UTC, artragis commented
oui mais non, actuellement c'est l'ui qui fait chier.

pour faire simple, au lieu d'ajouter le paramètre &type=article,tutorial 
par exemple, elle ajoute &id_models_2=article&id_models_3=tutorial


Le 18/01/2017 à 21:51, Pierre Beaujean a écrit :
>
> J'ai même un test unitaire pour ça ;)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-273598046>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xfdFRq7q6KzPYnhgNIk5RMoEuTMsks5rTntrgaJpZM4LVOk9>.
>

2017-01-18 21:12 UTC, Situphen commented on assets/scss/components/_search-box.scss
> +        margin-left: 50px;
Ah effectivement j'ai pas du faire très attention aux styles de "label" :D

2017-01-19 20:41 UTC, DevHugo commented
Tu as prévu quoi pour les anciennes tables de la recherche, notamment celle des extraits ?

2017-01-19 20:42 UTC, pierre-24 commented
Disparition pure et simple. Note que je devrais le préciser dans le `update.md`, parce que j'imagine que ça reste si on y touche pas :)

2017-01-19 21:00 UTC, DevHugo commented
Ouai, précise, y'a une histoire de clé étrangère, peut-être, à voir.

Sinon tu as oublié de préciser dans le update.md, qu'il faut builder le front :) !

2017-01-19 21:01 UTC, artragis commented
il me sembleque builder le front c'est fait automatiquement donc ça n'& 
pas à être dnas le update.md


Le 19/01/2017 à 22:00, Hugo Courtecuisse a écrit :
>
> Ouai, précise, y'a une histoire de clé étrangère, peut-être, à voir.
>
> Sinon tu as oublié de préciser dans le update.md, qu'il faut builder 
> le front :) !
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-273897050>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xXV2CTFKUGk_FYE8CTwt4Ukre72kks5rT87ygaJpZM4LVOk9>.
>

2017-01-19 21:48 UTC, DevHugo commented
J'ai trouvé un bug, un vrai mais qui est pas très embêtant !

Supprimer une partie et un chapitre dans un moyen tutoriel et un big tutoriel, ne supprime pas les extraits, ni le chapitre dans la recherche lors d'une ré-indexation partielle (ça marche bien avec les extraits et la ré-indéxation totale).

_Comment reproduire ?_

- Importer le tutoriel "Le langage C"
- Publié une première version du contenu et indexer là avec la commande `python manage.py es_manager index_flagged` (surtout pas index_all, ça marche dans le cas de la ré-indéxation de tous)
- Rechercher un extrait et notez une phrase dedans.
- Supprimer la partie dans laquelle est située l'extrait précédemment recherché.
- Rechercher l'extrait qui est censé être supprimé, constaté que cet extrait n'est pas supprimé dans les résultats de la recherche.

2017-01-20 06:21 UTC, pierre-24 commented
Bien vu, et en effet, il va être chiant à corriger ;)

2017-01-20 11:59 UTC, DevHugo commented
Je teste l'indexation du forum et c'est bon pour moi. On peur t'aider à faire quelque chose ?

2017-01-20 12:01 UTC, DevHugo commented
Je pensais par exemple de publier ça sur la beta pour tester les temps d'indexation et la pertinence des Informations, tu en pense quoi ?

2017-01-20 14:48 UTC, pierre-24 commented
> Je pensais par exemple de publier ça sur la beta pour tester les temps d'indexation et la pertinence des Informations, tu en pense quoi ?

Avec plaisir, mais ça ne dépend pas de moi :)

2017-01-20 14:49 UTC, DevHugo commented
@vhf ça te parait possible de déployer la branche sur la bêta, exceptionnellement, pour qu'on puisse tester ?

2017-01-20 18:37 UTC, DevHugo commented
@pierre-24 putain, j'en ai un autre, un peu le même genre, je pense que celui la est plus simple à résoudre

Quand on passe un topic et ses posts dans la corbeille, les utilisateurs peuvent quand même les voirs avec une indexation partielle.

_Comment reproduire ?_

- Créé un forum dans l'administration django réservé au staff uniquement, 

![capture du 2017-01-20 19-28-46](https://cloud.githubusercontent.com/assets/6099338/22160652/cc11938a-df46-11e6-9fe7-c6ae3f907728.png)

- Créer un sujet dans un autre forum non réservé aux admin avec au moins une réponse. Indexer les messages et sujets avec la commande index_flagged.
 
- Connectez-vous avec un compte avec les droits staff, passer le sujet dans la corbeille. Indexer les messages et topic avec la commande index_flagged.
 
-Déconnectez-vous du compte staff, les messages et les sujets visibles qui ne devraient pas être visible, le sont.

2017-01-20 22:04 UTC, pierre-24 commented
Zut, le topic doit bouger de place, mais pas les forums associés. Bien vu !

2017-01-21 14:03 UTC, pierre-24 commented
Bon, voilà, j'ai réglé les bugs signalé par @DevHugo  (encore 1000x merci). Comme ça, ça m'as permis de me souvenir de pourquoi les bases de données relationnelles, c'était quand même pratique (en particulier `JOIN`, qui me manque affreusement). 

Par contre, je disparais pour une semaine à partir de demain, et à priori j'aurais aucun accès à internet. Mais que ça vous empêche pas de tester, je découvrirais des surprises en rentrant ;)

2017-01-21 14:06 UTC, pierre-24 commented
Oh, *bonus track* pour @artragis, tant que j'y pense :)

![screenshot from 2017-01-21 15 03 54](https://cloud.githubusercontent.com/assets/7889675/22174955/2c04f94a-dfeb-11e6-98d4-1cd90692a332.png)

2017-01-21 14:22 UTC, DevHugo commented
Tu as eu les deux ?

2017-01-21 14:23 UTC, pierre-24 commented
Afirmatif ;)

Là, j'ai juste cassé un test (et oublié des *quotes*), mais sinon, c'est bon.

2017-01-21 14:24 UTC, DevHugo commented
Ok je re-teste ça immédiatement. Tu as un moyen simple de virer tous les index elasticsearch ?

2017-01-21 14:27 UTC, pierre-24 commented
Si tu fais `es_manager index_all`, tout va automatiquement se remettre à jour. Sinon, y'a moyen avec `_delete_by_query`.

2017-01-21 14:27 UTC, pierre-24 commented
(ou simplement `DELETE /zds_search`, en fait)

2017-01-21 15:12 UTC, DevHugo commented
Encore un petit souci, si la variable text dans le template  /home/hugo/python-development/zds-site/templates/searchv2/includes/chapter.part.html  est vide, on se prend une erreur !

2017-01-21 15:29 UTC, DevHugo commented
QA: ok !

Cas testé: 

- Recherche dans une "Intro" d'un article ("Découverte du langage Pony")

- Recherche dans une "Conclusion" d'un article ("Découverte du langage Pony")

- Recherche dans le titre d'un chapitre d'un article ("Découverte du langage Pony")

- Recherche dans l'extrait d'un article ("Découverte du langage Pony")

- Recherche dans une "Intro" d'un tutoriel ("Langage C")

- Recherche dans une "Conclusion" d'un tutoriel ("Langage C")

- Recherche dans le titre d'une partie d'un tutoriel ("Langage C")

- Recherche dans l'intro d'une partie d'un tutoriel ("Langage C")

- Recherche dans la conclusion d'une partie d'un tutoriel ("Langage C")

- Recherche dans le titre d'un chapitre d'un tutoriel ("Langage C")

- Recherche dans le titre de l'extrait d'un tutoriel ("Langage C")

- Recherche dans le contenu d'un tutoriel ("Langage C")

- Ajout de partie, chapitre, extrait

- Suppression de partie, chapitre, extrait

- Tous les critères de recherches

- Message masqué pour les admins

- Message masqué pour les non admin

- Recherche dans un sujet

- Recherche dans un message

- Sujet dans la corbeille visible pour les admins

- Sujet dans la corbeille non visible pour les autres

2017-01-21 15:35 UTC, DevHugo commented
@pierre-24 bravo, si tu as juste le temps de faire le if dans le template, on peut merger comme ça.

2017-01-21 16:03 UTC, pierre-24 commented
Ce soir sans problèmes. À mon avis, c'est le surlignage qui se foire :)

On Jan 21, 2017 4:35 PM, "Hugo Courtecuisse" <notifications@github.com>
wrote:

> @pierre-24 <https://github.com/pierre-24> bravo, si tu as juste le temps
> de faire le if dans le template, on peut merger comme ça.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-274268673>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHhjCxuim8JPyLBH2yAshrcS-oDuX6z0ks5rUiW3gaJpZM4LVOk9>
> .
>

2017-01-21 16:09 UTC, vhf commented
Je vais déployer ça le temps de tagger et builder le tout.

Déjà quelques trucs à corriger/ajouter à `update.md`:

---

*Vérifier que le port 9200 n'est pas accessible de l'extérieur (sinon, configurer nginx pour le bloquer)*

C'est le firewall qui doit bloquer ce port, nginx est juste le serveur web.

---

On ne schedule pas le reindexage par crontabs mais par systemd:

```
$ cat zds-es-index.service
[Unit]
Description=Reindex SOLR Service

[Service]
Type=oneshot
User=zds
Group=zds
ExecStart=/opt/zds/zdsenv/bin/python /opt/zds/zds-site/manage.py es_manager index_flagged
```

Est-ce que tu as une idée de l'interval auquel réindexer les trucs flaggés ? J'ai laissé les 30min de solr.

```
$ cat zds-es-index.timer
[Unit]
Description=ES reindex flagged contents

[Timer]
OnCalendar=*:30:00
Persistent=true

[Install]
WantedBy=timers.target
```

```
# Couper la réindexation par solr
$ systemctl stop zds-index-solr.timer
$ systemctl disable zds-index-solr.timer

# Lancer celle par ES
$ systemctl enable zds-es-index.timer
$ systemctl start zds-es-index.timer
```

2017-01-21 16:20 UTC, vhf commented
Procédure pour installer le plugin munin elasticsearch, aussi pour `update.md`:

```
cd /usr/share/munin/plugins/
wget https://raw.githubusercontent.com/true/true-munin-plugins/master/elasticsearch
```

```
ln -s /usr/share/munin/plugins/elasticsearch /etc/munin/plugins/elasticsearch_cache
ln -s /usr/share/munin/plugins/elasticsearch /etc/munin/plugins/elasticsearch_docs
ln -s /usr/share/munin/plugins/elasticsearch /etc/munin/plugins/elasticsearch_index_size
ln -s /usr/share/munin/plugins/elasticsearch /etc/munin/plugins/elasticsearch_jvm_memory
ln -s /usr/share/munin/plugins/elasticsearch /etc/munin/plugins/elasticsearch_jvm_pool_memory
ln -s /usr/share/munin/plugins/elasticsearch /etc/munin/plugins/elasticsearch_jvm_threads
```

```
service munin-node restart
```

2017-01-21 17:09 UTC, vhf commented
`es_manager index_all` alloue beaucoup trop de RAM, il va falloir corriger ça. Comment fonctionne le chargement des données de mysql vers ES ? Peux-tu modifier ça pour que ça se fasse par batch d'une taille configurable, disons 200 rows par 200 rows ?

2017-01-21 17:11 UTC, artragis commented on zds/searchv2/models.py
> +        objs = list(model.get_es_indexable(force_reindexing=force_reindexing))
ici il vaudrait mieux éviter de faire une liste car ça risque de demander énormément de RAM.

Je serais d'avis de créer des sous-listes de 10 éléments puis de les yielder. Ensuite plus qu'à faire la requêtes avec chaque sous-liste.

2017-01-21 17:14 UTC, pierre-24 commented
M'en doutais un peu, et je vais voir ce que je peut faire pour faire ça en
full-iterateurs (mieux) ou en batch's. Sinon, question temps, qu'est ce que
ça donne pour indexer tout ZdS (à peu près, hein)

On Jan 21, 2017 6:11 PM, "artragis" <notifications@github.com> wrote:

> *@artragis* commented on this pull request.
> ------------------------------
>
> In zds/searchv2/models.py
> <https://github.com/zestedesavoir/zds-site/pull/4096#pullrequestreview-17810485>
> :
>
> > +        See http://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.Elasticsearch.bulk
> +        and http://elasticsearch-py.readthedocs.io/en/master/helpers.html#elasticsearch.helpers.streaming_bulk
> +
> +        .. attention::
> +            Currently only implemented with "index" and "update" !
> +
> +        :param model: and model
> +        :type model: class
> +        :param force_reindexing: force all document to be returned
> +        :type force_reindexing: bool
> +        """
> +
> +        if not self.connected_to_es:
> +            return
> +
> +        objs = list(model.get_es_indexable(force_reindexing=force_reindexing))
>
> ici il vaudrait mieux éviter de faire une liste car ça risque de demander
> énormément de RAM.
>
> Je serais d'avis de créer des sous-listes de 10 éléments puis de les
> yielder. Ensuite plus qu'à faire la requêtes avec chaque sous-liste.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/4096#pullrequestreview-17810485>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHhjCy6j8mBDmj0QubNAsc97CaGurSbBks5rUjw3gaJpZM4LVOk9>
> .
>

2017-01-21 17:19 UTC, vhf commented
> Sinon, question temps, qu'est ce que ça donne pour indexer tout ZdS (à peu près, hein)

J'ai ajouté 4GB de swap et relancé le processus il y a 25 minutes. On verra.

2017-01-21 17:46 UTC, vhf requested changes

2017-01-21 17:46 UTC, vhf commented on zds/forum/models.py
> +        es_mapping.field('get_absolute_url', Text(index='not_analyzed'))
`index` doit être un booléen, pas un string. Je suppose que `False` vaut `not_analyzed`.

(Je mets qu'un commentaire, mais faut changer les 18 occurrences de `index='not_analyzed'`)

2017-01-21 18:05 UTC, pierre-24 commented
T'as raison, mais ça fonctionne quand même pour des raisons de
rétro-compatibilité :) (je corrige ça tantôt)

On Jan 21, 2017 6:46 PM, "victor felder" <notifications@github.com> wrote:

*@vhf* requested changes on this pull request.
------------------------------

In zds/forum/models.py
<https://github.com/zestedesavoir/zds-site/pull/4096#pullrequestreview-17811102>
:

> @@ -382,9 +387,73 @@ def old_post_warning(self):

         return False

+    @classmethod
+    def get_es_mapping(cls):
+        es_mapping = super(Topic, cls).get_es_mapping()
+
+        es_mapping.field('title', Text(boost=1.5))
+        es_mapping.field('tags', Keyword(boost=2.0))
+        es_mapping.field('subtitle', Text())
+        es_mapping.field('is_solved', Boolean())
+        es_mapping.field('is_locked', Boolean())
+        es_mapping.field('is_sticky', Boolean())
+        es_mapping.field('pubdate', Date())
+
+        # not analyzed:
+        es_mapping.field('get_absolute_url', Text(index='not_analyzed'))

index doit être un booléen, pas un string. Je suppose que False vaut
not_analyzed.

(Je mets qu'un commentaire, mais faut changer les 18 occurrences de
index='not_analyzed')

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zestedesavoir/zds-site/pull/4096#pullrequestreview-17811102>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AHhjC8rxL3gOnqbOcAcOSvTIsXnidj5bks5rUkSCgaJpZM4LVOk9>
.

2017-01-21 21:36 UTC, vhf commented on zds/searchv2/models.py
>          """Get a list of object to be indexed. Thought this method, you may limit the reindexing.
"Through"

2017-01-21 21:36 UTC, vhf commented on zds/searchv2/models.py
>          :param force_reindexing: force to return all objects, even if they may be already indexed.
"if they may already be indexed."

2017-01-21 21:36 UTC, vhf commented on zds/searchv2/models.py
>          """Overridden to actually save the values of ``es_flagged`` and ``es_already_indexed`` into BDD.
"into DB"

2017-01-21 21:36 UTC, vhf commented on zds/searchv2/models.py
> -        :raise ValueError: if id given by ES and pk does not match.
"do not match"

2017-01-21 21:36 UTC, vhf commented on zds/searchv2/models.py
> +            objects = query.filter(pk__gt=current_pk)[:objects_per_batch].all()
On slice plutôt sur `.all()` : `.filter(foo=bar).all()[sl:ce]`, c'est plus lisible. ;)

2017-01-21 21:36 UTC, vhf commented on zds/searchv2/models.py
> +                yield obj
Du coup si on `yield` un objet après l'autre, c'est pas trop un batch de 100 objets. Pourquoi pas yielder `objects` ?

2017-01-22 08:57 UTC, GCodeur commented on doc/source/back-end/searchv2.rst
> +En particulier, c'est la méthode ``get_es_indexable()`` qui est modifiée, profitant du fait que cette fonction peut envoyer n'importe quel type de document à indexer.
`renvoyer` serait peut-être mieux, non ?

2017-01-22 09:22 UTC, pierre-24 commented
@GCodeur: c'est yield, donc ça se discute ;)

On Jan 22, 2017 9:57 AM, "Guillaume" <notifications@github.com> wrote:

*@GCodeur* commented on this pull request.
------------------------------

In doc/source/back-end/searchv2.rst
<https://github.com/zestedesavoir/zds-site/pull/4096#pullrequestreview-17823831>
:

> @@ -313,27 +313,36 @@ Les avantages de cette situation sont multiples:


 Pour ce faire, l'indexation des chapitres (stocké à l'aide de la
classe ``FakeChapter``, `voir ici
<../back-end-code/tutorialv2.html#zds.tutorialv2.models.models_database.FakeChapter>`_)
est effectuée en même temps que l'indexation des contenus publiés
(``PublishedContent``).
-En particulier, c'est la méthode ``get_es_indexable()`` qui est
modifiée, profitant du fait que cette fonction peut retourner
n'importe quel type de document à indexer.
+En particulier, c'est la méthode ``get_es_indexable()`` qui est
modifiée, profitant du fait que cette fonction peut envoyer n'importe
quel type de document à indexer.

renvoyer serait peut-être mieux, non ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zestedesavoir/zds-site/pull/4096#pullrequestreview-17823831>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AHhjC2RfswUHwOv62ex8dHrHGDGh659Lks5rUxn3gaJpZM4LVOk9>
.

2017-01-22 13:04 UTC, vhf commented
Bon, je viens aux nouvelles.

```
$ time python manage.py es_manager index_all
- indexing topics
- indexing posts
- indexing publishedcontents

real    90m37.333s
user    42m57.330s
sys     1m10.100s
```

Donc déjà, ça crash plus et ça semble tout indexer correctement. La commande prend maximum 3% de la RAM, ce qui est très peu donc beaucoup mieux. Les batch fonctionnent.

Le problème maintenant, et on devrait pouvoir faire ça 3x plus vite si on regarde de plus près, c'est les requêtes qui récupèrent le contenu à indexer. Elles sont toutes extrêmement lentes, à un point difficilement acceptable.

Voici une de ces requêtes : 

```sql
# Query_time: 3.607905  Lock_time: 0.000340 Rows_sent: 100  Rows_examined: 382786
SELECT `utils_comment`.`id`, `utils_comment`.`author_id`, `utils_comment`.`editor_id`, `utils_comment`.`ip_address`, `utils_comment`.`position`, `utils_comment`.`text`, `utils_comment`.`text_html`, `utils_comment`.`like`, `utils_comment`.`dislike`, `utils_comment`.`pubdate`, `utils_comment`.`update`, `utils_comment`.`update_index_date`, `utils_comment`.`is_visible`, `utils_comment`.`text_hidden`, `forum_post`.`comment_ptr_id`, `forum_post`.`es_flagged`, `forum_post`.`es_already_indexed`, `forum_post`.`topic_id`, `forum_post`.`is_useful`, `forum_topic`.`id`, `forum_topic`.`es_flagged`, `forum_topic`.`es_already_indexed`, `forum_topic`.`title`, `forum_topic`.`subtitle`, `forum_topic`.`forum_id`, `forum_topic`.`author_id`, `forum_topic`.`last_message_id`, `forum_topic`.`pubdate`, `forum_topic`.`update_index_date`, `forum_topic`.`is_solved`, `forum_topic`.`is_locked`, `forum_topic`.`is_sticky`, `forum_forum`.`id`, `forum_forum`.`title`, `forum_forum`.`subtitle`, `forum_forum`.`category_id`, `forum_forum`.`position_in_category`, `forum_forum`.`slug` FROM `forum_post` INNER JOIN `utils_comment` ON ( `forum_post`.`comment_ptr_id` = `utils_comment`.`id` ) INNER JOIN `forum_topic` ON ( `forum_post`.`topic_id` = `forum_topic`.`id` ) INNER JOIN `forum_forum` ON ( `forum_topic`.`forum_id` = `forum_forum`.`id` ) WHERE `forum_post`.`comment_ptr_id` > 11718 ORDER BY `forum_post`.`comment_ptr_id` ASC LIMIT 100;
```

Comme on fait des batchs de 100, c'est facile d'évaluer combien de temps il faut pour indexer les posts : 

```
batch de 100 posts
>> select count(*) from utils_comment;
> 134463
>> ((134463/100 * 3.5s) /60) minutes
> 78 minutes
```

Une première solution est de faire de plus gros batch. Mais ça n'aura qu'un petit impact comparé à améliorer ces requêtes.

2017-01-22 13:07 UTC, artragis commented
peut être changer l'order by pour y mettre la date qui est sûrement 
mieux indexée.


Le 22/01/2017 à 14:04, victor felder a écrit :
>
> Bon, je viens aux nouvelles.
>
> |$ time python manage.py es_manager index_all - indexing topics - 
> indexing posts - indexing publishedcontents real 90m37.333s user 
> 42m57.330s sys 1m10.100s |
>
> Donc déjà, ça crash plus et ça semble tout indexer correctement. La 
> commande prend maximum 3% de la RAM, ce qui est très peu donc beaucoup 
> mieux. Les batch fonctionnent.
>
> Le problème maintenant, et on devrait pouvoir faire ça 3x plus vite si 
> on regarde de plus près, c'est les requêtes qui récupèrent le contenu 
> à indexer. Elles sont toutes extrêmement lentes, à un point 
> difficilement acceptable.
>
> Voici une de ces requêtes :
>
> # Query_time: 3.607905 Lock_time: 0.000340 Rows_sent: 100 
> Rows_examined: 382786
> SELECT `utils_comment`.`id`, `utils_comment`.`author_id`, `utils_comment`.`editor_id`, `utils_comment`.`ip_address`, `utils_comment`.`position`, `utils_comment`.`text`, `utils_comment`.`text_html`, `utils_comment`.`like`, `utils_comment`.`dislike`, `utils_comment`.`pubdate`, `utils_comment`.`update`, `utils_comment`.`update_index_date`, `utils_comment`.`is_visible`, `utils_comment`.`text_hidden`, `forum_post`.`comment_ptr_id`, `forum_post`.`es_flagged`, `forum_post`.`es_already_indexed`, `forum_post`.`topic_id`, `forum_post`.`is_useful`, `forum_topic`.`id`, `forum_topic`.`es_flagged`, `forum_topic`.`es_already_indexed`, `forum_topic`.`title`, `forum_topic`.`subtitle`, `forum_topic`.`forum_id`, `forum_topic`.`author_id`, `forum_topic`.`last_message_id`, `forum_topic`.`pubdate`, `forum_topic`.`update_index_date`, `forum_topic`.`is_solved`, `forum_topic`.`is_locked`, `forum_topic`.`is_sticky`, `forum_forum`.`id`, `forum_forum`.`title`, `forum_forum`.`subtitle`, `forum_forum`.`category_id`, `forum_forum`.`position_in_category`, `forum_forum`.`slug` FROM `forum_post` INNER JOIN `utils_comment` ON ( `forum_post`.`comment_ptr_id` = `utils_comment`.`id` ) INNER JOIN `forum_topic` ON ( `forum_post`.`topic_id` = `forum_topic`.`id` ) INNER JOIN `forum_forum` ON ( `forum_topic`.`forum_id` = `forum_forum`.`id` ) WHERE `forum_post`.`comment_ptr_id` > 11718 ORDER BY `forum_post`.`comment_ptr_id` ASC LIMIT 100;
>
> Comme on fait des batchs de 100, c'est facile d'évaluer combien de 
> temps il faut pour indexer les posts :
>
> |batch de 100 posts >> select count(*) from utils_comment; > 134463 >> 
> ((134463/100 * 3.5s) /60) minutes > 78 minutes |
>
> Une première solution est de faire de plus gros batch. Mais ça n'aura 
> qu'un petit impact comparé à améliorer ces requêtes.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-274329803>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xd8nB3JoSx-9I8rkZbEta0b7PsXOks5rU1PUgaJpZM4LVOk9>.
>

2017-01-22 13:13 UTC, vhf commented
Pas de différence. `comment_ptr_id` est la primary key ici, donc a priori y'a pas mieux comme index.

2017-01-22 13:24 UTC, pierre-24 commented
Je vous avoue que j'ai aucune idée de comment améliorer ça :s

On Jan 22, 2017 2:13 PM, "victor felder" <notifications@github.com> wrote:

> Pas de différence. comment_ptr_id est la primary key ici, donc a priori
> y'a pas mieux comme index.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-274330281>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHhjC_PHJwj2qIAGuYb_DvNG_NPILWwGks5rU1YUgaJpZM4LVOk9>
> .
>

2017-01-22 13:26 UTC, vhf commented
En fait il faudrait "juste" remplacer ces `INNER JOIN` par des `LEFT JOIN`, j'ai l'impression.

2017-01-22 13:28 UTC, vhf commented
```
Query_ID  Duration  Query
1 3.47567550  SELECT SQL_NO_CACHE […] INNER JOINs
2 0.00462125  SELECT SQL_NO_CACHE […] LEFT JOINs
```

2017-01-22 13:29 UTC, pierre-24 commented
Ah, ça doit être du côté des prefetch_related() alors ...

On Jan 22, 2017 2:28 PM, "victor felder" <notifications@github.com> wrote:

> Query_ID  Duration  Query
> 1 3.47567550  SELECT SQL_NO_CACHE […] INNER JOINs
> 2 0.00462125  SELECT SQL_NO_CACHE […] LEFT JOINs
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-274330994>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHhjC8x1RoIYsLEYqkU2Vcd2Bj215ggYks5rU1mGgaJpZM4LVOk9>
> .
>

2017-01-22 14:20 UTC, vhf commented
J'ai effectivement plus aucune slow query quand je change les 2 `select_related` des Posts en `prefetch_related`. Ça indexe approximativement 2x plus vite.

2017-01-22 14:23 UTC, vhf commented on zds/searchv2/models.py
> +                current_pk = obj.pk
Plutôt :

```diff
-            for obj in objects:
-                current_pk = obj.pk
+            current_pk = objects[-1].pk
```

?

2017-01-22 14:24 UTC, vhf commented on zds/utils/templatetags/elasticsearch.py
> +        if fragment != '':
`if fragment:` ?

2017-01-22 14:25 UTC, vhf commented on zds/utils/templatetags/elasticsearch.py
> +        if search_result[field] != '':
`if search_result[field]:` ?

2017-01-22 14:25 UTC, vhf commented on zds/searchv2/models.py
> +            if self.es_id != '':
`if self.es_id:` ?

2017-01-22 14:35 UTC, vhf commented
Idéalement il faudrait des batch sizes différentes pour les modèles. Je pense que pour les posts, on peut facile monter à 1000. A l'inverse, pour les PublishedContents, ES timeout avec une batch size de 500.

2017-01-24 22:56 UTC, vhf commented
Bon, j'ai retouché quelques trucs pour que ça aille plus vite. J'hésite entre 2 options, la 1ère c'est l'indexation hyper rapide à coup de multiprocessing et ça prend ~10min pour tout indexer par contre on peut pas trop faire ça en live, l'avantage c'est que la maintenance est courte. La seconde c'est une indexation qui prend environ 16 minutes mais qui est faisable en live. Je pense que je vais partir sur la seconde.

Les points importants que j'ai changé et qui avaient un gros impact ou qui n'étaient pas viables:

* Wrapper l'indexation d'un modèle dans une transaction. C'est pas vraiment viable. Les forums, avec le code initial, ça prenait ~75 minutes à indexer. Une transaction de 75 minutes, ça pose des tas de problèmes. J'ai cherché la raison de la présence du décorateur `@atomic` ici et je ne l'ai pas trouvée. Comme il est possible que j'aie pas pensé à un truc, merci de rectifier si cette transaction était vraiment primordiale :)
* `for obj in [centaines d'objets]: obj.update()` : c'est vraiment lent, on peut faire un update sur tous les objets d'un coup
* `dernier_obj = None; for obj in [centaines d'objets]: dernier_obj = obj` : même s'il n'est pas possible de slicer (`xs[-1]`), on peut toujours faire `xs[len(xs) - 1]`

2017-01-25 11:44 UTC, anayrat commented
Pour préciser, pourquoi OFFSET c'est mal : <http://use-the-index-luke.com/fr/no-offset>

2017-01-26 20:37 UTC, SpaceFox commented
J'ai l'impression que la version actuellement en bêta est très consommatrice pour l'indexation, ça vous paraît normal ? https://munin.spacefox.fr/zestedesavoir.com/beta.zestedesavoir.com/cpu.html

2017-01-26 20:45 UTC, artragis commented
C'est plutôt ça qui est gênant : 
https://munin.spacefox.fr/zestedesavoir.com/beta.zestedesavoir.com/mysql_slow.html



Le 26/01/2017 à 21:37, SpaceFox a écrit :
>
> J'ai l'impression que la version actuellement en bêta est très 
> consommatrice pour l'indexation, ça vous paraît normal ? 
> https://munin.spacefox.fr/zestedesavoir.com/beta.zestedesavoir.com/cpu.html
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-275506368>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xfxrlR0_I8IYnDeikJicu5ckBJxmks5rWQQegaJpZM4LVOk9>.
>

2017-01-26 20:47 UTC, vhf commented
Normal, oui. On n'a pas encore regardé. Si c'est comme pour l'indexation totale, qu'on a fait passer de 90min et 130% de RAM à 2% de RAM et 10min, ça m'inquiète pas trop.

En l'état, c'est viable. Et amiolerable, certainement aussi. Peut-être même drastiquement.

2017-01-26 20:49 UTC, vhf commented
Non le mysql slow faut pas vous en faire. Les paramètres sont pas du tout les mêmes. Je dois régulièrement les adapter sur la beta pour obtenir des infos utiles à optimiser les trucs. En vrai ce graphe est totalement indépendant du Backend actuel.

2017-01-26 20:53 UTC, SpaceFox commented
>
> C'est plutôt ça qui est gênant :
> https://munin.spacefox.fr/zestedesavoir.com/beta.
> zestedesavoir.com/mysql_slow.html


Vu l'échelle, même en l'état il n'y a rien d'inquiétant. Si en plus y'a des
expérimentations de victor là-dessous, tout va bien.

Le 26 janvier 2017 à 21:49, victor felder <notifications@github.com> a
écrit :

> Non le mysql slow faut pas vous en faire. Les paramètres sont pas du tout
> les mêmes. Je dois régulièrement les adapter sur la beta pour obtenir des
> infos utiles à optimiser les trucs. En vrai ce graphe est totalement
> indépendant du Backend actuel.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-275509269>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFhKnBiF3rMOt_a5FURxxLuipr3ZNtv8ks5rWQbPgaJpZM4LVOk9>
> .
>

2017-01-26 20:57 UTC, vhf commented
A propos de trucs remarquables mais insignifiants sur les stats de la beta, pour vous dire à quel point ça nous aide tout en étant difficilement interpretable extérieurement, regardez le wget / http.

2017-01-26 21:05 UTC, SpaceFox commented
WTF ?!

2017-01-26 21:57 GMT+01:00 victor felder <notifications@github.com>:

> A propos de trucs remarquables mais insignifiants sur les stats de la
> beta, pour vous dire à quel point ça nous aide tout en étant difficilement
> interpretable extérieurement, regardez le wget / http.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-275511291>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFhKnEbMD94x5b-EEIFcQDb41Vfz0Ir3ks5rWQi9gaJpZM4LVOk9>
> .
>

2017-01-26 21:25 UTC, Situphen commented
Si vous parlez bien de [cette page](https://munin.spacefox.fr/zestedesavoir.com/beta.zestedesavoir.com/wget_page.html) ça voudrait dire que le temps de chargement des pages a baissé ?

2017-01-27 16:36 UTC, GCodeur commented on zds/settings.py
> +            ('post', _(u'Messages du forums')),
`Messages du forum` (sans `s`). ;)

Ou alors, pourquoi pas `Sujets des forums` et `Messages des forums` ?

2017-01-27 16:38 UTC, GCodeur commented on zds/settings.py
> +            ('chapter', _(u'Chapitres publiés')),
Pas sûr que ces deux labels soient vraiment compréhensibles par un nouveau venu sur le site. Pourquoi pas `Tutoriels et articles` et `Chapitres de contenus` ?

2017-01-27 16:38 UTC, Situphen commented on zds/settings.py
> +            ('post', _(u'Messages du forums')),
On utilise partout "forum" au singulier pour parler "des forums" (par exemple dans la barre en haut du site) donc soit l'un soit l'autre mais ne pas garder 2 termes différents. Le plus simple est de garder le singulier je pense.

2017-01-27 16:40 UTC, Situphen commented on zds/settings.py
> +            ('chapter', _(u'Chapitres publiés')),
+1 mais attention quand même, quand il y aura les tribunes ça risque de faire long `Tutoriels, articles et tribunes` !

2017-01-27 16:40 UTC, GCodeur commented on zds/settings.py
> +            ('post', _(u'Messages du forums')),
OK, il faut juste enlever le `s` à `forums` alors. :)

2017-01-27 23:40 UTC, vhf commented
Pour la question d'http/wget, c'était une bête mauvaise config ipv6.

Pour la question CPU indexation chaque 30min, c'est réglé et c'était vraiment trivial. Merci SpaceFox d'avoir porté mon attention dessus. J'avais pas encore regardé cet aspect, mais attirer mon attention dessus était une bonne idée.

2017-01-27 23:41 UTC, vhf approved these changes

2017-01-27 23:43 UTC, vhf commented on zds/settings.py
> +            ('chapter', _(u'Chapitres publiés')),
Je ne comprends pas bien la distinction entre "Contenus publiés" et "Chapitres publiés". Et pourtant je crois que je touche un peu au projet. Je propose que @pierre-24 explique la différence, parce que sans la connaitre j'ai de la peine à considérer les alternatives.

2017-01-28 14:49 UTC, GCodeur commented on zds/settings.py
> +            ('chapter', _(u'Chapitres publiés')),
@vhf : quand on cherche `Contenus publiés`, on tombe sur les contenus eux-mêmes :

![Contenus publiés](https://www.pixenli.com/images/1485/1485614817043991900.png)

Alors que quand on fait `Chapitres publiés`, on tombe sur des chapitres appartenant aux contenus :

![Chapitres publiés](https://www.pixenli.com/images/1485/1485614851029601900.png)

Cette distinction existe déjà sur la version actuelle de la recherche. :)

2017-01-28 17:26 UTC, vhf commented on zds/settings.py
> +            ('chapter', _(u'Chapitres publiés')),
Ok, merci. Je comprends bien pourquoi on fait ça dans l'implémentation de la recherche, mais je vois pas l'intérêt d'exposer ce détail à l'utilisateur. Ça me rend confus devant le champ de recherche.

Je vois pas dans quel cas on voudrait chercher dans "intro et conclusion" mais pas "chapitres", ou dans "chapitres" sauf "intro et conclusion". Du coup j'ai retouché le formulaire de recherche pour qu'il n'affiche que "contenus publiés", qui se comporte comme si dans la version actuelle on cochait "contenus publiés + chapitres".

C'est là, avec les autres commits à rapatrier : https://github.com/zestedesavoir/zds-site/commits/elasticsearch-no-mp :)

2017-01-29 13:13 UTC, pierre-24 commented
Je suis de retour, entre deux avions. Je sais pas encore exactement quand
j'ai le temps de lire et réagir à tout ça, mais demain soir grand max :)

On Jan 28, 2017 6:26 PM, "victor felder" <notifications@github.com> wrote:

> *@vhf* commented on this pull request.
> ------------------------------
>
> In zds/settings.py <https://github.com/zestedesavoir/zds-site/pull/4096>:
>
> > @@ -531,6 +546,39 @@
>      'paginator': {
>          'folding_limit': 4
>      },
> +    'search': {
> +        'mark_keywords': ['javafx', 'haskell', 'groovy', 'powershell', 'latex', 'linux', 'windows'],
> +        'results_per_page': 20,
> +        'indexables': [
> +            ('publishedcontent', _(u'Contenus publiés')),
> +            ('chapter', _(u'Chapitres publiés')),
>
> Ok, merci. Je comprends bien pourquoi on fait ça dans l'implémentation de
> la recherche, mais je vois pas l'intérêt d'exposer ce détail à
> l'utilisateur. Ça me rend confus devant le champ de recherche.
>
> Je vois pas dans quel cas on voudrait chercher dans "intro et conclusion"
> mais pas "chapitres", ou dans "chapitres" sauf "intro et conclusion". Du
> coup j'ai retouché le formulaire de recherche pour qu'il n'affiche que
> "contenus publiés", qui se comporte comme si dans la version actuelle on
> cochait "contenus publiés + chapitres".
>
> C'est là, avec les autres commits à rapatrier : https://github.com/
> zestedesavoir/zds-site/commits/elasticsearch-no-mp :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/4096>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHhjC3E4M9UgDJl1HhxhzDubW5NvuR3rks5rW3pggaJpZM4LVOk9>
> .
>

2017-01-29 20:56 UTC, pierre-24 commented
Bon voilà. J'ai mergé les commits de @vhf  ici (joli travail, du coup je te fais grosso modo confiance vu que t'as testé, donc j'ai relu, mais j'ai rien trouvé de déconnant, je repasse de suite) et j'ai aussi mergé une proposition de @Situphen pour le design (merci à toi !).

Au delà de tout ça, ben ... Y'a plus qu'à tester. Donc là, il faut des gens qui fasse des requêtes intelligentes sur https://beta.zestedesavoir.com/rechercher/ et qui voient si les résultats correspondent à leurs attentes (le but, c'est d'éventuellement tripoter les facteurs de *boost*). Merci à tous, on en vois le bout !! :)

2017-01-29 21:23 UTC, pierre-24 commented on zds/searchv2/models.py
> +
valeur par défaut de `objects_per_batch` ici ?

2017-01-29 21:23 UTC, pierre-24 commented on zds/searchv2/models.py
> +        yield []
Tout compte fait, c'est pas du *yield* (voir la version django)

2017-01-29 21:23 UTC, pierre-24 commented on zds/searchv2/models.py
> +    def es_done_indexing(self):
Méthode encore utile ?

2017-01-29 21:23 UTC, pierre-24 commented on zds/searchv2/models.py
> +        """
Ajouter un *warning* "si vous touchez à ça, vous devez index_all !!"

2017-01-29 21:23 UTC, pierre-24 commented on zds/searchv2/models.py
> +                        if self.logger.getEffectiveLevel() <= logging.INFO:
@vhf : je ne comprend pas cette ligne o_O

2017-01-29 21:23 UTC, pierre-24 commented on zds/searchv2/models.py
> +        """Refresh the index. The task is done periodically, but may be forced with this method
être plus explicite.

2017-01-29 21:23 UTC, pierre-24 commented on doc/source/back-end/searchv2.rst
> +      'search': {
Ne correspond plus tout à fait à la réalité (`"search_group"`!)

2017-01-29 21:23 UTC, pierre-24 commented on doc/source/install/install-es.rst
> +    Par défaut, Elasticsearch requiert au moins 2 Gio de mémoire pour démarrer.
@vhf : du coup, ça donne quoi au niveau de la consommation réelle ?

2017-01-29 21:23 UTC, pierre-24 commented on doc/source/install/install-es.rst
> +.. figure:: ../images/search/no-connection.png
Mettre à jour l'image (le design à changé)

2017-01-29 21:26 UTC, pierre-24 commented on doc/source/install/install-es.rst
> +    Par défaut, Elasticsearch requiert au moins 2 Gio de mémoire pour démarrer.
Réponse à moi-même : https://munin.spacefox.fr/zestedesavoir.com/beta.zestedesavoir.com/index.html#elasticsearch ... Ça va, avec 512 Mio, on est large :)

2017-01-31 20:40 UTC, vhf commented on zds/searchv2/models.py
> +
volontiers oui, bien vu

2017-01-31 20:40 UTC, vhf commented on zds/searchv2/models.py
> +    def es_done_indexing(self):
probablement pas, à vérifier

2017-01-31 20:41 UTC, vhf commented on zds/searchv2/models.py
> +                        if self.logger.getEffectiveLevel() <= logging.INFO:
Elle ne log que si on peut logger. On peut clairement s'en passer, c'était pour mes tests.

2017-01-31 20:41 UTC, vhf commented on doc/source/back-end/searchv2.rst
> +      'search': {
Oui à corriger.

2017-01-31 20:42 UTC, vhf commented
Niveau consommation RAM ça a l'air tout à fait acceptable avec 512Mo. Pour l'indexation j'ai choisi de pas aller à pleine vitesse pour qu'elle n'impact pas trop les visites si on doit la faire en entier sans downtime.

2017-01-31 20:56 UTC, pierre-24 commented on doc/source/back-end/searchv2.rst
> +      'search': {
Fait !

2017-01-31 20:56 UTC, pierre-24 commented on zds/searchv2/models.py
> +
Fait :)

2017-01-31 20:56 UTC, pierre-24 commented on zds/searchv2/models.py
> +    def es_done_indexing(self):
Je confirme qu'elle n'est plus utilisée, donc je vais la virer.

2017-01-31 20:57 UTC, pierre-24 commented on zds/searchv2/models.py
> +                        if self.logger.getEffectiveLevel() <= logging.INFO:
Ok :)

2017-01-31 21:08 UTC, pierre-24 commented
> Niveau consommation RAM ça a l'air tout à fait acceptable avec 512Mo. Pour l'indexation j'ai choisi de pas aller à pleine vitesse pour qu'elle n'impact pas trop les visites si on doit la faire en entier sans downtime.

Parfait :)

> Quand c'est tout bon ici je déploierai cette PR en beta. En l'état c'est pas possible parce que ça demande de compiler le front, donc un tag, et je préfère pas tagger si on sait ce qu'on doit corriger.

Tout ce que je m'étais repéré est corrigé. Je te passe la main :)

2017-02-01 01:28 UTC, DevHugo commented
Quand je tape [Android](https://beta.zestedesavoir.com/rechercher/?q=Android), [Java](https://beta.zestedesavoir.com/rechercher/?q=Java), [Python](https://beta.zestedesavoir.com/rechercher/?q=python) à chaque fois les tutos intéressant sont des big-tuto. Ça serait possible de booster selon leurs tailles ?

Y'a un bug dans les résultats avec les mots clés python sur la béta … : 

![capture](https://cloud.githubusercontent.com/assets/6099338/22491774/01febd50-e826-11e6-9733-ada4ccb6c484.PNG)

2017-02-01 07:14 UTC, pierre-24 commented
> Quand je tape Android, Java, Python à chaque fois les tutos intéressant sont des big-tuto. Ça serait possible de booster selon leurs tailles ?

... Ben on peut toujours légèrement [booster les tutos sur les articles](https://github.com/pierre-24/zds-site/blob/e415c997464865260e686193697c07d8930ceb06/doc/source/back-end/searchv2.rst#configuration). 

> Y'a un bug dans les résultats avec les mots clés python sur la béta … :

En effet ... Sauf que pour savoir de quel *item* il s'agit, ça va pas être marrant ;) (faudrait lancer une requête sur le port 9200 pour avoir les résultats)

Tient, @Situphen , faudrait pas mettre un peu de `margin-bottom` à la zone bleue avant le *pager* ?

2017-02-01 11:10 UTC, Situphen commented
@pierre-24 Ouais peut-être, ça me choque pas non plus. J'ai vu une petite régression sur la page d'accueil donc je vais te faire une petite PR je pense ;)

2017-02-01 11:23 UTC, pierre-24 commented
Si t'as le temps, tu peux aussi accorder la clem' de la recherche et de la page d'acceil :p

2017-02-01 20:45 UTC, pierre-24 commented
Me suis fait une réflexion suite à ce que @DevHugo disais : en effet, c'est les articles (et les mini-tutos) qui montent le plus. Et en fait, c'est "logique" : j'ai décidé de stocker directement le texte d'un article/mini-tuto avec l'objet correspondant. Du coup, comparé aux moyen/big tutos, y'a des possibilités de *hits* en plus, donc c'est eux qui sortent en premier. Le *patch* idiot à ça, c'est de booster légèrement ces derniers :-°

2017-02-01 21:21 UTC, pierre-24 commented
@DevHugo : sinon, pour faire avancer l'histoire, le blanc que t'as repéré correspond au tuto https://beta.zestedesavoir.com/tutoriels/334/panda3d-et-heightmap/ ... Pour une raison qui m'échappe actuellement.

2017-02-01 21:21 UTC, DevHugo commented
Tu as le JSON renvoyé ?

2017-02-01 21:23 UTC, pierre-24 commented
@vhf me l'as très gentiment fourni, c'est pour ça que je sais que ça correspond à ce tuto là, mais très vite fait, je vois pas l'erreur (y'a rien de mauvais dans le JSON à priori). Je tente en important le tuto en local.

2017-02-01 21:39 UTC, pierre-24 commented
J'ai peut-être quelque chose:

```json
      {
        "_index": "zds_search",
        "_type": "publishedcontent",
        "_id": "263",
        "_score": 20.60248,
        "_source": {
          "get_absolute_url_online": "/tutoriels/334/panda3d-et-heightmap/",
          "description": "Genèse d'un terrain : d'une HeightMap au rendu en temps réel",
          "tags": [
            "python",
            "graphisme 3d"
          ],
          "text": **trop de trucs**,
          "title": "Panda3D et HeightMap",
          "content_type": "TUTORIAL",
          "publication_date": null,
          "content_pk": 334,
          "thumbnail": "/media/galleries/899/bfe4ef23-bca2-43a5-b401-401a27b4fde9.png.96x96_q95_crop.png",
          "categories": [
            "Informatique",
            "Arts, graphisme et multimédia",
            "Programmation et algorithmique",
            "Autres"
          ]
        }
      },
```

En local, le code aprécie *middle* le `"publication_date": null`. Chaipas trop pourquoi en bêta ça passe quand même sans erreurs, mais toujours est-il que c'est pas le comportement attendu :)

2017-02-01 21:44 UTC, DevHugo commented
ouai mais sur la beta, les erreurs dans les templates sont pas affiché, il me semble.

2017-02-01 21:45 UTC, pierre-24 commented
Donc c'est probablement ça. Je vais mettre un `pubdate if pubdate else update_date` qui va bien là ou il faut :)

2017-02-01 21:46 UTC, DevHugo commented
Ça serait bien de comprendre pourquoi la pubdate est à null. C'est pas normal.

2017-02-01 21:47 UTC, pierre-24 commented
> Ça serait bien de comprendre pourquoi la pubdate est à null. C'est pas normal.

À force de migrer (avec la ZEP-12 et tout ça), je pense que tout doit pas être *nickel* partout. C'est limite étonnant que ça tienne le coup ailleurs :p

2017-02-01 21:48 UTC, DevHugo commented
Mouai, ça vaut peut-être le coup de faire une requête sql sur la prod pour vérifier que tout est ok.

2017-02-01 21:52 UTC, pierre-24 commented
De fait. Puis je dis ça, mais ça a l'air d'être un tuto post zep-12. @vhf ? C'est `tutorialv2_publishedcontent` et c'est bien le champ `publication_date` qui devrait idéalement pas être à NULL.

2017-02-01 22:07 UTC, vhf commented
```py
>>> from zds.tutorialv2.models.models_database import PublishedContent
>>> PublishedContent.objects.filter(publication_date=None).count()
210
>>> PublishedContent.objects.filter(publication_date=None, update_date=None).count()
209
>>> PublishedContent.objects.filter(publication_date=None, must_redirect=False).count()
1
>>> PublishedContent.objects.filter(publication_date=None, must_redirect=False)
[<PublishedContent: Version publique de "Panda3D et HeightMap">]
>>> PublishedContent.objects.filter(publication_date=None, must_redirect=False).first().content_pk
334L
>>> PublishedContent.objects.filter(content_pk=334)
[<PublishedContent: Version publique de "Panda3D et HeightMap">]
```

2017-02-01 22:10 UTC, DevHugo commented
C'est sur la prod ou la béta ?

2017-02-01 22:14 UTC, pierre-24 commented
Il est tout à fait probable que ce bug soit en cause de [la correction effectuée ici](https://github.com/zestedesavoir/zds-site/commit/1d788e0f6a5525aaa7289070d357990569943e70). En tout ca, ça ressemble furieusement à [ça](https://github.com/zestedesavoir/zds-site/pull/3146).

2017-02-01 22:16 UTC, pierre-24 commented
Ou bien [celui là](https://github.com/zestedesavoir/zds-site/commit/613a984b1eceee6577dc37f6b41efeafdf4b8e72#diff-314eb87fc4e5f8242f8fbcfbbcb796beR668).

2017-02-04 10:47 UTC, vhf commented
@pierre-24 peux-tu stp me résumer la situation ? Dans l'idéal, j'aimerais que ce soit mergé mercredi au plus tard, si possible avant mercredi.

En l'état j'arrive pas à déterminer si c'est mergeable ou pas (problème de migrations/travis mis à part).

2017-02-04 11:09 UTC, pierre-24 commented
Basiquement, le bug est du à un truc qui c'est passé par le passé et qui ne
devrait plus se reproduire (y'a deux tests pour ça). J'ai "réglé" le
problème par un "machin if machin else bidule", donc logiquement ça passe
quand même.

Du reste, je pense qu'on est bon ici, sauf erreur de ma part :)

On Feb 4, 2017 11:47 AM, "victor felder" <notifications@github.com> wrote:

@pierre-24 <https://github.com/pierre-24> peux-tu stp me résumer la
situation ? Dans l'idéal, j'aimerais que ce soit mergé mercredi au plus
tard, si possible avant mercredi.

En l'état j'arrive pas à déterminer si c'est mergeable ou pas (problème de
migrations/travis mis à part).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-277434941>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AHhjCxuX0xLsU00DXjkjv6srNIVKpaOoks5rZFcmgaJpZM4LVOk9>
.

2017-02-04 11:27 UTC, vhf commented
Super, merci @pierre-24 . Du coup il manque plus que les tests passent sur cette PR et quand c'est vert, on mergera.

2017-02-04 11:33 UTC, DevHugo commented
C'est un souci de migration: 

CommandError: Conflicting migrations detected (0016_auto_20170108_1148, 0016_auto_20170201_1940 in tutorialv2; 0011_auto_20170130_1823, 0011_auto_20161224_1310 in forum).
To fix them run 'python manage.py makemigrations --merge'

2017-02-04 11:48 UTC, pierre-24 commented
Ah, oui, forcément. Bon, je check Ça quand je rentre du fosdem.

On Feb 4, 2017 12:33 PM, "Hugo Courtecuisse" <notifications@github.com>
wrote:

> C'est un souci de migration:
>
> CommandError: Conflicting migrations detected (0016_auto_20170108_1148,
> 0016_auto_20170201_1940 in tutorialv2; 0011_auto_20170130_1823,
> 0011_auto_20161224_1310 in forum).
> To fix them run 'python manage.py makemigrations --merge'
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-277437685>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHhjCxGK17W6kHYoA6j0Ju9jQPo9BVSGks5rZGHugaJpZM4LVOk9>
> .
>

2017-02-04 21:50 UTC, pierre-24 commented
Voilà, j'ai réglé les souchis de migration, j'ai intégré `dev` et j'ai mis à jour sur les dernières versions des librairies.Tout est bon, normalement :)

2017-02-05 07:01 UTC, DevHugo commented
@vhf Pour moi, on est bon ! J'ai plus aucune remarque. Je te laisse appuyer sur le bouton final ?

2017-02-05 08:39 UTC, vhf commented
Super, merci !

2017-02-05 08:39 UTC, merged

2017-02-05 08:41 UTC, pierre-24 commented
Waaaaaw, c'est finalement mergé <3

On Feb 5, 2017 9:39 AM, "victor felder" <notifications@github.com> wrote:

> Merged #4096 <https://github.com/zestedesavoir/zds-site/pull/4096>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/4096#event-949367904>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AHhjC-FxhVAUtd0tVqzLsY3X59KNDiI2ks5rZYqrgaJpZM4LVOk9>
> .
>

2017-02-05 09:07 UTC, vhf commented
Yep, une affaire rondement menée, bravo à tous !

2017-02-05 09:10 UTC, pierre-24 commented
Je dois donc plein de bières à plein de monde, en particulier à @Situphen
(quand il sera majeur, obviously) :)

On Feb 5, 2017 10:07 AM, "victor felder" <notifications@github.com> wrote:

> Yep, une affaire rondement menée, bravo à tous !
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-277506287>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHhjC55l6pGIkaCGHZJGCj_J2o3ySlaHks5rZZFAgaJpZM4LVOk9>
> .
>

2017-02-05 10:06 UTC, Situphen commented
@pierre-24 dans un peu plus d'un mois alors xD y'aura juste un petit problème de distance :-°

2017-02-05 10:11 UTC, pierre-24 commented
T'es pas de Lille, toi ? :P

On Feb 5, 2017 11:06 AM, "Situphen" <notifications@github.com> wrote:

> @pierre-24 <https://github.com/pierre-24> dans un peu plus d'un mois
> alors xD y'aura juste un petit problème de distance :-°
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-277508719>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHhjCzRjnsC9sxc3EdC1lzhGeR27FqWrks5rZZ84gaJpZM4LVOk9>
> .
>

2017-02-05 10:28 UTC, Situphen commented
Nan mais oh ! Je suis breton moi ! :P

2017-02-05 10:30 UTC, pierre-24 commented
Ça peut toujours s'arranger, faut juste que je trouve une excuse pour aller
la bas ;)

On Feb 5, 2017 11:28 AM, "Situphen" <notifications@github.com> wrote:

> Nan mais oh ! Je suis breton moi ! :P
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/4096#issuecomment-277509820>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHhjC23oGAbjxtqLedeuGeK1Ey6ep1uBks5rZaRdgaJpZM4LVOk9>
> .
>