No more error 500.
zestedesavoir/zds-site pull request #4107
Opened 2017-01-02 20:02 UTC by artragis

J'ai corrigé l'erreur 500 qu'a vu Andr0 (https://sentry.sandhose.fr/zeste-de-savoir/beta-backend/issues/809/)

J'ai aussi tenté de comprendre pourquoi les tribunes n'apparaissent pas dans les tags.

2017-01-02 21:48 UTC, vhf requested changes

2017-01-02 21:48 UTC, vhf commented on zds/tutorialv2/views/views_published.py
> -            queryset = queryset.filter(content__sha_picked=F('sha_public'))
C'est un revert de 66f0093a0af86f59625ae9aaa8af203afd7a18f5.

La question est : les billets qui n'ont pas été choisis par l'équipe de ZdS doivent-ils apparaitre dans les listes de contenus aux côtés des articles et tutoriels, c'est à dire typiquement [ici](https://zestedesavoir.com/contenus/?category=programmation-et-algorithmique) ou seulement dans les listes de contenus de même type afin de ne pas les mélanger avec les articles et tutoriels, typiquement comme [ici](https://zestedesavoir.com/articles/?category=programmation-et-algorithmique) ?

Le staff semble vouloir la 2e option, les membres du forum aussi, les devs semblent préférer la première. @FanJiyong un avis ?

2017-01-02 21:58 UTC, SpaceFox commented
Fonctionnellement, je ne vois pas ce qui justifie de mélanger du contenu
validé et non-validé (si ce n'est que c'est plus simple à développer).

Le 2 janvier 2017 à 22:48, victor felder <notifications@github.com> a écrit
:

> *@vhf* requested changes on this pull request.
> ------------------------------
>
> In zds/tutorialv2/views/views_published.py
> <https://github.com/zestedesavoir/zds-site/pull/4107#pullrequestreview-14873362>
> :
>
> > @@ -324,8 +324,6 @@ def get_queryset(self):
>
>          if self.current_content_type:
>              queryset = queryset.filter(content_type=self.current_content_type)
> -        else:
> -            queryset = queryset.filter(content__sha_picked=F('sha_public'))
>
> C'est un revert de 66f0093
> <https://github.com/zestedesavoir/zds-site/commit/66f0093a0af86f59625ae9aaa8af203afd7a18f5>
> .
>
> La question est : les billets qui n'ont pas été choisis par l'équipe de
> ZdS doivent-ils apparaitre dans les listes de contenus aux côtés des
> articles et tutoriels, c'est à dire typiquement ici
> <https://zestedesavoir.com/contenus/?category=programmation-et-algorithmique>
> ou seulement dans les listes de contenus de même type afin de ne pas les
> mélanger avec les articles et tutoriels, typiquement comme ici
> <https://zestedesavoir.com/articles/?category=programmation-et-algorithmique>
> ?
>
> Le staff semble vouloir la 2e option, les membres du forum aussi, les devs
> semblent préférer la première. @FanJiyong <https://github.com/FanJiyong>
> un avis ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/4107#pullrequestreview-14873362>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFhKnEycF1Kmap8l79z-I0gDGHhuCFriks5rOXDHgaJpZM4LZMCT>
> .
>

2017-01-03 07:08 UTC, pierre-24 commented on zds/tutorialv2/views/views_published.py
> -            queryset = queryset.filter(content__sha_picked=F('sha_public'))
On mélange pas, évidement ! (et je suis dev :p )

2017-01-03 07:09 UTC, artragis commented
Ok, donc je changerai le comportement. Mais on va faire les choses un 
poil plus proprement.


Le 03/01/2017 à 08:08, Pierre Beaujean a écrit :
>
> *@pierre-24* commented on this pull request.
>
> ------------------------------------------------------------------------
>
> In zds/tutorialv2/views/views_published.py 
> <https://github.com/zestedesavoir/zds-site/pull/4107>:
>
> > @@ -324,8 +324,6 @@ def get_queryset(self):
>   
>           if self.current_content_type:
>               queryset = queryset.filter(content_type=self.current_content_type)
> -        else:
> -            queryset = queryset.filter(content__sha_picked=F('sha_public'))
>
> On mélange pas, évidement ! (et je suis dev :p )
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4107>, or mute the 
> thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xaCl4RJ-B85G5BWUMLtq6T1bX03jks5rOfP8gaJpZM4LZMCT>.
>

2017-01-04 09:00 UTC, FanJiyong commented
La tribune viens avec des règles du jeu différentes de tout ce qui existe
depuis lors sur le ZDS.

Ainsi tout les billets publiés doivent apparaître de façon identique sur
ces pages.

Peut être qu'un légers détail visuel pourrait marquer ceux mis en avant.

Le mer. 4 janv. 2017 à 09:00, Coveralls <notifications@github.com> a écrit :

> [image: Coverage Status] <https://coveralls.io/builds/9512597>
>
> Coverage decreased (-16.3%) to 70.729% when pulling *2e303c6
> <https://github.com/zestedesavoir/zds-site/commit/2e303c6f72a1bfd5a547bdc46d98ba788a408b7b>
> on artragis:some_things_on_tribunes* into *ef3d824
> <https://github.com/zestedesavoir/zds-site/commit/ef3d824b598ea3cb2a4e5443da9b14c5438e32b6>
> on zestedesavoir:zep-13-b*.
>
> —
> You are receiving this because you were mentioned.
>
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/4107#issuecomment-270314006>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AOc7tL00n06PGsX1IraJQBSAUsqtuWHfks5rO1GsgaJpZM4LZMCT>
> .
>

2017-01-08 20:15 UTC, artragis commented on zds/tutorialv2/views/views_published.py
> -            queryset = queryset.filter(content__sha_picked=F('sha_public'))
ça a été fixé.

2017-01-12 21:38 UTC, pierre-24 commented
@artragis : est ce que c'est bon avec #4114 ?

2017-01-17 11:57 UTC, artragis commented
go to #4160

2017-01-17 11:57 UTC, closed without merging