Améliorations de la page Pseudo et Email
zestedesavoir/zds-site pull request #4109
Opened 2017-01-03 04:04 UTC by AmarOk1412

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | évolution
| Ticket(s) (_issue(s)_) concerné(s)  | #4073 

### QA

* Vérifier qu'on puisse bien changer son adresse mail sans prendre une adresse mail d'un autre utilisateur, ni une adresse mail vide.
* Vérifier qu'on puisse changer son pseudo sans prendre celui d'un autre utilisateur, ni le pseudo vide.
* Vérifier que la case *Afficher publiquement son mail* fonctionne correctement

2017-01-03 12:48 UTC, artragis requested changes

2017-01-03 12:48 UTC, artragis commented on zds/member/forms.py
> +        if get_object_or_404(Profile, user__username=user.username).show_email:
faire le `get_object_or404` ici génère une requête quelque peu inutile puisque nous avons le paramètre `user` qui possède l'attribut `profile`.

du coup : 

```python
if user.profile and user.profile.show_email:
    self.fields['options'].initial += 'show_email'
```

2017-01-03 12:48 UTC, artragis commented on zds/member/forms.py
> +        if username != self.previous_username:
excellent <3

2017-01-03 12:48 UTC, artragis commented on zds/member/views.py
> +        if form.data['email'] and profile.user.email != form.data["email"]:
du coup je pense qu'utiliser les cleaned_data ne serait pas de trop, notamment pour ce qui concerne le "strip".

2017-01-03 13:39 UTC, AmarOk1412 commented on zds/member/views.py
> +        if form.data['email'] and profile.user.email != form.data["email"]:
exact et thx, je fais ça dans la journée

2017-01-08 14:45 UTC, pierre-24 commented
Rapport de QA: OK. Merci le loup :)

2017-01-08 14:45 UTC, merged