[Code-style] Uniformise les quotes -> single-quote - module Gallery
zestedesavoir/zds-site pull request #4112
Opened 2017-01-03 07:27 UTC by Eskimon

**Afin de rendre les code review plus simple, je fait les changements module par module**

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | évolution
| Ticket concerné  | #3704

### QA

* Nop - code review devrait suffire je suppose ?

2017-01-03 07:40 UTC, vhf requested changes

2017-01-03 07:40 UTC, vhf commented on zds/gallery/forms.py
> +                'placeholder': _(u'Nom de l\'utilisateur'),
On préfère utiliser partout `'` sauf quand la string contient un `'`, auquel cas pour ne pas avoir à l'échapper on préfère `"l'utilisateur"`. ;)

2017-01-03 09:31 UTC, Eskimon commented
C'est moche :(

2017-01-04 20:39 UTC, Eskimon commented
Voilà, j'ai mixé comme il se doit pour limiter les échappements en gardant le single quote le plus souvent possible

2017-01-04 20:46 UTC, Eskimon commented
Sinon je me demandais, je viens de voir ca : https://github.com/zestedesavoir/zds-site/pull/3998 et du coup ca sert à quelque chose que je passe du temps sur ces détails ou on s'en fout ? (note, ca me dérange pas de passer du temps sur les dits détail car je suis content de pouvoir contribuer (en faisant les trucs trivial et de détail, sans valeur ajouté), mais si c'est voué à rester en PR *ad vitam eternam* puis poubelle car déprécié alors autant m'avertir tout de suite que je perde pas trop de temps inutilement quand même)

2017-01-04 20:48 UTC, vhf commented
C'est tout sauf inutile, et très apprécié @Eskimon  :)

2017-01-04 21:07 UTC, Eskimon commented
Un test pétén well fu** you python2 encoding !

2017-01-07 11:40 UTC, vhf approved these changes

2017-01-07 11:40 UTC, merged

2017-01-07 11:40 UTC, vhf commented
Merci !