Fix some stuffs on zep13
zestedesavoir/zds-site pull request #4143
Opened 2017-01-08 20:26 UTC by pierre-24

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | correction de bug 
| Ticket(s) (_issue(s)_) concerné(s)  | #3993 

Je me suis attaqué à la liste des TODOs de la ZEP-13, l'histoire d'avancer (sauf l'histoire de la 500 que je laisse à @artragis), à savoir:

* Permettre de dévalider un billet (avec des tests et tout)
* Icône superposée au texte "aucun contenu" https://github.com/zestedesavoir/zds-site/pull/3993#issuecomment-270009766
* Bandeau vert vide sur les billets en cours de conversion vers article, contient "Ce billet a été promu" pour le staff https://github.com/zestedesavoir/zds-site/pull/3993#issuecomment-270013869
* Titre du MP résolution d'alerte de billet buggé https://github.com/zestedesavoir/zds-site/pull/3993#issuecomment-270014123

2017-01-08 21:07 UTC, artragis requested changes

2017-01-08 21:07 UTC, artragis commented on templates/tutorialv2/index.html
> +    {% if tutorials != None %}
je ne comprends pas cette modif.

2017-01-08 21:07 UTC, artragis commented on templates/tutorialv2/view/content_online.html
> +    {% for author in content.authors.all %}
Voilà qui est étrange. C'est même assez illogique : les auteurs doivent être ceux liés à la public_version.

2017-01-08 21:08 UTC, pierre-24 commented on templates/tutorialv2/view/content_online.html
> +    {% for author in content.authors.all %}
Je sais, je m'en suis rendu compte ;)

2017-01-08 21:11 UTC, pierre-24 commented on templates/tutorialv2/index.html
> +    {% if tutorials != None %}
Moi bien:

```python
>>> a = []
>>> r = 1 if a else 0
>>> print(r)
0
```

Autrement dit, si la liste est vide et que je ne fait pas `bidule != None`, la condition ne passe pas, alors qu'on a besoin qu'elle passe même si la liste est vide.

2017-01-08 21:15 UTC, artragis commented on templates/tutorialv2/index.html
> +    {% if tutorials != None %}
ok. Du coup je vois et du coup je me dis que le test de base n'est peut être pas sur la bonne variable. En tout cas, c'est probablement le pb.

2017-01-08 21:22 UTC, pierre-24 commented on templates/tutorialv2/index.html
> +    {% if tutorials != None %}
ça provient de la manière très tordue dont est codé [`ContentOfAuthor`](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/views_contents.py#L1816). Tellement tordue que je ne me souviens plus exactement de pourquoi ça marche.

2017-01-08 21:22 UTC, pierre-24 commented
Ça y est, maintenant [y'a npm qui s'y met](https://travis-ci.org/pierre-24/zds-site/jobs/190071697) ?!?

2017-01-09 22:22 UTC, vhf commented
Merci ! Est-ce que tu peux rebaser sur `dev` pour que travis passe stp ?

2017-01-10 07:26 UTC, pierre-24 commented
Eh bien techniquement non, en fait, puisque je me suis basé sur `zep-13-b`. Bon, comme je suis sympa, je l'ai quand même fait, ça t'évitera un *rebase* :)

2017-01-10 07:50 UTC, pierre-24 commented
Ok. Bon. Maintenant, c'est plein de *commits* de *dev*.

2017-01-10 08:50 UTC, Anto59290 commented
J'aurais bien jeté un coup d'oeil au code. Il y a une méthode pour relire tes commits sans que ça soit noyé dans la masse ?

2017-01-10 08:50 UTC, pierre-24 commented
Nan, c'est ça qui est chiant :/

2017-01-10 08:55 UTC, pierre-24 commented
(tu peux toujours lire commit par commit, mais c'est pénible)

2017-01-10 09:01 UTC, pierre-24 commented
@Anto59290 voilà, j'ai nettoyé, tu peux lire :)

2017-01-10 09:32 UTC, Anto59290 commented on zds/tutorialv2/views/views_validations.py
> +    """Publish the content"""
Ça serait pas Unpublish du coup  ?

2017-01-10 11:10 UTC, pierre-24 commented on zds/tutorialv2/views/views_validations.py
> +    """Publish the content"""
Si :)

2017-01-10 12:00 UTC, lethom commented
C’est sans doute la branche de la ZEP 13 qu’il faudrait rebaser et pas celle la, non ?

2017-01-10 12:04 UTC, pierre-24 commented
> C’est sans doute la branche de la ZEP 13 qu’il faudrait rebaser et pas celle la, non ?

Tout à fait, et du coup je suis revenu sur ma décision.

2017-01-15 15:56 UTC, vhf commented on zds/tutorialv2/forms.py
> +        if content.is_tutorial:
Il est peut-être possible d'utiliser [ceci](https://github.com/zestedesavoir/zds-site/blob/558a269c2eb913f5ba473d9cbdc24b70fc99708d/zds/tutorialv2/models/mixins.py#L45-L58) ici, non ?

2017-01-15 18:50 UTC, pierre-24 commented on zds/tutorialv2/forms.py
> +        if content.is_tutorial:
Oui. D'un autre côté, on a très souvent ce genre de code ou au final, le problème est de choisir le déterminant (ce, le, ...).

2017-01-15 20:35 UTC, pierre-24 commented
Et on recommence :)

2017-01-15 20:35 UTC, closed without merging