Correction de l'orthographe de la doc sur les galeries
zestedesavoir/zds-site pull request #4148
Opened 2017-01-10 17:26 UTC by GCodeur

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | orthographe

Voici les corrections sur la documentation concernant les galeries. :)

Note : je corrige également un lien, ainsi qu'une erreur : depuis la ZEP-12, les articles possèdent aussi une galerie liée.

### QA

Relire les corrections en vérifiant qu'elles sont exactes et que je n'ai pas introduit d'autres fautes en les faisant.

2017-01-12 20:04 UTC, artragis requested changes

2017-01-12 20:04 UTC, artragis commented on doc/source/back-end/gallery.rst
> +    Le titre de l'image n'entre pas en compte dans le nommage de l'image une fois cette dernière téléchargée. Afin de s'assurer l'unicité des noms, nous utilisons un algorithme de hachage pour cela.
je préfère qu'on mette `*hashage*` car c'est clairement un anglicisme pour dire "condenser numériquement".

2017-01-12 20:04 UTC, artragis commented on doc/source/back-end/gallery.rst
> +Afin d'assurer une compatibilité maximale de toutes les images des galeries et leur redimensionnement au besoin, le logiciel pyllow est utilisé.
Du coup autant mettre `Pyllow` entre double antiquote.

2017-01-12 20:16 UTC, GCodeur commented on doc/source/back-end/gallery.rst
> +    Le titre de l'image n'entre pas en compte dans le nommage de l'image une fois cette dernière téléchargée. Afin de s'assurer l'unicité des noms, nous utilisons un algorithme de hachage pour cela.
En effet, ça se discute pas mal. Sur [Wikipédia](https://fr.wikipedia.org/wiki/Fonction_de_hachage), ils utilisent `hachage`, mais il est vrai que l'emploi du mot français n'a pas vraiment de sens, donc je vais changer ça. :)

2017-01-12 20:16 UTC, GCodeur commented on doc/source/back-end/gallery.rst
> +Afin d'assurer une compatibilité maximale de toutes les images des galeries et leur redimensionnement au besoin, le logiciel pyllow est utilisé.
En effet, et comme tu l'as fait avec une majuscule. :)

2017-01-14 08:40 UTC, vhf commented on doc/source/back-end/gallery.rst
> +Afin d'assurer une compatibilité maximale de toutes les images des galeries et leur redimensionnement au besoin, le logiciel `Pyllow` est utilisé.
`Pillow` ;)

2017-01-14 08:40 UTC, vhf commented on doc/source/back-end/gallery.rst
> +Afin d'assurer une compatibilité maximale de toutes les images des galeries et leur redimensionnement au besoin, le logiciel pyllow est utilisé.
C'est `Pillow`, pas Pyllow. ;)

2017-01-14 08:46 UTC, vhf commented on doc/source/back-end/gallery.rst
> +    Le titre de l'image n'entre pas en compte dans le nommage de l'image une fois cette dernière téléchargée. Afin de s'assurer l'unicité des noms, nous utilisons un algorithme de hachage pour cela.
Perso je pense que cette phrase est complètement à revoir. Déjà parce que le hash d'un nom de fichier ne donne aucune garantie d'unicité, donc dire qu'on le fait pour "s'assurer [de] l'unicité" (note que *de* est manquant), c'est faux.

Ensuite - et c'est pas du tout important mais - de deux choses l'une : soit on utilise la version anglaise (par ex. *fonction de **hashing***), soit la version française (par ex. *fonction de **hachage***). Autant je trouve que *hachage* est moche, autant je préfère qu'on utilise le vrai mot anglais ou le vrai mot français plutôt qu'inventer une nouvelle francisation de *hashing*.

2017-01-14 09:39 UTC, artragis commented
Disons que la chance que deux fichiers d'une même gallerie aient le même 
hash est la même que celle d'avoir un avion qui se crash sur une maison 
de campagne en dehors des couloirs aériens.

De même le "de" devant unicité n'est pas nécessaire pour être à la fois 
compréhensible et grammaticalement correct.
Enfin, c'est bien la première fois que j'entends "hashing". J'entends 
souvent "hash function" en anglais mais bon. Au pire, vue la phrase on 
est forcément dans l'anglicisme, le truc c'est qu'il faut qu'on soit 
compréhensible.



Le 14/01/2017 à 09:46, victor felder a écrit :
>
> *@vhf* commented on this pull request.
>
> ------------------------------------------------------------------------
>
> In doc/source/back-end/gallery.rst 
> <https://github.com/zestedesavoir/zds-site/pull/4148>:
>
> >
>   .. attention::
> -    Le titre de l'image n'entre pas en compte dans le nommage de l'image une fois cette dernière téléchargée. Afin de s'assurer l'unicité des noms, nous utilisons un algorithme de hashage pour cela.
> +    Le titre de l'image n'entre pas en compte dans le nommage de l'image une fois cette dernière téléchargée. Afin de s'assurer l'unicité des noms, nous utilisons un algorithme de hachage pour cela.
>
> Perso je pense que cette phrase est complètement à revoir. Déjà parce 
> que le hash d'un nom de fichier ne donne aucune garantie d'unicité, 
> donc dire qu'on le fait pour "s'assurer [de] l'unicité" (note que /de/ 
> est manquant), c'est faux.
>
> Ensuite - et c'est pas du tout important mais - de deux choses l'une : 
> soit on utilise la version anglaise (par ex. /fonction de *hashing*/), 
> soit la version française (par ex. /fonction de *hachage*/). Autant je 
> trouve que /hachage/ est moche, autant je préfère qu'on utilise le 
> vrai mot anglais ou le vrai mot français plutôt qu'inventer une 
> nouvelle francisation de /hashing/.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4148>, or mute the 
> thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xSu8eWlX9a6GPV5gjvRiUprdlREXks5rSItmgaJpZM4LfreL>.
>

2017-01-14 10:05 UTC, vhf commented on doc/source/back-end/gallery.rst
> +    Le titre de l'image n'entre pas en compte dans le nommage de l'image une fois cette dernière téléchargée. Afin de s'assurer l'unicité des noms, nous utilisons un algorithme de hachage pour cela.
Donc je propose ceci : 

```diff
-     Le titre de l'image n'entre pas en compte dans le nommage de l'image une fois cette dernière téléchargée. Afin de s'assurer l'unicité des noms, nous utilisons un algorithme de hachage pour cela.
+     Le titre de l'image n'entre pas en compte dans le nommage de l'image une fois cette dernière téléchargée. Afin de réduire le risque de rencontrer des conflits de noms de fichiers, ces derniers sont hashés.
```

Est-ce que c'est correct que c'est le nom de fichier qui est hashé ? Ou son titre ? Si c'est le titre, corriger en conséquence.

2017-01-14 14:44 UTC, GCodeur commented
En effet, je pense que c'est mieux de parler d'une diminution du risque, plutôt que de dire qu'on le supprime complètement (même si en pratique les risques sont très faibles).

Au passage, `hashés` est aussi un peu une francisation, mais ça ne me choque pas plus que ça, d'autant qu'on fait la même chose avec `uploadée`. Pour le choix entre `titre` et `nom`, j'avoue que je ne sais pas. :/

2017-01-28 10:59 UTC, Situphen commented on doc/source/back-end/gallery.rst
> +Afin d'assurer une compatibilité maximale de toutes les images des galeries et leur redimensionnement au besoin, le logiciel `Pillow` est utilisé.
Si tu veux mettre Pillow dans une balise code, en ReST c'est :

    ``Pillow``

2017-01-28 14:50 UTC, GCodeur commented on doc/source/back-end/gallery.rst
> +Afin d'assurer une compatibilité maximale de toutes les images des galeries et leur redimensionnement au besoin, le logiciel `Pillow` est utilisé.
Merci pour l'info ! :)

2017-01-28 15:59 UTC, artragis commented
merging time?

2017-01-28 15:59 UTC, merged