[WIP}début d'une interface d'édition sans les extraits splités
zestedesavoir/zds-site pull request #4150
Opened 2017-01-11 17:55 UTC by artragis

début d'une interface d'édition sans les extraits splités

Le but est ici de répondre à une demande de longue date de certains auteurs : ne plus splitter les extraits quand on rédige.
Seulement l'aspect splitté en aide d'autre (longs contenus...). Du coup je pense qu'on va imaginer une interface avec la possibilité de switcher d'un point de vue à l'autre.

C'est ce que devrait faire cette PR.

L'idée est de passer par une API pour charger puis envoyer les chapitres. 

# Ce qu'il reste à faire (à part "tout")

- [ ] mettre la deuxième interface en ligne
- [ ] endpoint pour envoyer les extraits
- [ ] trouver un moyens plus propre de découvrir qu'un a une section que le  `#= `
- [ ] mettre l'intro et la ccl dans la liste des children
- [ ] tester,
- [ ] js et le slugify

Finalement cela donnera quelques endpoint d'API que @firm1 par exemple pourrait utiliser voire même les gens du front.

2017-01-14 10:21 UTC, Anto59290 reviewed
Quelques petites questions

2017-01-14 10:21 UTC, Anto59290 commented on assets/js/content_edition.js
> +    var editor = $('full-chapter-editor');
Compte tu ajouter un 'use strict' dans le futur?

2017-01-14 10:21 UTC, Anto59290 commented on assets/js/content_edition.js
> +        e.preventDefault();  // no real submit, we'll call API
Est ce que rajouter aussi `event.stopPropagation();` ne serait pas pertinent ? C'est le cas dans pas mal de nos fonction JS sur des boutons.

2017-01-14 10:21 UTC, Anto59290 commented on assets/js/content_edition.js
> +                else {
Je pense que @vhf sera partisan d'un `} else {` en termes de style.

2017-01-14 10:21 UTC, Anto59290 commented on templates/tutorialv2/view/container_nosplit.html
> +{%  load emarkdown %}
Tu as un petit espace en trop ici.

2017-01-14 10:21 UTC, Anto59290 commented on zds/tutorialv2/api/urls.py
> +    url(r'^content/children/(?P<pk>\d+)/(?P<slug>[a-z0-9_-]+)/(?P<parent_container_slug>[a-z0-9_-]+)$',
Pourquoi tes routes portent-elles tous le même `name` ?

2017-01-14 10:36 UTC, artragis commented on assets/js/content_edition.js
> +    var editor = $('full-chapter-editor');
possible même si je ne connais pas les implications.

2017-01-14 10:36 UTC, artragis commented on assets/js/content_edition.js
> +        e.preventDefault();  // no real submit, we'll call API
Ah oui, en effet.

2017-01-14 10:37 UTC, artragis commented on assets/js/content_edition.js
> +                else {
Ok :)

2017-01-14 10:37 UTC, artragis commented on zds/tutorialv2/api/urls.py
> +    url(r'^content/children/(?P<pk>\d+)/(?P<slug>[a-z0-9_-]+)/(?P<parent_container_slug>[a-z0-9_-]+)$',
parce que je suis un poil tête en l'air :)

2017-01-25 12:26 UTC, artragis commented
Bon au moins pour les cas "habituels" l'édition fonctionne. Sauf pour la conclusion qui semble mal éditée.

2017-01-28 16:08 UTC, Situphen reviewed
J'ai regardé seulement la forme. J'ai pas commenté mais dans ton code en Python il y a une alternance entre des apostrophes et des guillemets sans raison apparente ? :/

2017-01-28 16:08 UTC, Situphen commented on assets/js/content-edition.js
> +            if(data.intrduction){
intr**o**duction

2017-01-28 16:08 UTC, Situphen commented on Gulpfile.js
> +        'assets/js/content-edition.js',
Je chipote mais si ça peut rester dans l'ordre alphabétique ce serait cool ;)

2017-01-28 16:08 UTC, Situphen commented on assets/js/content-edition.js
> +                finalText += data.introduction + '\n';
C'est du détail mais dans tout le JS on utilise du double-quote donc si pour rester cohérent est-ce que tu peux faire un rechercher/remplacer dans tout le fichier ? :)

2017-01-28 16:08 UTC, Situphen commented on templates/tutorialv2/view/container_nosplit.html
> +            <button type="button">{% trans 'Prévisualisation' %}</button>
Là aussi double-quote :P (pareil un petit Rechercher/Remplacer...)

2017-01-28 16:52 UTC, artragis commented on assets/js/content-edition.js
> +            if(data.intrduction){
Oh putain et moi qui comprenait pas pourquoi ça buggait :p merci tu m'as enlevé une épine du pied :)

2017-01-28 16:53 UTC, artragis commented on Gulpfile.js
> +        'assets/js/content-edition.js',
ça dépend : est-ce qu'il y a des dépendances à vérifier,

2017-01-28 16:54 UTC, artragis commented on templates/tutorialv2/view/container_nosplit.html
> +            <button type="button">{% trans 'Prévisualisation' %}</button>
hump il me semble que dans le front aussi on met des simple quotes. Mais globalement pour les quotes ça viendra à la fin, quand j'aurai un truc complet. Ce genre de détail c'est pas primordial à cette étape du process.

2017-01-28 16:59 UTC, Anto59290 commented on templates/tutorialv2/view/container_nosplit.html
> +            <button type="button">{% trans 'Prévisualisation' %}</button>
Il me semble que dans le Js la préférence va aux double quotes. Si tu ajoute le use strict au début de ton fichier toutes ces erreurs devraient être levées au build du front.

2017-01-28 17:00 UTC, artragis commented
ok, mais là on est dans le template :p


Le 28/01/2017 à 17:59, Anto59290 a écrit :
>
> *@Anto59290* commented on this pull request.
>
> ------------------------------------------------------------------------
>
> In templates/tutorialv2/view/container_nosplit.html 
> <https://github.com/zestedesavoir/zds-site/pull/4150>:
>
> > +{% load times %}
> +{% load feminize %}
> +
> +{% block title %}
> +    {{ container.title }} - {{ content.title }}
> +{% endblock %}
> +
> +{% block content %}
> +    {% include "tutorialv2/includes/chapter_pager.part.html" with position="top" %}
> +
> +     {% if container.has_extracts %}
> +        <form id="no-split-editor" method="post" action="">
> +            <textarea id="full-chapter-editor" class="md-editor" rows="100">
> +                {% trans 'Chargement en cours, veuillez patienter' %}
> +            </textarea>
> +            <button type="button">{% trans 'Prévisualisation' %}</button>
>
> Il me semble que dans le Js la préférence va aux double quotes. Si tu 
> ajoute le use strict au début de ton fichier toutes ces erreurs 
> devraient être levées au build du front.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4150>, or mute the 
> thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xYqDTYn4gv9iP1kYywEVpsECLg0Bks5rW3PngaJpZM4Lg4M6>.
>

2017-01-28 19:23 UTC, artragis commented on templates/tutorialv2/view/container_nosplit.html
> +            <button type="button">{% trans 'Prévisualisation' %}</button>
ok, mais pour ce commentaire n partiuclier on parle du fichier de template :) Et une grande partie n'est qu'un copier/coller de l'existant, notamment la partie prévisualisation donc...

2017-02-04 09:57 UTC, vhf requested changes
Tu la sens comment pour la prochaine release ?

Idéalement je la lance en début de semaine, mais si t'as besoin de plus de temps pour boucler ça j'attends volontiers que ce soit prêt.

2017-02-04 09:57 UTC, vhf commented on Gulpfile.js
> +const slufify = require('slugify');
Tu peux enlever le `slufify` ici et faire ceci dans `.jshintrc`:

```diff
-  "globals": {},
+  "globals": {"slugify": true},
```

2017-02-04 10:18 UTC, artragis commented
@vhf : merci pour la correction.

Pour ma part, je pense qu'en tant que fonctionnaltié expérimentale, elle est prête MAIS, j'ai tellement eu le nez dans le code que je préfèrerai que quelqu'un passe par là pour vérifier que je n'ai pas cassé le design par inadvertence. 

Il faudra aussi que j'ajoute un flag dans le settings.py pour que tu retire la fonctionnalité au cas où il y aurait trop de bugs.

2017-02-07 18:51 UTC, pierre-24 commented
Rapport de QA:

Tests et bugs:

+ On peut appeler ton interface pour la page principale d'un moyen tuto (ça génère pas de bug, mais ça génère pas de message d'erreur non plus, et puis surtout, ça donne une page avec rien).
+ Beaucoup plus ennuyeux: si on appelle ta page, les extraits sont indiqués comme suis : `#=le titre`. Sauf qu'à la sauvegarde, je pense que tu t'attends à un espace, parce que tout les titres perdent leur premier caractère (ça devient `#=e titre`). Et du coup, ça détruit la conclusion.
+ Rajouter un extrait dont le titre contient une majuscule (`#= Un nouvel extrait`) ne fonctionne pas, parce que le slug alors généré est `Un-nouvel-extrait`, et donc `InvalidSlugError` à cause de la majuscule :)
+ À priori, ajouter, supprimer et déplacer des extraits fonctionne. Sauf qu'avec le premier bug, c'est un peu difficile de dire si l'interface fonctionne correctement (j'attendrais que le *diff* m'indique le déplacement, mais puisque l'extrait change de slug, tout change).

Détails:

+ La position du lien d'édition est pas très évidente (je l'aurai bien vu dans le menu de droite)
+ Le bouton "sauver" est contre-intuitif quand on s'y attend pas. En particulier parce que le "sauvegardé" s'affiche en haut de la page, du coup j'ai appuyé comme un crétin plusieurs fois avant de comprendre.
+ La zone de texte est pas un peu longue quand même là ? :p 
+ Manque un `clearfix` quelque part en bas ;)
+ Y'a pas de bouton pour revenir sur le chapitre, du coup.
+ Faudrait quand même la possibilité de mettre un message de *commit*, et utiliser quand même ceux par défaut (« Édition du chapitre machin »), parce que l'historique ne ressemble pas à grand chose ;)
+ Qui dit édition de chapitre en mode *no-split* dit bien entendu création de chapitre en mode *no-split* (je vois les remarques arriver :p )

2017-02-07 18:54 UTC, pierre-24 commented
PS: vu les problèmes qu'on a eu (et le problème que j'ai pointé), je sais pas à quoi te sers l'extention `node_modules/slugify`, mais je serais plus chaud pour que t'appelle notre slugify à nous, via JS. Au cas ou ;)

2017-02-07 19:12 UTC, artragis commented
Ce que mon dernier commit doit avoir fixé :

- On peut appeler ton interface pour la page principale d'un moyen tuto 
(ça génère pas de bug, mais ça génère pas de message d'erreur non plus, 
et puis surtout, ça donne une page avec rien). ==> ah la joie des typo
- si on appelle ta page, les extraits sont indiqués comme suis : |#=le 
titre  ==> en effet, problème lorsque j'ai refacto mon JS.=
- |parce que le slug alors généré est |Un-nouvel-extrait|, et donc 
|InvalidSlugError| à cause de la majuscule :) ===> my name is boulet. 
C'est géré.
- La zone de texte est pas un peu longue quand même là ? :p ==> j'ai 
raccourcis.
- Le bouton "sauver" est contre-intuitif quand on s'y attend pas. En 
particulier parce que le "sauvegardé" s'affiche en haut de la page, du 
coup j'ai appuyé comme un crétin plusieurs fois avant de comprendre ==> 
j'ai mis en haut et en  bas :p.
- Faudrait quand même la possibilité de mettre un message de /commit => 
tête en l'air. Tout est prévu mais je le mets pas :p. C'est fait. Mais 
gageons que c'est parce que c'est une interface expérimentale.
/

Ce qui, je pense peut être mis sur le compte du caractère expérimental

- j'attendrais que le /diff/ m'indique le déplacement, mais puisque 
l'extrait change de slug, tout change.
/- /Y'a pas de bouton pour revenir sur le chapitre, du coup.
- Qui dit édition de chapitre en mode /no-split/ dit bien entendu 
création de chapitre en mode /no-split/ (je vois les remarques arriver 
:p )  ===> notons que côté back c'est prévu :p :p :p :p Je reste un dev 
back nonméo.
- Manque un |clearfix| quelque part en bas ;) ==> désolé, c'est du 
jargon webdesign, je comprends pas.
- La position du lien d'édition est pas très évidente (je l'aurai bien 
vu dans le menu de droite)


Le 07/02/2017 à 19:51, Pierre Beaujean a écrit :
>
> Rapport de QA:
>
> Tests et bugs:
>
>   * On peut appeler ton interface pour la page principale d'un moyen
>     tuto (ça génère pas de bug, mais ça génère pas de message d'erreur
>     non plus, et puis surtout, ça donne une page avec rien).
>   * Beaucoup plus ennuyeux: si on appelle ta page, les extraits sont
>     indiqués comme suis : |#=le titre|. Sauf qu'à la sauvegarde, je
>     pense que tu t'attends à un espace, parce que tout les titres
>     perdent leur premier caractère (ça devient |#=e titre|). Et du
>     coup, ça détruit la conclusion.
>   * Rajouter un extrait dont le titre contient une majuscule (|#= Un
>     nouvel extrait|) ne fonctionne pas, parce que le slug alors généré
>     est |Un-nouvel-extrait|, et donc |InvalidSlugError| à cause de la
>     majuscule :)
>   * À priori, ajouter, supprimer et déplacer des extraits fonctionne.
>     Sauf qu'avec le premier bug, c'est un peu difficile de dire si
>     l'interface fonctionne correctement (j'attendrais que le /diff/
>     m'indique le déplacement, mais puisque l'extrait change de slug,
>     tout change).
>
> Détails:
>
>   * La position du lien d'édition est pas très évidente (je l'aurai
>     bien vu dans le menu de droite)
>   * Le bouton "sauver" est contre-intuitif quand on s'y attend pas. En
>     particulier parce que le "sauvegardé" s'affiche en haut de la
>     page, du coup j'ai appuyé comme un crétin plusieurs fois avant de
>     comprendre.
>   * La zone de texte est pas un peu longue quand même là ? :p
>   * Manque un |clearfix| quelque part en bas ;)
>   * Y'a pas de bouton pour revenir sur le chapitre, du coup.
>   * Faudrait quand même la possibilité de mettre un message de
>     /commit/, et utiliser quand même ceux par défaut (« Édition du
>     chapitre machin »), parce que l'historique ne ressemble pas à
>     grand chose ;)
>   * Qui dit édition de chapitre en mode /no-split/ dit bien entendu
>     création de chapitre en mode /no-split/ (je vois les remarques
>     arriver :p )
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4150#issuecomment-278102739>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xag8GSV9tnhdPVhOYWYKZjWt7fOUks5raL06gaJpZM4Lg4M6>.
>

2017-02-07 20:14 UTC, artragis commented
avec la mise en page 

# Ce que mon dernier commit doit avoir fixé :

- On peut appeler ton interface pour la page principale d'un moyen tuto (ça génère pas de bug, mais ça génère pas de message d'erreur non plus, et puis surtout, ça donne une page avec rien). ==> ah la joie des typo
- si on appelle ta page, les extraits sont indiqués comme suis : `#=le titre`  ==> en effet, problème lorsque j'ai refacto mon JS.
- parce que le slug alors généré est `Un-nouvel-extrait`, et donc `InvalidSlugError` à cause de la majuscule :) ===> my name is boulet. C'est géré.
- La zone de texte est pas un peu longue quand même là ? :p ==> j'ai raccourcis.
- Le bouton "sauver" est contre-intuitif quand on s'y attend pas. En particulier parce que le "sauvegardé" s'affiche en haut de la page, du coup j'ai appuyé comme un crétin plusieurs fois avant de comprendre ==> j'ai mis en haut et en  bas :p.
- Faudrait quand même la possibilité de mettre un message de commit => tête en l'air. Tout est prévu mais je le mets pas :p. C'est fait. Mais gageons que c'est parce que c'est une interface expérimentale.

# Ce qui, je pense peut être mis sur le compte du caractère expérimental

- j'attendrais que le `diff` m'indique le déplacement, mais puisque 
l'extrait change de slug, tout change.
- Y'a pas de bouton pour revenir sur le chapitre, du coup.
- Qui dit édition de chapitre en mode `no-split` dit bien entendu création de chapitre en mode /no-split/ (je vois les remarques arriver :p )  ===> notons que côté back c'est prévu :p :p :p :p Je reste un dev 
back nonméo.
- Manque un `clearfix` quelque part en bas ;) ==> désolé, c'est du jargon webdesign, je comprends pas.
- La position du lien d'édition est pas très évidente (je l'aurai bien vu dans le menu de droite)

2017-02-08 12:47 UTC, pierre-24 commented
Rapport de QA:

+ Bon, y'a plus du tout de lien pour l'édition *no-split*, du coup. J'ai utilisé l'url, mais c'est un bug ;)
+ Toujours pas de message d'erreur quand on tente d'éditer une partie (contenant des containers), note.
+ Je suis coincé, parce que au bout de la deuxième fois, j'ai "en cours d'édition" (probablement une protection contre les multi-éditions), sauf que le formulaire est bien le seul à éditer le chapitre :o 
+ Au delà de ça, la création d'un nouvel extrait sans toucher aux autres à l'air de donner le bon comportement. Mais c'est le seul truc que j'ai pu tester :p

2017-02-08 12:50 UTC, pierre-24 commented
Ah, on dirait que la protection "en cours d'édition" a un temps limité. M'enfin ça rend l'édition (par exemple juste corriger une faute et re-sauvegarder tout de suite est impossible) et la QA un peu pénible.

2017-02-08 13:15 UTC, artragis commented
nope, c'est juste que ça flag le sha. Du coup faut que tu regardes le 
sha qui est envoyé à chaque fois; Désolé.


Le 08/02/2017 à 13:50, Pierre Beaujean a écrit :
>
> Ah, on dirait que la protection "en cours d'édition" a un temps 
> limité. M'enfin ça rend l'édition (par exemple juste corriger une 
> faute et re-sauvegarder tout de suite est impossible) et la QA un peu 
> pénible.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4150#issuecomment-278320611>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xQgDsf41s4oa0Ne-znmwFpFogM15ks5raboagaJpZM4Lg4M6>.
>

2017-02-08 16:27 UTC, pierre-24 commented
> Du coup faut que tu regardes le sha qui est envoyé à chaque fois

?

2017-02-08 20:43 UTC, pierre-24 commented
Dans la console, j'ai des "400 BAD REQUEST" en série quand j'appuie sur le bouton et qu'il me sors "en cours d'édition". Pas sur que ce soit voulu.

2017-02-08 20:44 UTC, artragis commented
C'est quoi le contenu des requêtes stp.


Le 08/02/2017 à 21:43, Pierre Beaujean a écrit :
>
> Dans la console, j'ai des "400 BAD REQUEST" en série quand j'appuie 
> sur le bouton et qu'il me sors "en cours d'édition". Pas sur que ce 
> soit voulu.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4150#issuecomment-278455477>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xQjxrQJQCCiE1jmqTzj6VHcoCFWNks5raijggaJpZM4Lg4M6>.
>

2017-02-08 20:50 UTC, pierre-24 commented
```
{"original_sha":"08cdf79489bef4b33589ce19898b5fb34d85a96d","containers":[],"extracts":[{"title":"En plein milieu de tout !!!","text":"Voilà.","child_type":"extract","slug":"en-plein-milieu-de-tout-!!!"},{"title":"Présentation de la discipline","text":"....","conclusion":"Nothing","remove_deleted_children":true,"message":"édition"}
```

Et à priori, c'est toujours là même. Réponse:

```
{"original_sha":"Quelqu'un a déjà édité le contenu pendant vous y travailliez."}
```

2017-02-08 20:55 UTC, artragis commented
Peux tu me dire quelle est la valeur du original_sha la **première 
fois** puis ce qu'il se passe ensuite stp?
Le 08/02/2017 à 21:50, Pierre Beaujean a écrit :
> |{"original_sha":"08cdf79489bef4b33589ce19898b5fb34d85a96d","containers":[],"extracts":[{"title":"En 
> plein milieu de tout 
> !!!","text":"Voilà.","child_type":"extract","slug":"en-plein-milieu-de-tout-!!!"},{"title":"Présentation 
> de la 
> discipline","text":"....","conclusion":"Nothing","remove_deleted_children":true,"message":"édition"} 
> |
>
> Et à priori, c'est toujours là même. Réponse:
>
> |{"original_sha":"Quelqu'un a déjà édité le contenu pendant vous y 
> travailliez."} |
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4150#issuecomment-278457542>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xdND4KWD02uXechGkQ7KMdEYmoxGks5raiqxgaJpZM4Lg4M6>.
>

2017-02-08 21:02 UTC, pierre-24 commented
Toujours `08cdf79489bef4b33589ce19898b5fb34d85a96d`. Par contre, la preomier fois, la réponse est `"{\"sha\": \"a8654c3cb49e133f516bd88e6adf96ae64f99d8d\", \"result\": \"OK\"}"`. Donc comme c'est le même sha qui est renvoyé, ça peut pas fonctionner :p

2017-02-08 21:03 UTC, artragis commented
Merci, il y a donc un pb dans ma gestion du sha :)


Le 08/02/2017 à 22:02, Pierre Beaujean a écrit :
>
> Toujours |08cdf79489bef4b33589ce19898b5fb34d85a96d|. Par contre, la 
> preomier fois, la réponse est |"{\"sha\": 
> \"a8654c3cb49e133f516bd88e6adf96ae64f99d8d\", \"result\": \"OK\"}"|. 
> Donc comme c'est le même sha qui est renvoyé, ça peut pas fonctionner :p
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4150#issuecomment-278460552>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xdRCvINAkj2x1VGRGS5Sd1U50LvNks5rai1sgaJpZM4Lg4M6>.
>

2017-02-08 21:29 UTC, pierre-24 requested changes

2017-02-08 21:29 UTC, pierre-24 commented on assets/js/content-edition.js
> +    var titleSeparator = "#= ";  // I use a new separator because we already handler the standard title marker ("# ")
Un espace en moins, ici ?

2017-02-08 21:29 UTC, pierre-24 commented on assets/js/content-edition.js
> +                    "title": textLine.substring(3).trim(),
et un pitit "2", là. Ou mieux, un `titleSeparator.len()` :)

2017-02-08 21:29 UTC, pierre-24 commented on assets/js/content-edition.js
> +            $("#no-split-editor").attr("data-sha", data.sha);
Note que cette partie fonctionne, ce champ est bien mis à la bonne valeur.

2017-02-08 21:29 UTC, pierre-24 commented on templates/tutorialv2/view/content.html
> +    {% if app.nosplit_edition_activated and user in content.authors %}
manque pas un truc entre "app" et "nosplit_machin_chose", genre `tutorialv2` ?

2017-02-08 21:29 UTC, pierre-24 commented on templates/tutorialv2/view/content_nosplit.html
> +    <li>{{ content.title }}</li>
Avec un petit `<a href="">` *please* ;)

2017-02-08 21:29 UTC, pierre-24 commented on templates/tutorialv2/view/content_nosplit.html
> +    {% if is_staff or can_edit %}
C'est utile, toute la partie sur la validation ci-dessous ?

2017-02-08 21:29 UTC, pierre-24 commented on templates/tutorialv2/view/content_nosplit.html
> +    {% if content.is_beta %}
C'est utile, ça ? :-)

2017-02-08 21:29 UTC, pierre-24 commented on templates/tutorialv2/view/content_nosplit.html
> +    {% if is_staff or can_edit %}
Et en fait, de manière générale, il y a plein de trucs qui servent à rien, sur cette page, t'aurais du te baser sur [la template `edit/container.html`](https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorialv2/edit/container.html), alors que tu t'es basé à priori sur `view/content.html` :p

2017-02-08 21:29 UTC, pierre-24 commented on templates/tutorialv2/view/content_nosplit.html
> +    <li>{{ content.title }}</li>
(et les containeurs qui vont avec, bien entendu)

2017-02-09 09:58 UTC, artragis commented on templates/tutorialv2/view/content_nosplit.html
> +    {% if content.is_beta %}
issu de l'ancien template :)

2017-02-09 09:59 UTC, artragis commented on templates/tutorialv2/view/content_nosplit.html
> +    {% if is_staff or can_edit %}
bah au moins on perd pas ses petits :)

2017-02-09 09:59 UTC, artragis commented on templates/tutorialv2/view/content.html
> +    {% if app.nosplit_edition_activated and user in content.authors %}
toutafé c'est ça le loup :)

2017-02-09 09:59 UTC, artragis commented on assets/js/content-edition.js
> +                    "title": textLine.substring(3).trim(),
non, le séparateur c'est bien `#~ `

2017-02-09 10:00 UTC, artragis commented on assets/js/content-edition.js
> +    var titleSeparator = "#= ";  // I use a new separator because we already handler the standard title marker ("# ")
non c'est ça qu'on veut.

2017-02-09 10:00 UTC, artragis commented on assets/js/content-edition.js
> +            $("#no-split-editor").attr("data-sha", data.sha);
Donc si la valeur est mise, je comprends pas pourquoi ça change pas lorsque tu cliques plusieurs fois.

2017-02-09 10:01 UTC, artragis commented on assets/js/content-edition.js
> +            $("#no-split-editor").attr("data-sha", data.sha);
(par contre... j'y pense le csrf token peut potentiellement être cassé)

2017-02-09 10:11 UTC, pierre-24 commented on assets/js/content-edition.js
> +                    "title": textLine.substring(3).trim(),
Au moins le `machin.length()`, alors, des fois que tu changerai d'avais.

2017-02-09 10:12 UTC, pierre-24 commented on assets/js/content-edition.js
> +    var titleSeparator = "#= ";  // I use a new separator because we already handler the standard title marker ("# ")
Anéfé, sinon ça fonctionne pas.

2017-02-09 10:13 UTC, pierre-24 commented on assets/js/content-edition.js
> +            $("#no-split-editor").attr("data-sha", data.sha);
Chaipas trop, faudrait débugger en profondeur (oh, joie, des `alert()` partout <3)

2017-02-09 12:49 UTC, artragis commented
ça devrait aller beaucoup mieux maintenant :)

2017-02-09 12:52 UTC, artragis commented on templates/tutorialv2/view/content_nosplit.html
> +    <li>{{ content.title }}</li>
j'ai été plus radical que ça : c'est de la duplication donc byebye.

2017-02-09 21:00 UTC, pierre-24 commented on templates/tutorialv2/view/content.html
> +    {% if app.nosplit_edition_activated and user in content.authors %}
Ou pas, parce que à priori, j'ai toujours pas le lien ^^

2017-02-09 21:04 UTC, artragis commented on templates/tutorialv2/view/content.html
> +    {% if app.nosplit_edition_activated and user in content.authors %}
je pète un steak. et là je vois pas l'erreur. on verra demain du coup...

2017-02-09 21:19 UTC, pierre-24 commented
Rapport de QA:

+ Les éditions à la suite fonctionnent \o/
+ Ajout, suppression et déplacement d'extrait font ce qu'on attendrait d'eux, donc ça c'est génial aussi <3
+ Comme j'ai dit, j'ai toujours pas le lien, je dois rajourer *nosplit* dans l'url ;)
+ Y'a définitivement un problème de *breadcrumb*: ![screenshot from 2017-02-09 22 04 01](https://cloud.githubusercontent.com/assets/7889675/22803142/0a187374-ef14-11e6-9af2-e0035f93d400.png) (et si j'insiste autant, c'est parce que du coup, on peut pas revenir en arrière pour voir ce qu'on a fait).
+ Je chicane, mais le bouton du dessus est uniquement clicable sur le texte (alors que le bouton du dessous est entièrement clicable)
+ Quand je dis "il manque un clearfix", je veux dire qu'il y a du chevauchement sur le bas de la page et qu'il faut le régler avec un `class="clearfix"` sur un des élément (cet `<hr>`, probablement): 
![screenshot from 2017-02-09 22 11 23](https://cloud.githubusercontent.com/assets/7889675/22803377/f7a889f8-ef14-11e6-95a7-8b0f85569c89.png)

Donc *nice* :)

2017-02-09 21:25 UTC, pierre-24 commented
Ah, par contre, la protection anti-multi-édition ne fonctionne plus. J'ai bien le `{original_sha"Quelqu'un a déjà édité le…dant vous y travailliez."}`, mais le formulaire ne m'indique que "en cours d'édition".

2017-02-09 21:25 UTC, artragis commented
>Je chicane, mais le bouton du dessus est uniquement clicable sur le texte (alors que le bouton du dessous est entièrement clicable)

strange, je regarderai.

>(et si j'insiste autant, c'est parce que du coup, on peut pas revenir en arrière pour voir ce qu'on a fait).

à voir si @vhf considère ça comme acceptable pour un truc expérimental, mais si j'y arrive je le ferai demain.

>Comme j'ai dit, j'ai toujours pas le lien, je dois rajourer nosplit dans l'url ;)

je regarde demain mais je comprends pas.

2017-02-09 21:26 UTC, artragis commented
>Ah, par contre, la protection anti-multi-édition ne fonctionne plus. J'ai bien le {original_sha"Quelqu'un a déjà édité le…dant vous y travailliez."}, mais le formulaire ne m'indique que "en cours d'édition".

faudra que je regarde quoi faire à ce propos...

2017-02-10 10:27 UTC, pierre-24 commented
Deux nouveaux bugs:

+ Si le titre contient une apostrophe, le slug généré est incorrect (il contient toujours l'apostrophe)
+ Pour une raison qui m'échappe, si j'édite un chapitre d'un big-tuto (donc situé dans une partie) ou un chapitre d'un moyen tuto, c'est l'introduction et la conclusion du containeur parent qui est affichée dans l'édidteur à la place de la conclusion du chapitre o_O

2017-02-10 10:45 UTC, artragis commented
>Pour une raison qui m'échappe, si j'édite un chapitre d'un big-tuto (donc situé dans une partie) ou un chapitre d'un moyen tuto, c'est l'introduction et la conclusion du containeur parent qui est affichée dans l'édidteur à la place de la conclusion du chapitre o_O

parce que je suis con (le prochain commit fixe ça)

2017-02-10 13:10 UTC, pierre-24 commented
J'en ai encore ;)

+ Merci pour les corrections, j'ai bien la bonne intro, la bonne conclusion et le lien d'édition apparait <3 (t'es sur que tu veux pas le mettre dans la barre à gauche ?). Oh, et nickel le *breadcrumb*, c'est déjà plus facile à employer.
+ C'est une bonne idée le paginateur, mais du coup, envois directement sur la page *nosplit*, non :)
+ La fonctionnalité anti-mullti-édition jette une erreur JS : `TypeError: e.ajax(...).done(...).error is not a function`.
+ Les titres contenant des ponctuation (typqiement "!", j'ai pas testé pour la virgule) génèrent des slugs incorects. Je sais pas quel `slugify` t'emplois, mais je pense que ça vaudrait la peine d'envoyer un message a son *dev*, parce qu'il est définitivement pourri :o

2017-02-10 13:15 UTC, artragis commented
Merci pour slugify. je regarde ce que je peux faire.

Pour le js, j'ai peut-être été un poil vite à customiser l'erreur. je regarde ce soir.


>C'est une bonne idée le paginateur,

le paginateur?

2017-02-10 13:20 UTC, pierre-24 commented
> >  C'est une bonne idée le paginateur,

> le paginateur?

... Le paginateur : 

![screenshot from 2017-02-10 14 19 11](https://cloud.githubusercontent.com/assets/7889675/22828156/0e8c54ec-ef9c-11e6-98cc-6fd79683ee86.png)

Me disais aussi que c'était une erreur, mais je trouve la fonctionnalité sympa ;)

2017-02-10 13:27 UTC, artragis commented
j'ai juste hérité du système normal en fait :p

2017-02-10 18:43 UTC, artragis commented
ça devrait être bon pour le slug @pierre-24, et l'appel à la méthode d'erreur devrait être réglé.
par contre pour le paginateur, ça te dérange @vhf si je fixe pas ça maintenant en me rangeant derrière l'aspect expérimental de la fonctionnalité?

2017-02-15 18:59 UTC, pierre-24 commented
Rapport de QA:

+ Quand je visite une page d'un tuto, j'ai une erreur XHR sur `http://localhost:8000/api/contenus/children/contenus/*` (par exemple). Je pense que tu fais un appel d'API inutile. Cette erreur n'apparait pas quand je suis dans l'interface nosplit.
+ Ton API n'est, à priori, pas documentée dans `/api/`. Sauf que je sais pas si c'est à cause de toi ou si `Unable to read api 'tags' from path http://localhost:8000/api/api-docs/api/tags (server returned INTERNAL SERVER ERROR)`.
+ La première fois que j'appuie sur le bouton, j'obtient "en cours d'édition". Je dois systématiquement appuyer une deuxième fois. Après, c'est ok.
+ La fonctionnalité anti-multi-édition ne fonctionne toujours pas, `SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data`. Là, ou je pige pas trop, c'est qu'à priori, le json en question, c'est `{"original_sha":"Quelqu'un a déjà édité le contenu pendant vous y travailliez."}`, ce qui m'a l'air tout à fait valide o_O
+ Concernant les slugs, j'ai l'impression que ton [dernier commit](https://github.com/zestedesavoir/zds-site/pull/4150/commits/d38caec0f7b35961aee68981c04c8b099e575b55) n'a eu aucun effet, puisque j'ai toujours des erreurs avec des caractères de ponctuation (en l'occurence un bête "!"). Et j'ai fait `npm install`, sans effet.

2017-02-15 19:03 UTC, pierre-24 commented
Note: les appels à l'API des contenus se font sur toute les pages (et génèrent des erreurs sur toutes les pages, évidement).

2017-02-15 19:10 UTC, pierre-24 commented
Je retire ce que j'ai dit pour le slug, il fallait faire un `make clean-front` avant. Le reste est toujours d'actualité :)

2017-02-15 20:12 UTC, sandhose commented on assets/js/content-edition.js
> +            data = JSON.parse(data);
`data` est pas déjà l'object parsé ? vu que tu as spécifié `type: json` plus haut ?

2017-02-15 20:12 UTC, sandhose commented on assets/js/content-edition.js
> +        $("#save-state").text("En cours d'édition");
faire un diff avec la valeur de la dernière sauvegarde pour vérifier si le texte a effectivement changé ?

2017-02-15 20:14 UTC, artragis commented on assets/js/content-edition.js
> +            data = JSON.parse(data);
Non ça semble pas marcher.

2017-02-15 20:15 UTC, artragis commented on assets/js/content-edition.js
> +            data = JSON.parse(data);
Non ça semble pas marcher.

2017-02-15 20:22 UTC, artragis commented on assets/js/content-edition.js
> +            data = JSON.parse(data);
Ps: notons que le "JSON.parse" fonctionne dans le cas qui concerne ta revue.

2017-03-28 18:28 UTC, GCodeur commented on templates/tutorialv2/view/container.html
> +            <p><a href="{{ container.get_absolute_url_nosplit }}" >{% trans 'Interface sans séparation des extraits (expérimental)' %}</a></p>
Petite suggestion :

```diff
- Interface sans séparation des extraits (expérimental)
+ Interface d'édition sans séparation des extraits (expérimental)
```

Vu l'endroit où le lien est placé, je me suis rendu compte que c'était pas si évident que ça. ;)

2017-03-28 18:51 UTC, GCodeur commented on assets/js/content-edition.js
> +                "message": $("#commit-message").val() || "édition"
C'est vraiment du pinaillage, mais ce serait mieux avec une majuscule pour rester cohérent avec les autres messages de commit par défaut. :)

2017-03-29 16:06 UTC, artragis commented on assets/js/content-edition.js
> +                "message": $("#commit-message").val() || "édition"
Ah j'avais pas vu :p

2017-03-29 16:06 UTC, artragis commented on templates/tutorialv2/view/container.html
> +            <p><a href="{{ container.get_absolute_url_nosplit }}" >{% trans 'Interface sans séparation des extraits (expérimental)' %}</a></p>
Je fais ça.

2017-03-29 16:07 UTC, artragis commented
@GCodeur  pour le bug de l'éditeur sur les contenu et conteneur vide, c'est bon :)

Par contre j'ai toujours le problème disant qu'il faut cliquer deux fois sur les boutons de soumission pour qu'ils marchent.

2017-03-29 20:18 UTC, GCodeur commented
J'ai parlé un peu avec @artragis sur IRC au sujet de cette PR et voici ce qui en est ressorti : le bug du bouton est dû au `p` :

![Capture](https://www.pixenli.com/images/1490/1490817963053269500.png)

De fait, et pour faire d'une pierre deux coups, voici la suggestion proposée : le texte de commit est mal placé (tout en bas), il pourrait donc être mis à côté d'Envoyer à la place du `p` (on pourrait utiliser le texte du bouton pour dire que c'est sauvé). Quant au bouton d'envoi en bas, il devient peu utile, donc on peut envisager de simplement le virer.

Enfin, il faudrait vider le champ du message de commit lors de l'envoi. :)

2017-03-30 06:56 UTC, artragis commented
Mon dernier commit ajoute : 

- le champ texte pour le message de commit pour le contenu
- correction du bug du `<p>`
- le message de commit devient vide après l'envoie.

2017-04-02 20:19 UTC, pierre-24 commented
Et donc, en gros, il reste quoi ? :)

2017-04-03 13:09 UTC, artragis commented
la QA? je pense du moins.

2017-04-03 18:33 UTC, pierre-24 commented
Rapport de QA: ok, mais (et je sais pas si c'est fait exprès ou pas, du coup)

+ On a pas de retour quand on appuye sur le bouton. Du coup, je peux appuyer 3x par erreur :p 
+ Et du coup, je pige pas trop ce que t'as dis à @GCodeur. Moi, j'ai ça:

![screenshot from 2017-04-03 20 33 01](https://cloud.githubusercontent.com/assets/7889675/24624630/c2a76f64-18ac-11e7-961f-9c66eb417418.png)

2017-04-03 18:38 UTC, artragis commented
Ok pour le retour bouton.

Je m'en occupe.


Le 03/04/2017 à 20:33, Pierre Beaujean a écrit :
>
> Rapport de QA: ok, mais (et je sais pas si c'est fait exprès ou pas, 
> du coup)
>
>   * On a pas de retour quand on appuye sur le bouton. Du coup, je peux
>     appuyer 3x par erreur :p
>   * Et du coup, je pige pas trop ce que t'as dis à @GCodeur
>     <https://github.com/GCodeur>. Moi, j'ai ça:
>
> screenshot from 2017-04-03 20 33 01 
> <https://cloud.githubusercontent.com/assets/7889675/24624630/c2a76f64-18ac-11e7-961f-9c66eb417418.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4150#issuecomment-291232553>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xeq5dmPvzNbYry3-jxM8iqlekdDWks5rsTttgaJpZM4Lg4M6>.
>

2017-04-03 20:05 UTC, pierre-24 commented
Rapport de QA: NOK

+ Je n'ai aucun retour quand j'appuye sur le bouton (mais aucune erreur dans la console JS)
+ les nouvelles (ou anciennnes) sections suivantes génèrent à nouveau des slugs invalides : `"#= ca ?!?` et `#= c'est l'histoire de la vie...`. 

Un peu comme si une partie du code n'était simplement plus exécutée :/

2017-04-04 10:31 UTC, artragis commented
T'in l'erreur était trop con : je mettais pas les classes dans les boutons...

n'oublie pas pour le front c'est `npm install && npm run clean && npm run build`.

2017-04-05 19:36 UTC, pierre-24 commented
Elle devient vraiment bien, cette petite PR, j'ai vraiment hâte de la voir en prod (et de l'utiliser). 

Rapport de QA: NOK (mais je l'ai cherché, en même temps)

+ Quand on l'utilise normalement, ça fonctionne très bien, et ce bouton fonctionne enfin <3
+ Quand on change `#= Un titre !` par `#= Un titre ...`, comme le slug ne change pas, le titre n'est pas changé non plus.
+ Y'a moyen de mettre juste `#= `. Du coup, ça génère un slug pas valide et ça corrompt bien le tuto comme il faut. Et si on réappuye sur le bouton "sauvegarder" (parce que je l'avais même pas fait exprès), c'est la teuf' dans le navigateur ;)

![screenshot from 2017-04-05 21 35 25](https://cloud.githubusercontent.com/assets/7889675/24723453/e073460c-1a47-11e7-89ee-0d08147b968b.png)

2017-04-05 19:51 UTC, pierre-24 commented on assets/js/content-edition.js
> +        e.preventDefault();  // no real submit, we"ll call API
Oh le méchant "find and replace" qui a été trop fort :p

2017-04-05 20:21 UTC, GCodeur commented
Sur un article n'ayant aucun extrait, j'ai l'erreur suivante côté serveur : `if not view_model.get_used_children()[0].child_type == searched_children:
IndexError: list index out of range` (`File "/.../zds/tutorialv2/api/views.py", line 59, in put`). Cela cause le même problème que @pierre-24 côté client. Le problème n'est plus présent quand il y a un extrait.

Deuxième problème, quand on met deux `#= conclusion`, on a une erreur 500 (`InvalidOperationError: Le slug « conclusion » est déjà présent dans le conteneur « Mon article »`). Même résultat côté front (qui gère donc visiblement mal les erreurs serveur).

Enfin, deux titres identiques causent l'erreur `self.parent.children[index - 1], self.parent.children[index]
IndexError: list index out of range` (`File "/.../zds/tutorialv2/api/views.py", line 86, in add_child_to_parent`).

Sinon, pour les boutons, tout est OK ! Lors du chargement initial, pourquoi ne pas mettre directement l'état `À jour` ?

2017-10-31 12:39 UTC, motet-a commented on zds/tutorialv2/urls/urls_contents.py
> +    url(r'^nosplit/(?P<pk>\d+)/(?P<slug>[a-zA-Z0-9_-]+)/$',
Faudrait peut-être renommer ces URLs. Tous les chemins sont en français et ce “nosplit” fait un peu tâche je trouve.

2018-09-11 19:01 UTC, closed without merging