[WIP] Ajout d'une interface de merge pour les contenus
zestedesavoir/zds-site pull request #4151
Opened 2017-01-12 19:01 UTC by Anto59290

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | nouvelle fonctionnalité / évolution
| Ticket(s) (_issue(s)_) concerné(s)  | #3251 [#1898](https://github.com/zestedesavoir/zds-site/issues/1898)

Je vous propose cette fonctionnalité pour régler  le problème d'écrasement lors de l'édition concurrente. Pour l'instant **je ne l'ai ajouté que sur l'édition de contenu (content edit)**. Pour l'utiliser il faut donc **éditer l'intro et/ou la conclusion d'un tuto** (et non un containeur ou d'une section) depuis deux onglets différents.

![merge](https://cloud.githubusercontent.com/assets/6287044/21902095/e42a7fb0-d8fa-11e6-919e-f28beae4245e.png)

C'est encore un travail en cours, mais **j'aimerais votre feedback avant d'aller plus loin**. La méthode proposé est normalement assez facile à dupliquer pour les autres champs.  Graphiquement on est assez proche de ce que j'imaginais, il me reste juste à virer la barre violette à droite des champs. Merci d'avance de vos retours.

### QA

* Installer les nouveaux paquets, reconstruire le front
* Editer un tuto dans l'onglet A
* Editer un tuto dans l'onglet B
* Valider l'édition dans l'onglet A
* Valider l'édition dans l'onglet B
* Dans l'onglet B vous devez tomber sur l'interface de merge, qui normalement fonctionne. Le bouton merge n'envoi pas le formulaire, il faut donc toujours cliquer sur le bouton Envoyer en bas de la page.

2017-01-12 19:16 UTC, artragis reviewed
c'est une review rapide. Mais cette fonctionnalité est cool. J'essaierai, demain, de builder ça pour voir ce que ça donne.

2017-01-12 19:16 UTC, artragis commented on zds/tutorialv2/forms.py
> +        if kwargs.get('data') is not None:
il te manque un `, None` pour forcer le get à te donner une valeur par défaut.

2017-01-12 19:16 UTC, artragis commented on zds/tutorialv2/forms.py
> +        if kwargs.get('data') is not None:
pourquoi la condition apparaît-elle deux fois?

2017-01-12 19:16 UTC, artragis commented on assets/js/auto-merge.js
> +					setValue(right.text());
peux-tu mettre un commentaire dans le code pour expliquer pourquoi on a "html" d'un côté et "text" de l'autre stp?

2017-01-12 19:45 UTC, pierre-24 commented
Mmh. Ça à peut être rien à voir, mais je coince à la première étape : 

```
(zdsenv)pbeaujea@chim13-cptrx04 ~/Devels/zds-site $ npm install
/
> optipng-bin@3.1.2 postinstall /home/pbeaujea/Devels/zds-site/node_modules/gulp-imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> gifsicle@3.0.4 postinstall /home/pbeaujea/Devels/zds-site/node_modules/gulp-imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> jpegtran-bin@3.2.0 postinstall /home/pbeaujea/Devels/zds-site/node_modules/gulp-imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully
gulp-concat@2.6.1 node_modules/gulp-concat
├── concat-with-sourcemaps@1.0.4 (source-map@0.5.6)
├── vinyl@2.0.1 (is-stream@1.1.0, replace-ext@1.0.0, clone-buffer@1.0.0, clone-stats@1.0.0, remove-trailing-separator@1.0.1, clone@1.0.2, cloneable-readable@1.0.0)
└── through2@2.0.3 (xtend@4.0.1, readable-stream@2.2.2)

gulp-sourcemaps@1.9.1 node_modules/gulp-sourcemaps
├── detect-newline@2.1.0
├── graceful-fs@4.1.11
├── convert-source-map@1.3.0
├── strip-bom@2.0.0 (is-utf8@0.2.1)
├── source-map@0.5.6
├── vinyl@1.2.0 (clone-stats@0.0.1, replace-ext@0.0.1, clone@1.0.2)
├── acorn@4.0.4
├── through2@2.0.3 (xtend@4.0.1, readable-stream@2.2.2)
├── debug-fabulous@0.0.4 (object-assign@4.1.0, lazy-debug-legacy@0.0.1, debug@2.6.0)
└── css@2.2.1 (inherits@2.0.3, urix@0.1.0, source-map-resolve@0.3.1, source-map@0.1.43)

jquery@3.1.1 node_modules/jquery

gulp-postcss@6.2.0 node_modules/gulp-postcss
├── vinyl-sourcemaps-apply@0.2.1 (source-map@0.5.6)
├── postcss@5.2.10 (js-base64@2.1.9, supports-color@3.1.2, source-map@0.5.6, chalk@1.1.3)
└── gulp-util@3.0.8 (array-differ@1.0.0, lodash._reescape@3.0.0, object-assign@3.0.0, array-uniq@1.0.3, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, beeper@1.1.1, dateformat@2.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, minimist@1.2.0, fancy-log@1.3.0, vinyl@0.5.3, gulplog@1.0.0, chalk@1.1.3, lodash.template@3.6.2, through2@2.0.3, multipipe@0.1.2)

jshint@2.9.4 node_modules/jshint
├── strip-json-comments@1.0.4
├── exit@0.1.2
├── console-browserify@1.1.0 (date-now@0.1.4)
├── minimatch@3.0.3 (brace-expansion@1.1.6)
├── shelljs@0.3.0
├── cli@1.0.1 (glob@7.1.1)
├── htmlparser2@3.8.3 (domelementtype@1.3.0, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.14, domutils@1.5.1)
└── lodash@3.7.0

autoprefixer@6.5.3 node_modules/autoprefixer
├── normalize-range@0.1.2
├── num2fraction@1.2.2
├── postcss-value-parser@3.3.0
├── browserslist@1.4.0
├── postcss@5.2.10 (js-base64@2.1.9, supports-color@3.1.2, source-map@0.5.6, chalk@1.1.3)
└── caniuse-db@1.0.30000607

cssnano@3.8.1 node_modules/cssnano
├── decamelize@1.2.0
├── object-assign@4.1.0
├── postcss-discard-empty@2.1.0
├── postcss-merge-idents@2.1.7
├── postcss-normalize-charset@1.1.1
├── postcss-discard-duplicates@2.0.2
├── postcss-reduce-transforms@1.0.4
├── postcss-minify-gradients@1.0.5
├── postcss-discard-comments@2.0.4
├── defined@1.0.0
├── postcss-reduce-initial@1.0.1
├── postcss-convert-values@2.6.0
├── postcss-value-parser@3.3.0
├── postcss-minify-font-values@1.0.5
├── postcss-discard-overridden@0.1.1
├── postcss-reduce-idents@2.4.0
├── postcss-ordered-values@2.2.3
├── postcss-unique-selectors@2.0.2 (uniqs@2.0.0, alphanum-sort@1.0.2)
├── postcss-discard-unused@2.2.3 (uniqs@2.0.0)
├── postcss-minify-params@1.2.2 (uniqs@2.0.0, alphanum-sort@1.0.2)
├── postcss-zindex@2.2.0 (uniqs@2.0.0)
├── postcss-merge-longhand@2.0.1
├── has@1.0.1 (function-bind@1.1.0)
├── postcss-filter-plugins@2.0.2 (uniqid@4.1.1)
├── postcss-normalize-url@3.0.8 (is-absolute-url@2.1.0, normalize-url@1.9.0)
├── postcss-calc@5.3.1 (postcss-message-helpers@2.0.0, reduce-css-calc@1.3.0)
├── postcss-minify-selectors@2.1.1 (alphanum-sort@1.0.2, postcss-selector-parser@2.2.2)
├── postcss@5.2.10 (js-base64@2.1.9, supports-color@3.1.2, source-map@0.5.6, chalk@1.1.3)
├── postcss-colormin@2.2.1 (colormin@1.1.2)
├── postcss-svgo@2.1.6 (is-svg@2.1.0, svgo@0.7.1)
└── postcss-merge-rules@2.1.1 (vendors@1.0.1, postcss-selector-parser@2.2.2, browserslist@1.5.2, caniuse-api@1.5.2)

gulp-jshint@2.0.4 node_modules/gulp-jshint
├── minimatch@3.0.3 (brace-expansion@1.1.6)
├── through2@2.0.3 (xtend@4.0.1, readable-stream@2.2.2)
├── rcloader@0.2.2 (lodash.assign@4.2.0, lodash.isobject@3.0.2, lodash.merge@4.6.0, rcfinder@0.1.9)
├── gulp-util@3.0.8 (array-differ@1.0.0, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, object-assign@3.0.0, array-uniq@1.0.3, beeper@1.1.1, dateformat@2.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, minimist@1.2.0, fancy-log@1.3.0, vinyl@0.5.3, gulplog@1.0.0, chalk@1.1.3, lodash.template@3.6.2, multipipe@0.1.2)
└── lodash@4.17.4

gulp-imagemin@3.1.1 node_modules/gulp-imagemin
├── pretty-bytes@4.0.2
├── plur@2.1.2 (irregular-plurals@1.2.0)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, has-ansi@2.0.0, strip-ansi@3.0.1)
├── through2-concurrent@1.1.1 (through2@2.0.3)
├── imagemin@5.2.2 (pify@2.3.0, file-type@3.9.0, promise.pipe@3.0.0, replace-ext@0.0.1, mkdirp@0.5.1, globby@5.0.0)
├── gulp-util@3.0.8 (array-differ@1.0.0, lodash._reinterpolate@3.0.0, object-assign@3.0.0, array-uniq@1.0.3, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, beeper@1.1.1, dateformat@2.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.3.0, minimist@1.2.0, vinyl@0.5.3, lodash.template@3.6.2, gulplog@1.0.0, through2@2.0.3, multipipe@0.1.2)
├── imagemin-svgo@5.2.0 (is-svg@2.1.0, svgo@0.7.1)
├── imagemin-optipng@5.2.1 (is-png@1.0.0, exec-buffer@3.1.0, optipng-bin@3.1.2)
├── imagemin-gifsicle@5.1.0 (is-gif@1.0.0, exec-buffer@3.1.0, gifsicle@3.0.4)
└── imagemin-jpegtran@5.0.2 (is-jpg@1.0.0, exec-buffer@3.1.0, jpegtran-bin@3.2.0)
(zdsenv)pbeaujea@chim13-cptrx04 ~/Devels/zds-site $ make build-front 
npm run build

> zds-site@0.2.0 build /home/pbeaujea/Devels/zds-site
> gulp build

[20:42:05] Using gulpfile ~/Devels/zds-site/Gulpfile.js
[20:42:05] Starting 'css:sprite'...
[20:42:06] Starting 'css:vendors'...
[20:42:06] Starting 'js'...
[20:42:06] 'js' errored after 2.34 ms
[20:42:06] Error: Cannot find module 'codemirror'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at Gulp.<anonymous> (/home/pbeaujea/Devels/zds-site/Gulpfile.js:48:17)
    at module.exports (/home/pbeaujea/Devels/zds-site/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/pbeaujea/Devels/zds-site/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/pbeaujea/Devels/zds-site/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/pbeaujea/Devels/zds-site/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /home/pbeaujea/Devels/zds-site/node_modules/gulp/bin/gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)
[20:42:06] Finished 'css:vendors' after 36 ms
[20:42:07] Finished 'css:sprite' after 1.01 s

npm ERR! Linux 3.13.0-37-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.7.2
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! zds-site@0.2.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zds-site@0.2.0 build script 'gulp build'.
npm ERR! This is most likely a problem with the zds-site package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zds-site
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls zds-site
npm ERR! There is likely additional logging output [...]

2017-01-12 19:49 UTC, Anto59290 commented
Si codemirror est un nouveau package, c'est une dépendance de mergely. J'ai peut être oublié quelques chose de mon côté. Si tu veut tester en contournant le problème tu peut faire un nom install mergely ce qui installera tout, le temps que je trouve une solution.

2017-01-12 19:49 UTC, artragis commented
il faut le mettre dans le fichier package.json non?


Le 12/01/2017 à 20:49, Anto59290 a écrit :
>
> Si codemirror est un nouveau package, c'est une dépendance de mergely. 
> J'ai peut être oublié quelques chose de mon côté. Si tu veut tester en 
> contournant le problème tu peut faire un nom install mergely ce qui 
> installera tout, le temps que je trouve une solution.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4151#issuecomment-272263651>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xY76Vn2-u1DiE2RpjQQuNQQ0h4VDks5rRoO0gaJpZM4LiHK3>.
>

2017-01-12 19:55 UTC, Anto59290 commented
Exact.

2017-01-12 20:42 UTC, Anto59290 commented on assets/js/auto-merge.js
> +					setValue(right.text());
Bien vu, j'ai uniformisé car il n'y avait pas de raison en particulier.

2017-01-12 20:47 UTC, artragis requested changes

2017-01-12 20:47 UTC, artragis commented on assets/js/auto-merge.js
> +		function mergelySetUp(div, left, right)
peux-tu mettre un `$` devant chaque variable (car c'est du jQuery).
De même, peux-tu changer le nom pour que ça soit plus proche du sens "fonctionnel" c'est à dire `$local` et `$remote` au lieu de left et right. du moins je pense (@vhf tu en dis quoi?)

2017-01-12 20:47 UTC, artragis commented on assets/js/auto-merge.js
> +	        var classList = button.attr("class").split(/\s+/);
hum pas sûr que ça soit la méthode la plus facile d'autant qu'il existe déjà l'attribut classList (`this.classList`).
Ensuite plutôt qu'un simple for, je suis d'avis d'utiliser un `this.classList.forEach(function(){...}`/

2017-01-12 20:53 UTC, Anto59290 commented on assets/js/auto-merge.js
> +		function mergelySetUp(div, left, right)
Pourquoi pas changer le nom. Après local et remote c'est une convention pour nous (car le code actuel écrase), par sur que ça soit clair nom plus... Je vais détailler les commentaires avant pour expliquer les paramètres.

2017-01-12 20:58 UTC, Anto59290 commented on assets/js/auto-merge.js
> +	        var classList = button.attr("class").split(/\s+/);
De mémoire .classList à un support limité (voir inexistant) avec < IE9, d'où le choix de .attr.

2017-01-12 20:59 UTC, artragis commented on assets/js/auto-merge.js
> +	        var classList = button.attr("class").split(/\s+/);
on ne supporte que IE 11 et supérieur, chrome last, firefox last, safari last.

2017-01-12 21:08 UTC, Anto59290 commented on assets/js/auto-merge.js
> +	        var classList = button.attr("class").split(/\s+/);
Ca marche alors ;)

2017-01-14 08:50 UTC, vhf commented
@pierre-24 Dans ton log je lis `npm ERR! npm  v2.15.11`. Me semble qu'on ne supporte qu'à partir de npm 3.

Tu peux probablement faire `npm install -g npm` ?

2017-01-14 08:55 UTC, vhf commented on assets/js/auto-merge.js
> +		function mergelySetUp(div, left, right)
Effectivement les variables jQuery doivent être préfixées par `$`. Je te fais vite un exemple : 

```js
var $lala = $('.foo').find('.bar').get(1);
var baz = $lala.val();
```

Je sais pas comment nommer idéalement `left` et `right`. Si c'est côté JS qu'on charge les contenus à afficher à gauche et à droite, c'est côté JS qu'on sait quelle version risque d'écraser quelle version, et c'est sur ça qu'on devrait se baser pour nommer explicitement ces paramètres. Genre au lieu de `left` on pourrait avoir `currentVersion` et au lieu de `right` on aurait `submittedVersion`. Un truc dans ce genre. Ça a du sens pour vous ?

2017-01-15 18:08 UTC, qwertygc commented
Un détail, dans le bouton, remplacer l'affreux barbarisme « merger » par « fusionner », plus compréhensible pour des non-dev.

2017-01-15 18:21 UTC, Anto59290 commented
C'est noté ;)

2017-01-20 21:17 UTC, artragis commented
Il faudra aussi rebase pour que les conflits soient résolus. Bon courage.

2017-01-21 06:51 UTC, Anto59290 commented
C'est des conflits avec ma propre PR sur le preview je pense donc ça devrait aller. Je vais proposer une version définitive avec l'interface sur tous les champs concernés ce week-end.

2017-02-01 18:21 UTC, DevHugo commented
Tu veux un coup de main pour finir ? tu as un souci ? tu veux des retours ?

2017-02-02 07:12 UTC, Anto59290 commented
Alors normalement tout devrait etre ok, il ne me reste plus que les tests a regler. Je regarde pour faire avancer ca ;)

2017-02-15 18:26 UTC, pierre-24 commented
Besoin d'aide ?

2017-02-15 18:40 UTC, Anto59290 commented
Besoin de temps surtout ^^. Je vais essayer de regarder ce week-end. N'hésite pas à remonter si je donne pas de nouvelles.

2017-04-19 17:57 UTC, cgabard commented
Je remonte alors car ce serait chouette !

2017-05-09 19:59 UTC, Anto59290 commented
Vu l'engouement autour de cette fonctionnalité j'ai repris un peu le dev dessus ;)

2017-05-09 20:07 UTC, artragis commented
Génial ! n'hésite pas à demander de l'aide.

2017-05-10 19:12 UTC, artragis commented
Y'a des pb dans ton rebase.

2017-05-10 19:56 UTC, Anto59290 commented
Ouai malheureusement... je vais essayer de nettoyer ça.

2017-05-10 20:11 UTC, Anto59290 commented
Ok je pense avoir remit la PR a plat en corrigeant mon rebase. Je pense qu'il me reste juste un test à fixer et ça sera bon ;)

2017-05-31 10:59 UTC, artragis commented
as-tu besoin d'aide?

2017-06-03 10:29 UTC, Anto59290 commented
Je pense que cette fois ci est la bonne. Les tests sont au verts, sauf npm qui fait des siennes.

2017-06-10 17:28 UTC, gustavi requested changes

2017-06-10 17:28 UTC, gustavi commented on zds/tutorialv2/forms.py
> +            self.helper.layout.append(Layout(HTML('<div id = "your_conclusion" class = "hidden" >' + old_conclusion +
préféer utiliser '...{0}'.format(...) ici

2017-06-10 17:28 UTC, gustavi commented on zds/tutorialv2/forms.py
> +            self.helper.layout.append(Layout(HTML('<div id = "your_conclusion" class = "hidden" >' + old_conclusion +
idem ailleurs

2017-06-10 17:28 UTC, gustavi commented on zds/tutorialv2/forms.py
> +                                          css_class='btn btn-grey preview-btn'),),
s/preview-btn/btn-preview ?

2017-06-10 17:28 UTC, gustavi commented on zds/tutorialv2/forms.py
> +        if kwargs.get('data', None) is not None:
Ce code ressemble beaucoup à ce qu'il y a plus haut. Il faudra trouver une solution (mixin ?) pour factoriser ça.

2017-08-01 05:44 UTC, artragis commented
Besoin d'aide?

2017-08-22 19:44 UTC, Anto59290 commented
J'avance un peu sur le refactoring. Je pense que j'ai une idée un peu plus claire sur comment organiser ça pour que ça sot propre. 

En revanche je bloque sur le front, je me tape une erreur JS assez incompréhensible... Est-ce que c'est normal que le fichier .lock est été modifié avec deux version de JQuery ? Si quelqu'un est motivé pour regarder ( @motet-a  ?) :)

2017-08-23 20:15 UTC, motet-a commented
@Anto59290 Coucou, quelle est l’erreur que tu rencontres ?

Ne t’occuppes pas trop du `yarn.lock`, c’est pas très important (normalement, même si tu le supprime et que tu continues d’utiliser `npm` tu ne devrais pas avoir trop de problèmes).

2017-08-23 20:24 UTC, motet-a requested changes
Je suis assez maniaque sur le style. J’espère que tu ne prendra pas ça trop mal :p

2017-08-23 20:24 UTC, motet-a commented on assets/js/auto-merge.js
> +(function($, undefined) {
Il faudrait réindenter ce fichier comme le reste, avec des espaces et non des tabulations.

2017-08-23 20:24 UTC, motet-a commented on assets/js/auto-merge.js
> +		{
L’accolade doit être sur la même ligne que `function`.

2017-08-23 20:24 UTC, motet-a commented on assets/scss/components/_auto-merge.scss
> +    display : none;
Pas d’espace avant le `:`

2017-08-23 20:24 UTC, motet-a commented on assets/scss/components/_codemirror.scss
> +/* BASICS */
Ça serait cool de réindenter tout ça avec 4 espaces :upside_down_face:

2017-08-23 20:24 UTC, motet-a commented on assets/scss/components/_codemirror.scss
> +  -moz-animation: blink 1.06s steps(1) infinite;
Il faudrait enlever tous les préfixes `-moz-` et `-webkit-`, ils sont ajoutés automatiquement.

2017-08-23 20:24 UTC, motet-a commented on assets/scss/components/_codemirror.scss
> +@keyframes blink {
Les noms des `@keyframes` sont globaux. `blink` risque de causer des collisions. Je pense qu’il faudrait le renommer en quelque chose comme `codemirror-blink`.

2017-08-26 12:53 UTC, Anto59290 commented
@motet-a : Voici l'erreur : 

```
mergely.js:1672 Uncaught TypeError: (intermediate value)(...) is not a function
    at mergely.js:1672
```

Ce qui correspond aux lignes 

```
// make the mergely widget
    jQuery.pluginMaker(Mgly.mergely);
```

J'ai l'impression que ça viendrait d'une mauvaise version de JQuery ?

2017-08-26 13:23 UTC, motet-a commented
Ah possible, on est encore sur jQuery 2.

2017-08-26 13:24 UTC, motet-a commented
@Anto59290 Oh en fait non, justement, on vient de passer à jQuery 3 récemment :upside_down_face:

2017-08-26 14:46 UTC, Anto59290 commented
> En fait on vient de passer à jQuery 3 récemment :upside_down_face:

Est ce que ça change quelque chose dans cette PR ?

2017-08-26 14:52 UTC, motet-a commented
Ben, si par exemple Mergely n’est pas compatible avec jQuery 3, ça expliquerait ton erreur.

2017-08-26 15:01 UTC, motet-a commented on zds/tutorialv2/forms.py
> +            self.helper.layout.append(Layout(HTML('<div id = "compare" class="compare-conclusion"></div>')))
Pas d’espaces autour du `=` de `id = "compare"`

2017-08-26 15:01 UTC, motet-a commented on zds/tutorialv2/forms.py
> +            self.helper.layout.append(Layout(HTML('<div id = "your_introduction" class = "hidden" >' +
Pas d’espaces autour des ' = '

2017-08-26 16:47 UTC, Anto59290 commented
> Ben, si par exemple Mergely n’est pas compatible avec jQuery 3, ça expliquerait ton erreur.

Je crois que c'est bien ce qui se passe... Je vais voir pour dégager mergely et utiliser uniquement codemirror, l'interface est moins complète, mais bon.

2017-08-26 17:05 UTC, motet-a commented
C’est un peu embêtant tout ça. On pourrait peut-être revenir à jQuery 2, mais si il y a quelque chose d’autre qui demande jQuery 3…

Tu as des alternatives en tête ?

2017-08-26 18:19 UTC, Anto59290 commented
On peut utiliser Codemirror sans la surcouche de mergely, mais c'est moins "fun" en terme d'interface : https://codemirror.net/demo/merge.html

2017-08-26 18:41 UTC, motet-a commented
Je ne connais pas trop le besoin mais CodeMirror m’a l’air d’être déjà très bien. Le fait que CodeMirror n’ai aucune dépendance, qu’il soit utilisable avec npm et qu’il ai l’air d’être maintenu à jour sont des gros avantages par rapport à Mergely.

2017-08-26 18:44 UTC, motet-a commented
(Bon en fait Mergely est sur npm, mais c’est un fork et non l’original. Bref. Le bazar.)

2017-09-19 11:22 UTC, artragis commented
On en est où ici? c'est vraiment un truc fun à avoir ça.

2017-09-22 20:01 UTC, artragis commented
need rebase + debug des tests, non?

2017-09-22 20:23 UTC, motet-a commented
Il faudrait quand-même arranger un coup le CSS et le JS.

2017-09-23 07:38 UTC, Anto59290 commented
J'en suis la pour l'instant. Ça fonctionne, mais j'ai été obligé de [faire un truc très moche](https://github.com/zestedesavoir/zds-site/pull/4151/files#diff-8944b57466f08564caa53a1988261ae0R672). Si quelqu'un a une alternative je suis preneur. Quand je le rajoute aux dépendances JS du projet ça ne fonctionne pas car d'après ce que j'ai compris c'est un module node qui n'est pas fait pour être utilisé dans un navigateur. Du coup ça voudrait dire utiliser quelque chose comme browserify ? Ca me parrait bien compliqué tout ça pour une lib...

2017-09-23 07:54 UTC, artragis commented
faudrait peut être ne le charger que sur la page d'édition des tutos plutôt que sur tout le site, non?

2017-09-23 08:04 UTC, Anto59290 commented
Bonne idée ;)
Je vais essayer de nettoyer tout ça se week-end (si je trouve un peu de temps :p )

2017-10-16 17:40 UTC, artragis commented
ping @Anto59290

2017-10-28 20:23 UTC, artragis commented
@Anto59290 il faut rebase pour régler quelques conflits :)

2017-11-02 08:11 UTC, motet-a commented on zds/settings.py
> -
Ça serait bien de laisser ce fichier tel qu'il était 🙃

2017-11-02 08:57 UTC, Anto59290 commented
Alors normalement il me reste plus qu'un peu de refactoring (identifié avec des TODO dans le code) et le lint du JS ;)

2017-11-02 08:59 UTC, motet-a commented
(Merci pour avoir supprimé la ligne vide. C’est pas un gros problème en soi mais ce genre de truc ne facilite pas la lecture du diff et en l’occurence, ça aurait plein de conflits avec mon autre PR des settings pour trois fois rien)

2017-11-05 14:39 UTC, motet-a commented on zds/tutorialv2/forms.py
> +                    _(u'Valider'),
Il reste un petit `u` en trop ici.

2017-11-05 15:03 UTC, Anto59290 commented
Je sais pas pourquoi le linting en Js ne passe pas, c'est assez étrange:

> 'CodeMirror' is not defined.

2017-11-05 15:19 UTC, motet-a commented
@Anto59290 C’est normal que jshint râle là-dessus. Utilises `windows.CodeMirror` à la place de `CodeMirror` et ça marchera.

2017-11-05 16:13 UTC, artragis approved these changes

2018-09-11 19:22 UTC, Situphen commented
Je ferme mais n'hésite pas à réouvrir quand tu auras du temps pour la finir ! :)

2018-09-11 19:22 UTC, closed without merging

2018-12-26 20:56 UTC, artragis commented
argl, a-t-on une idée de si ça reviendra un jour?

2018-12-27 08:12 UTC, Anto59290 commented
:wave: Au moment ou tu avais approve il restait juste de la QA et un peu de bugfix a faire il me semble. Mais dans l'ensemble tout était OK si mes souvenirs sont bons.

2018-12-27 10:01 UTC, artragis commented
ok, donc tu peux rouvrir et rebase stp?

2019-07-02 20:49 UTC, Vanadiae commented
On en est où ici @Anto59290 ?