Ne supprime pas les notes de karma et les sanctions par un modérateur qui se désinscrit
zestedesavoir/zds-site pull request #4167
Opened 2017-01-30 18:12 UTC by GCodeur

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | évolution

Actuellement, si un modérateur se désinscrit, les notes de karma et les sanctions (je parle de leur archive, c'est-à-dire de l'objet `Ban`, un membre sanctionné le reste) liées à son compte sont supprimées, ce qui est le comportement normal de l'effacement d'un objet dans Django.

Cependant, il serait préférable de garder ces informations en guise d'archive. Cette pull request modifie donc ce comportement pour le même que celui des messages : l'objet n'est pas supprimé mais transmis à l'utilisateur anonyme.

### QA

* Depuis l'admin Django, créer un utilisateur avec les droits staff et le profil associé ;
* Se connecter depuis ce compte, laisser une note de karma sur un membre et le sanctionner ;
* Se désinscrire ;
* Se connecter depuis un compte super-utilisateur (et admin) et vérifier que la note de karma est toujours présente (et qu'elle est liée à l'utilisateur anonyme défini dans `settings.py`) ;
* Dans l'admin Django, vérifier que l'objet `Ban` est toujours présent ;
* Vérifier que le test `zds.member.tests.tests_views.MemberTests.test_unregister` passe toujours.

2017-01-31 16:04 UTC, DevHugo approved these changes

2017-01-31 16:08 UTC, DevHugo commented
Je pense vraiment qu'il faut qu'on revoit le code de cette méthode et traiter par batch, les suppression car la on génère une requête pour chaque message, topic, like, dislike et commentaire à supprimer. 

C'est pas urgent car c'est pas une méthode utilisé tous les jours mais faut voir sur le long terme ! On créé une issue pour ça ?

2017-01-31 16:39 UTC, GCodeur commented
Je suis d'accord avec ça, je viens de faire une petite recherche : [ceci](http://stackoverflow.com/a/2743825)  pourrait convenir, non ?

Du coup, je suis partant pour ouvrir une issue, on merge quand même cette pull request en attendant ?

2017-01-31 17:59 UTC, DevHugo commented
C'est pas moi qui prend la décision mais je pense qu'on peut merge la PR pour pas retarder et puis on changera dans le futur cette méthode. 

@vhf , tu en pense quoi ? on fait un ticket ou on corrige de suite ? Sachant que la PR ne change pas le problème qui était déjà là avant.

2017-01-31 20:21 UTC, vhf commented
Oui faites une issue séparée. C'est très facile à régler mais y'en a trop pour mettre ça là-dedans.

```diff
-     for obj in Foo.objects.filter(bar=baz, qux=True):
-          obj.truc = "muche"
-          obj.chose = 42
-          obj.save()
+      Foo.objects.filter(bar=baz, qux=True).update(truc="much", chose=42)
```

Faudra en profiter pour sérieusement corriger les commentaires de la fonction en question, ils sont bourrés de fautes.

2017-01-31 20:26 UTC, vhf commented
J'y pensais jusqu'à ce que j'oublie : c'est non seulement extrêmement mieux niveau performance, c'est également beaucoup plus safe d'utiliser `update` que `save` dans la plupart des cas.

`save` update tous les champs, `update` seulement ceux qui sont donnés. Du coup même si on la joue safe avec des transactions, on peut se retrouver avec un `.save()` qui écrase un champ modifié dans un autre thread par un autre `.save()` ou par un `.update()`, alors que deux `.update()` sur des champs différents ne se seraient pas marchés dessus.

2017-01-31 20:48 UTC, GCodeur commented
OK, je vais créer l'issue, je m'occuperai de la PR demain (je devrais avoir le temps). :)

Du coup, on merge celle-ci ? Tu as fait la QA @DevHugo ?

2017-01-31 20:54 UTC, DevHugo commented
Oui de toute les manière, il faut une QA.

2017-02-01 17:17 UTC, DevHugo requested changes

2017-02-01 17:17 UTC, DevHugo commented on zds/member/views.py
>      # in case current has been moderator in his old day
Il manque les alertes. Sinon, elle vont être supprimées.

2017-02-01 17:18 UTC, GCodeur commented on zds/member/views.py
>      # in case current has been moderator in his old day
En effet, autant en profiter pour les ajouter :)

2017-02-01 17:44 UTC, DevHugo approved these changes

2017-02-01 18:02 UTC, DevHugo commented on zds/member/views.py
> +    for alert in Alert.objects.filter(moderator=current):
Y'a deux fois les mêmes lignes là.

2017-02-01 18:03 UTC, DevHugo commented
QA: Ok

2017-02-01 19:29 UTC, GCodeur commented
Merci @DevHugo !

@zestedesavoir/les-jeunes-pousses : est-il possible de merger cette PR ? Ça me permettrait de faire une PR résolvant #4170 sans créer de conflit. :)

2017-02-01 19:35 UTC, merged