Permet de marquer un contenu comme obsolète
zestedesavoir/zds-site pull request #4187
Opened 2017-02-08 16:34 UTC by GCodeur

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | nouvelle fonctionnalité
| Ticket(s) (_issue(s)_) concerné(s)  | #4185 

Ça m'a pris pas mal de temps (surtout pour comprendre le code de `tutorialv2,` mais je pense que le résultat y est ! Cette pull request permet de marquer un contenu comme obsolète, ce qui aura pour effet d'afficher un bandeau le signalant sur toutes ces pages. Cette action, faisable uniquement par le staff, est réversible.

### QA

* Créer un contenu et le publier, vérifier qu'il n'est pas marqué obsolète ;
* Marquer le contenu obsolète, le bandeau doit s'afficher sur toutes ses pages ;
* Le marquer comme non obsolète, le bandeau doit disparaître ;
* Le remarquer comme obsolète, puis le valider à nouveau sans cocher la case `Version majeure`, il doit rester obsolète ;
* Le valider encore une fois, mais cette fois en cochant la case : le bandeau doit disparaître ;
* Enfin, vérifier que le test `zds.tutorialv2.tests.tests_views.PublishedContentTests.test_obsolete` passe.

2017-02-08 16:58 UTC, Fumble commented on templates/tutorialv2/view/content_online.html
> +                                {% endif %}
J'aurais plutôt dit "Marquer comme obsolète". Idem pour la forme négative.

2017-02-08 17:07 UTC, GCodeur commented on templates/tutorialv2/view/content_online.html
> +                                {% endif %}
D'accord avec toi, c'était surtout par crainte de manque de place, mais je pense que ça peut passer.

2017-02-08 20:08 UTC, pierre-24 requested changes
QA ok à priori, mais je t'embête un peu avant de *merger* :)

2017-02-08 20:08 UTC, pierre-24 commented on zds/tutorialv2/tests/tests_views.py
> +        self.assertNotContains(result, u'Ce contenu est obsolète.')
Faut de la traduction, ici : `_()`

2017-02-08 20:08 UTC, pierre-24 commented on zds/tutorialv2/tests/tests_views.py
> +        self.assertNotContains(result, u'Ce contenu est obsolète.')
Il serait probablemnet intéréssant de faire le même test sur un chapitre de moyen/big tuto.

2017-02-08 20:08 UTC, pierre-24 commented on zds/tutorialv2/views/views_validations.py
> +def mark_obsolete(request, pk):
Je préférerai une vue en CBV, si ça ne te dérange pas. Je dis ça parce qu'il y a déjà des *mixins* pour les vues qui s'occupent de récupérer le contenu et tester que tout est bien (droits d'accès, toussa) ;)

2017-02-09 14:27 UTC, GCodeur commented
Normalement, tout est bon @pierre-24 (attendons Travis quand même) :)

2017-02-09 15:49 UTC, pierre-24 commented on zds/tutorialv2/views/views_validations.py
> +class MarkObsolete(LoginRequiredMixin, PermissionRequiredMixin, FormView):
Donc c'était bien l'ordre ? :o

2017-02-09 16:54 UTC, GCodeur commented on zds/tutorialv2/views/views_validations.py
> +class MarkObsolete(LoginRequiredMixin, PermissionRequiredMixin, FormView):
Eh oui :p

2017-02-09 20:49 UTC, pierre-24 commented
Rapport de QA: OK pour moi :)

2017-02-09 20:49 UTC, merged

2017-02-10 16:56 UTC, vhf commented
Cool, gg @GCodeur !

Petite remarque notamment pour la QA (cc @pierre-24 ) : il y a une migration inutile dans cette PR. C'est pas grave, mais mieux vaut éviter à l'avenir. :)

2017-02-10 16:57 UTC, pierre-24 commented
Bien vu :)

2017-02-10 17:18 UTC, GCodeur commented
Oui en effet, je m'étais un peu planté et j'ai dû faire une deuxième migration pour corriger mon erreur, désolé. :/

Pas sûr que ce soit bien utile mais si vous voulez une mini-PR qui fait tout en une migration, je peux.

2017-02-10 17:29 UTC, vhf commented
Non non pas grave @GCodeur :)