Empêche les notifications persistantes pour les pings
zestedesavoir/zds-site pull request #4197
Opened 2017-02-11 15:11 UTC by artragis

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | correction de bug 
| Ticket(s) (_issue(s)_) concerné(s)  | #4195

### QA

    Déplacement vers un forum auquel le pingé n'a pas accès
        Pinger X dans un forum 'public'
        Déplacer le sujet dans un forum non-public
    Créer un ping dans un forum auquel le pingé n'a pas accès
        Pinger X dans un forum non-public

2017-02-11 15:36 UTC, DevHugo commented
Je fait la QA ce soir.

2017-02-11 15:39 UTC, artragis commented
Merci, comme je code sur mon vieux windows, je ne suis sûr de rien car 
mon env est cassé de base. Que les tests unitaires soient passés est 
déjà une bonne chose;


Le 11/02/2017 à 16:36, Hugo Courtecuisse a écrit :
>
> Je fait la QA ce soir.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4197#issuecomment-279153022>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xZ8Mbxry2SQj7FryRyGKc3Ud1VdEks5rbdWPgaJpZM4L-My8>.
>

2017-02-11 15:40 UTC, DevHugo commented
Je vais faire attention, y'a pas de souci.

2017-02-11 16:14 UTC, artragis commented
Comme ça me faisais chier de fixer #4193 dans une PR qui allait forcément être en conflit avec celle-ci, j'ai mis le fix ici :)

2017-02-11 16:38 UTC, DevHugo commented
No rage bro.

2017-02-11 16:39 UTC, vhf commented on zds/notification/receivers.py
> +        logger.info('subsription %s was active', subscription)
`subscription`

2017-02-11 16:40 UTC, vhf commented on zds/notification/receivers.py
> +        if Topic.objects.filter(pk=comment.topic.forum.pk, group__in=list(user.groups.all)).first() is None:
[`.exists()`](https://docs.djangoproject.com/en/1.10/ref/models/querysets/#django.db.models.query.QuerySet.exists)?

2017-02-11 16:57 UTC, vhf commented on zds/notification/receivers.py
> +        if Topic.objects.filter(pk=comment.topic.forum.pk, group__in=list(user.groups.all)).exists():
Je crois que tu as inversé la condition ici? Tu passes de `if X.first() is None:` à `if X.exists():`

2017-02-11 17:33 UTC, artragis commented on zds/notification/receivers.py
> +        if Topic.objects.filter(pk=comment.topic.forum.pk, group__in=list(user.groups.all)).exists():
fixed

2017-02-11 19:52 UTC, DevHugo requested changes

2017-02-11 19:52 UTC, DevHugo commented on zds/notification/receivers.py
> +        if not Topic.objects.filter(pk=comment.topic.forum.pk, group__in=list(user.groups.all)).exists():
Tu as oublié des paranthéses ici `user.groups.all**()**`

2017-02-11 19:53 UTC, artragis commented
fixed.


Le 11/02/2017 à 20:52, Hugo Courtecuisse a écrit :
>
> *@DevHugo* requested changes on this pull request.
>
> ------------------------------------------------------------------------
>
> In zds/notification/receivers.py 
> <https://github.com/zestedesavoir/zds-site/pull/4197#pullrequestreview-21392926>:
>
> > @@ -272,8 +282,14 @@ def answer_comment_event(sender, **kwargs):
>   
>       assert comment is not None
>       assert user is not None
> -
> +    # avoids creation of a ping if forum is not visible.
> +    if sender == Post:
> +        if not Topic.objects.filter(pk=comment.topic.forum.pk, group__in=list(user.groups.all)).exists():
>
> Tu as oublié des paranthéses ici |user.groups.all**()**|
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4197#pullrequestreview-21392926>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xXPGyg9VOp_9pFMG1Tbm2CitRU57ks5rbhGVgaJpZM4L-My8>.
>

2017-02-11 19:58 UTC, DevHugo commented
J'ai une erreur, mais j'arrive pas à trouver ou `Cannot resolve keyword 'group' into field. Choices are: author, author_id, es_already_indexed, es_flagged, forum, forum_id, id, is_locked, is_solved, is_sticky, last_message, last_message_id, post, pubdate, publishablecontent, subtitle, tags, title, topicfollowed, topicread, update_index_date`.

C'est quand je poste un topic dans la corbeille.

2017-02-11 19:59 UTC, DevHugo approved these changes

2017-02-11 20:00 UTC, artragis commented
C'est dans quelle ligne stp?


Le 11/02/2017 à 20:58, Hugo Courtecuisse a écrit :
>
> J'ai une erreur, mais j'arrive pas à trouver ou |Cannot resolve 
> keyword 'group' into field. Choices are: author, author_id, 
> es_already_indexed, es_flagged, forum, forum_id, id, is_locked, 
> is_solved, is_sticky, last_message, last_message_id, post, pubdate, 
> publishablecontent, subtitle, tags, title, topicfollowed, topicread, 
> update_index_date|.
>
> C'est quand je poste un topic dans la corbeille.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4197#issuecomment-279171562>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xdC6yut4B3cNSxh7DIm6xVHcbXpnks5rbhLbgaJpZM4L-My8>.
>

2017-02-11 20:01 UTC, artragis commented
En fait c'est bon, fixed.


Le 11/02/2017 à 20:58, Hugo Courtecuisse a écrit :
>
> J'ai une erreur, mais j'arrive pas à trouver ou |Cannot resolve 
> keyword 'group' into field. Choices are: author, author_id, 
> es_already_indexed, es_flagged, forum, forum_id, id, is_locked, 
> is_solved, is_sticky, last_message, last_message_id, post, pubdate, 
> publishablecontent, subtitle, tags, title, topicfollowed, topicread, 
> update_index_date|.
>
> C'est quand je poste un topic dans la corbeille.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4197#issuecomment-279171562>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xdC6yut4B3cNSxh7DIm6xVHcbXpnks5rbhLbgaJpZM4L-My8>.
>

2017-02-11 20:06 UTC, DevHugo requested changes

2017-02-11 20:06 UTC, DevHugo commented on zds/notification/receivers.py
> +        if not Topic.objects.filter(pk=comment.topic.forum.pk, group__in=list(user.groups.all())).exists():
group__in => "forum__group__in"

2017-02-11 20:08 UTC, DevHugo approved these changes

2017-02-11 20:18 UTC, DevHugo commented
Si on édite dans le forum et qu'on ajoute une personne qui n'était pas déjà ping, cette personne là, ne reçoit pas de notification.

Exemple : 
- Admin poste avec un sujet avec un ping de user et valide
- Il édite et ajoute un ping de staff, valide l'édition
- Y'a que user qui est ping.

2017-02-11 20:23 UTC, DevHugo commented
On ne peut ping personne dans les forums privé, par exemple un admin ne peut pas pinger admin2 dans le forum privé.

2017-02-11 20:30 UTC, DevHugo commented
Passer dans un message dans un forum privé supprime bien les notification pour ceux qui n'ont pas les droits mais aussi ceux qui ont les droits.

2017-02-11 20:41 UTC, artragis commented
Au vue de l'utilité de la chose, je pense que c'est le comportement 
désiré (c'est volontaire) : en effet ce genre de chose arrivera surtout 
quand on passera vers la corbeille et en tant que staff j'osef d'avoir 
été pingé par un message dans la corbeille.


Le 11/02/2017 à 21:30, Hugo Courtecuisse a écrit :
>
> Passer dans un message dans un forum privé supprime bien les 
> notification pour ceux qui n'ont pas les droits mais aussi ceux qui 
> ont les droits.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4197#issuecomment-279173556>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xdV7-Plkfgs1i2bKM_XmMuLbLczMks5rbhpwgaJpZM4L-My8>.
>

2017-02-11 20:46 UTC, artragis commented
>On ne peut ping personne dans les forums privé, par exemple un admin ne peut pas pinger admin2 dans le forum privé.

ceci devrait être corrigé et agira sûrement sur la partie "je peux pas pinger lors de l'édit"

2017-02-11 21:22 UTC, DevHugo commented
Déplacement vers un forum auquel le pingé n'a pas accès
    Pinger X dans un forum 'public'
    Déplacer le sujet dans un forum non-public

Marche plus du coup

2017-02-11 21:36 UTC, artragis commented
J'ai pas compris. Je regarderai demain avec un cerveau plus alerte.


Le 11/02/2017 à 22:22, Hugo Courtecuisse a écrit :
>
> Déplacement vers un forum auquel le pingé n'a pas accès
> Pinger X dans un forum 'public'
> Déplacer le sujet dans un forum non-public
>
> Marche plus du coup
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4197#issuecomment-279176641>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xWLHV_vQXLZwUgDr7CEycnCvxECqks5rbiZ5gaJpZM4L-My8>.
>

2017-02-11 21:44 UTC, DevHugo commented
Je l'ai fait vite fait, je peut-être merder sur la QA, je confirme demain.

2017-02-11 21:45 UTC, vhf commented
Pas compris le scénario non plus.

2017-02-11 21:48 UTC, artragis commented
Je pense qu'il manque un mot ou deux dans le scénario que tu as utilisé 
c'est tout du coup on a juste pas compris ton rapport :)


Le 11/02/2017 à 22:44, Hugo Courtecuisse a écrit :
>
> Je l'ai fait vite fait, je peut-être merder sur la QA, je confirme demain.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/zestedesavoir/zds-site/pull/4197#issuecomment-279178015>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABc_xfexB282CONMDIQeNgN91i-MqN8dks5rbivRgaJpZM4L-My8>.
>

2017-02-12 11:39 UTC, vhf commented
J'ai changé la target branch vers `dev` au lieu de release. On activera pas les ping cette fois pour éviter de retarder une release qui devrait être assez courte et simple. Notamment parce qu'on va devoir attendre un peu de dev sur ZMarkdown. :)

2017-02-28 12:50 UTC, artragis commented
Après rebase et test, j'ai corrigé + ajouté un TU. Par contre les migrations sur les nombres de lettres dans les tutos m'empêchent de tester correctement chez moi.

2017-05-01 19:37 UTC, vhf commented
https://sentry.sandhose.fr/zeste-de-savoir/backend-l7/issues/927/

2018-12-27 11:03 UTC, closed without merging