Ajoute une alerte sur le nombre de contenus orphelins en validation
zestedesavoir/zds-site pull request #4212
Opened 2017-02-14 21:19 UTC by GCodeur

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | nouvelle fonctionnalité
| Ticket(s) (_issue(s)_) concerné(s)  | [ce sujet](https://zestedesavoir.com/forums/sujet/7872/alerte-sur-le-nombre-de-contenus-orphelins-dans-la-zone-de-validation/)

Cette PR ajoute au menu d'un membre staff le nombre de contenus orphelins en attente de validation.

### QA

* Mettre un tutoriel en validation ;
* Vérifier la présence du `(1)` dans le menu ;
* Réserver le tutoriel ;
* Vérifier que le `(1)` a disparu ;
* Idem avec les articles.

2017-02-15 19:35 UTC, pierre-24 requested changes

2017-02-15 19:35 UTC, pierre-24 commented on zds/utils/templatetags/interventions.py
> +def waiting_tutorials_count(user):
Pourquoi ce paramètre `user` ?

2017-02-15 19:35 UTC, pierre-24 commented
Sinon, QA ok : 

![screenshot from 2017-02-15 20 31 19](https://cloud.githubusercontent.com/assets/7889675/22991941/58c7a0a4-f3be-11e6-8db8-b5b92a60ecf6.png)

2017-02-15 19:39 UTC, GCodeur commented on zds/utils/templatetags/interventions.py
> +def waiting_tutorials_count(user):
Pour la même raison que pour la fonction qui récupère les alertes : afin de pouvoir appliquer le filtre sur un objet `User`. ;)

2017-02-15 19:42 UTC, pierre-24 commented on zds/utils/templatetags/interventions.py
> +def waiting_tutorials_count(user):
... Ce qui ne sert à rien dans ta fonction (ce qui est le cas pour les alertes, aussi, mais une issue à la fois) ;) Et à réflexion, pourquoi pas plutôt un paramètre `type`, qui te permetrait de faire `"tutorial"|waiting_count`, un truc du genre :)

2017-02-15 19:43 UTC, pierre-24 commented
Oh, et n'oublie pas d'éditer la [documentation des *templatetags*](http://zds-site.readthedocs.io/fr/latest/front-end/template-tags.html), merci :)

2017-02-15 19:44 UTC, GCodeur commented on zds/utils/templatetags/interventions.py
> +def waiting_tutorials_count(user):
J'aime bien cette solution, va pour ça.

2017-02-15 20:11 UTC, GCodeur commented
Je pense que tout est bon, @pierre-24 :)

2017-02-15 20:35 UTC, pierre-24 requested changes

2017-02-15 20:35 UTC, pierre-24 commented on zds/utils/templatetags/interventions.py
> +    return Validation.objects.filter(
Je vais faire mon chiant, et demander une petite levée d'erreur si `content_type not in zds.tutorialsv2.models.
TYPE_CHOICES_DICT`. Pour être sur :)

2017-02-15 21:19 UTC, pierre-24 requested changes

2017-02-15 21:19 UTC, pierre-24 commented on zds/utils/templatetags/interventions.py
> +    if not content_type in TYPE_CHOICES_DICT:
`not in`:)

2017-02-17 11:06 UTC, firm1 commented
Au vu du rendu, j'avoue que ce n'est pas a ça que je me m'attendais visuellement.

Pour l'instant le compteur est encore caché je trouve, car il faut cliquer sur le menu (action que je ne fais quasi jamais en tant que staff, sauf quand j'ai envie justement d'aller en zone de validation). Je voyais plutôt quelque chose à droite des alertes de modération directement visible.

2017-02-17 11:20 UTC, GCodeur commented
C'est effectivement à ça que j'avais pensé au début, mais on en avait un peu parlé sur IRC et on avait choisi ça (notamment pour des raisons de place il me semble). En soi, ça ne me paraît pas impossible à envisager, mais :

- à voir en terme de place, notamment quand le lien vers les tribunes sera ajouté
- est-ce que ce ne sera pas un peu anti-ergonomique d'avoir trois icônes ouvrant un menu déroulant et une redirigeant vers une autre page ?
- je ne maîtrise pas du tout la façon dont les icônes sont gérées et en bidouillant le HTML, je n'ai pas trouvé d'icône correspondante :/

2017-02-17 13:10 UTC, firm1 commented
Le problème avec la solution actuelle c'est que l'effet escompté (une alerte que l'on voit en permanence) n'est pas atteint.

> à voir en terme de place, notamment quand le lien vers les tribunes sera ajouté

Si on a un problème de place, on peut au moins partir du principe que le nouveau bouton d'alerte ne sera visible que sur les grands écrans. On peut conserver le travail que tu as fais dans cette PR pour les petit écrans.

> est-ce que ce ne sera pas un peu anti-ergonomique d'avoir trois icônes ouvrant un menu déroulant et une redirigeant vers une autre page ?

On peut avoir une icône qui affiche le nombre de contenus orphelins d'une part. En cliquant dessus on a une liste dans laquelle on a les orphelins de type article d'une part et les orphelins de type tutoriels. Et plus tard on aura aussi les tribunes. ça ne me semble pas déconnant.

> je ne maîtrise pas du tout la façon dont les icônes sont gérées et en bidouillant le HTML, je n'ai pas trouvé d'icône correspondante 

A mon sens il faudrait quelque chose qui évoque la validation ou le contenu. Mais en gros pour rajouter une nouvelle icone il faut le rajouter dans le dossier des [assets](https://github.com/zestedesavoir/zds-site/tree/dev/assets/images) et s'inspirer de la partie front dans le code (malheureusement on a pas encore de doc là dessus)

2017-02-23 20:36 UTC, GCodeur commented
Histoire d'avancer un peu, je viens de tenter un autre moyen de faire qui est d'afficher l'icône des paramètres aussi pour les membres du staff (je parle de la roue dentée) et ainsi de pouvoir y mettre le nombre comme on le fait actuellement pour les alertes par exemple. Seulement, niveau rendu, ça donne ça :

![Capture](https://www.pixenli.com/images/1487/1487881409027550200.png)

Lorsque je supprime par exemple l'icône des notifications via les outils de développement, tout revient à la normale. J'ai donc l'impression que le CSS n'accepte que 3 icônes (plus l'avatar), mais je ne le maîtrise pas du tout et ne sais pas comment y remédier.

Sinon, voici le rendu (note qu'il faut trouver un moyen de remettre l'icônes des notifications), est-ce que ça t'irait ?

![Capture](https://www.pixenli.com/images/1487/1487882165086530900.png)

2017-04-04 08:20 UTC, pierre-24 approved these changes

2017-04-04 08:21 UTC, GCodeur commented
Problème résolu grâce à @pierre-24, l'alerte est maintenant fixée sur l'avatar, voici ce que ça donne :

![Capture](https://www.pixenli.com/images/1491/1491293937040567600.png)

2017-04-10 17:57 UTC, artragis commented
@pierre-24 tu valides la QA?

2017-04-10 18:42 UTC, pierre-24 commented
Ouaip' :p

2017-04-10 19:11 UTC, merged