Améliore le marquage des notifications comme lues
zestedesavoir/zds-site pull request #4232
Opened 2017-03-01 16:15 UTC by GCodeur

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | évolution
| Ticket(s) (_issue(s)_) concerné(s)  | #4217

Cette pull request améliore le marquage des notifications comme lues en effectuant les deux modifications suivantes :

- les sujets et contenus liés à une notification sont aussi marqués comme lus : il s'agit de la correction du comportement observé dans #4217.
- les notifications de MP ne sont plus concernées : bien qu'il s'agisse de notifications dans la logique du code, elle n'apparaissent pas sur la page des notifications (où se situe le bouton `Tout marquer comme lu`) et les marquer comme lues également me semble assez déroutant.

### QA

* Depuis un compte (disons `user1`), envoyer plusieurs types de notifications à `user2` telles qu'un MP, une réponse à un MP, un commentaire sur un contenu où il est abonné, un post sur un sujet où il est abonné et un sujet sur un forum où il est abonné.
* Depuis `user2`, utiliser la fonction `Tout marquer comme lu`.
* Vérifier qu'il n'y a plus de notification au sens propre du terme qui soit non lue, mais que les MP n'ont pas été concernés.
* Vérifier que le sujet où un post a été écrit n'est plus en gras dans les derniers sujets suivis.

2017-03-02 14:41 UTC, artragis requested changes

2017-03-02 14:41 UTC, artragis commented on zds/notification/views.py
>      """Mark the notifications of the current user as read"""
Du coup peux-tu mettre à jour ce docstring?

2017-03-02 18:37 UTC, GCodeur commented on zds/notification/views.py
>      """Mark the notifications of the current user as read"""
En effet, je vais faire un truc plus précis.

2017-03-04 10:05 UTC, gustavi commented
**QA** : OK !

Je merge, merci :)

2017-03-04 10:05 UTC, merged