Ajout de l'autocomplétion à la création d'un sujet
zestedesavoir/zds-site pull request #4236
Opened 2017-03-02 19:24 UTC by AmarOk1412

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | nouvelle fonctionnalité
| Ticket(s) (_issue(s)_) concerné(s)  | #736 

Hei! I'm back.
Du coup, ma PR en cours (manque les tests).

Bug connu : l'autocomplétion cherche aussi les membres.

Note, je ne met pas que les sujets résolus. J'ai hésité, mais perso aller voir un sujet similaire non résolu peut éviter un doublon par exemple.

### QA

* Lancer ElasticSearch
* Se rendre à la création d'un nouveau sujet
* Vérifier qu'on peut bien trouver des sujets similaires et que ça l'ouvre au clic dans un nouvel onglet (exemple *Android ou ios*, *Rédiger sur zestedesavoir*)

* Vérifier qu'on puisse bien créer un sujet même sans elasticsearch

![similar](https://cloud.githubusercontent.com/assets/1888628/23523194/f2b759ac-ff53-11e6-8c10-fa4a3e6aaa84.png)

o/

2017-03-02 19:31 UTC, artragis commented on assets/js/autocompletion.js
> +        /*$("#content").on("DOMNodeInserted", "input", function(e) {
Pour faciliter la relecture, peux-tu supprimer le code s'il est totalement en commentaire?

2017-03-02 19:33 UTC, artragis commented on zds/forum/forms.py
> +                'data-autocomplete': '''{ "type": "simple",
Peut-être est-ce une déformation, mais pour mieux séparer les choses, ne serait-il pas mieux de créer un dictionnaire python  puis de le sérialiser grâce à `json.dumps`? ça rend explicite le fait qu'on veuille un json et ça évite les fautes de frappe. En plus ça permet de réduire un peu le poids de la page transmise.

2017-03-02 19:38 UTC, GCodeur commented on zds/searchv2/urls.py
> +    url(r'^topics-similaires/$', SimilarSubjectsView.as_view(), name='similar'),
C'est vraiment du pinaillage, mais généralement, on met les URL en français. Donc on préférera utiliser `sujets` plutôt que `topics` (c'est le cas dans les URL du forum notamment).

2017-03-02 19:42 UTC, artragis requested changes

2017-03-02 19:42 UTC, artragis commented on zds/searchv2/views.py
> +            for hit in search_queryset.execute():
du coup tu souhaites : 
```python
results = [{'id': i, 'url': str(hit.get_absolute_url), 'title': str(hit.title)} for i, hit in enumerate(search_queryset.execute()]
```

J'ai aussi un doute sur le fait que "get_absolute_url" soit une property. Si c'est le cas, alors c'est dommage de l'avoir nommé avec `get_` devant, encore un intoxiqué au java :p :p

2017-03-02 19:42 UTC, artragis commented on zds/searchv2/views.py
> +            self.authorized_forums = [f.pk for f in list_forums]
Ici tu veux probablement simplifier par : 

```python
searched_forums = Forum.objects.filter(group__isnull=True)
if user and user.is_authenticated():
    private_forums = Forum \
        .objects \
        .filter(group__isnull=False, group__in=user.groups.all())
    searched_forums = searched_forum | private_forums
    self.authorized_forums = searched_forums.values_list('pk', flat=True)
```

2017-03-02 19:42 UTC, artragis commented on zds/searchv2/views.py
> +        """Overridden because index manager must NOT be initialized elsewhere
toutafé 👍

2017-03-02 23:53 UTC, AmarOk1412 commented on zds/searchv2/views.py
> +            for hit in search_queryset.execute():
Les properties sont :
+ subtitle
+ pubdate
+ is_sticky
+ is_locked
+ title
+ get_absolute_url
+ tags
+ forum_get_absolute_url
+ forum_pk
+ forum_title
+ pk
+ is_solved
C'est sur que absolute_url aurait été préférable.

2017-03-03 23:59 UTC, AmarOk1412 commented on zds/searchv2/views.py
> +            self.authorized_forums = [f.pk for f in list_forums]
Au final j'ai pas changé ça, ça cassait les tests de la ZEP13 et pour ` result = self.client.get(reverse('search:similar') + '?q=est', follow=False)`

Et je fais comme un peu en dessous pour SearchView

2017-03-10 21:32 UTC, Situphen commented on assets/js/autocompletion.js
> +        $("[data-autocomplete]").each(function () {
Tu es sur que lors d'un événement `DOMNodeInserted` ça fonctionne ?

2017-03-10 21:32 UTC, Situphen commented on assets/scss/components/_autocomplete.scss
> +          padding: 0;
Indentation de 4 espaces et non pas 2 (à faire sur les autres lignes aussi) ;)

2017-03-10 21:32 UTC, Situphen commented on zds/forum/forms.py
> +                    'header': str(_(u'Sujets similaires :')),
Pour utiliser `str()` ?

2017-03-12 20:31 UTC, AmarOk1412 commented on zds/forum/forms.py
> +                    'header': str(_(u'Sujets similaires :')),
sans le str(), la serialisation se foire et lève une exception.

2017-03-12 20:52 UTC, AmarOk1412 commented on assets/js/autocompletion.js
> +        $("[data-autocomplete]").each(function () {
Oui. 
En fait, si je laissez dans l'état actuel et que je mettais plusieurs autocomplete sur la même page, tous étaient complétés de la même manière et si je laisse `$("#content").on("DOMNodeInserted", "input", function(e) {` j'obtiens une jolie boucle avec plein de requêtes et ça freeze le navigateur.

2017-03-12 21:02 UTC, Situphen commented on assets/js/autocompletion.js
> +        $("[data-autocomplete]").each(function () {
D'accord !

2017-03-24 22:37 UTC, vhf commented on zds/forum/forms.py
> +                    'header': str(_(u'Sujets similaires :')),
@Situphen la fonction d'i18n, là, qu'on utilise d'ailleurs partout, est lazy. Certaines autres fonctions ne forcent pas l'évaluation de ce `_()` lazy, et ça a tendance à lever une exception parfois surprenante. Ici, c'est très probablement ce que @AmarOk1412 a rencontré. `str()` forçant l'évaluation du machin, ça passe avec.

2017-03-27 20:11 UTC, artragis commented
Il manque quoi ici?

2017-03-27 21:00 UTC, AmarOk1412 commented
la QA je crois

2017-04-02 18:47 UTC, pierre-24 commented on zds/searchv2/views.py
> +            for hit in search_queryset.execute():
Pour le coup, le fautif, c'est moi :-°

En fait, je dirais que j'ai pas réfléchi des masses quand je l'ai appellée, mais ça provenait du fait qu'on fait des trucs similaires dans la ZEP-12, [ici](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/models/models_database.py#L381). Du coup, dans les templates, ça se voit pas et ça reste naturel :-°

2017-04-02 18:51 UTC, pierre-24 commented on zds/searchv2/views.py
> +        """Overridden because index manager must NOT be initialized elsewhere
J'approuve lourdement.

2017-04-02 19:13 UTC, pierre-24 commented
Rapport de QA, ok. Par contre, j'ai l'une ou l'autre remarque sur le code :)

2017-04-02 19:22 UTC, pierre-24 requested changes

2017-04-02 19:22 UTC, pierre-24 commented on zds/searchv2/views.py
> +                & MultiMatch(query=self.search_query, fields=['title', 'subtitle', 'tags'])
Faudrait pas rajouter une petite limitation ici ? Parce que dans la vraie vie, il peut y avoir plusieurs dizaines de résultats !

2017-04-02 19:22 UTC, pierre-24 commented on zds/searchv2/views.py
> +                cpt += 1
`cpt` :p (pas le nom de variable le plus clair)

2017-04-02 19:22 UTC, pierre-24 commented on zds/searchv2/views.py
> +            forums_pub = Forum.objects.filter(group__isnull=True).all()
Vu que ça fait deux fois que ce bout de code est utilisé sur le même fichier (et elle est aussi utilisée dans les templatetags, d'ailleurs, c'est de là que je l'ai sauvagement c/c), je me demande s'il serait pas bon d'en faire une fonction à part entière, dans un  `utils.py` quelquonque.

2017-04-02 19:22 UTC, pierre-24 commented on zds/searchv2/views.py
> +                cpt += 1
(d'ailleurs, pourquoi c'est nécessaire ? (vrai question))

2017-04-02 19:24 UTC, artragis commented on zds/searchv2/views.py
> +                cpt += 1
Si c'est vraiment nécessaire, on est en plein dans le usecase de `enumerate`

2017-04-03 02:56 UTC, AmarOk1412 commented on zds/searchv2/views.py
> +                cpt += 1
ooohhh c'est carrément du `enumerate`...

Par contre ouai c'est nécessaire. En fait, le id est utilisé par assets/js/autocompletion.js

2017-04-03 02:57 UTC, AmarOk1412 commented on zds/searchv2/views.py
> +                & MultiMatch(query=self.search_query, fields=['title', 'subtitle', 'tags'])
10 me parait bien pour une limitation. j'ajoute ça

2017-04-03 02:59 UTC, AmarOk1412 commented on zds/searchv2/views.py
> +            forums_pub = Forum.objects.filter(group__isnull=True).all()
Tu parles bien de toute la partie pour récupérer `self.authorized_forums` ? Tu as le 3è bout identique (celui de templatetags) ? Comme ça je fais un fichier `utils/authorized_forums.py` avec la fonction ;). Merci !

2017-04-03 04:14 UTC, AmarOk1412 commented
@pierre-24 @artragis thx pour la QA :)

2017-04-03 13:55 UTC, artragis approved these changes

2017-04-03 13:56 UTC, merged