Refonte de l'affichage du badge staff
zestedesavoir/zds-site pull request #4240
Opened 2017-03-10 20:02 UTC by GCodeur

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | correction de bug / évolution
| Ticket(s) (_issue(s)_) concerné(s)  | #2985, #3679

Le but de cette pull request est de refaire l'affichage du badge staff en respectant les deux contraintes suivantes :

- Nommer un membre staff doit afficher son badge immédiatement.
- Aucune requête ne doit avoir lieu pour déterminer si un membre est staff dans un post.

J'ai donc retenu la solution suivante : j'ai créé un attribut `show_staff_badge` sur le modèle `Profile` qui détermine si le badge doit être affiché. Cet attribut est mis à jour automatiquement via un signal lorsqu'un objet `User` est modifié (ce qui est le cas quand on met un membre dans un groupe).

La migration incluse avec la PR s'occupe de renseigner l'attribut pour tous les membres déjà existants (à vérifier si ce n'est pas un problème en terme de nombre de requêtes, sans oublier que l'on reste sur une migration qui ne sera donc exécutée qu'une fois).

### QA

* Lancer les migrations (`make migrate` ou `python manage.py migrate` en fonction de l'environnement de développement que vous utilisez).
* Vérifier que les badges s'affichent correctement sur les membres.
* Promouvoir un membre et vérifier que le badge s'affiche immédiatement. Vérifier également l'opération inverse.

2017-03-27 20:10 UTC, artragis commented
Déjà, bravo !

ensuite, faudra vérifier, mais il me semble que pour être staff, il suffit de faire partie du groupe "staff" donc c'est plutôt 
```python
staff_group = Group.objects.filter(name="staff")  # ou un nom qu'on obtient dans le fichier settings.py
user.profile.display_badge = staff_group in user.groups.all()
```

2017-04-01 12:02 UTC, vhf requested changes
J'ai regardé le code, ça m'a l'air bien mais j'ai pas testé. Je passe mon tour pour l'autre moitié de la QA !

2017-04-01 12:02 UTC, vhf commented on zds/member/migrations/0009_profile_show_staff_badge.py
> +                user_profile.save()
Il vaudrait mieux 

1. Récupérer les id des [users qui ont cette permission](https://stackoverflow.com/questions/378303/how-to-get-a-list-of-all-users-with-a-specific-permission-group-in-django) (demande directement une `values_list` qui est `flat`)
2. Faire directement un truc genre `UserProfile.objects.filter(user__in=).update(show_staff_badge=`

2017-04-02 18:56 UTC, vhf approved these changes

2017-04-03 19:21 UTC, pierre-24 commented
Rapport de QA: ok. Mais comme tu l'as fais remarquer, la *fixture* est un peu à l'ouest ^^

2017-04-03 19:26 UTC, merged