Un auteur qui voit son contenu republié doit suivre ce contenu
zestedesavoir/zds-site pull request #4243
Opened 2017-03-13 14:57 UTC by AmarOk1412

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | correction de bug
| Ticket(s) (_issue(s)_) concerné(s)  | #4238

### QA

+ Faire valider un article ;
+ Vérifier que vous (l'auteur) le suivez bien ;
+ Modifier l'article ;
+ Le faire revalider ;
+ Constater que vous le suivez toujours.

2017-03-13 17:02 UTC, gllmc requested changes
Lorsque je publie le contenu, je ne suis pas abonné. Est-ce que ça pourrait être lié à ce problème ?

2017-03-13 17:02 UTC, GCodeur commented on zds/notification/receivers.py
> +        if not NewPublicationSubscription.objects.get_existing(user, user):
Est-ce qu'il ne faudrait pas plutôt mettre `content` comme deuxième argument ? Je vois mal pourquoi on utilise deux fois `user`.

2017-03-14 13:40 UTC, AmarOk1412 commented on zds/notification/receivers.py
> +        if not NewPublicationSubscription.objects.get_existing(user, user):
En fait, l'important c'est qu'on toggle_follow une seule fois. Au premier passage, NewPubli... est à `None`, et après `subscription = NewPublicationSubscription.objects.get_or_create_active(user, user)` elle existe. 

Mais pour le coup, j'ai remplacé par `ContentReactionAnswerSubscription.objects.get_existing(user, content)` qui est plus *clair*, thx.

2017-03-17 20:14 UTC, gllmc approved these changes
QA : OK !

2017-03-18 21:07 UTC, merged

2017-03-18 21:07 UTC, vhf commented
Merci @AmarOk1412 , merci @GCodeur !