Nouvelle interface pour la liste des tuto
zestedesavoir/zds-site pull request #4327
Opened 2017-05-02 17:20 UTC by artragis

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | évolution
| Ticket(s) (_issue(s)_) concerné(s)  | No ticket

### Reste à faire, need help

- [ ] Mettre en avant certains contenu selon leur catégorie
- [ ] Les paramètres pré-défini de la recherche (@pierre-24)
- [ ] Retirer les dernières données écrites en dur pour former le design

### Relecture de code

Elle est primordiale pour plusieurs raisons : 

- entre le début du développement et aujourd'hui beaucoup de choses ont changé et le dernier rebase était plein de problèmes côté webdesign
- il ne faut pas qu'on crée des goulets d'étranglement

### QA

Faut visiter la page de contenu et voir ce qu'on a mal fait et/ou oublié

Désolé pour l'invocation de masse dans l'onglet review :p

2017-05-03 19:07 UTC, gllmc reviewed
:+1: 

Je trouve que le rendu est très bon et que ça va bien permettre d'améliorer la présentation des contenus qu'on a.

Voici les quelques problèmes que j'ai relevés.

2017-05-03 19:07 UTC, gllmc commented on templates/tutorialv2/view/all_content_page.html
> +                    <p>Dessiner une icône ou des illustrations, corriger un texte ou encore devenir co-auteur vous interesse ?</p>
"intéresse" (avec un accent)

2017-05-03 19:07 UTC, gllmc commented on templates/tutorialv2/view/all_content_page.html
> +                    <h3>Donner son avis</h3>
Plutôt "votre avis" par cohérence avec le deuxième bloc ?

2017-05-03 19:07 UTC, gllmc commented on templates/tutorialv2/view/all_content_page.html
> +                    <p>Les contenus presque terminés nécessitent souvent une relecture afin de peaufiner le fond comme la forme.</p>
"afin d'*en* peaufiner" ?

2017-05-03 19:07 UTC, gllmc commented on templates/tutorialv2/view/all_content_page.html
> +                    <p class="right">Consulter les contenus en bêta.</p>
J'aurais tendance à enlever le point ici.

2017-05-03 19:07 UTC, gllmc commented on templates/tutorialv2/view/all_content_page.html
> +                    <p>Vous avez un savoir à partager, vous vous sentez pédagogue, pourquoi ne pas commencer l'écriture d'un tutoriel ?</p>
Pour rester générique, je me contenterais de "contenu" ici.

2017-05-03 19:07 UTC, gllmc commented on templates/tutorialv2/view/all_content_page.html
> +                    <p class="right">Parcourir les demandes d'aides.</p>
Idem ici (pas de point)

2017-05-03 19:07 UTC, gllmc commented on templates/tutorialv2/list_page_elements/list_of_content.html
> +            {% if current_content_type == "ARTICLE" %}
#4328 ayant été mergé, attention ici à bien mettre le `or current_content_type == "OPINION"`.

2017-05-03 19:07 UTC, gllmc commented on templates/tutorialv2/list_page_elements/side_bar.html
> +        {% elif current_content_type == None %}
`elif not current_content_type` me paraît mieux à titre personnel, mais c'est subjectif.

2017-05-03 19:07 UTC, gllmc commented on templates/tutorialv2/view/all_content_page.html
> +{% endcomment %}
Il faudra ensuite enlever ces commentaires en français (ou les traduire).

2017-05-03 19:07 UTC, gllmc commented on templates/tutorialv2/view/all_content_page.html
> +                {{ content_count }} contenus
`content_count` n'existe pas chez moi et i18n sur les lignes 17 et 18.

2017-05-03 19:07 UTC, gllmc commented on templates/tutorialv2/view/all_content_page.html
> +                <button class="btn ico-after ico-search" type="submit" title="Rechercher"></button>
i18n (lignes 22 et 25)

2017-05-03 19:07 UTC, gllmc commented on templates/tutorialv2/view/all_content_page.html
> +        <h2 itemprop="name">À la une</h2>
i18n

2017-05-03 19:07 UTC, gllmc commented on templates/tutorialv2/view/all_content_page.html
> +        <h2 class="inline" itemprop="name">Domaines de savoir</h2>
i18n

2017-05-03 19:07 UTC, gllmc commented on templates/tutorialv2/view/all_content_page.html
> +            <a href="#" class="more-link">Plus d'articles</a>
i18n (lignes 51, 56, 61 et 66)

2017-05-03 19:07 UTC, gllmc commented on templates/tutorialv2/view/all_content_page.html
> +                    <p class="right">Parcourir les demandes d'aides.</p>
Il manque l'i18n dans le bloc "Envie de s'investir ?".

2017-05-03 19:07 UTC, gllmc commented on zds/tutorialv2/managers.py
> +                    introduction = '[[i]]\n|Ce contenu a été rédigé par {} qui a quitté le site.\n\n'\
Pourquoi cette modification ?

2017-05-03 19:31 UTC, artragis commented
https://www.pixenli.com/images/1493/1493838040036010300.png

2017-05-03 19:32 UTC, artragis commented on templates/tutorialv2/list_page_elements/list_of_content.html
> +            {% if current_content_type == "ARTICLE" %}
toutafé :)

2017-05-04 10:55 UTC, artragis commented
Pour l'image, j'ai trouvé, ligne 6 de "all_content_page" : `<img src="http://127.0.0.1:8000/static/images/home-clem.png">`. @abdelaz3r il faudra que tu expliques ce que tu voulais mettre.

2017-05-04 10:56 UTC, artragis commented on templates/tutorialv2/view/all_content_page.html
> +                    <p>Les contenus presque terminés nécessitent souvent une relecture afin de peaufiner le fond comme la forme.</p>
je sais pas

2017-05-04 11:00 UTC, artragis commented on zds/tutorialv2/managers.py
> +                    introduction = '[[i]]\n|Ce contenu a été rédigé par {} qui a quitté le site.\n\n'\
done

2017-05-04 11:00 UTC, artragis commented on templates/tutorialv2/list_page_elements/side_bar.html
> +        {% elif current_content_type == None %}
done

2017-05-04 11:00 UTC, artragis commented on templates/tutorialv2/list_page_elements/list_of_content.html
> +            {% if current_content_type == "ARTICLE" %}
done

2017-05-04 11:00 UTC, artragis commented on templates/tutorialv2/view/all_content_page.html
> +                    <p class="right">Parcourir les demandes d'aides.</p>
done

2017-05-04 11:01 UTC, artragis commented on templates/tutorialv2/view/all_content_page.html
> +            <a href="#" class="more-link">Plus d'articles</a>
done

2017-05-04 11:01 UTC, artragis commented on templates/tutorialv2/view/all_content_page.html
> +        <h2 itemprop="name">À la une</h2>
done

2017-05-04 11:01 UTC, artragis commented on templates/tutorialv2/view/all_content_page.html
> +                <button class="btn ico-after ico-search" type="submit" title="Rechercher"></button>
done

2017-05-04 11:01 UTC, artragis commented on templates/tutorialv2/view/all_content_page.html
> +{% endcomment %}
Done

2017-05-04 11:12 UTC, artragis commented on templates/tutorialv2/view/all_content_page.html
> +                {{ content_count }} contenus
done

2017-05-04 11:15 UTC, AmauryCarrade commented on templates/tutorialv2/view/all_content_page.html
> +                    <p>Les contenus presque terminés nécessitent souvent une relecture afin de peaufiner le fond comme la forme.</p>
Je trouve aussi qu'« afin d'en peaufiner » sonne mieux dans cette phrase.

2017-05-05 23:13 UTC, AmarOk1412 commented
Pour l'instant j'ai une erreur sur les lignes ` <p>{% trans 'Vous avez un savoir à partager, vous vous sentez pédagogue, pourquoi ne pas commencer l'écriture d'un tutoriel ?' %}</p>` et `<h2 class="inline">{% trans 'Envie de s'investir ?' %}</h2>` : `TemplateSyntaxError: Only options for 'trans' are 'noop', 'context "xxx"', and 'as VAR'.`

Sinon, j'ai des carrés blancs dans les blocs en bas (les span icon) et les boutons "Plus de tutoriels/articles" sont peut etre trop différent de ce qu'on trouve dans le reste du site.

Les pages "contenus/?category=arts-graphisme-et-multimedia" sont vides.

Mais ça a l'air très bien parti :)

2017-05-05 23:19 UTC, AmarOk1412 requested changes

2017-05-05 23:19 UTC, AmarOk1412 commented on assets/scss/components/_linkbox.scss
> +&:after {
Juste bien aligner ici pour que ça fasse plus propre (et l'accolade de fin), sinon le reste du code m'a l'air correct !

2017-05-06 07:58 UTC, artragis commented
@AmarOk1412 j'ai fixé le pb du template.

>Changer la top bar.

c'est à dire?

>Changer l'icone de clem en haut ?

j'attends le retour @abdelaz3r  pour ça.

>Les pages "contenus/?category=arts-graphisme-et-multimedia" sont vides (normal, reste à faire)

Heu, vide, c'est à dire? pas de tuto/article ou pas de design? @abdelaz3r tu peux jeter un coup d'oeil?

2017-05-06 20:50 UTC, AmarOk1412 commented
> @AmarOk1412 j'ai fixé le pb du template.
yeap c'est bon

Pour la top bar je parlais de ce point : https://zestedesavoir.com/forums/sujet/4856/discussions-sur-le-design-de-zestedesavoir/?page=3#p141039 *Sur la topbar, il n’y a plus qu’un bouton contenu en lieu et place des boutons tutos et articles;*

Pour http://127.0.0.1:8000/contenus/?category=communication-et-management, ce que j'ai c'est  : (avec 1 contenu logiquement)
![2017-05-06-16 49 03-screenshot](https://cloud.githubusercontent.com/assets/1888628/25775809/f691af36-327b-11e7-8ddd-32d43d47eaba.png)

2017-05-08 14:06 UTC, artragis commented
>Sur la topbar, il n’y a plus qu’un bouton contenu en lieu et place des boutons tutos et articles;

C'est voulu.

>ce que j'ai c'est : (avec 1 contenu logiquement)

étrange.

2017-05-25 09:12 UTC, abdelaz3r commented
Yep. Déso beaucoup de trucs ces temps. Je vais jeter un oeil à tout ça !

2017-05-25 09:31 UTC, pierre-24 commented
20 ans plus tard, j'apparais: à priori, je vois pas encore la partie sur la recherche implémentée, du coup ou est ce que vous avez besoin d'un coup de patte à ce niveau là ?

2017-05-25 10:18 UTC, abdelaz3r commented
Oui très clairement. En fait il faudrait que le formulaire de recherche renvoi un résultat spécifique selon ou on est.

Sur la home des contenus (all_content_page.html) il faut chercher dans tout les contenus (articles + tutos), sur les pages de catégorie (one_theme_content_page.html) il faut chercher dans les contenus (articles + tutos) appartenant à la catégorie (variable "theme" dans le template).

2017-05-25 10:30 UTC, pierre-24 commented
Normalement, c'est facile, faut juste que je réfléchisse un tout petit peu comment forcer le type et la catégorie, du coup :)

2017-05-25 10:35 UTC, abdelaz3r commented
# Truc encore à faire

Voilà un petit retour sur ce qu'il reste à faire. Comme dit à @artragis je ne m'occupe que des templates et du front. Donc il y a des petits trucs intéressants à faire pour me débloquer le truc.

## Général

- faire un nouveau "ancien" template pour les tribunes qui ne partagent pas ce template

## all_content_page.html

- charger les contenus à la une
- dans le bloc donner son avis : mettre l'url vers le forum de béta

## one_theme_content_page.html

- effectuer la recherche uniquement sur la catégorie (@pierre-24)
- n'afficher que 10 derniers articles
- n'afficher que 10 derniers tutoriels
- n'afficher que les articles appartenant à "theme"
- n'afficher que les tutoriels appartenant à "theme"
- modifier le link du flux rss/atom article pour filtrer selon la catégorie
- modifier le link du flux rss/atom tutoriel pour filtrer selon la catégorie

## Dernier niveau hiérarchique (new_template.html)

De manière général le dernier niveau sera assez simple visuellement. Il y aura toujours le bloc bleu en haut (mais sans la recherche et qui du coup ne sera qu'un fil d'ariane) avec des options. Je vais faire une maquette pour que ça marche. Donc il faudrait créer cette page avec une url, template et tout et tout. Je m'occupe de la remplir.

Après en fait cette page elle va "juste" afficher une liste PAGINEE de contenu avec "pas mal" d'option de filtre et de tri. Il faut donc modifier list_of_content.html pour permettre plus d'option. Notamment une *limite de contenu à charger*. De plus il faudrait une variable de filre et de tri.

Donc on pourrait spécifier dans les filtres :

- le type (article/tuto)
- la catégorie (une des 4)
- la sous-catégorie

Et dans le tri :

- par date (publication asc/desc)
- alphabétique (à voir)
- par nombre de vue (pour plus tard)

# Remarques général pour les URL

De manière général il faut réfléchir à l'arborescence. Je trouve pas le mieux de mettre l'URl de la page d'une catégorie comme ça `http://127.0.0.1:8000/contenus/?theme=Sciences%20humaines%20et%20sociales`, je verrai plutôt comme ça (mais c'est à discuter) : `http://127.0.0.1:8000/contenus/sciences-humaines-et-sociales` (avec un slug et pas un truc avec des majuscules et des espaces).

De plus il faudrait penser au nom et à l'affichage du dernier niveau hiérarchique. Qui peut afficher un peu ce qu'il veut.

2017-05-25 11:27 UTC, abdelaz3r commented on templates/tutorialv2/view/all_content_page.html
> +                    <h3>Donner son avis</h3>
done

2017-05-25 11:27 UTC, abdelaz3r commented on templates/tutorialv2/view/all_content_page.html
> +                    <p>Les contenus presque terminés nécessitent souvent une relecture afin de peaufiner le fond comme la forme.</p>
done

2017-05-25 11:27 UTC, abdelaz3r commented on templates/tutorialv2/view/all_content_page.html
> +                    <p class="right">Consulter les contenus en bêta.</p>
done

2017-05-25 11:27 UTC, abdelaz3r commented on templates/tutorialv2/view/all_content_page.html
> +                    <p class="right">Parcourir les demandes d'aides.</p>
done

2017-05-25 11:28 UTC, abdelaz3r commented on templates/tutorialv2/view/all_content_page.html
> +                    <p>Vous avez un savoir à partager, vous vous sentez pédagogue, pourquoi ne pas commencer l'écriture d'un tutoriel ?</p>
done

2017-05-25 11:28 UTC, abdelaz3r commented on templates/tutorialv2/view/all_content_page.html
> +                    <p>Dessiner une icône ou des illustrations, corriger un texte ou encore devenir co-auteur vous interesse ?</p>
done

2017-05-25 11:34 UTC, pierre-24 commented
Et du coup, les résultats de la recherche devraient-il s'afficher dans les templates que tu as prévues (un peu plus chaud) ou comme les résultats de recherches comme ils sont proposés maintenant ?

2017-05-25 11:44 UTC, abdelaz3r commented
Comme les résultats actuels

2017-05-25 12:01 UTC, qwertygc commented
Possible de voir un screenshot pour voir le résultat actuel ?

2017-05-25 12:14 UTC, abdelaz3r commented
La page de premier niveau:

![p1-1](https://cloud.githubusercontent.com/assets/3975144/26449766/64b6d32e-4154-11e7-8d69-a7e5725a5874.png)
![p1-2](https://cloud.githubusercontent.com/assets/3975144/26449780/743cf706-4154-11e7-8480-b61a473b33df.png)

La page de deuxième niveau:

![p2-1](https://cloud.githubusercontent.com/assets/3975144/26449786/7c047e1e-4154-11e7-99b0-5da82f3d471c.png)

2017-05-25 15:41 UTC, qwertygc commented
Et si on rajoutait une troisième colonne pour les billets ?

2017-05-25 15:47 UTC, abdelaz3r commented
Absolument pas ! Les tribunes et le restes des contenus sont pas du tout la même chose.

La, l'idée étant de rassembler en une seule page tout les contenus validés et de pouvoir parcourir comme dans une bibliothèque des contenus de zeste. Les tribunes c'est un tout autre truc.

2017-05-25 18:09 UTC, qwertygc commented
Donc si je comprends bien, ça permettra d'introduire les parcours ?

2017-05-25 19:13 UTC, abdelaz3r commented
Bah a plus long terme oui, mais ce n'est pas vraiment le sujet ici. On peut en discuter sur le forum, de voir comment la présentation des contenus peut évoluer. Ici c'est une PR qui propose une interface simple, unifiée des contenus. Il y a bien sûr des évolutions possibles mais je ne pense pas qu'il faille en discuter ici.

2017-05-30 15:59 UTC, abdelaz3r commented
@artragis : tu as du temps pour avancer sur ces points ces prochains jours ?

2017-06-12 17:09 UTC, artragis commented
>N'afficher que 10 derniers articles.

je check ça rapidement, mais c'est pas hyper compliqué. 

>Faire un nouveau "ancien" template pour les tribunes qui ne partagent plus ce template.

ça je te laisse le faire, mais un petit copier/coller du template qui est sur le repo actuel devrait suffir, non?

>N'afficher que les articles appartenant à "theme".

le back est prêt, à toi de gérer.

>Modifier le link du flux rss/atom article pour filtrer selon la catégorie.

Je vais vérifier, mais il me semble que c'est aussi de ton côté.

2017-06-12 18:58 UTC, artragis commented
J'ai fait quelques modifs sans avoir eu le temps de les tester. Mais en attendant, @abdelaz3r le nombre de tuto/article devrait être bon

2017-08-01 10:02 UTC, pierre-24 commented
Bon, je vais commencer par lister ce qui ne vas pas/reste à faire. [Y'a déjà un message ici](https://github.com/zestedesavoir/zds-site/pull/4327#issuecomment-303979056), mais c'est pour m'y retrouver ;)

# Général

[ ] Flux RSS
[ ] Urls pour inclure catégories et sous-catégories (ce qui sera probablement plus simple pour gérer les templates)
[ ] Liste des contenus correspondants à ce qui est demandé (pour le moment, ça ne fonctionne pas, on a juste la liste des *x* derniers articles et tutos quoiqu'il arrive)
[ ] Recherche (c'est moiiiiii, j'ai un truc en préparation :p )

# Page de premier niveaux

[ ] "Plus de tutoriels" et "plus d'articles" ne fonctionnent pas (probablement lié à ce qui suis).
[ ] Quand on clique sur "tout les tutoriels", "tout les articles" ou "tout les billets" dans le *dropdown*, on tombe invariablement sur cette page, avec "contenu". Par contre, le nombre de contenu est juste.
[ ] Pas d'administration pour la gestion des mises en avant ? (malgré que la case est cochée dans le message sus-cité)
[ ] Pas la bonne url pour le forum bêta ? (malgré que la case soit cochée dans le message sus-cité)

# Page de second niveau

[ ] "Plus de tutoriels" et "plus d'articles" ne fonctionnent pas.

# Page de troisième niveau

Au vu du commentaire,

```
En deux colonnes
Paginé
Filtré selon les filtres envoyés 
```

... Eh bien:

[ ] Faire la page de troisième niveau

# Remarques/questions

+ Quid des billets, du coup ? On remballe le lien du dropdown sur "l'ancienne page" (pas oublier de lancer un message d'erreur, du coup), ou on bricole pour faire un truc "à part" ?
+ Rajouter des petites infobules sur les liens, pour les catégories aux titres trop long
+ *Quid* de la gestion des images des (sous-)catégories ? (à noter qu'il existe déjà un champ en BDD pour l'image d'une sous-catégorie, mais pas de catégorie, tient).
+ 10, c'est pas un peu beaucoup ? Et d'ailleurs, comment se passe le clic sur la page "tout les tutoriels", en pratique ?
+ Pour pas que j'oublie: « oui, on repart bien sur la recherche "normale" »

ping @abdelaz3r @artragis

2017-08-03 19:34 UTC, pierre-24 commented
Bon, du coup, ce que j'ai fait: 

+ J'ai gardé l'ancienne page: à chaque fois qu'on clique sur "tout les ...", on retombe sur cette liste à l'ancienne. Comme ça, ça fonctionne toujours pour les billets, et on est tranquille.
+ J'ai implémenté la plupart des trucs, entre autre une url pour thème/catégorie. Du coup, j'ai été obligé de créer un nouveau point d'entrée, `/publications/`. Parce que `/contenus/` contient en fait déjà beaucoup de trucs en rapport avec la gestion des contenus, et qu'on a pas été très intelligents quand on a fait ça.
+ J'ai pas encore chipoté au dropdown.

2017-08-03 20:17 UTC, pierre-24 commented on zds/settings.py
> +        'content_per_theme': 10
*Note to self*: ces paramètres ne sont utilisés nul part. Il faudrait ^^ (mais qu'est ce que `'selected_content_method_name'` et `'list'` sont sencé faire ?!?)

2017-08-03 20:32 UTC, pierre-24 commented
Question: 

Comment adapter le design pour les titres un peu trop long ?

![screenshot from 2017-08-03 22 31 27](https://user-images.githubusercontent.com/7889675/28942436-9fe34ac6-789b-11e7-9e51-0bb6b6a45e58.png)

2017-08-04 14:17 UTC, motet-a commented
@pierre-24 Avec quelque chose comme ça ?

![image](https://user-images.githubusercontent.com/15378830/28972546-5d806cd2-7930-11e7-945b-592da90cd52b.png)

2017-08-04 14:25 UTC, motet-a commented
Petit problème de marge sur mobile :

![image](https://user-images.githubusercontent.com/15378830/28972806-61e85d7e-7931-11e7-8bd4-584f7093c586.png)

2017-08-04 17:07 UTC, motet-a commented
```diff
diff --git a/assets/scss/pages/_flexpage.scss b/assets/scss/pages/_flexpage.scss
index c5872341..dce5fb60 100644
--- a/assets/scss/pages/_flexpage.scss
+++ b/assets/scss/pages/_flexpage.scss
@@ -198,7 +198,7 @@ $content-width: 1145px;
 
         .flexpage-column {
             display: block;
-            margin-left: 10px;
+            margin-left: 0;
 
             section {
                 width: 100%;
```

2017-08-04 20:05 UTC, pierre-24 commented on zds/tutorialv2/views/views_published.py
> +            raise NotImplemented("filter view, cf. TODO.md at repository root")
NotImplementedError() en fait (je me fais avoir à chaque fois)

2017-08-04 20:05 UTC, pierre-24 commented on zds/tutorialv2/views/views_published.py
> +                category.subcategories = list(
Peut être remplacé par `category.subcategories = category.get_subcategories()` (mais ça demande de chipoter la template un peu).

2017-08-04 20:05 UTC, pierre-24 commented on zds/tutorialv2/views/views_published.py
> +                    .filter(content__subcategory__in=pks)\
`content_subcategory__in=category.subcategories`, du coup

2017-08-04 20:05 UTC, pierre-24 commented on zds/tutorialv2/views/views_published.py
> +            **dict(content_type='TUTORIAL', **recent_kwargs)
Joli <3

2017-08-04 20:10 UTC, vhf commented on zds/tutorialv2/views/views_published.py
> +            raise NotImplemented("filter view, cf. TODO.md at repository root")
yep !

2017-08-04 20:10 UTC, vhf commented on zds/tutorialv2/views/views_published.py
> +                category.subcategories = list(
Je préfère éviter pour le moment

2017-08-04 20:10 UTC, vhf commented on zds/tutorialv2/views/views_published.py
> +                    .filter(content__subcategory__in=pks)\
Merci !

2017-08-04 20:27 UTC, vhf commented
@abdelaz3r 
* j'ai rebasé donc faudra bien tirer avant de bosser sur le CSS.
* tu peux me faire une maquette pour le lvl `4` ?

2017-08-04 21:52 UTC, pierre-24 commented on zds/tutorialv2/urls/urls_articles.py
> +    url(r'^$', RedirectView.as_view(url=reverse('publication:list'))),
`, permanent=True`

2017-08-05 12:46 UTC, abdelaz3r commented
@vhf : tu as besoin d'une maquette ? Tu veux juste pas créer le template et je le met en forme ?

2017-08-05 13:43 UTC, pierre-24 commented
Pour mon bien être et le votre :-)

```patch
From e5af19d2622af624d591b5734da5fb3bf5b259f3 Mon Sep 17 00:00:00 2001
From: pierre-24 <pierreb24@gmail.com>
Date: Sat, 5 Aug 2017 15:41:28 +0200
Subject: [PATCH] =?UTF-8?q?r=C3=A9pare=20les=20templates?=
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

---
 templates/home.html                                         |  5 +++--
 .../tutorialv2/list_page_elements/list_categories.html      |  8 ++++----
 .../tutorialv2/list_page_elements/list_subcategories.html   |  4 ++--
 zds/tutorialv2/views/views_published.py                     | 13 ++++---------
 4 files changed, 13 insertions(+), 17 deletions(-)

diff --git a/templates/home.html b/templates/home.html
index 85db51a..8b182e9 100644
--- a/templates/home.html
+++ b/templates/home.html
@@ -25,6 +25,7 @@
 {% block content_out %}
     {% url 'opinion:list' as url_opinions %}
     {% url 'cats-forums-list' as url_forums %}
+    {% url 'publication:list' as url_publications %}
 
     {% url 'pages-association' as url_association %}
 
@@ -57,8 +58,8 @@
                                 <strong>gratuitement</strong> et <strong>sans publicité</strong>&nbsp;:
                             </p>
                             <ul>
-                                <li>des <a href="{% url 'publication:list' %}?type=tutorial">tutoriels de tous niveaux</a>&nbsp;;</li>
-                                <li>des <a href="{% url 'publication:list' %}?type=article">articles</a>&nbsp;;</li>
+                                <li>des <a href="{{ url_publications }}?type=tutorial">tutoriels de tous niveaux</a>&nbsp;;</li>
+                                <li>des <a href="{{ url_publications }}?type=article">articles</a>&nbsp;;</li>
                                 <li>des <a href="{{ url_opinions }}">tribunes</a>&nbsp;;</li>
                                 <li>et des <a href="{{ url_forums }}">forums d'entraide</a>.</li>
                             </ul>
diff --git a/templates/tutorialv2/list_page_elements/list_categories.html b/templates/tutorialv2/list_page_elements/list_categories.html
index 5f45dd3..5b6a290 100644
--- a/templates/tutorialv2/list_page_elements/list_categories.html
+++ b/templates/tutorialv2/list_page_elements/list_categories.html
@@ -14,8 +14,8 @@ exposes categories
         <a href="{% url 'publication:list' %}?category={{ category.slug }}" class="body">
             <p>{{ category.description }}</p>
             <p class="right">
-                {% if category.count_contents != 0 %}
-                    {{ category.count_contents }} {% trans 'contenu' %}{{ category.count_contents|pluralize_fr }}
+                {% if category.contents_count != 0 %}
+                    {{ category.contents_count }} {% trans 'contenu' %}{{ category.contents_count|pluralize_fr }}
                 {% else %}
                     {% trans 'Aucun contenu' %}
                 {% endif %}
@@ -23,8 +23,8 @@ exposes categories
         </a>
 
         {% for subcategory in category.subcategories %}
-           <a href="{% url 'publication:list' %}?subcategory={{ subcategory.subcategory__slug }}" class="tail">
-                <p>{{ subcategory.subcategory__title }}</p>
+           <a href="{% url 'publication:list' %}?subcategory={{ subcategory.slug }}" class="tail">
+                <p>{{ subcategory.title }}</p>
             </a>
         {% endfor %}
     </div>
diff --git a/templates/tutorialv2/list_page_elements/list_subcategories.html b/templates/tutorialv2/list_page_elements/list_subcategories.html
index 21fa328..e976ec2 100644
--- a/templates/tutorialv2/list_page_elements/list_subcategories.html
+++ b/templates/tutorialv2/list_page_elements/list_subcategories.html
@@ -13,8 +13,8 @@ exposes subcategories
             </a>
             <a href="{% url 'publication:list' %}?subcategory={{ subcategory.slug }}" class="body">
                 <p class="right">
-                {% if subcategory.count_contents != 0 %}
-                    {{ subcategory.count_contents }} {% trans 'contenu' %}{{ subcategory.count_contents|pluralize_fr }}
+                {% if subcategory.contents_count != 0 %}
+                    {{ subcategory.contents_count }} {% trans 'contenu' %}{{ subcategory.contents_count|pluralize_fr }}
                 {% else %}
                     {% trans 'Aucun contenu' %}
                 {% endif %}
diff --git a/zds/tutorialv2/views/views_published.py b/zds/tutorialv2/views/views_published.py
index 0a3a65f..3febfba 100644
--- a/zds/tutorialv2/views/views_published.py
+++ b/zds/tutorialv2/views/views_published.py
@@ -30,7 +30,7 @@ from zds.tutorialv2.mixins import SingleOnlineContentDetailViewMixin, SingleOnli
 from zds.tutorialv2.models import TYPE_CHOICES_DICT
 from zds.tutorialv2.models.models_database import PublishableContent, PublishedContent, ContentReaction
 from zds.tutorialv2.utils import search_container_or_404, last_participation_is_old, mark_read
-from zds.utils.models import Alert, CommentVote, Tag, Category, CategorySubCategory, CommentEdit, SubCategory
+from zds.utils.models import Alert, CommentVote, Tag, Category, CommentEdit, SubCategory
 from zds.utils.paginator import make_pagination, ZdSPagingListView
 from zds.utils.templatetags.topbar import top_categories_content
 
@@ -417,7 +417,7 @@ class ViewPublications(TemplateView):
                 self.request.GET.get('type', False) or \
                 self.request.GET.get('tags', False):
             self.level = 4
-            raise NotImplementedError("filter view, cf. TODO.md at repository root")
+            raise NotImplementedError('filter view, cf. TODO.md at repository root')
 
         self.template_name = self.templates[self.level]
         recent_kwargs = {}
@@ -427,12 +427,7 @@ class ViewPublications(TemplateView):
             # get categories and subcategories
             context['categories'] = list(Category.objects.order_by('position').all())
             for category in context['categories']:
-                category.subcategories = list(
-                    CategorySubCategory.objects
-                        .filter(is_main=True, category=category)
-                        .prefetch_related('subcategory')
-                        .values('subcategory__pk', 'subcategory__title', 'subcategory__slug', 'subcategory__image')
-                        .all())
+                category.subcategories = category.get_subcategories()
 
                 category.contents_count = PublishedContent.objects \
                     .published_contents() \
@@ -736,7 +731,7 @@ class SendContentAlert(FormView, LoginRequiredMixin):
         try:
             content_pk = int(self.kwargs['pk'])
         except (KeyError, ValueError):
-            raise Http404(u"Identifiant manquant ou conversion en entier impossible.")
+            raise Http404(u'Identifiant manquant ou conversion en entier impossible.')
         content = get_object_or_404(PublishableContent, pk=content_pk)
 
         alert = Alert(
-- 
1.9.1


```

2017-08-06 11:43 UTC, pierre-24 commented
C'est génial <3

Mais ... 

!()[https://ihatehongkong2.files.wordpress.com/2014/06/4488876837_8d3da2423a_z.jpg]

Rapport de QA:

+ Dans le dropdown, chez moi, la flèche est très proche du mot "bibliothèque":

![screenshot from 2017-08-06 13 24 52](https://user-images.githubusercontent.com/7889675/29002801-022e3f22-7aab-11e7-91d4-174d9bd9454e.png)

+ Les liens dans le dropdown ont toujours l'ancien format en "filtre" (d'où 404)
+ Quand on parcourt une sous-catégorie vide, il manque un "aucun contenu" (j'ai pas testé sur une catégorie vide):

![screenshot from 2017-08-06 13 30 48](https://user-images.githubusercontent.com/7889675/29002822-7b92c61c-7aab-11e7-9afe-74c3c8c2ba3f.png)

+ Ça serait éventuellement bien que sur la page "niveau 4", domaine et catégorie soient clicables.
+ Je sais pas si c'est vous (j'ai pas ça sur `dev`, en tout cas), mais y'a plus "zeste de savoir" dans l'atribut titre, et ce sur toutes les pages:

![screenshot from 2017-08-06 13 35 14](https://user-images.githubusercontent.com/7889675/29002854-2bf25324-7aac-11e7-81cf-58d4a508d44e.png)

+ Les flux RSS des catégories (`?category=xxx`) sont vides (mais ceux généraux et des sous-catégories fonctionnent)

2017-08-06 11:47 UTC, motet-a commented
![image](https://user-images.githubusercontent.com/15378830/29002929-b66ffea6-7aad-11e7-9a50-e2d1c1a7a676.png)

Hey les gens, tenez pas compte de ce problème de flèche et ne touchez à rien, j’ai un fix : #4440

2017-08-06 12:24 UTC, abdelaz3r commented
> Ça serait éventuellement bien que sur la page "niveau 4", domaine et catégorie soient clicables.

Done !

2017-08-06 12:41 UTC, motet-a commented
![image](https://user-images.githubusercontent.com/15378830/29003330-1b9b22fe-7ab5-11e7-9a78-d47b80235260.png)

Sur mobile, ça serait bien de mettre moins de marge et une ellipse : « Biblio… »

2017-08-06 12:42 UTC, motet-a commented
![image](https://user-images.githubusercontent.com/15378830/29003353-6a26abfa-7ab5-11e7-8c25-f4a1108ec5e9.png)

Voilà ce que ça donne avec un vrai navigateur.

2017-08-06 12:43 UTC, motet-a commented
À part ça j’ai bien essayé sur IE nottament et j’ai rien à rajouter à la review de @pierre-24.

2017-08-06 13:57 UTC, merged