[WIP] Alerte le staff en cas de nouveau fournisseur e-mail et lui permet de le bannir
zestedesavoir/zds-site pull request #4331
Opened 2017-05-06 12:08 UTC by GCodeur

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | nouvelle fonctionnalité
| Ticket(s) (_issue(s)_) concerné(s)  | #4313 

Cette PR ajoute un système envoyant une alerte aux membres du staff lorsqu'un nouveau fournisseur d'adresses e-mail est utilisé (lors de l'activation d'un compte ou de la modification de l'adresse e-mail). Une interface accessible via le menu utilisateur liste ainsi les nouveaux fournisseurs avec un bouton `Approuver` (= supprime l'alerte) et un bouton `Bannir` (= bannit le fournisseur et supprime l'alerte). Une autre page permet de gérer les fournisseurs bannis (et éventuellement d'en ajouter un manuellement).

Pour info, j'en ai profité au passage pour utiliser un `ModelForm` et une `CreateView`, ce qui permet de faire un formulaire de création d'objet de façon très simple.

### Todo

- [ ] Les tests.
- [ ] Voir comment migrer proprement les données de la liste existante vers la BDD. Si quelqu'un a une idée sur la question, n'hésitez pas.

### QA

- S'inscrire avec un fournisseur inutilisé.
- Se connecter sur un compte `user` et changer son e-mail avec encore une fois un fournisseur inutilisé.
- Se connecter en `admin` et vérifier que deux alertes ont été créées.
- Tester les boutons `Approuver` et `Bannir`.
- Vérifier l'ajout et la suppression d'un fournisseur banni.
- Vérifier qu'on ne peut pas s'inscrire (ou éditer son e-mail) avec un fournisseur banni.
- Code review.

2017-05-09 16:57 UTC, GCodeur commented
Les tests sont faits et j'ai inclus la feature demandée par @gustavi (recherche des membres utilisant un fournisseur). Par contre, j'ai toujours pas vraiment d'idée sur la manière la plus propre de transférer les fournisseurs actuellement interdits, je vais y réfléchir.

2017-05-13 11:36 UTC, GCodeur commented
Normalement, tout y est : tests, migrations, etc. Il ne manque plus que la QA.

PS : la PR n'est pas si énorme qu'elle en a l'air : sur les 2400 "lines changed", il y en a plus de 1600 qui correspondent à l'ancien fichier supprimé et à la migration.

2017-05-16 11:38 UTC, artragis requested changes
C'est une chouette PR, juste quelques broutilles à changer je pense.

2017-05-16 11:38 UTC, artragis commented on zds/member/views.py
> +        provider = re.findall(r'@(.+)', usr.email)[0].lower()
vaut mieux pas faire ça, en effet on peut créer une adresse mail avec un arrobase dans l'user part (oui, c'est strange le mail). à ce jeu, vaut mieux faire le simple truc suivant : 

`provider = usr.email.split('"')[-1].split('@')[-1]` puis à tester si `usr.email.ends_with('@' + provider)`. Ça peut paraître beaucoup, mais je me casse suffisament la tête avec ce genre de cas pour éviter que ça n'arrive sur zds.

2017-05-16 11:38 UTC, artragis commented on zds/member/views.py
> +            NewEmailProvider.objects.create(user=usr, provider=provider, use='NEW_ACCOUNT')
Quand c'est comme ça on aime bien utiliser des constantes, ça permet de donner le sens au code.

2017-05-16 11:38 UTC, artragis commented on zds/member/views.py
> +@permission_required('member.change_bannedemailprovider', raise_exception=True)
Il faudra mettre dans le UPDATE.md que comme il y a eu une nouvelle permission, il faut s'assurer que le staff est bien affiliée à cette permission, sinon ça va pas aller.

2017-05-16 11:38 UTC, artragis commented on zds/member/validators.py
> +                raise ValidationError(_(u'Ce fournisseur ne peut pas être utilisé.'), code=self.code)
Du coup ça serait cool (et faciliterait la migration) de mettre `from __future__ import unicolde_literals` et d'enlever le `u`.

2017-05-16 15:28 UTC, GCodeur commented on zds/member/views.py
> +@permission_required('member.change_bannedemailprovider', raise_exception=True)
C'est déjà fait, ça. ^^

2017-05-16 15:30 UTC, GCodeur commented on zds/member/views.py
> +        provider = re.findall(r'@(.+)', usr.email)[0].lower()
Tiens, je savais pas qu'on pouvait faire ça. Je vais adapter du coup, en effet.

2017-05-16 15:44 UTC, GCodeur commented on zds/member/views.py
> +            NewEmailProvider.objects.create(user=usr, provider=provider, use='NEW_ACCOUNT')
Tu veux parler d'une constante pour `NEW_ACCOUNT` ? Est-ce vraiment utile étant donné que la chaîne est très explicite ?

2017-05-16 15:44 UTC, GCodeur commented on zds/member/validators.py
> +                raise ValidationError(_(u'Ce fournisseur ne peut pas être utilisé.'), code=self.code)
Ça marche !

2017-05-16 16:21 UTC, GCodeur commented on zds/member/views.py
> +        provider = re.findall(r'@(.+)', usr.email)[0].lower()
Juste une question, à quoi sert le `.split('"')[-1]` ? Car `usr.email.split('@')[-1]` me paraît suffisant.

2017-05-19 07:21 UTC, artragis commented on zds/member/views.py
> +        provider = re.findall(r'@(.+)', usr.email)[0].lower()
ça peut si on est sûr que le mail est valide avant de faire le split.

2017-05-19 07:22 UTC, artragis commented on zds/member/views.py
> +            NewEmailProvider.objects.create(user=usr, provider=provider, use='NEW_ACCOUNT')
C'est toujours utile.

2017-05-19 09:41 UTC, pierre-24 commented
Tient, chaipas dans quelle mesure c'est possible, mais y'aurais pas moyen d'aller retrouver le nombre d'utilisateurs bannis ou en LS utilisant un fournisseur donné ? Comme ça, on vois directement les domaines qui peuvent possiblement poser problème.

2017-05-19 21:10 UTC, GCodeur commented
@pierre-24 : actuellement, il y a possibilité de rechercher tous les comptes correspondant à un fournisseur interdit. Tu verrais ça comment, un filtre "Comptes sanctionnés uniquement" ?

(Par contre, je sais pas si ça a un sens vu que dans ce cas, ça veut dire que le fournisseur est déjà sur la liste noire. ^^)

2017-05-20 08:44 UTC, pierre-24 commented
> Par contre, je sais pas si ça a un sens vu que dans ce cas, ça veut dire que le fournisseur est déjà sur la liste noire. ^^

Ah, oui, ok, évidement. J'ai rien dit, du coup :p

2017-05-26 07:43 UTC, gustavi requested changes

2017-05-26 07:43 UTC, gustavi commented on templates/member/settings/add_banned_email_provider.html
> +            {% trans "Retour" %} <span class="wide">{% trans "aux fournisseurs" %}</span>
Un `{% blocktrans %}` est préférable ici au lieu de 2 `{% trans %}`

2017-05-26 07:43 UTC, gustavi commented on templates/member/settings/banned_email_providers.html
> +            {% trans "Bannir" %} <span class="wide">{% trans "un fournisseur" %}</span>
idem, `{% blocktrans %}`

2017-05-26 07:43 UTC, gustavi commented on templates/member/settings/members_with_provider.html
> +            {% trans "Retour" %} <span class="wide">{% trans "aux fournisseurs" %}</span>
idem, `{% blocktrans %}`

2017-05-26 07:43 UTC, gustavi commented on templates/member/settings/new_email_providers.html
> +            {% trans "Bannir" %} <span class="wide">{% trans "un fournisseur" %}</span>
idem, `{% blocktrans %}`

2017-05-26 07:43 UTC, gustavi commented on zds/member/__init__.py
> +# coding: utf-8
Pourquoi mettre ça dans ce fichier ?

2017-05-26 07:43 UTC, gustavi commented on zds/member/forms.py
> +                'placeholder': _(u"La partie qui suit l'arobase dans l'adresse e-mail."),
On appelle ça un "nom de domaine" ;)

2017-05-26 07:43 UTC, gustavi commented on zds/member/models.py
> +        verbose_name = 'Nouveau fournisseur'
i18n

2017-05-26 07:43 UTC, gustavi commented on zds/member/models.py
> +        verbose_name_plural = 'Nouveaux fournisseurs'
i18n

2017-05-26 07:43 UTC, gustavi commented on zds/member/models.py
> +        verbose_name = 'Fournisseur banni'
idem

2017-05-26 07:43 UTC, gustavi commented on zds/member/models.py
> +    date = models.DateTimeField(auto_now_add=True, db_index=True,
Au lieu d'utiliser `verbose_name='foo'` au milieu, tu peux simplement le passer en premier paramètre : `DateTimeField('foobar', ...)`. C'est plus joli et plus uniforme, pas besoin de chercher au milieu ce que c'est. Pense également a bien en mettre sur TOUS les champs, même quand c'est trivial car ça peut ne pas l'être pour tous

2017-05-26 07:43 UTC, gustavi commented on zds/member/urls.py
> +    url(r'^fournisseurs/nouveaux/$', NewEmailProvidersList.as_view(), name='new-email-providers'),
Caser "email" quelque part dans les URL ne ferait pas de mal

2017-05-26 07:43 UTC, gustavi commented on zds/member/views.py
> +        provider = usr.email.split('@')[-1].lower()
J'ai pas testé mais ça match "@foo.xyz" si "@foo.*" est banni ?

2017-05-26 07:43 UTC, gustavi commented on zds/settings.py
> +        'providers_per_page': 50,
Tu peux même mettre 100

2017-05-26 10:15 UTC, GCodeur commented on zds/member/__init__.py
> +# coding: utf-8
C'est ce qu'on a fait pour ce genre de variables jusqu'à présent ([exemple](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/models/__init__.py)).

2017-05-26 10:18 UTC, GCodeur commented on zds/member/forms.py
> +                'placeholder': _(u"La partie qui suit l'arobase dans l'adresse e-mail."),
Comme c'est le `placeholder`, j'ai préféré faire quelque chose de plus clair ici, d'autant qu'on n'est [pas obligé](https://github.com/GCodeur/zds-site/blob/61251db1f9878b4fe13ba05fd371bcf99f8d4abc/templates/member/settings/add_banned_email_provider.html#L32-L37) de mettre un nom de domaine complet. C'est comme tu préfères.

2017-05-26 10:20 UTC, GCodeur commented on zds/member/views.py
> +        provider = usr.email.split('@')[-1].lower()
Pas "@foo.*" mais "@foo.". C'est ce que contient notre fichier actuellement et ce que j'ai mis dans les [instructions](https://github.com/GCodeur/zds-site/blob/61251db1f9878b4fe13ba05fd371bcf99f8d4abc/templates/member/settings/add_banned_email_provider.html#L32-L37) en haut du formulaire.

2017-05-26 10:37 UTC, GCodeur commented on zds/member/models.py
> +        verbose_name_plural = 'Nouveaux fournisseurs'
Pour nos autres modèles, on n'a jamais fait d'i18n ici, mais je pense que ça peut se faire.

2017-05-26 20:58 UTC, gustavi commented on zds/member/forms.py
> +                'placeholder': _(u"La partie qui suit l'arobase dans l'adresse e-mail."),
Dans ce cas le message n'est pas clair ici. Je préfère nom de domaine, c'est plus précis et tout le monde sais de quoi on parle

2017-05-29 11:38 UTC, artragis commented
j'ai testé un cas : 

le membre s'inscrit avec un domaine inconnu au bataillon (`unnouveaumembre@unnouveaumembre.com`).

Je me connecte en tant qu'administrateur. Aucun domaine n'apparaît dans la liste des "nouveaux domaines".

2017-05-29 16:55 UTC, GCodeur commented
@artragis : le fournisseur n'est ajouté qu'à l'activation du compte, tu l'as bien faite ?

2017-05-30 11:18 UTC, artragis commented
QA OK, je merge.

2017-05-30 11:18 UTC, merged