Passage à Django 1.10
zestedesavoir/zds-site pull request #4347
Opened 2017-05-23 19:55 UTC by gustavi

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | évolution
| Ticket(s) (_issue(s)_) concerné(s)  | #3898

### QA

TOUT doit être testé.

- [ ] Travis est content
- [ ] Testé et approuvé
- [ ] Testé en bêta

- [ ] Ça fonctionne !
- [ ] Code relu et approuvé !

2017-05-23 20:18 UTC, artragis commented on zds/gallery/views.py
> +            return
Why?

2017-05-23 20:18 UTC, artragis commented on zds/member/managers.py
> +            .select_related('user')
Why?

2017-05-23 20:18 UTC, artragis commented on zds/settings.py
> +#SWAGGER_SETTINGS = {
Le code commenté ne devrait pas être commité.

2017-05-23 23:47 UTC, gustavi commented on zds/member/managers.py
> +            .select_related('user')
https://docs.djangoproject.com/en/1.9/releases/1.8/#select-related-now-checks-given-fields

2017-05-23 23:48 UTC, gustavi commented on zds/gallery/views.py
> +            return
un bon gros fail

2017-05-23 23:49 UTC, gustavi commented on zds/settings.py
> +#SWAGGER_SETTINGS = {
C'est toujours WIP par rapport au problème évoque dans la description de l'issue

2017-05-24 00:25 UTC, gustavi commented
https://docs.djangoproject.com/fr/1.9/ref/forms/fields/#django.forms.CharField.strip pour les tests que j'ai modifié

2017-05-24 08:04 UTC, artragis commented on zds/member/managers.py
> +            .select_related('user')
DOnc maintenant on est obligé de sélectionner le user complet?

2017-05-27 08:25 UTC, gustavi commented on zds/member/managers.py
> +            .select_related('user')
Comme répondu sur IRC, avec {prefetch,select}_related oui.

2017-05-28 21:54 UTC, gustavi commented
Si quelqu'un a l'explication ou arrive à reproduire en version de dev pour [ça](http://paste.awesom.eu/0FiD) je prends !

2017-05-29 12:09 UTC, artragis commented
repproduit. 

pas sûr de ça, mais ça ressemble à un bug de la debug toolbar si j'en crois ma stack de debug django.

2017-05-29 23:07 UTC, gustavi commented
Après quelques recherches, pour reproduire le bug mystère : 

- DEBUG=False
- Créer une galerie avec admin
- Créer une galerie avec user (pour se faciliter la tâche)
- Aller sur la page des galeries
- Modifier l'HTML pour changer le PK de la galerie de user par cette d'admin
- Essayer de supprimer

2017-05-31 06:24 UTC, artragis requested changes

2017-05-31 06:24 UTC, artragis commented on zds/utils/management/commands/load_fixtures.py
> +        parser.add_argument('type', action='store', nargs='*', type=str, default=self.zds_modules,
en fait j'aurai pas fait comme ça : 

```python
parser.add_argument('-m', action='append_const', const='member', dest='type')
parser.add_argument('-s', action='append_const', const='staff', help='create staff members', dest='type')
parser.add_argument('--cf', action='append_const', const='category_forum', help='create_forum categories', dest='type')
parser.add_argument('--cc', action='append_const', const='category_content', help='create_forum categories', dest='type')
# etc.
```

2017-05-31 06:24 UTC, artragis commented on zds/utils/management/commands/load_fixtures.py
> +        default_module = options.get('type', self.zds_modules)
si tu utilises ma méthode, va falloir mettre `options.get('type') or self.zds_modules`

2017-05-31 06:24 UTC, artragis commented on zds/utils/management/commands/load_factory_data.py
> +        for filename in glob.glob(files):
+1

2017-05-31 06:24 UTC, artragis commented on zds/utils/management/commands/load_factory_data.py
> +        parser.add_argument('files', nargs='?', type=str)
un petit help pour dire que : 

- on gère le glob
- on s'attend à des fichier yaml

2017-06-02 12:13 UTC, gustavi commented on zds/utils/management/commands/load_fixtures.py
> +        parser.add_argument('type', action='store', nargs='*', type=str, default=self.zds_modules,
J'ai fait en sorte que le comportement soit identique à celui actuel (pas de modification des TU). Je suis d'accord sur le fait que ça DOIT être amélioré.

2017-06-06 16:28 UTC, vhf commented
FYI https://code.djangoproject.com/ticket/28276#comment:1

On saute direct à 1.11 ou on renomme une petite dizaine de clés à cause de ce bug Django. Tu choisis.

2017-06-08 20:55 UTC, gustavi commented
QA GO GO GO !

2017-06-08 20:56 UTC, gustavi commented on zds/utils/management/commands/load_factory_data.py
> +        parser.add_argument('files', nargs='?', type=str)
Pour le coup il va falloir faire une PR propre pour revoir TOUTES les commandes. Je ferai ça à ce moment.

2017-06-09 06:24 UTC, gustavi commented on zds/gallery/tests/tests_views.py
> +from django.test import TestCase, override_settings
Note : à supprimer

2017-06-09 06:24 UTC, gustavi commented on zds/gallery/tests/tests_views.py
> +    @override_settings(DEBUG=True)
idem

2017-06-09 06:24 UTC, gustavi commented on zds/settings.py
> +    'APIS_SORTER': 'alpha',
TODO : ajouter les "exclude"

2017-06-10 11:53 UTC, GCodeur commented
J'ai fait un petit tour du site avec Django 1.10 et tout est OK !

J'ai testé :

- la génération des fixtures (j'ai fait un `make restart_db` qui a marché parfaitement)
- les galeries (ajout d'images notamment)
- les contenus (création et publication, import et export d'archives, dont certaines venant de Django 1.8)
- les forums (création de sujets, mise en résolu, déplacement, alertes de modération)
- l'API (plusieurs vues testées via la documentation automatique)
- la création d'un MP

2017-06-10 16:43 UTC, gustavi commented
C'est mis à jour avec les dernières retouches et rebase. Je pense que si bug ultra spécifique il y a il sera trouvé en bêta.

@artragis je te laisse merge quand c'est bon pour toi !

2017-06-11 16:42 UTC, artragis commented
Je merge, on verra en béta.

2017-06-11 16:42 UTC, merged