Nettoie l'output des tests pour les commandes
zestedesavoir/zds-site pull request #4355
Opened 2017-05-30 11:57 UTC by artragis

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | correction de bug 
| Ticket(s) (_issue(s)_) concerné(s)  | (ex : #4346)

### QA

- Juste regarder l'output de travis
- Code review

2017-05-30 21:18 UTC, gustavi requested changes

2017-05-30 21:18 UTC, gustavi commented on zds/utils/management/commands/load_fixtures.py
> +            _options = arg.split('=')
j'ai totalement réécrit ça dans la PR django 1.10

2017-05-30 21:18 UTC, gustavi commented on zds/utils/management/tests.py
> +        get_commands()['load_fixtures'] = FixturesCommand(stdout=StringIO())
en fait dans l'issue je voulais qu'on rajoute un paramètre `--silent` par exemple

2017-05-31 06:15 UTC, artragis commented on zds/utils/management/commands/load_fixtures.py
> +            _options = arg.split('=')
ça ne m'étonne pas. j'ai juste fait ça car pycharm me le demandait.

2017-05-31 06:15 UTC, artragis commented on zds/utils/management/tests.py
> +        get_commands()['load_fixtures'] = FixturesCommand(stdout=StringIO())
oui, mais en voyant commant ça avait été codé (on n'utilise pas argparse), je préfère corriger **l'effet** que la cause, le travail de fond serait trop important.

2017-08-02 12:03 UTC, pierre-24 commented
Diu coup, est ce que ça en vaut encore la peine ?

2017-08-13 07:51 UTC, artragis commented
J'abandonne, je vais gérer ça autrement maintenant que django 1.10 est dans la boîte.

2017-08-13 07:51 UTC, closed without merging