Affiche la liste des abonnements sur la page des notifications
zestedesavoir/zds-site pull request #4361
Opened 2017-06-03 12:51 UTC by GCodeur

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | évolution
| Ticket(s) (_issue(s)_) concerné(s)  | #4356 

Cette PR ajoute à la page des notifications des options pour voir la liste des forums, membres et tags auxquels on est abonné dans des pop-ups.

### QA

- S'abonner à un tag, un forum et à un membre et vérifier que ces abonnements s'affichent sur la page des notifications.
- Vérifier que se désabonner supprime bien la ligne.
- Vérifier l'exactitude de l'information "Par courriel".
- Code review

2017-06-03 15:46 UTC, gustavi requested changes
Les icônes (https://i.imgur.com/n2uunPs.png) ne vont pas du tout. Il faut les changer ou ne pas en mettre.

2017-06-03 15:47 UTC, GCodeur commented
Je pense partir sur la deuxième solution. Je n'ai pas trouvé d'icônes plus adaptées. :/

2017-06-14 11:36 UTC, gustavi requested changes
Je me pose aussi la question de savoir a quoi va ressembler la page avec énorméments d'abonnements. Je ferai des tests et te dirai si c'est bon avant de merge.

2017-06-14 11:36 UTC, gustavi commented on zds/notification/views.py
> +        context['followed_users'] = Subscription.objects \
Tu peux facilement sortir la partie commune de la QS pour n'appliquer le reste qu'ensuite, ça sera plus simple à maintenir et le code sera plus lisible

2017-06-14 14:16 UTC, gcodeur commented
> Je me pose aussi la question de savoir a quoi va ressembler la page avec énorméments d'abonnements. 

La modale risque en effet de faire toute la hauteur de l'écran, je vais vérifier ça et voir si on peut rendre ça plus esthétique.
Je me demande aussi s'il n'y a pas un risque que la personne ait "trop" d'abonnements et que la page ne parvienne plus à se charger correctement. On pourrait ajouter un garde-fou en limitant l'affichage à 100 abonnements par exemple (avec un message disant que tout n'est pas affiché).

2017-09-24 10:36 UTC, closed without merging

2017-09-24 12:39 UTC, motet-a commented
On peut éventuellement faire une modale scrollable.

2017-09-24 15:36 UTC, gcodeur commented
Ouais, ça pourrait se faire (je rouvrirai une PR si je me relance là-dedans, mais si quelqu'un veut le faire entre-temps, qu'il n'hésite pas).