Met à jour TeXLive
zestedesavoir/zds-site pull request #4371
Opened 2017-06-07 06:48 UTC by pierre-24

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | correction de bug
| Ticket(s) (_issue(s)_) concerné(s)  | https://github.com/zestedesavoir/latex-template/issues/33

Merci à @Karnaj pour avoir courageusement corrigé les erreurs, paquets après paquets :)

### QA

Un build travis finissant avec succès, et sur l'installation de TexLive (supression du cache nécéssaire) et sur la création de PDF.

2017-06-07 07:12 UTC, gustavi requested changes
Il manque les informations pour la mise à jour en bêta/prod dans le `update.md`.

2017-06-08 05:48 UTC, pierre-24 commented
@gustavi : en effet, mais là je suis embêté. En effet, la documentation [dit de "suivre l'installation complète sous Linux"](http://zds-site.readthedocs.io/fr/latest/install/deploy-in-production.html#installation-de-l-application-de-base) , qui indique elle [d'installer TexLive par le gestionnaire de paquet](http://zds-site.readthedocs.io/fr/latest/install/backend-linux-install.html#aller-plus-loin). Si TexLive est effectivement installé via le gestionnaire de paquets, je n'ai rien de spécifique à faire (à part que ça risque de poser problème, parce que cette version de LaTeX  commence à dater). Autrement, je peux "simplement" dire d'utiliser le script d'installation :)

2017-06-08 07:38 UTC, gustavi commented
L'objectif de ce fichier est "**ne pas se faire chier à aller lire la doc en milieu d'une mise en pro**d" donc il faut une petite phrase qui dit ce qu'on fait et la/les commande(s) nécessaires à la mise à jour. Quand il y a une intervention manuelle il FAUT qu'elle soit un minimum détaillée !

2017-06-08 08:09 UTC, pierre-24 commented
Je pense que j'ai pas été clair:

+ Si sur la prod on utilise les paquets débian, il n'y a rien à faire
+ si c'est autre chose, il y a quelque chose à faire.

Ma question étant: c'est quoi qu'on utilise ? :p

2017-06-08 17:21 UTC, gustavi commented
OK j'ai rien dit, on utilise la version de Debian

2017-06-08 17:21 UTC, gustavi approved these changes

2017-06-08 17:21 UTC, merged