[WIP] Système de casquettes
zestedesavoir/zds-site pull request #4387
Opened 2017-06-27 17:16 UTC by gcodeur

**Ne pas merger, WIP.**

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | nouvelle fonctionnalité
| Ticket(s) (_issue(s)_) concerné(s)  | [forum](https://zestedesavoir.com/forums/sujet/8822/ma-casquette-de-modo/)

Cette PR est une ébauche et contient ce que j'ai déjà fait pour le système de casquettes.

### TODO

+ [ ] Régler les problèmes de design
+ [ ] Faire le ménage dans les migrations
+ [ ] Mettre des casquettes sur les MP automatiques
+ [ ] La documentation
+ [ ] Les tests

### QA

Pour le moment, on peut tester :

- l'affichage et la modification des casquettes sur le profil (la modification étant réservée aux membres ayant la permission `utils.change_hat`)
- l'envoi d'un message, d'un commentaire ou d'un MP avec une casquette
- la commande `python manage.py add_hat_to_group` qui ajoute une casquette à tous les membres d'un groupe (cf `UPDATE.md`)

Et aussi faire du code review.

2017-06-27 18:35 UTC, artragis requested changes
C'est une belle PR :)

2017-06-27 18:35 UTC, artragis commented on zds/member/views.py
> +@permission_required('utils.change_hat', raise_exception=True)
je serais tenté d'ajoujter un `@transaction.atomic`

2017-06-27 18:35 UTC, artragis commented on zds/member/views.py
> +    if not request.POST.get('hat'):
pour éviter les erreurs 500 : 

```python
    hat = request.POST.get('hat', None)
    if not hat:
        # error
    elif len(hat) > 40:  #elif très important
        #error
    else:

2017-06-27 18:35 UTC, artragis commented on zds/member/views.py
> +    if hat.profile_set.count() == 0:
pas très d'accord avec ça.

2017-06-27 18:35 UTC, artragis commented on zds/member/views.py
> +@permission_required('utils.change_hat', raise_exception=True)
je verrais bien un `@transaction.atomic`

2017-06-27 18:35 UTC, artragis commented on zds/tutorialv2/forms.py
> +        if reaction is None:
pourquoi `reaction`?

2017-06-27 18:35 UTC, artragis commented on zds/utils/models.py
> +    if not request.POST.get('hat'):
`if 'hat' not in request.POST`

2017-06-27 18:35 UTC, artragis commented on zds/utils/models.py
> +    except (ValueError, Hat.DoesNotExist, AssertionError):
un petit logger.warning permettrait d'avoir des infos bien utiles :)

2017-06-27 18:51 UTC, gcodeur commented on zds/member/views.py
> +    if not request.POST.get('hat'):
En effet, j'ai oublié le `elif`, bien vu !

2017-06-27 18:53 UTC, gcodeur commented on zds/member/views.py
> +    if hat.profile_set.count() == 0:
Pas d'accord avec la suppression ? Ça me paraît utile pour ne pas garder des objets inutiles.

Au cas où tu n'aurais pas compris ça : les messages utilisant la casquette la stockent sous format texte, donc ils la garderont. ;)

2017-06-27 18:54 UTC, gcodeur commented on zds/tutorialv2/forms.py
> +        if reaction is None:
C'est pour vérifier s'il s'agit d'une édition ou d'un nouveau commentaire. Dans le premier cas, on n'ajoute pas le choix de la casquette.

2017-06-27 18:55 UTC, gcodeur commented on zds/utils/models.py
> +    if not request.POST.get('hat'):
Pas forcément, car `hat` se trouvera dans la requête avec pour valeur `''` si la personne possède une casquette mais n'a rien sélectionné. ;)

2017-06-27 18:55 UTC, gcodeur commented on zds/utils/models.py
> +    except (ValueError, Hat.DoesNotExist, AssertionError):
Ok, j'avoue que j'ai jamais utilisé ça, mais les exemples d'utilisation ne manquent pas dans le code.

2017-06-27 20:07 UTC, artragis commented on zds/member/views.py
> +    if hat.profile_set.count() == 0:
j'ai pas supprimer un truc qui est important pour le site.

2017-06-27 20:08 UTC, artragis commented on zds/tutorialv2/forms.py
> +        if reaction is None:
ah bien vu. tu peux ajouter un commentaire pour dire ça stp?

2017-06-27 20:08 UTC, artragis commented on zds/utils/models.py
> +    if not request.POST.get('hat'):
donc `if not request.POST.get('hat', '')`

2017-06-28 15:25 UTC, gustavi commented on zds/utils/models.py
> +    class Meta:
Juste pour *****er les mouches, on préfère mettre `class Meta:` **après** les champs (oui je sais, c'est pas comme ça ailleurs il faut changer).

cf https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#model-style

2017-06-28 15:27 UTC, gcodeur commented on zds/utils/models.py
> +    class Meta:
Du coup, je mets ça après pour ce modèle-ci ?

2017-06-29 12:16 UTC, gcodeur commented
Le code est terminé ! Il y a normalement ce qu'il faut : tests et documentation.

J'ai mis à jour les instructions de QA dans le premier message.

2017-06-29 19:26 UTC, vhf commented on doc/source/back-end/member.rst
> +
La doc 😍

2017-06-29 19:29 UTC, vhf commented on zds/member/admin.py
> +    raw_id_fields = ('user', 'hats')
On n'aura jamais des milliers de hats, tu peux le mettre dans un select au lieu d'un `raw_id_field` ;)

2017-06-29 19:37 UTC, SpaceFox commented on zds/member/admin.py
> +    raw_id_fields = ('user', 'hats')
Sait-on jamais, on a peut-être le prochain Facebook entre nos mais :p

2017-06-29 19:38 UTC, vhf commented on zds/tutorialv2/forms.py
> +        if reaction is None:  # it's a new comment
`if not reaction: # we're not editing an existing comment` ? :)

2017-07-01 00:05 UTC, AmarOk1412 commented
@gcodeur tu peux me reping dimanche pour la **QA** ? J'aurais surement la possibilité d'y consacrer du temps

2017-07-02 12:43 UTC, gcodeur commented
@AmarOk1412 : ping pour la QA, merci de ton aide :)
Avant de merger, @gustavi m'avait dit sur IRC avoir quelques remarques à faire.

2017-07-02 15:49 UTC, AmarOk1412 commented
Suggestion : pouvoir enlever/modifier sa casquette à l'edit d'un message.

2017-07-02 15:54 UTC, AmarOk1412 commented
Sinon pour le moment @gcodeur **QA**: OK

2017-07-02 17:32 UTC, gcodeur commented
Merci pour la QA @AmarOk1412 !

Pour la modification de la casquette utilisée, ça me paraît assez complexe pour une première version : les casquettes utilisables sont celles que l'on a au moment où on poste. Si on peut éditer la casquette sur un ancien message, ça pose problème vu qu'on ne peut pas reconstituer quelles casquettes la personne avait quand elle a posté.

2017-07-03 21:33 UTC, vhf approved these changes

2017-07-04 02:31 UTC, AmarOk1412 commented
@gcodeur Bien sûr, c'est pas grave pour la V1, on peut juste garder l'idée de côté :)

2017-08-01 09:47 UTC, artragis approved these changes

2017-08-01 09:49 UTC, artragis commented
@gcodeur pour le rapport de codacy, si tu n'utilises jamais la variable "created", tu peux soit tricker en mettant un log.info où la variable apparaitra (exemple `logger.info('topic has hat(name=%s, new=%s)", hat, created)`) soit tu remplaces `created` par `_`

2017-08-01 12:33 UTC, vhf commented
Oui, remplace les variables non utilisées par `_`, c'est une convention :)

`first, _ = ('a', 'b')`

2017-08-05 10:09 UTC, vhf commented
FYI on aimerait merger cette PR dès que possible. GCodeur a quelques soucis de matériels mais ils devraient être résolus d'ici quelques jours max. Donc

1. Rebase
2. Règle les derniers détails
3. Merge
4. Merci

2017-08-06 13:46 UTC, pierre-24 commented
Rapport de QA: rien à redire, vraiment, beau boulot :)

2017-08-06 13:47 UTC, pierre-24 approved these changes

2017-08-06 14:01 UTC, motet-a approved these changes
LGTM

2017-08-06 14:17 UTC, merged