WIP: prépare la migration vers zmd
zestedesavoir/zds-site pull request #4389
Opened 2017-07-02 14:15 UTC by vhf

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | évolution
| Ticket(s) (_issue(s)_) concerné(s)  | #4388

Cette PR prépare le terrain pour la migration vers zmarkdown. Le but est de voir comment les choses fonctionnent actuellement, de documenter le travail qui sera nécessaire à la migration, et ce faisant de passer un coup de balais.

2017-07-07 16:18 UTC, vhf commented
Pour les curieux : 

* Server: https://github.com/vhf/zds-site/blob/5092aba14f7b1d7fe368da27c25b97f3762ab2c2/zmarkdown/markdown-server.js
* Client: https://github.com/vhf/zds-site/blob/c690e049e77d4b65dfe8c6612dfc58e061324823/zds/utils/templatetags/emarkdown.py#L35-L36

Test manuel / demo :

```py
import zerorpc

markdown_client = zerorpc.Client()
markdown_client.connect("tcp://127.0.0.1:24242")

html = markdown_client.toHTML("""
## My title

Foo: [bar](http://example.com)
""")

print html
```

```
$ yarn
$ npm run zmd
$ python zmd-server-test.py
<h2>My title</h2>
<p>Foo: <a href="http://example.com">bar</a></p>
```

2017-07-09 20:04 UTC, artragis commented on zmarkdown/config.js
> +const rebberConfig = {
remember we need to override `image` and `figure.image` to use the custome `\\image` command in rebber.

2017-07-09 20:12 UTC, vhf commented on zmarkdown/config.js
> +const rebberConfig = {
Oui ça viendra :)

Là c'est juste pour que ça fonctionne temporairement. Quand tout est bien câblé on verra où et comment on configure le serveur de rendu markdown/latex.

2017-07-26 21:27 UTC, SpaceFox commented on zds/utils/templatetags/emarkdown.py
> +    endpoint = '/html' if not is_latex else '/latex'
Le Comité Contre les Double Négations préfèrerait – si c'est possible – un truc du genre :

```python
endpoint = '/latex' if is_latex else 'html'
```

À voir selon les habitudes du langage aussi.

2017-07-26 21:39 UTC, vhf commented on zds/utils/templatetags/emarkdown.py
> +    endpoint = '/html' if not is_latex else '/latex'
Ouais peut-être, à voir.

Je me serais pas permis un `x = y if not not_foo else foo`, ça ce serait une double négation et ce serait pénible à lire. J'ai fait ça comme ça ici parce que clairement 99% des requêtes iront sur l'endpoint `/html` et que je préfère noter que sauf exception c'est là qu'on va.

Je crois que je préférerais

```python
endoint = '/html'
if is_latex:
    endpoint = '/latex'
```

à ta solution, pour continuer à véhiculer cette impression de valeur par défaut.

2017-07-27 07:08 UTC, artragis commented on zds/utils/templatetags/emarkdown.py
> +    endpoint = '/html' if not is_latex else '/latex'
Lorsque j'avais fait la condition initiale j'avais pensé justement au fait que plus de 90% des requêtes seraient vers html. Après mettez la forme que vous voulez, les deux sont correctes et lisibles.

2017-08-01 17:48 UTC, vhf commented on .travis.yml
> +  - $HOME/.texlive/bin/x86_64-linux/mktexlsr $HOME/.texlive
@pierre-24 @Karnaj une idée de comment faire pour que LaTeX trouve la classe ?

Je la mets là : `$HOME/.texlive/texmf-local/tex/latex/zestedesavoir/zmdocument.cls` mais si vous regardez les logs de travis, latex ne trouve pas la classe.

2017-08-01 18:04 UTC, pierre-24 commented on .travis.yml
> +  - $HOME/.texlive/bin/x86_64-linux/mktexlsr $HOME/.texlive
J'imagine que t'as déjà essayé, mais chez moi, je met simplement le .cls dans `$HOME/texmf/tex/latex/`, puis je fais un `texhash` et ça fonctionne sans autre forme de procès.

2017-08-01 19:05 UTC, pierre-24 commented on .travis.yml
> +  - $HOME/.texlive/bin/x86_64-linux/mktexlsr $HOME/.texlive
... Voilà, [ici](https://travis-ci.org/pierre-24/latex-template/builds/259902363?utm_source=email&utm_medium=notification), j'ai réussi. Ton "erreur", c'est le "zestedesavoir", du reste t'étais quasi dans le bon :)

2017-08-01 21:46 UTC, vhf commented on .travis.yml
> +  - $HOME/.texlive/bin/x86_64-linux/mktexlsr $HOME/.texlive
Fantastique, merci pour ton aide !

Maintenant il doit nous manquer des trucs :

> `FailureDuringPublication: ! LaTeX Error: File `xpatch.sty' not found.`

Je remets un message ici si je trouve

2017-08-01 22:09 UTC, vhf commented on .travis.yml
> +  - $HOME/.texlive/bin/x86_64-linux/mktexlsr $HOME/.texlive
Réussi !

2017-08-03 12:58 UTC, motet-a commented on zds/tutorialv2/epub_utils.py
> +    with open(join(working_dir, 'toc.ncx'), mode='wb', encoding='utf-8') as f:
cnx ou ncx ?

2017-08-11 18:59 UTC, motet-a commented on Gulpfile.js
> +gulp.task('css', ['css:sprite', 'css:vendors'], () =>
La tâche `css:vendors` n’existe plus désormais. Les dépendances externes (`normalize.css`) sont maintenant accédées directement depuis le `node_modules`.

2017-08-11 18:59 UTC, motet-a commented on Gulpfile.js
> +    gulp.src(['assets/scss/main.scss', 'assets/scss/zmd.scss'])
Pourquoi ne pas `@import` le fichier `zmd.scss` depuis `main.scss` ?

2017-08-31 18:09 UTC, artragis commented on zmarkdown/markdown-server.js
> +app.use(Raven.errorHandler());
ça peut être cool de trouver la version de zmd pour ajouter ça aux release management.

2017-09-01 06:21 UTC, artragis commented on zmarkdown/markdown-server.js
> +  Raven.mergeContext({
il existe la propriété "release" qui peut être sympa. mais là ça peut suffire, puisque les tags sont indexés.

2017-09-01 06:45 UTC, vhf commented on zmarkdown/markdown-server.js
> +  Raven.mergeContext({
Je veux bien un lien vers la doc, j'ai cherché et j'ai aussi comparé avec ce qu'on fait avec Django. :)

2017-09-01 08:39 UTC, vhf commented on zmarkdown/markdown-server.js
> +  Raven.mergeContext({
Ah je crois que c'était bien caché : https://docs.sentry.io/clients/javascript/sourcemaps/

Si je comprends bien je dois modifier le DSN pour y ajouter `/releases/<sha>` et passer

```
Raven.config({
    release: '<sha>'
})
```

2017-09-01 09:50 UTC, artragis requested changes

2017-09-01 09:50 UTC, artragis commented on zds/tutorialv2/publication_utils.py
> +            2: 'small',
tu peux ajouter 1: 'small' ici.

2017-09-01 12:53 UTC, vhf commented on requirements.txt
> +Pygments==2.2.0
Note: faudra faire tourner latex dans le venv pour qu'il puisse accéder à Pygments.

2017-09-10 14:31 UTC, closed without merging

2017-09-10 14:33 UTC, vhf commented
Suite ici comme ça tout le monde peut contribuer : #4617