Ajoute des champs DCMI aux pages des contenus - Rends le site compatible avec Zotero
zestedesavoir/zds-site pull request #4392
Opened 2017-07-03 23:29 UTC by rezemika

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | nouvelle fonctionnalité
| Ticket(s) (_issue(s)_) concerné(s)  | #4261 

### QA

- Installer l'extension Firefox Zotero ou un équivalent.
- Utiliser le bouton idoine pour enregistrer dans Zotero divers contenus du site. Vérifier le formatage des informations pour : 
    - chaque type de contenu ;
    - un contenu avec un seul auteur, deux et plus de deux auteurs ;
    - un contenu avec et un contenu sans description.

Voici le formatage que j'ai utilisé pour les champs DCMI, à modifier au besoin. La liste des auteurs est de type "Auteur 1, Auteur 2 et Auteur 3". Celle des tags est de type "Tag 1 ; Tag 2 ; Tag 3".

```
DC.publisher = "Zeste de Savoir"
DC.creator = [liste des auteurs du contenu]
DC.type = "text"
DC.title = [titre du contenu]
DC.abstract = [titre et description du contenu si disponnible]
DC.subject = [liste des catégories et des tags du contenu]
DC.date = [date de publication ou de dernière mise à jour du contenu]
DC.format = "text/html"
DC.source = [source du contenu si disponnible]
DC.language = "fr"
DC.rights = [licence du contenu]
```

PS : J'ai eu quelques soucis lors du merge. J'espère que ça ne posera pas de problème ici.

- [ ] Ça fonctionne !
- [ ] Code relu et approuvé !

2017-07-04 12:56 UTC, gllmc requested changes
Ça semble marcher sans problème de mon côté. Il y a quelques machins que j'améliorerais bien et des erreurs PEP-8 à corriger. :)

2017-07-04 12:56 UTC, gcodeur commented on templates/tutorialv2/view/content_online.html
> +    <meta name="DC.publisher" lang="fr" content="{{app.site.name}}" />
Plutôt `{{ app.site.litteral_name }}` pour un rendu plus correct ("Zeste de Savoir" au lieu de "ZesteDeSavoir").

2017-07-04 12:56 UTC, gcodeur commented on templates/base.html
> +            {% endif %}
Je n'ai pas vraiment compris cette modification, mais j'ai une indentation incorrecte sur ta branche :

Actuellement :

```html
                    {% if app.site.social.googleplus %}
                        <li><a href="{{app.site.social.googleplus}}" title="Retrouvez-nous sur Google+" class="btn ico-after google-plus light btn-google-plus btn-holder"></a></li>
            {% endif %}
```

Correct :

```html
                    {% if app.site.social.googleplus %}
                        <li><a href="{{app.site.social.googleplus}}" title="Retrouvez-nous sur Google+" class="btn ico-after google-plus light btn-google-plus btn-holder"></a></li>
                    {% endif %}
```

2017-07-04 12:56 UTC, gcodeur commented on zds/utils/templatetags/joinby.py
> +def joinby(values, separator=", ", same_final_separator=False):
PEP-8 : il faudrait des guillemets simples.

2017-07-04 12:56 UTC, gcodeur commented on zds/utils/templatetags/joinby.py
> +        return ""
PEP-8 : il faudrait des guillemets simples.

2017-07-04 12:56 UTC, gcodeur commented on zds/utils/templatetags/joinby.py
> +        final_sep = unicode(_(" et "))
PEP-8 : il faudrait des guillemets simples. Je n'ai pas vraiment compris pourquoi tu as utilisé `unicode`.

2017-07-04 12:56 UTC, gcodeur commented on zds/utils/templatetags/joinby.py
> +    return separator.join(map(str, values[:len(values)-1])) + (
PEP-8 : il faut des espaces autour des opérateur mathématiques. ;)

2017-07-04 12:56 UTC, gcodeur commented on zds/utils/templatetags/joinby.py
> +        return values[0].__str__()
```diff
- return values[0].__str__()
+ return str(values[0])
```

2017-07-04 12:56 UTC, gcodeur commented on zds/utils/templatetags/joinby.py
> +        final_sep + values.last().__str__()
```diff
- values.last().__str__()
+ str(values.last())
```

2017-07-04 12:56 UTC, gcodeur commented on templates/tutorialv2/view/content_online.html
> +    <meta name="DC.subject" lang="fr" content="{% joinby content.subcategory.all %}{% if content.tags.all %} - {% joinby content.tags.all separator=' ; ' same_final_separator=True %}{% endif %}" />
Pour ces deux lignes, j'utiliserais plutôt le tiret `–` au lieu de `-`. :)

2017-07-04 13:15 UTC, rezemika commented on templates/base.html
> +            {% endif %}
Ah oui en effet, ça doit être une fausse manip', désolé.

2017-07-04 13:18 UTC, rezemika commented on zds/utils/templatetags/joinby.py
> +        final_sep = unicode(_(" et "))
Pour le `unicode`, c'est parce que j'avais une erreur étrange à la ligne d'après quand je concatenais `final_sep` avec l'autre string.

Voilà ce que j'obtenais : `TypeError: coercing to Unicode: need string or buffer, __proxy__ found`. Je n'ai pu résoudre ça qu'en rajoutant un `unicode()`, j'ignores pourquoi.

2017-07-04 13:28 UTC, gcodeur commented on zds/utils/templatetags/joinby.py
> +        final_sep = unicode(_(" et "))
Dans ce cas, essaye de rajouter sous l'encodage la ligne `from __future__ import unicode_literals`, je pense que ça devrait marcher. ;)

2017-07-04 15:08 UTC, rezemika commented on zds/utils/templatetags/joinby.py
> +        final_sep = unicode(_(" et "))
Update : J'avais bêtement oublié de mettre à jour mon virtualenv avec les derniers paquets utilisés par ZdS. Je l'ai mis à jour et ça marche correctement sans nouvelle importation. :)

2017-07-06 16:22 UTC, rezemika commented
Changements effectués, désolé pour le retard. :)

Je suis passé par Github directement, d'où le triple commit.

2017-07-09 20:26 UTC, gllmc reviewed
Il y a juste un oubli qui a provoqué l'échec de Travis. Sinon, tout est OK.

Un *rebase* est requis par contre :

- `git fetch upstream`
- `git rebase upstream/dev`

2017-07-09 20:26 UTC, gcodeur commented on zds/utils/templatetags/joinby.py
> +        final_sep = _(" et ")
L'erreur de Travis vient d'ici, il faut des guillemets simples. :)

2017-07-09 20:30 UTC, rezemika commented on zds/utils/templatetags/joinby.py
> +        final_sep = _(" et ")
Ah ? Il me semblait que c'était pythonique de mettre des guillemets doubles pour des mots. Je refais un commit.

2017-07-09 20:33 UTC, gcodeur commented on zds/utils/templatetags/joinby.py
> +        final_sep = _(" et ")
@rezemika : en fait, on met en règle générale des guillemets simples. On met des guillemets doubles quand il y a une apostrophe dans la chaîne (pour éviter d'avoir à utiliser un antislash). ;)

2017-07-09 20:35 UTC, rezemika commented on zds/utils/templatetags/joinby.py
> +        final_sep = _(" et ")
Ah ok. De mon côté j'ai toujous mis des guillemets doubles pour les mots ou les phrases (genre "Hello world !") et des simples pour le reste (les séparateurs pour les split, ce genre de choses). My bad.

2017-07-09 20:38 UTC, gcodeur commented on zds/utils/templatetags/joinby.py
> +        final_sep = _(" et ")
Ce n'est pas vraiment un problème, ça. La règle que j'ai citée est celle qui a été choisie pour ce dépôt, mais PEP-8 est beaucoup plus permissif (d'où le fait qu'une règle ait été décidée afin de garder une certaine cohérence dans l'utilisation des guillemets).

2017-07-09 20:40 UTC, rezemika commented on zds/utils/templatetags/joinby.py
> +        final_sep = _(" et ")
Ah je vois. Merci de cette précision. :)

2017-08-02 11:53 UTC, pierre-24 commented
Ah, y'a un test à réparer, ici.

2017-08-04 13:25 UTC, pierre-24 commented on templates/tutorialv2/view/content_online.html
> +    <meta name="DC.creator" content="{% joinby content.authors.all %}" />
La gestion des auteurs est un peu particulière : pour que ça fonctionne, ça devrait probablement être `joinby content|displayable_authors:True`. Ça provient du fait que les auteurs peuvent varier en fonction des mises à jour d'un tuto.

2017-08-04 13:27 UTC, pierre-24 requested changes

2017-08-04 13:27 UTC, pierre-24 commented on zds/utils/templatetags/joinby.py
> +# coding: utf-8
Si tu ajoute un *templatetag*, il faut le documenter [ici](https://github.com/zestedesavoir/zds-site/blob/dev/doc/source/front-end/template-tags.rst) ;)

2017-08-04 13:28 UTC, pierre-24 commented on templates/tutorialv2/view/content_online.html
> +    <meta name="DC.creator" content="{% joinby content.authors.all %}" />
[Plus d'infos ici](https://github.com/zestedesavoir/zds-site/blob/dev/doc/source/front-end/template-tags.rst#le-module-displayable_authors)

2017-08-04 15:23 UTC, gllmc approved these changes

2017-08-04 15:24 UTC, pierre-24 approved these changes

2017-08-04 15:40 UTC, pierre-24 commented
Ben ça me semble fonctionner pas mal :)

![screenshot from 2017-08-04 17 34 22](https://user-images.githubusercontent.com/7889675/28975879-02fcd0aa-793c-11e7-93fa-77fd09c1c372.png)

2017-08-04 15:40 UTC, merged