Fix 4468
zestedesavoir/zds-site pull request #4482
Opened 2017-08-06 20:34 UTC by abdelaz3r

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | correction de bug
| Ticket(s) (_issue(s)_) concerné(s)  | #4468 
### QA

- Vérifier que l'entête s'affiche bien sur les 4 niveaux et sur desktop/mobile

2017-08-06 23:01 UTC, motet-a reviewed
Avec certaines largeurs de fenêtre, les séparateurs `>` ne sont pas toujours au début de la ligne : 

![image](https://user-images.githubusercontent.com/15378830/29007793-3cba0f8a-7b0b-11e7-83c7-ce6f08164fa5.png)

Je pense que ça pourrait faire mieux de lier les séparateurs `>` avec l’élément qui les suit, de façon à ce que les `>` soient toujours en début de ligne.

À part ça, c’est tout bon.

2017-08-08 09:21 UTC, abdelaz3r commented
Ouais je vais faire encore un commit pour gérer ça.

2017-08-11 11:20 UTC, abdelaz3r commented
Voilà, si quelqu'un peux faire la QA, normalement ça devrait être bon.

2017-08-11 17:35 UTC, motet-a requested changes
C’est carrément mieux ! Mais...

![image](https://user-images.githubusercontent.com/15378830/29224834-3ab8b37a-7ecc-11e7-8d2c-f133c8266d6e.png)

Il manque encore un petit truc, c’est presque parfait.

2017-08-12 14:06 UTC, closed without merging