[WIP] Permet de modifier la casquette à l'édition d'un message
zestedesavoir/zds-site pull request #4496
Opened 2017-08-07 20:27 UTC by gcodeur

**Ne pas merger, WIP.**

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | évolution
| Ticket(s) (_issue(s)_) concerné(s)  | aucun

### TODO

- [ ] Les tests

### QA

- Vérifier que l'on peut modifier la casquette lors de l'édition d'un message de forum, d'un sujet, d'un MP ou d'un commentaire d'un contenu.
- Vérifier que les casquettes disponibles sont celles qu'a l'auteur du message *actuellement*.
- Vérifier que lorsqu'on édite comme staff, les casquettes disponibles restent celles de l'auteur du message.
- Vérifier que restaurer une version depuis l'historique des éditions d'un message entraîne la suppression de la casquette si l'utilisateur ne l'a plus.
- Code review

2017-08-09 16:07 UTC, pierre-24 requested changes
Rapport de QA: ok, sauf les commentaires ci-dessous. Également, si on restaure un message, la casquette correspondante n'est pas restaurée (mais je ne sais pas si c'est réellement une *feature* désirable).

2017-08-09 16:07 UTC, pierre-24 commented on zds/pages/views.py
> +            if hat not in comment.author.profile.hats.all():
En toute honneteté, je m'interroge sur l'utilité de ce block `if`. En effet, je crois que ce qui revenait dans la discussion sur les casquettes ([ici, par exemple](https://zestedesavoir.com/forums/sujet/8822/ma-casquette-de-modo/#p153574)) était justement qu'elles permetaient de faire comprendre un message à postériori, puisque la casquette y restait même si l'utilisateur n'était plus staff. Là, j'ai l'impression que supprime justement la casquette si l'utilisateur quitte le staff.

2017-08-09 16:07 UTC, pierre-24 commented on zds/utils/models.py
> +        if hat not in author.profile.hats.all():
Et là, même chose, non ?

2017-08-09 17:03 UTC, gcodeur commented
@pierre-24: j'avais justement eu une discussion avec @vhf à propos du comportement attendu ici.

En fait, le rôle de la casquette est de certifier que le contenu du message a été écrit par quelqu'un ayant la dite casquette. Du coup, à partir du moment où on édite un message que l'on a posté avec une casquette, on ne peut laisser la casquette au message que si on la possède toujours étant donné que son contenu est modifié.

Pour l'historique des éditions, je n'ai en effet pas enregistré la casquette et j'ai opté pour vérifier si la casquette est toujours possédée par l'utilisateur lors d'une restauration (dans le cas contraire, on la supprime, une restauration étant considérée comme une édition avec l'ancien contenu comme en témoigne la date de dernière édition qui est mise à jour).

Est-ce que cette conception de la chose te paraît plus correcte ?

2017-08-10 08:24 UTC, pierre-24 commented
Ok, j'avais pas vu que c'était uniquement dans le cadre d'éditions. Du coup je viens de retester, QA OK :)

2017-08-10 08:24 UTC, pierre-24 approved these changes

2017-08-10 08:32 UTC, pierre-24 commented
Hop là :)

2017-08-10 08:32 UTC, merged