[WIP] Adieu npm, on passe à Yarn
zestedesavoir/zds-site pull request #4499
Opened 2017-08-08 17:50 UTC by motet-a

J’ai supprimé de la vieille doc périmée (et j’ai mis à jour un peu
moins de doc périmée).

TODO:

- [ ] Rajouter une note dans update.md

Exceptionellement, je pense qu’on peut se permettre de mettre à jour le 
`.travis.yml` plus tard parce que #4497 (TODO : Ouvrir une issue pour ne pas oublier).

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | correction de bug / nouvelle fonctionnalité / évolution
| Ticket(s) (_issue(s)_) concerné(s)  | #4498

### QA

Vérifier que tout marche bien et que la doc n’est pas trop moisie.

2017-08-08 20:07 UTC, vhf commented on doc/source/install/frontend-install.rst
> +Autrement, l'installation de ``node`` est détaillée sur le site de Node.js, soit par `téléchargement direct <https://nodejs.org/en/download/>`_, soit via un `gestionnaire de paquet <https://nodejs.or
Stp passe à node 6 minimum. Le nouveau zmarkdown requiert 6, c'est déjà ça de pris.

2017-08-08 20:07 UTC, vhf commented on doc/source/install/frontend-install.rst
> +Vous devez avoir au minimum la version 4.x.x de Node.js.
Cf. ci-dessus.

2017-08-08 20:08 UTC, vhf commented on doc/source/install/frontend-install.rst
> +    $ yarn install -g yarn
`yarn global yarn` si vraiment, mais `npm install -g yarn` suffit amplement.

2017-08-08 20:10 UTC, vhf commented on doc/source/install/frontend-install.rst
> +Pour ce qui est de Node.js, utilisez nvm si possible.
Utilisez la version disponible dans le package manager de votre OS si possible (càd si >= 6.x), `nvm` sinon.

2017-08-08 20:12 UTC, vhf commented on doc/source/utils/tox.rst
> +	flake8
Utilise le makefile stp :) Il a une commande pour ça.

2017-08-08 20:12 UTC, motet-a commented on doc/source/install/frontend-install.rst
> +    $ yarn install -g yarn
Oups, c’est une erreur. C’est `npm i -g yarn`, bien sûr !

2017-08-08 20:14 UTC, motet-a commented on doc/source/install/frontend-install.rst
> +Pour ce qui est de Node.js, utilisez nvm si possible.
Ayant personnellement un certains passé sous Debian stable où les paquets ont tendance à être vieux, je suis devenu assez (trop ?) méfiant des apt, yum et compagnie. Mais je suis d’accord.

2017-08-08 20:15 UTC, motet-a commented on doc/source/utils/tox.rst
> +	flake8
Au passage, je pense qu’il faudrait supprimmer la moitié des choses à propos de tox, ça fait complètement doublon avec le Makefile.

2017-08-08 20:53 UTC, vhf commented on doc/source/install/frontend-install.rst
> +Pour ce qui est de Node.js, utilisez nvm si possible.
Ouais je comprends les réserves, mais là le markdown c'est un requirement dur, y'a pas le choix.

Hésite pas à mettre un lien vers <https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions> s'il le faut. 6 est la LTS actuelle, dans 2 mois 8 sera LTS, c'est pas déconnant d'exiger 6 actuellement.

2017-08-08 20:53 UTC, vhf commented on doc/source/utils/tox.rst
> +	flake8
Oui volontiers !

2017-08-09 08:38 UTC, motet-a commented on doc/source/install/frontend-install.rst
> +Autrement, l'installation de ``node`` est détaillée sur le site de Node.js, soit par `téléchargement direct <https://nodejs.org/en/download/>`_, soit via un `gestionnaire de paquet <https://nodejs.or
Bon j’ai mis Node.js 8, vu que ça passe en LTS dans deux mois et que le Gulpfile actuel mache avec…

2017-08-09 08:45 UTC, motet-a commented on doc/source/utils/tox.rst
> +	flake8
Je vais supprimer purement et simplement le paragraphe (j’avais enlevé le `tox -e` parce que `flake8` va lire comme un grand ses options dans le `tox.ini`.

2017-08-09 09:40 UTC, motet-a commented on doc/source/utils/tox.rst
> +	flake8
Puis en plus, comme me l’a montré @pierre-24, tox est très contreversé depuis bien longtemps.

2017-08-09 10:54 UTC, motet-a commented
Ça y est, la CI passe.

2017-08-09 11:33 UTC, pierre-24 commented on update.md
> +TODO: Au revoir npm, on passe à yarn
Oups :p

2017-08-09 11:35 UTC, pierre-24 requested changes

2017-08-09 11:35 UTC, pierre-24 commented on doc/source/install/frontend-install.rst
> +Alternativement, l’installation de Node.js avec [nvm](https://github.com/creationix/nvm) est relativement simple. De plus, nvm permet très facilement de basculer d’une version à une autre.
Ah, le lien pour nvm n'est pas au bon format ici, c'est le format ReST qui doit être utilisé ;)

2017-08-09 11:56 UTC, pierre-24 commented on doc/source/install/frontend-install.rst
> +Si `yarn` n’est pas installé, vous pouvez le rajouter avec `npm i -g yarn`.
Redondant avec la partie juste en dessous (qui pourrait s'appeller installation et mise à jour de yarn, puisqu'on y met pas à jour node)

2017-08-09 11:56 UTC, pierre-24 approved these changes

2017-08-09 11:57 UTC, pierre-24 commented on doc/source/install/frontend-install.rst
> +Si `yarn` n’est pas installé, vous pouvez le rajouter avec `npm i -g yarn`.
(en fait si, mais pour dire "mettez à jour node de la même manière dont vous l'avez installé", donc ça pourrait aller en même temps)

2017-08-09 12:31 UTC, motet-a commented on doc/source/install/frontend-install.rst
> +Si `yarn` n’est pas installé, vous pouvez le rajouter avec `npm i -g yarn`.
Ouais en vrai je pense que la règle générale est “en cas de problème, venez sur IRC”.

2017-08-09 12:33 UTC, pierre-24 commented on doc/source/install/frontend-install.rst
> +Si `yarn` n’est pas installé, vous pouvez le rajouter avec `npm i -g yarn`.
Oui, mais on peut pas écrire ça :p

2017-08-09 12:44 UTC, AmauryCarrade commented on doc/source/install/frontend-install.rst
>  Alternativement, l’installation de Node.js avec `nvm <https://github.com/creationix/nvm`_ est relativement simple. De plus, nvm permet très facilement de basculer d’une version à une autre.
Faute de frappe, il semble manquer un `>` ici au niveau du lien.

2017-08-09 12:44 UTC, motet-a commented on doc/source/install/frontend-install.rst
>  Alternativement, l’installation de Node.js avec `nvm <https://github.com/creationix/nvm`_ est relativement simple. De plus, nvm permet très facilement de basculer d’une version à une autre.
Raaaah bien vu !

2017-08-09 12:45 UTC, motet-a commented on doc/source/install/frontend-install.rst
>  Alternativement, l’installation de Node.js avec `nvm <https://github.com/creationix/nvm`_ est relativement simple. De plus, nvm permet très facilement de basculer d’une version à une autre.
(Je ne me ferais jamais à la syntaxe de ce reStructuredText)

2017-08-09 13:08 UTC, pierre-24 commented
Voilà ;)

2017-08-09 13:08 UTC, merged