Fix 4506
zestedesavoir/zds-site pull request #4510
Opened 2017-08-11 15:46 UTC by pierre-24

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | correction de bug
| Ticket(s) (_issue(s)_) concerné(s)  | #4506

### QA

- **sur `dev`**: créer un sujet avec pour tags `c++` et `c#`. Normalement, ils devraient avoir le même slug
- Importer ma branche, faire `make migrate` et vérifier que la migration gère la duplication.
- Créer un article avec pour tag `c++` et un autre avec le tag `c#`. Les publier. Vérifier que si on utilise le tag `c++` dans la bibliothèque, on peut bien voir le contenu en question.
- Code review

2017-08-12 12:02 UTC, pierre-24 commented
*QA can start* :)

2017-08-12 12:59 UTC, vhf commented on zds/utils/models.py
> +    slug = models.SlugField(max_length=80, unique=True, db_index=True)
You can remove this one, it's already indexed. :)

2017-08-12 12:59 UTC, vhf commented on zds/utils/models.py
> +    slug = models.SlugField(max_length=80, unique=True, db_index=True)
Idem.

2017-08-12 13:00 UTC, vhf commented on zds/utils/models.py
> +    slug = models.CharField('Slug', max_length=30, unique=True, db_index=True)
Pourquoi pas `SlugField` ?

2017-08-12 13:02 UTC, vhf commented on zds/utils/models.py
> +        self.slug = uuslug(self.title, instance=self, max_length=80)
Est-ce que `save()` est aussi appelé lors d'un `update()` ?

2017-08-12 14:05 UTC, vhf approved these changes

2017-08-12 14:44 UTC, artragis requested changes
J'aime bien cette PR. Quelques modifications à ajoute mais rien de bien grave.

2017-08-12 14:44 UTC, artragis commented on zds/tutorialv2/managers.py
> +        if with_comments_count:
Un jour faudra peut être vérifier qu'on ne peut pas traduire cette requête en langage django.

2017-08-12 14:44 UTC, artragis commented on zds/tutorialv2/managers.py
> +    def last_contents(self, subcategories=None, tags=None, content_type=None, fetch_comments=True):
`fetch_comment_count` alors, non?

2017-08-12 14:44 UTC, artragis commented on zds/tutorialv2/models/models_database.py
> +        try:
je préfère l'utilisation du with pour ça. Comme on est en 2.7, on est obligé de créer notre contextmanager, mais ça donne un truc comme ça:

dans le module zds.utils
```python
from contextlib import contextmanager
 
@contextmanager
def ignore(*exceptions):
    try:
        yield
    except exceptions:
        pass
```

et à la place du try/catch
```python
with zds.utils.ignore(AttributeError):
    self.content.count_note = self.count_note
```

et plus loin, c'est pareil.

2017-08-12 14:44 UTC, artragis commented on zds/tutorialv2/views/views_published.py
> +        sub_query = """
à voir si on ne peut pas remplacer ça par un truc dans le langage django.

2017-08-12 14:44 UTC, artragis commented on zds/tutorialv2/views/views_published.py
> +            categories = ViewPublications.categories_with_contents_count(self.handle_types)
<3

2017-08-12 14:44 UTC, artragis commented on zds/utils/migrations/0014_auto_20170811_1508.py
> +        migrations.RunPython(force_unicity),
<3

2017-08-12 18:41 UTC, pierre-24 commented on zds/tutorialv2/managers.py
> +        if with_comments_count:
À priori, [on peut](https://docs.djangoproject.com/en/1.11/topics/db/aggregation/). Mais j'ai pas bien essayé, parce que je suis arrivé à rien.

2017-08-12 18:41 UTC, pierre-24 commented on zds/tutorialv2/managers.py
> +    def last_contents(self, subcategories=None, tags=None, content_type=None, fetch_comments=True):
Yep.

2017-08-12 18:46 UTC, pierre-24 commented on zds/tutorialv2/models/models_database.py
> +        try:
C'est sympa comme *trick*, ça, tient. On peut faire ça en py3, du coup ?

2017-08-12 18:52 UTC, artragis commented on zds/tutorialv2/managers.py
> +        if with_comments_count:
de même :p

2017-08-12 18:52 UTC, artragis commented on zds/tutorialv2/models/models_database.py
> +        try:
ouai, en python3 `contextlib.ignore` existe dans la lib standard.

2017-08-13 10:51 UTC, artragis approved these changes

2017-08-16 19:40 UTC, DevHugo commented
J'ai tenté de faire la QA ça ne marche pas : [http://ns531153.ip-198-100-145.net:8000/bibliotheque/?type=article](http://ns531153.ip-198-100-145.net:8000/bibliotheque/?type=article). Il génère un slug comme ceci: ?tag=c%23 et ?tag=c%2B%2B.

J'ai créé comme dans la QA deux articles, l'un avec le slug c++ et l'autre c#

2017-08-16 19:43 UTC, pierre-24 commented
Bien vu. En fait, j'ai totalement oublié de chipoter aux templates :-°

2017-08-16 20:02 UTC, pierre-24 commented
Voilà qui devrait être mieux :)

2017-08-16 21:13 UTC, DevHugo commented
Faut que je restete quoi ? tout ?

2017-08-17 05:16 UTC, pierre-24 commented
Oui :-°

2017-08-17 10:50 UTC, merged

2017-08-17 10:50 UTC, artragis commented
QA OK de mon côté (comme promis hier)