Image correcte lors de la publication sur Facebook
zestedesavoir/zds-site pull request #4531
Opened 2017-08-15 10:31 UTC by DevHugo

Facebook demande que l'attribut og:image soit présent dans la page pour récupérer l'image lors du partage. C'est conforme à la norme [opengraph](http://ogp.me/).

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | correction de bug
| Ticket(s) (_issue(s)_) concerné(s)  | https://zestedesavoir.com/forums/sujet/9136/image-illustration-lors-du-partage-dun-article-facebook/

### QA

 - Partager un article, tutoriel ou billet et vérifier que l'image est correcte.

2017-08-15 10:41 UTC, artragis requested changes
ça serait bien si tu en profitais pour appliquer la modification évoquée partout en fait.

2017-08-15 10:41 UTC, artragis commented on templates/base.html
> +    <meta property="og:image" content="https://{{ meta_image }}">
il est préférable d'utiliser `//` plutôt que https://

2017-08-15 10:41 UTC, artragis commented on templates/base.html
>      <meta property="og:image:url" content="http://{{ meta_image }}">
idem

2017-08-15 10:41 UTC, artragis commented on templates/base.html
>      <meta property="og:image:secure_url" content="https://{{ meta_image }}">
idem

2017-08-15 10:52 UTC, DevHugo commented on templates/base.html
> +    <meta property="og:image" content="https://{{ meta_image }}">
Je suis pas sur à quel point l'outil scrapper de Facebook, le gère. 

Pour l'attribut "og:image" et "og:image:url", sur la documentation, y'a écrit, "og:image - An image URL which should represent your object within the graph." mais comme il donne pas la définition d'une URL . Dans leurs exemples de présentation, il précise les http.

Pour l'attribut "og:image:secure_url", il mette clairement "An alternate url to use if the webpage requires HTTPS." donc ça me parait logique de préciser.

2017-08-15 10:56 UTC, DevHugo commented on templates/base.html
> +    <meta property="og:image" content="https://{{ meta_image }}">
J'ai trouvé dans la documentation "opengraph": 

URL | A sequence of Unicode characters that identify an Internet resource. | All valid URLs that utilize the http:// or https:// protocols

Donc ça me parait une bonne idée de le préciser.

2017-08-16 12:55 UTC, DevHugo commented
Je confirme, Facebook n'aime pas quand tu ne précise pas le protocole. 

> la valeur donnée //via.placeholder.com/350x350 pour la propriété og:image:url n’a pas pu être analysée en tant que type url.

Par-contre, il refuse d'ajouter les images si elles ont pas au moins 200px de largeur et de hauteur XD .

2017-08-16 20:22 UTC, vhf requested changes

2017-08-16 20:22 UTC, vhf commented on templates/base.html
>      <meta property="og:image:url" content="http://{{ meta_image }}">
Cette URL n'existe pas. Tout est en https.

2017-08-16 21:30 UTC, DevHugo commented
D

2017-08-16 21:30 UTC, closed without merging

2017-08-16 21:34 UTC, vhf commented
@DevHugo Est-ce qu'on peut supprimer la branche dans ce cas ?