Corrige les erreurs 500 liées à l'attribution des casquettes
zestedesavoir/zds-site pull request #4572
Opened 2017-08-22 17:36 UTC by gcodeur

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | correction de bug
| Ticket(s) (_issue(s)_) concerné(s)  | https://sentry.sandhose.fr/zeste-de-savoir/beta-backend/issues/1006/

L'erreur est causée par le fait que `unique=True` supporte mal l'UTF-8. Je l'enlève car le `get_or_create` fait déjà cette vérification. Par ailleurs, j'empêche les espaces au début et à la fin qui n'ont aucune raison d'être. ^^

### QA

- Ajouter une casquette "Staff" à un membre puis ajouter "Staff " (notez l'espace) à un autre membre. Vérifier que les deux membres reçoivent "Staff".
- Ajouter deux casquettes UTF-8 (`☆` et `♦`) à un membre et vérifier qu'elles sont correctement attribuées.
- Code review

2017-08-22 19:15 UTC, artragis requested changes

2017-08-22 19:15 UTC, artragis commented on zds/member/views.py
> +    hat_name = request.POST.get('hat', None).strip()
du coup vaut mieux remplacer le `None` par `''` sinon tu vas avoir un `AttributeError`.

2017-08-22 19:15 UTC, artragis commented on zds/utils/management/commands/add_hat_to_group.py
> +        hat_name = options['hat'].strip()
`options.get('hat', '').strip()`

2017-08-22 19:15 UTC, artragis commented on zds/utils/models.py
> +    name = models.CharField('Casquette', max_length=40)
du coup je suis pas sûr que supprimer le `unique` soit une bonne idée.

2017-08-23 17:32 UTC, gcodeur commented on zds/member/views.py
> +    hat_name = request.POST.get('hat', None).strip()
Bien vu !

2017-08-23 17:32 UTC, gcodeur commented on zds/utils/management/commands/add_hat_to_group.py
> +        hat_name = options['hat'].strip()
C'est moins important ici, mais ça vaut le coup quand même, je m'en occupe.

2017-08-23 17:34 UTC, gcodeur commented on zds/utils/models.py
> +    name = models.CharField('Casquette', max_length=40)
C'est nécessaire pour résoudre le problème des smileys (deux casquettes identiques avec un caractère UTF-8 différent).

2017-08-25 11:40 UTC, merged