Réécris le templatetag 'minute_to_duration'
zestedesavoir/zds-site pull request #4655
Opened 2017-09-22 20:52 UTC by rezemika

Ce commit réécrit le templatetag 'minute_to_duration' en utilisant 'timesince' (de base dans Django), passant ainsi de 130 lignes à 15 et rendant l'internationalisation du résultat automatique.

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | évolution
| Ticket(s) (_issue(s)_) concerné(s)  | Aucun

Étant donné qu'il s'agit d'un petit bricolage, pensez-vous que cette PR puisse être intégrée au code sans risque d'effet de bord ?

### QA

- [ ] Code relu et approuvé
- [ ] Ça fonctionne

2017-09-22 20:55 UTC, motet-a commented
> Étant donné qu'il s'agit d'un petit bricolage, pensez-vous que cette PR puisse être intégrée au code sans risque d'effet de bord ?

Faut des tests automatisés pour être à peu près tranquille :p

2017-09-23 10:15 UTC, pquentin commented
Le commit en lui-même a l'air bien si la QA confirme qu'il fonctionne.

Il faut être vigilant aux questions de fuseau horaire, il y a déjà eu [pas mal de soucis](https://github.com/zestedesavoir/zds-site/issues/3135) avec ça. En particulier quand Europe/Paris va revenir à l'heure d'hiver le mois prochain. Ceci dit l'utilisaton de `django.utils.timezone.now()` laisse penser que ce code est correct, vu qu'il va suivre la configuration Django.

2017-09-23 11:17 UTC, rezemika commented
@pquentin : Bien vu, je n'y avais pas pensé.

Cependant, vu que ZdS défini `USE_TZ = False`, `timezone.now()` retourne un datetime naïf (sans timezone). Et quand `timesince` reçoit un datetime naïf, il le compare avec un simple `datetime.datetime.now()` (voir [ici](https://github.com/django/django/blob/9718fa2e8abe430c3526a9278dd976443d4ae3c6/django/utils/timesince.py#L38-L39) et [ici](https://docs.djangoproject.com/fr/1.11/topics/i18n/timezones/)). Du coup, entre deux datetimes naïfs qui diffèrent d'une minute, on aura forcément une minute en retour. Par contre, ça risque effectivement de poser problème si on défini un jour `USE_TZ = True`. Du coup, pour éviter ce problème, je pense qu'il vaut mieux envoyer un datetime naïf dès maintenant, pour être sur qu'il sera toujours comparé à un autre datetime naïf.

Qu'en pense-tu ?

PS : Dans cette réécriture, j'arrondis le temps à 5 minutes près au delà d'une heure (contrairement aux 15 minutes de la version précédente). Je laisse ce réglage comme ça où je remets 15 minutes ?

2017-09-23 11:51 UTC, motet-a commented
Perso j’adore comment il font sur GitHub. Ils ne mettent jamais “une heure et 15 minutes”, ils mettent simplement “une heure”. Ça me semble plus pertinent sachant que c’est plus simple et qu’on se fiche un peu du nombre de minutes généralement.

2017-09-23 14:00 UTC, motet-a requested changes
Caractères invalides.

2017-09-23 14:00 UTC, motet-a commented on zds/utils/tests/test_misc.py
> +            u'1\xa0minute'
`\xa0` n’est pas un caractère unicode valide. Un espace insécable, c’est `'\xc2\xa0'` : deux octets. Mais c’est illisible, et comme les fichiers sont en UTF-8, tu peux très bien mettre un espace insécable “littéralement” : `'1 minute'`.

2017-09-23 14:13 UTC, rezemika commented on zds/utils/tests/test_misc.py
> +            u'1\xa0minute'
En effet, mais quand j'essaye comme ça, j'obtiens une erreur : 

AssertionError: u'1\xa0minute' != u'1 minute'
- 1 minute
?  ^
+ 1 minute
?  ^

Aurais-tu une idée de la cause de cette erreur ?

2017-09-23 14:37 UTC, rezemika commented on zds/utils/tests/test_misc.py
> +            u'1\xa0minute'
Autant pour moi, le caractère que j'utilisais et que je croyais être un espace insécable n'en était pas un.

2017-09-23 14:51 UTC, motet-a approved these changes

2017-09-23 14:51 UTC, motet-a commented on zds/utils/tests/test_misc.py
> +            u'1\xa0minute'
Euh en fait, je crois que j’ai raconté un peu n’importe quoi. Les chaînes `unicode` sont bien différentes des `str`, il va falloir que je révise Python :upside_down_face: Mais je pense que l’idéal est de mettre littéralement un espace insécable dans le code, rien que pour la lisibilité.

2017-09-23 18:11 UTC, pquentin commented
@rezemika Je n'ai pas vraiment d'avis sur timezone.now() vs datetime.now(). Le jour ou USE_TZ passe à True y'aura plein de soucis de toute façon j'imagine.

2017-09-29 04:14 UTC, pquentin commented on zds/utils/tests/test_misc.py
> +            self.assertEqual(remove_url_scheme(element.given), element.expected)
Tu as oublié de supprimer la ligne du dessus.

2017-10-26 14:16 UTC, rezemika commented
Je suis vraiment désolé, j'avais oublié cette PR.

2017-10-26 14:20 UTC, motet-a commented
Pas de souci @rezemika :)

2017-10-31 07:58 UTC, artragis commented on zds/utils/templatetags/minute_to_duration.py
> +    # Rounds value to avoid "1 heure, 2 minutes".
J'ai du mal à comprendre : si c'est pour éviter "il y a 1h et 2 minutes" l'encadrement ça devrait pas être : `55 < value < 65` (il y a 55 minutes et il y a 1h 5 minutes)?

2017-10-31 07:58 UTC, artragis commented on zds/utils/templatetags/minute_to_duration.py
> +    elif value > 60:
ça veut dire qu'on se donne une granularité de 1/4h?

2017-10-31 07:58 UTC, artragis commented on zds/utils/templatetags/minute_to_duration.py
> +    return filters.timesince(delta).replace(', ', _(' et '))
<3

2017-10-31 15:45 UTC, rezemika commented on zds/utils/templatetags/minute_to_duration.py
> +    # Rounds value to avoid "1 heure, 2 minutes".
En effet, au temps pour moi.

2017-10-31 15:45 UTC, rezemika commented on zds/utils/templatetags/minute_to_duration.py
> +    elif value > 60:
En effet. Ça vient de cette ligne-là : https://github.com/zestedesavoir/zds-site/blob/dev/zds/utils/templatetags/minute_to_duration.py#L86

2017-11-11 08:57 UTC, Anto59290 commented on zds/utils/templatetags/minute_to_duration.py
> +    # Rounds value to avoid "1 heure, 2 minutes".
> Rounds value to avoid "1 heure, 2 minutes".

A écrire completement en anglais du coup pour rester cohérent avec le reste ;)

2017-11-11 08:57 UTC, Anto59290 commented on zds/utils/templatetags/minute_to_duration.py
> +    elif value > 65:
Le cas où value = 65 n'est traité par aucune des conditions ?

2017-11-11 08:58 UTC, Anto59290 commented on zds/utils/tests/test_misc.py
> +            u'1 minute'
Depuis que l'on est passé à python3, nous n'avons plus besion des `u` devant les chaines de caratères ;)

2017-11-11 08:59 UTC, Anto59290 commented
@rezemika : je t'ai laissé quelques commentaire sur ton code. Tu peux aussi mettre à jour ta branche avec dev ;)

2017-11-11 11:40 UTC, rezemika commented
Merci bien ! C'est corrigé. :)

2017-11-11 14:03 UTC, Anto59290 approved these changes
Ca me semble bon :+1:

2017-11-11 14:03 UTC, Anto59290 commented on zds/utils/templatetags/minute_to_duration.py
> +    if value == 0:
Si on veut vraiment être tatillon il faudrait utiliser `<=0` ici au cas où on passerait une valeure negative (ce qui ne devrait pas arriver).

2017-11-11 16:34 UTC, rezemika commented on zds/utils/templatetags/minute_to_duration.py
> +    if value == 0:
Bonne idée en effet, je rajoute ça. :)

2017-12-16 18:52 UTC, artragis commented
si les corrections sont terminées ça serait bien de : 

- enlever le WIP
- faire un fixup des commits qui peuvent/doivent être mis ensemle.

2017-12-16 19:30 UTC, rezemika commented
Ah oui, désolé, j'avais oublié le WIP.

A priori, tous peuvent être squashés dans a9f63c5, sauf b5858da, ae745f6, 2eebfba, bbc7cbf, 092a6e7, 1c24038, 098454c, ce4d51d et 487ef5f (donc tous ceux après b5858da sauf le dernier) qui concernent les tests unitaires.

2018-01-05 15:52 UTC, Anto59290 commented on templates/tutorialv2/includes/tags_authors.part.html
> +            {% trans "Temps de lecture estimé : " %}{{ reading_time | minute_to_duration}}
Peux tu ajouter un espace entre `minute_to_duration` et `}}` pour être cohérent avec le reste du code ?

2018-01-05 15:55 UTC, Anto59290 commented on zds/utils/tests/test_misc.py
> +    def test_minute_to_duration(self):
Il y a un répertoire de test pour les templatetags. Je ne sais pas trop ce que fait la classe `TemplateTagsTest` dans ce fichier... Est ce qu'on pourrait déplacer les tests que tu ajoute dans un fichier à part dans le dossier /zds/utils/templatetags/test/ ?

2018-01-07 17:37 UTC, Anto59290 commented
J'ai testé et c'est bon pour moi :+1:

2018-01-08 08:38 UTC, merged

2018-01-08 12:09 UTC, rezemika commented
\o/ Merci !