Rends les textes incitatifs de la page bibliothèque plus punchys.
zestedesavoir/zds-site pull request #4659
Opened 2017-09-23 17:43 UTC by SpaceFox

| Q                                   | R
| ----------------------------------- | -------------------------------------------
| Type de modification                | _Wording_
| Ticket(s) (_issue(s)_) concerné(s)  | -

### QA

- Relire les modifications.
- Vérifier qu'elles s'affichent bien.

2017-09-23 18:18 UTC, motet-a requested changes
Espaces insécables :upside_down_face:

2017-09-23 18:18 UTC, motet-a commented on templates/tutorialv2/list_page_elements/call_for_helps.html
> +                <p>{% trans "Vous avez un savoir à partager ? vous vous sentez pédagogue ? Commencez donc l’écriture d’un contenu !" %}</p>
Espaces insécables avant les `?`, SVP ! Ça évite que les `?` ne se retrouvent tous seuls sur une ligne :upside_down_face:

2017-09-23 18:18 UTC, motet-a commented on templates/tutorialv2/list_page_elements/call_for_helps.html
> +                    <p>Vous pouvez dessiner (icônes, illustrations…), corriger un texte ou même devenir coauteur !</p>
Ici aussi, espaces insécables avant les `!` et les `?`.

2017-09-23 21:13 UTC, SpaceFox commented
Du coup j'ai collé des espaces insécables un peu partout.

2017-09-23 21:21 UTC, motet-a approved these changes
Du coup c’est pas très atomique et ça fait des conflits avec #4620, mais on va dire que c’est pas grave.

2017-09-23 21:25 UTC, SpaceFox commented
Ha oui, merde. Désolé, ce genre de gros merdier qui touche tout, j'ai tendance à ne pas le faire en WIP justement parce que ça fait des conflits avec l'univers entier, donc j'ai pas pensé à vérifier qu'il y avait déjà un travail dessus.

Au pire c'est 3 commits séparés, si vous voulez il suffit que je refasse une PR avec juste le premier – les deux autres, c'est un usage astucieux du rechercher/remplacer de PyCharm, c'est pas comme si c'était beaucoup de travail perdu :D

2017-09-23 22:01 UTC, motet-a commented
Nan mais c’est pas grave, [il n’y a même pas 30 lignes de conflits](https://mm.3.141.ovh/merge/8c84f0775234ef3b/a3af444caf777545).

2017-09-24 10:02 UTC, gcodeur commented
Travis a planté à cause d'une ligne [devenue trop longue](https://travis-ci.org/zestedesavoir/zds-site/jobs/279045140#L714). Reste à corriger ça et c'est bon !

2017-09-25 20:47 UTC, SpaceFox commented
Ça devrait être corrigé.

2017-09-26 20:38 UTC, gllmc approved these changes

2017-09-26 20:49 UTC, merged