Le texte de l’éditeur persiste
zestedesavoir/zds-site pull request #4660
Opened 2017-09-24 17:13 UTC by motet-a

Sauvegarde le texte de l’éditeur dans le localStorage.

Les entrées sont écrites en utilisant une sorte de cache LRU de façon
à supprimmer automatiquement les plus anciennes.

Ne fonctionne que sur les éditeurs (avec la classe `.md-editor`), ne
fonctionne pas sur tous les `<input type="text">` ou `<textarea>`.

Fix #4237.

Numéro du ticket concerné (optionnel) :  #4237

### Contrôle qualité

  1. Allez sur une page avec un (ou plusieurs) éditeur de texte ;
  2. écrivez du texte dans ces éditeurs ;
  3. naviguez, fermez l’onglet, faites ce que vous voulez ;
  4. retournez sur la page de départ, vous devriez retrouver votre texte.

2017-09-24 23:11 UTC, Situphen commented
Alors ce genre de fonctionnalités ne me dérange pas mais il faut faire attention car il y a pas mal de cas à gérer. Si c'est bien géré c'est nickel mais si c'est mal géré c'est largement pire qu'avant. Par exemple :

- Bob modifie une section d'un tutoriel et que son navigateur l'enregistre,
- Alice vient un peu plus tard et modifie la même section,
- Bob revient sur cette section et bam, la sauvegarde écrase dans l'éditeur ce qu'Alice avait écrit, Bob enregistre, cata.

Pour cette exemple il faut vérifier si l'éditeur est vide avant de mettre la sauvegarde. Voire peut-être afficher un message demandant à l'utilisateur s'il veut utiliser la sauvegarde (avec la date ?)

Il y a peut-être d'autres cas à gérer, donc prudence :)

2017-09-25 06:00 UTC, motet-a commented
Je pense pas qu’il y ai besoin d’afficher un message, mais je pense que ton exemple ferais un très bon test  e2e maintenant qu’on peut en faire avec Selenium. Je rajoute ça.

2017-09-25 21:17 UTC, motet-a commented
@Situphen Je viens de corriger ça et de rajouter [un gros test e2e](https://github.com/zestedesavoir/zds-site/pull/4660/commits/3bd77fdad22f63d7f930362624e5d99ed0500c47#diff-933246ffc9a54bcc9f8261a29356ada9R45) (vite fait) pour tester ton scénario.

2017-09-25 21:42 UTC, Situphen commented on zds/member/tests/tests_front.py
> +        selenium.get(self.live_server_url + '/membres/connexion/')
`/membres/connexion/` peut changer, utiliser `reverse('member-login')` ?

2017-09-25 21:43 UTC, motet-a commented on zds/member/tests/tests_front.py
> +        selenium.get(self.live_server_url + '/membres/connexion/')
Euh ouais, j’ai osé faire ça parce qu’il y avait la même bêtise juste au-dessus :upside_down_face:

2017-09-25 21:53 UTC, Situphen commented on zds/member/tests/tests_front.py
> +        selenium.get(self.live_server_url + '/membres/connexion/')
-1 ça t'apprendra :p

2017-10-03 18:05 UTC, gcodeur commented
Il y a un scénario que je trouve un peu gênant : si on crée un nouvel article en entrant une introduction et une conclusion, on les retrouvera la prochaine fois qu'on créera un article.

Pour gérer ça, pourquoi ne pas effacer l'enregistrement lors de l'envoi ?

2017-12-16 16:08 UTC, artragis commented
Du coup pourquoi c'est encore en wip?

2017-12-16 17:33 UTC, motet-a commented
En fait c’est juste parce que les tests que j’ai rajouté ne passent pas sur la CI pour une raison étrange. Faudrait qu’on puisse prendre un screenshot pour pouvoir débugger mais c’est compliqué :p

2017-12-18 06:55 UTC, artragis requested changes

2017-12-18 06:55 UTC, artragis commented on zds/member/tests/tests_front.py
> +        license_select.options[-1].click()
je pense qu'il te manque un `licence_select.click()` avant de cliquer sur l'option

2017-12-29 20:26 UTC, artragis commented on zds/member/tests/tests_front.py
> +        license_select.options[-1].click()
Je crois que je sais pourquoi. L'API officielle c'est `license_select.selectByIndex(len(license_select.options));`.

2018-09-12 11:46 UTC, artragis commented
Cette PR aurait mérité plus d'attention de ma part, j'ai donc repris le travail dans #5067 comme il n'y a plus qu'à modifier les tests, ça devrait aller :)

2018-09-12 11:46 UTC, closed without merging