Utilise des apostrophes typographiques dans les templates "pages/"
zestedesavoir/zds-site pull request #4682
Opened 2017-10-01 14:48 UTC by rezemika

Utilise des apostrophes typographiques dans les templates (`/pages/*` **uniquement**) à la place des `'`.

Numéro du ticket concerné : #4585 

**Nécessite de mettre à jour les fichiers de traduction pour les instances qui les utilisent.**

### Contrôle qualité

  - Vérifier que l'affichage est correct.

2017-10-03 08:34 UTC, motet-a commented
Tu t’es pas trompé dans ta regexp ? J’ai l’impression que tous les templates sont concernés, et pas que le dossier `templates/pages/`.

2017-10-03 09:01 UTC, rezemika commented
Ah non, je crois que je sais ce qui s'est passé. Comme un idiot, j'ai dû faire `git checkout -b fix-4585-pages` depuis la branche `fix-4585`, au lieu de `git checkout -b fix-4585-pages upstream/dev`. >_<

Il y a un moyen de corriger ça ?

2017-10-03 10:15 UTC, motet-a commented
@rezemika Vient sur IRC :upside_down_face:

2017-10-03 10:49 UTC, rezemika commented
Désolé, pour l'instant ça va pas être possible, je dois aller en cours. Je serai là ce soir.

2017-11-07 20:51 UTC, gllmc reviewed
Il me semble que cette PR ne corrige pas toutes les apostrophes des templates `pages/` et qu'il en reste, notamment dans ![ce fichier](https://github.com/rezemika/zds-site/blob/50ee5ff9c67b63288967147b392f464b5ab032ea/templates/pages/cookies.html). :)

2017-11-07 20:51 UTC, gcodeur commented on templates/pages/alerts.html
> +                        <td><a href="{% url 'member-detail' alert.author.username %}">{{ alert.author.username }}</a></td>
Il y a dû y avoir une erreur ici, puisque j'ai l'impression que du code a été dédoublé.

2017-11-07 21:50 UTC, rezemika commented on templates/pages/alerts.html
> +                        <td><a href="{% url 'member-detail' alert.author.username %}">{{ alert.author.username }}</a></td>
Je viens de vérifier dans la branche `dev` et je retrouve bien ces mêmes lignes ([ici](https://github.com/zestedesavoir/zds-site/blob/dev/templates/pages/alerts.html)). J'admets ne pas comprendre pourquoi elles apparaissent dans le diff...

2017-12-02 12:28 UTC, motet-a requested changes

2017-12-02 12:28 UTC, motet-a commented on templates/pages/eula.html
> +<<<<<<< a8eb1160d3039adbc79aaa2d67d5a0cf18393e52
Ah, tu as loupé une résolution de conflits :upside_down_face:

2017-12-02 12:28 UTC, motet-a commented
(Merci pour le petit rebase dans tous les cas)

2017-12-02 12:34 UTC, rezemika commented on templates/pages/eula.html
> +<<<<<<< a8eb1160d3039adbc79aaa2d67d5a0cf18393e52
Oups, en effet. Je corrige ça. :)

2017-12-02 12:57 UTC, motet-a requested changes
C’est tout bon sauf ça (je viens de tout relire à coup de `--word-diff`)

2017-12-02 12:57 UTC, motet-a commented on templates/pages/alerts.html
> +                        <td class="wide">{{ alert.get_type }}</td>
Okay donc ce bout de code semble avoir été rajouté par erreur. C’est le cas ?

2017-12-02 13:01 UTC, rezemika commented on templates/pages/alerts.html
> +                        <td class="wide">{{ alert.get_type }}</td>
Normalement, non. Je le retrouves bien sur la branche dev, ici : https://github.com/zestedesavoir/zds-site/blob/dev/templates/pages/alerts.html#L83, c'est étrange.

2017-12-02 13:10 UTC, motet-a commented on templates/pages/alerts.html
> +                        <td class="wide">{{ alert.get_type }}</td>
Hmmm je crois que tu confond avec ce qui commence à la ligne 93 :upside_down_face:

2017-12-02 13:10 UTC, motet-a commented on templates/pages/alerts.html
>                          <td class="wide">{{ alert.get_type }}</td>
C’est à partir d’ici que c’est sur la branche `dev`.

2017-12-02 18:03 UTC, rezemika commented on templates/pages/alerts.html
>                          <td class="wide">{{ alert.get_type }}</td>
Ah oui j'avais mal compris, désolé. Je croyais que c'était juste la ligne 83 qui posait problème.

2017-12-02 20:32 UTC, motet-a reviewed
Parfait !

2017-12-02 20:32 UTC, motet-a approved these changes
(Oups, j’ai misclick, je voulais approuver)

2017-12-02 20:33 UTC, merged

2017-12-02 20:33 UTC, motet-a commented
Merci !