Mise à jour du Makefile pour python3
zestedesavoir/zds-site pull request #4689
Opened 2017-10-04 13:51 UTC by naegi

Testé uniquement sur Archlinux pour le moment, nécessite d'être testé sur d'autres plateformes.
Basé sur #4676.

2017-10-06 14:42 UTC, motet-a requested changes
Petit piège avec `tox` sous Debian.

2017-10-06 14:42 UTC, motet-a commented on Makefile
> +	sudo apt-get install git python3-dev python3-setuptools libxml2-dev python3-lxml libxslt-dev libz-dev python3-sqlparse libjpeg62-turbo libjpeg62-turbo-dev libfreetype6 libfreetype6-dev libffi-dev py
Sous ma distro (Debian strech), `python3-tox` n’existe pas, c’est simplement `tox`.

2017-10-06 21:44 UTC, naegi commented on Makefile
> +	sudo apt-get install git python3-dev python3-setuptools libxml2-dev python3-lxml libxslt-dev libz-dev python3-sqlparse libjpeg62-turbo libjpeg62-turbo-dev libfreetype6 libfreetype6-dev libffi-dev py
Sous ubuntu aussi visiblement

2017-10-06 21:56 UTC, naegi commented
Pour tox, il me semble que [ça n'a pas été mis à jour](https://github.com/zestedesavoir/zds-site/blob/dev/tox.ini#L2).
Dites moi si je dis une bêtise, mais je ne pense pas quand même

2017-10-07 05:16 UTC, motet-a commented
En fait, le truc est qu’on utilise de moins en moins `tox` — je crois qu’on ne s’en sert que pour la config de `flake8` actuellement. Il faudrait sans doute faire du ménage là-dedans.

2017-10-07 16:26 UTC, naegi commented
Pourquoi ne pas supprimer tox et mettre la config de flake dans `.flake8` ?

2017-10-07 16:31 UTC, motet-a commented
Pourquoi pas :upside_down_face:

2017-10-07 16:34 UTC, naegi commented
Ok je fais ça dans une autre PR ?

2017-10-07 16:42 UTC, motet-a commented
Ouais, il vaut mieux. Il y aura peut-être des discussions là-dessus, puis il faut en plus retirer la doc qui parle de tox.

2017-10-07 16:44 UTC, naegi commented
Ok donc j'ai fini avec cette PR ci, il n'y a plus qu'à la valider

2017-10-07 16:47 UTC, motet-a reviewed
:shipit:

Ça m’a l’air bon pour Debian (et c’est assez probablement bon pour Ubuntu aussi). Pour le reste je sais pas.

2017-10-12 11:58 UTC, artragis commented
Je propose de merger. On corrigera au besoin.

2017-10-12 14:42 UTC, merged