Member refactoring
zestedesavoir/zds-site pull request #4709
Opened 2017-10-08 19:16 UTC by tleb

Suite de #4621 qui a encore des conflits avec dev, faut que je résolve ça.

Un peu toute la section membre a été impacté, c'est donc principalement du code review qui est nécessaire.

2017-10-11 13:12 UTC, gllmc requested changes
Merci pour ton travail ! J'ai relevé quelques trucs à corriger. À voir aussi ce que disent Travis et Codacy.

2017-10-11 13:12 UTC, gllmc commented on zds/member/decorator.py
> +        if profile is not None and (not profile.can_read_now() or not profile.can_write_now()):
`if profile is not None and not (profile.can_read_now() and profile.can_write_now())` ?

2017-10-11 13:12 UTC, gllmc commented on zds/member/forms.py
> +                self.field['options'].initial += option
:+1:

2017-10-11 13:12 UTC, gllmc commented on zds/member/models.py
> +        return any(g.name == settings.ZDS_APP['member']['bot_group'] for g in user_groups)
Mieux : `return self.user.groups.filter(name=settings.ZDS_APP['member']['bot_group']).exists()`. ;)

2017-10-11 13:12 UTC, gllmc commented on zds/member/models.py
> +            .count()
Pour le coup, je suis moyennement convaincu : la limite de caractères est là pour déterminer les cas qui nécessitent des retours à la ligne et les autres. Ici, ça me paraît nettement lisible.

2017-10-11 13:12 UTC, gllmc commented on zds/member/models.py
> +               (self.can_read or (self.end_ban_read and self.end_ban_read < datetime.now()))
Le `is_authenticated` me paraît inutile.

2017-10-11 13:12 UTC, gllmc commented on zds/member/models.py
> +            .filter(topicfollowed__user=self.user) \
Même remarque par rapport aux retours à la ligne.

2017-10-11 13:12 UTC, gcodeur commented on zds/member/views.py
> +        return redirect(reverse('member-detail', args=[profile.user.username]))
Je propose un truc comme ça :

```python
try:
    profile.save()
    messages.success(request, _('Le profil a correctement été mis à jour.'))
except:
    messages.error(request, _('Une erreur est survenue.'))
 return redirect(profile.get_absolute_url())
```

J'ai enlevé le `redirect(reverse('member-settings-mini-profile'))` qui est problématique étant donné qu'aucun utilisateur n'est spécifié.

Le `except` me plaît par ailleurs moyennement, on devrait spécifier les exceptions possibles ou le supprimer s'il n'y en a pas.

2017-10-11 13:12 UTC, gcodeur commented on zds/member/views.py
> +                                         for h in self.request.user.requested_hats.values_list('hat', flat=True))
En fait ici, le mieux est :

```python
context['is_required'] = HatRequest.objects \
    .filter(user=self.request.user, hat__iexact=hat.name).exists()
```

2017-10-11 13:12 UTC, gcodeur commented on zds/member/views.py
> +        if -100 < note.karma < 100:
Il y a un problème ici, tu as inversé la condition.

2017-10-12 17:41 UTC, tleb commented on zds/member/models.py
> +        return any(g.name == settings.ZDS_APP['member']['bot_group'] for g in user_groups)
Beaucoup mieux même. Faudrait que je lise la doc de Django sur les modèles un jour. :angel:

2017-10-12 17:46 UTC, tleb commented on zds/member/views.py
> +        return redirect(reverse('member-detail', args=[profile.user.username]))
D'accord avec toi à propos des `except` sans exceptions définis. Il faudrait voir les exceptions qui peuvent sortir et les mettre dans la clause du `except`.

2017-10-12 17:49 UTC, tleb commented on zds/member/views.py
> +        if -100 < note.karma < 100:
Oups. :|

2018-08-03 14:40 UTC, pierre-24 commented
Zut, c'est ireprenable, l'original a disparu :(

2018-08-03 14:40 UTC, closed without merging