Log des suppressions de contenus et de galeries
zestedesavoir/zds-site pull request #4742
Opened 2017-10-24 12:57 UTC by gcodeur

Numéro du ticket concerné (optionnel) : #4741

Fix #4741

### Contrôle qualité

- Créer un contenu.
- Le supprimer et vérifier que deux entrées de log apparaissent dans le terminal : la suppression du contenu et celle de la galerie liée.
- Créer une galerie sans contenu et la supprimer, vérifier la présence de l'entrée de log.

2017-10-24 13:48 UTC, artragis commented
lié à https://github.com/zestedesavoir/zds-site/issues/4057

2017-10-25 07:30 UTC, artragis requested changes

2017-10-25 07:30 UTC, artragis commented on zds/tutorialv2/receivers.py
> +        logger.info('{content_model} #{instance_pk} ({instance_slug}) has been deleted. User not found.'
quand on utiliser `logging` il ne faut pas utiliser `format` mais : 

```python
logger.info('%(content_model)s #%(instance_pk)d (%(instance_slug)s) has been deleted. User not found.',
                  content_model=type(instance).__name__, instance_pk=instance.pk,
                  instance_slug=instance.slug)
```
```

2017-10-25 08:50 UTC, motet-a commented on zds/tutorialv2/receivers.py
> +        logger.info('{content_model} #{instance_pk} ({instance_slug}) has been deleted. User not found.'
En fait, on peut parfaitement utiliser `str.format` dans ce cas parce que les fonctions du logger ne font aucun formattage quand il n’y a qu’un seul argument. Par exemple : 

```python
logger.info('%(a)s', a='b')  # affiche `b`
logger.info('%(a)s{}'.format('%(c)s'), a='b')  # plante parce que la chaîne de format que le logger va recevoir sera '%(a)s%(c)s' et `c` n’est pas défini, c’est un truc à ne pas faire
logger.info('%(a)s', b='c')  # plante parce que `a` n’est pas défini
logger.info('%(a)s')  # ne plante pas parce que aucun formatage n’est fait quand il n’y a qu’un seul argument, affiche `%(a)s`
logger.info('{}'.format('%(a)s'))  # pareil qu’au dessus.
```

Du coup je pense qu’il vaut même mieux utiliser `str.format` :upside_down_face:

2017-10-25 09:10 UTC, artragis commented on zds/tutorialv2/receivers.py
> +        logger.info('{content_model} #{instance_pk} ({instance_slug}) has been deleted. User not found.'
sauf que non. 

`logger.info('{}'.format('%(a)s'))  # pareil qu’au dessus, affiche `%(a)s``

applique format puis envoie dans le pipeline de loggin

alors que :   

`logger.info('%s', 'bla')`

envoie `%s` dans le pipeline de loggin et s'il y a besoin d'appliquer le format, on résoud le tout.

Du coup, la majorité du temps, comme on est plus en WARN ou en ERROR qu'en INFO ou DEBUG, les calculs nécessaire au format ne sont pas faits.

2017-10-25 09:24 UTC, motet-a commented on zds/tutorialv2/receivers.py
> +        logger.info('{content_model} #{instance_pk} ({instance_slug}) has been deleted. User not found.'
Ah, c’est vrai que le formattage du logger est sans doute plus économique au niveau des temps de calcul.

2017-10-27 10:28 UTC, motet-a approved these changes
Ça serait un chouilla mieux avec des paramètres nommés et un dict (`'%(type)s #%(pk)d (%(slug)s) has been …`), mais bon, ça passe :upside_down_face:

2017-10-27 10:41 UTC, gcodeur commented
J'ai modifié ça, c'était l'affaire de pas grand chose. :)

2017-10-27 11:59 UTC, merged

2017-10-27 12:00 UTC, motet-a commented
Bon, j’ai mergé ça vite parce qu’à mon avis c’est un truc assez important à avoir lors de la (très) prochaine version.