Facilite la mise en unes des topics et contenus
zestedesavoir/zds-site pull request #4754
Opened 2017-10-29 11:21 UTC by Anto59290

Ce commit facilite la mise en Unes des topics et contenus, ticket #4753 

### Contrôle qualité

- Aller sur un contenu publié en tant que staff, vérifier que vous pouvez mettre le contenu en une depuis la sidebar. Le formulaire est automatiquement remplit
- Idem pour un topic

Bonne QA !

2017-10-29 13:34 UTC, motet-a commented on templates/forum/topic/index.html
> +{% load append_query_params %}
Inutilisé ?

2017-10-29 13:43 UTC, motet-a commented on zds/featured/tests.py
> +        self.assertContains(response, _(u'Le contenu est introuvable'))
Pas besoin du préfixe `u` parce que Python 3 :upside_down_face:

2017-10-29 13:43 UTC, motet-a commented on zds/featured/views.py
> +    get_initial_error_message = _(u'Le contenu est introuvable')
Pas besoin du préfixe `u` parce que Python 3 :upside_down_face:

2017-10-29 14:51 UTC, Anto59290 commented
Merci @motet-a 
Pour une raison que j'ignore, les tests passent chez moi mais échouent sur la CI :thinking:

2017-11-04 15:26 UTC, motet-a commented on zds/featured/tests.py
> +        self.assertEqual(initial_dict['authors'], '{}, {}'.format(author.__str__(), author2.__str__()))
`'{}, {}'.format(author, author2)` ne marche pas ?

2017-11-04 15:32 UTC, motet-a commented
Je comprends pas pourquoi tu utilises directement les propriétés `.__str__()`. D’autant que je sache, en Python, il vaut mieux utiliser utiliser le type `str()` comme une fonction pour faire ça. Et de manière générale, il ne me semble pas que les propriétés dont les noms sont entourés de `__` sont faites pour être utilisées directement.

2017-11-04 15:34 UTC, motet-a commented on zds/featured/views.py
> +        except PublishedContent.DoesNotExist:
Ça serait bien de remonter le `except` pour “encadrer” juste la ligne qui risque de `raise`. C’est une bonne pratique.

2017-11-04 15:36 UTC, motet-a commented on zds/featured/views.py
> +        except Topic.DoesNotExist:
Ici aussi, j’imagine que le seul truc qui risque de `raise` est le `Topic.objects.get(id=topic_id)`. Ça serait mieux d’encadrer exactement cette ligne avec le `try … except`.

2017-11-04 19:39 UTC, motet-a reviewed
Il y a du mieux ! :upside_down_face:

2017-11-04 19:39 UTC, motet-a commented on zds/featured/views.py
> +    def get_inital_content_data(self, content_id):
J’écrirais cette fonction comme ça en fait : 

```python
    def get_inital_content_data(self, content_id):
        try:
            content = PublishedContent.objects.get(id=content_id)
        except PublishedContent.DoesNotExist:
            messages.error(self.request, self.get_initial_error_message)
            return None

        displayed_authors = ', '.join([str(x) for x in content.authors.all()])
        image_url = content.content.image.physical.url if content.content.image else None
        
        return {
            'title': content.title(),
            'type': self.displayed_content_type[content.content_type],
            'authors': displayed_authors,
            'url': self.request.build_absolute_uri(content.content.get_absolute_url_online()),
            'image_url': image_url,
        }
```

C’est plus court, il y a moins de variables et c’est moins indenté : Moins de risques d’erreurs. Jettes un coup d’œuil aux concepts comme l’*[early return](http://blog.timoxley.com/post/47041269194/avoid-else-return-early)*. Je trouve ça vraiment bien dans des langages commes Python (après, dans d’autres langages plutôt *fonctionnels*, c’est une autre histoire).

2017-11-04 19:39 UTC, motet-a commented on zds/featured/views.py
> +    def get_initial(self):
Pareil dans cette fonction. La variable `content_data` est bizarrement assignée à `None` puis réassignée ensuite mais pas dans tous les cas, si tu vois ce que je veut dire. Ça serait top d’éviter ça :upside_down_face:

2017-11-04 19:39 UTC, motet-a commented on templates/forum/topic/index.html
> +                        {% trans "Ajouter en une" %}
Manque 4 espaces

2017-11-04 19:39 UTC, motet-a commented on templates/tutorialv2/view/content_online.html
> +                            class="ico-after star blue">
Perso je réindenterai le `class=` au même niveau que le `href=` de la ligne d’avant.

2017-11-04 21:11 UTC, motet-a commented
Ben… pourquoi tu fermes @Anto59290 ?

2017-11-04 21:17 UTC, Anto59290 commented on zds/featured/views.py
> +    def get_inital_content_data(self, content_id):
Perso je suis plutôt contre l'early return. Je dirais même qu'en python on évite d'avoir plusieurs return par fonction (dans la mesure du raisonnable). Pour moi ça rend la lecture du code, le suivi de ce qui est fait beaucoup plus compliqué

2017-11-04 21:46 UTC, sandhose commented on zds/featured/views.py
> +    def get_inital_content_data(self, content_id):
typo `s/inital/initial/` ; dans la fonction au dessus aussi

2017-11-04 21:50 UTC, sandhose commented on zds/featured/views.py
> +    def get_inital_content_data(self, content_id):
Je suis assez d'accord que dans ce cas la, un early return est plus lisible qu'une fonction où tu dois mapper en tête l'état de deux variables avec l'indentation en plus qui va avec

2017-11-07 20:20 UTC, gllmc requested changes
Merci pour cette PR ! Il y a quelques trucs à corriger, mais sinon c'est bon. :)

2017-11-07 20:20 UTC, gcodeur commented on templates/tutorialv2/view/content_online.html
> +                            <a href="{% url "featured-resource-create" %}?content_type=published_content&content_id={{ content.pk }}"
`&amp;`

2017-11-07 20:20 UTC, gcodeur commented on templates/forum/topic/index.html
> +                        <a href="{% url "featured-resource-create" %}?content_type=topic&content_id={{ topic.pk }}" class="ico-after star blue">
`&amp;`

2017-11-07 20:20 UTC, gcodeur commented on zds/featured/views.py
> +            content = PublishedContent.objects.get(id=content_id)
Attention, dans le template, c'est l'ID du `PublishableContent` qui est utilisé. Par ailleurs, il vaut mieux utiliser `pk` plutôt que `id`.

2017-11-07 20:20 UTC, gcodeur commented on zds/featured/views.py
> +    get_initial_error_message = _('Le contenu est introuvable')
Je me trompe peut-être, mais `get` me semble plus indiqué pour les noms de méthodes (exemple de la différence entre `success_url` et `get_success_url`). Ici, tu peux simplement mettre `initial_error_message`

2017-11-07 20:20 UTC, gcodeur commented on zds/featured/views.py
> +        if content:
Le mieux est d'utiliser `else` ici, je pense.

2017-11-07 20:20 UTC, gcodeur commented on zds/featured/views.py
> +        except Topic.DoesNotExist:
Ici, je pense que tu pourrais mettre un `int` sur `topic_id` et ajouter `ValueError` aux exceptions attrapées.

2017-11-07 20:20 UTC, gcodeur commented on zds/featured/views.py
> +        except PublishedContent.DoesNotExist:
Idem ici pour `int` sur `content_id` et `ValueError`.

2017-11-09 07:53 UTC, Anto59290 commented on zds/featured/views.py
> +            content = PublishedContent.objects.get(id=content_id)
Est ce que tu es sur à propos du PublishableContent. Si je regarde la bonne vue ça se trouve ici : https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/published.py#L59 

Dans le template content_online.html on utilise parfois publishablecontent, ce qui laisse croire que content est de type PublishedContent, mais je ne suis pas sur de mon coup

2017-11-09 07:59 UTC, motet-a commented on templates/forum/topic/index.html
> +	    </ul>
Indentation

2017-11-09 07:59 UTC, motet-a commented on zds/featured/views.py
> +            content_data = None
Pareil, je ne vois pas à quoi sert `content_data`.

2017-11-09 07:59 UTC, motet-a commented on zds/featured/views.py
> +            content_data = None
Je ne vois pas à quoi sert cette variable `content_data`. Autant retourner directement, non ?

2017-11-09 08:07 UTC, Anto59290 commented on zds/featured/views.py
> +            content_data = None
Personellement je trouve ça pas top de mettre des return en plein milieu des méthodes. Je trouve que ça rend la lecture du code plus complexe, notamment pour savoir quel return est utilisé dans quel cas

2017-11-09 15:41 UTC, artragis commented on zds/featured/views.py
> +            content_data = None
c'est juste que pour le coup on n'a pas fait de return early. Ça peut être bien d'en profiter pour corriger ça.

2017-11-09 15:43 UTC, Anto59290 commented on zds/featured/views.py
> +            content_data = None
@artragis : par "corriger ça" tu veux dire faire un return None ? Sinon je ne comprend pas ce que tu veux dire ;)

2017-11-09 15:47 UTC, artragis commented on zds/featured/views.py
> +            content_data = None
oui ici je pense que c'est ce qui est désiré.

notons que ce n'est pas en soit une erreur. C'est juste qu'on n'a jamais été cohérent sur la manière de faire en ce qui concerne le return early. Ces derniers temps il y a une volonté de mettre en place cette technique dès que possible.

personnellement, je préfère une solution mixte qui consiste à faire un return quand une valeur qui ne permet pas le calcul est rencontré mais de préférer un flot plus plat quand on est dans le reste de la fonction. Mais les discussions sur IRC semblent s'être tournée sur la solution "une règle simple : on retourne dès que possible".

2017-11-09 15:50 UTC, Anto59290 commented on zds/featured/views.py
> +            content_data = None
Ok, si c'est ce qui est voulu ;) Je suis pas adepte de la pratique, mais je metterai le code à jour pour que ça reste en "cohérence" (autant que possible) avec ce qui existe / ce qui est voulu

2017-11-09 20:10 UTC, gcodeur commented on zds/featured/views.py
> +            content = PublishedContent.objects.get(id=content_id)
En fait, c'est plus compliqué que je ne le croyais, ça se passe [ici](https://github.com/zestedesavoir/zds-site/blob/232d36c5507adec4f3baaf044fff08bdbaebc303/zds/tutorialv2/mixins.py#L448) et c'est un objet utilisant des infos issues de la base et du repo git.

Par contre, je confirme que le `pk` de cet objet est celui du `PublishableContent`. Si tu regardes ailleurs dans le template, il est utilisé comme tel et je me suis pris une 404 en testant ta PR (et ça marchait en changeant pour le bon `pk`).

2017-11-09 20:16 UTC, gcodeur commented on zds/featured/views.py
> +        return initial
Là aussi, je pense que tu peux éviter de faire des assignations à `None`. Ça pourrait donner un truc comme ça :

```python
initial = super(FeaturedResourceCreate, self).get_initial()
content_type = self.request.GET.get('content_type', None)
content_id = self.request.GET.get('content_id', None)
if content_type == 'topic' and content_id:
    initial.update(**self.get_initial_topic_data(content_id))
elif content_type == 'published_content' and content_id:
    initial.update(**self.get_initial_content_data(content_id))
return initial
```

Du coup, il faudrait retourner un dictionnaire vide dans les deux autres méthodes plutôt que `None`.

2018-01-01 17:29 UTC, gcodeur commented on zds/featured/views.py
> +            content = PublishedContent.objects.get(pk=int(content_id))
Il y a toujours un problème de `pk` ici car ta requête se base sur celui du `PublishedContent` et les URL dans les pages de contenus utilisent celui du `PublishableContent`.

Pour fixer le problème, il suffit de remplacer cette ligne par quelque chose comme :

```diff
- PublishedContent.objects.get(pk=int(content_id))
+ PublishedContent.objects.get(content__pk=int(content_id))
```

2018-01-01 18:22 UTC, gllmc approved these changes
LGTM, merci !

2018-01-01 18:22 UTC, merged