Corrige le lien sur les tags pour les billets dans la page de recherche
zestedesavoir/zds-site pull request #4760
Opened 2017-10-30 07:35 UTC by Anto59290

Corrige le lien sur les tags pour les billets dans la page de recherche, aka #4409 

### Contrôle qualité

- Publiez un billet avec un tag
- Indexez votre contenu, recherchez votre billet dans la recherche
- Le billet appairait et le tag amène bien vers la page des billets et non pas vers les contenus/bibliothèque

2017-11-05 09:21 UTC, motet-a requested changes
Indentation :upside_down_face:

2017-12-10 17:25 UTC, gllmc submitted a review, later dismissed
~~Bon pour moi, à rebase/merge.~~

Edit : erreur de ma part, l’indentation n'est pas complètement corrigée. ;)

2018-01-01 17:13 UTC, gcodeur commented on templates/searchv2/includes/publishedcontent.part.html
> +                {% endif %}
Il reste un problème d'indentation ici, il y a un espace en plus sur le `{% else %}` par rapport au `{% endif %}`.

2018-01-01 17:15 UTC, gllmc approved these changes
LGTM

2018-01-01 17:16 UTC, Anto59290 commented on templates/searchv2/includes/publishedcontent.part.html
> +                {% endif %}
En fait j'ai fait un premier merge dans l'interface de Gihub, mais c'est pas possible d'indenter correctement. Donc j'ai fini par pull / commit / push. Tu a été plus rapide qu'un ninja :D

2018-01-01 19:41 UTC, merged