Refactor zds/tutorialv2/models/__init__.py
zestedesavoir/zds-site pull request #4762
Opened 2017-10-30 10:01 UTC by motet-a

Renomme certaines variable que je trouvais bizarrement nommées.

2017-10-30 17:10 UTC, gllmc reviewed
Merci pour ce refactoring, les noms des variables sont en effet bien plus cohérents !

2017-10-30 17:10 UTC, gcodeur commented on zds/utils/models.py
> +    ] + TYPE_CHOICES
Pourquoi utiliser une liste plutôt qu'un tuple ?

2017-10-30 17:10 UTC, gcodeur commented on zds/tutorialv2/models/__init__.py
> +]
J'avoue que je suis moyennement convaincu par le passage des compréhensions de liste sur plusieurs lignes. Je trouve que c'est largement lisible sur une ligne avec la limite des 120 caractères.

2017-10-30 17:13 UTC, motet-a commented on zds/tutorialv2/models/__init__.py
> +]
Oh pas de souci, je remet comme c’était avant :upside_down_face: 

(J’ai passé de longues années bloqué à la colonne 79 et j’ai un peu du mal à m’y défaire)

2017-10-30 17:16 UTC, motet-a commented on zds/utils/models.py
> +    ] + TYPE_CHOICES
Parce qu’avant c’était un tuple litéral dans les réglages et que j’ai changé ça en liste et qu’on ne peut pas concaténer facilement un tuple avec une liste avec l’opérateur `+`.

Puis j’imagine qu’en termes de performances, la différence entre un tuple et une liste est négligeable dans ce cas.

2017-11-04 09:45 UTC, gllmc requested changes
N'oublie pas de générer les migrations avec `python manage.py makemigrations`, elles sont manquantes. ;)

@artragis : tu as mis un :-1: plus haut, pourquoi ?

2017-11-04 10:36 UTC, motet-a commented
@gcodeur C’est fait, mais là je ne comprends pas du tout pourquoi il y aurait besoin de migrations. Je n’ai pas touché au modèle, non ?

2017-11-04 10:37 UTC, motet-a commented
Ah, je viens de comprendre. C’est une histoire de majuscules.

2017-11-04 11:52 UTC, gllmc approved these changes

2017-11-10 18:52 UTC, merged