Explicite l'utilisateur qui résoud un sujet
zestedesavoir/zds-site pull request #4778
Opened 2017-11-07 06:47 UTC by Anto59290

Explicite l'auteur de la mise en résolu d'un sujet sur le forum, ticket #4776 

### Contrôle qualité

  - Sur le forum, résoudre un sujet avec un auteur. Le message classique est bien affiché
  - Résoudre avec un membre du staff le sujet d'un membre classique le nouveau message avec le nom du modérateur est indiqué.

En ce qui concerne le code on a plusieurs options:
- Soit on laisse is_solved et solved_by, mais ça fait un peu doublon
- Soit on remplace is_solved par solved_by et dans la migration on considère que tous les sujets ont étés résolus par leurs auteurs (à defaut d'avoir la vrai information). Je pense que c'est plus propre (une seule info en base pour savoir si le sujet est résolu et par qui). Est ce que ça vous va ?

2017-11-07 19:57 UTC, gcodeur commented
> Soit on remplace is_solved par solved_by et dans la migration on considère que tous les sujets ont étés résolus par leurs auteurs (à defaut d'avoir la vrai information). Je pense que c'est plus propre (une seule info en base pour savoir si le sujet est résolu et par qui). Est ce que ça vous va ?

Je suis favorable à cette solution. Par contre, pense bien à gérer la désinscription en transférant la résolution de sujets au compte anonyme. ;)

2017-11-10 18:17 UTC, gllmc requested changes
Merci ! J'ai relevé quelques points à corriger.

2017-11-10 18:17 UTC, gllmc commented on templates/forum/topic/index.html
> +                        Ce sujet a été résolu par <a href="{{ url_member_detail }}">{{ username }}</a>
Je trouve ça assez peu clair. Je verrais plus un truc comme `[user] a marqué ce sujet comme résolu`. Par ailleurs, mets un point à la fin de la phrase. ;)

2017-11-10 18:17 UTC, gllmc commented on templates/forum/topic/index.html
> +            {% if user == topic.author or topic.solved_by == topic.author %}
Attention ici, si je résous un sujet de `user` en tant que `admin`, `user` verra qu'il a lui-même résolu son sujet à cause du premier test.

2017-11-10 18:17 UTC, gllmc commented on zds/forum/admin.py
> +    list_display = ('title', 'author', 'forum', 'pubdate')
Je pense que ce serait pas mal d'avoir `solved_by` ici.

2017-11-10 18:17 UTC, gcodeur commented on zds/forum/migrations/0016_topic_solved_by.py
> +        migrations.RunPython(forward, backward),
L'argument `reverse_code` est [facultatif](https://docs.djangoproject.com/fr/1.11/ref/migration-operations/#django.db.migrations.operations.RunPython), tu peux l'enlever et supprimer la fonction `backward`.

2017-11-10 18:17 UTC, gcodeur commented on templates/forum/topic/index.html
> +                {% if is_solved %}
`topic.is_solved` ?

2017-11-10 19:26 UTC, Anto59290 commented on zds/forum/migrations/0016_topic_solved_by.py
> +        migrations.RunPython(forward, backward),
Oui, mais ça rend la migration non reversible. C'est une bonne pratique de garder les migrations réversibles. Par exemple sur ta machine de test ça te permet d'appliquer ma migration, puis de la revert, puis de tester une autre PR sans avoir à toucher directement à ta BDD ;)

2017-11-10 19:30 UTC, Anto59290 commented on templates/forum/topic/index.html
> +            {% if user == topic.author or topic.solved_by == topic.author %}
Bien vu ;)

2017-11-10 19:55 UTC, Anto59290 commented on zds/forum/admin.py
> +    list_display = ('title', 'author', 'forum', 'pubdate')
On peut, mais sauf erreur de ma part ça va rajouter une requête SQL par sujet résolu dans l'interface d'administration. Si on fait ça l'admin de django peut très vite devenir très lent ;)

2017-11-10 21:49 UTC, gcodeur commented on zds/forum/admin.py
> +    list_display = ('title', 'author', 'forum', 'pubdate')
De mémoire (il me semble que j'avais testé ça), l'admin Django est "intelligente" et ajoute automatiquement les jointures appropriées.

2017-11-11 07:56 UTC, Anto59290 commented on zds/forum/admin.py
> +    list_display = ('title', 'author', 'forum', 'pubdate')
J'ai fait le test chez moi à l'aide de la django debug toolbar et le noombre de requêtes augmente bien. Dans mon test je suis passé de 6 à 9 pour 3 sujets résolus.

2017-11-11 09:27 UTC, motet-a commented on zds/forum/admin.py
> +    list_display = ('title', 'author', 'forum', 'pubdate')
Okay mais du coup c’est limité par la pagination ou pas ?

2017-11-11 09:40 UTC, Anto59290 commented on zds/forum/admin.py
> +    list_display = ('title', 'author', 'forum', 'pubdate')
Oui.  Il me semble que l'admin de Django pagine par 100 par défaut. Donc potentiellement ça pourra engendrer 100 requêtes supplémentaires (si tous les sujets de la page sont résolus)

2017-11-11 14:35 UTC, gcodeur commented on zds/forum/admin.py
> +    list_display = ('title', 'author', 'forum', 'pubdate')
Ok, dans ce cas, inutile de chercher à le rajouter (l'admin Django étant en plus très peu utilisée).

2017-11-11 14:39 UTC, gcodeur commented
Alors, QA presque OK, il reste un problème qui risque d'être complexe à corriger : si je suis `user`, que `admin` résout mon sujet, que j'annule la résolution puis que je le résous à nouveau (sans quitter la page), je verrai `admin a marqué` car le texte aura été chargé avec la page.

La meilleure solution me paraît être de simplifier un peu les conditions dans le template et de modifier  le JS pour que lorsqu'on résout un sujet, le texte soit remplacé par `Vous venez de marquer ce sujet comme résolu.`.

2017-11-16 20:04 UTC, gllmc approved these changes
LGTM, merci !

2017-11-16 20:05 UTC, merged