Add ALLOWED_HOSTS to dev settings.
zestedesavoir/zds-site pull request #4806
Opened 2017-12-05 10:52 UTC by informaticienzero

| Q                             | R
| ----------------------------- | -------------------------------------------
| Correction de bugs ?          | [oui]
| Nouvelle Fonctionnalité ?     | [non]
| Tickets (_issues_) concernés  | [#4805]

J'ai rajouté localhost et 0.0.0.0 comme autorisés dans le tableau `ALLOWED_HOSTS `.

### Contrôle qualité

Rien à signaler de particulier.

2017-12-06 15:40 UTC, motet-a requested changes
> When DEBUG is True and ALLOWED_HOSTS is empty, the host is validated against ['localhost', '127.0.0.1', '[::1]'].

Je ne suis pas (du tout) spécialiste en réseau mais je ne vois pas pourquoi ton serveur n'écoute pas sur une adresse normale comme 127.0.0.1 ou ::1. Écouter sur 0.0.0.0, ça veut dire écouter sur toutes les adresses : je ne vois pas pourquoi faire ça.

(Ah, si jamais tu as vraiment besoin d'écouter sur une adresse fantaisiste juste pour chez toi, tu peux facilement changer ça en faisant un autre fichier de config. Hésite pas à me demander si tu veux en savoir plus)

2017-12-06 19:14 UTC, AmarOk1412 requested changes
@motet-a Le seul scénario que je vois c'est si tu développes depuis une autre machine pour debug a distance. Mais dans tous les cas, c'est pas un cas à prévoir de base et je suis aussi contre.

2017-12-06 21:11 UTC, motet-a commented
(En fait, en me relisant, je viens de voir que mon précédent commentaire est un peu faux puisque `ALLOWED_HOSTS` spécifie les *hostnames* acceptés par le serveur, et c’est complètement indépendant de l’addresse IP sur laquelle le serveur écoute. Mais ça ne change pas mon point de vue.)

Mais encore une fois @informaticienzero, n’hésite pas à détailler ton problème et/ou ton cas d’usage, éventuellement sur [IRC](https://riot.im/app/#/room/#freenode_#zds-dev:matrix.org). Ça m’intéresse :slightly_smiling_face:

2017-12-07 08:57 UTC, informaticienzero commented
Je n'y connais pas grand chose avec Django, je viens de commencer sérieusement. Pour détailler mon problème, j'ai tout simplement suivi les instructions d'installation et la commande de lancement `make run-back`. 

Quand j'ai lancé, j'ai eu l'erreur remontée dans l'issue #4805. J'ai donc ajouté `localhost` et `0.0.0.0` dans les `ALLOWED_HOSTS`, mais je me rend compte en fait que seul `localhost` est nécessaire. 

Du coup, on rejette cette PR et j'en fais une nouvelle pour n'ajouter que `localhost` ? Ou bien cette configuration n'est pas nécessaire et je n'ai besoin de rien de tout ça et j'ignore l'erreur ?

2017-12-07 09:32 UTC, motet-a commented
Hum, le problème vient plutôt du Makefile à mon avis. Je pense qu'il devrait écouter sur `localhost`.

(En fait, moi j'utilise directement `./manage.py runserver`, ça écoute sur `localhost` comme il faut)

2017-12-07 10:13 UTC, informaticienzero commented
Dans ce cas, je propose qu'on rejette cette PR et j'en fais une autre qui modifie le makefile pour écouter sur `localhost`.

2017-12-07 18:31 UTC, AmarOk1412 commented
C'est en effet la meilleure solution je pense. Je me permet de fermer cette PR.

2017-12-07 18:31 UTC, closed without merging