Améliore le templatetag date
zestedesavoir/zds-site pull request #4815
Opened 2017-12-16 19:19 UTC by rezemika

Ce commit améliore le templatetag `date` en évitant la création d'une nouvelle instance de `datetime` et en utilisant la fonction `get_current_timezone()` de Django. J'ai suggéré cette modification pour le ticket #4811, mais vu que ça n'a pas de lien direct avec Django 1.11, j'ai fais une PR séparée.

### Contrôle qualité

- Vérifier que les dates s'affichent toujours correctement.

2017-12-17 18:50 UTC, artragis requested changes

2017-12-17 18:50 UTC, artragis commented on zds/utils/templatetags/date.py
> +        now = datetime.now(get_current_timezone())
je pense que ceci n'est pas vraiment désiré;

2018-01-07 23:08 UTC, rezemika commented on zds/utils/templatetags/date.py
> +        now = datetime.now(get_current_timezone())
Désolé pour le retard, j'avais lu la notif' et ça m'est sorti de la tête.

Que fait la fonction / classe `LocalTimezone()` en fait ? Le problème avec elle est qu'elle n'est apparemment plus disponible avec Django 1.11+.

2018-01-11 10:03 UTC, Anto59290 commented on zds/utils/templatetags/date.py
> +        now = datetime.now(get_current_timezone())
Je pense qu'il faut utiliser `django.utils.timezone.get_default_timezone` ;)

Cf. https://docs.djangoproject.com/en/1.7/_modules/django/utils/tzinfo/

2018-01-11 10:03 UTC, Anto59290 commented on zds/utils/templatetags/date.py
> +
Les espaces sont a éviter :)

2018-01-11 12:33 UTC, rezemika commented on zds/utils/templatetags/date.py
> +        now = datetime.now(get_current_timezone())
D'accord, merci @Anto59290 ! :)

2018-01-11 19:34 UTC, artragis approved these changes

2018-01-28 13:03 UTC, merged