[Feedback] Refactorise la fonction "login_view()" et rend les messages d'erreurs plus précis
zestedesavoir/zds-site pull request #4822
Opened 2017-12-28 22:16 UTC by rezemika

Cette modif' a été discutée [sur le forum](https://zestedesavoir.com/forums/sujet/9899/les-identifiants-fournis-ne-sont-pas-valides/) mais le topic semble au point mort. Je propose donc cette PR, à débattre pour savoir si on la garde ou pas. :)

Ce commit change la manière dont la fonction gère les erreurs pour la rendre un peu plus lisible.
Il rend aussi les messages d'erreur plus précis.

Avant, quand les identifiants fournis étaient invalides, seul "Les identifiants fournis ne sont pas valides." était indiqué. Désormais, le message est soit "Nom d’utilisateur inconnu.", soit "Mot de passe incorrect.".

### Contrôle qualité

  - Essayer de se connecter avec :
    - un pseudo et un MDP valides ;
    - un pseudo valide et un mauvais MDP ;
    - un pseudo inconnu.

2017-12-29 07:10 UTC, Anto59290 commented
J'ai relu rapidement depuis mon téléphone et j'ai l'impression qu'il manque les tests qui vont bien pour les différents cas.

Note: ce n'est pas la faute de cette PR en particulier, mais ne faudrait-il pas gérer ces erreurs dans la validation du formulaire plutôt que dans la vue ?

2017-12-29 09:00 UTC, motet-a reviewed
:+1:

2017-12-29 09:00 UTC, motet-a commented on zds/member/views.py
> +        else:
Ça serait mieux avec un `return` ici pour éviter d’indenter tout le `else` : https://softwareengineering.stackexchange.com/a/18459

2017-12-29 09:00 UTC, motet-a commented on zds/member/views.py
> +                messages.error(request, _('Nom d\'utilisateur inconnu.'))
Ça serait mieux avec une apostrophe : `_('Nom d’utilisateur inconnu.')`

2018-01-01 17:46 UTC, gcodeur commented
Merci pour cette PR !

Je pense que ce serait bien d'utiliser des phrases un peu moins "brutales".  Je pense à quelque chose comme :

- "Ce nom d'utilisateur est inconnu. Si vous ne possédez pas de compte, vous pouvez vous inscrire."
- "Le mot de passe saisi est incorrect. Cliquez sur le lien « Mot de passe oublié ? » si vous l'avez oublié."

2018-01-02 11:40 UTC, gllmc requested changes

2018-01-02 11:40 UTC, gcodeur commented on zds/member/views.py
>          password = request.POST['password']
Pour éviter les erreurs 500, remplace ces deux lignes par quelque chose comme :

```diff
- username = request.POST['username']
- password = request.POST['password']
+ username = request.POST.get('username', '')
+ password = request.POST.get('password', '')
```

Toutefois, je pense que le plus propre est d'utiliser une vraie validation de formulaire pour éviter ces problèmes (avec `form.is_valid`), qui vérifiera que le contenu des champs est normal (pas que les identifiants sont corrects). Le [tutoriel Django](https://zestedesavoir.com/tutoriels/598/developpez-votre-site-web-avec-le-framework-django/265_des-outils-supplementaires/1531_les-utilisateurs/#2-4982_passons-aux-vues) fait les choses assez bien, même s'il faut ensuite l'adapter à notre code.

2018-01-02 12:44 UTC, artragis commented on zds/member/views.py
>          password = request.POST['password']
+ 1 pour l'utilisation de form.is_valid() et `form.cleaned_data['username']`

2018-01-03 17:19 UTC, rezemika commented
J'ai essayé de réécrire la fonction en utilisant `is_valid()`, mais pour une raison que j'ignore, cette condition n'est pas validée alors que le dictionnaire `form.errors` est vide. Voilà le code : https://gist.github.com/rezemika/769685937b726c857fd998a69bca4c5b

Est-ce que l'un d'entre-vous aurait une idée de ce qui peut causer ça ?

2018-01-04 07:36 UTC, Anto59290 commented
Est ce que tu es sur que ton formulaire contient des données, cf. [ce cas particulier ](https://docs.djangoproject.com/fr/2.0/ref/forms/api/#django.forms.Form.non_field_errors) ?

2018-01-04 12:07 UTC, rezemika commented
@Anto59290 : Bonne idée, ça semble correspondre. Pourtant, quand je fais `print(request.POST)`, j'ai ceci qui s'affiche : `<QueryDict: {'csrfmiddlewaretoken': ['SAJTAu2TUTVKH3iJ3y13xwsjBiO3AROUI1HdpP9H0iOxcTYpnUcwVHnUzJ65kgGg'], 'password': ['admin'], 'username': ['admin'], 'remember': ['on']}>`.

Même quand je fais `form = LoginForm({'username':'admin', 'password':'admin', 'remember':'on'})`, `form.is_valid()` renvoie `False` et `form.errors` est toujours vide.

2018-01-08 13:00 UTC, Anto59290 commented
@rezemika : Si tu inspecte le contenu de form tu verra qu'il est bien vide pas de données : 

```py
In [10]: form.__dict__
Out[10]: 
{'_bound_fields_cache': {},
 '_errors': {},
 'auto_id': 'id_%s',
 'data': {},
 'empty_permitted': False,
 'error_class': django.forms.utils.ErrorList,
 'fields': OrderedDict([('username',
               <django.forms.fields.CharField at 0x7f16326f4160>),
              ('password', <django.forms.fields.CharField at 0x7f16325f75c0>),
              ('remember',
               <django.forms.fields.BooleanField at 0x7f16325f7668>)]),
 'files': {},
 'helper': <crispy_forms.helper.FormHelper at 0x7f16325f7898>,
 'initial': {},
 'is_bound': False,
 'label_suffix': '\xa0:'}

```

Pour l'initialiser je dirais qu'il faut faire `form = LoginForm(data=request.POST)` à la  place de `form = LoginForm(request.POST)`

2018-01-08 14:38 UTC, rezemika commented
@Anto59290 : tu as raison, il suffisait d'un `LoginForm(data=request.POST)`, merci ! :)

(C'est quand même bizarre, ça n'apparait même pas sur [la page de doc](https://docs.djangoproject.com/fr/1.10/topics/forms/#the-view) de Django...)

2018-01-08 15:03 UTC, Anto59290 commented
Je ne suis pas 100% sur, mais je pense que c'est à cause de la [signature de cette méthode](https://github.com/rezemika/zds-site/blob/58d00c937ed39e40d2ef1f731005a9e4cb417f0a/zds/member/forms.py#L57). Je me demande si ton request.POST n'était pas assigné au paramètre next. En nommant le paramètre on contourne le problème.

2018-01-08 15:21 UTC, rezemika commented
Ah, bien vu ! Je pense que tu as raison. Du coup, on pourrait peut-être faire quelque chose comme ça, vu que le paramètre `next` n'est pas utilisé dans la méthode. Qu'en pense-tu ?

```python
def __init__(self, *args, **kwargs):
    kwargs.pop('next', None)
    super(LoginForm, self).__init__(*args, **kwargs)
    # etc
```

2018-01-08 15:38 UTC, Anto59290 commented
Je ne voit pas de bonne raison de garder le paramètre next, je ne voit pas trop son utilité. Il me semble que ça a été[ introduit ici](https://github.com/zestedesavoir/zds-site/commit/77603d0d55a67b4a9ed9a8ceebe904be525200b8#diff-b38579ddedc555fa9207d48edc83b7dfR40).

2018-01-09 13:35 UTC, Anto59290 commented on zds/member/views.py
> +            except:
Alors quitte a refactorer du code dans le coin je propose de revoir aussi ce bout de code. Pour moi les problèmes sont les suivants:

- except générique
- duplication de code entre le try/except
- trop de ligne dans le try, on ne sait pas quelle ligne va lever une exception. 

Je propose quelque chose du genre: 
```py
try:
    response = redirect(next_page)
except: # Ajouter l'exception en question
    response = redirect(reverse('homepage'))

set_old_smileys_cookie(response, profile)
return response
```

2018-01-09 14:10 UTC, rezemika commented on zds/member/views.py
> +            except:
Bien vu ! C'est fait. :)

2018-01-13 21:37 UTC, gllmc approved these changes
Ça me paraît bon, merci de ton travail !

2018-01-13 21:38 UTC, merged

2018-01-13 21:47 UTC, rezemika commented
\o/ Merci !