[Feedback] [WIP] Ajoute une page avec les derniers sujets publiés
zestedesavoir/zds-site pull request #4831
Opened 2018-01-03 18:54 UTC by rezemika

**Cette PR fait suite à une suggestion faite sur le forum ([ici](https://zestedesavoir.com/forums/sujet/10014/liste-des-derniers-sujets/)). Il faudrait en discuter et voir si elle pertinente ou non.**

Ce commit ajoute une page accessible via l'URL "/forums/derniers-sujets/" qui affiche les derniers sujets publiés, toutes catégories confondues. Le bouton "Tous les sujets" sur la page d'accueil est renommé en "Derniers sujets" et pointe maintenant vers cette page.

La pagination n'y a pas été ajoutée étant donné que cette page a davantage pour but de voir quels sont les derniers sujets publiés que d'explorer tous les sujets publiés un jour sur un des forums (seuls les sujets les plus récents sont pertinents).
Le nombre de sujets affichés sur la page correspond au nombre de sujets qui seraient affichés sur la première page d'une liste avec pagination (voir `settings.ZDS_APP['forum']['topics_per_page']`).

La catégorie (et un lien vers celle-ci) est également ajouté dans les blocs des sujets, afin de rappeler que cette page liste les derniers sujets quelque soit leur catégorie (ils sont ordonnés selon leur date de publication).

Numéro du ticket concerné : aucun

### Points à vérifier / débattre

  - URL de la page ("/forums/derniers-sujets/" pour l'instant) ;
  - Mise en forme de la page ;
  - Nom du bouton vers cette page sur la page d'accueil ("Derniers sujets" pour l'instant, un peu redondant avec le titre à côté) ;
  - Pagination ?

2018-01-11 19:26 UTC, gllmc requested changes
Merci pour cette PR, je trouve cette nouveauté pertinente !

- Il y a une faille de sécurité à corriger (les sujets privés sont affichés).
- Éventuellement dans une deuxième itération, je pense qu'un filtre sur la gauche permettant de voir les derniers sujets sur la base de la date du dernier message serait pertinent.
- Je mettrais bien un lien `Tous les forums` en haut du menu de gauche sur cette page.

2018-01-11 19:26 UTC, gcodeur commented on templates/forum/last_subjects.html
> +                {% include "forum/includes/topic_row.part.html" with display_category=1 %}
`display_category=True` plutôt, non ?

2018-01-11 19:26 UTC, gcodeur commented on templates/home.html
> +                    <a href="{% url 'last-subjects' %}" class="btn btn-grey">{% trans "Derniers sujets" %}</a>
Je suis moyennement convaincu par ce titre, qui fait doublon avec ce qui est affiché à gauche. Pourquoi pas quelque chose comme `En voir plus` ?

2018-01-11 19:26 UTC, gcodeur commented on zds/forum/views.py
> +    queryset = Topic.objects.all().order_by('-pubdate')[:settings.ZDS_APP['forum']['topics_per_page']]
Attention, Les sujets dans les forums privés vont aussi être affichés ! Il faut faire un tri pour n'afficher que ceux que l'utilisateur peut voir.

2018-01-11 19:26 UTC, gcodeur commented on templates/forum/last_subjects.html
> +    {% endif %}
Tous ces conditions ne sont pas nécessaires en l'absence du filtre adéquat.

2018-01-11 19:26 UTC, gcodeur commented on templates/forum/last_subjects.html
> +    {% endif %}
Idem.

2018-01-11 19:58 UTC, rezemika commented on zds/forum/views.py
> +    queryset = Topic.objects.all().order_by('-pubdate')[:settings.ZDS_APP['forum']['topics_per_page']]
Oups, en effet.

2018-01-11 20:09 UTC, rezemika commented
Merci pour ton retour @gcodeur !

J'ai corrigé les erreurs, transformé la vue en fonction (je ne voyais pas comment gérer le filtrage des sujets visible autrement) et j'ai "préparé le terrain" pour ajouter les boutons de changement d'affichage.

Par contre, je ne te cache pas que je risque d'avoir un peu de mal à gérer cette partie là (mais je ne demande qu'à essayer :) ).

2018-01-11 20:23 UTC, gllmc reviewed
> Par contre, je ne te cache pas que je risque d'avoir un peu de mal à gérer cette partie là (mais je ne demande qu'à essayer :) ).

Le filtre fonctionnera comme ceux qui sont utilisés dans les pages de forums. L'idée est donc de passer par un paramètre `GET` `order` pour avoir une URL comme `/forums/derniers-sujets/?order=last_post`.

Selon ce paramètre, tu appliques ton `order_by` (dans la vue) sur `-pubdate` ou `-last_message__pubdate`) et tu modifies le filtre qui apparaît comme sélectionné dans le template.

Conseil : tu peux prévoir deux valeurs possibles pour `order` : `creation` et `last_post`. Si le paramètre est inexistant ou que sa valeur est incorrecte, considère que `creation` est sélectionné (c'est la valeur par défaut).

2018-01-11 20:23 UTC, gcodeur commented on zds/forum/views.py
> +    topics = Topic.objects.all().order_by('-pubdate')
Tu peux limiter le nombre de requêtes SQL avec un `.selected_related('forum')`. ;)

2018-01-11 20:23 UTC, gcodeur commented on templates/forum/last_subjects.html
> +                    {% trans "Tous les forums" %}
Mieux : tu peux l'afficher comme le lien `Nouveau sujet` qui apparaît dans un forum (regarde comment c'est fait dans le template), ça t'évite d'avoir un doublon avec deux fois le même texte sur le `h3` et le `li`.

2018-01-11 20:55 UTC, rezemika commented on templates/forum/last_subjects.html
> +                    {% trans "Tous les forums" %}
Bien vu, merci !

2018-01-11 20:56 UTC, rezemika commented on zds/forum/views.py
> +    topics = Topic.objects.all().order_by('-pubdate')
Oh sympa, je connaissais pas cette méthode. Merci pour la découverte. :)

2018-01-11 23:03 UTC, rezemika commented
Merci pour ton aide !

Je viens de tester en local et ça m'a l'air d'être bon. :)

2018-01-13 20:31 UTC, rezemika commented
À votre avis, je mets quelle classe pour les icônes des boutons de tri ? `move` (deux flèches tête-bêche) ou `history` (une horloge), ou autre chose ?

2018-01-14 14:47 UTC, Anto59290 commented on templates/forum/includes/topic_row.part.html
> +                        {{ topic.forum.title }}
Tu as oublié la balise trans ici et à plusieurs endroits dans le nouveau template

2018-01-14 14:49 UTC, Anto59290 commented on zds/forum/views.py
> +def last_subjects_view(request):
Les vues basées sur les classes sont nettement préférables aux fonctions.

2018-01-14 14:52 UTC, Anto59290 commented on zds/forum/views.py
> +    topics = topics[:settings.ZDS_APP['forum']['topics_per_page']]
À vérifier, mis je pense que la requête ligne 66 va chercher TOUS les topics de la base sans limites. Il faut pour moi: 

- connaître les forums que l'utilisateur peut lire
- aller chercher uniquement les topics concernés, avec une limitation dans l'orm et non pas en python

Je pense que ça sera plus propre et beaucoup plus rapide.

2018-01-14 21:00 UTC, rezemika commented
Merci pour ton retour ! Voilà les modifs ! :)

2018-01-19 20:15 UTC, motet-a commented on templates/forum/last_subjects.html
> +{% trans "Derniers sujets" %}
Indentation

2018-01-19 20:45 UTC, rezemika commented on templates/forum/last_subjects.html
> +{% trans "Derniers sujets" %}
Bien vu, c'est corrigé. Merci !

2018-01-21 18:16 UTC, gllmc reviewed
Je pense que ce serait bien d'avoir un test unitaire sur cette page qui vérifierait :

- que la page fonctionne sans erreur chez les utilisateurs connectés et non connectés.
- que les forums inaccessibles ne sont pas affichés.

Tu saurais comment faire ça ?

2018-01-21 18:16 UTC, gcodeur commented on zds/forum/views.py
> +            .filter(forum__in=self.request.user.profile.readable_forums()) \
Très bonne idée ! Par contre, il faut gérer le cas où l'utilisateur est anonyme (actuellement `AttributeError`).

2018-01-21 20:00 UTC, rezemika commented on zds/forum/views.py
> +            .filter(forum__in=self.request.user.profile.readable_forums()) \
Bien vu ! Je pousse les modifs.

Pour les tests unitaires, je sais pas, mais je vais essayer. :)

2018-01-21 20:37 UTC, rezemika commented
C'est bon, les tests unitaires sont écrits et m'ont l'air de passer en local. Qu'en pense-tu ?

2018-01-28 13:51 UTC, vhf commented on templates/forum/last_subjects.html
> +            <span itemprop="title">Derniers sujets</span>
i18n

2018-01-28 13:58 UTC, rezemika commented
Les tests passent sans problème. Plus qu'à trouver des icônes adaptées pour les boutons de tri et je pense que ce sera prêt à être mergé. Je suis preneur de toute suggestion. :)

2018-01-28 13:58 UTC, rezemika commented on templates/forum/last_subjects.html
> +            <span itemprop="title">Derniers sujets</span>
Bien vu, je corrige. Merci !

2018-01-30 20:43 UTC, gllmc approved these changes
C'est tout bon pour moi. Merci et désolé pour le délai !

(Je relance Travis vu que je ne comprends pas l'erreur.)

2018-01-30 20:56 UTC, gcodeur commented
Travis est passé sans problème et les icônes me paraissent adaptées. Si c'est bon pour toi, on peut merger. :)

2018-01-30 21:42 UTC, rezemika commented
> C'est tout bon pour moi. Merci et désolé pour le délai !

Aucun soucis ! J'étais moi-même assez occupé ces derniers temps.

Ça marche ! J'enlève le "[WIP]". À la limite on pourra toujours changer les icones plus tard si quelqu'un en suggère d'autres.

Merci ! :)

2018-01-30 21:54 UTC, merged