[WIP] Transforme la variable 'BASE_DIR' (string) en 'pathlib.Path'
zestedesavoir/zds-site pull request #4875
Opened 2018-02-14 20:36 UTC by rezemika

Il y a encore un paquet d'erreurs à corriger, c'est loin d'être mergeable pour l'instant, mais vu que j'ai une *segfault* de mon côté, je vais utiliser Travis pour les tests.

Numéro du ticket concerné : #4744 

### Contrôle qualité

  - Lancer les tests unitaires devrait suffire.

2018-02-14 23:04 UTC, rezemika commented
\o/ Les tests passent ! Je retire le "[WIP]". :)

2018-02-25 18:07 UTC, rezemika commented
J'ai un petit doute sur mon rebase, est-ce que quelqu'un peut me confirmer que [cette partie](https://github.com/zestedesavoir/zds-site/pull/4875/files#diff-314eb87fc4e5f8242f8fbcfbbcb796beR302) du code est bien sensée être là ?

2018-03-04 12:25 UTC, sandhose commented
J'ai une requête comme tu touches au `BASE_DIR`. Il y a masse de settings constamment overridés pour les tests de la même manière. Si tu pouvais changer ça en overridant ces settings dans les vrais settings de `test`, ça serait parfait: https://github.com/zestedesavoir/zds-site/blob/a9d83a77a4b49f6262f4a090de94bb97ac2286e0/zds/settings/abstract_test.py#L1

Sinon niveau code LGTM

2018-03-05 16:41 UTC, rezemika commented
@sandhose : Désolé, je ne suis pas sur de comprendre. Tu peux reformuler stp ? Tu parles d'enlever les `override_settings` et de tout mettre dans ce fichier là si j'ai bien compris ?

2018-03-05 18:40 UTC, sandhose commented
Exactement. Il y a une bonne dose de settings overridés dans les tests alors que ça pourrait être définit pour tout l'environnement de test.

On devrait pouvoir virer toutes les occurrences de
```
overridden_zds_app['content']['repo_private_path'] = str(settings.BASE_DIR / 'contents-private-test')
overridden_zds_app['content']['repo_public_path'] = str(settings.BASE_DIR / 'contents-public-test')
```

en définissant ça dans `zds/settings/abstract_test.py`

2018-03-05 19:19 UTC, artragis requested changes

2018-03-05 19:19 UTC, artragis commented on zds/gallery/tests/tests_views.py
> +        with open(str(settings.BASE_DIR / 'fixtures' / 'logo.png'), 'rb') as fp:
`with Path(settings.BASE_DIR, 'fixtures', 'logo.png').open('rb') as fp` marche aussi.

2018-03-05 19:19 UTC, artragis commented on zds/pages/views.py
> +        with open(str(settings.BASE_DIR / 'quotes.txt'), 'r', encoding='utf-8') as quotes_file:
tu peux ne pas importer `codecs` et faire `with Path(settings.BASE_DIR / 'quotes.txt').open('r', encoding='utf-8')`

2018-03-05 19:22 UTC, rezemika commented
D'accord, merci ! :)

2018-08-05 08:21 UTC, pierre-24 commented
Au fait, @rezemika, t'a pas tenu compte de la remarque de @artragis ^^

2018-08-05 10:53 UTC, rezemika commented
Ah ? Pourtant de mon côté je vois bien des modifs à ces endroits-là.

Après vérification, j'en ai en effet oublié quelques-unes. Je repousse pour actualiser le diff.

2018-08-05 11:33 UTC, pierre-24 commented
Bon, autant tout casser de suite.

2018-08-05 11:39 UTC, pierre-24 requested changes

2018-08-05 11:39 UTC, pierre-24 commented on zds/settings/abstract_base/zds.py
> +PANDOC_LOG_STATE = False
Je suis pas sur qu'on aie encore besoin de ça, en fait :o

2018-08-05 11:39 UTC, pierre-24 commented on zds/gallery/tests/tests_forms.py
> +        upload_file = open(str(settings.BASE_DIR / 'fixtures' / 'image_test.jpg'), 'rb')
`Path(xxx).open('rb')` :)

2018-08-05 11:39 UTC, pierre-24 commented on zds/member/tests/tests_models.py
> -overridden_zds_app['content']['repo_public_path'] = os.path.join(settings.BASE_DIR, 'contents-public-test')
Dis, t'as une bonne raison d'enlever ça ? Parce que en fait, si tu le fait pas, ça te bousille tes données "normales" ^^

2018-08-05 11:39 UTC, pierre-24 commented on zds/tutorialv2/tests/tests_utils.py
> +        manifest = open(str(settings.BASE_DIR / 'fixtures' / 'tuto' / 'article_v1' / 'manifest2.json'), 'r')
`Path().open()` :)

2018-08-05 11:39 UTC, pierre-24 commented on zds/tutorialv2/tests/tests_utils.py
> +        manifest = open(str(settings.BASE_DIR / 'fixtures' / 'tuto' / 'big_tuto_v1' / 'manifest2.json'), 'r')
`Path().open()` :)

2018-08-05 11:39 UTC, pierre-24 commented on zds/tutorialv2/tests/tests_views.py
> +
On a encore besoin de ça ?

2018-08-05 11:45 UTC, rezemika commented on zds/member/tests/tests_models.py
> -overridden_zds_app['content']['repo_public_path'] = os.path.join(settings.BASE_DIR, 'contents-public-test')
Hum, bonne question, j'avoue avoir oublié le pourquoi de ces changements. :-°

2018-08-05 11:51 UTC, rezemika commented on zds/tutorialv2/tests/tests_views.py
> +
Aucune idée. Je ne me suis encore jamais penché sur la génération des PDF.

2018-08-05 11:51 UTC, pierre-24 commented on zds/member/tests/tests_models.py
> -overridden_zds_app['content']['repo_public_path'] = os.path.join(settings.BASE_DIR, 'contents-public-test')
Je te promets que c'est bien le bazar sans ça :p

2018-08-05 11:52 UTC, pierre-24 commented on zds/tutorialv2/tests/tests_views.py
> +
@artragis ?

Je dis ça parce que c'est un ajout qui ne semble pas concerner ta PR, donc c'est peut être un truc qui est ressorti par génération de conflits.

2018-08-05 11:57 UTC, rezemika commented on zds/member/tests/tests_models.py
> -overridden_zds_app['content']['repo_public_path'] = os.path.join(settings.BASE_DIR, 'contents-public-test')
Ah oui, ça remplace les données de prod par les données de test si j'interprète bien ?

2018-08-05 11:59 UTC, pierre-24 commented on zds/member/tests/tests_models.py
> -overridden_zds_app['content']['repo_public_path'] = os.path.join(settings.BASE_DIR, 'contents-public-test')
Pas exactement. Disons que les contenus s'enregistrent par défaut dans un dossier "A". Sauf qu'à la fin du test, on est des gros bourrins, on vire le dossier "A". Du coup, si jamais y'avait des contenus avant tests, ils sont également supprimé (enfin, les fichiers sont supprimés, par la référence en BDD, c'est ça qui es drôle). Du coup, on évacue discretement le problème en créer un dossier spécialement pour les contenus générés par les tests, qu'on peut supprimer sans problèmes ;)

2018-08-05 12:20 UTC, rezemika commented on zds/member/tests/tests_models.py
> -overridden_zds_app['content']['repo_public_path'] = os.path.join(settings.BASE_DIR, 'contents-public-test')
Ah d'accord, merci pour la précision ! :)

2019-03-10 17:45 UTC, artragis commented
tu la continues ou pas?

2019-03-10 19:57 UTC, rezemika commented
Oh, désolé, j'avais oublié cette PR. Je mets à jour, et je vais surement bientôt faire un post sur le forum de dev concernant ma quasi-désertion du site (dont je m'excuse platement)...

2019-03-10 20:08 UTC, artragis commented
Tu n'as pas à t'excuser, c'est juste que j'essaie d'avoir une visibilité sur ce qui est fait et reste à faire. Si tu n'as pas le temps/la dispo c'est une réponse qui me convient, l'important c'est que je puisse m'organiser

2019-03-10 20:42 UTC, rezemika commented
Eh bien, je peux "maintenir" les PR déjà faites, mais je n'ai effectivement plus vraiment la disponibilité pour en ouvrir de nouvelles (ou seulement de petites, si l'occasion se présente).

2020-04-21 16:53 UTC, Arnaud-D commented
On en est où par ici @rezemika ?

2020-04-21 22:36 UTC, rezemika commented
J'ai résolu les conflits avec la branche de dev (désolé pour le commit de merge), voyons ce qu'en dit Travis. Cela dit, la PR est vieille de deux ans, est-ce qu'elle est encore d'actualité ?

2020-04-22 06:30 UTC, Arnaud-D commented
C'est encore d'actualité. En réunion de dév, on était d'accord pou dire qu'il faudra le faire "un jour" de toute façon. 

Si tu n'es pas plus assez dispo ou n'a pas plus l'envie ou le courage de terminer la PR, je suis prêt à la reprendre. Ça te paraît envisageable que je reprenne la main ?

2020-04-22 12:43 UTC, rezemika commented
Je n'ai aucune objection à ce que tu reprennes la main si tu le souhaites. Je veux bien essayer de continuer, mais j'ai effectivement quelques problèmes perso qui limitent ma capacité de travail en ce moment (sans compter le fait que, vu mon éloignement, j'ai perdu en familiarité avec le projet)... J'ai déjà commité une petite correction pour l'instant.

2020-04-28 21:12 UTC, Arnaud-D commented
Je reprends le boulot. :-)

2020-04-28 21:12 UTC, closed without merging