Simplifie l'URL des tags des sujets du forum
zestedesavoir/zds-site pull request #4877
Opened 2018-02-24 12:08 UTC by rezemika

Avant, l'URL d'un tag était de la forme "/forums/sujets/tag/PK/SLUG". La recherche des sujets avec un autre tag ne pouvait donc pas se faire en modifiant l'URL , puisqu'il fallait connaitre sa Public Key.
Désormais, l'URL est simplifiée et est de la forme "/forums/sujets/tag/SLUG", rendant la recherche possible.
L'ancienne URL reste utilisable pour ne pas casser les anciens liens.

Numéro du ticket concerné (optionnel) : Aucun

Que pensez-vous de cette nouvelle URL ? Est-elle pertinente ? Devrais-je la simplifier davantage avec quelque chose comme "/forums/sujets/?tag=SLUG" ou quelque chose comme ça ?

### Contrôle qualité

  - Vérifiez que les URL des tags des sujets sont valides ;
  - Vérifiez la possibilité de chercher un autre tag en modifiant l'URL ;
  - Vérifiez que les anciennes URL sont toujours valides.

2018-02-24 12:22 UTC, AmauryCarrade commented
À titre personnel, et considérant le slug unique, je préfère cette URL (`/forum/sujets/tag/<slug>`) à l'ancienne et à l'autre proposée.

Par contre si ce changement est validé, ne faudrait-il pas mieux _rediriger_ les anciennes URL (avec une 301 permanente) vers les nouvelles ? En l'état, sauf erreur de ma part, il y a pour chaque tag deux pages avec le même contenu. D'un point de vue logique (et SEO) c'est pas tip top.

2018-02-24 12:48 UTC, rezemika commented
Bonne idée ! Voilà qui est fait. :)

2018-02-24 12:51 UTC, artragis requested changes

2018-02-24 12:51 UTC, artragis commented on zds/forum/views.py
> +        tag = get_object_or_404(Tag, pk=self.kwargs.get('tag_pk'), slug=self.kwargs.get('tag_slug'))
vérifie bien qu'il n'est pas possible que deux tags aient le même slug (exemple c++ et c# et c) sinon get_object_or_404 va envoyer une erreur (multiple objects returned)

2018-02-24 12:57 UTC, AmauryCarrade commented on zds/forum/views.py
> +        tag = get_object_or_404(Tag, pk=self.kwargs.get('tag_pk'), slug=self.kwargs.get('tag_slug'))
Le `slug` d'un tag a une contrainte d'unicité, donc je suppose que c'est bon

https://github.com/zestedesavoir/zds-site/blob/dev/zds/utils/models.py#L602-L611

2018-02-24 14:29 UTC, artragis commented on zds/forum/views.py
> +        tag = get_object_or_404(Tag, pk=self.kwargs.get('tag_pk'), slug=self.kwargs.get('tag_slug'))
impeccable alors.

2018-02-24 14:29 UTC, artragis approved these changes

2018-03-07 19:58 UTC, rezemika commented
Les tests passent ! J'ai tout squashé pour avoir un historique plus propre. :)

2018-03-07 20:37 UTC, artragis commented
Je garde ta PR sous le coude, sûrement pour la v27 mais avant j'aimerai qu'on finisse le gros du travail sur zmd et la publication.

En tout cas merci pour ton courage.

2018-03-07 21:19 UTC, rezemika commented
Pas de souci, merci ! :)

2018-03-22 12:54 UTC, artragis commented
OK pour moi.

2018-03-22 12:54 UTC, merged