Corrige le bouton précédent pour les articles et les billets.
zestedesavoir/zds-site pull request #4987
Opened 2018-07-27 16:07 UTC by Karnaj

Le bouton précédent renvoie sur le contenu précédent et pas sur le premier contenu et pour les billets renvoie sur le billet précédent et pas sur le billet précédent de l'auteur.

Numéro du ticket concerné : #4979.

### Contrôle qualité

- Créer deux auteurs A et B.
- Créer un billet pour un A, puis un billet pour B, puis un autre billet pour A, puis pour B.
- Aller sur le second billet de A, vérifier que le bouton précédent renvoie sur le premier billet de A et que le bouton suivant renvoie sur le second billet de B.

2018-07-27 17:40 UTC, artragis requested changes

2018-07-27 17:40 UTC, artragis commented on zds/tutorialv2/views/published.py
> +                .order_by('publication_date').last()
Je pense qu'il serait plus efficace de faire `order_by('-publication_date').first()` pour que le SQL soit globalement `SELECT * FROM xxx ORDER BY publication_date DESC LIMIT 1 OFFSET 0`

2018-07-27 17:42 UTC, artragis commented on zds/tutorialv2/views/published.py
> +                .order_by('publication_date').last()
Il serait aussi cool d'ajouter un test pour s'assurer que le lien vers le billet précédent existe et est bon

créer trois contenus (utlise `PublishedContentFactory(type='OPINION', authors=[...])`) puis appelle la vue pour afficher le dernier des trois et regarde qu'il y a un lien vers le second mais pas de lien vers le premier.

2018-07-27 22:16 UTC, Karnaj commented
@artragis c'est fait. Les tests ne passent pas, apparemment une erreur de publication du PDF d'un contenu dans `test_ping_on_tuto.`.

2018-07-28 06:30 UTC, artragis commented
@Karnaj les tests passent, c'est pep 8 qui passe pas 

```
./zds/tutorialv2/tests/tests_views.py:6200:121: E501 line too long (124 > 120 characters)
./zds/tutorialv2/tests/tests_views.py:6204:121: E501 line too long (124 > 120 characters)
```

Je serai absent pendant une semaine, essaie de demander à d'autres personnes (@gcodeur @Situphen etc.) de faire la QA et/ou de merger.

2018-07-28 19:55 UTC, Situphen commented
@Karnaj 

- pour les articles si c'est la cas c'est bien un bug (oups :D)
- pour les billets par contre c'est voulu de ne parcourir que les billets d'un même auteur
   - c'est [une suggestion que @gcodeur a fait sur ma PR](https://github.com/zestedesavoir/zds-site/pull/4795#discussion_r151778739)
   - je suis du même avis que lui
   - on peut toujours changer ça si plusieurs personnes sont contre cet avis ou si quelqu'un arrive à nous faire changer d'avis

:)

2018-07-28 20:20 UTC, Karnaj commented
@Situphen Donc c'est voulu de renvoyer sur le billet précédent de l'auteur. Je peux supprimer cette correction et juste faire en sorte que le bouton précédent renvoie bien sur l'article précédent et le billet précédent de l'auteur dans le cas des billets.

Mais je pense tout comme @artragis qu'il est mieux de renvoyer sur le billet précédent tout court, pour garder une cohérence dans le comportement premièrement, et surtout parce que ça mène à un comportement surprenant : par exemple, si tu prends [mon dernier billet](https://zestedesavoir.com/billets/2673/utiliser-la-sdl-sous-linux-avec-code-blocks/), le lien précédent mène [à ce billet](https://zestedesavoir.com/billets/2090/zeste-de-savoir-passe-en-version-24-1/), mais puisque ce dernier est écrit par plusieurs personnes, le lien précédent mène à [ce billet](https://zestedesavoir.com/billets/1800/les-3-v-du-big-data/) qui lui n'est pas de moi et donc le lien « suivant » de ce dernier billet ne ramène pas à la page attendue. Pour moi la navigation est cassée avec ce comportement.

2018-07-28 21:56 UTC, Situphen commented
Hum, vos arguments se tiennent :) Je suis d'accord pour garder la modification alors, sachant qu'en passant par le profil on peut toujours retrouver les autres tribunes de l'auteur

2018-08-04 15:51 UTC, Karnaj commented
@Situphen donc c'est OK, tu peux merge ?

2018-08-04 17:11 UTC, pierre-24 commented
Voila ;)

2018-08-04 17:11 UTC, merged