La mise à jour d'un contenu ne conserve pas les anciens auteurs
zestedesavoir/zds-site pull request #4995
Opened 2018-08-04 18:29 UTC by Karnaj

Tout est dans le titre, lorsqu'on supprime un auteur d'un tutoriel et qu'on le republie, cet auteur n'apparaît plus dans la liste des auteurs.

Ticket concerné : #4134 

### Contrôle qualité

- Créer un tutoriel.
- Lui ajouter un auteur.
- Le publier et vérifier que l'auteur apparaît dans la liste des auteurs de la version publiée.
- Supprimer cet auteur.
- Republier le tutoriel et vérifier que cet auteur n'apparaît plus dans la liste des auteurs de la version publiée.

2018-08-04 18:34 UTC, artragis requested changes
Merci pour cette PR, je fais la QA demain, quelques petites modificatons pour rendre le test plus court.

2018-08-04 18:34 UTC, artragis commented on zds/tutorialv2/tests/tests_views.py
> +        tutorial = PublishableContentFactory(type='TUTORIAL')
peut être fait via `PublishedContentFactory(type='TUTORIAL', author_list=[self.user_author, self.user_guest])`

comme ça tu as un tutoriel, publié, avec deux auteurs.

2018-08-04 18:34 UTC, artragis commented on zds/tutorialv2/tests/tests_views.py
> +                'is_major': True,
un test identique avec `is_major` a `False` ne seraiut pas de trop.

2018-08-06 06:21 UTC, pierre-24 commented
J'peux QA ? :)

2018-08-06 06:25 UTC, artragis commented
je vais m'en occuper aujourd'hui @pierre-24

2018-08-06 06:26 UTC, pierre-24 commented
Je vais pas dire non ^^

2018-08-06 11:17 UTC, artragis approved these changes

2018-08-06 11:22 UTC, artragis commented
QA OK

2018-08-06 11:22 UTC, merged