[WIP] Facilite les propositions de unes
zestedesavoir/zds-site pull request #4996
Opened 2018-08-04 22:59 UTC by pierre-24

Comme proposé [ici](https://zestedesavoir.com/forums/sujet/9647/les-contenus-mis-en-une/?page=2#p165874), je me propose d'aider le travail de validation en permetant à tout un chacun de proposer un topic ou un contenu comme une. L'idée, c'est simplement un bouton de vote (comme l'abonement) et une page reprenant les différentes propositions avec le nombre de votes, une option pour ignorer et le bouton pour créer la une correspondante.

Numéro du ticket concerné (optionnel) : #4779 

TODO: 

- [ ] J'ai cassé la mise en une ;)
- [ ] Éviter d'afficher sur contenu obsolète
- [ ] Tests unitaires

### Contrôle qualité

  - Lancez `python manage.py migrate` et `yarn test` ;
 - La suite plus tard ;)

2018-08-07 17:26 UTC, rezemika commented
J'aime beaucoup cette fonctionnalité !

Voilà mon rapport de QA. :)

- Petite note méta : il faut aussi faire `make build-front` en plus de `migrate`.

- Sur la page du topic, le mot "vote" semble ne pas être aligné avec le reste de la ligne.

![Problème d'alignement.](https://user-images.githubusercontent.com/1690660/43790475-01ed1130-9a73-11e8-8602-69ade8d20601.png)

- Lorsque je clique dessus, il y a un chargement et je suis renvoyé en haut de la page (en fait, je suis redirigé de http://localhost:8000/forums/sujet/7/numquam-dolores-amet-vitae-maiores-explicabo-cumque-quisquam-nisi-culpa/ vers http://localhost:8000/forums/sujet/7/numquam-dolores-amet-vitae-maiores-explicabo-cumque-quisquam-nisi-culpa/?page=1), comme s'il s'agissait d'un formulaire classique. Pour retourner à la liste des sujets, il faut donc faire deux fois "Précédent".
- Ce n'est pas un gros problème, dans la mesure où ça ne devrait pas arriver souvent, mais lorsqu'il n'y a aucune proposition de requête, seul le header du tableau est visible. Ça serait peut-être plus intuitif d'afficher une ligne indiquant quelque chose comme "Aucune proposition pour l'instant" ?

![screenshot_2018-08-07 liste des requetes pour des unes mise en avant zeste de savoir](https://user-images.githubusercontent.com/1690660/43791140-00f465f6-9a75-11e8-9f44-710a81ecf9d7.png)

Sinon, tout le reste est ok. GG ! :)

2018-08-07 17:31 UTC, pierre-24 commented
Merci ;)

C'est marrant, parce que la 2 et la 3, on dirait ce qu'on pourrait obtenir sans avoir *rebuild* le front, justement. M'enfin je vais regarder :)

2018-08-07 17:33 UTC, rezemika commented
Ah, je sais plus à quel moment j'ai fais le rebuild. Je vais revérifier, j'ai peut-être dit une connerie. À vrai dire, je me suis rendu compte qu'il fallait le rebuilder quand un des boutons ne marchait pas. :-°

2018-08-07 18:56 UTC, pierre-24 commented
Voilà pour le point 4 (pas oublier de build le front, donc). Pour les autres, normalement, ça devrait être bon ^^

2018-08-09 11:15 UTC, gustavi commented on templates/featured/includes/featured_request.part.html
> +<form action="{{ link }}" method="post">
Identaton à revoir

2018-08-09 11:37 UTC, gustavi requested changes

2018-08-09 11:37 UTC, gustavi commented on templates/featured/includes/featured_request.part.html
> +{% if show_featured_requested %}
Identation de ce fichier à revoir

2018-08-09 11:37 UTC, gustavi commented on templates/featured/list_requests.html
> +                            {% trans "(accepté)" %}
"acceptée" non ?

2018-08-09 11:37 UTC, gustavi commented on templates/featured/list_requests.html
> +                    {% trans "Topics proposés" %}
s/Topic/Sujets ?

2018-08-09 11:37 UTC, gustavi commented on templates/tutorialv2/view/content_online.html
> +        {% url 'content:request-featured' object.pk as link_request %}
Il y a du code dupliqué avec le fichier de dessus. Peut-être qu'il est possible de le factoriser.

2018-08-09 11:37 UTC, gustavi commented on zds/featured/managers.py
> +            request = self.filter(
J'aime pas trop `request` comme nom de variable, c'est un truc pas mal utilisé en interne dans les vues, ça pourrait prêter à confusion.

2018-08-09 11:37 UTC, gustavi commented on zds/featured/models.py
> +    type = models.CharField(max_length=10, choices=(('CONTENT', _('Contenu')), ('TOPIC', _('Topic'))), db_index=True)
Ça serait bien de sortir les choix dans une variable dans la classe, ça permettra des les réutiliser si besoin.

2018-08-09 11:37 UTC, gustavi commented on zds/featured/models.py
> +    type = models.CharField(max_length=10, choices=(('CONTENT', _('Contenu')), ('TOPIC', _('Topic'))), db_index=True)
s/Topic/Sujet ?

2018-08-09 11:37 UTC, gustavi commented on zds/featured/models.py
> +    users_voted = models.ManyToManyField(User, verbose_name='Auteurs', db_index=True, blank=True)
Auteur(s)

2018-08-09 11:37 UTC, gustavi commented on zds/featured/models.py
> +    rejected = models.BooleanField(default=False)
Ça serait cool d'avoir des `versbose_name` (pour ce champs et tous les autres du model)

2018-08-09 11:37 UTC, gustavi commented on zds/featured/urls.py
> +    url(r'^unes/requete/(?P<pk>\d+)/$', FeaturedRequestedUpdate.as_view(), name='featured-resource-request-update'),
Plus une question qu'autre chose : c'est volontaire l'absence d'accents dans les URL ? J'ai pas souvenir de problèmes à ce niveau.

2018-08-09 11:37 UTC, gustavi commented on zds/featured/views.py
> +        if form.cleaned_data['request'] is not None:
Plutôt un .get() ici pour éviter une exception (je suis d'accord que normalement c'est bon mais autant éviter le "normalement" vu que le comportement sera le même)

2018-08-09 11:37 UTC, gustavi commented on zds/featured/views.py
> +                request = FeaturedRequested.objects.get(pk=form.cleaned_data['request'])
idem. À la limite sortir ça dans une variable.

2018-08-09 11:37 UTC, gustavi commented on zds/featured/views.py
> +        if 'type' in self.request.GET and self.request.GET['type'] == 'ignored':
Les deux conditions qui suivent peuvent être bougées dans le if parent

2018-08-09 11:37 UTC, gustavi commented on zds/tutorialv2/views/published.py
> +class DisplayOnlineContent(Featureable, SingleOnlineContentDetailViewMixin):
Remarque ici mais qui s'applique à l'ensemble de ZdS : ça serait bien que les mixins se terminent par "Mixin", ça permettrait de plus facilement identifier ce que c'est

2018-08-09 11:37 UTC, gustavi commented on zds/tutorialv2/views/published.py
> +            raise PermissionDenied('Interdit sur une tribune ou un contenu obsolete')
obsolète

2018-08-09 12:05 UTC, artragis commented on zds/tutorialv2/views/published.py
> +            raise PermissionDenied('Interdit sur une tribune ou un contenu obsolete')
pourquoi?

2018-08-09 12:19 UTC, pierre-24 commented on zds/tutorialv2/views/published.py
> +            raise PermissionDenied('Interdit sur une tribune ou un contenu obsolete')
J'en sais rien, j'ai préféré être prudent et copier la règle qui s'applique à la com' et qui dit qu'on ne diffuse pas les contenus obsolètes et les billets. Si tu me dis que osef', osef ;)

2018-08-09 12:20 UTC, pierre-24 commented on templates/tutorialv2/view/content_online.html
> +        {% url 'content:request-featured' object.pk as link_request %}
Difficilement, mais je reconnais une lourde inspiration.

2018-08-09 12:21 UTC, pierre-24 commented on zds/featured/urls.py
> +    url(r'^unes/requete/(?P<pk>\d+)/$', FeaturedRequestedUpdate.as_view(), name='featured-resource-request-update'),
Je ne me suis jamais posé la question, mais comme on a déjà eu des soucis d'UTF-8 (maintenant réglé avec python 3, normalement), je crois que c'est le choix de la sécurité ;)

2018-08-09 20:37 UTC, pierre-24 commented
Voilà :)

2018-08-10 11:31 UTC, gustavi requested changes
Bon désolé de faire encore des retours, des choses sont au travers des mailles du filet à la première relecture.

J'aime beaucoup la manière dont tu as codé ça, c'est très bien ! Pour le code review (python et HTML seulement) une fois que tu as corrigé mes retours je pense que c'est bon !!

2018-08-10 11:31 UTC, gustavi commented on zds/featured/managers.py
> +            raise Exception('cannot toggle without connected user')
Ça serait bien d'avoir une exception personnalisée

2018-08-10 11:31 UTC, gustavi commented on zds/featured/models.py
> +FEATUREABLE_TYPES = (
2 remarques : 

- ça serait bien d'ajouter le sufixe `_CHOICES`
- ça serait cool de sortir `CONTENT` et `TOPIC` pour les réutiliser dans des requêtes comme `queryset = queryset.filter(type='TOPIC')`, ça simplifie les modifications

2018-08-10 11:31 UTC, gustavi commented on zds/featured/urls.py
> +    url(r'^unes/requete/(?P<pk>\d+)/$', FeaturedRequestedUpdate.as_view(), name='featured-resource-request-update'),
OK, ça pourra faire l'objet d'une issue dédiée en effet

2018-08-10 11:31 UTC, gustavi commented on zds/featured/views.py
> +        request = FeaturedRequested.objects.get_existing(content)
`request` à renommer, surtout dans le fichier des vues

2018-08-10 11:31 UTC, gustavi commented on zds/featured/views.py
> +        type_featured_request = self.request.GET.get('type', None)
`get('type', None)` a un comportement identique à `get('type')`

2018-08-10 11:31 UTC, gustavi commented on zds/featured/views.py
> +            queryset = queryset.filter(type='TOPIC')
C'est ici pour les variables sur TOPIC/CONTENT

2018-08-10 11:31 UTC, gustavi commented on zds/featured/views.py
> +    @method_decorator(login_required)
2 remarques : 

- Je préfère largement l'utilisation de `@method_decorator(DECORATOR, name='dispatch')` lorsqu'on ne met rien dans la méthode en question, c'est plus propre à écrire et lire (cf https://docs.djangoproject.com/fr/1.11/topics/class-based-views/intro/#decorating-the-class)
- Tu peux utiliser le mixin `django.contrib.auth.mixins.LoginRequiredMixin` https://docs.djangoproject.com/en/1.11/topics/auth/default/#the-loginrequired-mixin et celui pour les permissions https://docs.djangoproject.com/en/1.11/topics/auth/default/#the-permissionrequiredmixin-mixin (ça permet d'avoir de jolies CBV)

Ce commentaire s'applique également à la suite du fichier

2018-08-10 11:31 UTC, gustavi commented on zds/featured/views.py
> +        if type_featured_request == 'ignored':
Remplacer cette condition par `queryset = queryset.filter(rejected=type_featured_request == 'ignored')` (ajouter des parenthèses si c'est PEP8 valide et  plus simple à lire)

2018-08-10 11:31 UTC, gustavi commented on zds/featured/views.py
> +        if type_featured_request == 'accepted':
Même remarque qui dessus

2018-08-10 11:31 UTC, gustavi commented on zds/tutorialv2/views/published.py
> +            raise PermissionDenied('Interdit sur une tribune ou un contenu obsolète')
Question : avant tu as fait un exception (que j'ai commenté) Exception avec un message en anglais, c'est voulu ?

2018-08-10 11:31 UTC, gustavi commented on zds/featured/managers.py
> +            users = [u for u in featured_request.users_voted.all()]
`list(featured_request.users_voted.all())` ne fait pas la même chose ?

2018-08-10 11:31 UTC, gustavi commented on zds/featured/models.py
> +from django.contrib.contenttypes.models import ContentType
Je vais faire le relou mais c'est cool si les imports peuvent être un minimum triés :)

2018-08-10 11:31 UTC, gustavi commented on zds/featured/tests.py
> +from django.contrib.contenttypes.models import ContentType
Même remarque pour l'import

2018-08-10 11:31 UTC, gustavi commented on zds/featured/tests.py
> +                                                 '?content_type=published_content&content_id={}'.format(tutorial.id)))
J'utiliserai plutôt `.pk` ici

2018-08-10 18:48 UTC, pierre-24 commented
Voilà :)

2018-08-22 22:42 UTC, firm1 commented
### Rapport de qualité

Pour tous les scénarii, je charge les fixtures de base en yml.

J'ai testé tous les scénario présenté dans l'aide à la QA et même plus. Je n'ai que 2 cas qui me posent problèmes.

## Scénario 1

- Je me connecte avec user/user et je vais sur le topic `http://localhost:8000/forums/sujet/1/android-vs-ios/` et je clique sur "Proposer la mise en avant"
- Le bouton s'incrémente bien avec 1 vote.
- Je me connecte avec admin et je vais dans la [liste des requêtes](http://localhost:8000/mise-en-avant/unes/requetes/) : je retrouve bien la proposition
- Je me reconnecte avec user et je vais invalider mon vote sur le sujet précécent.
- Le bouton se met à jour avec 0 votes
- Je me reconnecte en admin, et dans la liste des requêtes, j'ai la suprise de retrouver le sujet dans la liste, mais avec 0 vote.

![capture d ecran de 2018-08-23 00-19-05](https://user-images.githubusercontent.com/6066015/44493941-30c8a480-a66a-11e8-8cbc-18cd7868d8f4.png)

Pour moi c'est **KO** ici car il faudrait que la ligne disparaisse quand on a un nombre de vote = 0. Sinon ça pollue la liste inutilement.

## Scénario 2

- Je me connecte avec user/user et je vais sur le topic `http://localhost:8000/forums/sujet/1/android-vs-ios/` et je clique sur "Proposer la mise en avant"
- Le bouton s'incrémente bien avec 1 vote.
- Je me connecte avec admin et je vais dans la [liste des requêtes](http://localhost:8000/mise-en-avant/unes/requetes/) : je retrouve bien la proposition
- Je clique sur "ignorer", le sujet est bien supprimé de la liste des requêtes
- Si je retourne sur le sujet en question, le bouton "Voter/Ne plus voter" est encore actif et peut être incrémenté par n'importe qui d'autre.
- Si en tant que staff, je clique sur le bouton voter, le sujet ne repop plus dans la liste des requêtes.

On est donc dans une situation ou l'utilisateur peut encore voter sur un sujet, mais le staff ne voit plus les demandes. Ce qui peut être troublant. Soit on désactive le bouton sur le sujet lorsqu'un staff ignore la requête, soit on considère que si le compteur est incrémenté, même si le staff avait ignoré la requête, le sujet repop a nouveau.

Perso je préfère la deuxième option. Car un sujet qui n'était pas intéressant a un moment, peut le devenir au fil du temps.

2018-08-23 05:58 UTC, gcodeur commented
Il n'est pas inenvisageable de faire cohabiter les deux options, un peu comme avec les billets. Mais ça peut se faire dans un second temps.

2018-08-23 06:07 UTC, pierre-24 commented
Pour le scénario 1, en effet, totalement d'accord :)

Pour le scénario 2, je suis plus partagé:

1. À chaque vote, si la ligne reviend, ça va devenir pénible si le sujet est souvent plébiscité mais ne peut pas apparaitre en une. Il faudrait un bouton "ignorer définitivement", à l'instar des billets.
2. D'autre part, on peut aller rechercher les éléments ignoré à partir du menu de gauche ;)

2018-08-23 11:00 UTC, nils-van-zuijlen commented
Pour le scénario 2, je pense que la solution d'un bouton "ignorer définitivement" est plus adaptée, on ne va pas forcément aller dans ce menu de gauche facilement.

2018-08-23 15:59 UTC, firm1 commented
Je suis aussi ok pour le 'ignorer définitivement'. Mais il faudrait a minima que ça désactive le bouton de vote pour pas que les gens votent pour "rien".

2018-08-23 18:37 UTC, pierre-24 commented
as you wish :)

2018-08-29 19:46 UTC, pierre-24 commented
Voilà le "ignorer définitivement", donc :)

2018-08-29 20:22 UTC, pierre-24 commented
*je crois que j'ai trouvé*

2018-10-09 21:22 UTC, A-312 commented
Le résultat du vote ne devrait-il pas être à la discrétion de l'équipe ?

2018-12-23 16:11 UTC, pierre-24 commented
Y'a quoi qui va pas ici (à part la remarque de @A-312, s'entend ?)

2018-12-23 18:36 UTC, A-312 commented
Il y a un timeout entre deux demandes ?

2018-12-23 19:33 UTC, pierre-24 commented
Pas spécialement, pourquoi ?

2018-12-23 19:56 UTC, Situphen commented on Gulpfile.js
> +        'assets/js/featured-request-ignore.js',
Respecter l'ordre alphabétique :)

2018-12-23 19:56 UTC, Situphen commented on assets/js/ajax-actions.js
> +            $plural = $act.find("span#featured_request_plural");
Je sais que c'est ailleurs dans le fichier, mais le `span` avant le `#<id>` ne sert à rien donc je pense qu'il est mieux de l'enlever

2018-12-23 19:56 UTC, Situphen commented on assets/js/featured-request-ignore.js
> +    $featuredRequest.on("click", ".unpick-action", function () {
Pourquoi ne pas faire directement `$(".featured-request").on("click", ...` ?

2018-12-23 19:56 UTC, Situphen commented on assets/scss/layout/_sidebar.scss
> +                &.requesting span {
Je propose de fusionner avec celui du dessus : 

```scss
&.follow span,
&.requesting span {
    ...
}
```

2018-12-23 19:56 UTC, Situphen commented on zds/featured/managers.py
> +            raise FeaturedRequestedException('cannot toggle without connected user')
Pourquoi ne pas mettre tout sous un seul `if user is None` ?

2018-12-23 19:56 UTC, Situphen commented on zds/featured/mixins.py
> +from django.core.exceptions import PermissionDenied
Ordre alphabétique :)

2018-12-23 19:56 UTC, Situphen commented on zds/featured/mixins.py
> +from zds.featured.managers import FeaturedRequestedException
Idem

2018-12-23 19:56 UTC, Situphen commented on zds/tutorialv2/views/published.py
> +            self.object.type != 'OPINION' and not self.object.is_obsolete
Est-ce que tu peux m'expliquer ce que fait `context['show_featured_requested'] = context['show_featured_requested'] and self.object.type != 'OPINION' and not self.object.is_obsolete` s'il te plait ? :)

2018-12-23 20:06 UTC, artragis commented on zds/featured/managers.py
> +            raise FeaturedRequestedException('cannot toggle without connected user')
parce que la variable `user` est redefinie dans le premier `if`

2018-12-23 20:08 UTC, artragis commented on zds/tutorialv2/views/published.py
> +            self.object.type != 'OPINION' and not self.object.is_obsolete
et du coup créer une fonction qui dit dans le nom ce que ça fait.

2018-12-23 20:48 UTC, pierre-24 commented on zds/tutorialv2/views/published.py
> +            self.object.type != 'OPINION' and not self.object.is_obsolete
ça empêche de pouvoir voter sur les tribunes (qui peuvent pas être mises en avant) et sur les contenus obsoletes, si tant est que le contenu en question ne serait pas déjà rejeté.

2018-12-23 20:48 UTC, pierre-24 commented on zds/featured/managers.py
> +            raise FeaturedRequestedException('cannot toggle without connected user')
c'est ça ^^

2018-12-23 21:06 UTC, pierre-24 commented on assets/js/featured-request-ignore.js
> +    $featuredRequest.on("click", ".unpick-action", function () {
Parce que je ne connais pas le JS à fond ? :p

2018-12-23 21:10 UTC, Situphen commented on zds/tutorialv2/views/published.py
> +            self.object.type != 'OPINION' and not self.object.is_obsolete
le premier `and` ne devrait pas être `if` ? :)

2018-12-23 21:16 UTC, pierre-24 commented on zds/tutorialv2/views/published.py
> +            self.object.type != 'OPINION' and not self.object.is_obsolete
Non plus, parce que c'est vraiment pour se combiner avec le résultat déjà existant (parce l'équipe peut marquer un objet comme ne pouvant plus être proposé en une). Mais je vais bouger ça comme suggéré par @artragis

2018-12-23 21:53 UTC, pierre-24 commented
Voilà :)

2018-12-26 12:23 UTC, artragis commented
y'a conflit, va falloir rebase

2018-12-26 15:21 UTC, pierre-24 commented
Voilà :)

2018-12-26 15:32 UTC, artragis commented
ça a pas été rebase mais mergé...

ça signifie que là je ne peux que "squash" lorsque la qa aura été faite.

2018-12-26 15:33 UTC, pierre-24 commented
Parfaitement ^^ (mes commits n'ont pas vraiment d'intérêt individuellement, de toute façon).

2019-08-10 11:00 UTC, pierre-24 commented
Maieuuuh. Ma PR a un an, et elle était QA et tout ^^

2019-08-10 12:39 UTC, artragis commented
si tu peux gérer les conflits, comme la PR a été QA, je la validerai.

2019-08-11 20:25 UTC, pierre-24 commented
Voilà qui est fait ;) (à condition que les tests passent, bien entendu)

2019-08-13 18:14 UTC, artragis commented
Je merge, désolé de ne pas l'avoir fait avant !

2019-08-13 18:17 UTC, pierre-24 commented
pas de soucis ;)

2019-08-13 18:29 UTC, merged