Affiche la description du groupe sur les détails d'une casquette
zestedesavoir/zds-site pull request #5018
Opened 2018-08-22 20:48 UTC by gcodeur

Petite PR pour me remettre dans le bain. Actuellement, la page des détails d'une casquette donne peu d'informations : son nom et les membres qui la possèdent. Comme certains groupes possèdent déjà une description sur la page contact, cette PR vise à afficher également cette description sur les détails des casquettes directement liées à ces groupes.

### Contrôle qualité

- Vérifier que la page affichant les détails d'une casquette s'affiche correctement.
- Si la casquette est liée à un groupe, et que celui-ci est affiché sur la page de contact (objet `GroupContact`), vérifier que sa description sur la page contact est aussi reportée ici.

2018-08-22 21:23 UTC, nils-van-zuijlen commented
Est-ce qu'il serait possible d'avoir cette description de visible au survol de la casquette dans les messages ?

C'est demandé dans [ce thread du forum](https://zestedesavoir.com/forums/sujet/10405/suggestion-une-description-pour-les-casquettes/).

2018-08-22 21:23 UTC, firm1 commented
### Rapport qualité

Je tombe sur la même erreur qu'a rencontrée travis.

C'est à dire qu'en allant sur la page `http://localhost:8000/membres/casquettes/1/` qui correspond a la description du staff, j'ai une erreur 500.

Pour corriger le problème chez moi, j'ai rajouté `{% load emarkdown %}` en début du fichier `hat.html`

2018-08-23 11:18 UTC, gustavi requested changes

2018-08-23 11:18 UTC, gustavi commented on zds/member/views.py
> +                pass  # group not displayed on contact page
`context['groupcontact'] = None` me semble plus explicite que `pass` pour un résultat équivalent

2018-08-23 11:18 UTC, gustavi commented on zds/member/tests/tests_views.py
> +from zds.pages.models import GroupContact
Import à déplacer au dessus (tri par ordre alphabétique)

2018-08-23 12:17 UTC, gcodeur commented
Merci de vos retours, les problèmes remontés ont été corrigés !

> Est-ce qu'il serait possible d'avoir cette description de visible au survol de la casquette dans les messages ?

Rien d'impossible dans l'absolu, mais cela imposerait des jointures de plus ou une requête AJAX. Je ne sais pas si ça en vaut vraiment la peine et je préférerais voir ça dans un second temps.

2018-08-23 18:50 UTC, firm1 commented
La QA est désormais OK, et les tests passent : je merge.

Bravo pour le boulot et bon retour dans le game.

2018-08-23 18:50 UTC, merged