Vérifie si l'utilisateur a une adresse mail avant de lui envoyer un mail.
zestedesavoir/zds-site pull request #5019
Opened 2018-08-22 21:01 UTC by nils-van-zuijlen

Lors de l'inscription via OAuth (réseaux sociaux), un utilisateur peutr être crée sans adresse mail. Ceci cause des erreurs 500 lorsque l'on essaye de lui envoyer une notification par ce moyen.

Cette PR introduit une condition préalable à l'envoi de mails pour éviter ces erreurs.

Numéro du ticket concerné : #4943 

### Contrôle qualité

- Créez un compte avec une adresse mail vide (allez dans la BDD si besoin)
- Sur ce compte, demandez à recevoir toutes les notifications de MP
- Envoyez un MP à cet utilisateur à l'aide d'un autre compte normal.
- Il ne doit pas y avoir d'erreurs lors de l'envoi du MP.

2018-08-22 21:05 UTC, nils-van-zuijlen commented
Le test que j'ai écrit fail, mais je ne sais pas pourquoi...
J'ai l'output : 
```
(zdsenv) [nils@pineapple:zestedesavoir/zds-site][1]$ ./manage.py test zds.notification.tests.tests_tricky.SubscriptionsTest
Creating test database for alias 'default'...
 DEBUG  zds.utils.templatetags.emarkdown Result , {'disableToc': True, 'languages': [], 'depth': -1}, []
DEBUG:zds.utils.templatetags.emarkdown:Result , {'disableToc': True, 'languages': [], 'depth': -1}, []
 DEBUG  zds.utils.templatetags.emarkdown Result , {'disableToc': True, 'languages': [], 'depth': -1}, []
DEBUG:zds.utils.templatetags.emarkdown:Result , {'disableToc': True, 'languages': [], 'depth': -1}, []
F
======================================================================
FAIL: test_no_emails_for_those_who_have_none (zds.notification.tests.tests_tricky.SubscriptionsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nils/Developpement/zestedesavoir/zds-site/zds/notification/tests/tests_tricky.py", line 402, in test_no_emails_for_those_who_have_none
    self.assertEqual(1, len(mail.outbox))
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 1 test in 0.818s

FAILED (failures=1)
Destroying test database for alias 'default'...
(zdsenv) [nils@pineapple:zestedesavoir/zds-site][1]$
```

@artragis est-ce que tu sais ce qui peut faire que le mail n'est pas envoyé à l'utilisateur normal ?

2018-08-22 21:59 UTC, firm1 commented
Tu n'aurai pas tout simplement oublié de t'authentifier ?

```python
self.assertTrue(self.client.login(username=self.userOAuth1.username, password='hostel77'))
```

2018-08-22 22:13 UTC, nils-van-zuijlen commented
@firm1 Je viens d'essayer, merci pour l'idée, mais ce n'est pas ça.

2018-08-23 06:09 UTC, artragis requested changes

2018-08-23 06:09 UTC, artragis commented on zds/notification/tests/tests_tricky.py
> +        self.userOAuth1.email = ''
email vide donc pas de mail envoyé non?

2018-08-23 06:09 UTC, artragis commented on zds/notification/tests/tests_tricky.py
> +        self.userStandard1 = ProfileFactory().user
faudrait que tu forces l'utilisation d'un mail.

2018-08-23 06:09 UTC, artragis commented on zds/notification/tests/tests_tricky.py
> +        self.assertEqual(0, len(mail.outbox))
est-ce que userStandard1 a une adresse email?

2018-08-23 10:42 UTC, nils-van-zuijlen commented on zds/notification/tests/tests_tricky.py
> +        self.userStandard1 = ProfileFactory().user
C'est pas déjà fait là ?

https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/factories.py#L20

2018-08-23 10:44 UTC, nils-van-zuijlen commented on zds/notification/tests/tests_tricky.py
> +        self.assertEqual(0, len(mail.outbox))
Il y en a une définie dans la `UserFactory` par défaut.

2018-08-23 10:47 UTC, nils-van-zuijlen commented on zds/notification/tests/tests_tricky.py
> +        self.userOAuth1.email = ''
email vide donc pas de mail envoyé à cet utilisateur.

`send_message_mp(user, topic, content, send_by_mail=True)` envoie un mp aux autre participants au `topic` (MP) depuis l'utilisateur `user`.

Comme `send_by_mail` est `True` et que `userStandard1` a ses paramètres de notifications à "tous les MP et leurs réponses", il devrait recevoir un e-mail. (Non ?)

2018-08-23 11:15 UTC, gustavi commented on zds/notification/models.py
> +        # This can happen when an user subscribes via social networks without providing an e-mail adress
s/adress/address

2018-08-23 11:31 UTC, artragis commented on zds/notification/tests/tests_tricky.py
> +        self.assertEqual(0, len(mail.outbox))
donc le test semble faux ici : s'il y a une adresse email, la outbox doit être remplie.

2018-08-23 11:32 UTC, artragis commented on zds/notification/tests/tests_tricky.py
> +        self.userOAuth1.email = ''
userStandard devrait en avoir, et userOAuth1 ne devrait pas.

2018-08-23 11:38 UTC, nils-van-zuijlen commented on zds/notification/tests/tests_tricky.py
> +        self.assertEqual(0, len(mail.outbox))
Ben, non. L'auteur d'un message n'est pas notifié de son envoi.

2018-08-23 11:38 UTC, nils-van-zuijlen commented on zds/notification/tests/tests_tricky.py
> +        self.userOAuth1.email = ''
Oui. C'est ça.

2018-08-23 19:18 UTC, gcodeur commented on zds/notification/models.py
> +        # This can happen when an user subscribes via social networks without providing an e-mail address
A~n~ user.

2018-09-05 11:38 UTC, artragis commented
Peux-tu rebaser ta MR s'il te plait. Je regarderai le tout ce week end. Ce bug est trop important pour êtr elaissé de côté.

2018-09-08 11:21 UTC, artragis requested changes

2018-09-08 11:21 UTC, artragis commented on zds/notification/tests/tests_tricky.py
> +        self.userStandard1.profile.email_for_answer = True
la cause du fail du test est ici : tu save l'object user, mais pas l'object profile. J'ai un petit diff qui corrige tout ça : 

```diff
--- a/zds/notification/tests/tests_tricky.py
+++ b/zds/notification/tests/tests_tricky.py
@@ -371,13 +371,13 @@ class ContentNotification(TestCase, TutorialTestMixin):
 @override_settings(EMAIL_BACKEND='django.core.mail.backends.locmem.EmailBackend')
 class SubscriptionsTest(TestCase):
     def setUp(self):
-        self.userStandard1 = ProfileFactory().user
-        self.userOAuth1 = ProfileFactory().user
-
-        self.userStandard1.profile.email_for_answer = True
-        self.userOAuth1.profile.email_for_answer = True
-        self.userStandard1.profile.email_for_new_mp = True
-        self.userOAuth1.profile.email_for_new_mp = True
+        self.userStandard1 = ProfileFactory(
+            email_for_answer=True,
+            email_for_new_mp=True
+        ).user
+        self.userOAuth1 = ProfileFactory(
+            email_for_answer=True,
+            email_for_new_mp=True).user
 
         self.userOAuth1.email = ''
 
@@ -389,7 +389,6 @@ class SubscriptionsTest(TestCase):
         Test that we do not try to send e-mails to those who have not registered one.
         """
         self.assertEqual(0, len(mail.outbox))
-
         topic = send_mp(author=self.userStandard1, users=[self.userOAuth1],
                         title='Testing', subtitle='', text='',
                         send_by_mail=True, leave=False)
```

2018-09-08 12:14 UTC, artragis commented on zds/notification/models.py
> +        if not receiver.email:
ici j'ajouterais même : 

```python
from django.core.validators import email_re

"""
...
"""
if not receiver.email or not email_re.match(receiver.email):
```

2018-09-08 12:44 UTC, nils-van-zuijlen commented on zds/notification/models.py
> +        if not receiver.email:
Bonne idée.

2018-09-08 12:57 UTC, nils-van-zuijlen commented on zds/notification/models.py
> +        if not receiver.email:
Hum, y'a un petit pb :
```
  File "/home/nils/Developpement/zestedesavoir/zds-site/zds/notification/models.py", line 8, in <module>
    from django.core.validators import email_re
ImportError: cannot import name 'email_re'
```

2018-09-08 13:03 UTC, artragis commented on zds/notification/models.py
> +        if not receiver.email:
en effet, les choses semblent avoir changé, le code serait aujourd'hui : 

```python
from django.core.validators import validate_email

try:
    validate_email(receiver.email)  # il fait lui même le check de "ça existe et c'est valide"
except ValidationError:
    return
```

2018-09-09 07:46 UTC, artragis commented
QA OK

2018-09-09 07:46 UTC, artragis approved these changes

2018-09-09 07:46 UTC, merged