[WIP] Permet de signaler un profil
zestedesavoir/zds-site pull request #5033
Opened 2018-08-27 11:40 UTC by gcodeur

[Proposée ici](https://zestedesavoir.com/forums/sujet/9222/nouvelle-page-de-profil/?page=2#p187216), cette pull request ajoute un système de signalement sur les profils, qui permet d'envoyer une alerte au staff comme sur les forums ou les billets. Le but est essentiellement de pouvoir signaler les profils créés pour faire de la publicité dans la biographie ou la signature, mais peut aussi être utilisé en cas de contenu illégal (étant donné qu'on peut mettre n'importe quoi sur son profil sans validation).

À noter que j'ai fait une implémentation dans l'interface de profil actuelle. Étant donné que @firm1 travaille sur une nouvelle interface, je propose de *merge* sa PR (#5025) d'abord, puis j'adapterai la mienne.

Les tests sont d'ailleurs encore à écrire. En revanche, il est possible de faire de la QA dès maintenant.

### TODO

- [ ] Les tests
- [ ] Merge de #5025, cette PR sera adaptée ensuite

### Contrôle qualité

- Vérifier qu'il est possible de signaler un profil et de résoudre l'alerte créée, avec ou sans message.
- Vérifier que les autres systèmes de signalements ne sont pas impactés.
- Vérifier que la page "Toutes les alertes" fonctionnement correctement.
- Relecture du code.

2018-08-27 11:53 UTC, gustavi requested changes

2018-08-27 11:53 UTC, gustavi commented on templates/member/sidebar.html
> +                        <textarea type="text" name="reason" id="report-reason" placeholder="Spam, Contenu illégal, …" pattern=".{3,}" required title='{% trans "Minimum 3 caractères pour signaler" %}'
i18n sur `placeholder`

2018-08-27 11:53 UTC, gustavi commented on zds/member/views.py
> +@login_required
Je vais faire le casse c***** mais on peut utiliser des CBV au lieu de fonctions ? Si besoin peux m'occuper de te faire le changement.

2018-08-27 20:31 UTC, gcodeur commented
@gustavi : je viens d'éditer la PR pour utiliser des CBV. Par contre, j'ai utilisé `View` car aucune classe plus spécifique ne m'a semblé correspondre. Est-ce que ça te paraît bien ?

2018-08-28 11:32 UTC, gustavi commented on zds/member/views.py
> +        if not reason:
`if reason == ''`

2018-08-28 11:33 UTC, gustavi commented on zds/member/views.py
> +    http_method_names = ['post']
Je crois que c'est pas nécessaire (à tester, j'ai rien sous la main pour vérifier ce que je dis)

2018-08-28 11:33 UTC, gustavi commented on zds/member/views.py
> +class CreateProfileReportView(LoginRequiredMixin, View):
<3

2018-08-28 11:35 UTC, gustavi commented
Merci c'est parfait ! Si jamais on avait utilisé un formulaire Django alors FormView aurait été adapté mais là ça me convient comme manière de faire.

Un petit changement et niveau code review c'est valide.

2018-08-28 12:31 UTC, gcodeur commented on zds/member/views.py
> +    http_method_names = ['post']
En effet, toujours `HTTP ERROR 405` sans cette ligne, je l'enlève.

2018-09-12 20:04 UTC, gcodeur commented
À noter que la QA de cette PR est possible vu qu'elle est terminée et fonctionnelle en l'état (c'est pour ça que j'avais enlevé le WIP). Le seul problème est qu'elle touche à la page de profil, donc entre en conflit avec #5025. Un ajustement (mineur) sera nécessaire.

A priori, j'étais plutôt partant pour *merge* la PR de @firm1 en premier. Si elle tend à devenir longue, il vaut peut-être mieux merger celle-ci d'abord, mais dans ce cas, je peux ensuite faire une PR vers le repo de @firm1 pour proposer directement une intégration dans la nouvelle page de profil.

2018-09-12 20:55 UTC, firm1 commented
> Si elle tend à devenir longue, il vaut peut-être mieux merger celle-ci d'abord,

J'ai envie de dire que si ta feature est prête, on peut l'intégrer sans trop attendre.

2018-12-29 13:06 UTC, gcodeur commented
Je pense que cette PR peut être mergée maintenant. J'ai fait un rebase et vérifié que tout fonctionne toujours correctement.

2018-12-29 13:17 UTC, Situphen commented
J'ai enlevé l'étiquette Zombie et le WIP du titre. Dans la description tu dis que tu attends que la PR #5025 soit mergée, je suppose que ce n'est plus le cas : est-ce que tu peux éditer la description en conséquence ? :)

2018-12-29 13:26 UTC, gllmc commented
Voilà qui est fait !

2019-04-10 10:04 UTC, A-312 commented
Vous avez prévu quoi pour cette PR ? Elle peut être merge avant l'autre

2019-04-18 10:42 UTC, artragis commented
@gcodeur tu es dispo pour faire le rebase ou bien tu préfères que je m'y colle?

2019-05-16 11:18 UTC, artragis commented
Je vais faire le rebase et merger

2019-05-16 11:19 UTC, closed without merging