Ajout d'un box-shadow au message pointé par un lien vers un message
zestedesavoir/zds-site pull request #5039
Opened 2018-08-30 14:56 UTC by nils-van-zuijlen

La cible du lien vers un message change : Ce n'est plus le lien de la date mais tout le message.

Numéro du ticket concerné : #3341 

### Contrôle qualité

- Reconstruisez le front `make build-front`
- Vérifiez que les messages pointés dans l'url ont un contour bleu mais pas les autres.
- Vérifiez que les urls qui pointent vers un message fonctionnent bien.

2018-09-11 18:36 UTC, Eskimon commented
Tester sur firefox, a priori le concept fonctionne.

Si certains veulent émettre un avis sur l'esthetique, voici une capture d'écran du résultat :

![screenshot from 2018-09-11 20-35-44](https://user-images.githubusercontent.com/761168/45380181-64ac3f80-b602-11e8-9c8e-229b119debf8.png)

2018-09-12 07:33 UTC, Eskimon commented
Je sais pourquoi le shadow me dérange ! Je pense que implicitement ca me fait penser à une sélection ou un focus. Hors là c'est juste une mise en valeur, pas un vrai focus dans lequel je vais saisir quelque chose. Vous m'suivez ?

2018-09-12 07:49 UTC, firm1 commented
Moi j'ai pas trop d'avis. Il me semble que github fait comme ça aussi pour
l'highlight des permalink.

Le mer. 12 sept. 2018 à 09:33, Eskimon <notifications@github.com> a écrit :

> Je sais pourquoi le shadow me dérange ! Je pense que implicitement ca me
> fait penser à une sélection ou un focus. Hors là c'est juste une mise en
> valeur, pas un vrai focus dans lequel je vais saisir quelque chose. Vous
> m'suivez ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/5039#issuecomment-420543532>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFyPX0Ufws9k3GQO2bdxNDh6Nk7TnwHjks5uaLi5gaJpZM4WTpUH>
> .
>

2018-09-12 07:56 UTC, Eskimon commented
> Il me semble que github fait comme ça aussi pour l'highlight des permalink.

Effecivement. Il fait la même mise en forme pour le focus de la rédaction et le highlight.

![screenshot from 2018-09-12 09-55-49](https://user-images.githubusercontent.com/761168/45410503-26e6ff80-b672-11e8-9177-03aee3f8706f.png)

2018-09-12 17:37 UTC, nils-van-zuijlen commented
C'est pas mes modifs qui ont fait bug Travis.

2018-09-12 19:19 UTC, firm1 commented
> Effecivement. Il fait la même mise en forme pour le focus de la rédaction et le highlight.

Du coup, je sais pas. Moi ça ne me dérange pas tant que ça.

2018-10-30 09:52 UTC, Situphen commented
Je n'aime pas trop l'ombre, surtout qu'elle ne suit pas totalement le contour (on peut voir sur le screen d'Eskimon qu'elle passe sous la flèche près de l'avatar et la banderole "Auteur du sujet"). Si on prend un changement de couleur comme alternative, ça donne ça (j'ai pris du orange au hasard, il faudrait choisir une meilleure couleur) : 

![image](https://user-images.githubusercontent.com/6664636/47709670-08908f80-dc31-11e8-9b90-857d159347b3.png)

J'ai fait ça vite fait avec la console de développement de Firefox. Il faut apporter plusieurs modifications : 

- pour `.topic-message .message`, `border-color` qui change
- pour `.topic-message .user::after`, `border-right-color` qui change
- pour `.topic-message .message .is-author`, `border-top-color` qui change
- pour `.topic-message .message .is-author::after` et `.topic-message .message .is-author::before`, `background-color` qui change

Il faudrait donc probablement mettre l'id en `.topic-message` pour pouvoir changer tous les éléments

2018-11-12 21:47 UTC, nils-van-zuijlen commented
![](https://screenshotscdn.firefoxusercontent.com/images/c2cca9f5-ed5b-4050-aa54-d9e955385ec9.png)
![](https://screenshotscdn.firefoxusercontent.com/images/a6ccab9d-a1ff-41b5-a0c1-d5ad5c949a1d.png)

Est-ce que c'est mieux avec la bordure et pas l'ombre ?
Et quelle couleur prendre  ?

2018-11-12 22:08 UTC, Situphen commented
Si on part sur du bleu, il vaudrait mieux partir sur le même bleu que les liens je pense : `$color-message-emphasis: lighten($color-primary, 20%);` !

Par contre, je vous avoue que les deux solutions ne me convienne pas. La première n'est pas très esthétique car l'ombre ne respecte pas bien le contour, mais on voit bien que c'est un focus sur le message. La deuxième respecte le contour mais on ne sait pas trop pourquoi la couleur à changer, il n'y a pas cette effet intuitif de "c'est le message avec le focus"

2018-11-12 22:20 UTC, nils-van-zuijlen commented
Le problème, c'est que, dans l'état actuel des choses, on ne peut pas utiliser de shadow et respecter les contours donc il va falloir choisir :
![](https://screenshotscdn.firefoxusercontent.com/images/daea7db7-9234-4805-ae04-eb101981f7df.png)

2018-11-12 22:22 UTC, Situphen commented
Hum, je suis plutôt d'avis de soit trouver une alternative aux deux solutions, soit ne rien faire (il vaut mieux rien que quelque chose de pas esthétique ou pas compréhensible sur ce genre de problème)

2020-01-01 16:27 UTC, Situphen commented
Petit up ! Bien que datant d'un an, la branche se met facilement à jour avec `upstream/dev` donc c'est cool.

Dans l'état actuel, cette PR propose que la bordure complète du message soit bleu quand on vient de cliquer un lien qui cible ce message.

![Aperçu du contour complet](https://user-images.githubusercontent.com/6664636/71643586-db6bc100-2cbb-11ea-880f-8205fc3f9c25.png)

J'aime bien mais je trouve ça un peu trop chargé, je propose donc deux alternatives dans les messages suivants. Je vous laisse voter avec +1 et -1.

2020-01-01 16:28 UTC, Situphen commented
Un alternative est de mettre en bleu seulement le côté gauche.

![Aperçu bordure gauche](https://user-images.githubusercontent.com/6664636/71643605-0fdf7d00-2cbc-11ea-8be6-0144d377e97e.png)

2020-01-01 16:28 UTC, Situphen commented
Une autre alternative est de mettre en bleu le côté gauche et le haut.

![Aperçu bordure gauche et haute](https://user-images.githubusercontent.com/6664636/71643613-2c7bb500-2cbc-11ea-8fe8-24b411212969.png)

2020-01-01 16:54 UTC, A-312 commented
Autre possibilité : Rendre orangé l'header en haut, soit par une ombre, soit par la couleur de la police, le hover est bleu, on peu mettre le focus/active orange ?

SOLUTION A : 
![image](https://user-images.githubusercontent.com/18501150/71643771-e58ebf00-2cbd-11ea-8b22-c6545868240c.png)

 - La couleur est un peu vive ;
 - Il faut une version orange des icônes ;
 - Trop lourd ?

SOLUTION B : 
 - Léger mais peut-être modifié la couleur
![image](https://user-images.githubusercontent.com/18501150/71643835-dc522200-2cbe-11ea-9268-8df6e7fe5558.png)

SOLUTION C : 

 - Trop lourd/Mal équilibré.

![image](https://user-images.githubusercontent.com/18501150/71643851-220eea80-2cbf-11ea-8e66-654b26f03e3e.png)

---------- 

Après j'aime bien le comportement actuel du focus en bleu : 
![image](https://user-images.githubusercontent.com/18501150/71643882-8fbb1680-2cbf-11ea-8968-7420e4d64929.png)

Il ne suffirait pas mieux de faire un fixe sur firefox plutôt que de modifier le comportement actuel ?

2020-01-01 16:59 UTC, A-312 commented
D'ailleurs on dépasse la scope de #3341, il faudrait se mettre d'accord sur un rendu visuel avant de passer cette PR.

2020-01-01 17:00 UTC, A-312 requested changes
D'ailleurs on dépasse la scope de #3341, il faudrait se mettre d'accord sur un rendu visuel avant de passer cette PR.

2020-05-03 10:16 UTC, Arnaud-D commented
J'ai fait quelques essais dans mon coin. Je suis assez partant pour la solution "bordure sur le côté gauche", mais avec un peu d'épaisseur

Variante bleue (ma préférée, avec le bleu des liens) :

![image](https://user-images.githubusercontent.com/35631001/80911520-1dbf1080-8d37-11ea-99a4-fc60ed0c4c5a.png)

Variante orange :

![image](https://user-images.githubusercontent.com/35631001/80911563-56f78080-8d37-11ea-8787-eb7b3fe02442.png)

Je pense qu'une solution avec *shadow* ne rendra jamais bien sur notre design actuel, parce que contrairement à GitHub, nos cadres ne sont pas aussi nets, notamment parce que la pointe est grosse et qu'on a le petit onglet "auteur" qui dépasse.

2022-03-17 20:11 UTC, Situphen commented
Fermé par décision de la réunion des devs car le CSS des messages a été totalement refait

2022-03-17 20:11 UTC, closed without merging