Corrige le clignotement sous Chrome
zestedesavoir/zds-site pull request #5056
Opened 2018-09-04 14:58 UTC by A-312

Corrige : #5020 

Q/A : Vérifier sous chrome que ça ne clignote pas quand on est sur la fameuse colonne d'un pixel de largeur.

2018-09-05 10:06 UTC, gustavi requested changes

2018-09-05 10:06 UTC, gustavi commented on assets/scss/layout/_sidebar.scss
> +                        left: calc(100% + 1px); /*Fix #5020 : Clignotement de la Tooltip*/
En anglais le commentaire

2018-09-05 10:24 UTC, A-312 commented on assets/scss/layout/_sidebar.scss
> +                        left: calc(100% + 1px); /*Fix #5020 : Clignotement de la Tooltip*/
prevent tooltip flickering

2018-09-05 10:25 UTC, A-312 commented
OUPS, j'ai oublié de sauvegarder ma branche avant de changer >.<

2018-09-12 20:22 UTC, gllmc approved these changes
Rapport qualité : **OK**

Un rebase est nécessaire et on pourra *merge*. :)

2018-09-19 22:22 UTC, A-312 commented
Rebase OK

2018-09-20 07:37 UTC, merged