[WIP]Nouvelle interface d'upload des images
zestedesavoir/zds-site pull request #5071
Opened 2018-09-15 12:46 UTC by artragis

Voici donc la PR pour implémenter l'ajout automatique d'image via le drag&drop.

# A faire avant que ça soit Qatisable

- [x] gérer le cas de la gallerie par défaut, et de la gallerie des tuto
- [ ] le JS pour uploader au drag&drop.
- [ ] quelques tests du context_processor

2018-09-22 18:29 UTC, pierre-24 commented on zds/gallery/auto_upoload_gallery.py
> +from django.http.request import HttpRequest
typo: `auto_upoload` :)

2018-09-22 19:30 UTC, artragis commented on zds/gallery/auto_upoload_gallery.py
> +from django.http.request import HttpRequest
oO

2018-10-11 22:28 UTC, A-312 commented
Cette PR est seulement pour la galerie ? Je voulais proposer une PR pour l'upload du logo durant la création de billet. L'histoire que je ne rentre pas en concurrence avec celle-ci.

2018-10-15 07:16 UTC, artragis commented
@A-312  cette PR a pour but de faciliter l'ajout d'image dans les différents textes (forum, billets, tuto etc.) en uploadant au drag&drop et au copier/coller.

2018-10-15 11:53 UTC, AmauryCarrade commented on zds/gallery/auto_upload_gallery.py
> +        gallery = Gallery(title='Gallerie par défaut', subtitle='', slug='gallerie-default')
Typo : _Galerie par défaut_ en français (deux l uniquement en anglais). Idem pour le slug, du coup :) .

2018-10-15 12:46 UTC, sandhose commented on zds/gallery/auto_upload_gallery.py
> +        gallery = Gallery(title='Gallerie par défaut', subtitle='', slug='gallerie-default')
Aussi pour le slug, je dirais soit `galerie-defaut`, soit `default-gallery`

2018-10-15 17:18 UTC, A-312 commented on zds/gallery/auto_upload_gallery.py
> +        gallery = Gallery(title='Gallerie par défaut', subtitle='', slug='gallerie-default')
soit `galerie-par-defaut` 😛

2018-10-29 20:31 UTC, Situphen approved these changes
Sur la forme, il y a deux choses pas importantes mais je le dis quand même : 

- on a l'habitude d'utiliser des doubles guillemets si possible dans les fichiers JS du dépôt, ici il y a un mélange entre guillemets simples et doubles (ce sont les conventions Python qui débordent :D )
- l'URL des fichiers téléversés on deux barres obliques (`/media//...`), ce qui n'est pas gênant mais c'est perturbant et pas très beau (mais si j'ai bien compris ça vient du code de l'API et pas du tien)

Sur le fond, ça fonctionne très bien sur ordinateur ! Il faudra plus tard ajouter un bouton dans l'éditeur pour ajouter des fichiers vers un formulaire, comme ça sur mobile ça sera très bien aussi. Mais ce sera pour une prochaine PR :)

2018-10-29 20:31 UTC, Situphen commented on assets/js/editor.js
> +        $.ajax(
Je trouve cette partie difficile à lire à cause de l'indentation. Je propose ça : 

```js
         $.ajax({
            url: galleryUrl,
            data: formData,
            type: 'POST',
            processData: false,
            contentType: false,
            headers: {
                "X-CSRFToken": csrf
            },
            dataType: 'json'
        }).done(function (result) {
            var mdFinalCode = '![' + result.legend + '](' + result.url +')';

            editor.val(editor.val().replace(new RegExp(mdWaitingRegexp), mdFinalCode));
        }).fail(function () {
            editor.val(editor.val().replace(new RegExp(mdWaitingRegexp), ''));
        });
```

2018-10-29 20:36 UTC, Situphen commented on assets/js/editor.js
> -    "use strict";
Alors je crois bien qu'en déplaçant ça après ton code, tu as muté `jslint` :)

2018-10-30 09:50 UTC, artragis commented on assets/js/editor.js
> -    "use strict";
Cela explique pourquoi il n'a pas ralé sur les simple quotes.

2018-10-30 10:05 UTC, artragis commented on assets/js/editor.js
> +        $.ajax(
fixed.

2018-10-30 10:06 UTC, artragis commented
merci pour la review @Situphen j'ai corrigé le problème des doubles slash

2018-11-01 14:06 UTC, A-312 commented
Sous Firefox 63 / Windows je n'ai aucun effet visuel qui m'indique que je peux drag'n'drop sans que ça me fasse changer de page vers `file:///C:/Users/A312/...`

2018-11-01 21:05 UTC, artragis commented
> Sous Firefox 63 / Windows je n'ai aucun effet visuel qui m'indique que je peux drag'n'drop sans que ça me fasse changer de page vers file:///C:/Users/A312/... mais sinon le fichier est bien pris en compte.

j'ai déjà eu ce problème. @sandhose et @Situphen confirmeront mais c'est peut être parce que le "drop" par défaut n'est pas overridé quand on est ailleurs que sur la textbox. Je ne sais pas si c'est une bonne pratique de mettre un `preventDefault` sur l'élément body.

2018-11-02 15:44 UTC, artragis commented
@A-312 chez moi il y a bien un effet visuel autour de la textbox quand on fait un drag&drop

2018-11-02 17:26 UTC, A-312 commented
> @A-312 chez moi il y a bien un effet visuel autour de la textbox quand on fait un drag&drop

J'essayais dans la galerie. X/ Je viens de découvrir que le navigateur autorise le drag'n'drop sur un input type=file. :o

-----

Sinon l'effet dans le textbox est instable. :/ Il n'apparait pas à chaque fois si on fait un cercle avec le fichier par exemple.

2018-11-02 19:41 UTC, A-312 commented
Et quelques choses comme ça pour le css : 

```
box-shadow: 0 0 4px orange;
```

Ou en bleu : 
```
box-shadow: 0 0 4px rgba(0,0,255,0.5);
outline: 1px solid rgba(0,0,255,0.1);
```

2018-11-02 20:42 UTC, artragis commented
ping @sandhose ou @Situphen vous pensez quoi de la proposition de @A-312 ? (mettez +/- comme ça j'appliquerai)

2018-11-03 05:57 UTC, Situphen commented
Intuitivement je dirais que du bleu irait mieux que du orange, mais je te testerai ça cette après-midi :)

2018-11-03 22:04 UTC, Situphen commented
Alors je viens de tester la proposition de @A-312 et j'aime beaucoup le bleu ! Par contre je propose qu'on utilise une nuance de bleu déjà utilisée sur le site (celle utilisée pour la couleur des liens)  : 

```scss
.md-editor.selected {
    box-shadow: 0 0 4px lighten($color-primary, 20%);
    outline: 1px solid lighten($color-primary, 20%);
}
```

2018-11-04 12:59 UTC, Situphen commented
@artragis Il reste quoi à faire avant de merger ?

2018-11-04 21:03 UTC, artragis commented
moi j'ai fini, donc là si la QA dit OK et que la review l'est aussi, on merge.

2018-11-04 22:17 UTC, Situphen commented
Pour la review c'est OK pour moi !
Pour la QA, je me rends compte que j'ai seulement testé l'ajout dans un message du forum ou un message privé, mais pas dans un contenu. Donc il reste juste ça à QA et c'est bon.

2018-11-05 19:12 UTC, artragis commented
je te laisse faire le merge dès que tu as terminé la QA.

2018-11-05 20:26 UTC, Situphen requested changes
J'ai du faire ces deux petits changements chez moi pour que l'image soit bien envoyée à la galerie liée au contenu.

Aussi, il n'y a pas d'erreur quand l'image pèse trop lourd et est rejetée par l'API. Ça serait pas mal dans mettre une (je ne sais pas sous quelle forme) car sinon on va avoir des rapports de bug "le drag'n'drop ne fonctionne pas chez moi" :)

2018-11-05 20:26 UTC, Situphen commented on zds/gallery/auto_upload_gallery.py
> +    if not content or user not in [content.authors.all()]:
```suggestion
    if not content or user not in content.authors.all():
```

2018-11-05 20:26 UTC, Situphen commented on zds/gallery/auto_upload_gallery.py
> +    if request.user.is_authenticated() and is_url_of_content and 'pk' in request.resolver_match:
```suggestion
    if request.user.is_authenticated() and is_url_of_content and 'pk' in request.resolver_match.kwargs:
```

2018-11-05 20:52 UTC, artragis commented on zds/gallery/auto_upload_gallery.py
> +    if not content or user not in [content.authors.all()]:
tu es sûr pour celui là? c'est le seul qui me parît étrange.

2018-11-05 20:52 UTC, artragis commented on zds/gallery/auto_upload_gallery.py
> +    if request.user.is_authenticated() and is_url_of_content and 'pk' in request.resolver_match:
bien vu !

2018-11-05 20:53 UTC, artragis commented
@Situphen pour les erreurs, je vais regarder comment faire. C'est combien la taille max?

2018-11-05 22:24 UTC, Situphen commented
1 Mo je crois, c'est [défini dans les paramètres](https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings/abstract_base/zds.py#L146)

2018-11-06 12:41 UTC, artragis commented
j'ai réglé ça @Situphen

2018-11-06 20:53 UTC, Situphen commented on doc/source/back-end-code/gallery.rst
> +Le context processor pour trouver la gallerie automatique (``auto_upload_gallery.py``)
```suggestion
Le context processor pour trouver la galerie automatique (``auto_upload_gallery.py``)
```

2018-11-07 16:16 UTC, Situphen approved these changes

2018-11-07 16:59 UTC, Situphen commented
**Rapport de QA :** Tout est parfait ! Merci @artragis !

2018-11-07 16:59 UTC, merged