reduce code duplication in zds/forum/feeds.py
zestedesavoir/zds-site pull request #5082
Opened 2018-10-13 15:21 UTC by gasche

C'est juste une petite PR de refactoring de code. Il y a pas mal de redondance dans le code de ZDS et ça me démange régulièrement de faire des PRs de ce genre.

Le problème c'est que je n'ai pas pu tester cette PR parce que je n'ai pas réussi, avec un degré d'efforts raisonnables, à installer le backend à nouveau chez moi (ça avait marché la dernière fois, il y a quelques années). Cf. #5081, mais j'ai eu plein d'ennuis à la con en plus (genre `make install-back` marche une fois sur deux, make ensuite `python migrate.py` foire avec 

```python
ImportError: No module named colorlog
```

J'aimerais faire d'autres PRs de ce genre à l'occasion. Là, j'en envoie une toute petite pour tester et voir comment ça se passe. Je pense qu'il y a plusieurs choix :

- vous vous contentez de relire le code et de vous convaincre que c'est un refactoring qui ne change pas le comportement, et vous avec assez d'intégration continue pour qu'une typo se fasse détecter de toute façon; oui bien,
- l'un d'entre vous a un environnement de dev sur sa machine qui lui permet de tester facilement (moi je ne peux pas); ou bien,
- vous trouver une façon de rendre le site moins chiant à installer (ça ne doit pas prendre plus d'une demi-heure sur une machine; j'ai dépassé rien qu'avec la réinstallation de texlive quand j'ai fait `make install-linux-full` naïvement); ou bien,
- rien de tout cela ne vous convainc, et je pense que je devrai laisser tomber l'idée de faire du refactoring sur la base de code.

2018-10-13 16:30 UTC, pierre-24 commented
Chui un peu ennuyé. Ok, j'ai oublié le Makefile, mais c'est bien moi qui me
suis cassé la tête a simplifier le processus d'installation, et la doc dis
clairement que "make install-linux" suffit (
https://docs.zestedesavoir.com/install/install-linux.html). L'installation
de texlive est optionelle, d'ailleurs pour les raisons que tu cites.

Objectivement, je vois pas quoi faire de plus. On a hurlé "on veut pouvoir
installer ZdS facilement", c'est le cas (je pense) et c'est dans la doc.
Qu'est ce que tu veux qu'on fasse de plus ? Et évidement, c'est le problème
de la commande unique, quand ça foire, ben tu sais pas quoi faire, raison
pour laquelle je préférais la méthode étape par étape, ca fait un peu geek,
mais au moins on sais ce qui se passe. Bref.

Par contre, j'entends bien que t'as un problème avec un package python. Ca,
c'est intéressant et ennuyeux. Mais pas besoin de venir remettre tout le
processus en question pour autant. On est la pour aider.

Peace.

On Sat, Oct 13, 2018, 5:21 PM Gabriel Scherer <notifications@github.com>
wrote:

> C'est juste une petite PR de refactoring de code. Il y a pas mal de
> redondance dans le code de ZDS et ça me démange régulièrement de faire des
> PRs de ce genre.
>
> Le problème c'est que je n'ai pas pu tester cette PR parce que je n'ai pas
> réussi, avec un degré d'efforts raisonnables, à installer le backend à
> nouveau chez moi (ça avait marché la dernière fois, il y a quelques
> années). Cf. #5081 <https://github.com/zestedesavoir/zds-site/issues/5081>,
> mais j'ai eu plein d'ennuis à la con en plus (genre make install-back
> marche une fois sur deux, make ensuite python migrate.py foire avec
>
> ImportError: No module named colorlog
>
> J'aimerais faire d'autres PRs de ce genre à l'occasion. Là, j'en envoie
> une toute petite pour tester et voir comment ça se passe. Je pense qu'il y
> a plusieurs choix :
>
>    - vous vous contentez de relire le code et de vous convaincre que
>    c'est un refactoring qui ne change pas le comportement, et vous avec assez
>    d'intégration continue pour qu'une typo se fasse détecter de toute façon;
>    oui bien,
>    - l'un d'entre vous a un environnement de dev sur sa machine qui lui
>    permet de tester facilement (moi je ne peux pas); ou bien,
>    - vous trouver une façon de rendre le site moins chiant à installer
>    (ça ne doit pas prendre plus d'une demi-heure sur une machine; j'ai dépassé
>    rien qu'avec la réinstallation de texlive quand j'ai fait make
>    install-linux-full naïvement); ou bien,
>    - rien de tout cela ne vous convainc, et je pense que je devrai
>    laisser tomber l'idée de faire du refactoring sur la base de code.
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/zestedesavoir/zds-site/pull/5082
> Commit Summary
>
>    - reduce code duplication in zds/forum/feeds.py
>
> File Changes
>
>    - *M* zds/forum/feeds.py
>    <https://github.com/zestedesavoir/zds-site/pull/5082/files#diff-0>
>    (45)
>
> Patch Links:
>
>    - https://github.com/zestedesavoir/zds-site/pull/5082.patch
>    - https://github.com/zestedesavoir/zds-site/pull/5082.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/zestedesavoir/zds-site/pull/5082>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHhjCwNxDnXeoi7mzcfOGzhWlCshQwq8ks5ukgUMgaJpZM4XarUZ>
> .
>

2018-10-13 20:41 UTC, gasche commented
J'étais un peu à chaud dans mon message précédent, mais je ne veux pas donner l'impression d'être choqué par les problèmes d'installation. Une stack avec des composants variés, sur des distributions différentes, etc., il me semble normal qu'il y ait des petits accrocs de temps en temps .Si j'étais un contributeur régulier, j'aurais corrigé tous ces soucis et la plupart du temps je n'aurais rien à faire pour lancer un test. Mais pour un "drive-by commit", sachant que j'utilise une distribution moins courante que les autres (Fedora), c'est juste trop compliqué de maintenir un truc qui marche de façon robuste. C'est comme ça, c'est la vie, et je ne me plains pas : mais du coup j'explique pourquoi je n'ai pas testé le code et quels sont les choix.

(En fait je viens de refaire un `make install-linux` et ça a l'air de mieux marcher. Je crois que j'ai fait une incantation pour entrer dans le virtualenv avant, mais je ne sais pas si ça change quelque chose.)

(Par ailleurs, est-ce que vous savez pourquoi le test du CI travis échoue ? C'est le [test frontend](https://travis-ci.org/zestedesavoir/zds-site/jobs/441025597) qui échoue, visiblement à cause de problème côté LaTeX ?)

Je me demande ce que vous pensez du patch lui-même, de l'idée de faire ce genre de nettoyages dans le code.

2018-10-13 20:48 UTC, artragis commented
aucun test n'échoue, c'est pep8 qui râle : 

```python
./zds/forum/feeds.py:8:1: E302 expected 2 blank lines, found 1
```

2018-10-13 20:56 UTC, gasche commented
Merci ! J'avais raté ça dans le log. Je corrige.

2018-10-14 08:17 UTC, artragis commented
je mergerai ça quand la v27.3 sera sortie (donc quand #5077 et #5072 seront validées)

2018-10-14 09:44 UTC, artragis requested changes

2018-10-14 09:44 UTC, artragis commented on zds/forum/feeds.py
> +class ItemFeed(Feed):
plutôt que d'hériter ItemFeed de feed, j'aurai plutôt fait : 

```python
class ItemFeedMixin:
    """les méthodes communes"""

class LastPostFeedRss(Item, ItemFeedMixin):
    """le reste"""

2018-10-14 09:44 UTC, artragis commented on zds/forum/feeds.py
> +def get_request_object(request):
j'aurais du coup mis  `get_object(self, request)` dans le mixin et pas besoin d'en faire une fonction extérieure.

2018-10-14 10:31 UTC, gasche commented on zds/forum/feeds.py
> +class ItemFeed(Feed):
Bien vu, j'ai fais ça (`ItemMixin` plutôt que `ItemFeedMixin`, puisque c'est indépendant de l'aspect Feed), et puis ObjectMixin plutôt qu'une fonction `get_request_object`.

2018-10-14 10:32 UTC, gasche commented on zds/forum/feeds.py
> +def get_request_object(request):
`get_object` n'a rien à voir avec le concept "Item" de ces classes, il est juste là pour traiter un objet de requête. J'en ai fait un mixin différent.

2018-10-14 13:26 UTC, gasche commented
(En fait le fait de mettre `get_object` dans un mixin séparé ne marche pas, je ne sais pas pourquoi, donc je suis revenu à une fonction externe.)

2018-10-15 11:28 UTC, gasche commented
Le test automatique de Codacity n'aime pas cette PR, mais en fait que son warning (qui vient du fait que les codes des méthodes que j'ai déplacées ne dépend pas de `test`) n'est pas très pertinent ici, et qu'on peut l'ignorer.

2018-10-15 12:15 UTC, artragis commented
codacy est buggé, ignore-le.

2018-10-15 13:39 UTC, AmarOk1412 commented
Faudra vraiment l'enlever un jour btw.

2018-10-15 15:16 UTC, artragis commented
il est déjà enlevé. C'est @motet-a qui a laissé son propre lien.

2018-10-16 11:49 UTC, gasche commented
(Je crois que tous les changements demandés ont été effectués)

2018-10-16 12:15 UTC, artragis commented
dès que @sandhose sera d'accord pour merger ma PR sur l'export des contenus et que la v27.3 sera en prod tu n'auras plus qu'à faire un rebase.

2018-10-21 08:03 UTC, gasche commented
Je ne comprends pas trop pourquoi vous faites attendre cette PR sur une autre PR #5072 qui n'a rien à voir. 

Est-ce que c'est une façon d'éviter les conflits ? Mais je n'ai pas l'impression qu'il y ait des conflits entre les deux PRs (elles touchent des fichiers différents).

Ça m'est un peu égal et vous faites bien comme vous voulez, mais mon intuition est plutôt qu'on a intérêt à merger les PRs qui sont "prêtes" le plus vite possible dans `dev`, de façon à ce qu'elles bénéficient le plus longtemps possible des tests automatiques et de la QA qui sont faits par les gens sur `dev`. (Et c'est aussi moins chiant pour les auteurs que d'avoir à revenir rebaser un truc dans deux mois.)

2018-10-21 09:18 UTC, artragis commented
> 

Est-ce que c'est une façon d'éviter les conflits ? Mais je n'ai pas l'impression qu'il y ait des conflits entre les deux PRs (elles touchent des fichiers différents).

non ici c'est juste une question de *release management*. La version 27.3 termine le travail sur les exports de tuto et la version 28 reprend le travail de manière globale.

Je préfère éviter de faire grossir le nombre de changements dans une verison mineure. On n'a pas assez de personnes qui testent sur la béta.

je teste la partie "export de tuto" ce soir. Si c'est bon on n'aura qu'un problème à régler avec une petite régression qui est invisible côté user mais qui gène le déploiement.

Et là je mergerai tes PR.

2018-10-21 09:47 UTC, gasche commented
Mais dans ce cas-là, pourquoi ne pas avoir une "branche de release" séparée pour la version mineure, indépendante de `dev`, où y inclure seulement les changements qui t'intéressent, et continuer à merger le reste des choses dans `dev` ? (Il me semble que c'est ce que recommande le "Git Flow", par ailleurs.)

2018-10-29 14:06 UTC, artragis commented
tu peux rebase stp?

2018-10-29 14:13 UTC, gasche commented
Je viens de rebaser (ainsi que #5083 et #5084) mais je n'ai pas relancé les tests, alors il faut bien attendre Travis.

2018-10-29 14:53 UTC, merged