[Drag'n'drop] Vérification en JS + Scroll jusqu'à l'erreur
zestedesavoir/zds-site pull request #5181
Opened 2018-12-19 17:24 UTC by A-312

On vérifie que c'est une image côté JS puis on l'upload :D + Message d'erreur avec un timeout.

Fix #5176 .

# Q/A : 
 - Vérifier le scroll jusqu'à l'erreur si le message est créé hors de l'écran ; 
 - Essayez d'upload un PDF (par exemple) puis une image ;
 - Essayez d'uploader une image trop grande ;
 - Vérifier que le bouton "cacher" fonctionne. :)

2018-12-20 07:12 UTC, A-312 commented
@artragis v28 ou v28.1 ? 

Ca devrait être valide : https://w3c.github.io/clipboard-apis/#reading-from-clipboard

2018-12-20 09:56 UTC, Situphen commented
Je dirais en v28.1, c'est loin d'être urgent.

- Pour la détection d'images en JS, je ne trouve pas que ce soit hyper utile car c'est déjà fait niveau *backend* mais je ne suis pas contre non plus tant que ça fonctionne bien
- Pour l'erreur, je suis contre le timeout, il faudrait une croix.

2019-01-12 10:06 UTC, artragis commented
On en est où ici?

2019-01-12 16:56 UTC, A-312 commented
@artragis besoin d'un Q/A.

2019-01-12 16:56 UTC, A-312 commented
Je dois enlever le timeout apparemment

2019-01-12 17:38 UTC, Situphen commented
Oui, je suis contre faire disparaitre automatiquement les messages d'erreur, il faut que ce soit une volonté de l'utilisateur. Il faut donc une croix à la place du *timeout* :)

2019-01-20 20:47 UTC, artragis commented
Préviens quand tu auras fini du coup.

2019-01-22 01:00 UTC, A-312 commented
J'étais entrain de le faire ce WE, je ne sais oas pourquoi je me suis arrêté :/

2019-02-01 10:06 UTC, A-312 commented
@artragis Voila :)

2019-02-01 11:56 UTC, artragis commented
Y'a un blem

```
[10:09:39] Starting 'js'...
GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: operator (>)
File: script.js
Line: 31901
```

2019-02-01 12:02 UTC, artragis requested changes

2019-02-01 12:02 UTC, artragis commented on assets/js/editor.js
> +            return printErr("Votre image est trop lourde (" + (f.size/1024) + " Kio). La taille maximum est de 1024.0 Kio !");
il faut des espaces autour dezs signes arithmétiques `+`, `-`, `*` et `/`

2019-02-01 12:02 UTC, artragis commented on assets/js/editor.js
> +        }).insertAfter(editor).append('<a href="#hidealert" class="close-alert-box close-alert-box-text">Cacher</a>');
Je trouve plus lisible de mettre le `.append` avant le `insertAfter` car là il faut se poser la question de "quel est l'objet retourné par `insertAfter`.

2019-02-01 12:02 UTC, artragis commented on assets/js/editor.js
> +            $('body, html').animate({ scrollTop: pos }, 1000);
est-ce vraiment conseillé d'utiliser `animate` (ping @Situphen) ?

2019-02-01 12:02 UTC, artragis commented on assets/js/editor.js
> +        if (posTop < borderTop) {
Je propose d'ailleurs une autre solution que la minipulation du scroll, qui à mon sens est bien plus accessible et moins hasardeuse : donner un identifiant unique au message d'erreur puis ajouter `#le-fameux-id` à l'url de la page.

2019-02-01 12:02 UTC, artragis commented on assets/js/editor.js
> +        else if (borderBot < posBot) {
un peu de style : mettre le `else if` sur la même ligne que le `}`

J'ai l'impression que le linter est dans les choux sur ta PR, c'est étrange.

2019-02-01 12:02 UTC, artragis commented on assets/js/editor.js
>      var galleryUrl = '/api/galeries/'+ document.body.getAttribute('data-gallery') + '/images/';
étrange que le linter ait pas gueulé plus tôt dis donc, sur zds, on est sensé mettre des `"` pour les strings.

2019-02-01 12:02 UTC, A-312 commented
Avec [ma future update de gulp](https://github.com/A-312/zds-site/issues/7) on aurait le vrai emplacement :') Je vais regarder ça.

2019-02-01 12:03 UTC, A-312 commented on assets/js/editor.js
>      var galleryUrl = '/api/galeries/'+ document.body.getAttribute('data-gallery') + '/images/';
Il y en a un peu partout, je me demande si c'est pas un peu cassé

2019-02-01 12:04 UTC, artragis commented on assets/js/editor.js
>      var galleryUrl = '/api/galeries/'+ document.body.getAttribute('data-gallery') + '/images/';
c'est la question que je me pose en voyant cette ligne : c'est moi qui l'ai codée celle-là et pourtant pas de pb de lint...

2019-02-01 12:04 UTC, A-312 commented on assets/js/editor.js
> +        if (posTop < borderTop) {
Sauf que ça deplace le haut de l'écran sur l'élément, alors que là mon code déplace le bas de l'écran sur l'élément si l'élément est en bas ;)

2019-02-01 12:07 UTC, artragis commented on assets/js/editor.js
> +        if (posTop < borderTop) {
les messages d'erreurs sont mis en dessous de la boîte de rédaction?

2019-02-01 12:09 UTC, A-312 commented on assets/js/editor.js
> +            $('body, html').animate({ scrollTop: pos }, 1000);
c'est plus doux

2019-02-01 12:11 UTC, artragis commented on assets/js/editor.js
> +            $('body, html').animate({ scrollTop: pos }, 1000);
le résultat oui, mais je voulais surtout savoir si c'était réellement la technique souhaitée ou s'il n'y en avait pas une autre plus performante, jquery n'est pas optimisé pour tout.

2019-02-01 12:26 UTC, A-312 commented on assets/js/editor.js
>      var galleryUrl = '/api/galeries/'+ document.body.getAttribute('data-gallery') + '/images/';
La commande --speed désactive jslint il me semble

-----

Je me demande si travis fonctionne correctement sur certain point

2019-02-01 12:27 UTC, A-312 commented on assets/js/editor.js
> +        if (posTop < borderTop) {
Oui en dessous de la redaction, donc mon code va déplacer simplement le bas de l'écran jusqu'a voir l'écran, alors qu'un #le-fameux-id va déplacer le haut de l'écran sur l'élément

2019-02-01 12:31 UTC, artragis commented on assets/js/editor.js
> +        if (posTop < borderTop) {
oui si c'est en dessous ta solution est meilleure. J'avais pour idée que c'était au dessus.

2019-02-01 12:33 UTC, A-312 commented
@artragis corrigé

2019-02-01 12:34 UTC, artragis commented
Du coup je regarde demain.

2019-02-02 14:11 UTC, artragis commented
QA OK

2019-02-02 14:11 UTC, merged