Améliore l'historique d'édition sur le forum
zestedesavoir/zds-site pull request #5189
Opened 2018-12-20 18:00 UTC by A-312

Fix : #5116

![image](https://user-images.githubusercontent.com/18501150/50302036-2f2cb300-0489-11e9-9cd6-765d121d0ee0.png)

Peut-être modifier : "Historique des éditions du message" par autres choses ?

Q/A : Vérifier que les boutons/auteurs correspondent au bonne ligne.

2018-12-20 18:03 UTC, A-312 commented
NB : Je me suis compliqué la vie.

2018-12-20 19:06 UTC, A-312 commented
Je vais finir par faire une PR pour colorer travis. x)

2018-12-27 19:44 UTC, A-312 commented
Oups j'ai oublié de changer le titre de la dernière colonne

2018-12-28 22:19 UTC, gcodeur commented
Salut ! Je ne suis pas sûr d'avoir bien compris le but de cette PR. Pour confirmation, s'agit-il de décaler la colonne "version avant édition" d'un cran afin de faire coïncider la date d'une version et son contenu ?

2018-12-28 22:21 UTC, gcodeur commented on templates/pages/comment_edits_history.html
> +                <th>{% trans "Action" %}</th>
Peut-être "Contenu" ?

2018-12-28 22:30 UTC, A-312 commented on templates/pages/comment_edits_history.html
> +                <th>{% trans "Action" %}</th>
[Ah](#issuecomment-450217972)! C'est sur le screen que j'avais oublié de changer.

Contenu me semble plus adapté !

2018-12-28 22:30 UTC, A-312 commented
> 
> 
> Salut ! Je ne suis pas sûr d'avoir bien compris le but de cette PR. Pour confirmation, s'agit-il de décaler la colonne "version avant édition" d'un cran afin de faire coïncider la date d'une version et son contenu ?

C'est bien ça pour que ça soit plus évident.

2018-12-28 23:07 UTC, gcodeur commented
En effet, j'ai oublié de regarder le ticket associé, désolé !

Du coup, ça me semble être une très bonne idée. J'essaye de faire la QA demain.

2018-12-29 21:45 UTC, gllmc requested changes
Ça m'a l'air de marcher très bien ! Quelques petites corrections, mais rien de grave.

2018-12-29 21:45 UTC, gcodeur commented on templates/pages/edit_detail.html
> +    <h1>{% trans "Texte présent avant l'édtion :" %}</h1>
Vu la correction qui a été faite sur le tableau des éditions, il faudrait quelque chose comme "Texte de cette version" ou "Affichage d'une version", je pense.

Autre chose : pas de `:` dans un `h1`.

2018-12-29 21:45 UTC, gcodeur commented on templates/pages/comment_edits_history.html
> +                <th></th>
```suggestion
                <th>Version</th>
```

2018-12-29 21:45 UTC, gcodeur commented on templates/pages/comment_edits_history.html
> +                                Etat original
```suggestion
                                État original
```

Accent sur la majuscule (`État original`).

2018-12-29 21:45 UTC, gcodeur commented on templates/pages/comment_edits_history.html
> +                                Edition {{ forloop.revcounter0 }}
```suggestion
                                Édition {{ forloop.revcounter0 }}
```

Accent sur la majuscule (`Édition`).

2018-12-29 21:45 UTC, gcodeur commented on templates/pages/comment_edits_history.html
> +                        Edition {{ edits|length }}
```suggestion
                        Édition {{ edits|length }}
```

Accent sur la majuscule (`Édition`).

2019-01-10 15:35 UTC, A-312 commented on templates/pages/comment_edits_history.html
> +                <th>{% trans "Action" %}</th>
Ok

2019-01-10 15:36 UTC, A-312 commented on templates/pages/edit_detail.html
> +    <h1>{% trans "Texte présent avant l'édtion :" %}</h1>
Ok "Version antérieure du message"

2019-01-10 15:42 UTC, A-312 commented
@gcodeur Je n'ai pas su mettre tes changements en local pour git squash tes commits en un seul. :/

2019-01-10 21:27 UTC, gllmc reviewed
Encore une chose à corriger et c'est tout bon !

> @gcodeur Je n'ai pas su mettre tes changements en local pour git squash tes commits en un seul. :/

Euh, je ne comprends pas vraiment ce que tu veux dire. Lors de ma première revue, j'ai utilisé le système de suggestions de GitHub (qui l'interface m'a  proposé, mais que je ne maîtrise pas vraiment :sweat_smile: ). Par contre, j'ai l'impression que ta PR est très bien actuellement. Il y a un seul commit avec toutes les modifications suggérées, non ?

2019-01-10 21:27 UTC, gllmc commented on templates/pages/edit_detail.html
> +    <h1>{% trans "Version antérieure du message" %}</h1>
Désolé, ça m'avait échappé lors de ma première revue ! Ce changement doit être reporté dans le `title` de la page et dans la barre de navigation.

2019-01-19 09:12 UTC, A-312 commented
Corrigé

2019-01-20 11:14 UTC, artragis requested changes
Je fais confiance à gcodeur pour le code général là il ne manque que la doc.

2019-01-20 11:14 UTC, artragis commented on zds/utils/templatetags/sibling.py
> +class siblingNode(template.Node):
Une classe doit commencer par une majuscule.

2019-01-20 11:14 UTC, artragis commented on zds/utils/templatetags/sibling.py
> +def do_sibling(parser, token):
Un peut de doc serait cool . Deplus ça serait bien que tu le répertories dans la doc du back (dans le fichier .rst déjà existant.

2019-01-20 12:45 UTC, A-312 commented on zds/utils/templatetags/sibling.py
> +def do_sibling(parser, token):
ok je fais ça

2019-01-20 13:53 UTC, A-312 commented
Je dois traduire en anglais je suppose ? 

Cette fonction permet d'attribuer l’élément sélectionné, suivant ou précédent de `{list}` à une variable `{ouput_name}`.

    sibling {list} {dir} [as {ouput_name}]

 - `{list}` : Variable/Point d'entrée.
 - `{dir}` : `next`/`prev` ou une valeur numérique représentant l'index de l'élément voulu dans `{list}`.
 - `{ouput_name}` : Optionnel. S'il n'est pas défini, il prend la valeur de : 
           - `current` si `{dir}` est numérique ;
           - `next` ou `prev` si `{dir}` vaut `next`/`prev`.

Pour trouver la position actuelle dans le tableau et ainsi procéder aux instructions `next`/`prev`, le code va vérifier : 

 - Si vous avez défini la variable `siblingStep` avant d'appeler la fonction ;
 - Usage recommandé : Automatiquement dans une [boucle for](https://docs.djangoproject.com/fr/2.1/ref/templates/builtins/#for) grâce à la variable `forloop.counter0` ;
 - Si aucun des deux cas précédent est rempli : 
        - avec `{dir}` == `next` on obtient le deuxième élément (index = 1) ;
        - avec `{dir}` == `prev` on obtient l'avant dernier élément (index = len(list) - 1).

Si l'élément existe, l'élément est renvoyé sinon une liste vide est retourné '{}'.

Ces deux lignes font donc la même chose : 

    {% sibling edits 0 as current %}
    {% sibling edits 0 %}

2019-01-29 19:34 UTC, A-312 commented
dans https://github.comA/zestedesavoir/zds-site/tree/dev/doc/source/utils ? Je ne trouve pas le fichier correspondant pour les templatetags.

2019-01-31 18:22 UTC, artragis commented
https://docs.zestedesavoir.com/front-end/template-tags.html

2019-04-19 19:55 UTC, A-312 commented
@artragis fait

2019-04-20 06:43 UTC, artragis commented
ok, je check ça tout à l'heure, merci !)

2019-04-22 19:48 UTC, gustavi requested changes

2019-04-22 19:48 UTC, gustavi commented on zds/utils/templatetags/sibling.py
> +def do_sibling(parser, token):
En plus de la doc (il me semble que c'est fait à l'heure où j'écris ces lignes) un petit docstring serait parfait :)

2019-04-22 19:48 UTC, gustavi commented on zds/utils/templatetags/sibling.py
> +        except:
Mettre la ou les vraies exceptions ici. Mieux que que ça casse pour de vrai si l'erreur est ailleurs (template, BDD, interne à Django, etc) et qu'on ai des vrais logs plutôt que ce soit masqué par le "except".

2019-04-22 19:48 UTC, gustavi commented on templates/pages/comment_edits_history.html
> +                        Édition {{ edits|length }}
Il manque l'internationnalisation (i18n) ici.

2019-04-22 19:48 UTC, gustavi commented on templates/pages/comment_edits_history.html
> +                    <td>(Version actuelle)</td>
i18n

2019-04-22 19:48 UTC, gustavi commented on templates/pages/comment_edits_history.html
> +                                État original
i18n

2019-04-22 19:48 UTC, gustavi commented on templates/pages/comment_edits_history.html
> +                                Édition {{ forloop.revcounter0 }}
i18n

2019-04-22 19:49 UTC, gustavi requested changes

2019-04-22 19:49 UTC, gustavi commented on templates/pages/comment_edits_history.html
> +                <th>Version</th>
i18n ici que j'ai oublé

2019-07-01 07:30 UTC, A-312 commented on zds/utils/templatetags/sibling.py
> +        except:
Non ça plantera au premier (avec prev) ou au dernier (avec next).

```
                {% for edit in edits %}
                    {% sibling edits next as nextEdit %}
```

2019-07-12 11:16 UTC, A-312 commented
Prêt ! :D

2019-08-22 09:26 UTC, artragis commented
on en est où ici? il manque quoi?

2019-08-22 10:49 UTC, A-312 commented
@artragis de mon côté tout est bon

2019-08-22 11:35 UTC, artragis commented
tu peux faire un rebase pour s'assurer qu'on n'est pas dans le cas du travis qui est vert alors qu'il y a un pb?

2019-08-22 17:04 UTC, A-312 commented
La PR est plus vieille que ça, enfin je l'espère 😬

2019-08-22 17:28 UTC, gustavi requested changes
Niveau code c'est très bien mis à part des remarques sur le détail. J'essaye de trouver un peu de temps demain midi pour QA si personne ne s'en ai chargé.

2019-08-22 17:28 UTC, gustavi commented on zds/utils/templatetags/sibling.py
> +            Parse : sibling {list} {dir}
Préférer des commentaires `#` ici

2019-08-22 17:28 UTC, gustavi commented on zds/utils/templatetags/sibling.py
> +            side = (-1, 1)[self.direction == 'next']
Même si le code est valide et fonctionne je pense qu'il pourrait être réécris dans la continuité de la boucle pour plus de lisibilité :)

2019-08-22 17:28 UTC, gustavi commented on zds/utils/templatetags/sibling.py
> +        except:
Il serait bien d'avoir la vraie exception ici.

2019-08-22 17:28 UTC, gustavi commented on zds/utils/templatetags/sibling.py
> +"""
En général on met ce commentaire en premier dans le fichier. Mais c'est vraiment histoire d'en***er les mouches.

2019-08-22 17:34 UTC, A-312 commented on zds/utils/templatetags/sibling.py
> +        except:
> Non ça plantera au premier (avec prev) ou au dernier (avec next).
> 
> ```
>                 {% for edit in edits %}
>                     {% sibling edits next as nextEdit %}
> ```

2019-08-22 19:46 UTC, artragis commented on zds/utils/templatetags/sibling.py
> +        except:
mais il faut une vraie exception car là tu catches aussi les KeyboardInterrupt par exemple.

2019-08-25 09:36 UTC, artragis requested changes

2019-08-25 09:36 UTC, artragis commented on zds/utils/templatetags/sibling.py
> +
non, faut pas mettre de ligne ici.

2019-08-25 21:14 UTC, gustavi approved these changes

2019-09-11 11:16 UTC, artragis commented
QA KO pour un détail : les boutons sont mal alignés
![image](https://user-images.githubusercontent.com/1523653/64692908-6d925400-d496-11e9-9d51-698b4da59a11.png)

2019-09-11 11:37 UTC, A-312 commented
Et : 
![image](https://user-images.githubusercontent.com/18501150/64694113-383b3580-d499-11e9-82e0-d82892ac57f3.png)

Pour les boutons, il faut voir pour avoir une colonne plus grande et surement enlever le float, s'il y en a un.

2019-11-04 22:15 UTC, firm1 commented
Hello @A-312 on en est ou sur cette PR ? Tu pourrait la terminer et/ou faire un rebase, que je puisse la QA dans la foulée ?

2019-11-05 06:27 UTC, A-312 commented
Elle était prête

2019-11-05 06:31 UTC, A-312 commented
D'ailleurs elle a déjà été Q/A dans cet état et elle était passé, j'ai rollback/ignoré certain commentaires de code review qui faisait planter le code.

2019-11-05 07:41 UTC, firm1 commented
> D'ailleurs elle a déjà été Q/A dans cet état et elle était passé,

Le dernier commentaire de QA disait KO. Et je ne vois pas d'autre commentaire qui dise que la QA est passée.

2019-11-05 07:54 UTC, A-312 commented
Je l'ai remis à un état antérieur

2019-11-06 00:52 UTC, firm1 commented
**Rapport de QA**

Le code fonctionne, mais je suis un peu embêté par en relisant ton code, tu t'es un peu compliqué la vie.

Je t'ai [fais une PR](https://github.com/A-312/zds-site/pull/17/files) avec mes suggestions et ça évite de créer un tag.

2019-11-09 01:03 UTC, firm1 commented
Du coup @A-312 tu as eu le temps de jeter un coup d'oeil pour merger ma PR sur ta branche ?

2019-11-12 14:26 UTC, firm1 commented
Puisque je suis intervenu sur cette PR, je ne peux plus la QA :(

2019-11-21 12:33 UTC, artragis commented
Ok pour moi

2019-11-21 12:33 UTC, artragis approved these changes

2019-11-21 12:33 UTC, merged