Ajout d'un paramètre GET pour avoir une miniature Twitter large
zestedesavoir/zds-site pull request #5295
Opened 2019-03-03 13:05 UTC by philippemilink

Numéro du ticket concerné: #5291

En ajoutant `?twittercard=large` à la fin de l'URL d'un contenu, les balises meta `twitter:card` et `twitter:image` changent pour que Twitter affiche une large miniature lors du partage du lien vers un contenu.

J'ai également modifié l'URL dans les boutons de partage Twitter pour que l'URL partagée contienne automatiquement le paramètre GET supplémentaire (seulement s'il y a une image associée au contenu).

### Contrôle qualité

1. Aller sur un contenu qui contient une image
2. Le bouton de partage Twitter doit partager l'URL avec  `?twittercard=large` en plus

Note: c'est un peu compliqué à vérifier avec Twitter pour le moment, ce sera plus simple que ce sera dans la bêta.

2019-03-03 13:14 UTC, A-312 commented
Ne l'élargi pas par défaut en large ça va nous faire des choses flous dans 60-70% des cas

2019-03-03 13:16 UTC, A-312 requested changes

2019-03-03 13:16 UTC, A-312 commented on templates/misc/social_buttons.part.html
> +            <a href="https://twitter.com/share?url={{ app.site.url }}{{ link }}{% if has_image %}?twittercard=large{% endif %}&amp;text={{ text }}"
Ne l'élargi pas par défaut en large ça va nous faire des choses flous dans 60-70% des cas

2019-03-03 13:18 UTC, philippemilink commented
Dans ce cas, comment on facilite le partage de la version large ? Parce que si on ne met nul part qu'on partager la version large, ce sera assez caché comme feature... 
Ou alors on élargit seulement si la taille de l'image originale est déjà plus grande que la miniature large ?

2019-03-16 16:35 UTC, philippemilink commented
@A-312 up ?

2019-03-16 16:43 UTC, A-312 commented
C'est surtout pour l'équipe de com'

2019-03-16 18:20 UTC, philippemilink commented
C'est bon, j'ai enlevé le partage par défaut avec la miniature large (j'ai amendé mon commit).

2019-04-05 11:12 UTC, merged