retire les espaces en trop dans les titres
zestedesavoir/zds-site pull request #5354
Opened 2019-06-02 14:20 UTC by Vanadiae

Ajout du template tag `spaceless` autour du titre du template de base aux autres pages du site

fixes #5283

### Contrôle qualité

* Poster un lien depuis Discord vers le site en beta avec ma PR dessus
* Vérifier qu'il n'y ait pas d'espaces dans la description que Discord réussit à obtenir

2019-06-02 14:56 UTC, Situphen requested changes
Avant de mettre la PR sur la bêta pour vérifier que ça résout bien le mauvais affichage des liens sur Discord, on peut déjà regarder le code source pour voir si les sauts de lignes et espaces sont bien supprimés. Je viens de le faire et ta proposition ne fonctionne pas !

S je regarde [la documentation du filtre `spaceless`](https://docs.djangoproject.com/fr/2.1/ref/templates/builtins/#spaceless), c'est tout à fait normal car : 

> Seuls les espaces entre les *balises* elles-mêmes sont supprimés, pas ceux entre les balises et le texte.

Si je regarde [notre documentation](https://docs.zestedesavoir.com/front-end/template-tags.html), on n'a pas de filtre personnalisé prévu pour cet effet. Soit il en existe déjà un intégré à Django, soit tu peux essayer d'en créer un toi même ! Pour cela, tu peux regarder la documentation de Django ou regarder les filtres actuels (dossier `zds/utils/templatetags`).

2019-06-02 16:05 UTC, Vanadiae commented
En gros, je peux créer un templatetag pour retirer les *trailing whitespaces* dans zds/utils/templatetags en m'inspirant des autres ? Mais du coup si je le fais et que j'encadre le bloque `title` avec, ai-je encore besoin de laisser le bloc `spaceless` ou il serait inutile dans ce cas ?

2019-06-02 16:41 UTC, Situphen commented
Oui c'est ça, créer un *templatetag* personnalisé pour retirer les sauts de ligne et les espaces inutiles ! Je pense pas qu'il soit nécessaire de garder `spaceless`, par contre tu peux aller regarder son code source et t'en inspirer, vu qu'il fait presque le travail qu'il faut.

2019-06-02 17:42 UTC, Vanadiae commented
Je vais essayer de m'en inspirer, merci.

2019-06-03 17:35 UTC, Vanadiae commented
J'ai rajouté le tag mais il y a quelque chose qui m'embête c'est que le *templatetag* `captureas` agit avant `trail` donc captureas enregistre dans la variable le contenu du bloc `captureas` mais vu que `trail` agit après, les changements ne sont pas appliqués. Exemple :

```html+django
{% captureas title %}
    {% trail %}
        {% captureas title_blocks %}
            {% trail %} <!-- ici on est obligé de rajouter un bloc trail sinon le captureas n'aura pas trail qui sera passé -->
                <!-- ... -->
            {% endtrail %}
        {% endcaptureas %}
    {% endtrail %}
{% endcaptureas %}
```

2019-06-07 10:02 UTC, A-312 commented
Pourquoi ajouter trail ?

De plus il faut faire :

```twig
<title>
  {% spaceless %}
    {% captureas title %}
      /*....*/
    {% endcaptureas %}
  {% endspaceless %}
</title>
```

2019-06-07 10:42 UTC, Situphen commented
@A-312 Je l'ai écrit dans un commentaire plus haut `spaceless` enlève les espaces entre les balises HTML, pas à l'intérieur des balises !

2019-06-07 18:37 UTC, A-312 commented
Ok donc :

```
<title>
  {% trail %}
    {% captureas title %}
      /*....*/
    {% endcaptureas %}
  {% endtrail %}
</title>
```

Ce que je veux dire c'est qu'il faut que les balises sont en dehors de title dans le cas où title est remplacé par un autre élément

2019-06-08 19:05 UTC, Vanadiae commented
@A-312 Je ne comprends pas ce que tu essaies de dire ?  De plus, comme expliqué dans mon message précédent,

```html+django
{% trail %}
  {% captureas title %}
    /*....*/
  {% endcaptureas %}
{% endtrail %}
{{title|safe}}
```

Ne fonctionnera pas bien lorsque on utilisera `{{title|safe}}` car `captureas` évaluera son bloc avant que le bloc `trail` ne fasse son job. C'est pour cette raison que j'ai écris :

```html+django
{% captureas title %}
  {% trail %}
    /*....*/
  {% endtrail %}
{% endcaptureas %}
{{title|safe}}
```

De cette façon, le bloc `trail` fait son travail puis `captureas` récupère le code HTML dans `title`.

2019-06-10 19:25 UTC, artragis requested changes

2019-06-10 19:25 UTC, artragis commented on zds/utils/templatetags/trail.py
> +        str = re.sub(r'>\s+<', '><', self.nodelist.render(context))
pour augmenter les perfs il faudrait mettre toutes les regexp dans des constantes, ça ressemblerait à ça : 

```
tag_regexp = re.compile(r'>\s+<')
breaks_regexp = re.compile(r'[\n\r\f\v]+')
space_regexp = re.compile(r'(\s)+')

class TrailNode(template.Node):
    """
    Removes all spaces between tags, removes newlines and replaces large spaces and tabs by a single space or tab respectively
    """
    def __init__(self, nodelist):
        self.nodelist = nodelist

    def render(self, context):
        new_text = tag_regexp.sub('><', self.nodelist.render(context)) # et comme ça on évite de redéfinir str qui est un mot réservé
        new_text = breaks_regexp.sub('', new_text)
        return space_regexp.sub('$1', new_text) # à vérifier pour celle là, je ne sais plus si c'est bien $1 qu'il faut faire
```

2019-06-10 19:47 UTC, Vanadiae commented on zds/utils/templatetags/trail.py
> +        str = re.sub(r'>\s+<', '><', self.nodelist.render(context))
Je vérifierai et fairai les changements dans la semaine. J'y avais pas penser pour str (par habitude de string). Je savais pas qu'on pouvait faire des regexp constantes, intéressant. (J'ai encore un bon bout de chemin à faire en python)

2019-06-11 16:59 UTC, Vanadiae commented on zds/utils/templatetags/trail.py
> +        str = re.sub(r'>\s+<', '><', self.nodelist.render(context))
J'ai push et j'ai vérifié, normalement ça fonctionne nickel. Du coup le comportement du tag c'est :
* Retire tous les whitespaces entre les balises HTML
* Retire tous les espaces et tabulations à la fin et au début de toutes les lignes
* Retire tous les sauts de ligne possibles

Le 2e point permet d'avoir ce type de texte avec les espaces:

```html
               test        test2          <!-- Avant -->
test        test2 <!-- Après -->
```

2019-06-11 18:49 UTC, Situphen commented
Est-ce que tu peux ajouter un petit paragraphe dans la documentation de Zeste de Savoir à ce propos ? `doc/source/front-end/template-tags.rst`

2019-06-11 18:59 UTC, Vanadiae commented
Justement c'est ce que j'avais demandé il y a plusieurs messages. En tout cas pas de problème, je m'en occupe :smile_cat:

2019-06-11 19:28 UTC, Situphen commented on doc/source/front-end/template-tags.rst
> +Ce module défini l'élément ``trail`` qui permet de retirer tous les sauts de ligne et les espaces dans le bloc de gabarit entre les balises HTML ainsi qu'à la fin et au début des lignes. Le code suiv
```suggestion
Ce module définit l'élément ``trail`` qui permet de retirer tous les sauts de ligne et les espaces dans le bloc de gabarit entre les balises HTML ainsi qu'à la fin et au début des lignes. Le code suivant :
```

2019-06-11 19:33 UTC, Vanadiae commented on doc/source/front-end/template-tags.rst
> +Ce module défini l'élément ``trail`` qui permet de retirer tous les sauts de ligne et les espaces dans le bloc de gabarit entre les balises HTML ainsi qu'à la fin et au début des lignes. Le code suiv
Il y a "défini" sans 't' à plein d'endroits dans la doc, je corrige.

2019-06-11 19:42 UTC, artragis commented on zds/utils/templatetags/trail.py
> +        str = re.sub(r'>\s+<', '><', self.nodelist.render(context))
merki

2019-06-14 11:06 UTC, artragis commented
@Situphen tu pourras le placer sur la béta?

2019-06-14 15:22 UTC, Situphen commented
C'est sur la bêta et d'après mon test sur Discord ça a l'air de bien fonctionner !

@Vanadiae tu peux *rebase* s'il te plait ? :)

2019-06-14 17:16 UTC, Vanadiae commented
C'est bon c'est rebase

2019-06-14 17:33 UTC, merged

2019-07-06 22:08 UTC, Vanadiae commented
Quelqu'un pourrait réouvrir ma PR (j'ai trouvé un petit bug et il faut que je rajoute un test) ?

2019-07-06 23:12 UTC, Situphen commented
Elle a été mergée donc on ne peut pas la réouvrir, il faut en créer une nouvelle !

2019-07-08 06:31 UTC, Vanadiae commented
Ok ça marche (c'est pas la première fois en plus :smiley:)