Ajout des clemojiv3 en svg
zestedesavoir/zds-site pull request #5361
Opened 2019-06-10 21:15 UTC by A-312

fix : #5069

Etape : 

 1. Merge cette PR.
 2. Une fois que cette PR sera en prod, faire une PR sur le git de zmd.

2019-08-11 20:47 UTC, A-312 commented
En lien avec : zestedesavoir/zmarkdown/pull/344

2019-08-12 09:44 UTC, artragis commented
je me demandais d'ailleurs : c'est compatible avec le fait qu'on a deux jeux de smiley ça? comment on fait quand il demande `quelquechose.svg` alors que l'ancien jeu est en png/gif?

2019-08-12 15:40 UTC, A-312 commented
> je me demandais d'ailleurs : c'est compatible avec le fait qu'on a deux jeux de smiley ça? comment on fait quand il demande quelquechose.svg alors que l'ancien jeu est en png/gif?

La configuration de la prod est en lien symbolique, tant que le nom correspond (peut importe l'extension) l'image sera renvoyé.

Mais actuellement j'ai laissé cette question en suspend, j'ai mis les smileys dans "svg", il faudrait surement mettre à la racine et supprimer les .png/gif

2019-08-12 18:10 UTC, artragis commented
> peut importe l'extension

??? si c'est un lien symbolique, l'extension est importante;

2019-08-12 18:31 UTC, A-312 commented
> > peut importe l'extension
> 
> ??? si c'est un lien symbolique, l'extension est importante;

C'est l'inverse alors

2019-08-12 19:05 UTC, artragis commented
il faut que le nom du fichier soit identique et on switch en fonction de ce que dit le header. Mais si tu as smile.png d'un côté et smile.svg de l'autre c'est pas possible.

2019-08-12 19:06 UTC, A-312 commented
> il faut que le nom du fichier soit identique et on switch en fonction de ce que dit le header. Mais si tu as smile.png d'un côté et smile.svg de l'autre c'est pas possible.

On le fait déjà pour ninja (si je ne me trompe pas) avant c'est un png et non un gif

2019-08-12 19:44 UTC, artragis commented
on a pas mis gif deux fois? @sandhose @Situphen @pierre-24 (il me semble que c'est toi qui l'a fiat celle là)

2019-11-04 22:28 UTC, firm1 commented
Coucou,

Du coup, cette PR est toujours d'actualité ? Je voulais faire la QA, mais je vois que je ne peux pas la tester depuis le site.

2019-11-05 06:28 UTC, A-312 commented
Elle est prête, on attend juste la décision d'artragis

2019-11-05 07:38 UTC, firm1 commented
Du coup comment je peux la QA ? Qu'est ce qui peut être testée ?

2019-11-05 07:53 UTC, A-312 commented
Que tu vois l'image (svg) à l'url de la config

2019-11-05 08:34 UTC, firm1 commented
Je n'ai toujours pas compris désolé.

Je récupère ta branche, je démarre le site (d'aileurs je dois ré-installer le front ou juste builder le front ?).

Puis je fais quoi ? Je lire des contenus ? Poster sur le forum ? A quel endroit du site la PR est censée avoir de l'impact ?

2019-11-05 11:47 UTC, A-312 commented
Cette PR ajoute les SVG dans le dossier en question à part vérifier via requête HTTP la présence des images, tu ne peux pas faire frand chose

2019-11-05 12:06 UTC, artragis commented
Et du coup, comment tu gères le fait qu'on a la possibilité de ne pas mettre le set de smiley "clem"
?

2019-11-05 12:19 UTC, A-312 commented
@artragis Comment ça ? Je ne fais pas moins et pas plus que ma version actuelle

2019-11-05 12:44 UTC, artragis commented
comment tu gères le fait que certaines personnes ne mettront pas les SVG clem? comme tu changes l'extension, on fait comment?

2019-11-05 15:20 UTC, A-312 commented
Ce n'est pas déjà le cas dans la config nginx ?

Quand on est passé au clemojiv2, on a eu le cas on est passé de gif à png.

2019-11-05 17:23 UTC, A-312 commented
@artragis 

 - https://zestedesavoir.com/static/smileys/ninja.png
 - https://zestedesavoir.com/static/smileys/ninja.gif

Le .png redirige vers le .gif, voir ici quand on fait `:ninja:` : 

 - A l'époque c'était .png : https://zestedesavoir.com/forums/sujet/538/clem-sur-le-devant-de-la-scene/?page=14#p103325
 - Aujourd'hui c'est .gif : https://zestedesavoir.com/forums/sujet/13183/supprimer-le-bouton-signaler-le-profil-quand-le-membre-est-bannis/?page=1#p210619

2019-11-05 17:24 UTC, A-312 commented
Par contre je pense que je dois faire un nouveau commit pour déplacer `assets/smileys/svg/*.svg` vers `assets/smileys/*.svg` sauf si on laisse les anciens emotes en .png ou si en passe par une redirection nginx.

2020-01-21 12:05 UTC, artragis commented
> Par contre je pense que je dois faire un nouveau commit pour déplacer `assets/smileys/svg/*.svg` vers `assets/smileys/*.svg` sauf si on laisse les anciens emotes en .png ou si en passe par une redirection nginx.

Il faut les envoyer sinon on ne les aura pas dans les epubs.

2020-02-05 22:42 UTC, A-312 commented
@artragis Fait, j'étais persuadé de les avoir mis.

2020-02-06 11:11 UTC, artragis commented
QA:

# sur le forum

Prendre un message à l'ancien format, le citer

![image](https://user-images.githubusercontent.com/1523653/73931778-29866c80-48d9-11ea-94f6-d38aa081269a.png)

OK

# sur les tutoriels

- sur les epub, ça marche pas, QA KO (je vais te mettre le commentaire sur le pourquoi)
- sur la publication online OK.

2020-02-06 11:12 UTC, artragis requested changes

2020-02-06 11:12 UTC, artragis commented on zds/tutorialv2/epub_utils.py
> +    smiley_images_path = Path(settings.BASE_DIR, 'dist', 'svg', 'smileys')
ton dossier c'est dist/smileys/svg et toi tu demandes dist/svg/smileys, forcément ça marche pas. il faut mettre svg à la fin.

2020-02-06 11:48 UTC, A-312 commented on zds/tutorialv2/epub_utils.py
> +    smiley_images_path = Path(settings.BASE_DIR, 'dist', 'svg', 'smileys')
Corriger c'est pour ça qu'il ne faut jamais modifier/commit quand on est en train de piloter, on n'est pas assez attentif.

2020-02-09 10:03 UTC, artragis commented
Si on se fie à https://github.com/zestedesavoir/zmarkdown/blob/master/packages/zmarkdown/config/rebber.js#L42 il faut aussi ajouter un "/svg" à cette ligne : https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/publication_utils.py#L369

2020-02-09 12:10 UTC, A-312 commented
@artragis Ce n'est pas gênant qu'une variable/constante soit prefixé avec du texte en dure ?

2020-02-09 12:40 UTC, artragis commented
je comprends pas ta question pour deux raisons:

- c'est encore une fois un suffixe et non un préfixe
- je ne comprends pas ce que tu veux faire.

2020-02-09 13:22 UTC, A-312 commented
l'autre solution est de modifier la variable au lieu de suffixer la ligne que tu as indiqué

2020-02-09 14:11 UTC, artragis commented
la ligne que j'ai indiqué dit : `smiley_directory = SMILEY_BASE_DIRECTORY`, quand je dis "il faut ajouter /svg" je ne cherche pas à te piéger, il suffit de faire `smiley_directory = SMILEY_BASE_DIRECTORY + '/svg'`

2020-02-09 18:22 UTC, A-312 commented
Ca me semble étrange comme fonctionnement qu'on utilise un répertoire d'emote fix alors que pour zmd on spécifie le répertoire à chaque fois :/

2020-02-09 20:55 UTC, artragis commented
c'est le fonctionnement du template latex. ça permet d'éviter des copier/coller inutiles. je suis pas sûr que ça fonctionne comme attendu vu comment SMILEYS_BASE_PATH est construit, mais c'est pas du ressort de cette PR, d'autant que de toute façon le fix sur les smileys ne serait présent qu'avec la version 8 de zmd.

2020-02-11 11:25 UTC, artragis commented
Afin que ta PR soit auto suffisante, il ne te reste plus qu'à mettre qu'il faut zmd 8 dans le fichier zmd/package.json  et on sera bon, la QA est OK.

2020-02-11 12:32 UTC, A-312 commented
Je `npm install zmarkdown@latest` ce soir.

2020-02-11 20:59 UTC, merged