Améliore les descriptions des forums
zestedesavoir/zds-site pull request #5364
Opened 2019-06-27 11:53 UTC by artragis

Fix #4274

# QA

regardez le résutlat dans votre inspecteur pour la balice `meta description` 

Premier message du topic | résultat
message court avec bonjour (<120 char) | description = message complet
message court sans bonjour (<120 char) | description = message complet
message court avec bonjour (>120 char) | description = le premier message sans la phrase de "bonjour", ensuite 120 caractères
message court sans bonjour (>120 char) | description = 120 premiers caractères

2019-07-01 19:34 UTC, Vanadiae commented
Il y aurait pas moyen de mettre la longueur max (120) dans une variable pour pouvoir modifier plus facilement dans le futur ?

2019-07-01 20:22 UTC, artragis commented
Comme pour la configuration des "greetings", c'est possible, oui.

2019-07-02 14:05 UTC, Rockaround requested changes

2019-07-02 14:05 UTC, Rockaround commented on zds/settings/abstract_base/zds.py
> +        'greetings': ['salut', 'bonjour', 'yo ', 'hello', 'bon matin', 'tout le monde se secoue'],
```suggestion
        'greetings': ['salut', 'bonjour', 'yo ', 'hello', 'bon matin', 'tout le monde se secoue', 'bonsoir', 'bonjour à tous'],
```

2019-07-02 15:55 UTC, artragis commented on zds/settings/abstract_base/zds.py
> +        'greetings': ['salut', 'bonjour', 'yo ', 'hello', 'bon matin', 'tout le monde se secoue'],
bonjour à tous n'est pas nécessair car déjà couvert par bonjour.

2019-07-02 17:31 UTC, Rockaround commented on zds/settings/abstract_base/zds.py
> +        'greetings': ['salut', 'bonjour', 'yo ', 'hello', 'bon matin', 'tout le monde se secoue'],
J'avais en effet mal compris le code, mes excuses. Mais fonctionnera-t-il dans le cas suivant ? Sans ponctuation ni retour à la ligne.

https://zestedesavoir.com/forums/sujet/12518/matrice-dune-application-lineaire/

Je ne suis pas sûr non plus que le code retourne 120 caractères après avoir enlevé la salutation, si ?

2019-07-02 17:38 UTC, artragis commented on zds/settings/abstract_base/zds.py
> +        'greetings': ['salut', 'bonjour', 'yo ', 'hello', 'bon matin', 'tout le monde se secoue'],
il retire la première phrase (pour éviter les cas où on aurait des ponctuation trop disparates) si la première phrase est une salutation, puis il prend 120 caractères max.

APrès c'est pas sûr que retirer la salutation soit bien, et du coup à part le "tout le monde se secoue" qui est propre à des messages automatiques de zds.

2019-07-02 20:34 UTC, Vanadiae commented on zds/settings/abstract_base/zds.py
> +        'greetings': ['salut', 'bonjour', 'yo ', 'hello', 'bon matin', 'tout le monde se secoue'],
Il faut prendre en compte les clemoji qui sont après la salutation aussi (comme j'ai l'habitude de faire [par exemple](https://zestedesavoir.com/forums/sujet/12682/suggestion-une-liste-de-lecture-pour-les-zestes/#p205243))

2019-07-03 05:44 UTC, A-312 commented
@artragis c'est #5274 le numéro de l'issue ;)

On ne prend pas en compte la présence d'une description ?

----------

Ensuite en relisant l'issue, ton édition sur le titre (en précisant "forum" au lieu de "site") a exclu les contenus dans le titre mais l'idée de Leeroy comprenait aussi le début des contenus qui peuvent être vid ou très court, comme :

 - https://zestedesavoir.com/tutoriels/755/le-langage-c-1/
 - https://zestedesavoir.com/articles/3133/rencontre-avec-ryx/

J'ai détaillé/édité mon explication sur : https://github.com/zestedesavoir/zds-site/issues/5274#issuecomment-466640316

Je ne sais pas si ça devra faire le sujet d'une deuxième PR ou si tu inclure les contenus/billets dans cette PR.

2019-07-03 05:44 UTC, A-312 commented on templates/forum/topic/index.html
> +        {{ topic.meta_description }}
Tu ne prends pas en compte la présence d'une description ? On pourrait reprendre à la suite quand la description est présente, du style : 

{Ma description}... {debut du sujet}

J'ai détaillé/édité mon explication sur : https://github.com/zestedesavoir/zds-site/issues/5274#issuecomment-466640316

2019-07-03 09:02 UTC, artragis commented on templates/forum/topic/index.html
> +        {{ topic.meta_description }}
je ne comprends pas.

2019-07-03 16:51 UTC, A-312 commented on templates/forum/topic/index.html
> +        {{ topic.meta_description }}
On reprend la description/sous titre du sujet en plus du début du sujet. Je ne peux pas expliquer mieux que : https://github.com/zestedesavoir/zds-site/issues/5274#issuecomment-466640316

2019-07-03 18:41 UTC, artragis commented on templates/forum/topic/index.html
> +        {{ topic.meta_description }}
Pour les forums on aurait donc : 

```
sujet
sous-titre
[120 caractères après salutation]
```

si c'est le cas, alors non. Déjà que "120 caractères après salutation" j'étais moyen chaud (perso j'aurais juste mis les 120 premiers caractères et c'est tout) mais là ça sert à rien.

Pour les contenus on a déjà le sous-titre dans le meta (quand il y a sous-titre).

2019-07-03 18:50 UTC, A-312 commented on templates/forum/topic/index.html
> +        {{ topic.meta_description }}
Pourquoi 120 ? La limite de twitter est de 200 : https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup.html

2019-07-03 19:03 UTC, artragis commented on templates/forum/topic/index.html
> +        {{ topic.meta_description }}
on peut customiser. Mais du coup c'est pas le meta-description mais la twitter card qu'il faut customiser, non?

2019-07-03 20:49 UTC, A-312 commented on templates/forum/topic/index.html
> +        {{ topic.meta_description }}
Actuellement, on utilise une seule variable pour la description et la twittercard https://github.com/zestedesavoir/zds-site/blob/183dd10f31f2a25dc961efe6e33451b360f89354/templates/base.html#L83

2019-07-04 05:33 UTC, artragis commented on templates/forum/topic/index.html
> +        {{ topic.meta_description }}
du coup c'est une autre issue.

2019-07-04 10:59 UTC, Vanadiae commented on templates/forum/topic/index.html
> +        {{ topic.meta_description }}
Sinon il n'y a pas moyen d'avoir l'ensemble de la description stockée quelque part et de faire `description[:120]` ou `[:200]` pour twitter ?

2019-08-22 13:08 UTC, artragis commented on templates/forum/topic/index.html
> +        {{ topic.meta_description }}
bon j'ai regardé, on utilise la même description pour le meta et le twitter card, donc à l'heure actuelle, pour les forums, le bug est corrigé.

Pour les forums, il n'y a pas de notions de sous-titre.

Pour les contenus, je regarde ce qui peut être fait.

2019-08-22 13:10 UTC, artragis commented on zds/settings/abstract_base/zds.py
> +        'greetings': ['salut', 'bonjour', 'yo ', 'hello', 'bon matin', 'tout le monde se secoue'],
franchement, je pense que là on a déjà pas mal de "cas particulier".

2019-08-22 13:23 UTC, artragis commented on templates/forum/topic/index.html
> +        {{ topic.meta_description }}
Pour les contenus, comme je le pensais, ça existe déjà : 

```html
{% block description %}
    {% if content.description %}
        {{ content.description }}
    {% else %}
        Site et association de partage de connaissances animé par sa communauté. Vous y trouverez des tutoriels et des articles de tous niveaux et des forums.
    {% endif %}
{% endblock %}

```

2019-08-22 14:48 UTC, artragis commented on templates/forum/topic/index.html
> +        {{ topic.meta_description }}
Ok j'ai vu ce que je pouvais ajouter pour les tutos/articles/billets

2019-08-25 08:39 UTC, gustavi commented
**QA** : pas bon.

`Salut, message court 2 ziuhr izeuikrhzeiur hziuer hiuzeh riuzer hiuzerh izeurh iuzer hjklzuerh izjerh iuzer yzuierg iuzer iuzeh riuzehr iuzekrh iuzer iuzer ghiyzuer gyzerg uyzehr`

 -> 

`    <meta name="description" content="alut, message court 2 ziuhr izeuikrhzeiur hziuer hiuzeh riuzer hiuzerh izeurh iuzer hjklzuerh izjerh iuzer yzuierg iuzer">`

2019-08-25 09:57 UTC, artragis commented
bien vu. je fixe ça.

2019-08-25 10:04 UTC, artragis commented
fixé, c'est bien vu, j'avais pas remarqué que la première lettre était oubliée dans le cas où on trouvait le greeting mais pas de fin de phrase.

2019-08-25 11:56 UTC, gustavi commented
**QA** : OK !

Je merge, merci :)

2019-08-25 11:57 UTC, merged