Diminution de la marge entre un tableau et sa légende
zestedesavoir/zds-site pull request #5394
Opened 2019-08-10 00:43 UTC by Helmasaur

Fix #5379

2019-08-10 11:29 UTC, A-312 commented
Q/A
=====

Avant 
-------
![image](https://user-images.githubusercontent.com/18501150/62821271-d2dee680-bb72-11e9-9f69-073d3e58593c.png)

2019-08-10 11:30 UTC, A-312 commented
Q/A
=====

Le Q/A est ok, j'ai vérifié avant/après : 

Avant 
-------
![image](https://user-images.githubusercontent.com/18501150/62821271-d2dee680-bb72-11e9-9f69-073d3e58593c.png)

Après
-------
![image](https://user-images.githubusercontent.com/18501150/62821284-ff92fe00-bb72-11e9-9a4a-946e583c6605.png)

2019-08-10 13:09 UTC, Vanadiae requested changes

2019-08-10 13:09 UTC, Vanadiae commented on assets/scss/base/_tables.scss
> +    +figcaption {
ça existe pas `+balise` comme selecteur. Tu voulais faire quoi avec ce plus ?

2019-08-10 13:11 UTC, Helmasaur commented on assets/scss/base/_tables.scss
> +    +figcaption {
Le sélecteur `+` existe en CSS. J'en suis certain. Pas en SCSS par contre.

2019-08-10 13:28 UTC, Vanadiae commented on assets/scss/base/_tables.scss
> +    +figcaption {
Oui il existe, mais avec quelque chose devant du genre `foo + bar` pour dire qu'on sélectionne uniquement quand `bar` est directement après `foo`

2019-08-10 13:43 UTC, Helmasaur commented on assets/scss/base/_tables.scss
> +    +figcaption {
Ça fonctionne comme ça comme vu sur Discord mais j'ai rajouté l'esperluette 😉 !

2019-08-10 14:16 UTC, Helmasaur commented
Comment ça se fait que l'ajout d'une règle CSS retourne une erreur ?

2019-08-10 18:24 UTC, Vanadiae commented
Problème interne aux dépôts APT de travis + https://github.com/zestedesavoir/zds-site/pull/5251#issuecomment-520168007

2019-08-10 18:40 UTC, artragis commented
C'est de ma faute pour travis, je fix ça demain.

2019-08-10 18:51 UTC, A-312 commented
~~Les anciens rapports de Travis qui renvoient toujours vert c'était l'idée de l'avion !~~

2019-08-10 19:16 UTC, Helmasaur commented
> C'est de ma faute pour travis, je fix ça demain.

Pas de problème ! Je pensais que ça venait de moi et je n'arrivais pas à trouver le problème.

2019-08-11 10:15 UTC, A-312 commented
@Helmasaur 
```sh
git checkout hotfix-tableau-legende-marge
#Tu appliques les changements distants sur ta branche
git fetch upstream
git rebase upstream/dev
#Tu pousses 
git push -f
```

2019-08-11 23:10 UTC, Helmasaur commented
Merci !

2019-08-12 09:46 UTC, artragis commented
Comme la QA est ok et qu'un rebase est fait, je merge :)

2019-08-12 09:46 UTC, merged