Nettoyage de printemps du Gulpfile, partie 2
zestedesavoir/zds-site pull request #5402
Opened 2019-08-11 11:18 UTC by Situphen

- Améliore les tâches liées au sprite

*To be continued*

2019-08-11 22:03 UTC, A-312 requested changes

2019-08-11 22:03 UTC, A-312 commented on assets/js/modal.js
> +      Modal({
Tu as fais une très grosse modification ici, es-tu certain ?

`this` ne va pas retourner pareil sans

2019-08-11 22:05 UTC, Situphen commented on assets/js/modal.js
> +      Modal({
Je t'avoue que j'ai eu l'erreur `error  Do not use 'new' for side effects         no-new` donc j'ai supprimé le `new` en espérant que ça ne change rien au fonctionnement :D

2019-08-11 22:06 UTC, A-312 commented on assets/js/modal.js
> +      Modal({
Rajoute une variable devant, ça devrait faire l'affaire

2019-08-11 22:18 UTC, A-312 commented on Gulpfile.js
> +/// / Speed mode
C'est bizarre cette façon de faire pourquoi pas : 
```js
// Speed mode
```

ou

```js
/*
 * Speed mode
 */
```

2019-08-11 22:18 UTC, A-312 commented on assets/js/content-publication-readiness.js
> +    $.ajax(url, { method: 'PUT',
``method: 'PUT',`` à la ligne ?

2019-08-11 22:18 UTC, A-312 commented on assets/js/content-publication-readiness.js
> +      } })
à la ligne

2019-08-14 19:37 UTC, Situphen commented
J'ai presque fini mon nettoyage, il y a juste deux petits points qui me dérangent avec la configuration actuelle :

- les commentaires JSDOC sont modifiés (à voir si ça les rend invalides, en tous cas c'est moche) 
  ```js
  /**
   * Toggle the text of the element by the text of an attribute
   *
   * @param {string} dataAttribute
   */
  ```
  
  ```js
  /**
     * Toggle the text of the element by the text of an attribute
     *
     * @param {string} dataAttribute
     */
  ```
- les longues lignes n'émettent pas d'erreur ou d'avertissement (ça on peut le modifier) et ne peuvent pas être modifiées (peu m'importe le style tant que c'est plus court) automatiquement par le linter (avec la commande `yarn run lint --fix`)
  ```js
  gulp.watch(['assets/images/sprite/*.png', 'assets/scss/_sprite.scss.hbs'], gulp.series(cssSprite, gulp.parallel(css, imagesSprite)))
  ```
  
  ```js
  gulp.watch(
    ['assets/images/sprite/*.png', 'assets/scss/_sprite.scss.hbs'],
    gulp.series(cssSprite, gulp.parallel(css, imagesSprite))
  )
  ```

Je vais aussi essayer de reprendre la documentation du *frontend*, mais ce sera dans une autre PR pour éviter que celle-ci traine.

2019-09-10 11:17 UTC, A-312 commented
```
gulp.watch(
  ['assets/images/sprite/*.png', 'assets/scss/_sprite.scss.hbs'],
  gulp.series(cssSprite, gulp.parallel(css, imagesSprite))
)
```

C'est correct ça ? Utilise deux variables

2019-09-25 22:13 UTC, Situphen commented
J'ai mis à jour ma branche, j'ai réparé les JSDocs et je laisse tomber l'histoire des longues lignes (ça se fera au cas par cas lors de la QA ce n'est pas grave). Il y a peut-être encore quelques ajustements à faire puis on pourra passer à la QA.

2019-12-31 22:39 UTC, Situphen commented
C'est enfin prêt à être QAtisé !

2020-01-15 16:24 UTC, AmauryCarrade commented
Alors. **QA OK !** J'ai juste remarqué quelques détails précisés ci-dessous mais je les pense bénins.

> Mettre à jour les dépendances Node avec `yarn`

`yarn` a râlé sur des co-dépendances non-satisfaites, mais ça n'a rien perturbé après et il ne s'agissait que d'avertissements.

<details>
<pre>$ yarn               
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > eslint-config-standard@14.1.0" has unmet peer dependency "eslint@>=6.2.2".
warning " > eslint-plugin-import@2.19.1" has unmet peer dependency "eslint@2.x - 6.x".
warning " > eslint-plugin-jsdoc@19.1.0" has unmet peer dependency "eslint@^5.0.0 || ^6.0.0".
warning " > eslint-plugin-node@11.0.0" has unmet peer dependency "eslint@>=5.16.0".
warning "eslint-plugin-node > eslint-plugin-es@3.0.0" has unmet peer dependency "eslint@>=4.19.1".
warning " > eslint-plugin-standard@4.0.1" has unmet peer dependency "eslint@>=5.0.0".
[5/5] Building fresh packages...
Done in 18.93s.</pre></details>

> Vérifier les commandes `yarn run build` et `yarn run watch` pour ce qui concerne le sprite

Tout est OK, les sprites sont correctement créées et mises à jour (testé en renommant des images dans le dossier `assets/images/sprite`). Aucun problème, le `_sprite.scss` est bien mis à jour. Idem en ajoutant une nouvelle image. Autant en `watch` qu'en `build`.

(Bien sûr renommer une image fait planter l'étape du SCSS vu que ça renomme une variable avec, mais osef)

> Vérifier les commandes `yarn run lint` et `yarn run lint --fix`

Y'avait rien à corriger mais ça n'a pas retourné d'erreur.

<details><summary>Logs de <code>yarn run lint [--fix]</code></summary>
<pre>$ yarn run lint
yarn run v1.21.1
$ node ./node_modules/gulp/bin/gulp.js lint
The speed mode is not enabled.
[17:12:03] Using gulpfile ~/Sites/zds-site/Gulpfile.js
[17:12:03] Starting 'lint'...
[17:12:04] Finished 'lint' after 1.31 s
Done in 2.20s.</pre>

<pre>$ yarn run lint --fix
yarn run v1.21.1
$ node ./node_modules/gulp/bin/gulp.js lint --fix
The speed mode is not enabled.
[17:12:13] Using gulpfile ~/Sites/zds-site/Gulpfile.js
[17:12:13] Starting 'lint'...
[17:12:14] Finished 'lint' after 1.32 s
Done in 2.27s.</pre></details>

> Vérifier que le site fonctionne bien avec `make run-back`

Aucun soucis. De même avec `make run` (par acquit de conscience).

2020-01-15 16:29 UTC, Situphen commented
> `yarn` a râlé sur des co-dépendances non-satisfaites, mais ça n'a rien perturbé après et il ne s'agissait que d'avertissements.

J'ai eu la même chose. J'ai l'impression qu'il suit l'ordre des paquets tels qu'ils sont dans `package.json` et installe les `eslint-config-*` et `eslint-plugin-*` avant `eslint` donc lors de l'installation de ces paquets il émet un avertissement.

2020-01-15 16:31 UTC, AmauryCarrade commented
> J'ai eu la même chose. J'ai l'impression qu'il suit l'ordre des paquets tels qu'ils sont dans `package.json` et installe les `eslint-config-*` et `eslint-plugin-*` avant `eslint` donc lors de l'installation de ces paquets il émet un avertissement.

Ça explique pourquoi ça ne pose aucun soucis après, du coup. Parfait. :)

2020-01-15 16:32 UTC, Situphen commented
Je viens de mettre à jour la branche par rapport à `dev` mais sans aucune modification.

-------

@artragis Vu que la PR modifie tout le front, j'imagine que l'idéal c'est de la merger juste après avoir fini la v29. Mentionne moi quand c'est le cas comme ça je pourrais mettre à jour la branche, puis envoyez c'est pesé.

2020-01-15 16:50 UTC, A-312 commented
Une raison pour passer à NPM si ça fonctionne mieux 🤔

2020-01-20 02:15 UTC, Situphen commented
J'ai rebasé, mis à jour le `yarn.lock` et j'ai aussi corrigé le bout de code du Gulpfile qui met un `;` entre les fichiers JS lorsqu'on les concatène.

2020-01-26 17:15 UTC, philippemilink commented
Rapport de QA
============

OK.

Mêmes remarques que Amaury. Je n'ai pas réussi à faire cracher une erreur à `yarn run lint` en alignant mal une ligne dans un fichier JS. Je ne sais si c'est normal, ou si le linter se met à râler seulement pour d'autres choses.

2020-01-26 18:46 UTC, Situphen commented
J'ai mis à jour ma branche par rapport à `upstream/dev`.

> Je n'ai pas réussi à faire cracher une erreur à yarn run lint en alignant mal une ligne dans un fichier JS. Je ne sais si c'est normal, ou si le linter se met à râler seulement pour d'autres choses.

Ce n'est pas normal ! Il me met une erreur quand j'indente mal une ligne (que ce soit un multiple de 4 ou pas). À noter que pour le fichier `assets/js/editor.js` est exclu du lint, cette PR n'a que trop tardé donc je le ferai dans une autre PR.

```
/home/situphen/Code/zds-site/assets/js/autocompletion.js
  307:1  error  Expected indentation of 4 spaces but found 6  indent

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

2020-01-26 18:52 UTC, philippemilink commented
Je testais justement avec le fichier `editor.js` ! Je viens de tester avec le fichier `accordeon.js` et c'est bon, `yarn lint` râle bien, `--fix` corrige bien les erreurs.

**QA ok**

2020-01-26 18:55 UTC, Situphen commented
Travis est vert, merge qui veut !

2020-01-26 19:21 UTC, merged