Ajoute une commande pour publier un contenu
zestedesavoir/zds-site pull request #5411
Opened 2019-08-19 11:57 UTC by artragis

cette commande est nécessaire pour publier les
tutoriels qui sont trop longs à publier par rapport
au timeout de gunicorn.

# QA

- créer un tuto
- mettez-le en réservation
- lancez `python manage.py publish_content {id_de_votre_contenu}`
- observez que le contenu est publié
- lancez `python manage.py publication_watchdog`
- observé que les exports sont générés (ne vérifier que leur présence)

2019-08-19 20:31 UTC, AmauryCarrade commented
QA **NOK**

- Petit détail, la commande s'appelle `validate_content` et non `publish_content`
- Surtout, l'exécution plante à cause d'un mauvais usage de `argparse` : la méthode `add_option` n'existe pas

```
$ python manage.py validate_content 4
Traceback (most recent call last):
  File "manage.py", line 47, in <module>
    execute_from_command_line(sys.argv)
  File "/home/amaury/Sites/zds-site-situphen/zdsenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/amaury/Sites/zds-site-situphen/zdsenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/amaury/Sites/zds-site-situphen/zdsenv/lib/python3.7/site-packages/django/core/management/base.py", line 308, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "/home/amaury/Sites/zds-site-situphen/zdsenv/lib/python3.7/site-packages/django/core/management/base.py", line 282, in create_parser
    self.add_arguments(parser)
  File "/home/amaury/Sites/zds-site-situphen/zds/tutorialv2/management/commands/validate_content.py", line 16, in add_arguments
    parser.add_option('--major', dest='is_major', action='store_true')
AttributeError: 'CommandParser' object has no attribute 'add_option'
```

2019-08-19 20:39 UTC, AmauryCarrade requested changes
Pour corriger le problème d'arguments

2019-08-19 20:39 UTC, AmauryCarrade commented on zds/tutorialv2/management/commands/validate_content.py
> +        parser.add_option('--major', dest='is_major', action='store_true')
```suggestion
        parser.add_argument('--major', dest='is_major', action='store_true')
```

2019-08-19 20:39 UTC, AmauryCarrade commented on zds/tutorialv2/management/commands/validate_content.py
> +        parser.add_option('--source', dest='source', type=str, default='')
```suggestion
        parser.add_argument('--source', dest='source', type=str, default='')
```

2019-08-19 20:40 UTC, AmauryCarrade commented
Autre problème observé en corrigeant le soucis ci-dessus : les `PublishedContent` n'ont pas d'attribut `current_validation`

```
Traceback (most recent call last):
  File "manage.py", line 47, in <module>
    execute_from_command_line(sys.argv)
  File "/home/amaury/Sites/zds-site-situphen/zdsenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/amaury/Sites/zds-site-situphen/zdsenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/amaury/Sites/zds-site-situphen/zdsenv/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/amaury/Sites/zds-site-situphen/zdsenv/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/amaury/Sites/zds-site-situphen/zds/tutorialv2/management/commands/validate_content.py", line 44, in handle
    save_validation_state(content, is_update, published, content.current_validaton, versioned,
AttributeError: 'PublishableContent' object has no attribute 'current_validaton'
```

2019-08-20 08:45 UTC, artragis commented
Merci, j'ai modifié; Par contre ça me semble bizarre que current_version ne soit pas trouvé alors que je l'avais setté. Mais bon au moins là ça devrait aller.

2019-08-20 09:22 UTC, AmauryCarrade requested changes
QA toujours **NOK** mais cette fois c'est trivial : une simple faute de frappe.

En corrigeant les deux détails cités, la QA est OK. À noter que je ne pourrai pas confirmer car je n'aurai plus d'ordinateur à portée de main d'ici une demi-heure ^^

Le watchdog a planté chez moi par contre mais d'une erreur qui est indépendante de cette PR. Donc ça devrait marcher. Malheureusement j'ai à peine eu le temps de QA ça, je n'ai pas celui de creuser plus loin là tout de suite :/

2019-08-20 09:22 UTC, AmauryCarrade commented on zds/tutorialv2/management/commands/validate_content.py
> +            save_validation_state(content, is_update, published, content.current_validaton, versioned,
```suggestion
            save_validation_state(content, is_update, published, content.current_validation, versioned,
```
Faute de frappe

2019-08-20 09:22 UTC, AmauryCarrade commented on zds/tutorialv2/management/commands/validate_content.py
> +        content.current_validation =  Validation.objects.filter(content=content, status='PENDING_V').first()
```suggestion
        content.current_validation = Validation.objects.filter(content=content, status='PENDING_V').first()
```
PEP 8

2019-08-20 09:34 UTC, artragis commented
Si la QA est ok après modif, je merge, merci du coup de main @AmauryCarrade

2019-08-20 09:34 UTC, merged