Ajouter le bloc neutre à l'éditeur (fix #4938)
zestedesavoir/zds-site pull request #5475
Opened 2019-10-13 11:35 UTC by philippemilink

Fix #4938 

Si quelqu'un a envie de faire mieux comme icône, qu'il n'hésite pas !

2019-10-13 13:54 UTC, artragis requested changes

2019-10-13 13:54 UTC, artragis commented on assets/js/editor.js
> -                    selection.current = "[[erreur]]\n" + iterateRows(selection.current, "|");
le block c'est `[[erreur]]` pas  `[[error]]`

2019-10-13 14:23 UTC, philippemilink commented on assets/js/editor.js
> -                    selection.current = "[[erreur]]\n" + iterateRows(selection.current, "|");
Bien vu ! C'est pour ça que c'était un cas à part !

2019-10-13 14:37 UTC, philippemilink commented on assets/js/editor.js
> -                    selection.current = "[[erreur]]\n" + iterateRows(selection.current, "|");
Corrigé !

2019-10-16 13:17 UTC, firm1 commented
**Rapport de QA**

QA OK.

Un rebase et ça se merge.

2019-10-16 13:36 UTC, merged