Attend que ZMD soit lancé pour continuer l'installation
zestedesavoir/zds-site pull request #5484
Opened 2019-10-22 20:54 UTC by philippemilink

Numéro du ticket concerné: #5480 

### Contrôle qualité

Pour chaque test, lancer 
```bash
./scripts/install_zds.sh -packages -virtualenv -node -back -front -zmd +data
```

Trois cas sont à tester:
1. cas *normal*: lancer la commande d'installation: tout devrait fonctionner, éventuellement le premier ping échoue
2. ZMD ne démarre *pas du tout*: commenter la ligne 504 du fichier `install_zds.sh`, celle qui lance ZMD. Le script d'installation devrait finir par quitter, avant de charger les fixtures.
3. ZMD *est lent à démarrer*: tout en gardant la ligne de lancement de ZMD commentée, lancer le script d'installation, attendre que le premier ping échoue, puis dans une autre console, lancer `make zmd-start`. Les fixtures devraient se charger.

2019-10-22 21:52 UTC, Situphen requested changes

2019-10-22 21:52 UTC, Situphen commented on scripts/install_zds.sh
> +    done
Le code que tu proposes fais 5 essais avec 5 secondes entre chaque essai, je ne pense pas que ce soit optimal. Premièrement, je peux me tromper mais je ne pense pas que zmarkdown mette 25 secondes à se lancer, je dirais qu'au bout de 5 secondes on peut arrêter d'essayer. Deuxièmement, étant donné que vérifier si zmarkdown fonctionne correctement ne demande pas d'effort à l'ordinateur, on peut augmenter la fréquence des essais.

Je propose donc qu'on attente le démarrage de zmarkdown pendant 5 secondes au total, et que l'on regarde si zmarkdown est lancé tous les cinquièmes de secondes. On aurait donc `sleep 0.2` et `$nb_zmd_try -lt 25`.

2019-10-22 21:52 UTC, Situphen commented on scripts/install_zds.sh
> +
Avec les modifications que je propose plus haut, ce bloc n'est plus nécessaire et peut donc disparaître !

2019-10-23 11:07 UTC, A-312 commented on scripts/install_zds.sh
> +    done
oui 100 ou 200 ms puis 5 sec deux fois

2019-10-23 12:48 UTC, Situphen commented on scripts/install_zds.sh
> +    done
> oui 100 ou 200 ms puis 5 sec deux fois

Je ne vois pas l'intérêt, et ça complexifie le code.

2019-10-23 15:28 UTC, A-312 commented on scripts/install_zds.sh
> +    done
```
while ...
if i > 3
delay = 5
```
Je pense attendre 5 sec peut-être utile ( ref a gulp qui prend 5sec avant d'exécuté le script certaine fois)

2019-10-23 15:31 UTC, Situphen commented on scripts/install_zds.sh
> +    done
Oui mais il peut très bien prendre seulement 1 seconde et donc tu perds 4 secondes à attendre pour rien. Autant tester toutes les 0,2 secondes étant donné qu'il n'y a pas d'inconvénients.

2019-10-23 15:41 UTC, A-312 commented on scripts/install_zds.sh
> +    done
S'il n'y a pas de risque d'avoir des erreurs a cause de requête envoyé trop tôt. faisons comme ça

2019-10-23 16:58 UTC, philippemilink commented
C'est corrigé. Au pire, il y a 40 pauses de 0,2s. J'ai augmenté par rapport au 25 proposé, car la première fois que j'ai fait le test sur ma machine, zmd a mis plus de 5 secondes à se lancer (les caches devaient être froids... :smile:  )

2019-10-24 05:08 UTC, A-312 commented
Dernier point : curl est disponible par défaut sur toutes les machines Linux ? Les autres blocs du script utilisaient wget, pas besoin de l'ajouter à la liste des dépendances ?

2019-11-13 23:09 UTC, firm1 commented
### Rapport de QA

*QA OK*

Les cas testé sont bien fonctionnels. Un rebase et on merge.

2019-11-14 08:05 UTC, merged