WIP : Gestion des contributions aux contenus de ZdS
zestedesavoir/zds-site pull request #5485
Opened 2019-10-24 10:20 UTC by firm1

Cette PR permet de gérer la contribution aux contenus de Zeste de Savoir.

Ticket #5120 

### Un descriptif du workflow

#### Point de vue de l'auteur

- Je peux ajouter un contributeur au contenu

![Capture d’écran de 2019-10-24 12-17-46](https://user-images.githubusercontent.com/6066015/67476498-6bf0aa00-f658-11e9-9da6-ffed5149a311.png)

![Capture d’écran de 2019-10-24 12-17-57](https://user-images.githubusercontent.com/6066015/67476514-7317b800-f658-11e9-8cbc-96b0c62dfc30.png)

- Je peux supprimer un contributeur du contenu

![Capture d’écran de 2019-10-24 12-18-05](https://user-images.githubusercontent.com/6066015/67476528-7a3ec600-f658-11e9-98d5-2063e00aff5e.png)

#### Point de vue du contributeur

- Je peux voir sur ma page de profil, le nombre de contenu auxquels j'ai contribué

![Capture d’écran de 2019-10-24 12-18-15](https://user-images.githubusercontent.com/6066015/67476540-8165d400-f658-11e9-906b-70b0d5e2dbff.png)

- Lorsque le contenu est publié, on peut me voir dans la liste des contributeurs du contenu

![Capture d’écran de 2019-10-24 12-17-32](https://user-images.githubusercontent.com/6066015/67476556-87f44b80-f658-11e9-98c3-c8f85eb535f7.png)

### Contrôle qualité

- Lancez `make migrate-db` (le modèle ayant évolué)
- Lancez `make generate-fixtures` (des nouvelles fixtures des roles de contributions ont été ajouté)
- Connectez vous avec un utilisateur et tester les ajouts/suppression de contributeurs et vérifier que sur la page de profil des contributeurs, on voit bien les nombres de contributions.

Merci.

### Reste à faire

rajouter le fichier des fixtures.

2019-10-25 12:45 UTC, firm1 commented
Pour info la PR est prête a la QA.

2019-11-01 16:31 UTC, philippemilink commented
**Rapport de QA**


Quelques petits soucis:
- (remarque:) le `make generate-fixtures` m'a renvoyé une erreur de UniqueConstraint, j'ai donc fait un `make wipe-db`
- connecté en *user6*, j'ai ajouté *user10* comme *illustrateur* d'un article. Tout apparaît correctement.
- Cependant *user10* reçoit un MP de la part de *admin* (pourquoi *admin* et pas *user6* ?) intitulé "Aide à la relecture de l'article" (alors qu'il n'a pas relu, il a illustré) lui notifiant qu'il a été désigné comme relecteur (et pas illustrateur) de l'article bidule. Le lien de l'article mène vers une 403: l'URL est de la forme `/contenus/17/slug`, mais *user10* peut accéder à l'article avec l'URL de la forme `/articles/17/slug` (que j'ai récupérée depuis la page de profil de *user10*).


Je me suis arrêté là, je ne pense que ce soit les comportements désirés !


Et un petit rebase sera nécessaire avant de merger ! :smiley:

2019-11-04 23:42 UTC, firm1 commented
Merci @philippemilink pour la QA.

J'ai corrigé les points que tu as remonté sauf celui-ci : "un MP de la part de admin (pourquoi admin et pas user6 ?)". Parce que admin est le compte bot, j'ai gardé le même fonctionnement que ce qu'on a avec l'ajout des auteurs. C'est le bot (clem sur le site) qui prévient de l'ajout d'un nouvel auteur.

Tu peux reprendre ta QA.

2019-11-05 07:54 UTC, artragis commented
il te manque une migration @firm1

2019-11-05 08:17 UTC, firm1 commented
Ah ok. Bien vu. Je fais ça dès que possible.

2019-11-07 21:38 UTC, philippemilink commented
**Rapport de QA**

Sur le fonctionnement global, tout est bon: ajout, suppression de contributeurs à des articles / tutoriels et notification par message.

Cependant, trois détails:

- le tableau des contributeurs dans la popup de gestion des contributions dépasse de la popup:
![contributeurs](https://user-images.githubusercontent.com/5911232/68429379-40200900-01ae-11ea-8837-4aa27628150c.png)

- il est possible d'ajouter le même utilisateur avec le même rôle plusieurs fois (avec des rôles différents je pourrais comprendre, mais là je pense que c'est un bug):
![contributeurs-double](https://user-images.githubusercontent.com/5911232/68429438-5c23aa80-01ae-11ea-8b44-4fbc4a441935.png)

- suggestion: dans le message qui est envoyé au contributeur, ce serait pratique d'avoir le lien vers le contenu auquel ils ont contribué (pas juste le titre).

2019-11-08 05:52 UTC, A-312 commented
C'est vraiment utile d'avoir une popup plutôt qu'une page pour la liste de gestion des contributeurs ?

Je pense que quand tu as envie de gérer les contributeurs, tu veux en ajouter 10 sans que ça se ferme à chaque fois ou pouvoir faire page précédente/suivante sans que la popup soit fermé au retour. Comment ça se passe avec 10 lecteurs ? La liste se scroll ?

En plus un co-aut

2019-11-08 05:53 UTC, A-312 commented
Missclick

2019-11-13 20:53 UTC, firm1 commented
J'ai mis à jour la branche en corrigeant les bugs détectés par @philippemilink 

Cependant 

> suggestion: dans le message qui est envoyé au contributeur, ce serait pratique d'avoir le lien vers le contenu auquel ils ont contribué (pas juste le titre).

Etant donné que l'ajout du contributeur ne lui donne pas forcément les accès au contenu, on n'a pas forcément de lien valide à donner. Si le contributeur est ajouté au contenu qui n'est pas encore publié, le lien ne lui servira guère.

> C'est vraiment utile d'avoir une popup plutôt qu'une page pour la liste de gestion des contributeurs ?

Pour le coup, ce n'est pas une page qu'on est amené a visiter souvent. Et le faible nombre d'informations dans la popup me fait dire qu'on a pas besoin d'une page pour ça. C'est comme pour la gestion des auteurs en fait. Je ne pense pas que les gens aient besoin d'une page entière pour gérer les contributeurs. Perso, je pense pas qu'il y ait aujourd'hui un contenu publié avec plus de 10 contributeurs.

> Comment ça se passe avec 10 lecteurs ? La liste se scroll ?

Avec 11 contributeurs sur un article, j'ai cet affichage.

![Capture d’écran de 2019-11-13 21-51-35](https://user-images.githubusercontent.com/6066015/68803440-03498b80-0660-11ea-9fbe-541fda18c128.png)

2019-11-17 18:34 UTC, philippemilink commented
### Rapport de QA

> - le tableau des contributeurs dans la popup de gestion des contributions dépasse de la popup

Corrigé:
![contributeurs-ok](https://user-images.githubusercontent.com/5911232/69012010-14044500-0971-11ea-83da-ff8cdb76185a.png)


> - il est possible d'ajouter le même utilisateur avec le même rôle plusieurs fois (avec des rôles différents je pourrais comprendre, mais là je pense que c'est un bug)

Corrigé. On ne peut ajouter plusieurs fois un utilisateur que s'il a un rôle différent.


Tout est bon. :+1:

2019-11-18 19:39 UTC, artragis requested changes
La PR me semble très bonne, les changements à faire me semblent légers.

2019-11-18 19:39 UTC, artragis commented on templates/tutorialv2/contributions.html
> +        {% trans "contribution_articles de" %} {{ usr.username }}
C'est normal ça?

2019-11-18 19:39 UTC, artragis commented on zds/tutorialv2/views/contents.py
> +        elif not self.sort:
pourquoi ce `elif` plutôt que `else`?

2019-11-18 19:39 UTC, artragis commented on zds/tutorialv2/views/contents.py
> +        messages.error(self.request, _("Les relecteurs sélectionnés n'existent pas."))
les contributeurs séléctionnés, non?

2019-11-18 19:39 UTC, artragis commented on zds/tutorialv2/migrations/0028_auto_20191024_1918.py
> +            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorialv2.ContentContributionRole', verbose_name='role de la contribution'),
veut-on vraiment un cascade sur celui-là?

2019-11-18 19:39 UTC, artragis commented on zds/tutorialv2/forms.py
> +    contribution_role = ReviewerTypeModelChoiceField(
Bien vu :)

2019-11-18 21:12 UTC, firm1 commented on zds/tutorialv2/views/contents.py
> +        elif not self.sort:
C'était pour rester cohérent avec la [façon de faire](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/contents.py#L1953) actuellement en prod.

Il me semble que l'idée c'est de prévoir le cas ou un autre filtre peut être défini dans une classe fille.

2019-11-18 21:13 UTC, firm1 commented on templates/tutorialv2/contributions.html
> +        {% trans "contribution_articles de" %} {{ usr.username }}
non, ce n'est pas normal, erreur de copier/coller ...

2019-11-18 21:20 UTC, firm1 commented on zds/tutorialv2/migrations/0028_auto_20191024_1918.py
> +            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorialv2.ContentContributionRole', verbose_name='role de la contribution'),
je pense que oui. Si on supprime un rôle, on peut supprimer toutes les associations `contenu+membre+role` qui y sont liées, puisqu'elle n'ont plus sens sans le rôle.

2019-11-18 21:29 UTC, artragis commented on zds/tutorialv2/views/contents.py
> +        elif not self.sort:
ok merci.

2019-11-18 21:29 UTC, artragis commented on zds/tutorialv2/migrations/0028_auto_20191024_1918.py
> +            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorialv2.ContentContributionRole', verbose_name='role de la contribution'),
je valide alors :)

2019-11-19 06:55 UTC, merged

2019-11-19 06:57 UTC, artragis commented
par contre j'ai pas pu fermer le ticket car c'est évident que c'est pas #5120

2019-11-19 07:29 UTC, A-312 commented
tu as link une pr et non une issue