Ajoute la possibilité de déplacer "au début", uniquement en JS
zestedesavoir/zds-site pull request #5504
Opened 2019-11-05 12:05 UTC by artragis

# QA 

- créer un tuto
- créer deux parties
- dans la partie 1 créer un chapitre
- dans la page de garde du tuto, faites un glisser/déposer du chapitre vers la partie 2
- rafraîchissez
- assurez vous que le chapitre est bien dans la partie 2

2019-11-05 12:22 UTC, A-312 requested changes

2019-11-05 12:22 UTC, A-312 commented on assets/js/content.js
Tu n'as pas enlevé

```js
// TODO : [BACK] Add "beginning" moving_method
``` 

une dizaine de ligne plus bas

2019-11-05 12:42 UTC, artragis commented on assets/js/content.js
Ah pas vu

2019-11-13 01:20 UTC, firm1 commented
### Rapport de QA.

**KO**

- J'ai crée un tutoriel (utilisateur user) avec un titre une licence et catégorie.
- J'ai crée un Partie 1, puis son chapitre 1
- J'ai crée ensuite une Partie 2
- Je retourne au sommaire et je déplace par drag/drop le chapitre 1 vers la partie 2
- J'ai une erreur dans la console JS.
- En rafraîchissant, je me rend compte que le chapitre n'a pas été déplacé.

![Capture d’écran de 2019-11-13 02-15-45](https://user-images.githubusercontent.com/6066015/68724475-e8254000-05bb-11ea-91d8-4a96ce742b6d.png)

2019-11-13 06:09 UTC, A-312 commented
je regarderais, j'essaye ce soir

2019-11-13 10:08 UTC, artragis commented
ok, l'url ne semble pas être la bonne, mais comme j'ai fait confiance aux "todo" de a-312 j'ai pas assez réfléchi à ce que vallent chaque variable et malheureusement j'ai un petit soucis sur le pc sur lequel je suis en ce moment.

2019-11-13 10:36 UTC, A-312 commented
Il faut peut être enlever le dernier caractère

2019-11-13 18:41 UTC, A-312 commented
http://127.0.0.1:8000/contenus/deplacer/

```
moving_method: first:partie-1/chapitre-2018/
container_slug: chapitre-a
first_level_slug: partie-1
child_slug: a4
pk: 34
```

2019-11-13 20:27 UTC, artragis commented
il manque un truc dans l'url non?

2019-11-13 20:55 UTC, A-312 commented
"Actuellement" avec after, on a : 

http://127.0.0.1:8000/contenus/deplacer/

```
moving_method: after:chapitre-c/c3
container_slug: chapitre-a
first_level_slug: partie-1
child_slug: a4
pk: 34
```

Pour cette structure : 
![image](https://user-images.githubusercontent.com/18501150/68803602-5c192400-0660-11ea-9168-5515dfa13ce8.png)

2019-11-13 21:02 UTC, A-312 commented
J'ai testé avec `return "first:" + path.slice(1);`, ça ne corrige pas le soucis.

2019-11-13 21:18 UTC, artragis commented
ok je vérifierai quand j'aurai un environnement fiable.

2019-11-23 18:37 UTC, firm1 commented
## Rapport de QA

**Presque OK**

Les déplacements en glisser/déposer fonctionnent bien. Cependant le problème restant est celui-ci.

Lorsque je déplace un chapitre dans une autre partie, et que je clique immédiatement sur le chapitre en question, j'ai une erreur 404. Mais si je rafraîchis la page de tutoriel, plus de 404.

En gros, le lien cible devrait changer au drop du chapitre. Ce n'est pas le cas.

2019-11-23 20:29 UTC, artragis commented
ah bien vu. je tenterai de modifier du coup, c'est pas dans le scope de ma PR mais au moins ça permettra de merger la feature complète plus rapidement.

2019-11-23 21:10 UTC, A-312 commented
C'est censé se passer ici : https://github.com/artragis/zds-site/blob/6cf0ef18485e50bdeb7ebe9d32ae7dc32dc4f2c6/assets/js/content.js#L70

2019-11-24 10:16 UTC, A-312 commented
La requête ajax post renvoie une 404 à certain moment ou même une 500 Quand je déplace

Section1 (se situant dans partie B chapitre A) vers partie A chapitre C.

2019-11-24 10:28 UTC, A-312 commented
> En gros, le lien cible devrait changer au drop du chapitre. Ce n'est pas le cas.

Mon selecteur : $item.find("[data-children-type] > [data-slug] a") ne sélectionne pas tous les éléments seulement les éléments enfants sans modifier le lien de l'élément actuel

2019-11-24 12:24 UTC, artragis commented
`zds.tutorialv2.views.contents:chapitre-2019 was moved after partie-2/chapitre-c in tutorial id:34` montre que tu fais un truc qui n'est pas dans le scope de ma PR ou que tu n'as pas buildé le front.

2019-11-24 12:42 UTC, A-312 commented
Étrange sur la beta je n'avais pas ça, bug car je suis sur Windows ?

2019-11-24 19:51 UTC, A-312 submitted a review, later dismissed

2019-11-28 23:14 UTC, firm1 commented
## Rapport de QA

PS: je teste avec chrome.

Une regression observée depuis ma dernière QA. Je n'arrive pas à glisser/déposer un chapitre d'une partie vers un une partie vide.

Voici la structure de mon chapitre.

![Capture d’écran de 2019-11-29 00-06-52](https://user-images.githubusercontent.com/6066015/69834762-cb843b80-123c-11ea-8fb4-8c1b2bbd8467.png)

Quand je selectionne le chapitre C1.1 (qui possède une section), je n'ai pas moyen de le mettre dans P2. Je ne peux que transformer C1.1 en une autre partie.

Ce problème était censé être corrigé avec les derniers commits il me semble.

2019-11-29 16:53 UTC, A-312 commented
> Ce problème était censé être corrigé avec les derniers commits il me semble.

Une partie vide (dès le chargement de la page) ne peut recevoir qu'un chapitre ou partie vide.

Une partie (vide suite à un dnd, qui était plein au chargement de la page) ne peut recevoir que du contenu du même type (si c'était un chapitre que des extraits ou si c'était une partie que des chapitres).

Si c'est bien ça, c'est compliqué à régler et doit faire l'œuvre d'une autre PR (voir ma dernière (ou avant-dernière) issue.

2019-11-29 16:55 UTC, A-312 commented
#5538

2019-12-01 13:23 UTC, artragis commented
alors là c'est vraiment bizarre. on ne peut en effet pas déplacer un chapitre dans une partie vide (ce qui est quand même le but de la PR). Le rebase a cassé des choses.

2019-12-01 13:34 UTC, artragis commented
Plus précisément c'est le refacto qui a cassé la structure du html
problème je ne connais pas la structure attendue.

2019-12-01 22:18 UTC, A-312 commented
> alors là c'est vraiment bizarre. on ne peut en effet pas déplacer un chapitre dans une partie vide (ce qui est quand même le but de la PR). Le rebase a cassé des choses.

Ok #5540

2019-12-05 12:14 UTC, A-312 commented on templates/tutorialv2/includes/child.part.html
> +                     {% if not child.has_containers %}
Je sais que tu n'as pas fini mais : imagine que child devient vide, c'est plutôt au JS de savoir si l'élément a des enfants ou non. Le HTML/template devrait vraiment avoir aucune logique (comparative), je ne sais pas si c'est temporaire ou non. (A mon sens, moins on a de logique dans le HTML, moins on a de chance d'avoir un effet de bord sur une modif du code et ainsi on évite aussi de réduire la complexité du code).

Ensuite au lieu de : data-accept-container et data-accept-extracts ce n'est pas mieux de changer la logique initiale et plutôt de faire : `data-type=extract or container -> (pour chapter & part)` ou `data-element-type=` c'est a dire indiquer le type de l'element actuel dans le HTML.

2019-12-05 18:07 UTC, artragis commented on templates/tutorialv2/includes/child.part.html
> +                     {% if not child.has_containers %}
> Ensuite au lieu de : data-accept-container et data-accept-extracts ce n'est pas mieux de changer la logique initiale et plutôt de faire : data-type=extract or container -> (pour chapter & part) ou data-element-type= c'est a dire indiquer le type de l'element actuel dans le HTML.

globalement un attribut unique pour deux informations c'est rarement un bon pattern.

> Je sais que tu n'as pas fini mais : imagine que child devient vide, c'est plutôt au JS de savoir si l'élément a des enfants ou non. 

les conditions ont été copiées pour m'assurer que j'avais quelque  chose partout. Typiquement je vais ajaxifier le tout, quand j'aurais le temps (tm). Là je voulais juste retirer ce bouton de la liste car il faisait chier. Et un bon moyen de le retirer sans que ça casse les pieds de tout le monde c'est de rendre la création d'extrait rapide

2019-12-09 12:22 UTC, A-312 commented
> globalement un attribut unique pour deux informations c'est rarement un bon pattern.

Je trouve que si ça permet de rendre le code plus dynamique et de faire de la "gestion de masse". De plus tu as des sélecteurs pour choisir un élément selon sa valeur égales ou différentes.

> Là je voulais juste retirer ce bouton de la liste car il faisait chier. Et un bon moyen de le retirer sans que ça casse les pieds de tout le monde c'est de rendre la création d'extrait rapide

C'est agréable de les avoirs, surtout que j'ai fais le support pour dans le js.

----

Pour moi le plus grand soucis c'était d'avoir deux group sortable qui n'interagissent pas ensemble, je voulais les fusionner et en avoir un seul (un seul appel à sortable). Mais si tu arrives à faire sans c'est good.

2019-12-09 12:48 UTC, artragis commented
Non il sont pas correctement supportés dans le JS t il est peu probable qu'on puisse correctement les supporter. C'est pour ça que je les enlève de la **liste**, je les ai mis juste en dessous. Et la possibilité de créer rapidement un extrait sans avoir à passer par le texte c'est une demande fréquente.

2019-12-12 17:21 UTC, A-312 commented
![image](https://user-images.githubusercontent.com/18501150/70734247-2d987280-1d0c-11ea-980f-d67c08051701.png)

Tu enlèves le bouton pour ajouter un bouton et input ?

2019-12-12 17:23 UTC, A-312 commented
Il y a la solution POPUP. :/

2019-12-12 17:30 UTC, A-312 commented
![image](https://user-images.githubusercontent.com/18501150/70734552-bd3e2100-1d0c-11ea-9214-aa6385636935.png)

ORIGINE : PARTIE > CHAPITRE > SECTION A
DESTINATION : CHAPITRE > [nouvelle position de Section A]

Quand je drag'n'drop section A selon le schéma ci-dessus, la conversion ne transforme pas les H4 en H3 (il faut surement corriger mon code qui fait la conversation => selecteur qui n'est plus valide ?). (SVP ne corrigez pas ça en CSS ! Respectez la structure HTML).

----------

Ensuite : 

ORIGINE : PARTIE > CHAPITRE A
DESTINATION : CHAPITRE (VIDE) > [nouvelle position de Section A]

On ne peut pas d"placer CHAPITRE A dans CHAPITRE (VIDE) .

2019-12-12 17:32 UTC, A-312 requested changes
Nécessite les changements ci-dessus

2019-12-15 19:12 UTC, artragis commented
pourquoi sont-ils marqués "off topic"?

2019-12-15 19:39 UTC, A-312 commented
> pourquoi sont-ils marqués "off topic"?

Je pensais que c'était Q/A-able mais en faite non. 😕

2019-12-15 20:05 UTC, artragis commented
qu'est-ce qui est q/A ble mais en fait non?

2019-12-15 20:29 UTC, A-312 commented
> qu'est-ce qui est q/A ble mais en fait non?

Cette PR mais elle nécessite encore beaucoup de travail

2019-12-15 21:19 UTC, artragis commented
oui elle nécessite encore du travail mais du coup tes remarques ne sont pas "off topic" elles sont même utiles du coup je comprends vraiment pas pourquoi tu as fait ça.

bref dès que j'ai le temps je modifie.

(soit dit en passant, à la base la PR ne faisait qu'implémenter le déplacement dans un chapitre vide, elle s'est transformé en "régler tous les problèmes du d&d")

2019-12-16 01:33 UTC, A-312 commented
> (soit dit en passant, à la base la PR ne faisait qu'implémenter le déplacement dans un chapitre vide, elle s'est transformé en "régler tous les problèmes du d&d")

C'est toi qui a choisi de laisser ouvert cette PR et de fixe ici d'autres bugs non lier à ta PR.

Pick tes commits après https://github.com/zestedesavoir/zds-site/pull/5504#issuecomment-559843804 dans une nouvelle PR.

2020-01-02 13:19 UTC, A-312 commented
Tu peux merge ta PR avant le commentaire indiqué dans lon précédent message ou c'était bon + le BACK de l'ajax pour insérer une section?

Garde tes commits après, tu les ajouteras quand j'aurais fixer le bug du drag'n'drop

2020-04-13 16:39 UTC, A-312 commented
Voir #5572

2020-04-13 16:39 UTC, closed without merging