Nouvel éditeur markdown pour Zeste de Savoir
zestedesavoir/zds-site pull request #5517
Opened 2019-11-11 21:58 UTC by firm1

Cette PR apporte un nouvel éditeur client qui supporte zmarkdown. Le client s'appuie sur easymde et l'étend pour s'adapter au zmarkdown.

### Les fonctionnalités innovantes de cette PR

- La coloration syntaxique du code directement dans la zone de texte (WISIWYM) : permise par l'utilisation de *codemirror*, c'est **LE TRUC** demandé par la majorité des auteurs.

![Capture d’écran de 2019-11-11 22-33-47](https://user-images.githubusercontent.com/6066015/68623804-9acea300-04d5-11ea-8c18-5b8045148f8e.png)

- La possibilité d'avoir un aperçu de notre saisie à coté du texte en Markdown 

![Capture d’écran de 2019-11-11 22-38-22](https://user-images.githubusercontent.com/6066015/68623825-a7eb9200-04d5-11ea-815a-38a91cef66cd.png)

- La possibilité de passer l'éditeur en plein écran (pour profiter au maximum de son écran) voire d'avoir la vue *side by side* en plein écran.

![Capture d’écran de 2019-11-11 22-37-56](https://user-images.githubusercontent.com/6066015/68623844-b20d9080-04d5-11ea-9969-f629b8e9e693.png)

- Les raccourcis clavier sur les boutons

- De nouveaux boutons :
    - Le bouton de check list
    - Le bouton d'ajout de formule mathématique (il manquait vraiment je trouve)
    - Le bouton d'ajout d'une table

- L'affichage d'informations utiles (date du dernier enregistrement automatique, nombre de lignes, nombre de mots) du texte.

![Capture d’écran de 2019-11-11 22-36-30](https://user-images.githubusercontent.com/6066015/68623869-c487ca00-04d5-11ea-9e72-838c60a46061.png)

### Les régressions qu'amènent cette *Pull Request*

Voici la liste des régressions qui arrivent avec cette PR. Je pense personnellement que l'on peut se passer ça pour une v1 du nouvel éditeur, mais je ne voudrais pas juger moi même.

- On n'a plus de bouton "ajouter un smiley/emoji"
- On n'a plus de bouton ajouter un caractère spécial
- Plutôt que d'avoir des fenêtre modales "ZdS" qui s'affiche quand on clique par exemple sur "nouveau lien" pour nous demander une url, on a plutôt des fenêtres du navigateur web qui sont moins esthétiques que les modales de ZdS.

![Capture d’écran de 2019-11-11 22-47-06](https://user-images.githubusercontent.com/6066015/68623934-eaad6a00-04d5-11ea-875f-b2cd9f932cf2.png)

### Là ou il faudrait un coup de pouce ?

Pour régler les régressions, il faudrait que je sois capable de reproduire en *css* le comportement de la zone qui pop (l'espèce de dropdown) lorsqu'on clique sur un menu dans la barre d'outils.

En image ça donne ça.

![Capture d’écran de 2019-11-11 22-47-56](https://user-images.githubusercontent.com/6066015/68623928-e6814c80-04d5-11ea-80dc-5872367739ce.png)

# Instructions de QA

- Build du front
- Rendez-vous sur toutes les pages ou l'on a besoin d'écrire du markdown (répondre a un topic du forum, saisir un texte dans son contenu, modifier sa biographie) et tester les boutons de l'éditeur.

J'aimerai bien avoir vos retours (ou votre aide) sur cette PR

2019-11-12 11:25 UTC, Situphen reviewed
Je n'ai pas le temps de tout lire en détails mais voici déjà quelques remarques sur ma lecture du code. Il faudra faire attention à l'imbrication de plusieurs `if { } else { }` car ça peut devenir lourd à lire. Ne pas hésiter à sauter des lignes, etc. Pour tout ce qui est vraiment esthétique on verra à la fin mais il faudra uniformiser un peu.

2019-11-12 11:25 UTC, Situphen commented on assets/js/ajax-actions.js
> +    /* Editor */
Pour moi tout le code qui suit devrait être dans un fichier à part, `editor.js` par exemple.

2019-11-12 11:25 UTC, Situphen commented on assets/js/ajax-actions.js
> +        } else {
Je pense qu'il serait plus clair d'avoir ceci : 

```js
if (typeof beforeChars !== 'undefined' && typeof afterChars !== 'undefined' && beforeChars && afterChars) {
    if(checkMatch(...) && checkMatch(...)) {
        ...
    }
    else if(...) {
        ...
    }
}
```

D'ailleurs j'ai l'impression que les `typeof` ne sont pas nécessaires dans la première condition et que `if (beforeChars && afterChars)` suffirait.

2019-11-12 11:25 UTC, Situphen commented on assets/js/ajax-actions.js
> +                if(_titleContents[0].trim() === "i" || _titleContents[0].trim() === "information") {
un petit `var _type = _titleContents[0].trim()` rendrait la lecture des `if` et `else if` plus simple.

2019-11-12 11:25 UTC, Situphen commented on assets/js/ajax-actions.js
> +                } else {
Une condition ici serait bienvenue car un bloc neutre doit commencer par `neutre|` ou `n|` : 

```
[[neutre| Mon superbe titre]]
| Truc super cool
```

2019-11-12 11:25 UTC, Situphen commented on assets/scss/components/_editor.scss
> +            border-bottom: 0px;
Remplacer par `border: 0;`

2019-11-12 11:25 UTC, Situphen commented on assets/scss/components/_editor.scss
> +                padding-top: 0px;
Remplacer par `padding: 0;`

2019-11-12 12:38 UTC, A-312 commented
> On n'a plus de bouton "ajouter un smiley/emoji"

Toute façon avec nos ~90 emotes, le menu va devenir outdated.

-----

Pour ton menu full-css, le HTML doit ressembler à :

```html
<li><a>Menu</a>
<ul>
<li>Warning</li>
<li>...</li>
</li>
```

2019-11-12 12:40 UTC, artragis commented on assets/js/ajax-actions.js
> +                if(_titleContents[0].trim() === "i" || _titleContents[0].trim() === "information") {
d'ailleurs globalement on est sensé préférer `let` non?

2019-11-12 12:45 UTC, A-312 commented on assets/js/ajax-actions.js
> +                if(_titleContents[0].trim() === "i" || _titleContents[0].trim() === "information") {
const si la valeur ne change jamais

2019-11-12 14:36 UTC, firm1 commented
Merci @Situphen pour la review. Je vais tacher de prendre en compte tes remarques.

@A-312 : je n'ai malheureusement pas la main sur la production du html de la barre d'outil (ça serait trop facile sinon). Il faut avoir jouer avec la contrainte du html que produit la dépendance easymde (je n'ai pas envie de devoir le forker juste pour ça).

2019-11-12 16:53 UTC, A-312 commented on assets/js/ajax-actions.js
> +        } else {
+1 `if (beforeChars && afterChars)`

2019-11-12 17:53 UTC, Situphen commented on assets/js/ajax-actions.js
> +            if (typeof found !== "undefined") {
Inutile car déjà pris en compte avec le `if(found)`. En fait `undefined` c'est un peu comme `None` en Python.

2019-11-12 17:57 UTC, A-312 commented
J'ai vu ces points qui m'ont interpellé : 

 - [ ] Bug de l'astuce (affichage pas terrible, il manque la croix pour la fermer)
 - [ ] Ajouter une mention des raccourcis dans le tuto : https://github.com/Ionaru/easy-markdown-editor#keyboard-shortcuts
 - [ ] Le rendu de l'éditeur : On laisse le background blanc ? Ou on essaye de s'approcher un peu plus de la "réalité"/"prévisualisation" ?
 - [ ] "Auto-saved" en anglais
 - [ ] "[[n|titre]]" plutôt "[[neutre|titre]]" ?
 - [ ] Le bouton plein écran ne revient pas à la position du bloc d'édition (Le plus souvent un `scrollTop: $("#elementtoScrollToID").offset().top` suffit).
 - [ ] Bug bouton liste à puce (mauvais md)

Détails (non important) : 
  - Les icones ne sont pas à mon goût mais c'est un détail
    - icone codeinline non approprié
    - icone abréviation non approprié
    - icone math non approprié
    - icone key non approprié : Le clavier est à moitié parlant (-> voir pour une touche de clavier)
    - [ ] Les liens c'est le seul en bleu/couleur (ça me stress, on peut le corriger pour la v1 ?)

Q/A du rendu md dans le markdown pour chaque bouton (**surement pour la v2 ?**) :

| bouton | commentaire |
| - | - |
| bold | ok |
| italic | ok |
| barré | ok |
| abrev | plus d'espace entre le texte et l'abrev quand c'est le premier ? |
| touche | on ne peut pas l'encadrer ? (ajouter une bordure ? ou juste modifier la couleur ? comme le vrai)<br>![image](https://user-images.githubusercontent.com/18501150/68695890-27cc3780-057c-11ea-879e-6aef64790f94.png) |
| codeinline | idem que pour "touche" |
| exposant/indice | pas de rendu |
| center/left | pas de rendu |
| liste à puce | **BUG à corriger pour la v1** n'ajoute pas le bon md |
| liste ordonné | **C'est génial quand on appuie sur entrée !** un petit margin-left sur la liste ? |
| titre | Il faudrait qu'il soit au couleur de ceux du zds |
| citation | Absence de style :( (idem que "touche" |
| code | Même police, il faudrait peut-être alterner ? |
| Table | Ajouter un easter eggs ? |
| info/warning/erreur/question | Mettre leurs couleurs correspondantes ? |


Exemple d'easter eggs : (je sais ce n'est pas poussé) 
```
| Type | Site | Mascotte |
| -------- | -------- | -------- |
| Assoc | Zds | Clem |
```

2019-11-12 22:08 UTC, A-312 commented
Pour le dropdown, le mieux serait de faire une PR dans le repos de la lib : https://github.com/Ionaru/easy-markdown-editor/issues/129 . Normalement ce n'est pas trop compliqué, c'est juste une histoire d'ajouter un scopage à la boucle existante pour autoriser un sub-menu.

2019-11-12 23:28 UTC, firm1 commented
> Pour le dropdown, le mieux serait de faire une PR dans le repos de la lib : Ionaru/easy-markdown-editor#129 . Normalement ce n'est pas trop compliqué, c'est juste une histoire d'ajouter un scopage à la boucle existante pour autoriser un sub-menu.

Dans ce cas, ça passera dans la v2.

2019-11-12 23:48 UTC, firm1 commented
@A-312 j'ai normalement pris les remarques sauf : 

> Ajouter une mention des raccourcis dans le tuto : https://github.com/Ionaru/easy-markdown-editor#keyboard-shortcuts

On n'a pas la main dessus dans le code, c'est à faire sur le site (c'est à dire quand la PR sera mergé et déployée).

> Le rendu de l'éditeur : On laisse le background blanc ? Ou on essaye de s'approcher un peu plus de la "réalité"/"prévisualisation" ?

Pas compris cette phrase. c'est quoi pour toi "s'approcher de la réalité ?", car pour le moment en prod, il y'a deux couleurs 
- gris dans la prévisualisation du texte et le même gris a l'affichage dans un tutoriel
- gris dans la prévisualisation du texte sur le forum, et gris clair dans son affichage sur les forums.

D'ailleurs je ne vois pas de quel background "blanc" tu parles. Tu peux me préciser ou tu le vois ?

> "Auto-saved" en anglais

C'est code en dur dans la lib mère, je ne peut pas agir dessus directement. ça passera donc dans la v2 je pense.

> Le bouton plein écran ne revient pas à la position du bloc d'édition (Le plus souvent un scrollTop: $("#elementtoScrollToID").offset().top suffit).

Je n'ai pas la moindre idée de où coller ça.

2019-11-13 06:14 UTC, A-312 commented
Pour les points en v2 ça me va :
 - dropdown
 - autosaved
 - scrollTo

> Pas compris cette phrase. c'est quoi pour toi "s'approcher de la réalité ?"

Je parle de l'éditeur (a gauche) : le fond blanc + la police d'écriture

2019-11-13 08:15 UTC, firm1 commented
> Je parle de l'éditeur (a gauche) : le fond blanc + la police d'écriture

Perso ça ne me choque pas. D'autant plus qu'on a déjà du blanc en prod aujourd'hui.

Le thème codemirror qu''on utilise (idea) se base aussi sur le fait d'avoir un fond blanc. J'aimerai eviter au maximum de diverger si c'est pas necessaire.

2019-11-13 08:49 UTC, A-312 commented
Pour ce qui est de la police ? On reste en monospace ?

2019-11-13 08:59 UTC, artragis commented
@A-312 pour le coup tes questions sont excellentes mais j'aimerais qu'on reste sur un MVP. 

Du coup oui on va rester en monospace, MAIS, garde sur le coude l'ensemble de tes questions et envoie-les par MP et une fois que la fonctionnalité sera en prod, on demandera aux utilisateurs si pour eux ça serait mieux autrement.

2019-11-13 17:46 UTC, firm1 commented
Ceci étant, @A-312 tu penses que tu peux lancer une QA dessus ?

2019-11-13 18:13 UTC, A-312 reviewed
Tout me semble bien à part le md-help (absence de croix) et l'abbreviation

Pour le markdown help il n'y a toujours pas l'option de masquer. Tu as un exemple de comment faire : 

https://github.com/A-312/zds-site/blob/a124f91807e6fa4d3fc703eb849677830df62866/assets/js/editor.js#L688-L691

il suffit d'ajouter une class "altert-box" au HTML et d'ajouter le même bouton/lien cacher que le code ci-dessus et voila!

2019-11-13 18:13 UTC, A-312 commented on assets/js/editor.js
> +                            e.codemirror.replaceSelection("\n*["+abbr+"]: "+description);
Comportement étrange quand j'en rajoute deux de suite : 

![image](https://user-images.githubusercontent.com/18501150/68791111-eeadc900-0648-11ea-8b2d-cc05663adeba.png)

2019-11-13 22:25 UTC, firm1 commented
Voilà, j'ai corrigé tes deux derniers points @A-312 . A mon avis on est bon là.

2019-11-18 20:18 UTC, A-312 commented
~~La croix n'est pas centré~~

Certain point sont perfectible mais la PR est prête pour une v1.

Note : L'historique est partout le même que ça soit en MP, tuto ou sur forum. (Contrairement à ce qu'on a actuellement).

2019-11-18 20:19 UTC, A-312 submitted a review, later dismissed
~~La croix n'est pas centré~~

Certain point sont perfectible mais la PR est prête pour une v1.

Note : L'historique est partout le même que ça soit en MP, tuto ou sur forum. (Contrairement à ce qu'on a actuellement).

2019-11-18 20:27 UTC, Situphen commented on assets/js/editor.js
> +                    uniqueId: this.id+currentLocation[currentLocation.length - 1],
Je suggère d'essayer ça :

```suggestion
                    uniqueId: window.location.pathname + "@" + this.getAttribute("name"),
```

Je me suis inspiré de [`assets/js/editor-persistence.js`](https://github.com/zestedesavoir/zds-site/blob/dev/assets/js/editor-persistence.js#L51-L52) qui fonctionne bien.

2019-11-18 20:30 UTC, A-312 requested changes

2019-11-18 20:30 UTC, A-312 commented on assets/js/editor.js
> +        var currentLocation = document.location.href.split("/");
Ce n'est pas mieux `document.location.pathname` pour éviter le hashtag ?

2019-11-18 20:43 UTC, Situphen commented on assets/js/editor.js
> +                    uniqueId: this.id+currentLocation[currentLocation.length - 1],
Je confirme, ma proposition fonctionne correctement ! Bon par contre EasyMDE crée une entrée `localStorage` par éditeur, même si celui-ci est vide ; notre truc maison était plus optimisé :D

2019-11-18 20:48 UTC, A-312 commented on assets/js/editor.js
> +                    uniqueId: this.id+currentLocation[currentLocation.length - 1],
Au pire il suffit de clean les clés EasyMDE vide.

2019-11-18 21:04 UTC, firm1 commented
L'unicité vient d'être corrigé. @A-312 ça résous le problème de ton coté ?

2019-11-20 21:33 UTC, A-312 commented on assets/js/migration-to-easymde.js
> +        console.log(entries[n]);
Tu as laissé le printlog

2019-11-21 18:22 UTC, A-312 requested changes
Le script de Situphen ne fonctionne pas pour la page active (qui est chargé en premier) lors de la migration c'est-à-dire que la page courante perd son historique à cause d'un problème de priorité du script.

```diff
diff --git a/assets/js/editor.js b/assets/js/editor.js
index 99928c951..464d2b801 100644
--- a/assets/js/editor.js
+++ b/assets/js/editor.js
@@ -1,6 +1,18 @@
 (function($, undefined){
     "use strict";
 
+    (function(){
+        /**
+        * Migration easymde
+        */
+        let source = localStorage.getItem("savedEditorText");
+        let entries = source ? JSON.parse(source) : [];
+        for (let n in entries) {
+            localStorage.setItem("smde_" + entries[n].id, entries[n].value);
+        }
+        localStorage.removeItem("savedEditorText");
+    })();
+
     /**
     * Preview the message on bottom
     */
diff --git a/assets/js/migration-to-easymde.js b/assets/js/migration-to-easymde.js
deleted file mode 100644
index 7a0b5ca02..000000000
--- a/assets/js/migration-to-easymde.js
+++ /dev/null
@@ -1,10 +0,0 @@
-(function(){
-    "use strict";
-
-    let source = localStorage.getItem("savedEditorText");
-    let entries = source ? JSON.parse(source) : [];
-    for (let n in entries) {
-        localStorage.setItem("smde_" + entries[n].id, entries[n].value);
-    }
-    localStorage.removeItem("savedEditorText");
-})();
```

2019-11-21 19:23 UTC, firm1 commented
Merci @A-312 .

Qui veut appuyer sur le bouton magique ?

2019-11-21 19:25 UTC, Situphen commented
Je laisse l'honneur à @A-312 étant donné qu'il a fait la QA ! Une fois que Travis aura fini.

2019-11-22 06:20 UTC, merged