Légendes des images illimitées (fix #2742)
zestedesavoir/zds-site pull request #5527
Opened 2019-11-22 12:54 UTC by jeanlapostolle

La légende passe d'un Charfield de 80 caractères à un Textfield illimités en nombre de caractères.
Numéro du ticket concerné : #2742

### Contrôle qualité
  - Lancez `python manage.py migrate`
  - Ajouter une image dans une gallerie et vérifiez qu'on peut mettre plus de 80 caractères en légende.

2019-11-28 12:23 UTC, artragis requested changes

2019-11-28 12:23 UTC, artragis commented on zds/gallery/models.py
> +    legend = models.TextField(_('Légende'), null=True, blank=True)
Cöté test, ça passe.

par contre ça serait bien de réduire la taille de la textarea qui est générée. Ainsi il faut intervenir au niveau de `ImageForm` pour lui ajouter le paramètre `rows = 2` lorsqu'on ajoute le champ `legend` au layout du form.

2020-01-25 11:50 UTC, artragis commented
ping @jeanlapostolle

2020-01-25 15:35 UTC, A-312 commented on zds/gallery/models.py
> +    legend = models.TextField(_('Légende'), null=True, blank=True)
Si on modifie en textarea, on ne devrait pas commencer à utiliser : `Figure:` ? Pour essayer de supporter les retours à la ligne ? (Et de remplacer un double saut à la ligne par un simple ?)

![image](https://user-images.githubusercontent.com/18501150/73123471-9e2fe180-3f90-11ea-8218-12053987abb4.png)

2020-01-25 17:58 UTC, artragis commented on zds/gallery/models.py
> +    legend = models.TextField(_('Légende'), null=True, blank=True)
Non.

2020-01-25 17:59 UTC, artragis commented on zds/gallery/models.py
> +    legend = models.TextField(_('Légende'), null=True, blank=True)
NOn, mais la question est pertinente. En fait il ne faut même pas un textarea mais un field à l'ancienne sans limite.

2020-04-10 19:15 UTC, artragis commented
ping @jeanlapostolle  tu penses pouvoir reprendre ou tu préfères que je finisse ça?

2020-04-10 20:40 UTC, jeanlapostolle commented
Si il y a besoin que ça soit fait rapidement, il vaut mieux que tu reprennes oui.

2020-04-20 15:25 UTC, artragis commented
DU coup j'ai repris ton commit et j'ai fait la modif. Merci pour ta participation :)

2020-04-20 15:25 UTC, closed without merging