Ajout des suggestions aux contenus
zestedesavoir/zds-site pull request #5542
Opened 2019-12-03 21:15 UTC by firm1

Numéro du ticket concerné (optionnel) : #5526

Le but de cette PR est d'ajouter la possibilité pour les membres du staff d'associer un contenu du site à un autre en tant que suggestion. L'objectif étant que le lecteur, lorsqu'il va sur une publication, voit des contenus suggérés par les membres du staff qui pourraient l’intéresser.

### Le workflow

#### Du point de vue du staff

En tant que staff, je vais sur un tutoriel ou article et dans la *sidebar*, j'ai ces boutons (Ajouter une suggestion et gérer une suggestion).

![Capture d’écran de 2019-12-03 22-09-47](https://user-images.githubusercontent.com/6066015/70090116-d0206980-1619-11ea-91a0-13ba2e99b2c0.png)

Si je clique sur ajouter une suggestion, j'ai une modale qui s'ouvre et me demande de faire une recherche.

![Capture d’écran de 2019-12-03 22-10-23](https://user-images.githubusercontent.com/6066015/70090194-fc3bea80-1619-11ea-9d49-b2c98c9a8b5c.png)

Quand je cliquer sur ajouter, la suggestion est ajoutée

Si je clique dans la sidebar sur "gérer les suggestions", j'ai accès à la liste des suggestions que je peux supprimer

![Capture d’écran de 2019-12-03 22-10-39](https://user-images.githubusercontent.com/6066015/70090205-0231cb80-161a-11ea-8945-c41b9a8ee5a2.png)

#### Du point de vue du lecteur

Lorsque je consulte la version publiée du contenu, à la fin du contenu (avant les commentaires), on trouve 2 suggestions prise au hasard dans la liste des suggestions proposés par le staff.

![Capture d’écran de 2019-12-03 22-14-09](https://user-images.githubusercontent.com/6066015/70090346-43c27680-161a-11ea-9425-2810c4414784.png)

### Contrôle qualité

Vous devez avoir installé au moins le front (`make install-front`), le back (`make install-back`) et la partie elasticsearch (`./scripts/install_zds.sh +elastic-local`).

- Buildez le front (`make build-front`)
- Assurez vous d'avoir généré les fixtures (`make generate-fixtures`)
- Démarrez elasticsearch (`make run-elasticsearch`)
- Indexez les contenus dans elasticsearch (`make index-all`)
- Allez dans un article ou tutoriel (dans sa version brouillon) en tant que staff et constatez que dans la sidebar vous pouvez ajouter un contenu en tant que suggestion
- Allez dans les billets et vérifiez que vous ne pouvez pas (même en tant que staff) ajouter de suggestion de contenu a un billet

N'hésitez pas à tester des choses comme : 

- on ne peut pas ajouter deux fois la même suggestion
- on ne peut pas ajouter de billets non mis en avant par le staff en tant que suggestion à un tutoriel ou article

2019-12-14 14:50 UTC, artragis commented
- il faut être sur la version brouillon pour ajouter une éditorialisation, c'est dommage, ça va ralentir le travail des valido/membres de l'équipe de com'

J'ai été sur mon tutoriel "site web avec asp.net

j'ai lancé la recherche "asp"

on m'a proposé mon tutoriel

j'ai ajouté mon tutoriel

j'ai validé

j'ai eu aucun avertissement mais en vérité comme on ne peut pas lier un tuto à lui-même ça n'a pas eu d'effet.

ça serait bien si on avait un message d'avertissement dans ce cas.

2019-12-14 17:37 UTC, artragis commented
# Ajout de plusieurs fois le même tuto 

## test 1

- entrer PHP
- sélectionner "les filtres en php" et valider
- revenir dans la fenêtre
- ajouter "les filtres en php" et valider
- un message nous apprend que c'est déjà ajouté => OK

## test 2
- entrer PHP
- ajouter le tuto sur doctrine 2
- entrer php, ajouter le tuto sur doctrine 2
- entrer PHP ajouter un autre tuto, peu importe lequel
- valider
![image](https://user-images.githubusercontent.com/1523653/70852344-a9c3bf00-1ea0-11ea-96ae-a5347aa68e49.png)

je dirais que c'est ok pour une première version mais ça serait bien qu'on ne puisse pas mettre deux fois la même chose dans le même wizzard

2020-01-02 20:11 UTC, artragis requested changes

2020-01-02 20:11 UTC, artragis commented on assets/js/autocompletion.js
> +                     //jsonData = this.fetchData(search, "");
je sais pas si le linter te le dira mais faut pas laisser de code commenté

2020-01-02 20:11 UTC, artragis commented on zds/searchv2/views.py
> +        """Overridden because the index manager must NOT be initialized elsewhere."""
merci de l'avoir noté :)

2020-01-02 20:45 UTC, firm1 commented
Voilà, j'ai pris en compte toutes tes remarques @artragis ça a pris plus de temps que prévu, désolé.

2020-01-03 12:17 UTC, artragis commented
ça me semble bien mieux j'ai plus qu'à tester le cas de l'impossibilité d'ajouter un billet non choisi.

2020-01-06 09:58 UTC, firm1 commented
Des nouvelles ? Il me semble que c'est PR est la dernière bloquante pour la v29.

2020-01-06 12:49 UTC, artragis commented
je valide tout ce soir

2020-01-07 11:06 UTC, artragis commented
OK

2020-01-07 11:06 UTC, merged