Oubli de fire l'erreur avec Travis pour selenium
zestedesavoir/zds-site pull request #5553
Opened 2019-12-31 00:14 UTC by A-312

Un effroyable oubli dans ma dernière PR ! #5348

2019-12-31 02:00 UTC, A-312 commented
> selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: (693, 628) is out of bounds of viewport width (1152) and height (574)

😕

2020-01-02 12:16 UTC, artragis requested changes
Ta PR est bonne, tu te prends juste un bug de geckodriver il existe [un workarround](https://stackoverflow.com/a/52045231/1242324) et je t'ai donné les endroits où il faut le mettre.

2020-01-02 12:16 UTC, artragis commented on zds/tutorialv2/tests/tests_front.py
> +        action_chains.click(intro).perform()
il faut faire un `move_to_element` avant le click ici : 
`action_chains.move_to_element(intro).click().send_keys('intro').perform()`

ceci dit firefox semble avoir un [bug supplémentaire](https://stackoverflow.com/a/52045231/1242324) le mieux serait donc de faire une petite fonction utilitaire qui va te permettre de scroller où il faut.

2020-01-02 12:16 UTC, artragis commented on zds/tutorialv2/tests/tests_front.py
> +        action_chains.click(intro).perform()
de même ici : 
`action_chains.move_to_element(intro).click().send_keys('Le cadavre exquis boira le vin nouveau.').perform()`

2020-01-02 12:55 UTC, A-312 commented on zds/tutorialv2/tests/tests_front.py
> +        action_chains.click(intro).perform()
fonction utilitaire ? J'insère du JS pour scroll?

2020-01-02 12:59 UTC, artragis commented on zds/tutorialv2/tests/tests_front.py
> +        action_chains.click(intro).perform()
en gros il faut faire cette méthode : 
```python
def scroll_shim(passed_in_driver, object):
        x = object.location['x']
        y = object.location['y']
        scroll_by_coord = 'window.scrollTo(%s,%s);' % (
            x,
            y
        )
        scroll_nav_out_of_way = 'window.scrollBy(0, -120);'
        passed_in_driver.execute_script(scroll_by_coord)
        passed_in_driver.execute_script(scroll_nav_out_of_way)
```

avec des meilleurs noms de variable et ensuite l'appeler comme il faut. En somme une fonction utilitaire qui te permet de faire le taf d'appeler le js qui va bien.

2020-01-04 00:47 UTC, A-312 commented on zds/tutorialv2/tests/tests_front.py
> +        action_chains.click(intro).perform()
Fait merci ! :D

2020-01-04 08:44 UTC, artragis approved these changes

2020-01-04 08:44 UTC, merged