improvement/avoid-multipost-when-updating-a-tutorial: Éviter de créer des messages automatiques en doublon avec un message manuel lors de la mise à jour d'une bêta de tutoriel, en appliquant correctement la limite de 15 minutes entre deux messages
zestedesavoir/zds-site pull request #5568
Opened 2020-01-09 14:35 UTC by marin-m

Bonjour,

Lorsque la bêta de tutoriel est mise à jour, un message automatique est posté sur le sujet.

Ce message n'est pas supprimable. Il contourne également la limite de 15 minutes entre deus messages.

* Si l'auteur choisir de mettre à jour la bêta, puis de poster un message pour expliquer ses changements, il va naturellement avoir la possibilité de modifier le message automatique pour le faire (étant donné la limite de 15 minutes qui l'y contrait).

* Si cependant il choisir de poster un message pour expliquer ses changements, puis de mettre à jour la bêta (il a le droit aussi), alors il va se retrouver avec deux messages, dont un automatique,  sur son sujet, sans que ce ne soit particulièrement utile à lui ou au lecteur. En effet, actuellement, la [limite](https://github.com/zestedesavoir/zds-site/blob/76ef17d/zds/forum/models.py#L386) de 15 minutes entre deux réponses à un même sujet ne s'applique pas correctement.

Cette pull request se contente de modifier ce dernier point sur ce dernier cas : la limite sera appliqué correctement lors de la création d'un nouveau message de réponse automatique.

## Contrôle qualité

Les étapes suivantes peuvent être effectuées pour vérifier le bon fonctionnement de cette pull request :

* Créer un tutoriel.
* Mettre le tutoriel en bêta.
* Répondre au sujet concerné avec le même compte.
* Moins de 15 minutes après, mettre à jour la bêta du tutorie.

Cordialement,

2020-01-09 18:05 UTC, artragis commented
Salut et bienvenu à toi parmi les dev de zds.

j'attends avec impatience que tu considères que ta PR n'est plus en brouillon car je pense que cette fonctionnalité sera très utile au site, pas mal de personne se plaignant qu'il y a trop de messages sur la béta.

2020-01-09 18:34 UTC, marin-m commented
Salut,

Merci pour ton accueil. J'ai enlevé ma PR de l'état brouillon, je l'y avais mise en attendant que la CI passe. Pour l'instant c'est surtout une modification « transitoire », plus un bug fix qu'autre chose (mais qui améliorera la situation).

À mon avis, l'optimal serait : 
- Une case à cocher pour choisir, ou non, l'émission d'un message ou d'un nouveau topic lors d'une modification liée à une bêta (à ajouter dans la modale actuelle).
- Voire même une option de profil ou de tutoriel.
- L'idéal en plus serait de pouvoir supprimer ses messages (sur la plupart des forums, notamment basés sur des logiciels comme SMF, il y en a et étant une personne qui a fréquenté beaucoup les forums, je préfère largement les sites qui proposent de pouvoir supprimer ses messages à ceux que ni le proposent pas. Il y a plein de raisons qui peuvent vouloir mener à supprimer ses messages dans la pratique.).

Merci et bonne soirée !

2020-01-12 10:40 UTC, artragis requested changes
La feature fonctionne.

Il ne reste plus que le petit changement à faire sur le commentaire et ça sera impec :)

2020-01-12 10:40 UTC, artragis commented on zds/tutorialv2/views/contents.py
> +                # Si l'anti-spam se déclenche (l'auteur a posté lui-même un
les commentaires doivent être en anglais.

2020-01-12 18:38 UTC, marin-m commented on zds/tutorialv2/views/contents.py
> +                # Si l'anti-spam se déclenche (l'auteur a posté lui-même un
@artragis Voilà, et j'ai traduit le message du premier commit commit aussi.

2020-01-12 20:06 UTC, merged

2020-01-12 20:07 UTC, artragis commented
Eh voilà. Merci pour ta contribution !