Support complet du drag'n'drop
zestedesavoir/zds-site pull request #5572
Opened 2020-01-13 17:50 UTC by A-312

Vu que le back n'était pas prêt quand j'ai codé le front, ceci a dissimulé certaine incompatibilité (dont une importante) : Impossible de déplacer des sections dans une partie qui a contenue des chapitres.

2020-01-13 17:52 UTC, artragis commented
ne passe plus par la branche ici. reprends tout chez toi à partir de dev ça évitera les problèmes de merge/conflits/rebase

2020-01-13 20:11 UTC, artragis requested changes

2020-01-13 20:11 UTC, artragis commented on templates/tutorialv2/includes/child_online.part.html
> +                    <h3>
pas bon ça de perdre les listes. Il nous faut du ol/li

2020-01-13 21:43 UTC, A-312 commented on templates/tutorialv2/includes/child_online.part.html
> +                    <h3>
même quand c'est uniquement pour l'édition ? (je n'ai pas touché à la version publié)

2020-01-13 21:55 UTC, A-312 commented on templates/tutorialv2/includes/child_online.part.html
> +                    <h3>
Je vais tout mettre en ol, ça m'arrange. :D

2020-01-26 21:36 UTC, A-312 commented
- [ ] Demain (pas ce soir), je dois corriger le problème de dragging un peu *relou*, il me semble que c'est simplement une question de css (margin et padding))
 - [ ] Je dois aussi mettre à jour les liens des boutons

2020-05-01 09:11 UTC, A-312 commented
@artragis j'ai besoin d'aide : Quand on est sur un big tuto, quand je déplace une partie dans une partie vide ça ne prend pas en compte le déplacement : 

![image](https://user-images.githubusercontent.com/18501150/80795221-2cbd8b80-8b9c-11ea-9cdf-1cc444b753e7.png)

1. Je déplace
2. Je F5
3. Je constate que la partie n'a pas était déplacé (pourtant j'ai un code 200)

![demo dnd](https://user-images.githubusercontent.com/18501150/80795281-57a7df80-8b9c-11ea-8ba6-00c61a03fe4d.gif)

2020-05-02 16:07 UTC, A-312 commented
- [ ] Vérifier que les liens sont bien mise à jour.

2020-05-02 16:19 UTC, artragis commented on zds/tutorialv2/views/contents.py
> +                if not parent.has_child_with_path(target):
ok c'est là que ça marche pas. tu peux essayer de mettre : 

```python
                if '/' not in target:
                    target_parent = versioned
                else:
                    target_parent = search_container_or_404(versioned, '/'.join(target.split('/')[:-1]))*
                 if not target_parent .has_child_with_path(target):
                     try_adopt_new_child(target_parent, child)
                     # la suite

2020-05-02 16:34 UTC, A-312 commented
- Voir si le bug du sommaire (dans la sidebar) du contenu en cours de validation est lié à cette PR

2020-05-02 16:49 UTC, A-312 commented on zds/tutorialv2/views/contents.py
> +                if not parent.has_child_with_path(target):
Merci :D

2020-05-08 15:18 UTC, A-312 commented
Si quelqu'un souhaite prendre la suite, sachez que le plus dure est fait. Il faut juste actualiser les liens des titres des sections/chapitres/parties quand vous déplacez une partie, ça se passe vers ici :  https://github.com/zestedesavoir/zds-site/pull/5572/files#diff-b0b1ccb3166fc9d5d1d5310076c69634R86

2021-02-28 19:39 UTC, Situphen commented
Vu en réunion, je ferme.

2021-02-28 19:39 UTC, closed without merging