Changement : clarification des messages de promotion en article (#5675)
zestedesavoir/zds-site pull request #5678
Opened 2020-04-05 08:09 UTC by Arnaud-D

Petite clarification des messages pour la promotion en article.

Fix #5675.

## QA

En tant que staff,

- ouvrir un billet ;
- trouver le bouton « Proposer comme article » et cliquer dessus ;
- vérifier la cohérence du dialogue et l'absence de fautes d'orthographe ;
- cliquer sur « Confirmer » et vérifier la cohérence du bandeau de confirmation.

En tant qu'auteur de l'article promu :

- vérifier la réception du MP de notification ;
- vérifier la cohérence de ce MP avec le reste.

2020-04-05 08:27 UTC, A-312 commented
Je ne suis pas sûr que le bouton soit plus claire :/ `Créer un article`, `Dupliquer en article` ? (Je ne pense pas avoir mieux)

Mais ce passage explicite bien l'action en cours : https://github.com/zestedesavoir/zds-site/pull/5678/commits/0cd14bfa85298fb9b2ad9fdfaf172bf32a3da426#diff-eb19aab06dd17de7178922cad32beabbR1326-R1328

2020-04-05 09:40 UTC, A-312 requested changes

2020-04-05 09:40 UTC, A-312 commented on zds/tutorialv2/views/validations.py
> +                                         "et est en attente de validation."))
Tu dois mettre des apostrophes simples

2020-04-05 09:40 UTC, A-312 commented on zds/tutorialv2/forms.py
> +                 "puis créera une demande de validation pour ce dernier.</p>"),
Apostrophe simple ;)

2020-04-05 11:45 UTC, A-312 submitted a review, later dismissed

2020-04-10 15:02 UTC, firm1 commented
### Rapport de QA

QA OK

2020-04-10 15:02 UTC, merged