permet a travis de tester la generation des fixtures
zestedesavoir/zds-site pull request #5688
Opened 2020-04-08 12:43 UTC by firm1

Cette PR permet d'activer les tests de génération de fixtures dans travis, ce qui permet de reproduire le bug qu'il y a en ce moment sur la branche de dev.

Une fois que travis aura prouvé que l'erreur est existante par un build, cette PR servira aussi de branche de correction de ce bug pour pouvoir merger la solution.

### Contrôle qualité

Travis est suffisant pour valider cette PR.

2020-04-08 12:49 UTC, A-312 commented
A la fin, il faudra surement que tu fusionnes ton nouveau job, avec un job existant car la limite de job parallèle est de 5. (Avec 6 jobs, on rallonge de beaucoup le temps d’exécution de travis).

2020-04-08 12:53 UTC, A-312 commented on .travis.yml
>        env: ZDS_TEST_JOB="front fixture selenium"
Pour bosser (le temps que ta PR soit en draft) je te conseillerai de supprimer les autres jobs, au lieu de les lancer à chaque fois, tu gagneras du temps entre chaque test. ;)

2020-04-08 12:56 UTC, A-312 commented
Et je ne comprends pas trop l'intérêt vu qu'on le fait déjà là : https://github.com/zestedesavoir/zds-site/blob/8e1b83e600cdf3f9fe73c7d8dde937642c6ddc57/scripts/install_zds.sh#L558

(Je suppose que pour l'instant ce n'est que du debug ?)

2020-04-08 12:58 UTC, A-312 commented on scripts/travis_script.sh
> +    if [[ "$ZDS_TEST_JOB" == "fixture" ]] || [[ "$ZDS_TEST_JOB" == *"zds."* ]]; then
Ou sinon : `ZDS_TEST_JOB="zds.fixture"` 😝 (Fait attention car `fixture` est utilisé aussi par le job 4 et n'a pas besoin d'un nouveau makemigrations).

2020-04-08 18:23 UTC, A-312 commented on scripts/install_zds.sh
> +        exit 1
[Je suis con sur ce coup là](https://github.com/zestedesavoir/zds-site/commit/c90e2b5f80e100535b296da73adfff1082aec4db). J'ai complètement zappé que sans code erreur travis n'allait pas planter -.-" Tu peux rajouter un commentaire : `# Throw error for travis` ?

2020-04-09 14:11 UTC, firm1 commented
Voilà, le problème est corrigé.

- 1 [commit](https://github.com/zestedesavoir/zds-site/pull/5688/commits/ae40e12aa47a4ad86b839e9482104bc3dcdbb3e9) qui démontre l'[erreur](https://github.com/zestedesavoir/zds-site/runs/574025067)
- 1 [commit](https://github.com/zestedesavoir/zds-site/pull/5688/commits/089c2f0e6e7ee391e832ea796760f8615cb9f7f1) qui [corrige](https://github.com/zestedesavoir/zds-site/runs/574092037) l'erreur

2020-04-09 14:30 UTC, A-312 requested changes

2020-04-09 14:30 UTC, A-312 commented on scripts/install_zds.sh
> +        settingsParams="--settings=zds.settings.ci_test"
Il ne faut pas remettre `zds.settings.travis_fixture` ? (travis n'aime pas nos log trop long)

2020-04-09 14:30 UTC, A-312 commented on scripts/install_zds.sh
> +    print_info "run fixtures on '${settingsParams}' params"
Dans certain cas `settingsParams` est vide, est-ce normal ?

2020-04-09 14:30 UTC, A-312 commented on scripts/install_zds.sh
> +        python manage.py migrate ${settingsParams}; exVal=$?
Pourquoi tu remigrates une deuxième fois ?

Si tu tiens à cet ligne, il faut rajouter un `zds_register_for_install "-back-migrate-db"` dans travis_header.sh, pour ne pas faire le migrate lors de l'installation du back

Parce que là, on fait 3 migrates dans le même job, à l'installation du back, ici, avant de lancer selenium.

2020-04-09 14:33 UTC, A-312 commented on scripts/install_zds.sh
> +        python manage.py migrate ${settingsParams}; exVal=$?
Tu pourrais modifier ce passage :
```
        if ! ( [[ "$ZDS_TEST_JOB" == *"zds."* ]] || \
               [[ "$ZDS_TEST_JOB" == *"selenium"* ]]); then
            print_info "* Don't migrate-db, if only doc are registered."
            zds_register_for_install "-back-migrate-db"
        fi
``` 

En : 

```
        if ! ( [[ "$ZDS_TEST_JOB" == *"zds."* ]] || \
               [[ "$ZDS_TEST_JOB" == *"fixture"* ]]) || \
               [[ "$ZDS_TEST_JOB" == *"selenium"* ]]); then
            print_info "* Don't migrate-db, if only doc are registered."
            zds_register_for_install "-back-migrate-db"
        fi
```

2020-04-09 14:37 UTC, A-312 commented on scripts/install_zds.sh
> +        python manage.py migrate ${settingsParams}; exVal=$?
Etrange le job 4, ne devrait pas avoir la migration d'active : 
![image](https://user-images.githubusercontent.com/18501150/78906872-33b31b80-7a80-11ea-97d7-a584b766797a.png)

La condition présente ici : https://github.com/zestedesavoir/zds-site/blob/089c2f0e6e7ee391e832ea796760f8615cb9f7f1/scripts/install_zds.sh#L473 devrait empêcher la migration après l'installation du back

2020-04-09 14:39 UTC, Situphen commented
On pourrait se simplifier la vie en déclarant la variable d'environnement `DJANGO_SETTINGS_MODULE` tout au début de `install_zds.sh` : 

```
if $(_in "--travis-output" $@); then
    export DJANGO_SETTINGS_MODULE="zds.settings.travis_fixture"
fi
```

2020-04-09 14:42 UTC, firm1 commented on scripts/install_zds.sh
> +        settingsParams="--settings=zds.settings.ci_test"
bien vu, j'ai oublié de repasser dessus après debug

2020-04-09 14:43 UTC, firm1 commented on scripts/install_zds.sh
> +    print_info "run fixtures on '${settingsParams}' params"
Yep ça dois rester vide quand on install en mode sqlite.

2020-04-09 14:45 UTC, firm1 commented on scripts/install_zds.sh
> +        python manage.py migrate ${settingsParams}; exVal=$?
je n'ai pas trop creusé, mais dans le cas du job 5, les précédents migrate ne se font pas. Si j'enlève cette ligne j'ai un message comme quoi les tables n'existent pas (preuve que le migrate n'est pas passé sur mysql)

2020-04-09 14:46 UTC, firm1 commented
> On pourrait se simplifier la vie en déclarant la variable d'environnement DJANGO_SETTINGS_MODULE tout au début de install_zds.sh (voir la documentation) :

Bien vu, je n'avait pas pensé à ça.

2020-04-09 15:05 UTC, merged