Un seul fichier comme README et page de garde de la doc
zestedesavoir/zds-site pull request #5697
Opened 2020-04-11 13:20 UTC by Situphen

Je propose d'avoir un seul fichier pour le README et la page de garde de la documentation. J'ai essayé de rester concis : 

- une petite présentation du projet
- quelques informations pour commencer à contribuer

2020-04-11 13:47 UTC, artragis approved these changes

2020-04-11 13:47 UTC, artragis commented on README.rst
> +N'hésitez pas à discuter avec nous sur `le forum Dev Zone de Zeste de Savoir <https://zestedesavoir.com/forums/communaute/dev-zone/>`__ ou sur le canal ``#zds-dev`` de `notre Discord <https://discord
le canal a changé de nom

2020-04-11 13:59 UTC, Vanadiae requested changes

2020-04-11 13:59 UTC, Vanadiae commented on README.rst
> +-  `latex-template <https://github.com/zestedesavoir/latex-template>`__, notre gabarit LaTeX pour générer des PDFs ;
", utilisé par notre moteur Markdown"

2020-04-11 13:59 UTC, Vanadiae commented on README.rst
> +-  `extensions-notificateurs <https://github.com/zestedesavoir/extensions-notificateurs>`__, notre extension de navigateur pour recevoir des notifications.
"nos" extensions ?

2020-04-11 13:59 UTC, Vanadiae commented on README.rst
> +-  `zmarkdown <https://github.com/zestedesavoir/zmarkdown>`__, notre moteur Markdown ;
```suggestion
-  `zmarkdown <https://github.com/zestedesavoir/zmarkdown>`__, notre moteur Markdown amélioré pour les besoins du site ;
```
Quelque chose comme ça, en précisant peut-être le type d'amélioration par rapport à du markdown lambda ?

2020-04-11 13:59 UTC, Vanadiae commented on README.rst
> +.. |Licence GPL| image:: http://img.shields.io/badge/license-GPL-yellow.svg
```suggestion
.. |Licence GPL| image:: https://www.gnu.org/graphics/gpl-v3-logo.svg
```
Ou le png https://www.gnu.org/graphics/gplv3-with-text-136x68.png (venant de https://www.gnu.org/graphics/license-logos.html)

2020-04-11 13:59 UTC, Situphen commented on README.rst
> +N'hésitez pas à discuter avec nous sur `le forum Dev Zone de Zeste de Savoir <https://zestedesavoir.com/forums/communaute/dev-zone/>`__ ou sur le canal ``#zds-dev`` de `notre Discord <https://discord
En effet, c'est corrigé !

2020-04-11 14:03 UTC, Situphen commented on README.rst
> +.. |Licence GPL| image:: http://img.shields.io/badge/license-GPL-yellow.svg
Je pense que c'est mieux de garder ça sous forme de badge comme actuellement.

2020-04-11 14:08 UTC, Situphen commented on README.rst
> +-  `latex-template <https://github.com/zestedesavoir/latex-template>`__, notre gabarit LaTeX pour générer des PDFs ;
Ce n'est pas utilisé par notre moteur Markdown mais par `zds-site` directement :)

2020-04-11 14:09 UTC, Vanadiae commented on README.rst
> +.. |Licence GPL| image:: http://img.shields.io/badge/license-GPL-yellow.svg
d'accord

2020-04-11 14:59 UTC, A-312 commented
C'est vraiment utile d'avoir le même blabla sur la doc et git ? Je trouvais ça bien d'avoir simplement le sommaire sur la doc

2020-04-11 17:09 UTC, Situphen commented
Mon but c'est d'améliorer la documentation petit bout par petit bout. Actuellement si tu donnes le lien vers la documentation à quelqu'un, tu tombes sur deux petites ligne puis le sommaire. Je trouve bien d'avoir une petite introduction au projet avant d'avoir le sommaire, ça donne une idée du projet. Dans l'idéal, cette documentation devrait être le point d'entrée du projet. "Ah tu t'intéresses au projet technique de ZDS ? Tiens voici le lien vers la doc, tout est dessus !" Actuellement ce dépôt est aussi un point d'entrée, c'est pour ça que je propose que le texte soit le même. Ça évite par ailleurs la duplication de contenu.

2020-04-23 11:57 UTC, Arnaud-D commented on README.rst
> +-  `latex-template <https://github.com/zestedesavoir/latex-template>`__, notre gabarit LaTeX pour générer des PDFs ;
> générer des PDFs

générer des PDF

C'est très secondaire, mais normalement on ne met pas les acronymes au pluriel en français.

2020-04-23 11:58 UTC, Arnaud-D commented
À part ma remarque, c'est pour moi. Il n'y aura plus qu'à rebaser.

2020-04-24 08:18 UTC, Situphen commented
C'est corrigé et rebasé !

2020-04-24 08:31 UTC, merged