Correction du problème de plein écran sur le nouvel éditeur
zestedesavoir/zds-site pull request #5720
Opened 2020-04-16 15:10 UTC by firm1

Cette PR permet de corriger le passage en plein écran sur le nouvel éditeur tel que pointé par le ticket #5692 .

Puisque ce bug est bloquant pour la 29.1, je préfère la solution qui consiste a corriger rapidement chez nous et le correctif un peu plus propre arrivera avec la prochaine version de easymde (du coup pas besoin de leur mettre la pression pour rien).

Numéro du ticket concerné : #5692

### Contrôle qualité

- Démarrer le site
- Pensez à builder le front (sur linux `make build-front`)
- Allez sur une zone de texte (sur un sujet de forum par exemple) cliquez sur le bouton de passage en plein écran
- Vérifiez que la barre d'outil est passée aussi en plein écran que l'on a plus le bug tel qu'on le voit en beta en ce moment (cf. capture ci-dessous)

![](https://user-images.githubusercontent.com/6664636/79016020-4572ec80-7b6e-11ea-8971-ea180bcf9783.png)

2020-04-17 01:13 UTC, ToxicScorpius commented
J'ai fait le QA pour cette PR (je pense) !

2020-04-17 06:48 UTC, A-312 requested changes
Pourquoi ? Alors qu'on a un fix chez easymde ? En plus ça fait double message (un gros bloc) avec l'astuce markdown

2020-04-17 09:55 UTC, firm1 commented
@A-312 
> Pourquoi ?

Comme expliqué dans mon message de PR 

> Puisque ce bug est bloquant pour la 29.1, je préfère la solution qui consiste a corriger rapidement chez nous et le correctif un peu plus propre arrivera avec la prochaine version de easymde (du coup pas besoin de leur mettre la pression pour rien).

---

> En plus ça fait double message (un gros bloc) avec l'astuce markdown

ça ne j'ai pas compris par contre.

2020-04-17 18:10 UTC, Arnaud-D commented
**QA KO** pour moi. Firefox 75 sous Ubuntu 18.04.

## Drôles d'artefacts

C'est pas tellement bloquant, mais j'ai de drôles d'artefacts à la frontière entre les deux zones. C'est aussi présent sur la bêta.

![image](https://user-images.githubusercontent.com/35631001/79599372-a73ed380-80e5-11ea-9673-7f31150a2746.png)

Par contre, j'ai joué avec le bouton "retrouver un text area normal" et j'ai foutu le merdier.

## En mode normal

Les boutons se retrouvent en bas :

![image](https://user-images.githubusercontent.com/35631001/79599774-609da900-80e6-11ea-9329-d4f835afc442.png)

## En plein écran

Énorme chaos.

![image](https://user-images.githubusercontent.com/35631001/79599543-fa188b00-80e5-11ea-99ed-7c20130bac25.png)

Quand on clique sur le mode de compatibilité, on a ce qu'on voit dans la capture d'écran. Ensuite quand on clique sur "aperçu sur le côté", on a plus que la barre avec le fond derrière (mais on ne peut pas défiler vers le bas. À ce moment là, le bouton aperçu ne fait plus rien.

C'est le mode de compatibilité qui sèment le chaos j'ai l'impression.

Ah et on ne voit pas si on est en mode de compatibilité ou pas en cliquant le bouton, il reste avec la même tête, il n'y a pas de changement de style pour le voir « activé ».

2020-04-17 19:14 UTC, A-312 submitted a review, later dismissed

2020-04-19 13:56 UTC, firm1 commented
Merci @Arnaud-D pour la QA.

> Drôles d'artefacts

J'ai aussi firefox 75 mais sur ubuntu 19.10 mais j'observe pas ton bug. Je pense qu'on doit avoir un niveau de zoom différent ou une définition d'écran différente. Quoiqu'il en soit, c'est très probablement un bug que tu dois aussi avoir sur la prod en ce moment (tu peux vérifier s'il te plait ?), du coup ce n'est pas vraiment dans le scope de cette PR.

> Par contre, j'ai joué avec le bouton "retrouver un text area normal" et j'ai foutu le merdier.

J'ai apporté quelques ajustement là dessus.

**En mode normal** : ça devrait être corrigé.

**En mode plein écran** : Il s'avère que le "mode compatibilité" (ce bouton n'est pas très explicite d'ailleurs) tel qu'implémenté n'est pas compatible avec le plein écran tel que pensé par l'upstream à la base (d'ailleurs en creusant un peu je me rends compte que la PR faite à l'upstream ne gère pas ce cas). Pour le moment j'opte pour la solution qui consiste à désactiver les boutons de plein écran qui ne sont pas compatible avec ce mode.

la QA est relancée.

2020-04-19 15:50 UTC, Arnaud-D commented
J'ai en effet les artefacts en prod. On est d'accord sur le fait que ce soit hors-scope pour cette PR.

---

:heavy_check_mark: QA essentiellement OK.

Je n'ai pas réussi à faire foirer l'affichage ; les boutons sont bien grisés.

Une petite remarque : quand on repasse en mode compatibilité depuis le plein écran, on reste en haut. C'est un peu curieux, mais non-bloquant selon moi et peut être amélioré après coup.

---

Je suis d'accord avec le principe de griser les boutons, il faudrait juste quelque chose pour indiquer pourquoi (typiquement que le mode de compatibilité est activé). J'ai l'impression que c'est couvert/couvrable par #5726.

2020-04-19 20:14 UTC, firm1 commented
> Une petite remarque : quand on repasse en mode compatibilité depuis le plein écran, on reste en haut. C'est un peu curieux, mais non-bloquant selon moi et peut être amélioré après coup.

Yep, ce bug est connu (et lui aussi en prod) mais pour corriger celà il faut intervenir coté upstream (je vais voir si je peux pousser une PR à l'upstream dessus).

Je fais une rebase de cette PR pour que ça soit mergeable du coup.

2020-04-21 15:07 UTC, merged