Retire les aides du formulaire de création/édition de contenu
zestedesavoir/zds-site pull request #5742
Opened 2020-04-25 17:08 UTC by artragis

On les place désormais dans la sidebar, avec une ajaxification
Le but est d'avoir des boutons simples à utiliser pour demander de l'aide.

Ce commit propose une UI assez moche car je ne sais pas comment bien présenter ces boutons, mais le tout est assez fonctionnel. (je n'ai juste pas encore exclus les billets)

# A l'aide

ça serait bien que quelqu'un qui a une bonne idée de comment faire une GUI acceptable pour cette fonctionnalité me fasse une PR avec le CSS adapté. 

# QA 

- Créer un tuto
- Observez que le formulaire de demander d'aide n'existe plus
- Éditer le tuto
- Observez que le formulaire de demande d'aide n'existe plus
- dans la page d'accueil du tuto, dans la sidebar, une partie "Demander de l'aide à la communauté apparaît.
- Lorsqu'on clique sur un des boutons, il change de statu (désactivé => activé, activé => désactivé ) et lorsqu'on recharge la page c'est le bon statu qui apparâit
- Regarder que cette section n'apparaît pas pour les billets

2020-05-11 19:33 UTC, Arnaud-D commented on templates/tutorialv2/view/content.html
> +                    ci dessous votre contenu sera répertorié dans la page <a href="{{ help_url }}">des aides</a>
> En sélectionnant un des éléments ci dessous votre contenu sera répertorié

En sélectionnant un des éléments ci-dessous, votre contenu sera répertorié => trait d'union et virgule.

2020-05-11 19:33 UTC, Arnaud-D commented on templates/tutorialv2/view/content.html
> +            {% trans "Demander de l'aide à la communauté" %}
Chez moi le texte "Demander de l'aide à la communauté" est trop long dans la sidebar (ça frôle le bord). Je propose juste de raccourcir en "Demander de l'aide" et la popup expliquera le reste.

2020-05-11 19:41 UTC, artragis commented
Radis for QA

2020-05-11 19:44 UTC, artragis commented on templates/tutorialv2/view/content.html
> +                    ci dessous votre contenu sera répertorié dans la page <a href="{{ help_url }}">des aides</a>
fixed

2020-05-11 19:44 UTC, artragis commented on templates/tutorialv2/view/content.html
> +            {% trans "Demander de l'aide à la communauté" %}
fixed

2020-05-20 18:45 UTC, Arnaud-D commented
:x: QA NOK

J'ai un problème à l'affichage : la coche est trop prêt du texte.

![image](https://user-images.githubusercontent.com/35631001/82484492-48042280-9ada-11ea-85be-2fdb28c031bf.png)

Firefox 76.0.1 sous Ubuntu 18.04.

2020-05-20 19:11 UTC, artragis commented
> Je crois que la solution choisie en CSS ne s'adapte pas bien aux différentes résolutions d'écran. Il vaudrait mieux positionner la coche par rapport au texte que par rapport au bord gauche.

il faudrait faire comment?

2020-05-20 19:34 UTC, Arnaud-D commented on zds/tutorialv2/views/contents.py
> +        messages.error(self.request, str(_("Les suggestions sélectionnées n'existent pas.")))
On est vraiment obligés de convertir en string ? Il me semblait que Django gérait correctement l'internationalisation des messages d'erreur.

2020-05-20 20:04 UTC, artragis commented on zds/tutorialv2/views/contents.py
> +        messages.error(self.request, str(_("Les suggestions sélectionnées n'existent pas.")))
le pb c'est que `_` est ici lazy et json ne sait pas sérialiser un lazy il faudrait que j'importe gettext non lazy juste pour cette ligne là où forcer l'évaluation et assez claire.

Si on ne fait pas ça on a un 500.

2020-06-09 19:47 UTC, artragis commented
Pour info, je n'ai pas avancé ici car je ne comprends pas ce qu'il faudrait faire en CSS.

2020-06-13 12:49 UTC, AmauryCarrade commented
Salut ! J'ai regardé le soucis de CSS.

Ça aurait pu se corriger, mais je propose plutôt de réutiliser l'existant. En effet, sans trop que je ne comprenne pourquoi, le code actuel de cette PR ré-implémente l'affichage de l'icône et tout, alors qu'on peut juste réutiliser les mêmes classes que le reste des éléments de la barre latérale.

Je propose donc ceci :

```diff
diff --git a/assets/js/content-helps.js b/assets/js/content-helps.js
index ca8b2c255..aebbdd6c7 100644
--- a/assets/js/content-helps.js
+++ b/assets/js/content-helps.js
@@ -1,5 +1,5 @@
 (function($) {
-  $('.help-toogle').click((e) => {
+  $('.help-toggle').click((e) => {
     const $current = $(e.target)
     e.preventDefault()
     const newActivation = $current.attr('data-activated') !== 'true'
@@ -13,13 +13,14 @@
         help_wanted: $current.text()
       },
       success: () => {
-        if (newActivation) {
-          $current.addClass('help-activated')
-          $current.attr('data-activated', 'true')
-        } else {
-          $current.removeClass('help-activated')
-          $current.attr('data-activated', 'false')
-        }
+        let current_el_classes = $current[0].classList
+
+        current_el_classes.toggle('selected', newActivation)
+        current_el_classes.toggle('ico-after', newActivation)
+        current_el_classes.toggle('tick', newActivation)
+        current_el_classes.toggle('green', newActivation)
+
+        $current.attr('data-activated', newActivation.toString())
       }
     })
   })
diff --git a/assets/scss/layout/_sidebar.scss b/assets/scss/layout/_sidebar.scss
index 18f62f66b..6a375946a 100644
--- a/assets/scss/layout/_sidebar.scss
+++ b/assets/scss/layout/_sidebar.scss
@@ -342,16 +342,16 @@
                     margin-top: 5px;
                 }
             }
-            
+
             &.not-ready {
                 background: $color-not-ready-content;
             }
         }
-        
+
         li {
             &.not-ready {
                 background: $color-not-ready-content;
-            }   
+            }
         }
 
         ol li.current {
@@ -379,28 +379,3 @@
         }
     }
 }
-
-.sidebar ul li a.help-toogle {
-    &:after {
-        position: absolute;
-        display: block;
-        left: 20px;
-        margin-left: 30px;
-        margin-right: 5px;
-        content: " ";
-    }
-
-    &.help-activated:after{
-        color: $color-success;
-        content: " ";
-        @include sprite();
-        @include sprite-position($tick-green);
-        width: 16px;
-        height: 16px;
-        top: 7px;
-        padding-left: 0;
-    }
-    &.help-activated {
-        font-weight: bolder;
-    }
-}
diff --git a/templates/tutorialv2/view/content.html b/templates/tutorialv2/view/content.html
index f50955f0d..59d679fce 100644
--- a/templates/tutorialv2/view/content.html
+++ b/templates/tutorialv2/view/content.html
@@ -725,7 +725,7 @@
             {% for help in helps %}
                 <li>
                     <a href="{% url 'content:helps-change' content.pk %}"
-                       class="help-toogle {% if help.pk in content_helps %}help-activated{% endif %} help-{{ help.slug }}"
+                       class="help-toggle {% if help.pk in content_helps %}selected ico-after tick green{% endif %} help-{{ help.slug }}"
                        data-activated="{% if help.pk in content_helps %}true{% else %}false{% endif %}">
                         {{ help.title }}
                     </a>
```

…ce qui donne : 

![image](https://user-images.githubusercontent.com/1417570/84569177-c88a0c00-ad84-11ea-9e35-8448a336d479.png)

J'ai au passage retiré un poil de duplication de code dans le JS qui gère ça (on sous-utilise l'argument `force` de `classList.toggle()`, c'est tellement pratique pour ce genre de cas).

2020-06-13 13:08 UTC, AmauryCarrade commented on zds/tutorialv2/views/contents.py
> +class ChangeHelp(LoggedWithReadWriteHability, SingleContentFormViewMixin):
Autre remarque : si JS est désactivé, le lien ne fonctionne pas car il attend une requête POST (et car il ne fait de toute façon jamais de redirection pour gérer ce cas), ce qui fait que sans JS on se prend une erreur 500.

Si on s'en fout de gérer le cas où JS est désactivé (cf. discussion de la dernière réunion de dév) mais qu'on veut tout de même avoir un retour un minimum propre, on pourrait faire : 

```suggestion
@method_decorator(require_POST, name='dispatch')
class ChangeHelp(LoggedWithReadWriteHability, SingleContentFormViewMixin):
```

Cette suggestion nécessite d'ajouter l'import correspondant : 

```py
from django.views.decorators.http import require_POST
```

2020-06-15 11:26 UTC, artragis commented on zds/tutorialv2/views/contents.py
> +class ChangeHelp(LoggedWithReadWriteHability, SingleContentFormViewMixin):
Je pense avoir trouvé encore mieux.

2020-06-15 13:16 UTC, AmauryCarrade commented on zds/tutorialv2/views/contents.py
> +class ChangeHelp(LoggedWithReadWriteHability, SingleContentFormViewMixin):
Effectivement, passer par un vrai formulaire en secondaire c'est d'autant mieux, +1

2020-06-15 14:28 UTC, AmauryCarrade commented
Donc, QA : 
- :heavy_check_mark: OK avec JS (même si je propose une petite amélioration) ;
- :x: Pas OK sans JS : il manque le jeton CSRF, et l'un des champs n'est pas correctement initialisé (état inversé).

Aussi, sans JS on a juste un JSON comme retour, mais ça change tout de même l'aide. Donc bon, je me dis que comme support limité ça suffit.

Dans le patch qui suit, je propose plusieurs améliorations et correctifs : 
- le jeton CSRF est ajouté au formulaire ;
- la valeur du champ `activated` du formulaire est corrigée ;
- la requête AJAX est construite à partir du formulaire, et non reconstruite indépendamment : ça évite toute divergence, rendant le tout bien plus cohérent (de plus, un `<button />` n'accepte pas d'attribut `href`) ;
- effet de bord, il n'est plus nécessaire d'ajouter une en-tête pour le jeton CSRF vu qu'il est dans les champs du formulaire ;
- le changement de style est effectué instantanément au clic (et confirmé lorsque la réponse est reçue, ou restauré si on reçoit une erreur), afin de donner une bien plus grande impression de fluidité à l'utilisateur ;
- plus anecdotique, mais `ToogleHelpForm` est renommé en `ToggleHelpForm`.

```diff
diff --git a/assets/js/content-helps.js b/assets/js/content-helps.js
index aebbdd6c7..8c6a4c3ab 100644
--- a/assets/js/content-helps.js
+++ b/assets/js/content-helps.js
@@ -1,27 +1,37 @@
 (function($) {
+  function change_help_state($help_button, state) {
+    let current_el_classes = $help_button[0].classList
+
+    current_el_classes.toggle('selected', state)
+    current_el_classes.toggle('ico-after', state)
+    current_el_classes.toggle('tick', state)
+    current_el_classes.toggle('green', state)
+
+    $help_button.attr('data-activated', state.toString())
+    $help_button.blur()
+
+    $help_button.parent().find('input[name="activated"]').val((!state).toString())
+  }
+
   $('.help-toggle').click((e) => {
-    const $current = $(e.target)
     e.preventDefault()
+
+    const $current = $(e.target)
+    const $form = $current.parent()
+    const data = $form.serialize()
+
     const newActivation = $current.attr('data-activated') !== 'true'
-    $.ajax($current.attr('href'), {
-      headers: {
-        'X-CSRFToken': $('input[name=csrfmiddlewaretoken]').val()
-      },
+
+    // Change status before request for instant feeling.
+    // Will be changed back on error.
+    // This update the form so serialize must be called before/
+    change_help_state($current, newActivation)
+
+    $.ajax($form.attr('action'), {
       method: 'POST',
-      data: {
-        activated: newActivation ? 'true' : 'false',
-        help_wanted: $current.text()
-      },
-      success: () => {
-        let current_el_classes = $current[0].classList
-
-        current_el_classes.toggle('selected', newActivation)
-        current_el_classes.toggle('ico-after', newActivation)
-        current_el_classes.toggle('tick', newActivation)
-        current_el_classes.toggle('green', newActivation)
-
-        $current.attr('data-activated', newActivation.toString())
-      }
+      data,
+      success: data => change_help_state($current, data.help_wanted),
+      error: () => change_help_state($current, !newActivation)
     })
   })
 })(jQuery)
diff --git a/templates/tutorialv2/view/content.html b/templates/tutorialv2/view/content.html
index dbd9f64c2..e2f1f036e 100644
--- a/templates/tutorialv2/view/content.html
+++ b/templates/tutorialv2/view/content.html
@@ -718,7 +718,7 @@
                     <p>
                         Lorsque vous rédigez un tutoriel ou un article, il se peut que vous ayiez
                         besoin d'aide. La communauté est là pour vous ! En sélectionnant un des éléments
-                        ci-dessous, votre contenu sera répertorié dans la page <a href="{{ help_url }}">des aides</a>
+                        ci-dessous, votre contenu sera répertorié dans <a href="{{ help_url }}">la page des aides</a>
                         et la communauté pourra vous contacter.
                     </p>
                 {% endblocktrans %}
@@ -728,9 +728,10 @@
                 {% for help in helps %}
                     <li>
                         <form action="{% url 'content:helps-change' content.pk %}" method="POST">
-                            <input type="hidden" name="activated" value="{% if help.pk in content_helps %}true{% else %}false{% endif %}">
+                            {% csrf_token %}
+                            <input type="hidden" name="activated" value="{% if help.pk in content_helps %}false{% else %}true{% endif %}">
                             <input type="hidden" name="help_wanted" value="{{ help.title }}">
-                            <button href="{% url 'content:helps-change' content.pk %}" type="submit"
+                            <button type="submit"
                                class="help-toggle {% if help.pk in content_helps %}selected ico-after tick green{% endif %} help-{{ help.slug }}"
                                data-activated="{% if help.pk in content_helps %}true{% else %}false{% endif %}">
                                 {{ help.title }}
diff --git a/zds/tutorialv2/forms.py b/zds/tutorialv2/forms.py
index 05dc03df9..459a386f2 100644
--- a/zds/tutorialv2/forms.py
+++ b/zds/tutorialv2/forms.py
@@ -1450,7 +1450,7 @@ class RemoveSuggestionForm(forms.Form):
     )
 
 
-class ToogleHelpForm(forms.Form):
+class ToggleHelpForm(forms.Form):
     help_wanted = forms.CharField()
     activated = forms.BooleanField(required=False)
 
diff --git a/zds/tutorialv2/views/contents.py b/zds/tutorialv2/views/contents.py
index c6dba31e5..52cdd0c32 100644
--- a/zds/tutorialv2/views/contents.py
+++ b/zds/tutorialv2/views/contents.py
@@ -38,7 +38,7 @@ from zds.tutorialv2.forms import ContentForm, JsFiddleActivationForm, AskValidat
     RejectValidationForm, RevokeValidationForm, WarnTypoForm, ImportContentForm, ImportNewContentForm, ContainerForm, \
     ExtractForm, BetaForm, MoveElementForm, AuthorForm, RemoveAuthorForm, CancelValidationForm, PublicationForm, \
     UnpublicationForm, ContributionForm, RemoveContributionForm, SearchSuggestionForm, RemoveSuggestionForm, \
-    EditContentLicenseForm, EditContentTagsForm, ToogleHelpForm
+    EditContentLicenseForm, EditContentTagsForm, ToggleHelpForm
 from zds.tutorialv2.mixins import SingleContentDetailViewMixin, SingleContentFormViewMixin, SingleContentViewMixin, \
     SingleContentDownloadViewMixin, SingleContentPostMixin, FormWithPreview
 from zds.tutorialv2.models import TYPE_CHOICES_DICT
@@ -2068,7 +2068,7 @@ class RemoveAuthorFromContent(LoggedWithReadWriteHability, SingleContentFormView
 
 
 class ChangeHelp(LoggedWithReadWriteHability, SingleContentFormViewMixin):
-    form_class = ToogleHelpForm
+    form_class = ToggleHelpForm
 
     def form_valid(self, form):
         """
@@ -2085,7 +2085,7 @@ class ChangeHelp(LoggedWithReadWriteHability, SingleContentFormViewMixin):
         else:
             self.object.helps.remove(data['help_wanted'])
         self.object.save(force_slug_update=False)
-        return HttpResponse(json.dumps({'result': 'ok'}), content_type='application/json')
+        return HttpResponse(json.dumps({'result': 'ok', 'help_wanted': data['activated']}), content_type='application/json')
 
     def form_invalid(self, form):
         return HttpResponse(json.dumps({'errors': form.errors}), status=400, content_type='application/json')
```

Je peux l'envoyer directement en un commit, sur simple demande.

2020-06-15 15:41 UTC, artragis commented
J'ai appliqué ton patch + mettre en camelCase ta fonction + avoir une vraie redirection quand on n'est pas en ajax

2020-06-15 16:01 UTC, AmauryCarrade commented
Mmh, n'aurais-tu pas oublié d'envoyer une partie des modifications ?

2020-06-15 16:07 UTC, artragis commented
Merde... le push est pas passé

2020-06-15 16:21 UTC, artragis commented
ça devrait être mieux.

2020-06-21 12:23 UTC, AmauryCarrade requested changes
Un petit dernier détail, probablement une erreur de fusion :)

2020-06-21 12:23 UTC, AmauryCarrade commented on assets/js/content-helps.js
> +      }
Code dupliqué : un problème de fusion ou similaire ? Il faudrait réutiliser la fonction plus haut, et utiliser l'état final renvoyé par le serveur.

```suggestion
      success: data => changeHelpButtonState($current, data.help_wanted)
```

2020-06-21 12:26 UTC, AmauryCarrade commented on assets/js/content-helps.js
> +      },
Et désolé pour la double-revue parce que j'ai regardé un peu vite, mais pareil ici.
```suggestion
      data,
```

2020-06-21 12:31 UTC, AmauryCarrade commented on assets/js/content-helps.js
> +    const newActivation = $current.attr('data-activated') !== 'true'
Et ici aussi (ahhh je suis mauvais)

C'est bizarre, c'est comme si la moitié avait été appliqué

```suggestion
    const $current = $(e.target)
    const $form = $current.parent()
    const data = $form.serialize()

    const newActivation = $current.attr('data-activated') !== 'true'
```

2020-06-22 15:45 UTC, artragis commented on assets/js/content-helps.js
> +    const newActivation = $current.attr('data-activated') !== 'true'
y'a des trucs que j'avais enlevé car il y avait des variables non utilisées, notamment data.

2020-06-22 15:51 UTC, artragis commented
rebasé et mis à jour

2020-06-22 16:51 UTC, AmauryCarrade requested changes
:heavy_check_mark: QA OK

Il reste un dernier détail à corriger (sinon impossible de fusionner), mais inutile de refaire ensuite le contrôle qualité :slightly_smiling_face: .

2020-06-22 16:51 UTC, AmauryCarrade commented on assets/js/content-helps.js
> +      error: () => changeHelpButtonState($current, !newActivation),
ESLint râle.

```suggestion
      error: () => changeHelpButtonState($current, !newActivation)
```

2020-06-22 17:33 UTC, merged