Ajoute un attribut alt aux images de unes et cartouches de contenu de la page d'accueil
zestedesavoir/zds-site pull request #5756
Opened 2020-04-28 16:27 UTC by ToxicScorpius

J'ai ajouté un attribut `alt` aux images de unes (`illustration {{featured.title}}`) et aux cartouches de contenu sur la page d'accueil (`logo de {{content.public_title}}`)

Numéro du ticket concerné : #5674 

Merci !

2020-04-28 18:09 UTC, artragis commented on templates/featured/includes/featured_resource_item.part.html
> +        <img src="{{ featured_resource.image_url|remove_url_scheme }}" alt="illustration {{featured.title}}" class="featured-resource-illu">
As-tu essayé de créer une feature qui a un guillemet dans le titre pour voir si ça pète pas tout? (logiquement, non django fiat bien les choses, mais j'aimerais être sûr)

2020-04-28 19:15 UTC, Situphen reviewed
Léger perfectionnisme de ma part

2020-04-28 19:15 UTC, Situphen commented on templates/featured/includes/featured_resource_item.part.html
> +        <img src="{{ featured_resource.image_url|remove_url_scheme }}" alt="illustration {{featured.title}}" class="featured-resource-illu">
```suggestion
        <img src="{{ featured_resource.image_url|remove_url_scheme }}" alt="Illustration {{ featured.title }}" class="featured-resource-illu">
```

2020-04-28 19:15 UTC, Situphen commented on templates/tutorialv2/includes/content_item.part.html
> +            <img src="{{ content.image.physical.content_thumb.url }}" alt="logo de {{content.public_title}}">
```suggestion
            <img src="{{ content.image.physical.content_thumb.url }}" alt="Logo de {{ content.public_title }}">
```

2020-04-28 20:09 UTC, A-312 commented on templates/featured/includes/featured_resource_item.part.html
> +        <img src="{{ featured_resource.image_url|remove_url_scheme }}" alt="illustration {{featured.title}}" class="featured-resource-illu">
Le guillemet n'est pas déjà convertie en `%22` dans l'url ?

2020-04-28 20:28 UTC, ToxicScorpius commented on templates/tutorialv2/includes/content_item.part.html
> +            <img src="{{ content.image.physical.content_thumb.url }}" alt="logo de {{content.public_title}}">
Est ce que c'est vraiment nécessaire ? Une personne aveugle ne fait pas la différence entre une majuscule et une minuscule...

2020-04-28 20:29 UTC, ToxicScorpius commented on templates/featured/includes/featured_resource_item.part.html
> +        <img src="{{ featured_resource.image_url|remove_url_scheme }}" alt="illustration {{featured.title}}" class="featured-resource-illu">
Nope, je n'y ai pas pensé. Je vais créer un tuto avec des guillemets plus tard et voir si tout fonctionne.

2020-04-28 21:33 UTC, Situphen commented on templates/tutorialv2/includes/content_item.part.html
> +            <img src="{{ content.image.physical.content_thumb.url }}" alt="logo de {{content.public_title}}">
La majuscule n'est pas vraiment nécessaire, c'est du perfectionnisme poussé à outrance. Par contre mettre des espaces pour `{{ var }}` ça facilite la lecture du code. :)

2020-04-29 05:49 UTC, Arnaud-D requested changes

2020-04-29 05:49 UTC, Arnaud-D commented on templates/tutorialv2/includes/content_item.part.html
> +            <img src="{{ content.image.physical.content_thumb.url }}" alt="Logo de {{ content.public_title }}">
Tu vas devoir utiliser `{{ content_title }}`, actuellement ça n'affiche rien (tu peux le constater en testant en local). Tu peux voir un groupe `capture_as` et tu verras pourquoi on utilise pas `content.public_title` de manière brute. :)

2020-04-29 05:49 UTC, Arnaud-D commented on templates/featured/includes/featured_resource_item.part.html
> +        <img src="{{ featured_resource.image_url|remove_url_scheme }}" alt="Illustration {{ featured.title }}" class="featured-resource-illu">
`featured_resource.title` à la place de `featured.title`. Actuellement, ça n'affiche rien. ;)

2020-04-29 05:50 UTC, Arnaud-D commented
:x: **QA KO.** Le texte après « Illustration » et « Logo de » n'est pas affiché, cf. mes commentaires.

2020-04-30 21:09 UTC, Arnaud-D commented
:heavy_check_mark: QA OK.

Rebase puis on pourra fusionner !

2020-04-30 21:10 UTC, Arnaud-D approved these changes

2020-05-13 19:01 UTC, merged