Ajoute le fil d'Ariane dans la bibliothèque et le profil
zestedesavoir/zds-site pull request #5768
Opened 2020-04-30 20:58 UTC by Arnaud-D

Fix #5090.

J'ajoute le fil d'Ariane sur la bibliothèque et le profil.

J'aurais besoin d'un peu de soutien sous la forme :

1. De retours sur l'utilité réelle dans la bibliothèque. J'ai l'impression que c'est assez redondant avec le gros bandeau bleu.
2. D'aide pour le design et le CSS. Ça dépasse largement mes capacités, et ce que j'ai fait n'est pas abouti.
3. D'une revue du code. J'ai pas fait de CSS depuis 10 ans, je découvre Sass, je suis pas très assuré.

### Contrôle qualité

Pour le profil :

- Rebuilder le front.
- Aller sur un profil quelconque.
- Constater qu'on a le fil d'Ariane correct (avec les liens sauf sur le dernier élément).

Pour la bibliothèque

- Rebuilder le front.
- Aller sur la bibliothèque
- Constater le fil d'Ariane correct
- Recommencer sur une catégorie, une sous-catégorie, un tag, le type article et le type tutoriel (ces derniers sont accessibles depuis la page d'accueil).

2020-04-30 22:11 UTC, Situphen reviewed
Quelques petites remarques sur la forme, je ne me suis pas posé de question sur le fond. :)

2020-04-30 22:11 UTC, Situphen commented on templates/tutorialv2/view/base_categories.html
> +        <li>{{subcategory.title}}</li>
Espacement
```suggestion
        <li>{{ subcategory.title }}</li>
```

2020-04-30 22:11 UTC, Situphen commented on templates/member/profile.html
> +            {% blocktrans with username=profile.user.username %} Profil de {{ username }} {% endblocktrans %}
Indentation en trop
```suggestion
        {% blocktrans with username=profile.user.username %} Profil de {{ username }} {% endblocktrans %}
```

2020-04-30 22:11 UTC, Situphen commented on assets/scss/components/_breadcrumb.scss
> +        }
Concaténation/Factorisation
```suggestion
        ol li {
            a {
                color: #ddd;
            }

            &:not(:last-child):after {
                @include sprite();
                @include sprite-position($ariane-alt);
            }
        }
```

2020-04-30 22:11 UTC, Situphen commented on assets/scss/components/_breadcrumb.scss
> +            background-image:none;
Espacement
```suggestion
            background-image: none;
```

2020-04-30 22:11 UTC, Situphen commented on assets/scss/components/_breadcrumb.scss
> +        background:#225871;
Espacement
```suggestion
        background: #225871;
```

2020-04-30 22:11 UTC, Situphen commented on assets/scss/components/_breadcrumb.scss
> +    color:white;
Espacement
```suggestion
    color: white;
```

2020-06-18 20:52 UTC, AmauryCarrade commented
> De retours sur l'utilité réelle dans la bibliothèque. J'ai l'impression que c'est assez redondant avec le gros bandeau bleu.

Sur ce point je suis d'accord : je ne suis pas franchement convaincu de la pertinence d'avoir un fil d'Ariane dans la bibliothèque. Le fil est déjà présent sous une autre forme dans le bandeau bleu. Je serais pour ne pas le remettre.

> D'aide pour le design et le CSS. Ça dépasse largement mes capacités, et ce que j'ai fait n'est pas abouti.
> D'une revue du code. J'ai pas fait de CSS depuis 10 ans, je découvre Sass, je suis pas très assuré.

Je vais regarder ça :) .

2020-06-18 21:23 UTC, AmauryCarrade requested changes
Je trouve, après avoir regardé, que l'intégration n'est pas si mal que ça. Je n'ai pas encore regardé le CSS en détail mais j'ai laissé quelques notes.

En terme d'intégration elle-même, je serais partant de supprimer le champ de recherche dans ce cas précis. En effet, ça fait doublon avec le champ déjà présent dans l'en-tête. Je trouve que c'est confus, sans compter que ça fait une belle tâche blanche.

![Le fil d'Ariane tel que proposé, avec le champ de recherche blanc dans un univers bleu](https://user-images.githubusercontent.com/1417570/85071695-2e78f800-b1b8-11ea-91f2-9ad08bd91270.png)

Mais sinon, je le trouve pas si mal que ça. Pour être honnête, j'y avais déjà un peu réfléchi et je n'avais pas trouvé de _bonne_ solution, au delà de quelque chose de ce genre… Difficile de persister l'intégration fluide du bandeau bleu, le fil d'Ariane étant par essence une belle interruption dans ce dernier.

J'avais aussi pensé à le mettre _sous_ le bandeau, mais je ne suis pas sûr que ça rendrait si bien que ça, sans compter que ce serait peut-être un peu bizarre de couper le contenu comme ça, donc à la réflexion, bof bof.

Ou alors, vu que seule la page des membres est concernée, on pourrait réfléchir à une alternative pour cette dernière (ou pour toutes les pages à bandeau). Par exemple, on pourrait imaginer ne pas mettre de fil d'Ariane, mais à la place, insérer un lien de retour à la liste des membres (c'est le seul lien “perdu” en l'absence de fil d'Ariane). Cette solution pourrait être réutilisée ailleurs au besoin.

Voici un exemple rapide, bricolé dans le navigateur directement… c'est pour l'idée, hein. Et il faudrait bien sûr voir ce que ça deviendrait avec un écran étroit (mais on peut s'arranger).

![Bouton de retour flottant sur le bandeau bleu](https://user-images.githubusercontent.com/1417570/85073012-50737a00-b1ba-11ea-8bc2-892ae010cc52.png)

Mais ta solution reste propre, bien que je l'amputerais de son champ de recherche…

2020-06-18 21:23 UTC, AmauryCarrade commented on assets/scss/components/_breadcrumb.scss
> +.breadcrumb-alt {
Le nom de cette classe n'est pas très explicite. Je propose de la renommer `breadcrumb-flexpage` (par référence à la classe des pages avec en-tête bleues, `flexpage-header`, même si je trouve ce nom bien peu pertinent), ou bien `breadcrumb-blue-header`.

2020-06-19 22:13 UTC, Arnaud-D commented
> Mais ta solution reste propre, bien que je l'amputerais de son champ de recherche…

Le problème de ça, c'est que tu te retrouves avec le champs de recherche sur une partie des pages seulement, ce qui est pour le moins curieux.

> Ou alors, vu que seule la page des membres est concernée, on pourrait réfléchir à une alternative pour cette dernière (ou pour toutes les pages à bandeau).

Il n'y a pas que la page des membres, il y a aussi la bibliothèque. Ça contraint un peu la conception.

2020-06-20 01:25 UTC, AmauryCarrade commented
En fait, je partais du principe qu'on ne mettait pas de fil d'Ariane sur la bibliothèque (étant donné que ça fait doublon), ce qui fait qu'il ne reste que la page de profil concernée, pour le moment. Effectivement, si on la garde sur la bibliothèque, ça change la donne.

2020-06-20 09:52 UTC, Arnaud-D commented
Ça fait effectivement doublon, mais le problème, c'est que c'est inhomogène avec les autres pages et donc déroutant. C'est quelque chose que j'ai entendu par une testeuse "attends elle est passée où la recherche ?". Le champ est en plein milieu, mais ce n'est pas là qu'on l'attend apparemment. :D Et la recherche ne cherche que dans la bibliothèque à cet endroit là en plus...

Peut-être que cette PR mérite une plus ample réflexion et devrait partir au cimetière pour mieux revenir plus tard. Les fonctions remplies par le fil d'Ariane peuvent probablement être rendues d'une meilleure manière. Je vois au moins les fonctionnalités suivantes :

1. permettre de faire une recherche sur tout le site depuis n'importe quelle page ;
2. se repérer dans le site ;
3. naviguer dans des arborescences (sur la bibliothèque et le forum notamment).

2020-08-13 21:50 UTC, Arnaud-D commented
Ce sujet mérite un peu plus de réflexion avant de pouvoir être traité correctement.

2020-08-13 21:50 UTC, closed without merging