Déplace la modification des tags dans un formulaire séparé
zestedesavoir/zds-site pull request #5788
Opened 2020-05-13 22:23 UTC by Arnaud-D

Je continue le mouvement de simplification de la création de contenu en déplaçant le choix des tags dans un formulaire séparé sous forme de modale.

Je ne suis pas très subtil sur le design, ça ressemble à ça pour l'instant :

![image](https://user-images.githubusercontent.com/35631001/81871719-aed48980-9578-11ea-86c9-bba10fab1a8e.png)

Il me reste du travail :

- [ ] améliorer la modales pour rajouter une phrase ou deux d'explication sur ce que sont les tags
- [ ] tests unitaires pour la nouvelle vue
- [ ] quelques lignes de codes qui me paraissent maladroites et que je veux regarder de plus près
- [ ] gérer l'affichage du bouton sur la version en ligne, puisque ce n'est pas une info versionnée, mais éditoriale
- [ ] écrire quelques lignes d'instructions pour la QA.

### Contrôle qualité

TODO

2020-05-14 18:55 UTC, artragis commented
ça vaudrait pas le coup de faire ça in-place plutôt que dans une modale?

2020-05-14 19:01 UTC, Arnaud-D commented
Tu penses à quoi exactement ?

Je crains que le faire *in-place* empêche de rajouter des explications et aussi soit insurmontable pour moi niveau *front* (trouver des solutions ergonomiques et élégants, peut-être un bout de JS ou autre).

2020-06-09 12:30 UTC, A-312 commented
J'ai une préférence pour le inplace mais je trouve le screenshot propre c'est tout de suite mieux que la situation actuelle, en plus il y a plein de test. 👍

2020-06-10 18:13 UTC, artragis requested changes

2020-06-10 18:13 UTC, artragis commented on zds/tutorialv2/views/contents.py
> +        initial_tags_field = ', '.join([tag['title'] for tag in self.object.tags.values('title')]) or ''
le `or ''` me semble de trop puisque `','.join([])` retourne `''`

2020-06-10 18:13 UTC, artragis commented on zds/utils/forms.py
> +            self.errors.append(TagValidator.error_utf8mb4.format(tag))
j'aime bien ça :)

2020-06-10 18:13 UTC, artragis commented on zds/utils/forms.py
> +            self.errors.append(error)
quel est l'intérêt de passer par une variable temporaire?

2020-06-10 18:13 UTC, artragis commented on zds/utils/forms.py
> +            self.logger.warning('%s bad slug', tag)
hésite pas à mettre un délimiteur autour de `%s` pour qu'on puisse plus facilement observer les espaces vides. (e.g `'"%s" bad slug'`)

2020-06-10 19:01 UTC, Arnaud-D commented on zds/tutorialv2/views/contents.py
> +        initial_tags_field = ', '.join([tag['title'] for tag in self.object.tags.values('title')]) or ''
J'ai trouvé plus concis encore (cf. mon commit).

2020-06-10 19:02 UTC, Arnaud-D commented on zds/utils/forms.py
> +            self.errors.append(TagValidator.error_utf8mb4.format(tag))
Tant mieux que tu apprécies, j'étais assez content de l'idée aussi. On a encore des progrès à faire sur la gestion des erreurs dans le code, ceci dit.

2020-06-10 19:02 UTC, Arnaud-D commented on zds/utils/forms.py
> +            self.errors.append(error)
Aucun. Ça reste lisible sans, donc j'ai enlevé.

2020-06-10 19:03 UTC, Arnaud-D commented on zds/utils/forms.py
> +            self.logger.warning('%s bad slug', tag)
Bien vu. C'est fait

2020-06-12 10:58 UTC, artragis approved these changes

2020-06-12 11:03 UTC, artragis commented
QA OK

2020-06-12 11:03 UTC, merged