Simplifie le watchdog de publication
zestedesavoir/zds-site pull request #5814
Opened 2020-06-02 12:50 UTC by Situphen

Voici un petit nettoyage du watchdog de publication qui le simplifie et ça devrait régler nos soucis. Auparavant on lançait plusieurs générations d'export en parallèle mais on s'est rendu compte que ça causait pas mal d'erreurs "MySQL has gone away" donc on est ne parallélise plus. Plus besoin donc de `concurrent.futures` que j'ai enlevé.

Si jamais on voit l'erreur `FailureDuringPublication`, le *watchdog* continue de tourner. Si jamais on a une autre erreur (du style "MySQL has gone away") alors normalement le *watchdog* devrait planter et être redémarrer par systemd.

N'hésitez pas à donner vos avis !

2020-06-02 17:20 UTC, artragis commented on zds/tutorialv2/publication_utils.py
> +        shutil.copy2(latex_file_path, published_content_entity.get_extra_contents_directory())
ça serait bien de faire la copy avant le `full_tex_compiler_call` tiens comme ça on évitera les cas où le latex est pas envoyé.

2020-06-02 17:21 UTC, artragis requested changes

2020-06-02 17:21 UTC, artragis commented on zds/tutorialv2/publication_utils.py
> +        logging.info('published latex=%s, pdf=%s', published_content_entity.has_type('tex'),
d'ailleurs on devrait peut être faire `logger.info` plutôt que `logging.info`

2020-06-02 18:56 UTC, Situphen commented on zds/tutorialv2/publication_utils.py
> +        logging.info('published latex=%s, pdf=%s', published_content_entity.has_type('tex'),
Je me demande si on ne devrait pas l'enlever et laisser seulement le message de succès du watchdog.

2020-06-02 19:50 UTC, artragis commented on zds/tutorialv2/publication_utils.py
> +        logging.info('published latex=%s, pdf=%s', published_content_entity.has_type('tex'),
ça me va aussi.

2020-06-03 07:46 UTC, Situphen commented
J'ai ajouté les instructions de QA et ma branche est sûr la bêta si besoin :)

2020-06-09 17:01 UTC, firm1 commented
# Rapport de QA

**QA OK**

2020-06-09 17:23 UTC, merged