Ajoute une page avec la liste des sujets suivis
zestedesavoir/zds-site pull request #5815
Opened 2020-06-03 14:33 UTC by Karnaj

On peut accéder à la liste des sujets suivis par un membre depuis sa page de profil.

### Contrôle qualité

- S'amuser à suivre et arrêter de suivre des sujets avec un membre. 
- Vérifier que le lien apparaît bien (avec le bon nombre de sujets suivis) depuis la page de profil de ce membre.
- Suivre un sujet dans un forum privé (staff par exemple) avec un membre `m`. Vérifier que seul un membre qui a aussi accès à ce forum peut le voir dans la liste des messages suivis de `m` et qu'on a un message indiquant que des sujets sont invisibles.

2020-06-03 16:02 UTC, A-312 commented
C'est seulement pour les sujets qu'on suit soit même ? Car sinon c'est un peu intrusif de voir ce qu'une personne suit.

2020-06-10 10:49 UTC, Karnaj commented
> C'est seulement pour les sujets qu'on suit soi-même ? Car sinon c'est un peu intrusif de voir ce qu'une personne suit. eye

Effectivement, j'ai modifié le code pour que ce soit le cas. Il me reste à écrire les tests correspondants.

2020-07-18 20:13 UTC, philippemilink commented
Prêt à QA ?

2020-07-20 11:52 UTC, Karnaj commented
Normalement oui @philippemilink. Je mets à jour la branche et c'est OK.

2020-07-21 11:59 UTC, AmauryCarrade reviewed
:heavy_check_mark: QA OK

J'ai cependant quelques remarques ci-dessous. :)

2020-07-21 11:59 UTC, AmauryCarrade commented on templates/forum/find/topic.html
> +        {% trans "Sujets suivis par" %}
Vu que cette page n'est visible que par la personne qui suit les sujets (même pas par le staff par exemple), ne serait-il pas plus pertinent d'avoir un titre plus direct ? Tel que « Les sujets que vous suivez » ou « Vos sujets suivis » ou « Sujets suivis »

2020-07-21 11:59 UTC, AmauryCarrade commented on templates/forum/find/topic.html
> +        {% trans "Sujets suivis par" %}
Même remarque sur le titre.

2020-07-21 11:59 UTC, AmauryCarrade commented on templates/forum/find/topic.html
> +    {{ usr.username }}
Merci d'avoir retiré ces guillemets :ok_hand:

2020-07-21 11:59 UTC, AmauryCarrade commented on templates/forum/find/topic.html
> +                {% trans "Aucun sujet public n’a été suivi par" %} {{ usr.username }}.
Même remarque sur le titre.

2020-07-21 11:59 UTC, AmauryCarrade commented on templates/forum/find/topic.html
>      <li>{% trans "Recherche" %}</li>
C'est pas directement dans le cadre de cette PR, mais je trouve que ce dernier élément du fil d'Ariane est… peu pertinent.

2020-07-21 13:03 UTC, Karnaj commented on templates/forum/find/topic.html
> +                {% trans "Aucun sujet public n’a été suivi par" %} {{ usr.username }}.
Effectivement, ce sera mieux. Au début, on pouvait accéder à la liste des sujets suivis par n'importe quel utilisateur, et en limitant à la liste des sujets que l'on suit, je n'ai pas changé le titre.

2020-07-21 13:04 UTC, Karnaj commented on templates/forum/find/topic.html
>      <li>{% trans "Recherche" %}</li>
Je retire tu penses ? D'ailleurs faudra un « grand remaniement » au niveau du fil d'Ariane.

2020-07-21 13:17 UTC, AmauryCarrade commented on templates/forum/find/topic.html
>      <li>{% trans "Recherche" %}</li>
Je serais pour le retirer (et donc retirer le lien de l'actuel avant-dernier élément).

2020-07-23 16:19 UTC, artragis commented on templates/forum/find/topic.html
>                  {% trans "Aucun sujet public n’a été créé par" %} {{ usr.username }}.
autant continuer sur la lancée, non,

2020-07-24 09:42 UTC, AmauryCarrade commented on templates/forum/find/topic.html
>                  {% trans "Aucun sujet public n’a été créé par" %} {{ usr.username }}.
Comment ça ? Ce message-là peut être affiché avec n'importe quel utilisateur depuis n'importe quel utilisateur ; je ne suis pas sûr de comprendre ce que tu veux dire.

2020-07-24 09:53 UTC, AmauryCarrade requested changes
:x: QA NOK

Le titre est bien modifié mais on observe un pseudo superflu à sa suite (car il n'a pas été retiré dans le cas où on est sur la page de nos sujets suivis). C'est trivial à corriger.

![Le titre erroné (pareil pour les autres pages) : « Vos sujets suivis admin ».](https://user-images.githubusercontent.com/1417570/88379526-6b31a380-cda3-11ea-8390-27823d9b12b4.png)

2020-07-24 09:53 UTC, AmauryCarrade commented on templates/forum/find/topic.html
> +    {{ usr.username }}
```suggestion
    {% if followed_topics != None %}
        {% trans "Vos sujets suivis" %}
    {% else %}
        {% blocktrans with name=usr.username %}Sujets créés par {{ name }}{% endblocktrans %}
    {% endif %}
```

2020-07-24 09:53 UTC, AmauryCarrade commented on templates/forum/find/topic.html
> +    {{ usr.username }}
```suggestion
    {% if followed_topics %}
        {% trans "Vos sujets suivis" %}
    {% else %}
        {% blocktrans with name=usr.username %}Sujets créés par {{ name }}{% endblocktrans %}
    {% endif %}
```

2020-07-24 09:53 UTC, AmauryCarrade commented on templates/forum/find/topic.html
> +                {% trans "Aucun sujet public n’a été créé par" %} {{ usr.username }}.
Tant qu'à faire : 

```suggestion
                {% blocktrans with name=usr.username %}Aucun sujet public n’a été créé par {{ name }}.{% endblocktrans %}
```

2020-07-24 11:35 UTC, artragis commented on templates/forum/find/topic.html
>                  {% trans "Aucun sujet public n’a été créé par" %} {{ usr.username }}.
Ok.

2020-07-24 22:20 UTC, AmauryCarrade approved these changes
:heavy_check_mark: QA OK

~~J'attends juste de voir ce que voulais @artragis avant de fusionner~~ Je n'avais pas vu qu'il avait répondu

2020-07-24 22:21 UTC, AmauryCarrade commented on templates/forum/find/topic.html
>                  {% trans "Aucun sujet public n’a été créé par" %} {{ usr.username }}.
Donc tout est bon pour toi ?

2020-07-26 09:57 UTC, merged