Passage à zmarkdown 9.1
zestedesavoir/zds-site pull request #5825
Opened 2020-06-11 18:48 UTC by Situphen

Passage à zmarkdown 9.1

2020-06-11 18:52 UTC, TitiAlone commented
Alors, je suis censé faire un PR ici, il y a des changements à faire côté `zds-site` pour profiter pleinement de la version (`linenostart` et `hl_lines` en particulier). Bien sûr, c'est une mineure, elle peut donc être déployée telle quelle, sans casser quoi que ce soit (par rapport à la 9.0, qu'on a pas testé par ailleurs). A voir comment on souhaite organiser les MàJ.

2020-06-11 18:54 UTC, TitiAlone commented
Par ailleurs, a-t-on toujours besoin de `pm2` alors qu'on utilise la version incluse dans le `node_modules` ?

2020-06-11 19:58 UTC, Situphen commented
> Alors, je suis censé faire un PR ici, il y a des changements à faire côté `zds-site` pour profiter pleinement de la version (`linenostart` et `hl_lines` en particulier). Bien sûr, c'est une mineure, elle peut donc être déployée telle quelle, sans casser quoi que ce soit (par rapport à la 9.0, qu'on a pas testé par ailleurs). A voir comment on souhaite organiser les MàJ.

Je propose : cette PR reste telle quelle pour l'instant et on la supprimera quand ta PR sortira si elle n'a pas été mergée entre temps.

> Par ailleurs, a-t-on toujours besoin de `pm2` alors qu'on utilise la version incluse dans le `node_modules` ?

Bien vu ! J'ai vérifié et effectivement c'est inutile car c'est déjà installé par le paquet `zmarkdown` donc je l'ai enlevé.

2020-07-06 13:06 UTC, AmauryCarrade commented
Je reprend cette PR et vais étudier l'intégration de `linenostart` et `hl_lines` (ne pas fermer, donc !).

2020-07-06 14:56 UTC, AmauryCarrade commented
> Je reprend cette PR et vais étudier l'intégration de `linenostart` et `hl_lines` (ne pas fermer, donc !).

Finalement ce fut plus simple que prévu (cf. dernier commit). Le support est fonctionnel en l'état, sauf pour les blocs de code qui ont un fond de couleur (a priori, uniquement `console`), car il est nécessaire que le fond du code soit transparent.

En effet le surlignage est implémenté en utilisant un pseudo-élément attaché sur le numéro de la ligne (car seul ce dernier a l'info de la ligne surlignée) et placé _sous_ le code, afin que ce dernier reste sélectionnable.

D'un point de vue accessibilité : l'info que la ligne est surlignée n'est pas du tout disponible pour les lecteurs d'écran, mais je ne vois pas trop comment la donner (les numéros de lignes sont pas disponibles non plus je pense, mais je n'ai pas testé). Le contraste est bon sauf pour les commentaires où il est un peu faible, mais ce problème existe aussi sans surlignage : il faudrait donc ajuster leurs couleurs tout court.

### Contrôle qualité

1. Mettre à jour ZMD et lancer le serveur (`make zmd-install && make zmd-stop && make zmd-start && make run`).
2. N'importe où dans un champ de texte supportant Markdown, insérer du code avec des numéros de lignes ne débutant pas à 1 et des lignes surlignées.
3. Vérifier que les bonnes lignes sont sélectionnées, et que les numéros de ligne commencent à la bonne valeur.

Exemple de code pour tester, trouvé dans le hasard : 

``````md
```c linenostart=229 hl_lines=234,237
char *
__initstate (unsigned int seed, char *arg_state, size_t n)
{
  int32_t *ostate;
  int ret;
  __libc_lock_lock (lock);
  ostate = &unsafe_state.state[-1];
  ret = __initstate_r (seed, arg_state, n, &unsafe_state);
  __libc_lock_unlock (lock);
  return ret == -1 ? NULL : (char *) ostate;
}
```
``````

2020-07-06 15:50 UTC, AmauryCarrade commented
Le dernier commit ajoute le support complet pour les extrait de console, en plus du reste. On passe à zmd 1.9.2.

Les consoles sont également mieux intégrées.

![Aperçu de la nouvelle intégration et des surlignements & décalages de lignes.](https://user-images.githubusercontent.com/1417570/86612045-d0b61f80-bfaf-11ea-9ca4-516f0b14410f.png)


### Contrôle qualité

1. **Avant de mettre à jour ZMD** (donc avec l'ancienne version), lancer le serveur et créer un message, ou quelque chose, qui contienne un code de type `console` : 
    ``````markdown
    ```console
    $ sl
    * tchou tchou *
    ```
    ``````
2. Mettre à jour ZMD et relancer le serveur (`make zmd-install && make zmd-stop && make zmd-start && make run`).
3. Dans un autre message que celui de la première étape (qui doit resté intouché et non-mis-à-jour), insérer du code avec des numéros de lignes ne débutant pas à 1 et des lignes surlignées. Insérer également un code de type console avec ces fonctionnalités.
4. Vérifier : 
    - que les bonnes lignes sont sélectionnées, et que les numéros de ligne commencent à la bonne valeur ;
    - que le bloc de code console est correctement affiché (avec tout sur fond noir, y compris les numéros de ligne), et que les surlignages et numéros décalés marchent ;
    - que les blocs de code dans les messages utilisant l'ancienne version de ZMD (le message créé avant la mise à jour) sont toujours correctement affichés.

Exemple de code pour tester, trouvé dans le hasard : 

``````markdown
```c linenostart=229 hl_lines=234,237
char *
__initstate (unsigned int seed, char *arg_state, size_t n)
{
  int32_t *ostate;
  int ret;
  __libc_lock_lock (lock);
  ostate = &unsafe_state.state[-1];
  ret = __initstate_r (seed, arg_state, n, &unsafe_state);
  __libc_lock_unlock (lock);
  return ret == -1 ? NULL : (char *) ostate;
}
```

```console hl_lines=2
$ sl
* tchou tchou *
```
``````

2020-07-07 20:09 UTC, philippemilink commented
Rapport de QA
---------------

(j'allais dire que c'est toujours un plaisir de faire des QAs avec un protocole si bien détaillé, mais tu as oublié de dire qu'il fallait faire `make build-front` 😉  )

Presque OK.

Pour les lignes surlignées et le début de la numérotation différent de 1: pas de problème.

C'est pour l'extrait de console le problème: l'apparence n'est pas la même pour les messages écrits avant le passage à ZMD 9.1:
![image](https://user-images.githubusercontent.com/5911232/86836763-426c9700-c09e-11ea-8be3-2fe7812a3cf3.png)

En plus, il faudra penser à rebase.

2020-07-07 23:55 UTC, AmauryCarrade commented
C'est normal car il n'est pas possible d'appliquer le nouveau style sur les anciens rendus : ces derniers manquent d'une classe CSS pour ça, ajoutée par smd 1.9.2, et donc absente des messages rendus avec une version antérieure.

Les anciens rendus doivent rendre _correctement_ malgré tout (d'où cette partie de la QA), mais pas être _identiques_.

Demain je fais le rebase (et j'ajouterai aussi quelques _protips_ Markdown liés à ces nouvelles fonctionnalités de zmd, mais ça ne demandera pas de QA autre que Travis).

2020-07-08 07:53 UTC, artragis commented
@philippemilink tu peux considérer que le rendu que tu proposes est celui attendu. Merci de l'avoir noté.

@AmauryCarrade je t'invite à noter quelque part dans le projet (commentaire du CSS) que ce genre de comportement est en effet attendu comme ça on tombera pas des nues dans 9 mois et 27 jours et que quelqu'un viendra nous dire que ça fait ça alors qu'il s'attend à autre chose.

2020-07-08 11:08 UTC, AmauryCarrade commented
> @AmauryCarrade je t'invite à noter quelque part dans le projet (commentaire du CSS) que ce genre de comportement est en effet attendu comme ça on tombera pas des nues dans 9 mois et 27 jours et que quelqu'un viendra nous dire que ça fait ça alors qu'il s'attend à autre chose.

@artragis C'est fait ! J'ai également ajouté des astuces MD et mis la branche à jour par rapport à `dev`. Quand Travis sera contente, ce sera fusionnable, sauf avis divergents sur les astuces Markdown.

2020-07-08 11:24 UTC, artragis requested changes

2020-07-08 11:24 UTC, artragis commented on assets/scss/base/_source-code.scss
> +  // Old blocs only have a bkack background on the content, not the line numbers,
-bkak + black

2020-07-08 11:24 UTC, artragis commented on assets/scss/base/_source-code.scss
> +          color: hsl(0, 0%, 98%);  // TODO $white
pourquoi ne pas mettre une variable ici?

2020-07-08 11:24 UTC, artragis commented on assets/scss/base/_source-code.scss
> +      background-color: transparent;
gg

2020-07-08 11:24 UTC, artragis commented on assets/scss/base/_source-code.scss
> +// the background-color being overrided for new versions).
overridden

2020-07-08 11:28 UTC, AmauryCarrade commented on assets/scss/base/_source-code.scss
> +          color: hsl(0, 0%, 98%);  // TODO $white
La variable existe déjà dans #5835, d'où le commentaire TODO, mais je ne jugeais pas pertinent de créer la variable juste pour ça. Cela dit je ne m'y oppose pas, si vous trouvez que ce serait mieux.

2020-07-08 12:50 UTC, TitiAlone commented on assets/js/markdown-help.js
> +    'vous pouvez à la fois choisir à quel numéro démarrent les lignes et en surligner avec <code>```lisp linenostart=244 hl_lines=247,252</code> au début d\'un bloc de code.'
Pas sûr de moi, mais ces astuces ne devraient-elles pas commencer par des majuscules comme les autres ?

2020-07-08 12:52 UTC, AmauryCarrade commented on assets/js/markdown-help.js
> +    'vous pouvez à la fois choisir à quel numéro démarrent les lignes et en surligner avec <code>```lisp linenostart=244 hl_lines=247,252</code> au début d\'un bloc de code.'
J'ai tout passé en minuscules sur #5835 parce que le rendu est typographiquement meilleur : 

> **Astuce :** Pour ajouter une image, vous pouvez…
> **Astuce :** pour ajouter une image, vous pouvez…

Mais si on veut de la cohérence, je peux remettre les majuscules ici et ne les retirer que là bas. Ou pas du tout si vous tenez à l'incohérence typographique.

2020-07-08 12:54 UTC, TitiAlone commented on assets/js/markdown-help.js
> +    'vous pouvez à la fois choisir à quel numéro démarrent les lignes et en surligner avec <code>```lisp linenostart=244 hl_lines=247,252</code> au début d\'un bloc de code.'
Ben du coup je serais d'avis de les retirer partout

2020-07-08 12:55 UTC, TitiAlone commented on assets/js/markdown-help.js
> +    'vous pouvez à la fois choisir à quel numéro démarrent les lignes et en surligner avec <code>```lisp linenostart=244 hl_lines=247,252</code> au début d\'un bloc de code.'
Ah, je viens de comprendre que tu l'avais déjà fait ailleurs, désolé du coup

2020-07-08 14:24 UTC, AmauryCarrade commented on assets/js/markdown-help.js
> +    'vous pouvez à la fois choisir à quel numéro démarrent les lignes et en surligner avec <code>```lisp linenostart=244 hl_lines=247,252</code> au début d\'un bloc de code.'
Je pourrais les retirer ici aussi en soit (en déplaçant la modification), dans les deux cas c'est pas directement lié à la PR

2020-07-08 14:51 UTC, AmauryCarrade commented
Si ce n'est l'histoire de variable on est bon.

2020-07-08 17:48 UTC, merged