fix #5684
zestedesavoir/zds-site pull request #5837
Opened 2020-06-23 06:55 UTC by jeanlapostolle

Numéro du ticket concerné (optionnel) :
#5684

### Contrôle qualité
Mettre un utilisateur en Lecture Seule. Vérifier qu'il ne peut pas poster de messages et qu'il n'a pas le bouton "Nouveau sujet"

2020-06-23 11:05 UTC, AmauryCarrade requested changes
Salut et merci pour cette contribution !
J'ai laissé un petit commentaire sur le code mais c'est vraiment rien du tout.

Par contre cette PR casse un test, comme tu peux le constater tout en bas. En l'occurrence [le `test_frontend_alert_existence_other_pages`](https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/tests/tests.py#L859-L875), qui vérifie la présence du message en bas de page signalant qu'il y a une autre page.

Et en effet : quand je teste, je constate la présence du message « Vous êtes en lecture seule. Vous ne pouvez pas poster de messages. » _même quand je suis connecté via un compte sans restriction_ (j'ai testé en mettant `user` en LS, et en testant via `admin`). Plus généralement, il n'y a plus aucun bouton de création ou de formulaire d'envoi pour quiconque. Un peu _trop_ efficace :D .

### Le problème

En réalité le problème est simple : tu as confondu les deux objets qu'on a qui représentent un utilisateur. En effet on a : 
- d'un côté l'objet `User` de Django (celui exposé dans la variable `user`), qui ne contient que les éléments de base de l'utilisateur (nom, courriel, mot de passe, …), ce que Django gère lui-même pour nous ;
- d'un autre côté l'objet `Profile` (exposé via `user.profile`), qui est une sorte d'extension de `User` avec ce qui concerne ZdS : biographie, site web, préférences, … et aussi l'état de lecture seule.

Là où c'est fourbe, c'est qu'en cas d'appel à une méthode ou une propriété inconnue, le moteur de gabari de Django ne râle pas : il ignore et remplace par une valeur fausse. `user.can_write_now` _n'existe pas_ ; le moteur considère donc que c'est faux, et ainsi, `{% if not user.can_write_now %}` est toujours vrai.

### Le correctif

Le correctif est simple : `can_write_now` est défini, donc, [dans le `Profile`](https://github.com/zestedesavoir/zds-site/blob/dd29950fe4810dc9ee4870a863b8ee611a60bf45/zds/member/models.py#L368) ; il faut remplacer tous ses appels par `user.profile.can_write_now`.

### Et aussi

Je t'invite à _ajouter un test_ (tu peux prendre comme modèle le test lié plus haut) vérifiant que pour un utilisateur en lecture seule, le bon message est bien affiché, et _aussi_ que pour un utilisateur qui n'est _pas_ en lecture seule, le message n'est _pas_ affiché. Et de même pour les liens de création d'un sujet.

Il est tout aussi important de tester le fonctionnement de ce qu'on ajoute, que la non-régression du reste :) . (Et c'est aussi valable pour la QA.)

N'hésite pas à demander (ou, avant, à regarder dans [d'autres tests](https://github.com/zestedesavoir/zds-site/blob/251164ad4e559d85b8c4838dcf4e1ede42ccb4da/zds/member/tests/tests_models.py#L288-L313)) pour savoir comment mettre un membre en lecture seule en Python.

Enfin, il faudra _rebase_ pour pouvoir fusionner la PR.

Et merci encore !

2020-06-23 11:05 UTC, AmauryCarrade commented on templates/misc/message_form.html
> +</div>
Il serait mieux de respecter l'indentation ici

```suggestion
{% elif not user.can_write_now %}
    <div class="alert-box ico-after ico-alert light">
        {% trans "Vous êtes en lecture seule. Vous ne pouvez pas poster de messages." %}
    </div>
```

2020-07-06 20:54 UTC, philippemilink commented
Comment mentionné dans les commentaires de la PR #5845, il faudrait aussi empêcher les utilisateurs en LS de pouvoir masquer leurs messages.

2020-09-02 18:07 UTC, Situphen commented
Coucou @jeanlapostolle, penses-tu avoir le temps de continuer cette PR ? Si besoin d'aide n'hésites pas à nous demander ! :)

2020-09-03 05:56 UTC, jeanlapostolle commented
Oui, je la reprends après mes vacances ^^

2021-06-06 19:55 UTC, Arnaud-D commented
@jeanlapostolle Est-ce que tes vacances sont finies ? :D

2021-06-07 14:05 UTC, jeanlapostolle commented
Oui euh j'ai peut-être oublié du travail par ici ^^. Je vais devoir le délaisser, je n'ai même plus d'environnement de dév' pour ZDS et je n'ai pas le temps d'en refaire avant un certain temps.

2021-06-07 14:43 UTC, Arnaud-D commented
Je la déplace dans "En attente de reprise" alors. Tu pourras reprendre toi-même ta PR si le cœur t'en dit. Ou laisser quelqu'un la reprendre, mais c'est peu probable vu les habitudes de développement qu'on a. :-)

2022-01-22 22:49 UTC, SpaceFox commented
Pour info, le _fork_ est inaccessible pour je ne sais quelle raison, donc je ne connais pas de moyen simple de reprendre cette PR.

2022-01-23 14:05 UTC, philippemilink commented
> Pour info, le _fork_ est inaccessible pour je ne sais quelle raison, donc je ne connais pas de moyen simple de reprendre cette PR.

Oui, la branche semble ne plus exister.

Tu peux récupérer le code qui a déjà été fait avec : 
```bash
wget https://github.com/zestedesavoir/zds-site/pull/5837.patch
git apply 5837.patch
```
... et faire une nouvelle PR.

2022-01-23 16:16 UTC, Arnaud-D commented
Je ferme, ça a été repris par #6234.

2022-01-23 16:16 UTC, closed without merging