Permet de sauvegarder sans quitter
zestedesavoir/zds-site pull request #5865
Opened 2020-07-12 14:17 UTC by artragis

Cette PR a pour but de permettre de sauvegarder un contenu en cours d'édition sans être redirigé. Ce qui permet de ne pas perdre le travail en cours

fix #5819

### Contrôle qualité

1. make build-front
2. démarrer le serveur

#### Cas nominal 1 : ancien éditeur

- Créer un article
- Créer un nouvel extrait, observez que les deux boutons sont "Envoyer" et "Aperçu"
- Se placer sur l'éditeur historique
- Cliquer sur "Envoyer"
- Cliquer sur "Éditer l'extrait"
- Observer que nous avons maintenant 3 boutons "Aperçu", "Sauvegarder et continuer" et "Sauvegarder et quitter"
- Écrire quelque chose dans le champ texte et appuyer sur "sauvegarder et continuer"
- Pendant un temps les deux autres boutons sont désactivés puis redeviennent cliquables
- Mettre à jour la page
- Le texte proposé est bien celui qui a été sauvegardé

#### Cas nominal 2 : nouvel éditeur

- Créer un article
- Créer un nouvel extrait, observez que les deux boutons sont "Envoyer" et "Aperçu"
- Se placer sur le nouvel éditeur
- Cliquer sur "Envoyer"
- Cliquer sur "Éditer l'extrait"
- Observer que nous avons maintenant 3 boutons "Aperçu", "Sauvegarder et continuer" et "Sauvegarder et quitter"
- Écrire quelque chose dans le champ texte et appuyer sur "sauvegarder et continuer" ou bien sur Ctrl + S
- Pendant un temps les deux autres boutons sont désactivés puis redeviennent cliquables
- Mettre à jour la page
- Le texte proposé est bien celui qui a été sauvegardé

Aller dans l'historique des modifications et voir les modifications qui viennent d'être sauvegardées.
#### Non régression 

- vérifier qu'aucun bouton n'est apparu lorsqu'on veut poster un message sur le forum
- vérifier que les boutons de l'éditeur sont toujours opérationnels

2020-07-12 16:14 UTC, AmauryCarrade requested changes
Quelques petites remarques, mais dans l'ensemble c'est cool ! C'est une fonctionnalité plus qu'utile. Merci !

Je n'ai pas encore fait la QA, mais les instructions sont claires.

2020-07-12 16:14 UTC, AmauryCarrade commented on assets/js/editor-buton-save.js
> +function changeSubmitButtonState() {
Peut-être que `toggleSubmitButtonsState` serait un meilleur nom ?

2020-07-12 16:14 UTC, AmauryCarrade commented on assets/js/editor-buton-save.js
> +    }
```suggestion
    $(b).prop('disabled', !$(b).prop('disabled'))
```

2020-07-12 16:14 UTC, AmauryCarrade commented on assets/js/editor-buton-save.js
> +  console.log(data)
Journalisation oubliée.
```suggestion
```

2020-07-12 16:14 UTC, AmauryCarrade commented on assets/js/editor-buton-save.js
> +    success: (resultData) => {
Peut-être faudrait-il aussi vider le champ du message de commit ? Ou veut-on le dupliquer pour chaque enregistrement ?

2020-07-12 16:14 UTC, AmauryCarrade commented on assets/js/editor-new.js
> +      'Ctrl-S': () => {
J'aime beaucoup la possibilité de pouvoir `Ctrl + S`. :+1:

2020-07-12 16:14 UTC, AmauryCarrade commented on assets/js/editor-new.js
> +        console.log('override ' + $saveButton.length)
Journalisation oubliée.

```suggestion
```

2020-07-12 16:14 UTC, AmauryCarrade commented on zds/tutorialv2/views/contents.py
> +                                content_type='application/json')
On pourrait utiliser une `JsonResponse`, qui gère automatiquement les détails techniques (sérialisation, `Content-Type`, etc.) (il faudrait ajouter `from django.http import JsonResponse`). C'est aussi plus lisible, je trouve.

```suggestion
            return JsonResponse({'result': 'ok', 'last_hash': extract.compute_hash(),
                                 'new_url': extract.get_edit_url()})
```

2020-07-12 16:59 UTC, artragis commented on assets/js/editor-buton-save.js
> +    success: (resultData) => {
Je préfère ne pas changer car les gens n'y touchent pas énormément

2020-07-12 17:05 UTC, artragis commented on assets/js/editor-buton-save.js
> +function changeSubmitButtonState() {
ça devrait être bon

2020-07-12 17:06 UTC, artragis commented on zds/tutorialv2/views/contents.py
> +                                content_type='application/json')
C'est fait.

2020-07-12 17:21 UTC, AmauryCarrade commented on assets/js/editor-buton-save.js
> +    success: (resultData) => {
Ça se tient.

2020-07-12 17:27 UTC, AmauryCarrade requested changes
Un petit détail :) Et après ce sera testable je pense.

2020-07-12 17:27 UTC, AmauryCarrade commented on zds/tutorialv2/views/contents.py
> +                                            'new_url': extract.get_edit_url()}))
`JsonResponse` prend directement un dictionnaire (ou autres) en paramètres, pas une chaîne JSON, et se charge de la sérialisation :) .

```suggestion
            return JsonResponse({'result': 'ok', 'last_hash': extract.compute_hash(),
                                 'new_url': extract.get_edit_url()})
```

2020-07-12 19:20 UTC, AmauryCarrade requested changes

2020-07-12 19:20 UTC, AmauryCarrade commented on zds/tutorialv2/tests/tests_views/tests_content.py
> +        tutorial = PublishableContent.objects.find(pk=tutorial.pk)
Petite erreur que je n'avais pas vue et qui fait planter les tests ^^
```suggestion
        tutorial = PublishableContent.objects.get(pk=tutorial.pk)
```

2020-07-12 19:24 UTC, artragis commented on zds/tutorialv2/tests/tests_views/tests_content.py
> +        tutorial = PublishableContent.objects.find(pk=tutorial.pk)
c'est étrange ça, c'est sensé être fixé depuis un baille

2020-07-12 19:47 UTC, AmauryCarrade requested changes
:x: QA NOK. Enfin, l'essentiel fonctionne ; il y a juste un petit défaut d'affichage sur les formulaires de création d'extrait. Et si on utilise l'éditeur expérimental, là, c'est pas la joie.

### Cas nominal 1 : ancien éditeur

- :x: Créer un nouvel extrait, observez que les deux boutons sont "Envoyer" et "Aperçu"
  _Les deux boutons sont “Aperçu” et “Sauvegarder et quitter”._

### Cas nominal 2 : nouvel éditeur

- :x: Créer un nouvel extrait, observez que les deux boutons sont "Envoyer" et "Aperçu"
  _Les deux boutons sont “Aperçu” et “Sauvegarder et quitter”._
- :x: Mettre à jour la page. Le texte proposé est bien celui qui a été sauvegardé.
  _Le texte n'est pas mis à jour (avec le nouvel éditeur). Quand on inspecte la requête envoyée par “Sauvegarder et continuer” (ou Ctrl+S), on constate que le texte initial est envoyé, et non le texte courant. Je pense qu'il s'agit d'un soucis de synchronisation entre EasyMDE et le `textarea`._

Au delà de ça, c'est tout bon et je n'ai pas constaté de régressions. :)

2020-07-12 20:08 UTC, artragis commented
J'ai trouvé un moyen de forcer la synchro mais je suis pas contre une revue pour ça car je sais pas si c'est normal de faire comme ça.

SInon, pour les label des boutons, c'est fixé.

2020-07-12 22:09 UTC, AmauryCarrade commented
Pour la revue sur l'éditeur, j'invoque @Situphen ou @firm1 qui ont travaillé sur l'éditeur ; ce n'est pas mon cas et je crains de manquer d'un avis éclairé.

2020-07-12 22:16 UTC, AmauryCarrade approved these changes
Sinon, me concernant, :heavy_check_mark: QA OK

2020-07-13 18:20 UTC, A-312 commented on assets/js/editor-buton-save.js
> +'use strict'
Il manque un `t` au nom du fichier pour faire `button`

2020-07-13 18:20 UTC, A-312 commented on assets/js/editor-buton-save.js
> +  }
La fonction que tu cherches doit être `easyMDE.autosave()` ou `window.editors[textarea.id].autosave()`

2020-07-13 18:36 UTC, artragis commented on assets/js/editor-buton-save.js
> +  }
autosave je flush pas tout dans le localstore?

2020-07-13 18:37 UTC, artragis commented on assets/js/editor-buton-save.js
> +'use strict'
BIen vu

2020-07-13 18:43 UTC, artragis commented on assets/js/editor-buton-save.js
> +  }
ça ne semble pas du tout fonctionner: 

![autosave](https://user-images.githubusercontent.com/1523653/87341228-8d2c5a00-c549-11ea-8f1a-8bc82a31b68c.PNG)

2020-07-13 19:45 UTC, A-312 commented on assets/js/editor-buton-save.js
> +  }
J'ai compris de travers, ça doit être : `window.editors[textarea.id].codemirror.save()`

2020-07-14 07:52 UTC, artragis commented on assets/js/editor-buton-save.js
> +  }
là, en effet, ça fonctionne

2020-07-14 08:10 UTC, merged