Gére les espaces insécables dans l'aperçu de mise en une
zestedesavoir/zds-site pull request #5936
Opened 2020-10-02 19:09 UTC by philippemilink

Fix #5903

Suite du commit 58c858452067ca14dcec3b5678e1fe85d4c0eb0e (voir la PR #5883)

### Contrôle qualité

Reconstruire le front: `make build-front`

1. Se connecter en tant qu'administrateur ;
2. Accéder à la page d'un contenu ;
3. Mettre ce contenu en Une ;
4. Mettre le titre suivant : « `Comment alerter les secours ?` »: le point d'interrogation reste sur la même ligne.

2020-10-05 11:37 UTC, AmauryCarrade requested changes
:x: QA NOK : c'est nickel pour le titre mais la description n'est pas traitée. C'est peut-être voulu ?

![image](https://user-images.githubusercontent.com/1417570/95075097-ea324900-070f-11eb-84b3-81d8ad210a4a.png)

2020-10-05 11:37 UTC, AmauryCarrade commented on assets/js/featured-resource-preview.js
> +      .replace(' :', '&nbsp;:');
Pas de point-virgule.
```suggestion
      .replace(' :', '&nbsp;:')
```

2020-10-09 20:05 UTC, philippemilink commented on assets/js/featured-resource-preview.js
> +      .replace(' :', '&nbsp;:');
Fait. Mais ça m'étonne que le point-virgule soit carrément interdit...

2020-10-11 12:13 UTC, firm1 commented
## Rapport de QA 

J'ai le même problème que @AmauryCarrade ci-dessous.

![Capture d’écran de 2020-10-11 14-12-17](https://user-images.githubusercontent.com/6066015/95678271-dbdea400-0bcb-11eb-9b12-42ae62f5cfe7.png)

Le titre est bon mais pas la description.

2020-10-11 14:04 UTC, philippemilink commented
> Le titre est bon mais pas la description.

Ah, je n'avais pas vérifié que sur la page d'accueil aussi la description s'affichait bien.


> D'ailleurs j'ai une regression qui est apparue. L'aperçu temps réel du titre ne fonctionne plus pendant la création de la Une (ça marche pourtant pour le type et les auteurs).

Je n'arrive pas à reproduire le problème, _chez moi ça fonctionne_...

2020-10-11 15:50 UTC, firm1 commented
# Rapport de QA

*QA OK*

Je ne sais pas ce qu'il manque mais je n'ai pas le bouton de merge allumé.

2020-10-11 16:12 UTC, merged