Ne pas afficher `msg-are-hidden` pour 1er message
zestedesavoir/zds-site pull request #5946
Opened 2020-10-05 13:39 UTC by viki53

Fixe #5916

Si le premier message d'une conversation est caché, il faut laisser le message apparent (avec les styles adéquats) au lieu du message raccourci.

### Contrôle qualité

Ouvrir un sujet dont le premier message est masqué. Il devrait être déplié, sans impacter le reste des messages cachés.

J'ai également testé le cas où les deux (ou plus) premiers messages sont masqués : le premier apparaît mais pas le second.

2020-10-05 14:58 UTC, AmauryCarrade approved these changes
:heavy_check_mark: QA OK

Par contre j'ai remarqué que quand tous les messages d'un sujet sont masqués, on ne peut plus les réafficher quand l'antiflood est actif.

![image](https://user-images.githubusercontent.com/1417570/95095988-047a2000-072c-11eb-97d2-2bef605d3e8a.png)

2020-10-05 15:03 UTC, AmauryCarrade requested changes
En fait le soucis remonté ne se présente pas quand je teste ton autre PR, donc ça semble dépendant. Donc :x: QA NOK.

2020-10-05 15:14 UTC, viki53 commented
Oui les deux PR se cumulent, c'est les marges qui cachent le message derrière l'alert, c'est réglé par l'autre PR ça 🙂

2020-10-06 11:32 UTC, AmauryCarrade approved these changes
J'ai testé les deux PR en même temps, en les fusionnant dans une branche temporaire chez moi, et c'est tout bon, effectivement. :)

2020-10-06 11:32 UTC, merged