suppression de jquery du fichier d'accessibilité et correction de bugs
zestedesavoir/zds-site pull request #5965
Opened 2020-10-11 15:41 UTC by firm1

Cette PR permet de retirer la dépendance jquery sur le fichier `accessibility-links.js`, et en profite pour corriger les bugs découverts qui est : si on essaye d'acceder à la zone de recherche de la page d'accueil ou la page de la bibliothèque depuis le menu d'accessibilité, on est pas renvoyé au bon endroit.

Numéro du ticket concerné (optionnel) : #5786 

### Contrôle qualité

Par exemple :

- Avant de lancer le site `make run-back` assurez-vous d'avoir buildé le front `make build-front`
- Lancez le site `make run-back`
- Allez sur la page d'accueil et tenter d'acceder au menu d'accessibilité (appuyer sur la touche tab après avoir raffraichi votre fenêtre) et vérifiez que les 3 liens fonctionnent bien.

Ci-dessous une capture du menu d'accessibilité 

![Capture d’écran de 2020-10-11 17-40-21](https://user-images.githubusercontent.com/6066015/95683029-fe32ea80-0be8-11eb-832f-07ffb595843e.png)

2020-10-11 19:46 UTC, artragis requested changes

2020-10-11 19:46 UTC, artragis commented on assets/js/accessibility-links.js
> +    var style = window.getComputedStyle(el)
Il me semble qu'on préfère utiliser `const` maintenant

2020-10-11 19:46 UTC, artragis commented on assets/js/accessibility-links.js
> +    element.addEventListener('focus', function() {
pourquoi faire un mix entre arrow functions et les anciennes manières de déclarer?

2020-10-11 19:46 UTC, artragis commented on assets/js/accessibility-links.js
> +      var link = this.getAttribute('href')
Idem, on préfère utiliser `const`

2020-10-11 21:25 UTC, firm1 commented on assets/js/accessibility-links.js
> +    var style = window.getComputedStyle(el)
bien vu.

2020-10-11 21:25 UTC, firm1 commented on assets/js/accessibility-links.js
> +      var link = this.getAttribute('href')
bien vu.

2020-10-12 08:34 UTC, artragis approved these changes

2020-10-18 08:16 UTC, artragis commented
QA OK

2020-10-18 08:16 UTC, merged