suppression de jquery du fichier close-alert-box.js
zestedesavoir/zds-site pull request #5969
Opened 2020-10-11 20:33 UTC by firm1

Cette PR supprime jquery du fichier `close-alert-box.js`

Numéro du ticket concerné (optionnel) : #5786

### Contrôle qualité

- Avant de lancer le site `make run-back` assurez-vous d'avoir buildé le front `make build-front`
- Lancez le site `make run-back`
- Vérifiez les endroits ou cette fonction est utilisée sur le site às avoir:
    - fermer la boite d'alerte dans l'éditeur de texte qui présente l'aide markdown
    - fermer les boîtes d'alertes qui surviennent par exemple lorsqu'on réserve un tutoriel

![Capture d’écran de 2020-10-11 22-32-23](https://user-images.githubusercontent.com/6066015/95689529-b4aac580-0c11-11eb-8c11-e59c84168c4c.png)
![Capture d’écran de 2020-10-11 22-32-39](https://user-images.githubusercontent.com/6066015/95689532-b70d1f80-0c11-11eb-85db-749ac60e5ed6.png)

2020-10-18 08:18 UTC, artragis commented on assets/js/close-alert-box.js
> +    setTimeout(function() {
à quoi sert le setTimeOut ici?

2020-10-19 20:26 UTC, Situphen commented on assets/js/close-alert-box.js
> +    setTimeout(function() {
Je n'ai pas l'impression que ce soit utile ici. Si jamais c'est pour remplacer la fonction `slideUp` de jQuery alors il faudrait plutôt la mettre à l'intérieur du `addEventListener` avec une valeur à 150 au lieu de 1000.

2020-10-19 21:25 UTC, firm1 commented on assets/js/close-alert-box.js
> +    setTimeout(function() {
A la base je l'ai mis pour m'assurer que tout soit vraiment chargée (bizarement le `domcontentloaded` ne suffisait pas). Si vouw avez des idées, je suis preneur

2020-10-21 13:01 UTC, AmauryCarrade commented on assets/js/close-alert-box.js
> +    setTimeout(function() {
Le problème ici, c'est que l'élément est créé _après_ l'exécution de ce script, par un autre qui a la mauvaise idée d'avoir un fichier qui arrive après dans l'ordre alphabétique. Utiliser un `setTimeout` n'est pas idéal car si pour quelque raison (ordinateur peu puissant, latence…) les scripts mettent plus de 100ms à s'exécuter, les bannières ne pourront être fermées.

J'ai trois solutions à proposer pour régler ce problème.

1. Écouter sur `load` au lieu de `DOMContentLoaded`.  
    L'événement `load` est diffusé lorsque tout est chargé (tous les scripts, toutes les images, etc.). À ce moment, le script qui injecte les bannières aura tourné, et donc l'élément sera disponible.
2. S'arranger pour que ce script soit exécuté en dernier.  
    Pour ça il faut modifier la configuration de Gulp afin qu'il ajoute ce script aux autres systématiquement en dernier. Ça se fait, mais il faut le documenter dans le code (comme on le fait déjà avec les scripts qui sont explicitement injectés en premier).
3. Utiliser de la délégation d'événements.  
    Ça consiste à écouter _tous_ les événements de clic, et à les filtrer de manière à ignorer ce qui ne colle pas à ce qu'on veut. Dans ce cas présent, ça ressemblerait à quelque chose de ce genre (non testé).
    
    ```js
    document.addEventListener('click', e => {
        if (!e.target.classList.contains('close-alert-box')) return
        e.target.parentElement.remove()
        e.preventDefaut()
    })
    ```

2020-10-21 13:02 UTC, AmauryCarrade requested changes
Ça fonctionne en l'état mais j'apprécierais que le code soit amélioré, au niveau des commentaires qui ont été fait sur le `setTimeout`.

2020-11-07 08:45 UTC, firm1 commented
Du coup j'ai pris en compte vos remarques, j'ai opté pour l'option 3 de @AmauryCarrade qui me parait plus efficace niveau maintenance et vieillissement du code.

2020-12-17 21:28 UTC, Situphen approved these changes
**QA OK !**

2020-12-17 21:28 UTC, merged