Afficher la liste des commentaires d'un membre
zestedesavoir/zds-site pull request #5974
Opened 2020-10-18 06:11 UTC by firm1

Cette PR (qui reprend la base commencée par @Situphen ) permet d'afficher la liste des commentaires d'un membre. C'était déjà le cas pour le forum, mais ça n'a jamais été le cas pour les commentaires de publications.

Numéro du ticket concerné (optionnel) : #5963 

### Contrôle qualité

- Démarrez le site
- Allez sur la page de profil d'un membre ayant posté des commentaires sur un contenu (`user` par exemple) et vérifiez que vous avez le bouton "X commentaires publiés" (cf. capture ci-dessous)

![Capture d’écran de 2020-10-18 08-08-13](https://user-images.githubusercontent.com/6066015/96360012-37071e00-1119-11eb-8094-98875db94dc2.png)

- Cliquez sur ce fameux bouton, et vérifiez que vous avez accès à la page qui liste effectivement les commentaires (cf. capture ci-dessous)

![Capture d’écran de 2020-10-18 08-10-33](https://user-images.githubusercontent.com/6066015/96360036-6c137080-1119-11eb-95ac-bda9825dfd5a.png)

2020-10-19 20:16 UTC, Situphen requested changes

2020-10-19 20:16 UTC, Situphen commented on templates/tutorialv2/comment/list.html
> +            {% trans "Aucun commentaire n’a été content_reactioné par" %} {{ usr.username }}.
```suggestion
            {% trans "Aucun commentaire n’a été posté par" %} {{ usr.username }}.
```

Je vois que tu as remplacé vraiment toutes les occurrences de `post` par `content_reaction` ! :D

2020-11-07 08:14 UTC, firm1 commented
Suggestion de @Situphen pris en compte.

2020-11-07 12:37 UTC, Arnaud-D commented
QA NOK :x: 

Quand un membre a des commentaires postés mais aucun contenu publié, le cadre "Contenus" ne s'affiche pas, et donc on ne peut pas accéder aux commentaires du membre en question.

Je pense que la solution sera de modifier cette ligne : `{% if public_tutos_count > 0 or articles_public_count > 0 or opinions_public_count > 0 %}` dans le template.

2020-11-07 14:36 UTC, firm1 commented
Merci @Arnaud-D pour la QA, tu as tapé dans le mil, le problème était justement à ce niveau.

2020-11-07 16:06 UTC, Arnaud-D commented
QA OK :heavy_check_mark:

2020-11-07 16:07 UTC, merged