Corrige le style et la semantique lors de la desinscription
zestedesavoir/zds-site pull request #5996
Opened 2020-11-23 06:43 UTC by ToxicScorpius

Traite l'issue #5716 

J'ai ajouté une balise `<samp>` pour améliorer la sémantique de la page, et modifié le style de la balise `<kbd>`.

# Q/A

- Se connecter comme utilisateur lambda
- Se rendre dans les Paramètres -> Désinscription

Je m'y suis prise comme un bourrin avec le style, mais ça marche. Je ne sais pas si ça risque de casser quelque chose dans le reste du site, mais vu que c'est juste une modification du style de `<kbd>` je pense que les chances sont faibles.

Je souhaiterai avoir une couleur plus rougeatre pour le texte, pour qu'il puisse bien correspondre au bouton auquel il fait référence, vous en pensez quoi ?

Merci pour votre temps !

2020-11-23 11:05 UTC, AmauryCarrade requested changes
Merci ! J'ai un commentaire sur ta façon de gérer les styles, afin d'éviter de la duplication de code.

> Je m'y suis prise comme un bourrin avec le style, mais ça marche. Je ne sais pas si ça risque de casser quelque chose dans le reste du site, mais vu que c'est juste une modification du style de `<kbd>` je pense que les chances sont faibles.

Avec le CSS qu'on a, _on ne sait jamais_. :p 

> Je souhaiterai avoir une couleur plus rougeâtre pour le texte, pour qu'il puisse bien correspondre au bouton auquel il fait référence, vous en pensez quoi ?

On pourrait, il ne faudrait juste pas qu'on confonde avec un bouton mais il y a peu de risque je pense. Le plus simple, si tu suis ce que je propose plus bas, c'est de modifier le style des éléments `kbd` existants pour ajouter une variation via une classe supplémentaire : 

```scss
kbd {
    // code existant

    &.is-red {
        // Code qui change sa couleur (le reste étant inchangé)
    }
}
```

…et ajouter la classe à l'élément `kbd` utilisé ici.

```html
<kbd class="is-red"><samp>…</samp></kbd>
```

Pour la couleur, [tu peux en piocher une ici](https://zestedesavoir.github.io/normes-graphiques/#couleurs). Le plus simple si tu veux changer ça c'est d'attendre que la PR normes soit fusionner et de rebaser sur `dev` après, tu auras accès à toutes les variables SCSS des couleurs etc.

2020-11-23 11:05 UTC, AmauryCarrade commented on assets/scss/layout/_content.scss
> +    kbd {
Je vois que tu as choisi de dupliquer le style de l'élément `kbd`. Je ne suis pas fan de cette solution, ça créé du code dupliqué plus difficile à maintenir à l'avenir.

Tous les styles des contenus sont disponibles via `@import "base/content" que l'on aperçoit plus haut. Actuellement, le CSS ressemble à ça, ce qui limite les éléments dans lesquels ont peut appliquer ces styles.

```scss
.main .content-container {

    // …

    .article-content,
    .message-content {
        margin-bottom: 20px;
        color: #424242;
        @import "base/content";
    }
}
```

On pourrait ou juste réutiliser l'une de ces classes dans le HTML sans toucher au CSS (tous les styles seraient automatiquement appliqués), ou les remplacer par une nouvelle classe plus générique (par exemple `.content`) que l'on pourrait utiliser dés que l'on veut un élément avec des styles de texte rédigé comme cela — ce qui serait mieux pour l'avenir mais plus compliqué à mettre en place (plein de changements partout pour remplacer les classes existantes).

Dans un premier temps, réutiliser l'existant est tout de même plus simple :) .

2020-11-24 11:15 UTC, AmauryCarrade commented
J'ai pas QA mais ça me semble pas trop mal. Par contre, il va falloir attendre #5922 pour pouvoir intégrer les couleurs et autres en tant que variables, et éventuellement utiliser un `.content` générique s'il y en a un d'ici là (sinon pas grave ça peut attendre ça).

2020-12-17 21:09 UTC, Situphen commented
@ToxicScorpius Il y a des conflits à résoudre par rapport à upstream/dev étant donné que la PR qui met en place Black a été fusionnée et à modifié le style des fichiers Python. :)

2021-02-13 15:09 UTC, AmauryCarrade commented
Quand tu reprendras cette PR, il faudra rebaser pour inclure les modifications de la norme, puis appliquer cette dernière :) .

2021-06-06 20:16 UTC, Arnaud-D commented
Je repasse à "En attente de QA". J'ai essayé de le faire, mais je me suis embrouillé et je lâche l'affaire pour le moment. :)

2021-09-19 09:35 UTC, Arnaud-D commented
QA NOK :x: 

Alors on peut faire le rebase sans trop de problèmes, mais le bouton rouge foire (Firefox, dernière version) ; je ne vois pas trop pourquoi cependant, au vu des modifs...
![image](https://user-images.githubusercontent.com/35631001/133922369-821f679b-f14e-4ff4-82ea-4f7a9a0bfc57.png)

2022-10-06 13:53 UTC, Arnaud-D commented
Reprise par #6396.

2022-10-06 13:53 UTC, closed without merging