Améliore la connexion aux réseaux sociaux
zestedesavoir/zds-site pull request #6003
Opened 2020-12-13 23:32 UTC by Situphen

- Un peu de nettoyage
  - Supprime `python-social-auth` qui n'est plus utilisé
  - Supprime `SOCIAL_AUTH_GOOGLE_OAUTH2_USE_DEPRECATED_API` qui n'est plus utilisé
- Redirige les membres après leur connexion
  - Si on clique sur le bouton "Connexion" depuis une page en particulier, alors on est redirigé vers celle-ci après s'être connecté (ceci existe déjà pour la connexion standard mais pas pour la connexion avec les réseaux sociaux)
  - [Documentation en question](https://python-social-auth.readthedocs.io/en/latest/use_cases.html#return-the-user-to-the-original-page)
- Un seul compte peu importe le moyen de connexion
  - Si un utilisateur se connecte avec Facebook et qu'il y a déjà un compte avec la même adresse de courriel (créé avec l'inscription standard ou un autre réseau social) alors on ne crée pas un nouveau compte mais on associe le compte Facebook avec le compte existant
  - [Documentation en question](https://python-social-auth.readthedocs.io/en/latest/use_cases.html#associate-users-by-email)
    > For example, if a user signed up with their Facebook account, then logged out and next time tries to use Google OAuth2 to login, it could be nice (if both social sites have the same email address configured) that the user gets into their initial account created by Facebook backend.
    > 
    > This feature is disabled by default because it’s not 100% secure to automate this process with all the backends. Not all the providers will validate your email account and others users could take advantage of that.
    > 
    > Take for instance User A registered in your site with the email foo@bar.com. Then a malicious user registers into another provider that doesn’t validate their email with that same account. Finally this user will turn to your site (which supports that provider) and sign up to it, since the email is the same, the malicious user will take control over the User A account.

2020-12-17 22:05 UTC, AmauryCarrade commented
> Un seul compte peu importe le moyen de connexion 
> […]

Comme on ne supporte que des moyens de connexion qui vérifient l'adresse de courriel, pour nous, le problème de sécurité ne s'applique pas — donc, bonne idée, et j'approuve :) .

2021-11-28 16:38 UTC, Arnaud-D commented
J'ai essayé de tester, mais sans succès. Je ne sais pas si ça ne marche pas ou si j'ai mal compris quelque chose.

Google m'indique :

```
Erreur 400 : redirect_uri_mismatch

Vous ne pouvez pas vous connecter à cette appli, car elle ne respecte pas le règlement OAuth 2.0 de Google.

Si vous êtes le développeur de l'appli, enregistrez l'URI de redirection dans Google Cloud Console.
```
Des idées ?

2021-12-28 14:36 UTC, philippemilink commented
Rapport de QA
---------------

OK pour Google, OK pour la redirection vers la où on était avant de se connecter.

Facebook me sort une erreur :
> Sorry, something went wrong.
> 
> We're working on getting this fixed as soon as we can.

Peut-être parce qu'on n'a pas dans nos environnements de dev [les identifiants nécessaires pour l'API de Facebook](https://github.com/zestedesavoir/zds-site/pull/6003/files#diff-4dc8a285e13d167d704f4662e902ca7d507c7d8f5375d24b251d51ea84b59f61L31) ?


Pour Google, j'ai fait ça en navigation privée, en n'étant pas connecté avant à Google (donc j'ai du me connecter à mon compte Google au moment de me connecter à ZdS avec Google).

> Comme on ne supporte que des moyens de connexion qui vérifient l'adresse de courriel, pour nous, le problème de sécurité ne s'applique pas — donc, bonne idée, et j'approuve :) .

Ce serait bien d'écrire quelque part que les moyens de connexion qu'on propose doivent vérifier l'adresse mail. Pour s'en souvenir le jour où on voudra ajouter un moyen de connexion qui ne vérifie pas l'adresse mail !

2021-12-28 17:33 UTC, Situphen commented
C'est rebasé ! J'ai fait un tour dans les paramètres pour développeur du compte Facebook de ZDS et j'ai fait un peu de nettoyage, donc ça devrait mieux fonctionner. Je t'envoie un message en privé avec le détail et on pourra décider au niveau des clés ce qu'on peut rendre publique ou partager avec les autres. :)

2021-12-29 20:52 UTC, philippemilink requested changes
Rapport de QA
---------------

### Google

Google renvoie une erreur lorsqu'on accède à notre version locale de ZdS avec l'adresse http://localhost:8000/. Si on utilise http://127.0.0.1:8000/, ça fonctionne.

Donc la connexion avec Google fonctionne. ✔️ 

### Facebook

J'ai utilisé les identifiants que @Situphen m'a transmis en privé. Là c'est l'inverse, 127.0.0.1 ne fonctionne pas, mais localhost fonctionne. Dans tous les cas, Facebook n'a pas l'air content qu'on n'ait pas de https sur notre version locale.

Au final, ça fonctionne même si le compte Facebook créé exprès avec pour nom `Clémentine de Noël` donne comme pseudo `ClmentinedeNol`. Je ne sais pas si on considère ça comme un bug ou non.


### Revue de code


>> Comme on ne supporte que des moyens de connexion qui vérifient l'adresse de courriel, pour nous, le problème de sécurité ne s'applique pas — donc, bonne idée, et j'approuve :) .
>
> Ce serait bien d'écrire quelque part que les moyens de connexion qu'on propose doivent vérifier l'adresse mail. Pour s'en souvenir le jour où on voudra ajouter un moyen de connexion qui ne vérifie pas l'adresse mail !

Ce serait bien que ce soit fait.

On pourrait sans doute aussi en profiter pour supprimer les variables `SOCIAL_AUTH_TWITTER_KEY` et `SOCIAL_AUTH_TWITTER_SECRET`, maintenant inutiles.

2022-01-08 21:31 UTC, Situphen commented
J'ai supprimé les variables pour Twitter et j'ai ajouté un peu de documentation, qu'en penses-tu ?

> Là c'est l'inverse, 127.0.0.1 ne fonctionne pas, mais localhost fonctionne.

Dans les paramètres des développeurs de Facebook, je n'ai pas eu la possibilité de mettre un nom de domaine, d'où l'adresse IP. Il faudrait que j'uniformise un peu ça.

> Au final, ça fonctionne même si le compte Facebook créé exprès avec pour nom `Clémentine de Noël` donne comme pseudo `ClmentinedeNol`. Je ne sais pas si on considère ça comme un bug ou non.

Il faudra investiguer sur l'origine de ce comportement car ce n'est clairement pas souhaitable, mais j'ai essayé sur `upstream/dev` et j'ai le même comportement donc ça ne vient pas de ma PR je pense.

2022-01-09 13:42 UTC, philippemilink commented on doc/source/back-end/member.rst
> +Si un visiteur se connecte une première fois avec son compte Google puis la fois suivante avec son compte Facebook, et si les deux comptes sont liées à la même adresse de courriel, alors les deux com
```suggestion
Si un visiteur se connecte une première fois avec son compte Google puis la fois suivante avec son compte Facebook, et si les deux comptes sont liés à la même adresse de courriel, alors les deux comptes devraient être liés en théorie au même compte Zeste de Savoir. Pour cette raison, si d'autres services venaient à être ajouter dans le futur, il faut s'assurer au préalable que ceux-ci valident bien l'adresse de courriel lors de l'inscription, sinon une usurpation du compte Zeste de Savoir serait possible.
```

2022-01-09 14:19 UTC, philippemilink commented
Une petite typo.

Sinon :

> J'ai supprimé les variables pour Twitter et j'ai ajouté un peu de documentation, qu'en penses-tu ?

Ok pour la documentation, mais je pensais plutôt à un commentaire au niveau des paramètres `SOCIAL_AUTH_....` dans `zds/settings/abstract_base/requirements.py` (bref là où on irait ajouter des paramètres le jour où on ajoutera un moyen de connexion) pour rappeler qu'il faut que le fournisseur de connexion vérifie bien les adresses mails (la doc c'est bien, mais malheureusement on ne pensera probablement pas à la consulter le jour J).


> > Là c'est l'inverse, 127.0.0.1 ne fonctionne pas, mais localhost fonctionne.
> 
> Dans les paramètres des développeurs de Facebook, je n'ai pas eu la possibilité de mettre un nom de domaine, d'où l'adresse IP. Il faudrait que j'uniformise un peu ça.

J'attends que tu uniformises pour retester et merger ou bien on merge directement ? (dans ce cas, peut-être préciser dans la doc les URLs qui vont bien)

 
> > Au final, ça fonctionne même si le compte Facebook créé exprès avec pour nom `Clémentine de Noël` donne comme pseudo `ClmentinedeNol`. Je ne sais pas si on considère ça comme un bug ou non.
> 
> Il faudra investiguer sur l'origine de ce comportement car ce n'est clairement pas souhaitable, mais j'ai essayé sur `upstream/dev` et j'ai le même comportement donc ça ne vient pas de ma PR je pense.

Ok, tu peux ouvrir un ticket pour qu'on garde le problème à l'esprit ?

2022-03-28 21:42 UTC, Situphen commented
J'ai mis à jour ma branche par rapport à `upstream/dev` et créé le ticket concernant la suppression des accents dans le pseudo lors de l'inscription avec Facebook. J'ai ajouté un commentaire dans les paramètres concernant l'ajout de nouveaux fournisseurs.

J'ai regardé à nouveau pour pouvoir se connecter en local avec `localhost` pour Google et `127.0.0.1` pour Facebook mais je n'ai pas réussi à faire en sorte que cela fonctionne. Les deux services ont des restrictions différentes à ce niveau j'ai l'impression ! J'ai donc ajouté une ligne à ce sujet dans la documentation.

2022-05-14 20:56 UTC, Arnaud-D commented
Si je comprends bien, un rebase et c'est bon ici, vu que c'est déjà QAisé ?

2022-06-16 16:59 UTC, Arnaud-D commented
@philippemilink, @Situphen : un rebase et c'est bon ici ou il reste des choses à vérifier ?

2022-06-17 20:09 UTC, Situphen commented
> @philippemilink, @Situphen : un rebase et c'est bon ici ou il reste des choses à vérifier ?

Il me semble qu'on est bon pour la fusion si @philippemilink confirme que j'ai bien répondu à ses attentes :)

2022-06-19 16:39 UTC, philippemilink approved these changes
Je viens de tester sur la bêta la version dev et cette PR, les connexions avec Facebook et Google fonctionnent de la même façon.

**QA OK** :heavy_check_mark:

2022-06-19 16:39 UTC, merged