Amélioration du fonctionnement des sessions
zestedesavoir/zds-site pull request #6021
Opened 2021-02-04 19:51 UTC by Situphen

Amélioration du fonctionnement des sessions

2023-05-24 21:19 UTC, philippemilink requested changes
Il faut faire un petit rebase.

Est-ce que tu pourrais ajouter des tests, stp ? (ne serait-ce que pour s'assurer que les URLs que tu rajoutes peuvent être appelées correctement, pas forcément besoin de vérifier que ce qui est affiché est correct)

2023-05-24 21:19 UTC, philippemilink commented on zds/middlewares/managesessionsmiddleware.py
> +        if user.is_authenticated:
```suggestion
        if user is not None and user.is_authenticated:
```

2023-06-05 18:22 UTC, Situphen reviewed
Modifications :
- `if user is not None and user.is_authenticated`
- `if session_key and session_key != self.request.session.session_key`
- ajout des tests

2023-06-08 10:36 UTC, philippemilink requested changes
Je viens de faire une revue de code un peu plus poussée (j'ai même été un peu tatillon). Une fois que les points que j'ai soulevés seront corrigés, je testerai, mais ça me semble déjà pas mal.

2023-06-08 10:36 UTC, philippemilink commented on requirements.txt
> +ua-parser==0.16.1
Est-ce qu'on a vraiment besoin de lister `ua-parser` dans `requirements.txt` ? Je viens de tester, en installant `user-agents`, ça installe automatiquement la dépendance `ua-parser`.

Ce serait utile de le préciser si on  a besoin d'une version précise de la dépendance, mais là ça ne me semble pas être nécessaire.

2023-06-08 10:36 UTC, philippemilink commented on templates/member/settings/sessions.html
> +    {% include "misc/paginator.html" with position="top" %}
Je ne pense pas qu'on ait besoin de pagination pour lister les sessions, on devrait rarement avoir tellement de sessions actives que ça demande une pagination :) M'enfin, puisque c'est fait :)

2023-06-08 10:36 UTC, philippemilink commented on templates/member/settings/sessions.html
> +                                </form>
Puisque je suis tatillon pour cette revue de code, ce bloc est indenté avec une tabulation en trop :)

2023-06-08 10:36 UTC, philippemilink commented on zds/member/views/sessions.py
> +        for session in Session.objects.iterator():
Je n'aime pas vraiment `Session.objects.iterator()`, parce que si je comprends bien, ça veut dire récupérer toutes les sessions existantes en base de données et les parcourir. Sur la prod, la table `django_session` contient 25729 entrées, donc l'affichage de cette page risque d'être long.

J'ai bien compris que par défaut les données des sessions sont sérialisées en base de données, donc tu ne peux pas filtrer par utilisateur. Mais en fouillant dans la documentation, j'ai trouvé [ça](https://docs.djangoproject.com/fr/3.2/topics/http/sessions/#example) qui semble dire que tu peux surcharger le modèle correspondant aux sessions pour y inclure l'ID de l'utilisateur.

2023-06-08 10:36 UTC, philippemilink commented on zds/member/views/sessions.py
> +
Tu peux ajouter : 
```py
http_method_names = ["post"]
```
pour s'assurer qu'on ne puisse accéder à cette vue que en POST.

2023-06-08 10:36 UTC, philippemilink commented on zds/middlewares/managesessionsmiddleware.py
> +class ManageSessionsMiddleware:
Peut-être rajouter un commentaire pour expliquer ce que fait ce middleware, à quoi il sert, pourquoi on en a besoin ?

2023-09-07 19:34 UTC, Situphen commented on requirements.txt
> +ua-parser==0.16.1
`user-agents` inclut bien `ua-parser` mais dans sa version 0.10.0 qui date de février 2020. On peut s'en contenter mais autant installer la dernière version de `ua-parser` pour mieux détecter les nouveaux appareils, non ?

2023-10-14 17:35 UTC, philippemilink commented on requirements.txt
> +ua-parser==0.16.1
Ok... C'est bizarre que `user-agents` ne mette pas à jour sa version de `ua-parser`... Je n'ai juste pas envie que ce soit à nous de tester si les versions de `user-agents` et `ua-parser` sont bien compatibles...

2024-01-17 10:58 UTC, AmauryCarrade commented
Hello! Est-ce que cette PR est toujours d'actualité, et est-ce que de l'aide serait souhaitée en plus de la future QA ?

2024-01-17 19:10 UTC, philippemilink commented
Pour moi (mais je ne suis pas l'auteur), cette PR est toujours d'actualité, il faut seulement prendre en compte mes remarques :)

2024-01-17 20:01 UTC, Situphen commented
Je confirme que cette PR est encore d'actualité mais je n'ai pas la motivation pour me remettre dedans en ce moment. @AmauryCarrade Si tu as envie de la reprendre, n'hésites pas, je peux te donner les droits sur ma branche ou tu peux créer une nouvelle PR. Il faut simplement me prévenir histoire que ça ne coincide pas avec une reprise de la motivation de mon côté :D

2024-03-09 23:55 UTC, Situphen commented on requirements.txt
> +ua-parser==0.16.1
Finalement, j'ai viré la dépendance `user-agents` (dernière version en août 2020, dernière PR fusionnée en février 2023) pour ne garder que `ua-parser` qui a globalement tout ce qui nous faut et qui est plus actif

2024-03-09 23:55 UTC, Situphen commented on templates/member/settings/sessions.html
> +    {% include "misc/paginator.html" with position="top" %}
Oui, ça ne mange pas de pain !

2024-03-09 23:55 UTC, Situphen commented on templates/member/settings/sessions.html
> +                                </form>
Bien vu !

2024-03-09 23:55 UTC, Situphen commented on zds/member/views/sessions.py
> +
Bonne idée !

2024-03-09 23:56 UTC, Situphen commented on zds/middlewares/managesessionsmiddleware.py
> +class ManageSessionsMiddleware:
C'est fait :)

2024-03-09 23:56 UTC, Situphen commented on zds/member/views/sessions.py
> +        for session in Session.objects.iterator():
C'est fait !

2024-03-09 23:58 UTC, Situphen commented
Bon, j'ai eu un élan de motivation donc j'ai pu mettre à jour cette PR et prendre en compte les différentes remarques !

2024-03-10 13:44 UTC, philippemilink approved these changes
**QA OK** :heavy_check_mark:

2024-03-10 13:44 UTC, merged