[WIP]Change la manière de faire la publication des tuto et des latex
zestedesavoir/zds-site pull request #6025
Opened 2021-02-16 21:09 UTC by artragis

VOici le code de base pour faire la publication des tutos avec zmd 10; C'est tout beau tout neuf, ça sent bon.

Le code doit encore être un peu nettoyé mais en soi voici ce qui marche chez moi :

- la publication  avec un gain de perf tout de même a priori

Ce qui ne marche pas : 

le latex, j'ai une 500

2021-03-12 21:48 UTC, philippemilink commented
Tu peux rebaser, stp ?

2021-03-13 07:50 UTC, artragis commented
C'est bon

2021-04-07 19:48 UTC, philippemilink commented on zds/utils/templatetags/emarkdown.py
> +
Je m'étonne que black ne râle pas à cause de la ligne vide juste après le `except`...

2021-04-08 11:14 UTC, Situphen reviewed
J'ai regardé le code et c'est franchement du bon boulot !

Par contre j'ai l'impression que ton code s'ajoute au code actuel. Est-ce que à terme on supprimera l'ancienne manière de publier un contenu (notamment `publish_container()` de `tutorialv2/publish_container.py`) ? Car j'ai l'impression qu'il va y avoir une bonne partie du code qui ne sera plus vraiment utilisé (c'est déjà le cas avec la génération des exports en *watchdog* au lieu de *sync*) donc il va falloir faire du nettoyage !

Aussi tu as un peu enlevé la génération de l'export HTML mais tu as gardé `ZmarkdownHtmlPublicator`, il y a une raison ?

2021-04-08 11:14 UTC, Situphen commented on zds/tutorialv2/publication_utils.py
> +    public_version.save()
Ce ne serait pas plutôt `db_object.save()` ?

2021-04-08 11:14 UTC, Situphen commented on zds/tutorialv2/publish_container.py
> +                parsed = render_to_string(ctx.get("intro_ccl_template"), args)
Peux-tu m'expliquer ce bout de code ?

2021-04-08 11:14 UTC, Situphen commented on zds/tutorialv2/publish_container.py
> +def publish_container_new(
Je pense qu'il faudrait aérer un peu plus le code de cette fonction et ajouter peut-être quelques commentaires pour que ce soit maintenable sur le long terme.

2021-04-08 16:46 UTC, artragis commented on zds/tutorialv2/publication_utils.py
> +    public_version.save()
il faut bel et bien save public_version.
Par contre il faut comprendre pourquoi db_object ne l'est pas aussi.

2021-04-08 16:48 UTC, artragis commented on zds/tutorialv2/publish_container.py
> +                parsed = render_to_string(ctx.get("intro_ccl_template"), args)
à la base c'est un moyen de préparer la migration du rendu des epub vers la nouvelle méthode de rendu. Cependant, les epubs sont plus difficiles à gérer que prévus, c'est pour ça que j'ai deux branches du code : la `_new` qui est utilisée pour générer la vue HTML du site et le PDF, et l'ancienne qui est là pour l'epub

2021-04-16 12:37 UTC, Situphen requested changes
**Instructions de QA**

```bash
source zdsenv/bin/activate
make update
make zmd-stop # si jamais zmd tourne
make zmd-start
make run-back
```

-----

Ce qui ne va pas : 

- Il n'est plus possible de générer les exports à la demande depuis un contenu car la commande `publication_watchdog` n'a pas été prévue pour gérer le markdown : 
  
  ```
  TypeError: publish() missing 1 required keyword-only argument: 'cur_language'
  ```
- J'ai importé le mini-tutoriel « Explorons WikiData » depuis la bêta et le temps de lecture estimé est de 2 minutes en local contre 13 minutes sur la bêta, donc il y a un soucis.
- J'ai exporté le moyen-tutoriel « Introduction à la preuve de programmes C avec Frama-C et son greffon WP » depuis la bêta et le temps de lecture estimé est de 1 heure et 15 minutes, c'est mieux que sur la bêta où il est inexistant mais ça me parait faible.
- J'ai exporté le gros-tutoriel « Les réseaux de zéro » depuis la bêta et le temps de lecture estimé est de 4 heures et 30 minutes , c'est mieux que sur la bêta où il est inexistant mais ça me parait faible.
- Impossible d'exporter en PDF les tutoriels « Introduction à la preuve de programmes C avec Frama-C et son greffon WP » et « Les réseaux de zéro » à cause d'erreurs de `lualatex` mais ça provient peut-être de mon installation locale, à ignorer pour l'instant.

Ce qui va : 

- La publication et dépublication des contenus générés automatiquement ne pose pas de soucis
- L'export PDF du tutoriel « Explorons WikiData » fonctionne et rend très bien
- Les exports ZIP et EPUB n'échouent pas, après je n'ai pas vérifié leur contenu
- La commande `generate_pdf` fonctionne correctement

2021-04-18 13:31 UTC, artragis commented
pour l'estimation des temps, j'ai trouvé pourquoi: j'ai utilisé le décompte des mots au lieu du décompte des caractères.

Pour l'erreur du cur_language ça va être fixé.

2021-04-18 18:45 UTC, Situphen requested changes
Ce qui va bien : 

- l'estimation du temps est corrigée : 13 min pour « Explorons WikiData » ; 8 h et 45 min pour « Introduction à la preuve de programmes C avec Frama-C et son greffon WP » et 1 jour 2h pour « Les réseaux de zéro »
- la génération du LaTeX et du PDF fonctionne correctement (seulement « Explorons WikiData » pour le PDF car ça a échoué pour les deux autres mais c'est à cause de mon environnement de dev)

Ce qui ne va pas bien : 

- la génération du Markdown via `publishable_watchdog` ne fonctionne pas correctement : seul les titres sont dans le fichier
- conséquence directe : la commande `generate_pdf` qui se base sur le fichier Markdown ne donne pas un bon PDF
- il faut ajouter `data-tr-formatmd="{% trans "Markdown" %}"` à `templates/tutorialv2/includes/exports.part.html` pour que "Markdown" s'affiche (et non pas "md") dans la modale pour demander la génération des exports du contenu
  ![image](https://user-images.githubusercontent.com/6664636/115156923-10ee1680-a087-11eb-9437-69147f2b900e.png)

2021-04-18 18:56 UTC, artragis commented
> conséquence directe : la commande generate_pdf qui se base sur le fichier Markdown ne donne pas un bon PDF

ça c'est bizarre car justement on ne se sert plus jamais du fichier markdown, on appelle toujours le publicateur pdf

`PublicatorRegistry.get("pdf").publish(base_name + ".md", str(building_extra_content_path))` <= on utilise bien le bon publicateur

Par contre le md était juste pas ajouté à la liste des publicateurs

2021-04-18 20:09 UTC, Situphen commented
Alors la commande `generate_pdf` c'est bon (je devais être sur une mauvaise version avant) mais par contre mon fichier Markdown est toujours vide (seulement les titres de premier niveau) !

2021-04-20 18:48 UTC, artragis commented
J'ai trouvé la cause du bug. Et c'est fixé.

2021-04-20 19:21 UTC, Situphen approved these changes
**QA OK** C'est bon pour moi ! Bravo pour ce travail !

2021-04-20 19:30 UTC, merged