Dropdown actions messages
zestedesavoir/zds-site pull request #6041
Opened 2021-02-22 22:53 UTC by viki53

Plusieurs changements pour un même résultat : utilisation d'un dropdown classique (via `<details>` et `<summary`) pour les actions de messages

Création d'un composant `.dropdown` au passage. Renommage du `header-dropdown` qui créait un conflit.

### Contrôle qualité

  - `make build-front`
  - Aller sur un message avec des options (avec et sans modération activée)
  - Un dropdown devrait s'ouvrir, avec fermeture lors du clic à l'extérieur
  - Les dropdowns du header devraient fonctionner comme d'habiture

2021-02-22 23:00 UTC, Situphen requested changes
Petite revue de code.

Pour être cohérent avec le reste du code, il faudrait une indentation à 4 espaces pour `assets/scss/components/_dropdown.scss` au lieu d'une tabulation.

2021-02-22 23:00 UTC, Situphen commented on assets/scss/components/_dropdown.scss
> +	}
```suggestion
	&[open] summary::before {
		content: '';
		position: fixed;
		top: 0;
		right: 0;
		bottom: 0;
		left: 0;
	}
```

2021-02-22 23:00 UTC, Situphen commented on doc/source/front-end/elements-specifiques-au-site.rst
> +==================
```suggestion
Les menus déroulants (ou dropdown)
==================================
```

2021-02-22 23:00 UTC, Situphen commented on doc/source/front-end/elements-specifiques-au-site.rst
> +La class ``.dropdown-content`` permet de grouper le contenu pour le positionner.
```suggestion
À ne pas confondre avec ``header-dropdown``, ces menus déroulants ne requièrent aucun JS pour fonctionner mais se reposent sur la balise ``<details>``.

Pour créer un menu déroulant, ajoutez simplement la classe ``dropdown`` à l'élément ``<details>``, en utilisant la balise ``<summary>`` pour fournir un texte alternatif au ``…`` affiché par défaut.

La classe ``.dropdown-content`` permet de grouper le contenu pour le positionner.
```

2021-02-23 13:14 UTC, Situphen requested changes
Petite revue, de jour cette fois-ci !

2021-02-23 13:14 UTC, Situphen commented on assets/scss/components/_dropdown.scss
> +            border-top: 0;
Déjà présent au dessus dans le bloc `&::before, &::after {}`
```suggestion
```

2021-02-23 13:14 UTC, Situphen commented on assets/scss/components/_dropdown.scss
> +            border-top: 0;
Déjà présent au dessus dans le bloc `&::before, &::after {}`
```suggestion
```

2021-02-23 13:14 UTC, Situphen commented on assets/scss/components/_dropdown.scss
> +            border-bottom-color: #fff;
Ça revient au même, mais c'est pour garder l'habitude de ne pas avoir de couleurs en dur dans le code et d'utiliser celles de [la palette](https://zestedesavoir.github.io/normes-graphiques/#couleurs)
```suggestion
            border-bottom-color: $true-white;
```

2021-02-23 13:14 UTC, Situphen commented on assets/scss/components/_dropdown.scss
> +            border-bottom-color: hsla(0, 0%, 0%, .04);
Ça revient au même, mais c'est pour garder l'habitude de ne pas avoir de couleurs en dur dans le code et d'utiliser celles de [la palette](https://zestedesavoir.github.io/normes-graphiques/#couleurs)
```suggestion
            border-bottom-color: rgba($true-black, .04);
```

2021-02-23 13:48 UTC, viki53 commented on assets/scss/components/_dropdown.scss
> +            border-top: 0;
Nécessaire pour contrer le `border-width` de la ligne au-dessus. Au pire on peut l'enlever du bloc double, ou repasser à deux blocs dédiés (sans bloc commun).

2021-02-23 21:27 UTC, Situphen commented
Deux points probablement liés au fait d'utiliser `<details>` et `<summary>` sans JS :
- Si on clique sur le menu déroulant, puis que l'on clique en dehors pour le fermer : 
  - si on clique sur le message concerné, sur un des messages précédents ou autour des messages, le menu se ferme ;
  - si on clique sur un des messages suivants, **le menu ne se ferme pas**, ce qui est très gênant je trouve.
- Si on clique sur le menu déroulant puis qu'on clique sur un autre menu, celui-ci ne se ferme pas. Je ne sais pas à quelle point c'est gênant.
  ![Capture d'écran du soucis](https://user-images.githubusercontent.com/6664636/108908813-0b92c380-7624-11eb-9ded-dcb7b5021e2d.png)
- Si on clique sur le menu déroulant, puis sur une action (par exemple, « Citer »), celui-ci ne se ferme pas. Je ne sais pas à quelle point c'est gênant.

Autre point : 
- Au survol des trois petits points, le curseur n'indique pas que c'est cliquable.
- Je trouve que le menu une fois ouvert n'est pas assez délimité par rapport au message, je propose : une bordure un peu plus foncée, une bordure un peu plus large ou une couleur de fond différente.

2021-02-23 21:41 UTC, AmauryCarrade reviewed
Comme précisé sur Discord, je pense qu'à terme on gagnerait à permettre n'importe quoi comme déclencheur, avec éventuellement un conteneur pouvant accueillir n'importe quoi et donnant la forme avec la flèche, car ce genre de menu sera utile pour bien d'autres choses en réalité.

Petite remarque en passant.

2021-02-23 21:41 UTC, AmauryCarrade commented on assets/scss/components/_dropdown.scss
> +$dropdown-offset-right: 6px;
Pourquoi pas de `rem` ici ? Ça implique d'adapter plus bas avec `calc` par contre

```suggestion
$dropdown-offset-right: $length-6;
```

2021-02-24 09:39 UTC, viki53 commented
Pour la fermeture au clic sur le contenu, il va probablement falloir ajouter du JS sur les boutons en questions, puisque c'est pas forcément une action à automatiser sur tous les dropdowns (uniquement sur les actions qui ne déclenchent pas de navigation).

Le curseur au survol est voulu : un bouton sur une page Web n'a par défaut pas de curseur, le `pointer` est utilisé pour les liens, pour prévenir qu'il y aura une action de navigation. Ça peut se rajouter si besoin, mais je vois pas trop l'intérêt.

J'ai changé la bordure du contenu du dropdown pour la rendre plus grande et foncée.

J'ai aussi passé le style des `…` sur le CSS des messages plutôt que dans le dropdown, on pourra donc utiliser n'importe quel déclencheur par la suite.

2021-02-24 19:28 UTC, AmauryCarrade commented on assets/scss/variables/_lengths.scss
> +$length-15: 1.5rem;
L'idée de normer les longueurs c'est pas d'en ajouter quand on en a envie :-°

2021-02-24 19:34 UTC, AmauryCarrade requested changes
Dans la suite de mon commentaire sur les normes (qu'aurait dû être dans cette revue)

2021-02-24 19:34 UTC, AmauryCarrade commented on assets/scss/components/_dropdown.scss
> +            right: #{$length-15 - $dropdown-offset-right};
Si le but de `$length-15` était de pouvoir sommer ici, il plus propre d'utiliser l'offset comme il est, et d'y ajouter le décalage nécessaire à la construction de la flèche en pixels, à l'aide de `calc` : 

```suggestion
            right: calc(15px - #{$dropdown-offset-right});
```

2021-02-24 19:34 UTC, AmauryCarrade commented on assets/scss/components/_dropdown.scss
> +            right: #{$length-14 - $dropdown-offset-right};
Idem

```suggestion
            right: calc(14px - #{$dropdown-offset-right});
```

2021-02-24 19:41 UTC, Situphen requested changes
(Bon il y a de la redite avec Amaury mais tant pis.)

Au niveau du code, comme dit @AmauryCarrade, on souhaite laisser telles quelles les valeurs pour les éléments où on est au pixel près, comme la flèche dont il est question ici. Désolé si j'ai laissé entendre qu'il fallait tout mettre dans des variables, c'est une nouvelle façon de fonctionner donc on tâtonne encore ! :)

Au niveau du fonctionnement, c'est presque bon ! Petit détails de perfectionnisme, quand le menu est ouvert « Options du message » apparaît au survol de tout l'écran étant donné que `::before` prend tout l'écran. est-ce que le `title` est nécessaire ? (Github n'en met pas pour son menu identique sur les messages.)

2021-02-24 19:41 UTC, Situphen commented on assets/scss/components/_dropdown.scss
> +            right: #{$length-14 - $dropdown-offset-right};
Petit retour en arrière, ne pas mettre de variable étant donné que c'est pour la flèche donc c'est du pixel-perfect.
```suggestion
            right: #{14px - $dropdown-offset-right};
```

2021-02-24 19:41 UTC, Situphen commented on assets/scss/components/_dropdown.scss
> +            right: #{$length-15 - $dropdown-offset-right};
Petit retour en arrière, ne pas mettre de variable étant donné que c'est pour la flèche donc c'est du pixel-perfect.
```suggestion
            right: #{15px - $dropdown-offset-right};
```

2021-02-24 19:41 UTC, Situphen commented on assets/scss/variables/_lengths.scss
> +$length-15: 1.5rem;
```suggestion
```

2021-02-24 19:45 UTC, AmauryCarrade commented
Concernant la fin du message de Situphe, je mettrais un `aria-label` en lieu et place d'un `title`.

2021-02-24 19:50 UTC, viki53 commented
Le `title` est pour faciliter la découverte : quelqu'un ne qui sait pas ce que fait ce bouton peut passer la souris pour connaître son usage sans risquer d'activer quelque chose par erreur.

Ok pour les variables, même si pour le coup ça me paraît lourd de mélanger des variables qui correspondent directement à une dimension.

2021-02-24 19:55 UTC, Situphen commented
> Le `title` est pour faciliter la découverte : quelqu'un ne qui sait pas ce que fait ce bouton peut passer la souris pour connaître son usage sans risquer d'activer quelque chose par erreur.

À mon avis on peut aisément le remplacer par un `cursor: pointer` comme sur les autres boutons du site web pour dire "il est possible de cliquer ici", ce qui vient confirmer ce que les 3 petits points indiquent déjà un peu.

2021-02-24 19:55 UTC, Situphen approved these changes

2021-02-24 20:00 UTC, viki53 commented
En fait je pensais surtout à _il se passe quoi si je clique ?_ plus que de savoir que c'est cliquable.

Si on veut un effet de bouton il vaut mieux quelques styles pour faire ressortir la zone réactive.  
Le curseur donne plus une indication de ce qu'il va se passer au clic : `pointer` = lien/navigation, `default` = bouton/action.

2021-02-24 20:04 UTC, Situphen commented
> En fait je pensais surtout à _il se passe quoi si je clique ?_ plus que de savoir que c'est cliquable.

Personnellement je pense que les 3 petits points sont assez clairs et indiquent un menu, mais peut-être que je me trompe.

> Le curseur donne plus une indication de ce qu'il va se passer au clic : `pointer` = lien/navigation, `default` = bouton/action.

Au niveau des styles par défaut des navigateurs je suis d'accord, en pratique beaucoup moins : je viens de vérifier pour Github et Twitter et tous les deux utilisent des `pointer` pour tous leurs boutons.

2021-02-24 20:21 UTC, AmauryCarrade commented
À mon sens, les trois points dans un coin du message indiquent clairement ce que ça fait, et jamais dans aucune interface trois points n'ont d'effet destructeur ; je pense donc que ce n'est pas un problème. Par contre, labelliser pour les lecteurs d'écran est évidemment nécessaire.

> Au niveau des styles par défaut des navigateurs je suis d'accord, en pratique beaucoup moins : je viens de vérifier pour Github et Twitter et tous les deux utilisent des pointer pour tous leurs boutons (c'est aussi le cas de Zeste de Savoir actuellement d'ailleurs).

Idem. De façon générale, _pointeur = actionnable_, à mon sens, et c'est autant le cas des boutons que des liens. Je trouve le comportement par défaut des navigateurs (curseur par défaut sur les boutons) peu logique.

Je serais donc pour avoir un curseur pointeur sur ces points, avec en plus un retour visuel, idéalement (p.ex. passer les points dans la couleur des liens).

> Si on veut un effet de bouton il vaut mieux quelques styles pour faire ressortir la zone réactive.

Cela ne me semble pas pertinent pour un menu de dépassement — d'ailleurs, assez peu de sites mettent en avant la zone réactive pour ce genre de menus, du moins quand ils sont isolés. Je ne m'oppose pas absolument à l'idée mais je pense qu'on gagnerait en légèreté ressentie en évitant de le faire.

> Ok pour les variables, même si pour le coup ça me paraît lourd de mélanger des variables qui correspondent directement à une dimension.

Qu'entends-tu par là ? La normalisation est encore toute jeune, il est tout à fait possible de discuter des règles de son application.

Mon raisonnement est le suivant : `$dropdown-offset-right`, c'est une longueur de l'interface, il faut qu'elle soit cohérente avec le reste du site. Par contre, le décalage d'un pixel pour construire la flèche en CSS, ça n'en fait pas partie, donc les pixels c'est OK. C'est bien que la base soit de 14px qu'est une valeur normée ; cela dit, c'est pas un drame de le mettre en pixels par contrainte technique.

2021-02-24 20:32 UTC, viki53 commented
> Par contre, labelliser pour les lecteurs d'écran est évidemment nécessaire.

Pour le coup y'avait déjà le `.sr-only` pour ça, donc le `aria-label` est répétitif. Je supprime.

Je suis pas pour ajouter des styles non plus, juste que pour moi c'est plus efficace qu'un curseur pour savoir ce que ça fait avant même d'y passer la souris. Pour le style au survol/focus je verrais plutôt un changement de luminosité du gris plutôt que de couleur. 

Pour les variables je parlais surtout des `$length-xx` qui correspondent toutes à `x.xrem`, c'est lourd pour pas grand chose au final. Les noms sont pas super sémantiques et ne pointent que vers des valeurs fixes qui n'ont pas vocation à changer.

2021-02-25 21:42 UTC, Situphen commented
Bon, que faisons-nous ? J'aurais aimé avoir un curseur `pointer` mais c'est clairement un détail donc je propose que l'on fusionne tel quel. @AmauryCarrade ?

2021-02-25 23:30 UTC, AmauryCarrade commented
> Pour le coup y'avait déjà le .sr-only pour ça, donc le aria-label est répétitif. Je supprime.

Effectivement. :+1: 

> Je suis pas pour ajouter des styles non plus, juste que pour moi c'est plus efficace qu'un curseur pour savoir ce que ça fait avant même d'y passer la souris. Pour le style au survol/focus je verrais plutôt un changement de luminosité du gris plutôt que de couleur.

Effectivement sur le style au survol, ça se discute (par contre dans ce cas, plutôt prendre un des autres gris, il y a une sélection d'une dizaine de luminosités de gris, ça sert à ça ^^), mais ça me va très bien.

Cela dit, je persiste à penser que ça se cumulerait très bien avec un pointeur, tant j'ai peur que de voir un truc qui réagit mais sans le curseur qui devient un pointeur ferait bizarre (d'autant plus que presque tous les éléments actionnables de ZdS ont un pointeur, ce serait la seule exception avec les cases à cocher — et pour les cases à cocher j'avais bien l'intention de changer ça).

> Pour les variables je parlais surtout des `$length-xx` qui correspondent toutes à `x.xrem`, c'est lourd pour pas grand chose au final. Les noms sont pas super sémantiques et ne pointent que vers des valeurs fixes qui n'ont pas vocation à changer.

Ce système est relativement récent, et je suis totalement ouvert à la discussion le concernant. L'objectif est simple : normaliser les longueurs, afin qu'on ait pas tout et n'importe quoi partout mais que toutes les tailles (au sens large : largeur d'élément, marge entre des éléments, tailles de bordure, …) soient [dans un même ensemble restreint de longueurs](https://zestedesavoir.github.io/normes-graphiques/#longueurs), ce qui donne une cohérence visuelle d'ensemble bien plus propre.

Passer par des variables permettait d'imposer cette structure car… y'a pas de variable hors de la structure, tout simplement. Mais si tu penses qu'une autre façon de faire serait plus pertinente, et ce quelle que soit cette façon de faire, je suis tout à fait ouvert à la discussion (peut-être pas ici, cela dit).

> Bon, que faisons-nous ? J'aurais aimé avoir un curseur `pointer` mais c'est clairement un détail donc je propose que l'on fusionne tel quel. @AmauryCarrade ?

Je ne vais pas bloquer la PR si c'est juste ça, mais je préfère _vraiment_ avec un pointeur pour tous les actionnables du site.

2021-02-26 07:56 UTC, viki53 commented
Par rapport au choix du curseur sur les boutons, cet article résume pas mal la situation selon moi :
https://uxdesign.cc/buttons-shouldnt-have-a-hand-cursor-part-2-4a6e1c8423a5 

Le W3C est également assez explicite sur la définition : 
> **pointer**
>     The cursor is a pointer that indicates a link. 
https://www.w3.org/TR/CSS21/ui.html#cursor-props

2021-02-26 13:27 UTC, AmauryCarrade commented
> Par rapport au choix du curseur sur les boutons, cet article résume pas mal la situation selon moi :
> https://uxdesign.cc/buttons-shouldnt-have-a-hand-cursor-part-2-4a6e1c8423a5

J'ai lu les trois posts et j'arrive pas à être convaincu. Enfin, disons que pour moi, ces articles disent bien que ce n'est _pas une mauvaise chose_ de ne pas avoir de curseur pointeur sur les assimilés boutons, mais il ne dit pas grand chose sur le fait que ce serait une mauvaise chose d'en avoir.

Les arguments sortent un peu de nulle part, à base de « Microsoft a dit que », et de « On a toujours fait comme ça », plus des tests sur des échantillons minuscules, bref, c'est une tribune intéressante mais je n'arrive pas à y adhérer totalement même si certains de ces propos font sens. D'ailleurs beaucoup de ses arguments peuvent se retourner à l'identique (p.ex. sur le fait que certains grands ne mettent pas de pointeur ; il remarque lui-même qu'en fait, ce n'est pas aussi vrai, et _beaucoup_ de grands mettent des pointeurs sur tous les actionnables). Aussi, son argument de confirmation d'action s'applique très bien au fait de… mettre un curseur sur ces trois points qui n'ont _pas_ une tête de bouton au sens classique du terme (i.e. un rectangle avec ou une couleur ou une élévation différente).

Disons donc que je ne m'oppose pas à ne pas avoir de pointeur ; mais que je persiste à trouver que c'est une meilleure idée.

D'autant plus, et c'est aussi un point qui me fait pencher vers le curseur pointeur, que tout ZdS en utilise sur tous les actionnables ; ce serait la seule exception.

Quant à la définition du W3C je ne suis pas sûr qu'elle soit tant que ça pertinente tant on est sur un élément dicté par l'usage plus que par la norme, à mon sens.

> Pour les variables on peut en discuter tranquillement ailleurs avec plaisir. Je comprends bien l'intérêt d'en limiter le nombre, la façon de faire actuelle me paraît juste un peu bancale :)

Avec plaisir, quand tu veux. Je ne suis pas sectaire sur la façon de gérer ça, je veux juste que les normes restent propres :) .

2021-02-26 15:59 UTC, AmauryCarrade approved these changes

2021-02-26 16:00 UTC, merged