Ajout d'un filtre par tag sur les flux RSS/Atom des contenus
zestedesavoir/zds-site pull request #6048
Opened 2021-02-26 08:55 UTC by entwanne

Salut,

Juste un petit changement pour ajouter des filtres par tag sur les flux des contenus, par exemple http://zds/billets/flux/rss/?tag=python
Ce qui semble [être attendu par certaines personnes](https://discuss.afpy.org/t/blogs-francais-sur-python/88/11).

2021-02-26 09:31 UTC, artragis requested changes

2021-02-26 09:31 UTC, artragis commented on zds/tutorialv2/feeds.py
> +        if "tag" in self.query_params:
j'aurais préféré un `if self.query_params.get("tag", "").strip()` qui permettra d'éviter de passer un slug null à la requête

2021-02-26 10:48 UTC, artragis commented on zds/tutorialv2/feeds.py
> +        tag = self.query_params.get("tag", "").strip()
il faudrait aussi trouver le moyen de changer le "link" car là on a ça : 

```xml
    <link href="http://localhost:8000/tutoriels/" rel="alternate"></link>
    <link href="http://localhost:8000/tutoriels/flux/atom/" rel="self"></link>
```
le `tag=python` est perdu.

2021-02-26 10:48 UTC, artragis commented on zds/tutorialv2/feeds.py
>          if "subcategory" in self.query_params:
il faudrait probablement propager le changement sur le `if self.query_params.get("subcategory", "").strip()` histoire de garder une cohérence.

Idem, mettre en dessous `tags = None` puis faire le if en se passant du else permettrait de garder toujours le même pattern de code

2021-02-26 10:57 UTC, entwanne commented on zds/tutorialv2/feeds.py
> +        tag = self.query_params.get("tag", "").strip()
Mmh je suis d'accord mais on a actuellement le même comportement pour les catégories.

2021-02-26 13:40 UTC, entwanne commented on zds/tutorialv2/feeds.py
> +        tag = self.query_params.get("tag", "").strip()
J'ai fait un truc un peu crade mais ça fonctionne : https://github.com/zestedesavoir/zds-site/pull/6048/files#diff-690b81fad8df2a1f1ce37c846641d9247e3472d244f17039d2910a5ed0c98d5eR129

2021-03-02 19:30 UTC, artragis approved these changes

2021-03-02 19:30 UTC, artragis commented
QA OK

2021-03-02 19:40 UTC, merged

2021-03-02 19:55 UTC, entwanne commented
Merci !