Nouveau SDK pour Sentry
zestedesavoir/zds-site pull request #6055
Opened 2021-03-01 19:09 UTC by Situphen

Nouveau SDK pour Sentry, car l'ancien n'est plus maintenu

[Documentation pour la configuration](https://docs.sentry.io/platforms/python/guides/django/)

- [x] Configuration de base d'après la documentation
- [ ] Remplacer les appels à Raven avec la nouvelle façon de faire dans `zds/tutorialv2/publication_utils.py`
- [ ] Tester sur la bêta et adapter la configuration

2021-03-01 20:39 UTC, artragis requested changes

2021-03-01 20:39 UTC, artragis commented on zds/settings/prod.py
> +    integrations=[DjangoIntegration()],
C'est là qu'il faut ajouter la loggingintegration, non?

2021-03-01 20:49 UTC, Situphen commented on zds/settings/prod.py
> +    integrations=[DjangoIntegration()],
Oui, mais en fait par défaut il est déjà inclut d'après la documentation, il faut que j'enlève l'importation.

2021-05-22 21:01 UTC, Situphen commented
@firm1 Ce n'est pas grave si je supprime `/var/log/zds/middlewares.log` ? Les requêtes de la journée vers Matomo sont toujours accessibles via systemd (`journalctl -e -u zds`).

2021-05-23 14:13 UTC, merged