Permet l'utilisation de svg dans la gallerie
zestedesavoir/zds-site pull request #6067
Opened 2021-03-08 17:59 UTC by artragis

### Contrôle qualité

- Ajouter une image png/webp dans la gallerie
- Ajouter une image svg dans la gallerie
- Faire un glisser/déposer d'une image png/webp dans un message du forum
- Faire un glisser/déposer d'une image svg dans un message du forum
- Ajouter une illustration png à votre tuto
- Ajouter une illustration svg à votre tuto

Tout doit fonctionner

2021-03-13 15:17 UTC, philippemilink requested changes
Rapport de QA
----------------

- Mes quelques remarques par rapport au code
- Un petit conflit à résoudre
- Ajouter une image png/webp dans la gallerie ✔️ 
- Ajouter une image svg dans la gallerie ❌ en essayant d'ajouter la galerie les SVG qui sont dans `assets/images/{editor/svg,brands}/*`, j'obtiens le message d'erreur en validant le formulaire: *Transférez une image valide. Le fichier que vous avez transféré n'est pas une image, ou il est corrompu.*
- Faire un glisser/déposer d'une image png/webp dans un message du forum ✔️ 
- Faire un glisser/déposer d'une image svg dans un message du forum ✔️ 
- Ajouter une illustration png à votre tuto et Ajouter une illustration svg à votre tuto ✔️ (j'ai fait sur un billet, mais ça devrait être pareil)

2021-03-13 15:17 UTC, philippemilink commented on zds/gallery/forms.py
> +from django.core.validators import FileExtensionValidator
Ces deux imports ne sont pas utilisés dans le fichier. À supprimer ?

2021-03-13 15:17 UTC, philippemilink commented on zds/gallery/api/tests.py
> +            pass
À quoi ça sert de faire un `with open(): pass`? à tester que l'ouverture du fichier ne génère pas d'exception ? Ça demande peut-être de rajouter un commentaire :)

2021-03-13 16:42 UTC, artragis commented on zds/gallery/api/tests.py
> +            pass
ça permet de créer le fichier, sinon il te dit qu'il existe pas

2021-03-13 16:42 UTC, artragis commented on zds/gallery/forms.py
> +from django.core.validators import FileExtensionValidator
bien vu, mais du coup, pourquoi le linter ne le voit pas?

2021-03-13 21:30 UTC, philippemilink commented on zds/gallery/api/tests.py
> +            pass
Ok, donc juste un commentaire qui précise ça, alors !

2021-03-13 21:38 UTC, philippemilink commented on zds/gallery/forms.py
> +from django.core.validators import FileExtensionValidator
Apparemment black n'a pas cette fonctionnalité: https://github.com/psf/black/issues/86

2021-03-13 21:50 UTC, Arnaud-D commented on zds/gallery/forms.py
> +from django.core.validators import FileExtensionValidator
Oui, j'ai aussi remarqué ça récemment. Ce serait bien qu'on ait quelque chose pour détecter ça. `black` fait le formatage et on pourrait (r)ajouter autre chose pour gérer les règles de styles qui ne sont pas du formatage.

2021-03-14 07:37 UTC, artragis commented
> Ajouter une image svg dans la gallerie ❌ en essayant d'ajouter la galerie les SVG qui sont dans assets/images/{editor/svg,brands}/*, j'obtiens le message d'erreur en validant le formulaire: Transférez une image valide. Le fichier que vous avez transféré n'est pas une image, ou il est corrompu.


Celle là c'est vraiment étrange. je vais retester mais à l'époque la première chose que j'avais regardé, justement c'est l'upload dans une gallerie.

2021-03-14 16:17 UTC, artragis commented
C'est bon j'ai trouvé, c'est corrigé.

2021-03-14 18:24 UTC, philippemilink requested changes
Rapport de QA
----------------

- Ajouter une image png/webp dans la galerie ✔️ 
- Ajouter une image svg dans la galerie ✔️ 
- Ajout d'un fichier autre que image impossible dans la galerie: :x:
   - le formulaire n'est pas validé avec un simple fichier JavaScript
   - la validation du formulaire soulève une exception NotAnImage (qui ferait une 500 en prod) quand on essaie d'envoyer un fichier markdown renommé en `fake-img.png`
   - par contre un fichier markdown renommé en `fake-svg.svg` est bien sauvegardé... 🛑 
- Faire un glisser/déposer d'une image png/webp dans un message du forum ✔️ 
- Faire un glisser/déposer d'une image svg dans un message du forum ✔️ 
- Glisser/déposer un faux SVG dans un message du forum est interdit: ✔️ Là on a bien une erreur `Erreur 500 Internal Server Error : 'InvalidImageFormatError at /api/galeries/55/images/'`
- Ajouter une illustration png à votre tuto ✔️ 
- Ajouter une illustration svg à votre tuto ✔️ mais :x: car un faux SVG valide le formulaire.

2021-03-20 11:15 UTC, artragis commented
Les bugs détectés ont été fixés

2021-03-21 13:31 UTC, philippemilink commented
Rapport de QA
----------------

- Ajouter une image png/webp/jpeg dans la galerie ✔️ 
- Ajouter une image svg dans la galerie ✔️ 
- Ajout d'un fichier autre que image impossible dans la galerie: :heavy_check_mark: 
   - le formulaire n'est pas validé avec un simple fichier JavaScript
   - le formulaire n'est pas validé avec fichier Markdown renommé en `fake-img.png`
   - le formulaire n'est pas validé avec fichier Markdown renommé en `fake-img.svg`
- Faire un glisser/déposer d'une image png/webp/jpg dans un message du forum ✔️ 
- Faire un glisser/déposer d'une image svg dans un message du forum ✔️ 
- Glisser/déposer un faux SVG /PNG dans un message du forum est interdit: ✔️
- Ajouter une illustration PNG/SVG/JPG à votre tuto ✔️ 
- Ajouter une illustration qui est un faux PNG ou SVG à votre tuto: génère une erreur 500 NotAnImage

Donc tout est bon, mais je me dis que ce serait bien d'en profiter pour corriger le dernier point. Donc je valide la PR, mais je ne merge pas. @artragis si tu préfères ouvrir une issue séparée pour traiter ce point, je te laisse merger.

2021-03-21 13:44 UTC, artragis commented
c'est bon de mon côté : j'ai fixé aussi l'erreur 500 pour les minitatures des contenus

2021-03-21 14:56 UTC, philippemilink commented
Rapport de QA
---------------------

:x: En voulant mettre un PNG non valide (un fichier markdown renommé en foo.png) comme miniature d'un billet, j'ai l'erreur `ValueError 'ContentForm' has no field named 'physical'.` Idem pour un faux SVG.

2021-03-21 15:38 UTC, artragis commented
Aahhh j'ai trouvé : c'est la remontée d'erreur qui lève l'exception

2021-03-21 18:13 UTC, philippemilink approved these changes
Rapport de QA
---------------------

**OK** ! :heavy_check_mark: :partying_face:

2021-03-21 18:41 UTC, merged