Corrige un bug dans l'abonnement aux MP
zestedesavoir/zds-site pull request #6070
Opened 2021-03-09 19:39 UTC by Arnaud-D

Utilise add_participant dans tous les cas d'ajout de participant à un MP (sauf pour l'API).
Ajoute une option au signal pour distinguer les usages explicites (qui doivent conduire à une notif)
de ceux silencieux (qui ne doivent pas conduire à une notif).

Fix #6068.

### Contrôle qualité

TODO

2021-03-10 22:30 UTC, philippemilink commented on zds/utils/mps.py
> +    except NotReachableError:
Pour éviter d'avoir à gérer une exception, peut-être faire `if is_reachable(author):` (comme [ici](https://github.com/zestedesavoir/zds-site/pull/6070/files#diff-1d38ae54d26804b2157ebd633136aa502ac9bfd1ab4f7167e886222f9996680aR276)) ?

2021-03-11 12:30 UTC, Arnaud-D commented on zds/utils/mps.py
> +    except NotReachableError:
Ça revient essentiellement au même. En Python, l'idiome a plutôt tendance à être du côté de l'utilisation d'exception, même si un if fait ici aussi très bien l'affaire.

Dans le cas présent, ce code n'a pas vocation à rester à long terme. Quand on envoie un message avec le bot, c'est qu'on décide de le faire dans le code. À partir de là, on pourrait avoir une variante de la fonction qui n'ajoute pas automatiquement l'auteur au fil de MP quand on poste dans celui-ci.

2021-04-04 17:25 UTC, artragis requested changes
Le fonctionnel est OK, j'ai deux/trois broutilles sur le code et ça sera mergeable. Oublie pas de rebase.

2021-04-04 17:25 UTC, artragis commented on zds/mp/signals.py
> +topic_created = Signal(providing_args=["instance"])
y'a pas de "instance" dans tes receivers

2021-04-04 17:25 UTC, artragis commented on zds/utils/mps.py
> +            sender=post.__class__, post=post, by_email=send_by_mail, no_notification_for=no_notification_for
tu as renommé "instance" ici mais pas dans la définition du signal.

2021-04-04 17:25 UTC, artragis commented on zds/utils/mps.py
> +    try:
```python
with suppressing(NotReachableError):
        n_topic.add_participant(author, silent=True)
        n_topic.save()
```

me paraît plus idiomatique

2021-04-04 19:53 UTC, Arnaud-D commented on zds/mp/signals.py
> +topic_created = Signal(providing_args=["instance"])
Je devrais avoir réglé le soucis de cohérence.

Je mets aussi l'info en commentaire à la place, vu que cet argument est déprécié dans les versions récentes de Django et sera supprimé ensuite. J'ai copié la manière pragmatique de commenter d'une autre lib.

> The purely documentational providing_args argument for Signal is deprecated. If you rely on this argument as documentation, you can move the text to a code comment or docstring.
Source: [Doc de Django](https://docs.djangoproject.com/en/dev/releases/3.1/#deprecated-features-3-1)

2021-04-04 19:54 UTC, Arnaud-D commented on zds/utils/mps.py
> +            sender=post.__class__, post=post, by_email=send_by_mail, no_notification_for=no_notification_for
Voir plus haut.

2021-04-04 19:56 UTC, Arnaud-D commented on zds/utils/mps.py
> +    try:
C'est bien ça, je ne connaissais pas !

2021-04-04 19:58 UTC, artragis commented on zds/utils/mps.py
> +    try:
A priori, c'est `suppress` et pas `suppressing` et j'avais appris ça sur le site https://zestedesavoir.com/tutoriels/954/notions-de-python-avancees/3-further/2-context-managers/#4-4-contextlib

2021-04-04 19:59 UTC, artragis commented on zds/utils/mps.py
> +    try:
et un autre exemple d'utilisation https://zestedesavoir.com/tutoriels/1226/le-pattern-dispatcher-en-python/#1-un-exemple-pour-commencer-un-chatter-bot

2021-04-04 20:02 UTC, artragis approved these changes

2021-04-04 20:09 UTC, merged