Lier des sujets du forum à des dépôts annexes #5807
zestedesavoir/zds-site pull request #6084
Opened 2021-03-16 20:47 UTC by Migwel

Numéro du ticket concerné (optionnel) :
#5807

### Contrôle qualité

  - Lancez `python manage.py runserver`;
  - Se connecter en tant que `dev` ;
  - Se rendre sur un topic du forum et cliquer sur "Créer un ticket"

*Ancien comportement:"
Il n'est possible de créer des tickets que sur le dépôt zds-site

*Nouveau comportement:*
Il est possible de choisir entre zds-site et zmarkdown

2021-03-16 21:48 UTC, Situphen commented on templates/forum/topic/index.html
> +                                        <option value="{{repo.name}}">{{repo.name}}</option>
Chipotage esthétique
```suggestion
                                        <option value="{{ repo.name }}">{{ repo.name }}</option>
```

2021-03-16 21:48 UTC, Situphen commented on zds/utils/templatetags/interventions.py
> +        return "{}/{}".format(get_repository(repository_name)["bugtracker"], topic.github_issue)
Suggestion pour plus de lisibilité
```suggestion
        if topic.github_repository_name:
            repository_name = topic.github_repository_name
        else:
            repository_name = "zds-site"
        bugtracker = get_repository(repository_name)["bugtracker"]
        return f"{bugtracker}/{topic.github_issue}"
```

2021-03-16 21:48 UTC, Situphen commented on zds/utils/context_processor.py
> +        url = get_repository("zds-site")["url"]
Ça m'embête un peu d'avoir `zds-site` en dur dans le code. :/

2021-03-16 21:48 UTC, Situphen commented on zds/settings/abstract_base/zds.py
> +    ],
- Est-ce qu'on ne devrait pas mettre `zestedesavoir/zds-site` et `zestedesavoir/zmarkdown` en `name` pour se laisser la possibilité plus tard d'avoir des dépôts externes ? Ce n'est pas important mais je trouve que ça ne mange pas de pain de le faire.
- Comme je l'ai dit dans un autre commentaire, il faudrait garder le nom du dépôt principal dans une variable
- Clairement du détails vu qu'il n'y a que deux dépôts mais les URL sont redondantes

Je propose donc quelque chose comme ceci : 

```suggestion
    "github_projects": {
        "url": "https://github.com/{}".format,
        "bugtracker": "https://github.com/{}/issues".format,
        "api": "https://api.github.com/repos/{}".format,
        "default_repository": "zestedesavoir/zds-site",
        "repositories": [
            "zestedesavoir/zds-site",
            "zestedesavoir/zmarkdown",
        ],
    },
```

Pour `https://github.com/zestedesavoir/zds-site` aurait donc par exemple : 

```py
ZDS_APP["github_projects"]["url"](ZDS_APP["github_projects"]["default_repository"])
```

Autre exemple : 

```py
ZDS_APP["github_projects"]["url"](get_repository(request.POST["repository"]))
```

C'est peut-être prendre un bazooka pour tuer une mouche, à réfléchir.

2021-03-16 22:07 UTC, Migwel commented on zds/settings/abstract_base/zds.py
> +    ],
Pour la partie des URLs redondantes, j'y ai pensé aussi mais j'avais "peur" de rendre ça trop générique (et moins lisible) sans savoir si le prochain dépôt qui sera ajouté sera un dépôt de Github. Par exemple si on ajoute un dépôt de Gitlab, ce travail de générification aura été contre-productif.
La question est évidemment de savoir ce qui est le plus probable: qu'on ajoute un nouveau dépôt Github ou un complètement différent (j'imagine Github)

2021-04-11 16:44 UTC, philippemilink commented
Comment est-ce qu'on peut tester ça sans envoyer en vrai des tickets à GitHub ? (et au passage devoir avoir le token de l'API)

(ou bien il n'y a pas besoin de tester ce comportement, juste l'interface ?)

2021-04-11 17:03 UTC, Migwel commented
> 
> 
> Comment est-ce qu'on peut tester ça sans envoyer en vrai des tickets à GitHub ? (et au passage devoir avoir le token de l'API)
> 
> (ou bien il n'y a pas besoin de tester ce comportement, juste l'interface ?)

Pour tester ça localement, j'ai changé les valeurs dans zds.py pour un dépôt personnel (et j'ai utilisé un vrai token). Sans ça, je ne vois pas d'autre moyen de tester.

2021-04-11 17:57 UTC, philippemilink submitted a review, later dismissed
Rapport de QA
----------------------

Donc j'ai testé avec un token et deux dépôts privés sur GitHub et ça fonctionne bien, que ce soit la création d'un ticket dans un dépôt ou dans l'autre ou l'association à un ticket déjà existant. J'avais un doute sur la façon dont allait être gérés les anciens sujets qui ont déjà un ticket associé, mais ça semble bien pris en compte.

De mon côté j'approuve, ping @Situphen pour qu'il confirme que ses remarques sur le code sont résolues.

2021-04-11 18:34 UTC, Situphen requested changes
Je confirme que mes remarques précédentes ont bien été prises en compte ! J'ai une dernière remarque en commentaire qui permet d'avoir un code plus compréhensible à mes yeux et donc mieux maintenable sur le long terme, si ça ne vous demande pas trop de boulot. Sinon tout est bon !

2021-04-11 18:34 UTC, Situphen commented on zds/utils/context_processor.py
> +    raise Exception("Incorrect repository_name: " + repository_name)
Sauf erreur de ma part on pourrait faire cette simplification là :
```suggestion
def get_repository_url(repository_name, url_type):
    if repository_name not in settings.ZDS_APP["github_projects"]["repositories"]:
        raise Exception("Incorrect repository_name: " + repository_name)

    return settings.ZDS_APP["github_projects"][url_type](repository_name)
```

2021-04-15 15:28 UTC, Situphen approved these changes

2021-04-15 15:29 UTC, Migwel commented on zds/utils/context_processor.py
> +    raise Exception("Incorrect repository_name: " + repository_name)
Bonne idée en effet, c'est bien plus simple

2021-04-18 17:12 UTC, philippemilink approved these changes
Rapport de QA
---------------

**OK** ✔️

2021-04-18 17:21 UTC, merged