Envoie un MP lorsqu'un membre est retiré des auteurs d'un contenu (#5778)
zestedesavoir/zds-site pull request #6085
Opened 2021-03-19 21:01 UTC by Migwel

Numéro du ticket concerné (optionnel) :
#5778

### Contrôle qualité

**MP lors du retrait d'un autre membre:**

  - Créez un contenu (article, billet, tutoriel)
  - Ajoutez un membre à la liste d'auteurs
  - Retirez ce membre de la liste d'auteurs

**Ancien comportement:**
Aucun MP n'est envoyé lors du retrait du membre
**Nouveau comportement:**
Un MP est envoyé au membre lorsqu'il est supprimé de la liste d'auteurs

**Aucun MP lors du retrait de soi-même:**
  - Créez un contenu (article, billet, tutoriel)
  - Ajoutez un membre à la liste d'auteurs
  - Retirez-vous de la liste d'auteurs

**Ancien et nouveau comportement:**
Aucun MP n'est envoyé lors du retrait

2021-03-27 15:25 UTC, Arnaud-D requested changes
C'est OK niveau fonctionnalité, mais quelques commentaires sur le code.

2021-03-27 15:25 UTC, Arnaud-D commented on zds/tutorialv2/views/authors.py
> +                        send_by_mail=True,
Tu peux enlever cette ligne, c'est déjà la valeur par défaut.

2021-03-27 15:25 UTC, Arnaud-D commented on zds/tutorialv2/views/authors.py
> +                        direct=False,
Tu peux enlever cette ligne, c'est déjà la valeur par défaut.

2021-03-27 15:25 UTC, Arnaud-D commented on zds/tutorialv2/views/authors.py
> +                self.request, _("Vous avez enlevé {} de la liste des auteurs de {}.").format(authors_list, _type[0])
Utilise une f-string pour faire le formatage, on généralise cette méthode dans tout le code.

2021-03-27 15:25 UTC, Arnaud-D commented on zds/tutorialv2/views/authors.py
> +                    ).format(_type[0]),
Utilise une f-string pour faire le formatage, on généralise cette méthode dans tout le code.

2021-03-27 15:25 UTC, Arnaud-D commented on zds/tutorialv2/views/authors.py
> +            messages.success(self.request, _("Vous avez bien quitté la rédaction de {}.").format(_type[0]))
Utilise une f-string pour faire le formatage, on généralise cette méthode dans tout le code.

2021-03-27 16:27 UTC, artragis commented on zds/tutorialv2/views/authors.py
> +                self.request, _("Vous avez enlevé {} de la liste des auteurs de {}.").format(authors_list, _type[0])
Non on peut pas : ici on formate sur le code traduit, pas sur la string elle-même

2021-03-27 16:27 UTC, artragis commented on zds/tutorialv2/views/authors.py
> +                    ).format(_type[0]),
Idem

2021-03-27 18:13 UTC, Arnaud-D commented on zds/tutorialv2/views/authors.py
> +                self.request, _("Vous avez enlevé {} de la liste des auteurs de {}.").format(authors_list, _type[0])
Oui, en effet, j'ai dis des bêtises. Dans ce cas on ne devrait pas suivre les conseils de : https://docs.djangoproject.com/en/2.2/topics/i18n/translation/#standard-translation et utiliser de l'interpolation en mode `_('Today is %(month)s %(day)s.') % {'month': m, 'day': d}` ?

(Après, en pratique, on ne traduit pas, donc peu importe...)

2021-03-29 17:15 UTC, Migwel commented on zds/tutorialv2/views/authors.py
> +                self.request, _("Vous avez enlevé {} de la liste des auteurs de {}.").format(authors_list, _type[0])
Je n'ai pas d'opinion prononcée là-dessus mais j'ai surtout continué avec cette approche parce que c'est comme ça que c'est fait partout dans le code base (quand on utlise `messages.success(...)`). Si on veut changer ça, je pense que ça devrait se faire via une PR indépendante qui ferait ce changement partout.

2021-04-04 20:16 UTC, Arnaud-D commented on zds/tutorialv2/views/authors.py
> +                self.request, _("Vous avez enlevé {} de la liste des auteurs de {}.").format(authors_list, _type[0])
Pas de soucis pour moi, on peut laisser comme ça dans un premier temps. :)

2021-04-04 20:18 UTC, Arnaud-D approved these changes

2021-04-04 21:27 UTC, merged