Réduit la quantité de requêtes réalisées sur la page d'accueil des forums
zestedesavoir/zds-site pull request #6089
Opened 2021-03-27 13:52 UTC by artragis

### Contrôle qualité

- Sans être connecté : aller sur la page d'accueil des forums. Les nombres sont corrects, les URLS sont fonctionnelles
- En étant connecté et en ayant au moins un message non lu qui est le dernier message du forum, aller sur la page d'accueil des forums, la graisse est bien mise, les nombres sont corrects, les urls sont fonctionnelles.

2021-03-27 14:12 UTC, Situphen reviewed
Je ne suis pas trop fan de la duplication de `forums.part.html` et `forums.authenticated.part.html`. Je pense qu'on pourrait avoir seulement `forums.part.html` avec un paramètre booléen `is_authenticated` : 

```html+django
        {% if user.is_authenticated %}
            {% include "forum/includes/forums.part.html" is_authenticated=True %}
        {% else %}
            {% include "forum/includes/forums.part.html" is_authenticated=False %}
        {% endif %}
```

et ceci dans `forums.part.html` : 

```html+django
{% if is_authenticated %}
    {% set last_message_url as last_message.topic.resolve_last_read_post_absolute_url %}
{% else %}
    {% set last_message_url as last_message.topic.resolve_first_post_absolute_url %}
{% endif %}
```

puis utiliser `{{ last_message_url }}`

Si `{% set %}` ne fonctionne pas alors utiliser `{% captureas %}` (et dans les deux cas il faut le charger au début du gabarit je crois).

2021-03-27 14:28 UTC, Situphen commented on zds/forum/managers.py
> +        return getattr(topic, "_is_read")
Je me demande si ça ne serait pas plus clair en une seule fonction : 

```suggestion
    def topic_read(self, topic, user=None):
        """
        Checks if the user has read the **last post** of the topic.
        Returns false if the user read the topic except its last post.
        Technically this is done by checking if the user has a `TopicRead` object
        for the last post of this topic.
        :param topic: A topic
        :param user: A user. If undefined, the current user is used.
        :return:
        """

        if hasattr(topic, "_is_read"):
            return getattr(topic, "_is_read")

        if user is None:
            user = get_current_user()
        if not user.is_authenticated:
            return False

        is_read = self.filter(post=topic.last_message, topic=topic, user=user).exists()
        setattr(topic, "_is_read", is_read)
        return is_read
```

2021-03-27 14:28 UTC, Situphen commented on zds/forum/managers.py
> +        return getattr(topic, "_is_read")
Il faudrait peut-être aussi trouver un nom plus claire que `topic_read()`. Peut-être `is_topic_last_message_read()` ?

2021-03-27 15:46 UTC, artragis commented
Pour la "duplication", au départ, je voulais dupliquer la boucle complète pour justement éviter d'avoir un if/else if dans le template (c'est long et ça peut générer des requêtes inutiles selon ce qu'on teste) mais vue l'organisation, c'était plus compliqué que prévu.

Personnellement, je trouve au contraire que cette "duplication" est nécessaire car on fait beaucoup de choses très différentes en fonction du type de user et que finalement là, on est plus souple.

2021-03-27 16:01 UTC, Situphen commented
Dans le cas présent on a seulement un appel à une fonction qui change en fonction de si c'est un membre connecté ou un anonyme et le if/else c'est simplement un booléen, donc à mon avis les performances ne risquent pas grand chose alors que dupliquer le code veut dire faire les modifications futures aux deux endroits.

2021-04-04 20:56 UTC, artragis commented on zds/forum/managers.py
> +        return getattr(topic, "_is_read")
fixed

2021-04-18 18:00 UTC, philippemilink reviewed
Rapport de QA:
----------------

Tout fonctionne bien, mais j'ai juste un doute sur le cas quand le dernier message est non-lu: le lien vers le dernier message non-lu pointe vers l'avant-dernier message du message (celui qui est déjà lu). C'est normal ou bien c'est un bug ?

J'ai relevé les chiffres donnés par la debug toolbar, pour la page `/forums`:
```
non connecté:
default 21.20 ms (73 requêtes including 72 similar and 22 duplicates )
==> default 14.78 ms (40 requêtes including 39 similar )

connecté:
default 49.08 ms (186 requêtes including 174 similar and 101 duplicates )
==> default 66.22 ms (164 requêtes including 143 similar and 37 duplicates )
```
(les temps ne doivent pas être significatifs), oui il y a une réduction, mais ça me paraît encore beaucoup, on ne peut pas faire mieux ?

@Situphen tes remarques ont bien été prises en compte ?

2021-04-18 18:12 UTC, Situphen requested changes
> tes remarques ont bien été prises en compte ?

Oui ! Par contre en regardant le code j'ai une nouvelle remarque.

> Tout fonctionne bien, mais j'ai juste un doute sur le cas quand le dernier message est non-lu: le lien vers le dernier message non-lu pointe vers l'avant-dernier message du message (celui qui est déjà lu). C'est normal ou bien c'est un bug ?

C'est le comportement actuellement en production et c'est normal, c'est pour relire le message précédent et avoir le contexte. :)

> (les temps ne doivent pas être significatifs), oui il y a une réduction, mais ça me paraît encore beaucoup, on ne peut pas faire mieux ?

On peut probablement faire mieux mais ça demanderait encore plus de travail donc autant fusionner le travail qui est fait et on verra plus tard si quelqu'un a la motivation pour améliorer encore plus le code ! :)

2021-04-18 18:12 UTC, Situphen commented on zds/forum/models.py
> +            last_post = Post.objects.select_related("topic").filter(topic__forum=self).order_by("-pubdate").all()[0]
Tu n'y a pas touché donc tu n'as pas d'obligation à modifier cela mais j'imagine que ça doit simplifier la requête SQL donc vu que c'est appelé plein de fois ce serait chouette de modifier ça !
```suggestion
            last_post = Post.objects.select_related("topic").filter(topic__forum=self).order_by("-pubdate").first()
```

2021-04-18 18:12 UTC, Situphen commented on templates/forum/includes/forums.part.html
> +            {% block last_message %}
Ce bloc est devenu inutile :)

2021-04-18 18:22 UTC, artragis commented
@philippemilink un truc que j'ai remarqué en testant : la première fois il y a beaucoup de requêtes et dès le premier F5, ça change du tout au tout. Il y a probablement un cache quelque part mais je n'arrive pas à comprendre où car la conf de dev ajoute le "NoCacheMiddleware".

2021-04-18 18:24 UTC, Situphen commented
> Il y a probablement un cache quelque part mais je n'arrive pas à comprendre où car la conf de dev ajoute le "NoCacheMiddleware".

Ce *middleware* là c'est seulement pour les fichiers statiques :)

2021-04-18 18:25 UTC, Situphen approved these changes

2021-04-18 18:26 UTC, artragis commented on templates/forum/includes/forums.part.html
> +            {% block last_message %}
fixed

2021-04-18 18:35 UTC, merged