Optimisation des requêtes sur la page d'accueil
zestedesavoir/zds-site pull request #6101
Opened 2021-04-19 16:01 UTC by Situphen

2021-04-19 19:46 UTC, artragis requested changes

2021-04-19 19:46 UTC, artragis commented on zds/tutorialv2/models/database.py
> +        return json
ça vaudrait presque le coup de renommer cette variable pour qu'elle ne vaille pas la même chose que le module json

2021-04-19 19:46 UTC, artragis commented on zds/tutorialv2/models/database.py
> +            manifest = self.content.load_manifest(sha=self.sha_public, public=self)
pourquoi ne pas mettre un `self._manifest = self._manifest or self.content.load_manifest(sha=self.sha_public, public=self)` et initialiser `_manifest` à None.

Comme ça quand tu vas chercher le titre et la description, tu ne fais qu'une seule fois la lecture.

2021-04-19 19:46 UTC, artragis commented on zds/tutorialv2/managers.py
> -            .prefetch_related("authors__profile")
ça ne va pas être gênant de ne pas la charger?

2021-04-19 19:50 UTC, Situphen commented on zds/tutorialv2/managers.py
> -            .prefetch_related("authors__profile")
Non car cette fonction n'est utilisée que pour la page d'accueil et dans celle-ci pour les contenus on ne fait pas appel au profil des auteurs.

2021-04-19 19:54 UTC, Situphen commented on zds/tutorialv2/models/database.py
> +            manifest = self.content.load_manifest(sha=self.sha_public, public=self)
Bonne idée !

2021-04-19 19:54 UTC, Situphen commented on zds/tutorialv2/models/database.py
> +        return json
Bonne idée !

2021-04-19 20:11 UTC, philippemilink approved these changes
Rapport de QA
---------------

Voici les mesures que moi j'obtiens:
```
connecté:
default 86.45 ms (140 requêtes including 100 similar and 24 duplicates )
default 55.70 ms (107 requêtes including 80 similar and 24 duplicates )
==> default 56.56 ms (99 requêtes including 63 similar and 8 duplicates )
default 56.56 ms (99 requêtes including 63 similar and 8 duplicates )

anonyme:
default 27.77 ms (111 requêtes including 84 similar and 22 duplicates )
default 22.03 ms (82 requêtes including 64 similar and 22 duplicates )
==> default 45.13 ms (82 requêtes including 56 similar and 8 duplicates )
default 34.57 ms (53 requêtes including 36 similar and 8 duplicates )
```
Ça diminue bien et tout fonctionne, donc c'est **OK** ✔️ 

@artragis je te laisse approuver et merger

2021-04-20 05:48 UTC, artragis approved these changes

2021-04-20 05:49 UTC, merged