Feature/multi sur meme reseau ipv6
zestedesavoir/zds-site pull request #6124
Opened 2021-05-23 14:49 UTC by PetitMote

J'ai (oups) effacé ma branche précédente, je la refais. Cf #6120 

Modification de la fonction member_from_ip afin qu'elle retourne tous les membres sur un même bloc IPV6. Adaptation du template associé. Ajout de tests fonctionnels et d'autorisation.

Numéro du ticket concerné :
closes #4103

### Contrôle qualité

- Se connecter en tant que staff
- Aller sur un profil utilisateur et cliquer sur son adresse IP ou se rendre directement sur membres/profil/multi/<adresse ip>/
- Vérifier que les utilisateurs soient bien affichés avec une IPV4
- Donner dans la base à 2 utilisateurs une adresse IPV6 sur le même réseau (par exemple en modifiant le dernier caractère)
- Vérifier qu'avec une IPV6, on a bien 2 blocs avec la liste utilisant l'adresse ip exacte et la liste utilisant le même réseau IPV6, contenant les deux utilisateurs modifiés précédemment
- Éventuellement (fonctionnait avant) : se connecter en utilisateur et vérifier que l'accès est verrouillé

Exemple, 2 comptes sur un même réseau IPV6 chez moi :
![image](https://user-images.githubusercontent.com/81959473/118635313-b950e100-b7d3-11eb-980e-1f1679e3b4cb.png)

2021-05-31 19:45 UTC, artragis submitted a review, later dismissed

2021-05-31 19:45 UTC, artragis commented on templates/member/admin/memberip.html
> +        En IPv6, les adresses sont attribuées par bloc d'IP. Un bot de spam peut donc facilement changer d'adresse IP au sein de ce bloc. Sont affichées ici tous les membres dont l'IPv6 fait partie d
"sont affiché~~e~~s tous les membres" (sans l'accord au féminin)

2021-05-31 19:45 UTC, artragis commented on zds/member/views.py
> +        network_ip = str(network_ip)[:-1]
pourquoi ne pas simplement avoir mis : 

```python
members_and_ip["network_ip"] = str(network_ip)[:-1]
members_and_ip["network_members"] = Profile.objects.filter(last_ip_address__startswith=network_ip).order_by("-last_visit")
```

ça évite la lourdeur d'un update

2021-06-01 08:28 UTC, viki53 commented on templates/member/admin/memberip.html
> +            Liste des membres dont la dernière IP connue est <code>{{ ip }}</code>
Je sais pas si `<code>` est vraiment utile ici. C'est pas une balise hyper sémantique mais elle est plutôt faite pour présenter du _code_ informatique qu'une _adresse IP_… À étudier/débattre ?

2021-06-01 08:28 UTC, viki53 commented on templates/member/admin/memberip.html
> +    {% if ":" in ip %}
Y'aurait pas moyen de rendre cette condition plus générale ? Genre en créant une méthode/fonction réutilisable pour s'assurer qu'on utilisera toujours la même condition partout ?

2021-06-01 08:28 UTC, viki53 commented on templates/member/admin/memberip.html
> +            Liste des membres dont la dernière IP connue fait partie du bloc <code>{{ network_ip }}</code>
Idem pour la balise `<code>` ici

2021-06-01 08:28 UTC, viki53 commented on templates/member/admin/memberip.html
> +    <div class="members">
La `<div>` autour de `<ul>` est utile ? Ça peut pas être combiné ?

2021-06-01 08:28 UTC, viki53 commented on templates/member/admin/memberip.html
> +    {% if ":" in ip %}
Ce bloc s'affiche uniquement en cas d'IPv6 c'est ça ? Mais le reste (la liste au-dessus notamment) s'affiche dans tous les cas, c'est bien ça ?

2021-06-01 08:30 UTC, PetitMote commented on templates/member/admin/memberip.html
> +            Liste des membres dont la dernière IP connue est <code>{{ ip }}</code>
Je l'ai intégrée suite à la proposition de Amaury (cf la PR précédente, que j'ai accidentellement fermée...). Je ne pense pas que ce soit hyper utile, notamment parce que bon, l'adresse IP tu viens de naviguer, mais bon, ça ne change pas grand chose non plus et ça la rend un poil plus lisible.

2021-06-01 08:33 UTC, PetitMote commented on templates/member/admin/memberip.html
> +    {% if ":" in ip %}
Le bloc s'affiche effectivement uniquement en cas d'IPV6. Au-dessus ça s'affiche tout le temps, vu que ça concerne la liste des membres avec exactement la même IP.

Je ne sais pas si c'est réellement utile de définir une fonction pour tester cette condition ? Les adresses ip sont manipulées comme des chaînes de caractères, c'est déjà pas hyper propre de base, et je ne suis pas convaincu par l'ajout d'une fonction. Il me semble que @AmauryCarrade avait regardé en plus, et vu que c'était la *python way* pour vérifier qu'une IP était une IPV6, donc tout le monde devrait retomber là-dessus.

2021-06-01 08:34 UTC, PetitMote commented on templates/member/admin/memberip.html
> +    <div class="members">
Aucune idée, j'y connais rien en front, j'ai juste repris le template tel qu'il était. Tu voudrais mettre la class sur le ul, c'est ça ?

2021-06-01 08:35 UTC, PetitMote commented on zds/member/views.py
> +        network_ip = str(network_ip)[:-1]
Parce que j'y ai pas pensé 😬 M'en occupe ce soir

2021-06-01 08:45 UTC, viki53 commented on templates/member/admin/memberip.html
> +    {% if ":" in ip %}
C'est plus une question de clarté du code, en lisant on comprendrait directement que la condition sert à détecter une IPv6 plutôt que de voir une simple recherche textuelle

2021-06-01 08:47 UTC, viki53 commented on templates/member/admin/memberip.html
> +    <div class="members">
Oui, ce serait l'idée. Vu le CSS actuel ça risque de péter les styles, du coup à laisser comme ça pour le moment (ou tu te motives à faire du CSS :D )

2021-06-01 08:48 UTC, viki53 commented on templates/member/admin/memberip.html
> +            Liste des membres dont la dernière IP connue est <code>{{ ip }}</code>
Ok. Je suis pas contre, ça me semble juste pas conventionnel mais pourquoi pas vu que c'est pas une balise avec un `role` associé a priori.

2021-06-01 08:58 UTC, PetitMote commented on templates/member/admin/memberip.html
> +    <div class="members">
Moi non, mais si tu veux le faire j'ai aucun soucis avec ça :|

2021-06-01 08:58 UTC, PetitMote commented on templates/member/admin/memberip.html
> +    {% if ":" in ip %}
On peut aussi rajouter un commentaire ? Ta remarque fait sens, vu que c'est pas précisé, mais je ne sais pas si c'est la meilleure solution, à vous de me le dire

2021-06-01 12:06 UTC, AmauryCarrade commented on templates/member/admin/memberip.html
> +    {% if ":" in ip %}
+1 pour au moins mettre un commentaire. Ça ne me choquerait pas d'avoir une fonction dédiée (et son filtre associé pour les gabarits), mais un commentaire m'irait aussi.

2021-06-01 18:18 UTC, PetitMote commented on zds/member/views.py
> +        network_ip = str(network_ip)[:-1]
Ok alors en faisant les tests, je viens de trouver pourquoi, tout bêtement parce que j'ai besoin de `network_ip` pour la recherche de membres, juste après. Et c'est nécessaire de faire le slice pour cette recherche parce que par défaut un réseau IPV6 se termine avec `::`, ce qui ne matche pas avec les débuts d'adresses IPV6.

Je peux mettre comme tu proposes, et donc remettre le slice dans le `filter` juste après, mais pour le coup ça ne me paraît pas plus propre, si ?

```Python
members_and_ip["network_ip"] = str(network_ip)[:-1]
members_and_ip["network_members"] = Profile.objects.filter(last_ip_address__startswith=str(network_ip)[:-1]).order_by("-last_visit")
```

2021-06-01 18:29 UTC, PetitMote commented on templates/member/admin/memberip.html
> +        En IPv6, les adresses sont attribuées par bloc d'IP. Un bot de spam peut donc facilement changer d'adresse IP au sein de ce bloc. Sont affichées ici tous les membres dont l'IPv6 fait partie d
Fait, merci :)

2021-06-01 18:30 UTC, PetitMote commented on templates/member/admin/memberip.html
> +    {% if ":" in ip %}
J'ai ajouté le commentaire, je vous laisse me dire si vous pensez que c'est suffisant ou si ça mérite plutôt la fonction et le filtre

2021-06-02 18:06 UTC, artragis commented on zds/member/views.py
> +        network_ip = str(network_ip)[:-1]
tu peux faire `network_ip = str(network_ip)[:-1]` puis assigner la variable au membre du dictionnaire. C'est plus l'idée de faire un update qui selon moi est contre-intuitif

2021-06-02 20:01 UTC, PetitMote commented on zds/member/views.py
> +        network_ip = str(network_ip)[:-1]
Si ça te semble plus clair, je veux bien, mais je ne comprends pas bien. C'est juste une question de lisibilité ou il y a autre chose que je ne connais pas ?

2021-06-02 20:58 UTC, artragis commented on zds/member/views.py
> +        network_ip = str(network_ip)[:-1]
C'est juste pour la lisibilité. Y'a pas grand intérêt à créer un nouveau dictionnaire pour mettre à jour un dico.

2021-06-03 12:44 UTC, AmauryCarrade submitted a review, later dismissed

2021-06-03 12:44 UTC, AmauryCarrade commented on templates/member/admin/memberip.html
> +    {% if ":" in ip %} <!--Checks if it's an IPV6 to show the members from the same IPV6 network-->
Pour commenter le code du _template_, il vaut mieux utiliser des commentaires du moteur de gabarits de Django (sous la forme `{# commentaire #}`) que des commentaires HTML. En effet, de tels commentaires ne sont pas inclut dans le rendu HTML. Ce commentaire l'est, et d'une c'est inutile, de deux ça ne ferait aucun sens en lisant le code HTML car la condition ne serait plus là.

De manière générale, on n'utilise les commentaires HTML que si _vraiment_ on veut que le commentaire soit visible dans le code source généré de la page. Dans les faits, c'est très rare : généralement on ne veut qu'annoter pour nous, mais conserver le commentaire et l'envoyer à tous les visiteurs n'est que peu utile. Ça peut servir pour des mentions d'attribution, par exemple, mais sinon…
```suggestion
    {# Checks if it's an IPV6 to show the members from the same IPV6 network #}
    {% if ":" in ip %}
```

2021-09-12 18:03 UTC, Situphen commented
@PetitMote Cette PR est presque prête, tu as le temps de prendre en compte le dernier commentaire ? :)

2021-11-27 11:25 UTC, PetitMote commented on templates/member/admin/memberip.html
> +    {% if ":" in ip %} <!--Checks if it's an IPV6 to show the members from the same IPV6 network-->
C’est fait maintenant :)

2021-11-27 11:33 UTC, PetitMote commented on zds/member/views.py
> +        network_ip = str(network_ip)[:-1]
C’est fait dans le commit #3ffea09 (mais bizarrement, ça n’affiche pas la review comme outdated)

2021-11-27 11:36 UTC, PetitMote commented
J’ai enfin pris le temps de rouvrir PyCharm et de faire mes rebase ^^
Normalement, les modifs demandées ont été prises en compte et tout devrait être ok.

2021-11-27 11:37 UTC, Situphen requested changes, later dismissed

2021-11-27 11:37 UTC, Situphen commented on templates/member/admin/memberip.html
> +    {% if ":" in ip %}Checks if it's an IPV6 to show the members from the same IPV6 network
Une petite coquille s'est glissée là j'ai l'impression :)
```suggestion
    {# Checks if it's an IPV6 to show the members from the same IPV6 network #}
    {% if ":" in ip %}
```

2021-11-28 10:30 UTC, PetitMote commented
Mise à jour par rapport à la version de dev

2021-11-28 14:08 UTC, Arnaud-D commented
QA OK :heavy_check_mark:

2021-11-28 14:09 UTC, Arnaud-D approved these changes

2021-11-28 14:10 UTC, merged