Ajoute un système de liens de partage
zestedesavoir/zds-site pull request #6134
Opened 2021-06-10 13:51 UTC by Arnaud-D

Fix #6092.

Pour l'instant c'est très préliminaire.

Il y a deux gros morceaux à faire :
1. La gestion des liens de partage (ajout, révocation, expiration, modification, ...).
2. La gestion de l'accès au contenu vers les liens.

Pour l'instant, j'ai commencé le 1. parce que j'ai une meilleure idée de comment procéder.

J'aurai sûrement besoin d'aide pour faire un front un peu acceptable, mais c'est pas urgent pour le moment. :-)

### Contrôle qualité

Plus tard.

2021-06-27 19:58 UTC, Arnaud-D commented
J'avance petit à petit. Les templates ne facilitent pas la tâche, parce qu'ils gèrent au cas par cas, la bêta, la version en ligne, le draft, etc. Il faudrait probablement restructurer un peu ça. J'hésite.

2023-05-23 18:19 UTC, Arnaud-D commented
En attente de #6457.

2023-10-28 19:01 UTC, Arnaud-D commented
Ça va pouvoir reprendre ici puisqu'on a fusionné #6457 !

2024-11-09 09:06 UTC, Arnaud-D commented
J'ai repris, et j'ai réussi très rapidement à passer les obstacles qui me bloquaient avant la PR que je mentionnais auparavant.

Il reste pas mal de finitions, mais il n'y plus d'obstacle majeur.

2024-11-11 17:08 UTC, Arnaud-D commented
J'ai bien avancé, plus qu'à écrire plus de tests !

2025-11-22 19:50 UTC, artragis commented
On en est où ici? Faut-il passer à la QA?

2025-11-23 06:47 UTC, Arnaud-D commented
Oui, c'est en attente de QA. ^^

On utilise le projet "Suivi des PR" pour suivre ça en détail. C'est comme ça que tu peux avoir la meilleure info (tant que le projet est bien rempli, ce qu'on essaie de faire avec soin).

<img width="386" height="138" alt="image" src="https://github.com/user-attachments/assets/639e6ace-9cab-4740-ab85-18ddcb10fab6" />

2025-11-23 14:20 UTC, artragis commented
# QA

(je mets OK quand le comportement obtenu est celui attendu pour garder une certaine compacité du message)

## Tuto

- lien actif dernier brouillon => OK
- lien actif dernière béta => fonctionnel mais deux évolutions à faire dans le futur: mettre un indicateur quand la béta est pas encore activée, et passer le lien en désactiver quand on désactive la béta
- lien désactivé => OK
- /!\ on peut créer un lien actif dans le passé, ça permet de tester le cas du lien expiré, mais du coup ça réduit l'UX (les utilisateurs peuvent faire l'erreur), à voir si on choisit de mettre ce comportement plus tard.
- Suppression du contenu => OK
- désinscription du user => Comportement indéterminé bien qu'attendu: les tutos qui sont "publiés" sont passés sous externe, les liens sont gardés mais comme personne ne peut se connecter à externe, il y a potentiellement des liens vers des versions "verrolées" (i.e l'auteur a volontairement vandalisé le tuto avant de se barer) qu'on ne trouve pas et qui passent sous le radar. Pour moi, à la désinscription il faudrait voir s'il y a pas multiple auteur. Si finalement il ne reste plus que externe alors on retire les liens.

## article

Résultat identique à tuto, j'ai pas refait le test de désinscription cependant

## Billet


- lien actif dernier brouillon => OK
- lien actif dernière béta > /!\ on ne devrait pas pouvoir le créer, puisqu'un billet ne peut jamais entrer en béta

Voilà pour le fonctionnel

2025-11-23 14:38 UTC, artragis requested changes

2025-11-23 14:38 UTC, artragis commented on zds/tutorialv2/urls/urls_contents.py
> +    path("partage/modifier/<slug:id>/", EditShareableLinkView.as_view(), name="edit-shareable-link"),
Pour celui-là et les suivants préférer `<uuid:id>`  car finalement ce sont des uuid qu'on manipule

2025-11-23 14:38 UTC, artragis commented on zds/tutorialv2/views/display/shared_content.py
> +    def _get_sha(self):
aspect tâtillon donc si tu aimes pas tu peux laisser comme ça, mais j'aurais préféré un ` _select_sha(self) -> str | None`. l'aspect typehint permet de montrer l'intention de retourner None si pas de sha. (et donc de déléguer la 404 plus tard) alors qu'on aurait pu imaginer un ` _select_sha_or_404(self) -> str`  comme on voit souvent dans django.

2025-11-23 14:38 UTC, artragis commented on zds/tutorialv2/views/display/shared_content.py
> +    def _get_sha(self):
Vu que le code est répété deux fois sans aucune modif, hésite pas à faire un mixin

2025-11-29 17:29 UTC, Arnaud-D commented
Merci pour tes retours !

> lien actif dernière béta => fonctionnel mais deux évolutions à faire dans le futur: mettre un indicateur quand la béta est pas encore activée, et passer le lien en désactiver quand on désactive la béta

Très bonnes idées. Par contre, je ne souhaite pas désactiver le lien automatiquement quand on désactive la bêta. L'activation/désactivation, c'est une opération manuelle dans le système que j'ai conçu et je souhaite que ça reste comme ça.

Je préfèrerai un système ou il est "suspendu" pour cause de bêta inactive, et on l'indique avec un petit warning à l'utilisateur, associé à un bouton pour réactiver la bêta facilement.

Bref, c'est du boulot en plus, mais techniquement faisable. ^^

> /!\ on peut créer un lien actif dans le passé, ça permet de tester le cas du lien expiré, mais du coup ça réduit l'UX (les utilisateurs peuvent faire l'erreur), à voir si on choisit de mettre ce comportement plus tard.

C'est vrai que ce n'est pas idéal, mais je n'ai pas tellement le courage de le changer pour cette itération. Ça pourrait se faire côté front avec l'attribut "min" du sélecteur de date, qu'on doit pouvoir donner depuis Django relativement facilement.

>  désinscription du user => Comportement indéterminé bien qu'attendu: les tutos qui sont "publiés" sont passés sous externe, les liens sont gardés mais comme personne ne peut se connecter à externe, il y a potentiellement des liens vers des versions "verrolées" (i.e l'auteur a volontairement vandalisé le tuto avant de se barer) qu'on ne trouve pas et qui passent sous le radar. Pour moi, à la désinscription il faudrait voir s'il y a pas multiple auteur. Si finalement il ne reste plus que externe alors on retire les liens.

Je comprends bien le souci, mais je préfère ne rien faire pour l'instant. Vandaliser le tuto est hypothétique, et on peut aussi imaginer des cas (hypothétiques également) d'auteurs qui reviennent après avoir supprimé leur compte (et qu'on réintègre), de repreneurs tiers, du staff de validation, etc. qui pourraient réutiliser ces choses-là.

On a un cas un peu pareil de données "théoriquement inacessibles" mais en fait pas vraiment avec les images d'ailleurs. Pour l'instant, on a choisi de ne rien faire.

> lien actif dernière béta > /!\ on ne devrait pas pouvoir le créer, puisqu'un billet ne peut jamais entrer en béta

À terme, les billets n'existeront plus en tant que tel (d'ailleurs, cette PR fait partie du programme). Je propose de ne pas implémenter ce blocage, car il irait à contre-courant des convergences techniques entre tous les types de contenus en cours actuellement. Le but de cette convergence est de pouvoir faire la fusion technique de tous les types de contenus facilement.

Dans l'intervalle, qui sera peut-être long, ce sera un peu bizarre, parce qu'on pourra créer des liens qui ne marcheront que dans le futur et bugué en attendant.

---

Sinon, j'ai bien pris tes retours techniques, plus quelques autres bricoles.

---

Au passage, j'ai trouvé un comportement un peu étrange. La date d'expiration, c'est le premier jour d'invalidité du lien, ce qui n'est pas forcément intuitif. On s'attendrait plus à choisir une limite de validité (donc inclus). Je n'ai pas vraiment le courage de changer ça, parce que ça fait réécrire pas mal de choses  - ce qui est sujet à erreurs - et tout revalider.

2025-12-07 17:24 UTC, artragis commented
Ok, au vue de tout ça, je vais donc dire "QA OK".

2025-12-07 17:24 UTC, artragis approved these changes

2025-12-09 07:00 UTC, merged