Gère plus d'erreurs possibles venant de Matomo
zestedesavoir/zds-site pull request #6151
Opened 2021-08-21 18:23 UTC by philippemilink

Cette PR gère plus d'erreurs possibles retournées par Matomo.

Actuellement, sur l'environnement de dev, consulter les statistiques d'un contenu renvoie une erreur 500 `AttributeError 'str' object has no attribute 'items'`. Cela provient du fait que Matomo renvoie des erreurs `You can't access this resource as it requires 'view' access for the website id = 4.` (ce point devra être corrigé dans une autre PR, mais autant en profiter pour gérer correctement ce cas).

J'en ai profité pour corriger quelques détails dans le code auquel j'ai touché:
- faire `data = {}` juste avant de tenter `data.get("message", ...)` n'est pas une très bonne idée...
- pas besoin de f-strings lorsqu'il n'y a rien à formater dans les chaînes de caractères

Si quelqu'un a une idée comment factoriser les deux lignes `self.logger / message.error` qui se répètent (presque identiquement) trois fois, je suis preneur.

### Contrôle qualité

Sur l'environnement de dev, aller à la page des statistiques d'un contenu: la page s'affiche, sans erreur 500.

Comme toujours pour les statistiques, il faudra s'assurer sur la bêta que ça fonctionne bien, même lorsque des statistiques sont disponibles.

2021-08-21 20:00 UTC, artragis requested changes, later dismissed

2021-08-21 20:00 UTC, artragis commented on zds/tutorialv2/views/statistics.py
> +        if all != {}:
ne pas utiliser `all` qui est une fonction par défaut de python (e.g `all(lambda x: x >= 2, [2,3,4,5,6])` )

2021-08-21 20:31 UTC, philippemilink commented on zds/tutorialv2/views/statistics.py
> +        if all != {}:
Corrigé.

2021-09-19 07:42 UTC, Arnaud-D requested changes
QA NOK :x: 

Globalement ça marche, mais il y a des trucs qui me gênent, notamment les messages d'erreur en anglais et cryptique affichés à l'utilisateur. C'est pas forcément dans le périmètre de ta modif, mais comme c'est connexe...

J'ai fait des suggestions pour cacher les détails sur les messages du site. Si on veut garder l'aspect technique visible, il faudrait tout de même l'introduire avec un message d'erreur compréhensible.

----

Pour ce qui est d'éviter la duplication, stocker les messages d'erreur comme attribut de classe est déjà un bon début.

2021-09-19 07:42 UTC, Arnaud-D commented on zds/tutorialv2/views/statistics.py
> +                    self.request, data.get("message", _("Impossible de récupérer les statistiques du site."))
Je serais plutôt partisan d'avoir ici un message pour les humains systématiquement. C'est assez peu accueillant de se payer le message technique en anglais.

```suggestion
                    self.request, _("Impossible de récupérer les statistiques du site.")
```

2021-09-19 07:42 UTC, Arnaud-D commented on zds/tutorialv2/views/statistics.py
> +                            data[index].get("message", _("Impossible de récupérer les statistiques du site.")),
Idem : 

```suggestion
                    self.request, _("Impossible de récupérer les statistiques du site.")
```

2021-09-19 07:42 UTC, Arnaud-D commented on zds/tutorialv2/views/statistics.py
>              self.logger.exception(f"Something failed with Matomo reporting system.")
Ici tu peux enlever le `f` ici aussi.

```suggestion
            self.logger.exception("Something failed with Matomo reporting system.")
```

2021-10-09 08:15 UTC, philippemilink commented
J'ai pris en compte les remarques, ajouté un test pour s'assurer que les erreurs Matomo ne provoquent pas d'erreur 500, et dans le cas où il y a une erreur, ne pas afficher les graphiques (sinon, ça provoquait une erreur JS).

2021-10-17 08:18 UTC, Arnaud-D requested changes
J'aime bien comment la fonction gère ses erreurs par exception et qu'on fasse la gestion de ça ailleurs que dans la fonction elle-même, c'est plus propre.

J'ai juste une gêne sur un point précis, je ne suis pas sûr d'avoir compris ce que le code devrait faire, ça me semble étrange.

2021-10-17 08:18 UTC, Arnaud-D commented on zds/tutorialv2/views/statistics.py
> +            raise Exception(self.logger.exception, _("Erreur inconnue"))
Ce passage m'embête. En testant, j'ai l'impression qu'il remplace toutes les exceptions en "Erreur inconnue", ce qui fait qu'on n'a plus de vrai message d'erreur, y compris dans les log. Si tu retires le `try: ... except`, ça semble fournir les bons messages d'erreur.

2021-10-17 08:18 UTC, Arnaud-D commented on zds/tutorialv2/views/statistics.py
> +        return {}
D'après PyCharm, cette ligne n'est pas atteignable, tu peux l'enlever sans risque. :-)

2021-10-20 17:56 UTC, philippemilink commented on zds/tutorialv2/views/statistics.py
> +        return {}
En effet, corrigé.

2021-10-20 17:57 UTC, philippemilink commented on zds/tutorialv2/views/statistics.py
> +            raise Exception(self.logger.exception, _("Erreur inconnue"))
Bien vu ! Corrigé. (c'est pour ce genre de retours qu'on se rend compte que c'est quand même bien d'avoir un système de QA !)

2021-10-23 08:45 UTC, Arnaud-D commented
QA OK :heavy_check_mark:

2021-10-23 08:45 UTC, Arnaud-D approved these changes

2021-10-23 08:46 UTC, merged