Utilise le KaTeX de zmd pour ZdS
zestedesavoir/zds-site pull request #6182
Opened 2021-10-02 10:50 UTC by philippemilink

Pour être sûr d'avoir vraiment les mêmes versions dans les deux modules.

Fix #6140

### Contrôle qualité

1. `make update`
2. Videz bien votre cache navigateur
3. Créez un commentaire / post / contenu / MP qui contienne des maths, par exemple:
    ```
    Un peu de maths: $\sum_ia_i$

    $$a \cdot x^2 + b \cdot x + c = 0 \quad \Longrightarrow \quad x = \frac {-b \pm \sqrt{b^2 - 4ac}}{2a}$$
    ``` 
    Les maths doivent correctement s'afficher.

Il faut peut-être aussi vérifier que les maths sont bien rendues dans les epubs.

@Situphen J'ai vérifié dans les scripts ansible, on installe bien zmd avant de builder le front.

Par contre, en faisant la PR, j'ai été surpris que `make build-front` ne râle pas, alors que les fichiers CSS de KaTeX étaient manquants...

2021-10-07 15:25 UTC, Situphen commented
J'ai fusionné #6179 qui a touché au script d'installation donc tu as un petit conflit à résoudre. Une fois que ce sera fait je m'occuperai de la QA.

2021-10-07 18:43 UTC, philippemilink commented
Corrigé.

2021-10-07 21:29 UTC, Situphen requested changes

2021-10-07 21:29 UTC, Situphen commented on scripts/install_zds.sh
> +    zds_fold_end
Petit erreur lors du rebasage :)
```suggestion
```

2021-10-08 17:52 UTC, philippemilink commented
Bien vu, corrigé !

2021-11-18 21:43 UTC, Situphen approved these changes
**QA OK !**

2021-11-18 21:44 UTC, merged