Rend publication_watchdog plus résistant aux exceptions
zestedesavoir/zds-site pull request #6264
Opened 2022-03-20 20:44 UTC by philippemilink

Pour éviter que le service `zds-watchdog` entier ne plante lorsqu'une erreur survient dans la boucle qui traite chaque demande de publication, on place le contenu de la boucle dans un bloc `try/except`. De cette façon, les seules erreurs qui pourraientt faire planter le service sont celles qui apparaîtraient dans le bloc `except`.

## QA

Surtout une revue de code, s'assurer que le watchdog continue à fonctionner dans des conditions normales.

2022-03-23 21:59 UTC, Situphen requested changes
Je pense qu'il serait plus lisible d'avoir un seul `try` avec plusieurs `except` comme ceci : 

```py
try:
    content = publication_event.published_object
    # ...
    publicator = PublicatorRegistry.get(publication_event.format_requested)
    publicator.publish(md_file_path, base_name)
except FailureDuringPublication:
    logger.exception("...")
    # ...
except Exception:
    logger.exception("...")
    # ...
```

Aussi, est-ce qu'utiliser `logger.exception` ne permettrait pas d'éviter d'utiliser `logger.error` avec `e_type` et `e_value` en paramètres ?

2022-03-25 14:48 UTC, philippemilink commented
> Je pense qu'il serait plus lisible d'avoir un seul `try` avec plusieurs `except` comme ceci :

En effet, c'est plus clair.

> Aussi, est-ce qu'utiliser `logger.exception` ne permettrait pas d'éviter d'utiliser `logger.error` avec `e_type` et `e_value` en paramètres ?

Je ne connaissais pas, et c'est bien ce dont a besoin ici, comme ça on les détails de l'exception et la backtrace dans les logs.

2022-03-27 21:18 UTC, Situphen commented on zds/tutorialv2/management/commands/publication_watchdog.py
> +            except:
Y a-t-il une raison pour capturer toutes les exceptions et non seulement `FailureDuringPublication` ? :)

2022-03-28 19:29 UTC, philippemilink commented on zds/tutorialv2/management/commands/publication_watchdog.py
> +            except:
Parce qu'autres exceptions que `FailureDuringPublication` peuvent aussi arriver ! :) Celle qui apparaissait avant #6269 était une `OSError` par exemple. Et puis au final le traitement d'une `FailureDuringException` ou d'une autre exception est le même, donc autant factoriser.

2022-03-28 20:37 UTC, Situphen approved these changes, later dismissed

2022-03-28 20:50 UTC, merged