Remplace notre vue de login par le LoginView de Django
zestedesavoir/zds-site pull request #6273
Opened 2022-03-28 12:14 UTC by Arnaud-D

Un des items de  #6246.

Pour l'instant, j'ai refactorisé les tests du login :
* réorganisation des tests existants
* ajout d'un test pour vérifier que l'erreur obtenue pour un utilisateur inactif
* correction d'un bug dans la vue pour passer le test (c'est un soucis truc que j'ai déjà vu passer sur le forum il me semble)

Je fais le passage vers le LoginView de Django dans un second temps. J'aimerais que la CI me confirme que c'est solide avant.

### Contrôle qualité

Bientôt...

2022-04-02 16:08 UTC, Situphen commented on zds/member/views/login.py
> +            if not user.is_active:
Sauf erreur on pourrait utiliser `elif` ici pour gagner un niveau d'indentation et gagner en clarté :)

2022-04-02 16:11 UTC, Situphen commented on zds/member/views/login.py
> +                        # after a browser session.)
Ancien commentaire à supprimer ?

2022-04-02 16:18 UTC, Situphen commented on zds/member/views/login.py
> +                    return render(request, "member/login.html", {"form": form, "csrf_tk": csrf_tk})
Potentiellement un doublon avec la fin de la fonction

2022-04-03 19:56 UTC, Arnaud-D commented on zds/member/views/login.py
> +                    return render(request, "member/login.html", {"form": form, "csrf_tk": csrf_tk})
Obsolète.

2022-04-03 19:57 UTC, Arnaud-D commented on zds/member/views/login.py
> +                        # after a browser session.)
Obsolète.

2022-04-03 19:57 UTC, Arnaud-D commented on zds/member/views/login.py
> +            if not user.is_active:
Obsolète.

2022-04-04 08:05 UTC, Arnaud-D commented
C'est prêt à être QA !

2022-06-02 21:10 UTC, Arnaud-D commented
D'après le commentaire de Migwel dans l'issue ci-dessus : fix #4861.

2022-07-14 15:53 UTC, philippemilink commented
Tu peux mettre à jour la PR et corriger le conflit, stp ?

2022-07-16 16:06 UTC, philippemilink requested changes
Quelques petits détails à corriger et ça devrait être bon.

2022-07-16 16:06 UTC, philippemilink commented on zds/member/forms.py
> +            " Regardez dans vos mails : %(email)s."
N'affiche pas l'e-mail renseigné (c'est potentiellement une fuite de données personnelles).

Ou alors, ne laisse que quelques lettres et remplace les autres par des astérisques (mais ça peut être casse-pieds à faire...)

2022-07-16 16:06 UTC, philippemilink commented on zds/member/forms.py
> +        elif not user.profile.can_read:
Avant la PR, la condition pour tester si un utilisateur est banni était `if not profile.can_read_now()`. La fonction `can_read_now()` semble faire plus de choses que simplement retourner `can_read` (mais elle demande à ce que `user.is_authenticated` soit à `True`, donc il va peut-être falloir l'adapter un peu pour ce cas d'usage (je pense `is_authenticated` vaut encore `False` à ce stade ?)

2022-07-16 16:06 UTC, philippemilink commented on zds/member/tests/views/tests_login.py
> +        self.assertContains(result, escape(LoginForm.error_messages["inactive"][:20]))
Si l'email n'est pas affiché dans le message, plus besoin de ne tester qu'avec le début de la chaîne de caractères.

2022-07-16 16:06 UTC, philippemilink commented on zds/member/forms.py
> +        "invalid_login": _(
`invalid_credentials` au lieu de `invalid_login` (sinon on pense après dans le code qu'il ne s'agit vraiment que du login, et pas du mot de passe).

Le changement est à répercuter aussi dans les tests.

2022-07-18 11:55 UTC, Arnaud-D commented on zds/member/forms.py
> +        "invalid_login": _(
Alors ça, je ne le changerais pas, parce que c'est le choix de Django dans `AuthenticationForm`, je ne fais que le customiser.

2022-07-18 14:45 UTC, Arnaud-D commented on zds/member/forms.py
> +            " Regardez dans vos mails : %(email)s."
J'ai choisi de mettre un renvoi vers le lien "Vous n'avez pas reçu le courriel d'activation ?" à la place.

Initialement, j'ai juste reproduit le comportement actuel, c'est pour ça que j'avais fait l'effort d'avoir ce message d'erreur qui fuite. ^^

2022-07-18 14:45 UTC, Arnaud-D commented on zds/member/tests/views/tests_login.py
> +        self.assertContains(result, escape(LoginForm.error_messages["inactive"][:20]))
Voir l'autre [commentaire](https://github.com/zestedesavoir/zds-site/pull/6273#discussion_r922692865).

2022-07-18 15:25 UTC, Arnaud-D commented on zds/member/forms.py
> +        elif not user.profile.can_read:
J'ai extrait une méthode `is_banned` qui fait le job. Il y avait effectivement un bug pour les bans temporaires, qui ne pouvaient pas se connecter même après expiration du ban.

L'interface n'est pas pratique à l'usage pour les sanctions. Elle laisse trop transparaître le stockage en base de donnée et ça conduit à des erreurs comme celle-ci. On teste `profile.can_read` et `profile.end_ban_read` en direct dans certains templates typiquement. Je vais en faire un ticket, parce que ça pourrait être une refacto avantageuse.

2022-07-18 21:05 UTC, philippemilink requested changes
Tout fonctionne bien, sauf la redirection vers l'URL quand on se connecte.

Pour reproduire :
1. Se connecter
2. Aller sur une page à laquelle on ne peut accéder qu'en étant connecté (éditer un message sur le forum, les paramètres de son compte, etc)
3. Copier l'URL
4. Se déconnecter
5. Coller l'URL. On est redirigé vers la page de connexion, avec le paramètre `next` bien positionné.
6. Se connecter
7. On est redirigé vers l'accueil au lieu de l'URL collée initialement.

J'arrive à causer le bug avec l'URL `http://127.0.0.1:8000/membres/parametres/profil/`.

Il faudrait aussi trouver pourquoi les tests ne montrent pas le problème...

2022-07-19 08:52 UTC, Arnaud-D commented
C'est un bug intéressant. Les tests que j'avais écrits interrogeaient directement la vue en POST, en envoyant correctement le paramètre `next` dans l'URL. Sauf que quand on GET la page, l'attribut `action` du formulaire n'était pas correct : le `next` n'y était pas. Quand on soumet le formulaire comme un humain, l'info n'était alors pas envoyée et on retombait sur la redirection par défaut, la page d'accueil. J'ai ajouté un test qui regarde si on a bien un `action={next}` dans la page.

C'est le genre de choses qui bénéficierait de tests plus englobants, par exemple avec selenium.

2022-07-19 17:26 UTC, philippemilink approved these changes
**QA OK** :heavy_check_mark:

2022-07-19 17:33 UTC, merged