Refactorise le module de MP
zestedesavoir/zds-site pull request #6288
Opened 2022-04-10 16:20 UTC by Arnaud-D

Un des items de #6246.

* Refacto des URL :
  * utilise `path` au lieu de `re_path`
  * utilise les nouveaux motifs en conséquence
  * ajoute un *namespace* `mp` pour ce module
  * change les noms de route pour des noms plus courts, plus simple et visant à être plus clairs
  * change la route pour éditer un message qui requérait l'id et le slug du topic pour agir seulement sur un message (ils ont leur propre id)
  * change la route pour marquer non lu qui avait été faite de manière un peu tordue (par moi, en l'occurrence :D)

* Autres refacto au passageperz
  * bouge du code (`perform_unread`) pour marquer un message comme non lu à un meilleur endroit (c'était surprenant)
  * TODO voir pour refactoriser `perform_unread` parce que c'est illisible

### Contrôle qualité

Coming soon...

2022-07-03 15:54 UTC, philippemilink requested changes
> J'ai mis une redirection pour le lien vers un MP uniquement.

Est-ce qu'on en a vraiment besoin ? Cette URL est utilisée par les extensions navigateurs ou autre ?

2022-07-03 15:54 UTC, philippemilink commented on templates/mp/topic/index.html
> +                {% url "mp:post-unread" message.pk %}
Je serais plus pour `mp:mark-post-unread` pour être sûr de ce que fait cette route (on pourrait penser que ça affiche les messages non-lus, par exemple).

2022-07-03 15:54 UTC, philippemilink commented on zds/mp/urls.py
>      ),
Il ne me semble pas avoir vu de test pour cette route ;)

2022-07-03 19:48 UTC, Arnaud-D commented
Je ne suis pas sûr qu'on en ait besoin, mais c'est le genre de lien qu'on *pourrait* avoir dans ses favoris pour une raison ou une autre. Si on ne redirige pas, le lien est cassé. Comme on peut l'empêcher à pas trop cher, je me suis dit que ça serait mieux de le faire.

Je suis totalement ouvert au fait de l'enlever si tu penses que c'est superflu. Je l'ai mis justement parce que je ne voulais pas qu'on me dise en QA que ça serait mieux de le rajouter. :D

2022-07-03 19:57 UTC, philippemilink commented
> Je ne suis pas sûr qu'on en ait besoin, mais c'est le genre de lien qu'on _pourrait_ avoir dans ses favoris pour une raison ou une autre. Si on ne redirige pas, le lien est cassé. Comme on peut l'empêcher à pas trop cher, je me suis dit que ça serait mieux de le faire.

Ok pour garder cette URL, mais alors ajoute un petit test pour tester que la route fonctionne bien :)

2022-07-04 07:34 UTC, Arnaud-D commented
Voilà qui est fait.

2022-07-04 07:34 UTC, Arnaud-D commented on zds/mp/urls.py
>      ),
Ajouté !

2022-07-04 07:34 UTC, Arnaud-D commented on templates/mp/topic/index.html
> +                {% url "mp:post-unread" message.pk %}
Fait !

2022-07-14 15:27 UTC, philippemilink approved these changes
**QA OK** :heavy_check_mark:

2022-07-14 15:27 UTC, merged