Refactorise les URL du forum
zestedesavoir/zds-site pull request #6295
Opened 2022-05-07 07:21 UTC by Arnaud-D

Lié à #6246.

Au menu de cette refacto des URL du forum :

* utilise un namespace,
* utilise path au lieu de re_path,
* remplacer "editer" par "modifier",

### Contrôle qualité

Vérifier que les forums continuent de fonctionner nominalement (juste exercer toutes les routes).

2022-07-03 16:50 UTC, philippemilink requested changes
La revue de code est OK, mais quand on va sur le profil d'un utilisateur : 
```
NoReverseMatch at /@admin

Reverse for 'topic-find' not found. 'topic-find' is not a valid view function or pattern name.
```
Et en effet les tests sur la vue du profil d'un membre semblent un peu léger (la page de profil n'a pas grand chose à afficher, donc une bonne partie du template n'est pas traitée, par exemple [les topics  du membre](https://github.com/zestedesavoir/zds-site/blob/dev/templates/member/profile.html#L468-L478)).

2022-07-03 19:44 UTC, Arnaud-D commented
J'ai corrigé l'oubli. Je ne souhaite pas rajouter de tests dans cette PR parce que ça fait grossier le scope au-delà de ce que je suis prêt à faire. Ta remarque pourrait peut-être faire l'objet d'un ticket de refactorisation ?

2022-07-14 15:33 UTC, philippemilink submitted a review, later dismissed
**QA OK** :heavy_check_mark:

2022-07-14 15:44 UTC, philippemilink commented
Désolé, le merge n'était pas aussi simple. Il faut mettre à jour les routes dans certains tests :
- https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/tests/tests_feeds.py#L319,L322
- https://github.com/zestedesavoir/zds-site/blob/dev/zds/forum/tests/tests_feeds.py#L154-L157

2022-07-15 19:42 UTC, philippemilink approved these changes
**QA OK** :heavy_check_mark:

2022-07-15 19:43 UTC, merged