Déplace HelpWriting dans les tutos
zestedesavoir/zds-site pull request #6301
Opened 2022-05-07 13:22 UTC by Arnaud-D

Un des items de #6246.

Déplace le modèle HelpWriting dans les tutos

### Contrôle qualité

Appliquer les migrations. 
Tester brièvement que le site fonctionne toujours.

2022-06-19 15:45 UTC, philippemilink commented
Il y a avait un conflit pour mettre à jour la PR, je l'ai résolu depuis l'interface de GitHub, mais pas correctement selon le linter. Je te laisse corriger mes erreurs @Arnaud-D ? ;)

2022-06-19 15:55 UTC, philippemilink requested changes
J'ai un doute sur les deux migrations que tu introduis : j'ai l'impression que ça va supprimer la table correspondante et la recréer ensuite (et donc perdre tout son contenu). J'ai pas encore testé, peut-être que ça fonctionne.

Et puisque tu as bien nommé la deuxième migration, tu pourrais faire de même pour la première :) Et d'ailleurs elles pourraient avoir le même nom, comme ça on saura que ces deux migrations sont liées (quelque chose du style `move_help_writing`).

2022-06-20 20:46 UTC, philippemilink commented
(Et  d'ailleurs la CI ne passe pas à cause des migrations.)

(Étonnant qu'elle soit passée la première fois)

2022-06-26 21:01 UTC, Arnaud-D commented
Bien vu, les migrations ne faisaient pas du tout ce qui était souhaité. Comme ça se passe bien d'habitude, j'ai trop fait confiance à la génération automatique, mais le cas présent est un de ceux qui ne fonctionnent pas, évidemment.

C'est un peu subtil la marche à suivre dans ce cas-ci, vu qu'il faut découpler la base de données et le statut utilisé par l'autodétection, tout en gardant tout bien en ordre. Pour référence, il y a des [infos dans la doc Django](https://docs.djangoproject.com/en/4.0/ref/migration-operations/#separatedatabaseandstate) et surtout je me suis inspiré de [cette réponse sur StackOverflow](https://stackoverflow.com/questions/25648393/how-to-move-a-model-between-two-django-apps-django-1-7).

À tester attentivement. ^^

2022-06-28 21:06 UTC, philippemilink approved these changes
**QA OK** :heavy_check_mark: 

J'ai aussi vérifié ce que faisaient les migrations avec la commande `sqlmigrate` : 
```
% py manage.py sqlmigrate utils 0025_move_helpwriting                                                                                                                                                                                                                                                                
BEGIN;
--
-- Custom state/database change combination
--
ALTER TABLE "utils_helpwriting" RENAME TO "tutorialv2_helpwriting";
COMMIT;
% py manage.py sqlmigrate tutorialv2 0033_move_helpwriting                                                                                                                                                                                                                                                           
BEGIN;
--
-- Custom state/database change combination
--
COMMIT;
```
Donc ça fait bien ce qu'on veut que ça fasse, et uniquement ça ! :)

2022-06-28 21:06 UTC, merged