Option sur le profil : masquer l'activité sur le forum / les commentaires... (#6254)
zestedesavoir/zds-site pull request #6307
Opened 2022-05-18 21:43 UTC by Migwel

Ajout d'une option qui permet de masquer l'activité du forum et commentaires de contenu sur le profil.
Ces informations devraient être cachées à tout utilisateur lambda (ou non connecté) mais doivent rester visibles pour les membres du staff et pour l'utilisateur dont c'est le profil.

Numéro du ticket concerné : #6254

### Contrôle qualité

Scénario 1:
* Se connecter en tant qu'utilisateur lambda User1
* Modifier son profil et cocher la checkbox "Masquer mes activités de forum et commentaires sur mon profil"
* Se déconnecter
* Visiter le profil de User1 sans être connecté
* Vérifier que le contenu relatif au forum et aux commentaires laissé sous les contenus n'est pas affiché

Scénario 2:
* Se connecter en tant qu'utilisateur lambda User1
* Modifier son profil et cocher la checkbox "Masquer mes activités de forum et commentaires sur mon profil"
* Se déconnecter
* Se connecter en tant que membre du staff
* Visiter le profil de User1
* Vérifier que le contenu relatif au forum et aux commentaires laissé sous les contenus est bien affiché

Scénario 3:
* Se connecter en tant qu'utilisateur lambda User1
* Modifier son profil et cocher la checkbox "Masquer mes activités de forum et commentaires sur mon profil"
* Visiter son propre profil
* Vérifier que le contenu relatif au forum et aux commentaires laissé sous les contenus est bien affiché

Scénario 4:
* Se connecter en tant qu'utilisateur lambda User1
*  Vérifier dans son profil que la checkbox "Masquer mes activités de forum et commentaires sur mon profil" n'est pas cochée
* Se déconnecter
* Visiter le profil de User1 sans être connecté
* Vérifier que le contenu relatif au forum et aux commentaires laissé sous les contenus est bien affiché

2022-05-18 22:22 UTC, Situphen requested changes, later dismissed

2022-05-18 22:22 UTC, Situphen commented on zds/member/forms.py
> +        ("hide_forum_activity", _("Masquer mes activités de forum et commentaires sur mon profil")),
Je pense qu'il faut préciser que le masquage s'effectue pour tout le monde sauf soi-même et l'équipe de modération. Sinon, les membres vont regarder leur profil, voir que c'est encore présent et croire que ça ne fonctionne pas alors que ça fonctionne.
```suggestion
        ("hide_forum_activity", _("Masquer mes activités de forum et commentaires sur mon profil (sauf pour moi et l'équipe de modération)")),
```

2022-05-21 19:19 UTC, Arnaud-D commented
QA NOK :heavy_multiplication_x: 

Quelques soucis identifiés :

* Le cadre concernant les commentaires sur les contenus n'est pas masqué quand on active le masquage dans le profil.
* Connecté en tant que simple staff, je n'ai pas vu voir l'activité sur un profil qui masque, alors que je devrais.
* En tant qu'admin, c'est bon.

Je pense que le problème vient de `user.is_staff`, qui vérifie que l'utilisateur est staff au sens de Django (en gros, est admin). Au sens de ZdS, être staff, c'est essentiellement être dans le groupe staff, qui a des permissions particulières. On devrait checker soit le groupe, soit la permission. Je pense que la permission c'est mieux. Tu peux choisir la permission à partir de ce qui est utilisé pour l'encart "Administration et modération" (probablement "member.change_profile" du coup).

2022-05-22 05:50 UTC, Migwel commented
Merci pour la QA (et les suggestions) @Arnaud-D . Je pense que c'est corrigé avec mon dernier commit

2022-05-22 08:52 UTC, Arnaud-D approved these changes
QA OK :heavy_check_mark: 

Dans mes tests, le masquage/non-masquage marche pour le membre lui-même, les non-connectés, les simples membres connectés, les staff et les admins.

2022-05-22 08:52 UTC, Arnaud-D commented on zds/member/views/profile.py
> +        )
C'est une bonne idée d'avoir fait ça. Nos templates ont tendance à être ou devenir compliqués et faire ce que tu as fait est une bonne technique pour qu'ils restent compréhensibles et maintenables.

2022-05-22 08:53 UTC, merged