Vide le stockage local lors de l'envoi avec Ctrl+Entrée
zestedesavoir/zds-site pull request #6310
Opened 2022-05-20 16:39 UTC by Arnaud-D

Fix #6309.

Cette PR corrige un soucis en ajoutant le vidage du stockage local lors de l'envoi avec Ctrl+Entrée dans les formulaires de forum.

J'ai choisi une option qui est normalement compatible avec tous les navigateurs. J'envoie un événement "submit" et le dispatche à l'éditeur, ce qui simule la soumission du formulaire via le bouton. Voir [cette page MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event) pour des infos sur pourquoi ça fonctionne.

Il n'y a pas non plus besoin de vérifier que le formulaire n'est pas vide, parce que c'est comme si on cliquait sur le bouton, avec les mêmes vérifications.

### Contrôle qualité

Astuce pour gagner du temps : changer le paramètre anti-spam `spam_limit_seconds` dans `zds.py` à une valeur plus basse (quelques secondes par exemple).

* Non régression : envoyer un message sur le forum avec le bouton, constater qu'il est bien envoyé et sans erreur, et que la zone de texte est vide (et que le local storage aussi, par conséquent).
* Correction du bug : envoyer un message sur le forum avec Ctrl+Entrée, constater qu'il est bien envoyé et sans erreur, et que la zone de texte (et le local storage) sont vides.

2022-06-19 17:02 UTC, philippemilink requested changes
Le linter râle :
```
blabla/zds-site/assets/js/editor-new.js
  1005:25  error  'SubmitEvent' is not defined  no-undef
```

Chez moi (Debian Sid, Firefox 91.10.0esr), le Ctrl-Enter ne fonctionne pas :
```
Uncaught TypeError: r.dispatchEvent is not a function
    p editor-new.js:1006
```

:x: QA NOK

2022-06-20 08:13 UTC, Arnaud-D commented
Alors, pour la deuxième erreur, j'ai une correction. C'est rien en plus, je ne sais même pas comment j'ai pu me planter comme ça.

Par contre, je me rends compte que la technique que j'utilise est dépréciée dans Firefox (en fait c'est même un bug selon certains) et ne fonctionne pas dans Chrome. On ne peut pas lancer un `submit` avec des événements `untrusted` (lancés depuis un script comme dans mon cas). Il faut que je réfléchisse à une autre solution.

2022-06-20 08:40 UTC, Arnaud-D commented
Bon, normalement ça marche maintenant. J'ai fait la méthode bête et méchante ; ça m'apprendra à vouloir faire le malin avec un `SubmitEvent`. :D

2022-06-20 20:43 UTC, philippemilink approved these changes
**QA OK** :heavy_check_mark:

2022-06-20 20:43 UTC, merged