Unification des adresses de création de contenu
zestedesavoir/zds-site pull request #6324
Opened 2022-05-31 21:20 UTC by Migwel

Fix #5724.

Cette PR modifie les liens de créations de contenu de `.../nouveau-tutoriel` vers `.../nouveau-contenu/TUTORIEL` (et de même pour les articles et billets). Je ne suis pas nécessairement à 100% convaincu que ce type de contenu (i.e. `TUTORIEL`) tout en majuscule est nécessairement beau à voir mais c'est relativement facile à changer si on pense qu'une autre approche est meilleure.

### Contrôle qualité
**Scénario 1:**
* Se connecter
* Cliquer sur "Commencer à rédiger" sur la page d'accueil
**Résultat attendu:** Le lien est de la forme `.../contenus/nouveau-contenu/TUTORIEL`

**Scénario 2:**
* Se connecter
* Cliquer sur Bibliothèque > Accéder à tous les contenus de la bibliothèque
* En bas de la page, cliquer sur "Écrire un tutoriel"
**Résultat attendu:** Le lien est de la forme `.../contenus/nouveau-contenu/TUTORIEL`

**Scénario 3:**
* Se connecter
* Cliquer sur Bibliothèque > Accéder à tous les contenus de la bibliothèque
* En bas de la page, cliquer sur "Écrire un article"
**Résultat attendu:** Le lien est de la forme `.../contenus/nouveau-contenu/ARTICLE`

**Scénario 4:**
* Se connecter
* Cliquer sur Tribune > Tous les billets
* En haut à gauche de la page, cliquer sur "Nouveau billet"
**Résultat attendu:** Le lien est de la forme `.../contenus/nouveau-contenu/OPINION`

**Scénario 5:**
* Se connecter
* Se rendre manuellement sur la page `.../contenus/nouveau-contenu/INCORRECT`
**Résultat attendu:** Le type de contenu choisi par défaut est tutoriel

2022-06-01 08:04 UTC, Arnaud-D commented
À mon avis, tu peux garder cette approche. On risque de changer à nouveau le fonctionnement de la création de contenu quand on s'attaquera à la [nouvelle organisation des contenus](https://github.com/orgs/zestedesavoir/projects/3), donc pas la peine de faire du zèle sur cette amélioration.

2022-06-12 14:29 UTC, Arnaud-D requested changes
Ça fonctionne, j'ai juste une petite remarque sur le code.

2022-06-12 14:29 UTC, Arnaud-D commented on zds/tutorialv2/urls/urls_contents.py
> +    re_path(r"^nouveau-contenu/(?P<created_content_type>[A-Z]+)", CreateContent.as_view(), name="create-content"),
Tu devrais utiliser cette syntaxe, elle est plus lisible et va être généralisée partout (les PR sont en attente de QA) :

```diff
-    re_path(r"^nouveau-contenu/(?P<created_content_type>[A-Z]+)", CreateContent.as_view(), name="create-content"),
+    path("nouveau-contenu/<str:created_content_type>/", CreateContent.as_view(), name="create-content"),
```
Ça ne change a priori rien à la suite de ton code, voire même ça facilitera des évolutions futures.

2022-06-13 18:34 UTC, Migwel commented on zds/tutorialv2/urls/urls_contents.py
> +    re_path(r"^nouveau-contenu/(?P<created_content_type>[A-Z]+)", CreateContent.as_view(), name="create-content"),
Ah oui, j'y avais pensé (car j'ai lu ton billet sur le sujet) mais j'avais utilisé re_path pour être cohérent avec le reste du fichier dans son format actuel. Mais je comprends aussi l'idée d'utiliser le "nouveau" format lorsqu'on ajoute des lignes dans ce fichier. C'est fait

2022-06-15 06:53 UTC, Arnaud-D approved these changes
QA OK :heavy_check_mark: 

Le fait d'aller par défaut sur "Tutoriel" pourrait peut-être être remplacé par une 404, mais comme je disais l'autre jour, pas de zêle inutile. :D

2022-06-15 07:02 UTC, merged