Gère les utilisateurs inexistants dans RedirectOldContentOfAuthor
zestedesavoir/zds-site pull request #6331
Opened 2022-06-05 17:15 UTC by philippemilink

La vue `RedirectOldContentOfAuthor` permet de rediriger les anciennes URLs `/contenus/tutoriels/{user_pk}` vers une URL de la forme `/tutoriels/voir/{user_slug}`. Cependant si `user_pk` recevait l'id d'un utilisateur inexistant, une erreur 500 était levée. Cette PR corrige ce problème et ajoute les tests pour cette vue.

Problème rapporté par Sentry.

### Contrôle qualité

- Utiliser l'ancienne URL pour un utilisateur qui existe, par exemple : http://127.0.0.1:8000/contenus/tutoriels/10/ doit rediriger vers http://127.0.0.1:8000/tutoriels/voir/user1/
- Utiliser l'ancienne URL pour un utilisateur qui n'existe pas, par exemple : http://127.0.0.1:8000/contenus/tutoriels/128/. La page doit renvoyer une 404 et non pas une 500.

2022-07-04 16:32 UTC, Arnaud-D requested changes
Quelques commentaires de maintenabilité seulement. La fonctionnalité fait le job comme il faut.

2022-07-04 16:32 UTC, Arnaud-D commented on zds/tutorialv2/tests/tests_views/tests_redirect.py
> +        self.assertEqual(response.status_code, 404)
Pourquoi ne nommes-tu pas les *paths* lors de leur définition pour pouvoir les `reverse` dans ce test ? Tu pourrais tout reverser : l'URL de requête et la redirection.

Un path qui ne matche pas renvoie une 404 de par le fonctionnement de Django, t'as deux lignes qui testent essentiellement le code de Django, là. :D

Je ne suis pas sûr que le `follow=True` soit nécessaire aussi, vu qu'on ne fait rien du contenu de la réponse.

2022-07-04 16:32 UTC, Arnaud-D commented on zds/tutorialv2/views/redirect.py
> +    /contenus/tutoriels/user_pk/ => /tutoriels/voir/user_slug/
Je comprends l'idée du commentaire, mais ça me paraît un bon moyen de faire un commentaire qui devient faux à terme. Et ce terme est déjà en vue : on changera certainement les URL canoniques pour la nouvelle organisation des contenus.

C'est certes moins ergonomique, mais peut déjà voir l'information en question en lisant le code de la vue et le fichier `urls_*.py` qui va bien.

2022-07-15 16:20 UTC, philippemilink commented on zds/tutorialv2/tests/tests_views/tests_redirect.py
> +        self.assertEqual(response.status_code, 404)
> Pourquoi ne nommes-tu pas les paths lors de leur définition pour pouvoir les reverse dans ce test ? Tu pourrais tout reverser : l'URL de requête et la redirection.

En effet, c'est mieux.

> Un path qui ne matche pas renvoie une 404 de par le fonctionnement de Django, t'as deux lignes qui testent essentiellement le code de Django, là. :D

C'était en effet le cas pour `/contenus/foo` car les types de contenus possibles dans l'URL `/contenus/<type>` sont listés en dur dans le code, mais pas pour le test de l'utilisateur inexistant, qui teste justement une partie de la vue `RedirectOldContentOfAuthor` (et c'est ce test manquant qui fait qu'on a besoin de cette PR !)

> Je ne suis pas sûr que le follow=True soit nécessaire aussi, vu qu'on ne fait rien du contenu de la réponse.

En effet, sauf pour la dernière où l'erreur 404 est levée par la vue redirigée.

2022-07-15 16:21 UTC, philippemilink commented on zds/tutorialv2/views/redirect.py
> +    /contenus/tutoriels/user_pk/ => /tutoriels/voir/user_slug/
Ok, j'ai enlevé cette modification.

2022-07-18 21:00 UTC, Arnaud-D commented on zds/tutorialv2/tests/tests_views/tests_redirect.py
> +        response = self.client.get("/contenus/tutoriels/3954", follow=True)
Ici, tu reverses pas ?

2022-07-18 21:12 UTC, philippemilink commented on zds/tutorialv2/tests/tests_views/tests_redirect.py
> +        response = self.client.get("/contenus/tutoriels/3954", follow=True)
Bien vu. Je ne sais pas pourquoi en le faisant je pensais que puisque l'utilisateur 3954 n'existait pas, ça ne fonctionnerait pas...!

2022-07-19 08:54 UTC, Arnaud-D approved these changes
QA OK :heavy_check_mark:

2022-07-19 08:55 UTC, merged