Rajout de champ mot de passe aux pages de Désinscription et de changements d'email
zestedesavoir/zds-site pull request #6334
Opened 2022-06-05 20:12 UTC by Migwel

Fix #5372.

Change la façon dont on gère les confirmations par mot de passe en ajoutant un FieldPasswordMixin. Et utilise ce mixin pour ajouter une confirmation aux pages de désincriptions et celle de changement d'email.

### Contrôle qualité
**Scénario 1:**
* Se connecter
* Se rendre sur la page de modification de nom d'utilisateur et d'email
* Essayer de modifier son nom d'utilisateur ou email sans remplir le champ de mot de passe
**Résultat attendu:** la soumission ne fonctionne pas, le mot de passe est un champ obligatoire

**Scénario 2:**
* Se connecter
* Se rendre sur la page de modification de nom d'utilisateur et d'email
* Essayer de modifier son nom d'utilisateur ou email en fournissant un mot de passe incorrect
**Résultat attendu:** la mise à jour échoue avec un message mentionnant que le mot de passe est incorrect

**Scénario 3:**
* Se connecter
* Se rendre sur la page de modification de nom d'utilisateur et d'email
* Essayer de modifier son nom d'utilisateur ou email en fournissant le bon mot de passe
**Résultat attendu:** La mise à jour fonctionne

Répéter ces trois scénarios pour les pages de déinscription et celle de changement de mot de passe.

2022-06-05 20:28 UTC, philippemilink reviewed
Joli travail ! Je viens juste de parcourir rapidement le code et je me demandais si tu ne pouvais pas mettre le `password = forms.CharField(...)` que tu as rajouté dans chaque formulaire, directement dans `FieldPasswordMixin` ?

2022-06-06 07:12 UTC, Migwel commented
> Joli travail ! Je viens juste de parcourir rapidement le code et je me demandais si tu ne pouvais pas mettre le `password = forms.CharField(...)` que tu as rajouté dans chaque formulaire, directement dans `FieldPasswordMixin` ?

Je ne sais plus pourquoi, quand j'avais essayé cette approche ça n'avait pas fonctionné. Mais je viens de ré-éssayer ça et ça fonctionne correctement. Mais j'ai dû le faire hériter de `forms.Form` et donc ça m'a l'air d'être plus une vraie classe parent plutôt qu'un mixin donc je l'ai renommé

2022-06-16 18:49 UTC, Arnaud-D requested changes
QA NOK :heavy_multiplication_x: 

C'est relativement mineur, mais un peu gênant d'un point de vue UX. Je trouve que les labels pour le changement de mot de passe sont confus. On a "Mot de passe (confirmation)" d'un côté et "Confirmer le nouveau mot de passe" de l'autre. Je pense qu'il faudrait voir apparaître "ancien mot de passe" pour que ça soit bien clair.

Quelques autres commentaires concernant plutôt le code.

Sinon, ça fonctionne.

2022-06-16 18:49 UTC, Arnaud-D commented on zds/member/forms.py
> +        super(UnregisterForm, self).__init__(*args, **kwargs)
Ici, c'est probablement possible de juste écrire `super()` sans plus de précisions.

2022-06-16 18:49 UTC, Arnaud-D commented on zds/utils/forms.py
> +    def check_correct_password(self, cleaned_data):
Ça ne serait pas mieux d'écrire une méthode `clean()` dans ce mixin, qui serait appelée par les différents utilisateurs dans leur propre méthode clean, via `super().clean()` (utiliser l'héritage, donc), plutôt que d'appeler cette méthode là explicitement ?

T'en penses quoi ?

2022-07-27 20:24 UTC, Migwel commented on zds/utils/forms.py
> +    def check_correct_password(self, cleaned_data):
Ah oui, c'est carrément mieux, j'envoie çá

2022-07-30 19:44 UTC, Arnaud-D approved these changes

2022-07-30 19:56 UTC, merged