ajout de la syntax fix #XXXX dans le template
zestedesavoir/zds-site pull request #6338
Opened 2022-06-18 08:50 UTC by antoineB24

fix #6308

### Contrôle qualité

  - faite une nouvelle pull request
  - et voyez la nouvelle syntax `fix #XXXX` 

(ce n'est pas super, je pourrai le changer si vous le voulez)

2022-06-18 12:44 UTC, philippemilink requested changes
Les petits changements que j'ai indiqués et ce sera bon ! :)

2022-06-18 12:44 UTC, philippemilink commented on .github/pull_request_template.md
> +fix #XXXX
```suggestion
<!-- Remplacez XXXX par le numéro de ticket corrigé par vos changements : GitHub fermera le ticket mentionné automatiquement (voir https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue pour plus de détails). Supprimez la ligne s'il n'y a pas de ticket associé. --!>
Fix #XXXX 
```

2022-06-18 12:45 UTC, Arnaud-D submitted a review, later dismissed
Quelques remarques à prendre en compte pour rendre ça impeccable.

2022-06-18 12:45 UTC, Arnaud-D commented on .github/pull_request_template.md
> +<!-- Remplacez XXXX par le numéro de ticket concerné (si il y en a un) , github fermera l'issus concerné automatiquement  (voir https://docs.github.com/en/issues/tracking-your-work-with-issues/linkin
Quelques suggestions et corrections :
* le numéro de ticket concerné (si il y en a un) =>  le numéro de l'éventuel ticket concerné
* github => GitHub
* l'issus concerné => le ticket (pas besoin de mettre concerné, on sait duquel on parle), voire mieux utiliser "celui-ci", vu qu'il y est fait référence avant.
* d'info => d'informations (on n'est pas à quelques lettres près)
* Fais de ce qui est entre parenthèse une phrase à part entière (et ne pas oublier le point à la fin de cette phrase, ainsi que la première).

2022-06-18 12:45 UTC, Arnaud-D commented on .github/pull_request_template.md
> +fix #XXXX
C'est vraiment un détail, mais "Fix" avec une majuscule me plairait plus. :D

2022-06-19 15:40 UTC, philippemilink approved these changes
**QA OK** :heavy_check_mark:

2022-06-19 15:57 UTC, merged