Améliore le sommaire de la barre latérale
zestedesavoir/zds-site pull request #6344
Opened 2022-06-26 16:36 UTC by jeanlapostolle

Ajoute une couleur bleue au survol de l'élément, recentre le texte ajoute une bordure entre les éléments.

Fix #6176 

### Contrôle qualité

Vérifier sur la barre latérale d'un contenu : 
 -  la présence de bordure entre les titres
 - le texte est aligné verticalement
 - l'élément se bleute au survol
 - 
![image](https://user-images.githubusercontent.com/8135797/175824497-abe15fcb-0f22-405a-9e36-059c928960f1.png)

2022-07-03 14:34 UTC, philippemilink requested changes
Ça me semble bon, mais il un truc qui me dérange : seul le texte fait office de lien. C'est-à-dire que même lorsqu'on arrive dans la zone qui active le bleutage de l'élément, il faut être précisément sur le texte avoir le curseur "lien cliquable". Ce serait bien plus ergonomique si ce curseur apparaissait sur toute la zone surlignée, pour bien indiquer que cliquer n'importe où dans la zone surlignée a un effet.

Un `cursor: pointer;` bien placé devrait suffire.

2022-09-08 08:36 UTC, Arnaud-D commented
@jeanlapostolle, est-ce que tu penses retravailler cette PR ?

2022-09-08 09:53 UTC, jeanlapostolle commented
@Arnaud-D Oui, c'est en haut de ma ToDoList de Septembre.

2022-10-11 20:08 UTC, Arnaud-D commented
C'est en haut de ta todo list d'octobre aussi ? :D

2022-11-27 21:53 UTC, Situphen commented
J'ai discuté avec @jeanlapostolle et il n'a pas le temps de travailler sur cette PR en ce moment donc je l'ai étiquetté Zombie et marquée comme étant en attente de reprise.

2023-04-15 15:57 UTC, philippemilink commented
Je ferme, la PR a été reprise par #6458.

2023-04-15 15:57 UTC, closed without merging