Stop le décalage de l'astuce
zestedesavoir/zds-site pull request #6345
Opened 2022-06-26 20:52 UTC by jeanlapostolle

Fix #6247 

### Contrôle qualité

- Ouvrir une page avec le nouvel éditeur
- Recharger la page jusqu'à avoir une aide d'une ligne
- Mettre l'éditeur en Apreçu sur le côté
- Vérifier que l'astuce n'est pas décalé.

2022-06-27 20:52 UTC, philippemilink requested changes
QA NOK :x: 

C'est bon pour le nouvel éditeur, mais lorsque l'ancien éditeur est utilisé, on perd les marges à gauche et à droite du bandeau de l'astuce (à gauche avec la PR, à droite sans) : 
![image](https://user-images.githubusercontent.com/5911232/176033483-f0e2b79b-f8f9-4f7a-a5b0-5827d4696693.png)

2022-09-08 08:36 UTC, Arnaud-D commented
@jeanlapostolle, est-ce que tu penses retravailler cette PR ?

2022-09-08 09:54 UTC, jeanlapostolle commented
@Arnaud-D Oui, c'est en haut de ma ToDoList de Septembre.

2022-10-11 20:09 UTC, Arnaud-D commented
C'est en haut de ta todo list d'octobre aussi ? :D

2022-11-27 21:53 UTC, Situphen commented
J'ai discuté avec @jeanlapostolle et il n'a pas le temps de travailler sur cette PR en ce moment donc je l'ai étiquetté Zombie et marquée comme étant en attente de reprise.

2023-07-06 18:27 UTC, closed without merging