Permet d'amener à la fin d'un topic qu'on a déjà lu
zestedesavoir/zds-site pull request #6352
Opened 2022-07-11 11:57 UTC by artragis

(j'avoue ne pas avoir vu si un ticket existait)

### Contrôle qualité

#### Op only

- avec un premier utilisateur créer un topic
- avec un second visitez le topic
- Repartir à l'accueil des forum
- se servir du lien dans la sidebar pour revenir au message
- **On est mené au message d'origine, pas d'erreur**

#### Autre non lu

- faites vivre la discussion en utilisant toujours le lien de la side bar pour s'y rendre jusqu'à ce que la page 2 apparaisse
- lire le dernier message avec l'utilisateur 2
- Repartir à l'accueil des forum
- se servir du lien dans la sidebar pour revenir au message
- **On est mené au dernier message (page 2 donc), pas d'erreur**

2022-07-15 15:49 UTC, philippemilink requested changes
Rapport de QA
--------------------
 
Pas OK :x: 

- Avec `user1` créer un topic
- Avec `user2` poster un message dans ce topic
- Avec `user5`, poster un message dans ce topic
- Poster des messages en alternant les utilisateurs `user1` et `user5`, jusqu'à obtenir une deuxième page (note : pour tester, j'ai réduit le paramètre `posts_per_page` à 16)
- Le lien du sujet dans la barre latérale de `user5` mène toujours à un message de la première page, même s'il poste un message sur la deuxième page
- Après que `user2` lise tous les nouveaux messages du sujet, en consultant les deux pages, le lien du sujet dans la barre latérale mène toujours à un message de la première page.

Concernant la revue de code, il est sans doute possible de factoriser les premières lignes communes de chaque test : 
```py
author = ProfileFactory().user
reader = ProfileFactory().user
topic = TopicFactory(author=author, forum=ForumFactory(category=ForumCategoryFactory(), position_in_category=1))
```

2022-07-25 18:39 UTC, artragis commented
fixed

2022-07-26 17:35 UTC, philippemilink submitted a review, later dismissed
Rapport de QA
--------------------
 
Pas OK :x: 

1. Avec `user1` créer un topic
2. Avec `user2` poster un message dans ce topic
3. Avec `user5`, poster un message dans ce topic
4. Avec `user1`, aller sur le sujet : on se prend une erreur `MultipleObjectsReturned at /forums/ get() returned more than one Post -- it returned 2!`.

Ça montre aussi qu'il manque un test, puisque actuellement tous les tests passent.

2022-07-26 17:36 UTC, artragis commented
Bien vu.

2022-07-26 17:36 UTC, artragis commented
Je ferai ça demain du coup.

2022-07-30 19:55 UTC, Arnaud-D commented
@artagis T'as un petit soucis de lint back. Sinon, c'est prêt pour repasser en QA ?

2022-07-30 20:33 UTC, artragis commented
Oui ça me semble prêt. Je fais le lint demain.

2022-08-31 12:26 UTC, Arnaud-D approved these changes
QA OK :heavy_check_mark:

2022-08-31 12:32 UTC, merged