Premier jalon pour la classification par objectif des contenus
zestedesavoir/zds-site pull request #6354
Opened 2022-07-15 16:45 UTC by Arnaud-D

Cette PR implémente les bases de la nouvelle classification des publications. J'ai appelé ça "classification par objectifs", vu qu'il n'y avait pas vraiment de nom jusqu'à présent. En lien avec le [groupe de travail](https://zestedesavoir.com/forums/sujet/16067/les-resultats-du-groupe-de-travail-organisation-des-publications/) et le [projet GitHub associé](https://github.com/orgs/zestedesavoir/projects/3).

Au menu :
- un modèle pour enregistrer les objectifs (c'est-à-dire les catégories) et un champ pour pouvoir les associer aux publications (en many-to-many) ;
- une interface d'admin pour la gestion des objectifs (les créer, renommer, etc.) ;
- une vue pour gérer la classification pour une publi seule (accessible au staff uniquement pour le moment, et on enregistre également l'action dans le journal des événements, le bouton est dans la section "Éditorialisation" de la barre latérale) ;
- des tests de tout ça et ce qu'il faut pour aller avec (factory notamment) ;
- et même des fixtures pour l'environnement de dév !

J'ai choisi de mettre le formulaire pour le staff seulement, avec la même permission que tout ce qui est édition de publications des tiers par le staff.

Niveau orga du code, j'ai choisi de mettre la vue et le formulaire dans un seul fichier `goals.py`, alors que les autres vues de formulaire sont séparées en forms d'un côté et views de l'autre. Je pense que mettre les deux au même endroit est plus facile niveau maintenance, vu qu'il n'est pas prévu que le formulaire soit réutilisé ailleurs dans le futur.

Sinon, ça a été l'occasion d'étendre le système de journal d'événements pour la première fois, et c'est plutôt facile à faire, donc bon point de côté-là.

### Contrôle qualité

Avant toute chose, appliquer les migrations.

Pour l'administration des objectifs :
* se loguer en tant qu'admin et aller dans l'interface d'administration ;
* créer des catégories, en supprimer, etc ;
* regarder qu'elles sont bien créée et qu'elles apparaissent dans la modale d'éditorialisation.1

Pour la gestion des objectifs sur un contenu :
* se loguer en tant que staff ;
* aller sur un contenu et modifier les objectifs du contenu ;
* vérifier que c'est bien pris en compte en allant voir les valeurs initiales dans la modale (videz bien votre cache pour être sûr) ;
* vérifier aussi que le journal d'événement a bien un enregistrement pour l'action.

Petites vérifications de permission :
- vérifier qu'on n'est bien redirigé vers le login quand on n'est pas logué et qu'on essaie d'accéder à la vue en question (voir le diff pour la nouvelle route) ;
- vérifier que le formulaire n'est pas affiché pour les non-staff et qu'on se prend une 403 si on essaie d'utiliser le formulaire malgré tout ;
- vérifier qu'on a bien une erreur quand on trifouille le formulaire pour avoir des valeurs invalides.

### Après cette PR

Ce premier jalon n'est pas très utile en soi et ne permet pas d'avancer outre mesure. Pour la suite, j'envisage une interface permettant l'édition en masse, ce qui facilitera le classement quand la fonctionnalité sera déployée en production.

2022-07-16 16:22 UTC, philippemilink requested changes
Quelques petites corrections à faire, mais beau boulot ! :+1:

2022-07-16 16:22 UTC, philippemilink commented on templates/tutorialv2/includes/editorialization.part.html
> +            Modifier les objectifs
```suggestion
            {% trans "Modifier les objectifs" %}
```

2022-07-16 16:22 UTC, philippemilink commented on zds/tutorialv2/models/events.py
> +
Factorise avec le receveur de signal suivant (puisqu'ils effectuent exactement la même action) ?

2022-07-16 16:22 UTC, philippemilink commented on zds/tutorialv2/views/goals.py
> +    modal_form = True
C'est bien une vue qui ne sert qu'à gérer le formulaire de la modale de choix des objectifs ? Dans ce cas, il faut ajouter `http_method_names = ["post"]`, par exemple, pour empêcher qu'elle ne soit appelée en GET.

2022-07-18 11:18 UTC, Arnaud-D commented on templates/tutorialv2/includes/editorialization.part.html
> +            Modifier les objectifs
BIen vu, c'est corrigé.

2022-07-18 11:27 UTC, Arnaud-D commented on zds/tutorialv2/views/goals.py
> +    modal_form = True
Ouais, bonne idée ! C'est fait.

2022-07-18 11:33 UTC, Arnaud-D commented on zds/tutorialv2/models/events.py
> +
Je préfère ne pas le faire. Le code est similaire, mais c'est un hasard. Il n'y a pas de raison fondamentale qui fait que ces événements ont les mêmes attributs (ici, le minimum vital envisagé pour le journal d'événements), ça pourrait évoluer à l'avenir. C'est plus facile à changer si on ne fusionne pas des choses trop tôt.

2022-07-18 11:34 UTC, Arnaud-D commented
Voilà, j'ai pris en compte deux remarques et la troisième j'argumente sur pourquoi je préfère ne pas faire comme ça.

2022-07-18 21:33 UTC, philippemilink requested changes
Tout fonctionne bien, mais le bouton *Modifier les objectifs* et la modale associée sont visibles lorsque je suis connecté avec un utilisateur et que je vais sur les contenus rédigés par cet utilisateur.

2022-07-19 09:23 UTC, Arnaud-D commented
Ah oui, j'avais complètement oublié ça. C'est corrigé.

2022-07-19 17:40 UTC, philippemilink approved these changes
**QA OK** :heavy_check_mark:

2022-07-19 17:44 UTC, merged