N'envoie pas de MP lors de la dépublication de contenu sans auteur inscrit
zestedesavoir/zds-site pull request #6356
Opened 2022-07-15 19:37 UTC by philippemilink

Fix #6353

### Contrôle qualité

Le scénario qui pose problème :
1. Avec un utilisateur A, créer et publier un billet
2. En tant qu'utilisateur A, se désinscrire (*Paramètres* > *Désinscription*)
3. Se connecter en tant qu'`admin` et *modérer* ce billet (dans la section *Administration* de la colonne à gauche du billet)
4. On revient sur la liste des billets et tout fonctionne comme attendu

Vérifier que le comportement normal fonctionne toujours :
1. Avec un utilisateur A, créer et publier un billet
2. Se connecter en tant qu'`admin` et *modérer* ce billet (dans la section *Administration* de la colonne à gauche du billet)
3. On revient sur la liste des billets et tout fonctionne comme attendu
4. Se connecter avec l'utilisateur A, il a bien reçu un MP le notifiant de la modération et la dépublication du billet

Vérifier que ça fonctionne toujours lorsqu'il y a plusieurs auteurs :
1. Avec un utilisateur A, créer un billet, y ajouter l'utilisateur B comme auteur, publier le billet
2. En tant qu'utilisateur A, se désinscrire (*Paramètres* > *Désinscription*)
3. Se connecter en tant qu'`admin` et *modérer* ce billet (dans la section *Administration* de la colonne à gauche du billet)
4. On revient sur la liste des billets et tout fonctionne comme attendu
4. Se connecter avec l'utilisateur B, il a bien reçu un MP le notifiant de la modération et la dépublication du billet

Refaire les scénarios :
- en *dépubliant* le billet
- avec un tutoriel et en *dépubliant*
- avec un article et en *dépubliant*

2022-07-20 11:28 UTC, Arnaud-D requested changes
Je n'ai encore pas testé la fonctionnalité, mais j'ai une remarque sur l'implémentation.

2022-07-20 11:28 UTC, Arnaud-D commented on zds/tutorialv2/views/validations_opinions.py
> +            elif versioned.authors.first().username != settings.ZDS_APP["member"]["external_account"]:
Je m'interroge sur la meilleure solution. Je pense que ça serait plus simple et robuste de filtrer versioned.authors pour ne garder que ceux pour qui `is_reachable` est vrai (voir le module de MP pour ça). La solution que tu proposes ne couvre pas tout à fait ce qui déclenche l'erreur, à savoir un des destinataires du nouveau MP, `external`, est dans le groupe bot. Tester `is_reachable` garantit à 100% l'absence de l'exception correspondante.

On pourrait aussi imaginer des cas bizarres où un contenu est repris, licence le permettant, et où on aurait `external` en plus d'un autre auteur (c'est une hypothèse bien sûr, rien n'oblige à avoir ce cas). Regarder le premier auteur s'il n'y en a pas qu'un seul me paraît alors une potentielle source de bugs tordus à l'avenir.

Sinon une solution simplificatrice, c'est de virer ce concept de `is_reachable` et d'autoriser à tout le monde d'envoyer des MP aux bots, même si ça peut être découragé par ailleurs (en ne faisant pas apparaître dans les suggestions d'ajout au MP, pas sur le profil du bot, etc.). Actuellement, on a une solution intermédiaire, vu que Clem est déjà dans un certain nombre de MP auto et qu'on peut y écrire.

2022-07-23 17:11 UTC, philippemilink commented on zds/tutorialv2/views/validations_opinions.py
> +            elif versioned.authors.first().username != settings.ZDS_APP["member"]["external_account"]:
J'ai ajouté une fonction `filter_reachable()` qui ne garde que les utilisateurs à qui on peut envoyer des MPs.

2022-07-24 09:43 UTC, Situphen commented on zds/tutorialv2/views/validations_opinions.py
> +                        versioned.authors.all(),
Ça ne devrait pas être `recipients` ici ?
```suggestion
                        recipients,
```

2022-07-24 09:43 UTC, Situphen commented on zds/tutorialv2/views/validations_opinions.py
> +                            versioned.authors.all(),
Idem ?
```suggestion
                            recipients,
```

2022-07-24 11:43 UTC, philippemilink commented on zds/tutorialv2/views/validations_opinions.py
> +                        versioned.authors.all(),
Bien vu, corrigé !

2022-07-24 11:44 UTC, philippemilink commented on zds/tutorialv2/views/validations_opinions.py
> +                            versioned.authors.all(),
Idem, corrigé !

2022-07-24 12:37 UTC, Situphen approved these changes
**QA OK** Ça fonctionne correctement !

2022-07-24 21:03 UTC, Arnaud-D approved these changes

2022-07-24 21:03 UTC, merged