Track la recheche en tant que telle dans matomo
zestedesavoir/zds-site pull request #6362
Opened 2022-07-26 16:44 UTC by artragis

Le but de cette PR est de changer la manière dont le moteur de recherche est tracké car matomo permet d'avoir un rapport spécifique à cet usage :

![search](https://user-images.githubusercontent.com/1523653/181062971-c602c213-0dd0-4175-abf1-d7021936172c.png)
![search_report](https://user-images.githubusercontent.com/1523653/181063046-0ee87ce7-afc7-4745-819e-9486462e16ba.png)

N'ayant pas d'environnement avec la recherche installée, je n'ai pas pu tester

### Contrôle qualité

Dans un environnement qui a la recherche ET matomo,
faire des recherches avec des mots différents, visitez les résultats, naviguer entre les pages.

S'assurer que : 

1. ça ne génère pas d'erreur
2. ça envoie des données à matomo pour ce rapport

2022-07-26 18:11 UTC, philippemilink requested changes
Ça peut être pratique comme fonctionnalité ! 

Je viens juste de parcourir rapidement le code, je ferai la QA plus tard en déployant sur la bêta.

2022-07-26 18:11 UTC, philippemilink commented on zds/middlewares/matomomiddleware.py
> +                if p.startswith("/rechercher") and response.context_data["object_list"]:
Utilise `reverse("search:query")` au lieu de `"/rechercher"`.

2022-08-14 14:22 UTC, philippemilink commented on zds/middlewares/matomomiddleware.py
> +                    p.contains(reverse("search:query"))
```suggestion
                    reverse("search:query") in p
```

Sinon on se prend un `AttributeError 'str' object has no attribute 'contains'`.

2022-08-14 14:40 UTC, artragis commented on zds/middlewares/matomomiddleware.py
> +                    p.contains(reverse("search:query"))
c'est modifié.

2022-08-15 20:37 UTC, artragis commented
Le résultat actuel c'est ça : 
![rapport-recherche](https://user-images.githubusercontent.com/1523653/184713411-d50450d4-4d09-4bf1-bbe7-f4c6376b1b90.png)

Si le rapport "nombre de mot clef sans résultat" est vide c'est parce que je n'arrive pas à avoir un résultat fiable ET performant pour l'instant pour compter le nombre de résultat.
L'objet "Search" qui est retourné par le sdk elastik est iterable mais ne surcharge pas `__len__` ce qui impose de faire une requête `count` à elastic, ce qui peut être long, juste pour une stat.

Je pense avoir une astuce à base de paginator/page_count. mais pour l'instant j'ai pas eu le temps de l'implémenter.

2022-08-16 11:12 UTC, philippemilink commented
Je merge ou bien j'attends que tu tentes quelque chose pour *nombre de mot clef sans résultat* ?

2022-08-16 14:46 UTC, artragis commented
je tente un truc  ce soir sur la béta, si ça marche pas on mergera

2022-08-16 17:58 UTC, artragis commented
après test, ça fonctionne :
![mots clefs sans resultat](https://user-images.githubusercontent.com/1523653/184947354-6d35774f-4990-460c-a7c7-b1396f064516.png)

2022-08-16 18:34 UTC, philippemilink approved these changes
**QA OK** ✔️

2022-08-16 18:35 UTC, merged