Vérifie que la présence des comptes essentiels au démarrage de l'application
zestedesavoir/zds-site pull request #6369
Opened 2022-07-31 11:20 UTC by Arnaud-D

Fix #4872.

Reprise de #4873.

- Ajoute une vérification de la présence des comptes essentiels (bot + auteur externe + anonyme) au démarrage de l'application
- Simplifie la récupération des comptes bots dans tout le code
- Déplace les bots dans un fichier de fixtures dédié.

### Contrôle qualité

Vérifier le déclenchement de l'erreur :
- Supprimer la base de donnée (locale)
- Appliquer les migrations (sans les fixtures)
- Vérifier qu'on a une exception qui correspond à l'absence d'un compte

Ensuite, vérifier l'absence de l'erreur :
- générer les fixtures (ça importe les comptes essentiels)
- vérifier que ça démarre comme il faut

2022-08-14 20:29 UTC, philippemilink requested changes
### Rapport de QA

**OK** ✔️ 

Juste le petit changement demandé et je merge (au passage, un rebase serait le bienvenu !).

2022-08-14 20:29 UTC, philippemilink commented on zds/utils/misc.py
> +            raise Exception(f"User {username!r} does not exist. You must create it to run the server.")
Tu pourrais préciser dans le message la commande à lancer pour charger les fixtures qui vont bien pour avoir les comptes nécessaires.

2022-08-15 07:40 UTC, Arnaud-D commented on zds/utils/misc.py
> +            raise Exception(f"User {username!r} does not exist. You must create it to run the server.")
Je ne vais pas mettre la commande, mais un message spécifique pour le dév. J'ai pas envie de metttre la doc directement dans le message d'erreur et la solution est 100% spécifque à notre environnement de dév et le choix des fixtures.

On est obligé de charger bots + group + users si on veut charger les fixtures des bots, à cause des dépendances. Voire même d'autres choses.

2022-08-15 09:17 UTC, philippemilink commented on zds/utils/misc.py
> +            raise Exception(f"User {username!r} does not exist. You must create it to run the server.")
Ce qui m'embête, c'est que je n'arrive à trouver nul part les instructions pour régler ce problème lors du déploiement d'une version de production. Même dans nos scripts Ansible on ne fait rien de la sorte (ça a du être fait à la main la première fois et il n'y a plus eu besoin de le faire depuis). Il me semblait que dans notre doc on avait une page ou section *Déploiement en production* mais je ne la trouve plus non plus.

J'ai l'impression que celui qui déploiera à partir de zéro ZdS pour de la production se prendra forcément le message d'erreur en suivant les instructions d'installation, et il n'y aura ensuite aucune explication sur comment régler le problème (quels sont les comptes requis ? quels attributs doivent-ils avoir ?).

Je suis d'accord de pas mettre la doc dans le message d'erreur, juste un pointeur vers la doc. Peut-être rajouter [ici](https://docs.zestedesavoir.com/utils/fixture_loaders.html) une section qui décrit les données de base qu'il faut obligatoirement avoir ?

(en me relisant : pourquoi pas ne pas créer automatiquement les comptes lorsque la fonction de check se rend compte qu'ils n'existent pas ?)

2022-08-15 10:30 UTC, Arnaud-D commented on zds/utils/misc.py
> +            raise Exception(f"User {username!r} does not exist. You must create it to run the server.")
Je préfère ne pas ajouter de lien vers la doc, parce que c'est typiquement le lien qui se retrouvera obsolète parce qu'on oublie de le changer. Là, on cherche "fixtures" dans la doc et on trouve ce qu'on veut, donc pour moi l'expérience est proche. ^^

On pourrait faire des choses automatiquement... mais je ne me vois pas le développper à un horizon prévisible. Cette PR est juste une reprise de PR zombie pour que le boulot qui avait été fait soit concrétisé.

C'est certain qu'il y a des pistes d'amélioration par dessus la présente PR, mais c'est selon moi un autre sujet encore.

2022-08-15 12:13 UTC, philippemilink commented on zds/utils/misc.py
> +            raise Exception(f"User {username!r} does not exist. You must create it to run the server.")
Ok. On fera un ticket / une PR lorsque le problème se présentera vraiment :)

2022-08-15 12:14 UTC, philippemilink approved these changes

2022-08-15 12:14 UTC, merged