Corrige la route pour dissocier un ticket GitHub d'un sujet du forum
zestedesavoir/zds-site pull request #6378
Opened 2022-08-13 21:31 UTC by philippemilink

Cette PR corrige la route pour dissocier un ticket GitHub d'un sujet du forum (probablement un oubli lors de la refactorisation des URLs) et ajoute un test pour s'assurer que ce genre de problème ne passe plus sous nos radars.

Problème rapporté par Sentry.

### QA

Le plus simple est sans doute de faire une revue de code et de constater que le changement principal est correct et ne peut pas introduire de bug, sinon il est possible que je déploie cette PR sur la bêta. Si #6377 est fusionné lors de la QA, il est aussi possible modifier les champs *Ticket GitHub* (avec n'importe quelle valeur) et *Nom du dépôt GitHub* (par une des valeurs des dépôts définies dans la [configuration](https://github.com/zestedesavoir/zds-site/blob/dev/zds/settings/abstract_base/zds.py#L125-L126)) et en tant qu'utilisateur `dev`, aller sur la page du sujet et constater qu'elle s'affiche correctement.

2022-08-14 11:25 UTC, Arnaud-D requested changes
Je pense que ce n'est pas la peine de QA outre mesure, c'est juste un oubli que j'ai fais lors de la refactorisation des URL. Ce genre de soucis est attrapé par le type de test que tu as ajouté et dont on manque globalement dans la suite.

2022-08-14 11:25 UTC, Arnaud-D commented on zds/forum/tests/tests_views.py
> +        self.assertNotContains(response, label_link_issue)
Je pense que c'est mieux de séparer les différents cas. En fait, tes commentaires délimitent les cas qui devraient être dans des tests individuels. Et ce qui est au début de la fonction est le `setUp`. ^^

2022-08-14 13:53 UTC, philippemilink commented on zds/forum/tests/tests_views.py
> +        self.assertNotContains(response, label_link_issue)
Corrigé.

2022-08-31 13:04 UTC, Arnaud-D approved these changes

2022-08-31 13:13 UTC, merged