Passe à la version 22.04 d'Ubuntu pour GitHub Actions
zestedesavoir/zds-site pull request #6380
Opened 2022-08-14 13:58 UTC by philippemilink

L'image `ubuntu-18.04` qu'on utilise actuellement pour la CI est déprécié depuis le 8 août (cf
https://github.com/actions/runner-images/issues/6002). Cette PR passe la version d'Ubuntu à 22.04 (qui est aussi une LTS).

Malheureusement, la version 22.04 de l'image n'inclut plus geckodriver ni Firefox (cf
[le README de la version 22.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md) vs [le README de la version 18.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu1804-Readme.md)), il faut donc les installer manuellement.

### QA

- Revue de code
- S'assurer que la CI passe avec tous les tests, y compris front avec Selenium.

2022-08-14 23:52 UTC, Situphen requested changes

2022-08-14 23:52 UTC, Situphen commented on .github/workflows/ci.yml
> +          tar -xzf geckodriver-v0.31.0-linux64.tar.gz -C geckodriver
Il serait bien de mettre le numéro de version dans une variable pour faciliter la maintenance !

2022-08-14 23:52 UTC, Situphen commented on .github/workflows/ci.yml
> +        run: sudo apt update && sudo apt install firefox
Peut-être préciser la version de Firefox à installer ? Car sinon il est probable que le script plante un jour car la version de Firefox est trop récente par rapport à la version de geckodriver.

2022-08-16 12:13 UTC, philippemilink commented on .github/workflows/ci.yml
> +          tar -xzf geckodriver-v0.31.0-linux64.tar.gz -C geckodriver
C'est fait.

2022-08-16 12:16 UTC, philippemilink commented on .github/workflows/ci.yml
> +        run: sudo apt update && sudo apt install firefox
Depuis les dépôts des distributions (avec `apt-get` ou `snap`) c'est pas évident, parce qu'ils ne proposent qu'une version des logiciels à la fois. Donc oui on est dépendant des mises à jour de Firefox faites chez Ubuntu. J'ai essayé d'installer Firefox en téléchargeant une version packagée depuis chez Mozilla (et donc en sélectionnant la version souhaitée), mais je n'ai pas réussi à faire fonctionner gecko avec...

Donc, oui ce serait bien de figer la version Firefox installée, mais je n'ai pas réussi à le faire...

2022-08-17 21:40 UTC, Situphen approved these changes

2022-08-17 21:49 UTC, merged