Ajoute une page de preview pour la classification par objectifs
zestedesavoir/zds-site pull request #6386
Opened 2022-09-05 14:21 UTC by Arnaud-D

Cette PR ajoute une page pour que tout un chacun puisse jeter un œil à la future classification par objectifs, avant qu'une intégration plus aboutie soit préparée. C'est le pendant accessible à tous de la page d'édition en masse réservée au staff.

Au menu :
   * une page avec des filtres pour voir le classement selon les différents objectifs ;
   * un petit message dans la bibliothèque pour que le lien existe *quelque part* sur le site.

Je suis volontairement resté très simple. Le but est de mettre cette classification aux yeux de tous rapidement ; le travail plus abouti risque d'être long. En conséquence :
  * j'ai mis en commun du code avec la page d'édition en masse pour le staff ;
  * j'ai volontairement peu de tests (la page est simple, vouée à la disparition à plus ou moins brève échéance, et s'appuie essentiellement sur l'édition en masse des objectifs, qui est bien testée).

### Contrôle qualité

Vérifier que la nouvelle route marche (en allant sur la bibliothèque par exemple).

Vérifier que les liens nous amènent pas sur des pages privées mais bien vers les versions en ligne.

Vérifier qu'il n'y a pas de versions privées qui s'affichent.

2022-09-27 16:03 UTC, artragis requested changes
Test OK
mais j'ai deux trois commentaires.

2022-09-27 16:03 UTC, artragis commented on templates/tutorialv2/goals/view-goals.html
> +        Cette page est un aperçu de la classification par objectif. Elle vise à donner un avant-goût de
plutôt que ce pavé (ou en complément d'icelui) on pourrait pas ajouter la description du but?

2022-09-27 16:03 UTC, artragis commented on templates/tutorialv2/goals/view-goals.html
> +        <p>{% trans "Il n'y a pas de publications à lister." %}</p>
s'il n'y en a pas, en FR, on ne met pas de s.

2022-09-27 16:03 UTC, artragis commented on templates/tutorialv2/view/categories.html
> +            <strong>Avis aux curieux</strong> ! La nouvelle <a href="{{ url_view_goals }}">classification par objectifs</a> fait son avant-première.
parfois tu mets classification par objectif, parfois par objectifs (comme ici, avec un s donc), je ne sais pas s'il y en a une plus correcte que l'autre, mais il faut rester cohérent.

2022-09-27 16:03 UTC, artragis commented on templates/tutorialv2/goals/mass-edit-goals.html
> +            <li><a href="{% url "content:mass-edit-goals" %}" class="{% if all %}selected{% endif %}">Toutes ({{ num_all }})</a></li>
J'aurais mis le "all" en dernier car finalement c'est la forme non classifiée.

2022-09-28 08:05 UTC, Arnaud-D commented on templates/tutorialv2/goals/view-goals.html
> +        Cette page est un aperçu de la classification par objectif. Elle vise à donner un avant-goût de
Les pavés sont pas bien gros par chez toi s'ils font deux phrases ! Blague à part, j'ai ajouté une phrase pour donner l'objectif.

2022-09-28 08:05 UTC, Arnaud-D commented on templates/tutorialv2/goals/view-goals.html
> +        <p>{% trans "Il n'y a pas de publications à lister." %}</p>
Corrigé.

2022-09-28 08:07 UTC, Arnaud-D commented on templates/tutorialv2/view/categories.html
> +            <strong>Avis aux curieux</strong> ! La nouvelle <a href="{{ url_view_goals }}">classification par objectifs</a> fait son avant-première.
Le pluriel est plus logique selon moi. J'ai harmonisé en ce sens.

2022-09-28 08:07 UTC, Arnaud-D commented on templates/tutorialv2/goals/mass-edit-goals.html
> +            <li><a href="{% url "content:mass-edit-goals" %}" class="{% if all %}selected{% endif %}">Toutes ({{ num_all }})</a></li>
Oui, pourquoi pas.

2022-09-28 08:16 UTC, Arnaud-D commented
J'ai pris en compte les remarques de artragis.

2022-09-28 08:23 UTC, artragis commented on templates/tutorialv2/goals/view-goals.html
> +        Cette page est un aperçu de la classification par objectif. Elle vise à donner un avant-goût de
Du coup tu as pas ajouté la description du but (l'attribut .description dans l'objet goal) ?

2022-09-28 08:37 UTC, Arnaud-D commented on templates/tutorialv2/goals/view-goals.html
> +        Cette page est un aperçu de la classification par objectif. Elle vise à donner un avant-goût de
Ah je n'avais pas compris que tu parlais de ça. Mais je vois pas l'intérêt en fait. Surtout sur une page de preview comme ça, sans ambition.

2022-09-28 09:40 UTC, artragis commented on templates/tutorialv2/goals/view-goals.html
> +        Cette page est un aperçu de la classification par objectif. Elle vise à donner un avant-goût de
Ok, ducoup je valide

2022-09-28 09:41 UTC, artragis approved these changes

2022-09-28 09:41 UTC, merged