Améliore l'affichage de l'estimation du temps de lecture
zestedesavoir/zds-site pull request #6401
Opened 2022-10-11 16:10 UTC by Arnaud-D

Reprise de #5998.

Fix #5780.

J'ai changé un peu par rapport à ce qu'avait fait Toxic à l'époque.

On a une précision changeante, de moins en moins fine à mesure que les valeurs de temps devienne grande. On passe de la minute, à 5 min, à 10 min, puis 15 min puis 30 min, puis 60 min. Comme ça, la valeur a une précision adaptée à la longueur : pas besoin d'être précis à 15 min sur une publication qui met plusieurs dizaines d'heures à être lue.

Le filtre est flexible pour adapter facilement les valeurs de précision ou les bornes des intervalles.

J'en ai profité pour refactoriser un peu (changement de nom) et me suis essayé aux annotations de type.

### Contrôle qualité

* Relire le code et les tests pour juger de la pertinence des troncatures.
* Importer l'archive d'un très gros contenu (par exemple le tuto arduino) et voir que le temps est affiché uniquement en heures.
* Importer l'archive d'un article plus court et constater le temps affiché en minutes.
* Possibilité de faire ça sur des choses intermédiaires, mais c'est plus dur de bien viser sur la durée. :D

2022-10-11 17:19 UTC, Situphen requested changes
Deux petites suggestions après une première lecture du code :)

2022-10-11 17:19 UTC, Situphen commented on zds/utils/templatetags/humanize_duration.py
> +        return _("%(h)s et %(m)s") % {"h": hours_fragment, "m": minutes_fragment}
Ce serait je pense plus lisible sous cette forme : 

```suggestion
        return _(f"{hours_fragment} et {minutes_fragment}")
```

2022-10-11 17:19 UTC, Situphen commented on templates/tutorialv2/includes/tags_authors.part.html
>              {% endif %}
Cela devrait être possible étant donné que la fonction fonctionne correctement quand `reading_time` est nul. On peut même inclure la balise `<p>` dans la condition `if`.

```suggestion
            {% if online and not is_part_or_chapter %}
                {% trans "Temps de lecture estimé à " %}{{ reading_time|humanize_duration }}
            {% endif %}
```

2022-10-11 18:40 UTC, Arnaud-D commented on zds/utils/templatetags/humanize_duration.py
> +        return _("%(h)s et %(m)s") % {"h": hours_fragment, "m": minutes_fragment}
Si je ne me trompe pas, les f-strings ne sont pas supportées pour l'internationalisation. Après, je m'y suis peut-être mal pris malgré tout, mais je ne crois pas que les f-strings soient une solution.

2022-10-11 18:42 UTC, Arnaud-D commented on templates/tutorialv2/includes/tags_authors.part.html
>              {% endif %}
Ouais, j'avais retiré un bout de condition en gérant correctement le cas nul, mais j'avais pas pensé à regarder autour plus que ça. :D Je fais une modif en ce sens.

2022-10-11 19:22 UTC, Situphen commented on zds/utils/templatetags/humanize_duration.py
> +        return _("%(h)s et %(m)s") % {"h": hours_fragment, "m": minutes_fragment}
Tu as effectivement raison. Je propose donc d'utiliser cette alternative : 

```suggestion
        return _("{hours} et {minutes}").format(hours=hours_fragment, minutes=minutes_fragment)
```

2022-10-11 19:28 UTC, Situphen commented on zds/utils/templatetags/humanize_duration.py
> +    hours_fragment = ngettext("1 heure", f"{hours} heures", hours)
Si j'ai bien compris la traduction ne fonctionnera pas avec des f-strings là non plus. Je propose donc ceci : 

```suggestion
    minutes_fragment = ngettext("1 minute", "{minutes} minutes", minutes).format(minutes=minutes)
    hours_fragment = ngettext("1 heure", "{hours} heures", hours).format(hours=hours)
```

2022-10-11 19:39 UTC, Arnaud-D commented on zds/utils/templatetags/humanize_duration.py
> +        return _("%(h)s et %(m)s") % {"h": hours_fragment, "m": minutes_fragment}
Ça me va !

2022-10-11 21:34 UTC, Situphen requested changes
Il faut effectuer ce changement sinon le filtre n'est pas appliqué.

2022-10-11 21:34 UTC, Situphen commented on templates/tutorialv2/includes/tags_authors.part.html
> +            <p>{% blocktrans %}Temps de lecture estimé  à {{ reading_time|humanize_duration }}.{% endblocktrans %}</p>
```suggestion
            <p>{% blocktrans with reading_time=reading_time|humanize_duration %}Temps de lecture estimé à {{ reading_time }}.{% endblocktrans %}</p>
```

2022-10-11 21:38 UTC, Situphen commented on templates/tutorialv2/includes/tags_authors.part.html
> +            <p>{% blocktrans %}Temps de lecture estimé  à {{ reading_time|humanize_duration }}.{% endblocktrans %}</p>
D'ailleurs je me demande s'il ne faudrait pas rajouter "environ" pour préciser le caractère peu précis de l'estimation. 🤔

2022-10-12 06:24 UTC, Arnaud-D commented on templates/tutorialv2/includes/tags_authors.part.html
> +            <p>{% blocktrans %}Temps de lecture estimé  à {{ reading_time|humanize_duration }}.{% endblocktrans %}</p>
C'est une bonne idée de rajouter ça.

2022-10-12 10:56 UTC, Situphen approved these changes
**QA OK**

2022-10-12 10:56 UTC, merged