Corrige deux erreurs liées à"Auteur externe"
zestedesavoir/zds-site pull request #6408
Opened 2022-10-21 11:47 UTC by Arnaud-D

Fix  #6392.

Corrige deux erreurs liées à la présence du compte externe dans une publication.

Les commits sont propres et peuvent être ajoutés sans squash.

### Contrôle qualité

* Se connecter qu'admin pour se faciliter la vie.
* Créer, une publication avec external parmi les auteurs, et quelques autres comptes (user1, user2 par exemple).
* Mettre en bêta cette publication, constater qu'il n'y a pas de 500 "NotReachableError".
* Retirer le compte "external" des auteurs d'une publication où il est auteur, constater qu'il n'y a pas de 500 "NotReachableError".
* Retirer un autre compte des auteurs et constater qu'il reçoit bien un MP.

2022-10-21 16:50 UTC, philippemilink commented
(je ne vois pas de tests :eyes: :smiley: on doit pouvoir s'inspirer des tests que j'avais ajouté dans cette PR : https://github.com/zestedesavoir/zds-site/pull/6356)

2022-10-21 21:51 UTC, Arnaud-D commented
Effectivement, j'avais zappé les tests. J'en ai fait une partie déjà. Il manque l'autre.

2022-10-22 16:05 UTC, Arnaud-D commented
Voilà, il y a des tests pour tout. J'en ai profité pour réarranger un peu les fichiers de test au passage. L'analyse temp-réel de mon IDE n'était pas très fan du fichier de 3500 lignes.

2022-10-26 19:37 UTC, Situphen requested changes
Il y a simplement une petite faute de frappe (présente 5 fois) à corriger et ce sera bon !

2022-10-26 19:37 UTC, Situphen commented on zds/tutorialv2/tests/tests_views/tests_removeauthor.py
> +        self.other_autor = ProfileFactory().user
5 occurrences à renommer
```suggestion
        self.other_author = ProfileFactory().user
```

2022-10-26 19:50 UTC, Arnaud-D commented on zds/tutorialv2/tests/tests_views/tests_removeauthor.py
> +        self.other_autor = ProfileFactory().user
C'est corrigé.

2022-10-26 20:10 UTC, Situphen approved these changes
**QA OK**

2022-10-26 20:10 UTC, merged