Plus de déconnexion après modification du mot de passe
zestedesavoir/zds-site pull request #6424
Opened 2022-11-10 21:14 UTC by Situphen

Actuellement, on est déconnecté lorsqu'on change son mot de passe, ce qui est assez perturbant. Cette PR corrige ce soucis en utilisant [la fonction de Django `update_session_auth_hash`]( https://docs.djangoproject.com/fr/3.2/topics/auth/default/#session-invalidation-on-password-change) prévue pour ça.

À noter pour le futur que Django propose [des vues prêtes à l'emploi pour le changement et la réinitialisation du mot de passe](https://docs.djangoproject.com/fr/3.2/topics/auth/default/#module-django.contrib.auth.views), si on souhaite éviter de gérer cela par nous même comme actuellement.

**QA :** Modifier son mot de passe et vérifier que l'on n'est pas déconnecté

2022-11-30 11:29 UTC, DonKnacki commented
non, je reste déconnecté après changement de mot de passe avec un compte classique (testé sur la beta et en local)
Voici mon test : 
1) connection un compte qui nécessite login + password (user2 en local)
2) sur la page des comptes (http://localhost:8000/membres/parametres/compte/ en local) , la partie mot de passe, je rempli les 3 champs nécessaires (Mot de passe actuel, Nouveau mot de passe, confirmation) puis Enregistrer
3) je suis rediriger automatiquement sur la page de connexion et non connecté évidemment

2022-11-30 23:23 UTC, Situphen commented
C'est normal que cela ne fonctionne pas sur la bêta car cette PR n'est pas sur la bêta. Par contre, c'est très étonnant que ça ne fonctionne pas chez toi en local ! Es-tu sûr d'être sur ma branche et non pas sur `upstream/dev` ?

2022-12-05 22:21 UTC, philippemilink requested changes
Ça fonctionne.

La raison de l'utilisation de la fonction n'est pas vraiment claire juste à partir du nom de la fonction, donc un petit commentaire ne fera pas de mal.

Si tu es motivé, tu peux aussi rajouter un petit test rapide.

Avec en plus un rebase, et je merge.

2022-12-05 22:21 UTC, philippemilink commented on zds/member/views/profile.py
> +        update_session_auth_hash(self.request, profile.user)
```suggestion
        # to avoid being disconnected after changing the password:
        update_session_auth_hash(self.request, profile.user)
```

2022-12-05 22:30 UTC, philippemilink approved these changes
## Rapport de QA

**QA OK** ✔️

2022-12-05 22:39 UTC, merged