Mise à jour des instructions d'installation pour macOS.
zestedesavoir/zds-site pull request #6427
Opened 2022-11-30 15:21 UTC by AmauryCarrade

Mise à jour majeure de la documentation d'installation sous macOS 12+.

Cette mise à jour comprend : 
- des recommandations sur l'installation de ZdS sous macOS (notamment, l'utilisation des GNU Coreutils à la place de ceux de BSD) ;
- la mise à jour de la documentation pour indiquer les commandes modernes du `Makefile` ;
- une réécriture entière de la documentation pour macOS afin qu'elle soit plus didactique.

### Contrôle qualité

- Relire la documentation à la recherche de typos (le correcteur ortho-grammatical de PyCharm me dit que c'est bon, mais sait-on jamais).
- Idéalement, tester l'installation en suivant ces instructions sous macOS 12+.

---

_Le commit n'est pas signé car je n'ai pas encore reconfiguré la signature automatique de mes commits sur mon nouvel ordi — sous macOS, vous l'aurez deviné. Ayant [configuré GitHub pour exiger la signature de mes commits](https://docs.github.com/fr/authentication/managing-commit-signature-verification/displaying-verification-statuses-for-all-of-your-commits#about-vigilant-mode), c'est normal qu'il râle. C'est bien moi :p ._

2022-12-05 22:54 UTC, philippemilink requested changes
Belle documentation !

Peut-être un peu trop détaillée par endroits, mais je ne vais pas te faire retirer des phrases :)

Je suis étonné que tu ais eu besoin d'installer les coreutils GNU/Linux. Sur mon Mac bloqué à la version BigSur 11.6, je ne me souviens pas précisément comment j'avais installé initialement ZdS, mais je n'avais pas eu besoin de faire ces manipulations...

Quelques typos, problèmes de formatage et reformulations suggérées et on pourra merger.

2022-12-05 22:54 UTC, philippemilink commented on doc/source/install/install-osx.rst
> +  demander de l'aide sur le `forum des Devs' de Zeste de Savoir
Sphinx transforme l'apostrophe après `Devs` en guillemets `Devs”`, ce qui est un peu bizarre...

2022-12-05 22:54 UTC, philippemilink commented on doc/source/install/install-osx.rst
> +Vous aurez ensuite besoin d'**Homebrew**, un système permettant de télécharger et
Idem, l'apostrophe après le d, de `d'Homebrew` est transformée en guillemets. Ici le plus simple est sans doute d'écrire `Vous aurez ensuite besoin de **Homebrew**`.

2022-12-05 22:54 UTC, philippemilink commented on doc/source/install/install-osx.rst
> +Si vous avez décidé garder la version native de Python, si elle est assez récente,
```suggestion
Si vous avez décidé de garder la version native de Python, si elle est assez récente,
```

2022-12-05 22:54 UTC, philippemilink commented on doc/source/install/install-osx.rst
> +Utilitaires GNU/Linx au lieu de BSD
```suggestion
Utilitaires GNU/Linux au lieu de BSD
```

2022-12-05 22:54 UTC, philippemilink commented on doc/source/install/install-osx.rst
> +négatif et ça permet à ``zds-site`` de fonctionner sans manip.
```suggestion
négatif et ça permet à ``zds-site`` de fonctionner sans manipulation particulière.
```

2022-12-05 22:54 UTC, philippemilink commented on doc/source/install/install-osx.rst
> +de l'environnement de ```zds-site``.
```suggestion
de l'environnement de ``zds-site``.
```

2022-12-05 22:54 UTC, philippemilink commented on doc/source/install/install-osx.rst
> +  - installer les dépendance de ``zds-site`` dans l'environnement virtuel ;
```suggestion
  - installer les dépendances de ``zds-site`` dans l'environnement virtuel ;
```

2022-12-05 22:54 UTC, philippemilink commented on doc/source/install/install-osx.rst
> +Une fois dans votre environnement python et toutes les dépendances installées,
```suggestion
Une fois dans votre environnement Python et toutes les dépendances installées,
```

2022-12-05 22:54 UTC, philippemilink commented on doc/source/install/install-osx.rst
> +Si vous avez une petite machine et que vous voulez une version plus légère,
```suggestion
Si vous avez une machine peu puissante et que vous voulez une version plus légère,
```

2022-12-05 22:54 UTC, philippemilink commented on doc/source/install/install-osx.rst
> +mais sans tous ces conforts de développement, vous pouvez démarrer une version
```suggestion
mais sans tous ces outils de développement, vous pouvez démarrer une version
```

2022-12-05 22:54 UTC, philippemilink commented on doc/source/install/install-osx.rst
> +  contenus que vous avez pu créer, sur votre instance locale**, puis recréé des
```suggestion
  contenus que vous avez pu créer, sur votre instance locale**, puis recrée des
```

2022-12-06 07:40 UTC, Arnaud-D commented on doc/source/install/install-osx.rst
> +Vous aurez ensuite besoin d'**Homebrew**, un système permettant de télécharger et
La forme avec "de" est aussi la forme correcte, le h étant ce qu'il est en anglais. ^^

2022-12-25 18:24 UTC, AmauryCarrade commented on doc/source/install/install-osx.rst
> +  demander de l'aide sur le `forum des Devs' de Zeste de Savoir
Je vais régler ça en utilisant une apostrophe typographique `’`. Mais c'est étrange, en effet.

2022-12-25 18:24 UTC, AmauryCarrade commented on doc/source/install/install-osx.rst
> +Vous aurez ensuite besoin d'**Homebrew**, un système permettant de télécharger et
Idem que plus haut : cette forme n'est pas très naturelle en français ; je vais lui préférer l'apostrophe typographique.

2022-12-25 18:40 UTC, AmauryCarrade commented
C'est OK pour moi, j'ai repris toutes les remarques, corrigé les apostrophes, renommé le fichier afin d'être cohérent avec le nouveau nom de macOS, et voilà !

2022-12-25 19:12 UTC, AmauryCarrade commented
J'avais pas vu certains commentaires de @philippemilink.

> Peut-être un peu trop détaillée par endroits, mais je ne vais pas te faire retirer des phrases :)

J'ai voulu rendre la documentation accessible y compris à des débutant·es complets, afin de faciliter la compréhension. C'est pour ça que la documentation s'apparente presque à un tutoriel à certains endroits. C'est aussi pour ça que j'ai pensé à deux niveaux de lecture, [en écrivant un chemin de contournement](https://github.com/zestedesavoir/zds-site/pull/6427/files#diff-a1885dac402403d5629f6411fe46e8f0d920e0eefc0dfff545d341e3eef12730R35-R46).

> Je suis étonné que tu ais eu besoin d'installer les coreutils GNU/Linux. Sur mon Mac bloqué à la version BigSur 11.6, je ne me souviens pas précisément comment j'avais installé initialement ZdS, mais je n'avais pas eu besoin de faire ces manipulations...

C'est probablement faisable en contournant le script d'installation et en faisant les étapes à la main (comme la CI), ou en réécrivant le script pour qu'il soit aussi compatible avec BSD/Darwin. J'ai fait ce choix afin de continuer d'utiliser le script d'installation, et donc d'être _futur-proof_, évitant que la documentation pour macOS ne se décale par manque de mise à jour.

On peut faire autrement, donc, mais c'est plus d'effort.

2023-01-21 15:53 UTC, philippemilink approved these changes
Je n'ai pas testé (j'ai déjà ZdS installé sur mon Mac), mais ça me semble correct. **QA OK** ✔️

2023-01-21 16:04 UTC, merged