Amélioration de la connexion via les réseaux sociaux
zestedesavoir/zds-site pull request #6429
Opened 2022-12-01 15:32 UTC by Situphen

Amélioration de la connexion via les réseaux sociaux en deux points.

- On n'enlève plus les espaces des pseudos, car on désactive le paramètre `CLEAN_USERNAMES` qui consiste en l'application de deux expressions régulières pour nettoyer les pseudos : 
  ```py
  NO_ASCII_REGEX = re.compile(r"[^\x00-\x7F]+")
  NO_SPECIAL_REGEX = re.compile(r"[^\w.@+_-]+", re.UNICODE)

  def clean_username(cls, value):
      """Clean username removing any unsupported character"""
      value = NO_ASCII_REGEX.sub("", value)
      value = NO_SPECIAL_REGEX.sub("", value)
  return value
  ```
  **J'ai besoin d'avis là dessus !** Je ne suis pas sûr que ce soit une bonne idée. Pour les membres connectés via Google, les pseudos sont créés à partir des adresses de courriel donc il ne devrait pas y avoir de soucis (ni espace ni virgule). Par contre, les pseudos des membres connectés via Facebook sont créés à partir de leur nom et donc peuvent contenir des espaces et peut-être des virgules. Il me semble que les virgules sont interdites dans les pseudos des comptes classiques car on les utilise en tant que séparateur lors de la création de nouveaux messages privés. Pour les espaces, les pseudos sont mieux lisibles avec mais cela complique le ping dans les messages.
- On récupère l'adresse de courriel des comptes Facebook, car figurez-vous que demander le scope de suffit pas et il faut explicitement demander à récupérer ce champ. Malheureusement, il me semble que ce n'est pas rétroactif donc seuls les nouveaux comptes en bénéficieront.

**QA :** Vérifier le bon fonctionnement de la connexion via les réseaux sociaux, notamment Facebook. (Cela se fera directement sur la bêta.)

2022-12-06 20:45 UTC, philippemilink commented
Hmmm, je ne comprends pas tout au premier point...

- ce que tu proposes pour le premier point n'est pas committé. Tu attends qu'on se mette d'accord ici sur ce qu'il faut précisément implémenter pour le commiter ?
- tu parles de nettoyage de *mot de passe*, je suppose que tu veux dire nettoyage de *login* ?
- je suis d'accord pour empêcher d'avoir des espaces dans le login, mais en fait ce n'est pas une restriction qui est déjà en place...
- pourquoi ne pas tout simplement reprendre ce qui est fait dans le [morceau de code que cites (+ quelques lignes suivantes)](https://github.com/zestedesavoir/zds-site/blob/a333b4c965acd6816624f8e901bb9da99881f3d6/zds/member/validators.py#L83-L88) ? Ça interdit les caractères qu'on ne veut pas (notamment le utf8mb4 avec ses caractères fourbes) et devrait autoriser les caractères accentués...

2022-12-06 22:17 UTC, Situphen commented
Je viens de relire et effectivement ce n'était pas très clair, j'ai probablement écrit ces paragraphes dans un état de fatigue avancé ! J'ai réécrit quelques morceaux pour que cela soit mieux compréhensible (enfin j'espère).

> ce que tu proposes pour le premier point n'est pas committé. Tu attends qu'on se mette d'accord ici sur ce qu'il faut précisément implémenter pour le commiter ?

Si si, le premier point est commité. Il y a un commit par point ! J'attends surtout un retour sur le premier point car je ne suis pas sûr que ce que je propose soit souhaitable en fait.

> tu parles de nettoyage de mot de passe, je suppose que tu veux dire nettoyage de login ?

Oups, il s'agit en effet du nettoyage du pseudo et non pas du mot de passe.

> je suis d'accord pour empêcher d'avoir des espaces dans le login, mais en fait ce n'est pas une restriction qui est déjà en place...

Il n'y a pas de restriction sur les espaces dans les pseudos lors d'une modification de pseudo ou d'une inscription classique, mais il y a en a une *de facto* pour l'inscription via les réseaux sociaux. Dans son état actuel, le premier commit enlèverai cette restriction pour l'inscription via les réseaux sociaux. Au début je pensais que c'était une bonne idée mais je ne suis finalement pas sûr, car pour les comptes Facebook les pseudos sont créés à partir du nom du compte. On peut donc penser qu'une grande proportion de ces pseudos contiendront des espaces. Et la conséquence que j'imagine c'est que ça augmenterait le nombre de fois où on doit utiliser `@**pseudo avec espace**` au lieu de `@pseudo`, ce qui n'est pas très souhaitable je trouve. Il est possible que ce soit une tempête dans un verre d'eau, à vous de me le dire !

> pourquoi ne pas tout simplement reprendre ce qui est fait dans le [morceau de code que cites (+ quelques lignes suivantes)](https://github.com/zestedesavoir/zds-site/blob/a333b4c965acd6816624f8e901bb9da99881f3d6/zds/member/validators.py#L83-L88) ? Ça interdit les caractères qu'on ne veut pas (notamment le utf8mb4 avec ses caractères fourbes) et devrait autoriser les caractères accentués...

Même réponse qu'au-dessus.

2023-08-27 14:17 UTC, Arnaud-D commented
À mon avis, on devrait partir sur les mêmes restrictions que quand on s'inscrit sans passer par Facebook. Autrement dit, la suggestion de Philippe de reprendre les validations en place actuellement, avec utf8mb4.

Pour les nombreux caractères avec espaces, je n'ai pas de craintes particulières. Le ping est une fonctionnalité non-centrale pour l'usage du site. Ensuite, on a fait le choix d'avoir un raccourci pour le ping qui ne fonctionne pas dans 100% des cas et la syntaxe qui marche à tous les coups se fait oublier. Faut vivre avec ! :D

2024-03-10 13:38 UTC, Situphen commented
Nouvel élan de motivation donc j'ai mis à jour cette PR !

J'ai suivi vos retours et j'ai implémenté les même filtres pour les comptes créés à partir des réseaux sociaux que pour ceux créés de façon classique : pas de virgule, pas de barre oblique et pas de caractères utf8mb4. Pour ce dernier point, pas sûr que ce soit nécessaire car les réseaux sociaux ne doivent pas l'autoriser je suppose, mais ça ne mange pas de pain. J'ai du créer une fonction à part de la fonction existante car la bibliothèque attend une fonction qui nettoie le pseudo et non pas une fonction qui lève une exception. Si cela vous semble bon, alors on peut tester la PR sur la bêta.

2024-03-10 14:05 UTC, philippemilink requested changes

2024-03-10 14:05 UTC, philippemilink commented on zds/member/validators.py
> +    return replace_utf8mb4(username).replace(",", "").replace("/", "")
Ajoute un commentaire disant que les caractères à supprimer viennent de [là](https://github.com/zestedesavoir/zds-site/blob/a333b4c965acd6816624f8e901bb9da99881f3d6/zds/member/validators.py#L83-L88) et ajoute un commentaire [au même endroit](https://github.com/zestedesavoir/zds-site/blob/a333b4c965acd6816624f8e901bb9da99881f3d6/zds/member/validators.py#L83-L88) disant que les valeurs interdites sont aussi référencées ici (pour que si  un jour au modifie l'une ou l'autre des fonctions, on pense aussi à regarder l'autre fonction ; j'espère que c'est clair...).

2024-03-10 14:05 UTC, philippemilink commented on zds/utils/misc.py
> +    return re_pattern.sub("\uFFFD", s)
Pourquoi remplacer par un caractère bizarre (� d'après ce que j'ai vu dans les tests) et pas tout simplement enlever les caractères non-ascii ?

2024-03-10 14:23 UTC, Situphen commented on zds/utils/misc.py
> +    return re_pattern.sub("\uFFFD", s)
Aucune raison, j'ai simplement gardé le comportement historique, mais en effet c'est plus logique de supprimer probablement.

2024-03-11 19:19 UTC, philippemilink commented
Je viens de déployer sur la bêta, je te laisse tester @Situphen avec le compte Facebook de test (je pense que ça va aussi être l'occasion de faire un tour dans les réglages de Facebook pour utiliser leur API).

2024-03-11 20:21 UTC, Situphen commented
Ça fonctionne ! J'ai créé un compte ZDS avec un utilisateur test de Facebook et j'ai bien un pseudo avec un espace entre le nom et prénom, ainsi qu'une une adresse de courriel.

![image](https://github.com/zestedesavoir/zds-site/assets/6664636/f939b54b-fc8e-4fa5-92e5-46cc07330f42)

2024-03-11 20:48 UTC, philippemilink approved these changes

2024-03-11 20:48 UTC, merged