Lève dess restrictions sur les billets
zestedesavoir/zds-site pull request #6441
Opened 2022-12-23 21:58 UTC by Arnaud-D

Dans le cadre de l['organisation des contenus](https://github.com/orgs/zestedesavoir/projects/3/views/2), cette PR :

- supprime des fonctions inutilisées en rapport avec la distinction billet/tuto/article ;
- rend générique certains affichages en utilisant "publication" au lieu de "tutoriel", "article" ou "billet ;
- déverouille la structure des billets et articles pour permettre tout comme les tutoriels ;
- permet l'ajout/suppression de contributeurs sur les billets.

### Contrôle qualité

Draft pour le moment.

2022-12-23 23:18 UTC, Situphen commented on templates/tutorialv2/messages/add_contribution_pm.md
>  {% blocktrans with title=content.title|safe type=type|safe user=user|safe %}
```suggestion
{% blocktrans with title=content.title|safe user=user|safe %}
```

2023-01-15 15:38 UTC, philippemilink requested changes
J'ai créé un billet avec parties, chapitres et sections un peu dans tous les sens, par forcément de façon homogène (ie une partie a un chapitre, une autre partie a directement des sections). Une fois le billet publié, sur la version publique, peu importe le lien sur lequel je clique dans la hiérarchie du contenu (nom de partie, nom de chapitre, nom de section), je me prends une erreur 404. Je pense qu'il y a aussi des changements à faire dans les routes.

EDIT: et bien-sûr, ce serait bien d'ajouter les tests pour détecter ce genre de bugs :)

2023-01-15 21:51 UTC, Arnaud-D commented
J'avais effectivement oublié ça. J'ai ajouté les routes manquantes pour les billets et les articles.

J'ai réussi (laborieusement) à ajouter des tests. Je me suis restreint aux billets et articles, et j'ai gardé ça simple. En gros, je crée un contenu avec des conteneurs, je le publie et je regarde qu'on peut voir la version en ligne.

On pourrait enrichir ça encore plus, mais je préfère éviter de faire un excès de zèle à ce niveau.

2023-01-16 15:40 UTC, Arnaud-D commented
J'ai ajouté l'affichage des liens vers la partie ou chapitre suivant et précédent. C'était présent que sur les tutoriels, j'ai fait en sorte que ça soit actif partout.

2023-01-26 14:39 UTC, Arnaud-D commented
Ça pourrait être intéressant de fusionner #6457 avant cette PR-ci. #6457 change complètement les templates, la présente sera difficilement fusionnable de toute façon ; c'est plus simple pour moi de reprendre cette PR à partir de l'autre que l'inverse.

2023-10-28 19:00 UTC, Arnaud-D commented
Ça va pouvoir reprendre ici puisqu'on a fusionné #6457 !

2023-10-28 21:20 UTC, Arnaud-D commented
Comme on peut le voir ci-dessus, j'ai découpé cette PR en plus petits morceaux. Elle est désormais obsolète et je la ferme donc.

2023-10-28 21:20 UTC, closed without merging