Ajoute une commande pour lister les paquets Node.js à mettre à jour
zestedesavoir/zds-site pull request #6453
Opened 2023-01-20 22:03 UTC by Situphen

Ajoute une commande pour lister les paquets Node.js à mettre à jour

**QA :** 

- Mettre à jour l'environnement avec `source zdsenv/bin/activate && make update`
- Vérifier le fonctionnement de la commande `make list-outdated-front`

2023-01-20 23:00 UTC, philippemilink requested changes

2023-01-20 23:00 UTC, philippemilink commented on Makefile
> +	@npx david
Quand il y a des dépendances qui ne sont pas à jour, `npx david` renvoie le code 1, ce que `make` n'aime pas : j'ai à la fin de la sortie de david : `make: *** [list-outdated-front] Error 1`.

Je propose : 
```suggestion
	@npx david || true
```

Sinon OK.

2023-01-21 08:43 UTC, Situphen commented on Makefile
> +	@npx david
Bonne idée ! J'ai mis à jour la PR

2023-01-21 10:54 UTC, philippemilink approved these changes
**QA OK** ✔️

2023-01-21 10:55 UTC, merged