Refactorise les templates des publications
zestedesavoir/zds-site pull request #6457
Opened 2023-01-26 13:04 UTC by Arnaud-D

Le travail n'est pas fini, il me reste à :

- [ ] corriger des choses pour la vue de version spécifique
- [ ] mieux ranger les includes de templates
- [ ] mieux ranger les configurations de vue/les vues
- [ ] écrire des tests Selenium ?

---

Cette PR refactorise les templates des publications.

Il y a une part de mise à jour de l'expérience utilisateur. J'ai essayé de rationaliser un peu sans nécessairement trop toucher au design. J'ai réorganisé les menus pour séparer les actions de bêta, celles qui concernent la version en ligne, etc. Je pense que c'est plus facile à naviguer qu'avant, même si imparfait.

Sinon, il y a tout un pan de technique. L'objectif est de faciliter la création des [liens de partage](https://github.com/zestedesavoir/zds-site/pull/6134) à terme, ce qui était essentiellement incompatible avec l'organisation actuelle. On a donc :

* seulement deux templates (_content_ ou _container_) pour tout ce qui montre un contenu, quelque soit son état (draft, bêta, version en validation, version en ligne, version spécifque, et à l'avenir lien de partage) ;
* ces templates sont configurables, pour adapter l'affichage à la vue. Par exemple, on ne montre pas les boutons d'édition en dehors de la vue draft ou on n'affiche pas le lien vers la version brouillon si on y est déjà ;
* la configuration se fait au niveau de la vue, c'est un peu complexe avec quand même beaucoup d'options possible ;
* j'ai refait la hiérarchie des vues pour que ça soit plus facile à suivre et supprimer de la redondance.
* il y a nouvelle vue spécifique pour voir une version par son commit (auparavant, c'était à moitié mélangé avec la vue draft un peu générateur de bugs).

Il y a des choses qu'on pourrait faire pour aller plus loin, mais que je ne ferais pas dans cette PR.

* Par exemple, beaucoup d'affichages sont basés sur `is_staff`. Cette information est souvent pas très précise, et on devrait utiliser des véritables permissions sur les vues (quitte à réecrire `has_permission`), afin d'éviter d'avoir la logique d'afficahge indépendante de celle des actions associées. Actuellement, on a des bugs à cause de ça.
* Il y a de la duplication par exemple entre `child` et `child_online` ou au sein même des templates ou j'ai intégré des choses très similaires en parallèle. Ça peut être fait dans un deuxième temps, je pense.

### Contrôle qualité

À rédiger. Il y a pas mal de choses à regarder. :D

En quelques mots : 
* vue en ligne : en tant que visiteur, membre, auteur, staff
* vue bêta : en tant que membre, auteur, staff
* vue draft : en tant qu'auteur ou staff
* vue "version" sur la version en validation : en tant qu'auteur ou staff.

Et ça pour les différents formats de contenu possible (afin de tester l'affichage "content" et l'affichage "container")

Et en particulier pour les vues "draft", il faut tester l'affichage pour tous les états possibles (en ligne, pas en ligne, bêta, pas bêta, les différentes étapes de validation, etc.).

2023-02-13 12:22 UTC, artragis reviewed
J'ai eu un peu de temps pour passer sur quelques requêtes comme tu les évoques dans ton message initial.

Sur la globalité, je nai rien vu de choquant mais bon 85 fichiers c'est complexe à review.

2023-02-13 12:22 UTC, artragis commented on templates/tutorialv2/includes/headline/categories.part.html
> +    {% trans "Catégorie" %}{{ content.subcategory.all|pluralize }} :
je vois que tu fais plusieurs fois le .subcategory.all. Pourquoi ne pas faire dans le python un `subcategories = list(content.subcatogory.all())`? cela ne génèrerait qu'une seule requête et comme ça tu n'as qu'une seule liste.

2023-02-13 12:22 UTC, artragis commented on zds/tutorialv2/views/display/content.py
> +        context["contributions"] = ContentContribution.objects.filter(content=self.object).order_by(
tu peux ajouter un prefetch sur user comme ça pas besoin de 50 requêtes

2023-02-13 12:22 UTC, artragis commented on zds/tutorialv2/models/database.py
> +        return Validation.objects.filter(content=self).order_by("-date_proposition").first()
faire un select_related sur le validator pour éviter que le template face une requête à chaque validation.
De plus, faire 
```python
validation = Validation.objects.select_related("author").filter(content=self).order_by("-date_proposition").first()
validation.content = self
return validation
```
car à plusieurs reprises dans le template on appelle validation.content alors que validation vient de `content.get_validattion()`

2023-02-14 14:30 UTC, Arnaud-D commented on templates/tutorialv2/includes/headline/categories.part.html
> +    {% trans "Catégorie" %}{{ content.subcategory.all|pluralize }} :
Il y a un prefetch qui évite déjà la duplication de ça, rajouter la conversion en liste ne change pas le nombre de requêtes. Quand on enlève le prefetch, on voit bien toutes ces requêtes dupliquées par contre.

2023-02-14 14:53 UTC, Arnaud-D commented on zds/tutorialv2/views/display/content.py
> +        context["contributions"] = ContentContribution.objects.filter(content=self.object).order_by(
Bien vu, ça économise un peu dans le cas où il y a des contributeurs. Je n'avais pas regardé cette situation, donc ça ne change rien au compte de mon message initial, cependant.

2023-02-14 15:21 UTC, Arnaud-D commented on zds/tutorialv2/models/database.py
> +        return Validation.objects.filter(content=self).order_by("-date_proposition").first()
Ça marche, mais c'est un peu _hacky_ et je ne vais pas le faire.

Je pense qu'une meilleure soution (pour une autre PR s'il n'y a pas de souci sensible de performance en prod) serait de lier les demandes de validation explicitement à `content`, en déclarant dans PublishableContent le modèle Validation comme le support d'une relation ManyToMany. Je pense que ça rendrait le code plus lisible et débloquerait certaines optimisations.

Aussi, de rajouter un champ, ça oblige à tester qu'on renvoie effectivement quelque chose et pas None. Ce qui complique un peu le code juste pour enlever une requête pour le rare cas où le contenu est en validation.

2023-02-14 15:32 UTC, Arnaud-D commented
J'ai trouvé le plus gros coupable pour mon augmentation du nombre de requête. J'avais une méthode `is_author` qui tapait la base de donnée à chaque fois qu'elle était appelée (9 fois). J'ai trouvé une autre solution beaucoup plus avantageuse et qui utilise des données déjà prefetchées et n'introduit donc aucune nouvelle requête.

J'ai aussi au passage fait une partie des suggestions d'artragis et changé d'autres bricoles non introduites par ma PR, mais qui ne mangent pas de pain.

2023-04-16 18:52 UTC, philippemilink requested changes
J'ai parcouru le code modifié, pas les nouveaux fichiers. Pas encore testé, mais j'ai remarqué quelques petites choses à changer.

(faut vraiment éviter de faire des PRs aussi énormes  (au moins en un seul commit), c'est un enfer à QA...)

2023-04-16 18:52 UTC, philippemilink commented on templates/tutorialv2/includes/sidebar/summary.part.html
> +                <a class="mobile-menu-link" href="{{ base_url }}{{ child.slug }}/">
C'est pas plutôt `child.get_url_path` ?

2023-04-16 18:52 UTC, philippemilink commented on templates/tutorialv2/includes/sidebar/summary.part.html
> +                                href="{{ base_url }}{{ child.slug }}/{{ subchild.slug }}/"
Tu n'oublies pas beaucoup de cas là ? (les online, content.is_beta, et not subchild.text)

2023-04-16 18:52 UTC, philippemilink commented on templates/tutorialv2/validation/index.html
> +                                    <a href="url_validation_version">
```suggestion
                                    <a href="{{ url_validation_version }}">
```

2023-04-16 18:52 UTC, philippemilink commented on templates/tutorialv2/view/container.html
> +            Site et association de partage de connaissances animé par sa communauté. Vous y trouverez des tutoriels et des articles de tous niveaux et des forums.
Faudrait pas plutôt mettre cette phrase dans la configuration `ZDS_APP["site"]["content_default_meta_description"]` (ou bien utiliser `ZDS_APP["site"]["long_description"]` qui existe déjà).

2023-04-16 18:52 UTC, philippemilink commented on templates/tutorialv2/view/content.html
> +            Site et association de partage de connaissances animé par sa communauté. Vous y trouverez des tutoriels et des articles de tous niveaux et des forums.
Idem.

2023-04-16 18:52 UTC, philippemilink commented on zds/tutorialv2/forms.py
> +        self.previous_page_url = reverse("content:view-version", kwargs=route_parameters)
```suggestion
        self.previous_page_url = get_content_version_url(validation.content, validation.version)
```

2023-04-16 18:52 UTC, philippemilink commented on zds/tutorialv2/forms.py
> +        self.previous_page_url = reverse("content:view-version", kwargs=route_parameters)
```suggestion
        self.previous_page_url = get_content_version_url(validation.content, validation.version)
```

2023-04-16 18:52 UTC, philippemilink commented on zds/tutorialv2/forms.py
> +        self.previous_page_url = reverse("content:view-version", kwargs=route_parameters)
```suggestion
        self.previous_page_url = get_content_version_url(validation.content, validation.version)
```

2023-04-16 18:52 UTC, philippemilink commented on zds/tutorialv2/models/database.py
> +        return Validation.objects.filter(content=self).order_by("-date_proposition").first()
Fais quand même ce que propose Artragis, en mettant en commentaire un TODO avec ta proposition.

2023-04-16 18:52 UTC, philippemilink commented on zds/tutorialv2/models/mixins.py
>          return url
Je propose plutôt : 
```py
if version and version != self.sha_draft:
    route_parameters["version"] = version
    return reverse("content:view-version", kwargs=route_parameters)
else:
    return reverse("content:view", kwargs=route_parameters)
```
Je trouve ça plus lisible, et ça économise un `reverse`.

2023-04-16 18:52 UTC, philippemilink commented on zds/tutorialv2/models/versioned.py
> +    This class is used to handle a specific version of a tutorial.
```suggestion
    This class is used to handle a specific version of a content.
```

2023-04-16 18:52 UTC, philippemilink commented on zds/tutorialv2/tests/tests_views/tests_beta.py
> +        result = self.client.get(url, follow=False)
Ici (et dans les tests suivants), tu peux utiliser `get_content_version_url()`, non ?

2023-04-16 18:52 UTC, philippemilink commented on zds/tutorialv2/views/validations_contents.py
> +        self.success_url = reverse("content:view-version", kwargs=route_parameters)
```suggestion
        self.success_url = get_content_version_url(validation.content, validation.version)
```

2023-04-16 18:52 UTC, philippemilink commented on zds/tutorialv2/views/validations_contents.py
> +            redirect_url = reverse("content:view-version", kwargs=route_parameters)
Idem, utiliser `get_content_version_url()`.

2023-04-17 18:23 UTC, Arnaud-D commented on templates/tutorialv2/view/container.html
> +            Site et association de partage de connaissances animé par sa communauté. Vous y trouverez des tutoriels et des articles de tous niveaux et des forums.
Ça, je n'y ai pas touché. Ça serait plutôt pour une autre PR si tu veux le déplacer.

2023-04-17 18:24 UTC, Arnaud-D commented on templates/tutorialv2/view/content.html
> +            Site et association de partage de connaissances animé par sa communauté. Vous y trouverez des tutoriels et des articles de tous niveaux et des forums.
Ça, je n'y ai pas touché. Ça serait plutôt pour une autre PR si tu veux le déplacer.

2023-04-17 18:35 UTC, Arnaud-D commented on templates/tutorialv2/includes/sidebar/summary.part.html
> +                                href="{{ base_url }}{{ child.slug }}/{{ subchild.slug }}/"
Je ne crois pas. C'est inclut dans base_url normalement. C'est tout l'intérêt de la PR de déplacer cette logique plus en amont. Le juge de paix, c'est de vérifier le comportement de ces liens en faisant les tests.

2023-05-08 14:07 UTC, Arnaud-D commented on templates/tutorialv2/validation/index.html
> +                                    <a href="url_validation_version">
Commit "Fix 1"

2023-05-08 14:09 UTC, Arnaud-D commented on zds/tutorialv2/models/mixins.py
>          return url
Commit "Fix 2"

2023-05-08 14:11 UTC, Arnaud-D commented on zds/tutorialv2/models/versioned.py
> +    This class is used to handle a specific version of a tutorial.
Corrigé.

2023-05-08 14:13 UTC, Arnaud-D commented on zds/tutorialv2/views/validations_contents.py
> +        self.success_url = reverse("content:view-version", kwargs=route_parameters)
Commit "Fix 3"

2023-05-08 14:15 UTC, Arnaud-D commented on zds/tutorialv2/views/validations_contents.py
> +            redirect_url = reverse("content:view-version", kwargs=route_parameters)
Commit "Fix 4"

2023-05-08 14:17 UTC, Arnaud-D commented on zds/tutorialv2/tests/tests_views/tests_beta.py
> +        result = self.client.get(url, follow=False)
Ici c'est la route "content:beta-view", donc la fonction en question ne fait pas l'affaire.

2023-05-08 14:19 UTC, Arnaud-D commented on zds/tutorialv2/forms.py
> +        self.previous_page_url = reverse("content:view-version", kwargs=route_parameters)
Fix 5

2023-05-08 14:19 UTC, Arnaud-D commented on zds/tutorialv2/forms.py
> +        self.previous_page_url = reverse("content:view-version", kwargs=route_parameters)
Fix 6

2023-05-08 14:20 UTC, Arnaud-D commented on zds/tutorialv2/forms.py
> +        self.previous_page_url = reverse("content:view-version", kwargs=route_parameters)
Fix 7

2023-05-08 14:38 UTC, Arnaud-D commented on zds/tutorialv2/models/database.py
> +        return Validation.objects.filter(content=self).order_by("-date_proposition").first()
Fix 8

2023-05-08 14:50 UTC, Arnaud-D commented on templates/tutorialv2/includes/sidebar/summary.part.html
> +                <a class="mobile-menu-link" href="{{ base_url }}{{ child.slug }}/">
C'est corrigé (commit "Fix 9"à. Ça marchait quand même, mais la fonction en question vise justement à éviter de faire de la création de chemins dans le template.

2023-05-08 14:55 UTC, Arnaud-D commented
> (faut vraiment éviter de faire des PRs aussi énormes (au moins en un seul commit), c'est un enfer à QA...)

Toutes mes excuses. Ça aurait été sûrement possible, mais e n'ai pas réussi à le découper en petits morceaux. Et comme ça touche à beaucoup de fichiers, c'est tout de suite massif.

J'ai traité les commentaires sinon.

2023-07-15 18:48 UTC, philippemilink commented
Tu peux corriger le conflit, rebaser sur dev et corriger le test qui plante, stp ?

2023-09-30 06:54 UTC, Arnaud-D commented
Voilà, les tests sont corrigés !

2023-10-12 20:53 UTC, philippemilink commented on zds/tutorialv2/models/versioned.py
> +    This class is used to handle a specific version of a tutorial.
Hmm, non ?

2023-10-12 21:41 UTC, Arnaud-D commented on zds/tutorialv2/models/versioned.py
> +    This class is used to handle a specific version of a tutorial.
Ah, je n'ai fait que la moitié de la correction. Ça devrait être bon maintenant.

2023-10-14 17:22 UTC, philippemilink approved these changes
Comme discuté lors de la dernière réunion des dev's, j'approuve et merge, mais sans avoir vraiment fait une QA complète... J'ai seulement testé en jouant avec un billet, je n'ai rien remarqué d'anormal.

Dans tous les cas, beau gros boulot ! :+1:

2023-10-14 17:23 UTC, merged