connexion par Facebook perd la page de redirection après la connexion…
zestedesavoir/zds-site pull request #6464
Opened 2023-02-20 20:06 UTC by NaelDeLuca

… (zestedesavoir#6367)

La modification doit permettre à un utilisateur qui se connecte avec Google ou Facebook depuis la page d'un contenu de rester sur la page du contenu après la connexion.

### Contrôle qualité
Sur le serveur de bêta:
- Se rendre sur la page d'un contenu
- Descendre tout en bas de la page
- Cliquer sur le bouton connexion puis se connecter avec Google ou Facebook
- Vérifier qu'on est sur la même page qu'avant la connexion et non sur la page d'accueil

2023-02-20 20:47 UTC, philippemilink requested changes

2023-02-20 20:47 UTC, philippemilink commented on templates/member/includes/login_button.part.html
> +    class="btn is-social-login is-{{ network }}">
Pas de besoin de mettre à la ligne le `class=....`.

Aussi, une espace a été ajouté avant `social` dans le `{% url`, ce qui devient une route invalide et donc ne fonctionne pas (c'est ce qui plante sur la CI).

2023-02-20 20:47 UTC, philippemilink commented on templates/member/includes/login_button.part.html
> +</a>
Ça c'est potentiellement ton éditeur qui fait n'importe quoi, mais puisque c'est un changement qui ne sert à rien, autant ne pas l'inclure. Si tu n'arrives pas à dire à ton éditeur de ne pas faire ça, tu peux dire à Git de ne pas committer cette partie des changements.

2023-02-22 18:03 UTC, artragis commented
Il semble y avoir un soucis de conf facebook sur la béta. Cependant quand je compare les urls des boutons entre la prod et la béta, la béta a bien le query string nécessaire donc au pire ça me semble bon, je pense qu'on peut merger. Tu en penses quoi @philippemilink

2023-04-02 13:58 UTC, philippemilink approved these changes

2023-04-02 13:58 UTC, merged