Evolution moteur de recherche
zestedesavoir/zds-site pull request #6475
Opened 2023-03-20 21:50 UTC by victorlohezic

Actuellement, Elasticsearch constitue le moteur de recherche de Zeste de Savoir. Il permet d’indexer le contenu du site (provenant de la base de données MariaDB et de fichiers sur le disque) puis de rechercher dans cet index. Cette PR consiste à remplacer l'ancienne version de Elasticsearch par la dernière version de Typesense. 

On a donc mis à jour l'application searchv2 avec Typesense mais aussi les applications tutorialv2 et forum (pour générer les schémas des documents à ajouter aux collections).

### Contrôle qualité

La procédure d'installation est la suivante : 
- source zdsenv/bin/activate
- make index-all 
- make zmd-start
- make run 

Il est alors possible de faire une recherche, filtrer en fonction de : contenus publiés, messages du forum, sujets du forum. 
Si on ajoute un contenu, le modifie,  il est possible de faire make index-flagged pour l'indexer.

2023-03-24 11:42 UTC, philippemilink commented on scripts/define_variable.sh
> +    ZDS_TYPESENSE_VERSION="xyz"
ça devrait être key, je pense, au lieu de version

2023-04-02 18:21 UTC, philippemilink requested changes
C'est un gros morceau ! :)

Ça amène donc forcément beaucoup de commentaires.

Je trouve qu'il y a encore beaucoup de mentions à ElasticSearch dans le code (j'en ai pointées quelques unes, il y en a d'autres). Faites
```sh
git grep -Irni elastic
git grep -Irni shards
git grep -Irni replica
git grep -Irni es_ # un peu plus compliqué à faire le tri, mais on en voit
```
Et vous aurez un bon aperçu de ce qu'il reste à supprimer / adapter.

De façon générale, dans le code, évitez les noms de variables qui peuvent être utilisées dans un autre module que celui de la recherche et qui peut prêter à confusion. Par exemple : 
- `index_manager` -> `search_engine_manager`
- `index_id` -> `search_engine_id`
- ... et probablement d'autres dont je ne me souviens plus.

Vous faites des doc-strings pour les nouvelles fonctions et c'est bien. Mais tant qu'à faire, utilisez le format pour que Sphinx génère une belle documentation, comme on le fait déjà dans certaines fonctions, et sinon c'est (un peu) documenté [là](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html).

Les docs-strings, mais vous pouvez aussi utiliser les [type hints](https://docs.python.org/3/library/typing.html) en Python maintenant.

Concernant les classes liées à la recherche, je ne comprends pas bien pourquoi certaines ont Django dans leur nom, par exemple `AbstractSearchDjangoIndexable` (je sais, c'était le cas avec ES, mais pendant qu'on change la recherche, autant tout faire). Ça donne l'impression qu'elles utilisent une fonctionnalité de Django (voire qu'elles sont fournies par Django), alors qu'il ne me semble pas ? Ce serait bien de supprimer Django du nom de ces classes.

N'oubliez pas d'adapter aussi la documentation (on en avait parlé à notre dernière réunion).

La CI ne passe pas, il faudrait corriger ça.

Et un petit rebase sur la branche `dev` ne ferait pas de mal, pour avoir les commits qui ont été pushés dans le dépôt entre temps.

(et je n'ai pas encore testé !)

2023-04-02 18:21 UTC, philippemilink commented on .github/workflows/ci.yml
> +
Si vous déclarez un service typesense au-dessus, il y a quand même besoin de l'installer et le lancer manuellement ?

2023-04-02 18:21 UTC, philippemilink commented on requirements.txt
> +typesense==0.15.0
Pas besoin du commentaire `#Typesense`, et à placer plutôt plus haut avec les dépendances `# Explicit dependencies (references in code)` (et en profiter pour supprimer les modules ElasticSearch).

2023-04-02 18:21 UTC, philippemilink commented on scripts/install_zds.sh
> +        export TYPESENSE_API_KEY=xyz
Cette variable est dans le fichier `define_variable.sh`, pas besoin de refaire un export ici.

2023-04-02 18:21 UTC, philippemilink commented on templates/forum/topic/new.html
> +
Changement inutile, à annuler.

2023-04-02 18:21 UTC, philippemilink commented on templates/searchv2/search.html
> +
Ce n'est pas nécessaire de sauter partout des lignes.

2023-04-02 18:21 UTC, philippemilink commented on templates/searchv2/search.html
> +                                {% trans "type d’objet inconnu" %} : {{ result.collection }}
On ne devrait jamais arriver dans ce cas. Le visiteur ne saura pas quoi faire de l'information et l'équipe technique ne sera jamais informée qu'il y a des recherches qui renvoient des types d'objets inconnus. Il faut les filtrer en amont et s'il y a des types d'objet inconnus, générer un avertissement, comme ce qui est fait [là](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorialv2/views/statistics.py#L232).

2023-04-02 18:21 UTC, philippemilink commented on zds/forum/models.py
>      """catch the pre_delete signal to ensure the deletion in ES"""
```suggestion
    """catch the pre_delete signal to ensure the deletion in the search engine"""
```

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/__init__.py
>          "hosts": ["localhost:9200"],
Je crois que ce n'est pas 9200 le port par défaut de TypeSense.

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/__init__.py
>      """Create connection(s) to Elasticsearch from parameters defined in the settings.
```suggestion
    """Create connection(s) to the search engine from parameters defined in the settings.
```

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/add_content.sh
Fichier à supprimer maintenant.

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/chapters.jsonl
Fichier à supprimer maintenant.

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/client.py
Fichier à supprimer maintenant.

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/content.jsonl
Fichier à supprimer maintenant.

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/forms.py
> +    validated_content_labels = sorted(
Au-dessus, la variable équivalente s'appelle `content_type_values` (suffixe `values`), là vous suffixez avec `labels`. Mettez vous d'accord sur un choix unique, pour que ce soit cohérent.

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/management/commands/es_manager.py
Ce fichier devrait être renommé en quelque chose comme `search_manager.py`.

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/management/commands/es_manager.py
> +            raise Exception("Unable to connect to Typesense, aborting.")
```suggestion
            raise Exception("Unable to connect to the search engine, aborting.")
```
Tentons d'abstraire les choses :)

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/management/commands/es_manager.py
> +        # self.index_manager.setup_custom_analyzer()
En commentaire, donc à supprimer ?

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/models.py
> +from typesense import Client
```suggestion
from typesense import Client as SearchEngineClient
```
pour que ce soit plus simple par la suite de comprendre de quel client on parle.

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/models.py
> +    - ``get_schema()`` (not mandatory, but otherwise, ES will choose the schema by itself) ;
```suggestion
    - ``get_schema()`` (not mandatory, but otherwise, the search engine will choose the schema by itself) ;
```

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/models.py
> +        See https://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html#schemas
Lien à supprimer ? (la note au-dessus aussi ?)

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/models.py
> +        return es_schema
Encore trop de mentions à ElasticSearch à mon goût :)

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/models.py
>          See https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html.
Encore d'actualité de faire des bulks ? (le lien n'est certainement plus pertinent !)

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/models.py
> +    return int(time.mktime(date.timetuple()))
`date.timestamp()` ne fait pas le boulot ?

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/posts.jsonl
Fichier à supprimer maintenant.

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/publishedcontent.jsonl
Fichier à supprimer maintenant.

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/models.py
>      def es_bulk_indexing_of_model(self, model, force_reindexing=False):
```suggestion
    def bulk_indexing_of_model(self, model, force_reindexing=False):
```

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/models.py
>      es_already_indexed = False
```suggestion
    already_in_search_engine = False
```

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/models.py
> +            pass
Qu'est-ce qui peut arriver comme exception ? On veut vraiment la passer sous silence ?

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/tests/tests_models.py
>          self.assertTrue(manager.index not in self.manager.es.cat.indices())
`es` a été renommé `search` (et à de nombreuses occurrences plus bas)

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/models.py
> +    index_id = ""
```suggestion
    search_engine_id = ""
```
me paraît mieux, car sinon on peut ne pas savoir de quel index il s'agit.

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/topics.jsonl
Fichier à supprimer maintenant.

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/views.py
> +from .client import client
Non, il faut faire comme vous avez fait dans `zds/searchv2/models.py`.

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/views.py
> +    def _add_a_numerical_filter(self, field, values):
```suggestion
    def _add_numerical_filter(self, field, values):
```

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/views.py
> +        values : is a list of int with value that we want for the field
Tant qu'à faire, autant utiliser le format correct pour générer une belle doc : 
```
:param field: name of the field to filter
:type field: str
:param values: list of values we want for the field
:type values: List[int]
```
(un truc du genre, regarde les autres fonctions pour t'inspirer)

Aussi, on commence lentement à mettre en place du typing, donc, pourquoi ne pas avoir : 
```py
def _add_numerical_filter(self, field: str, values: List[int])

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/views.py
> +    Site members who are part of the staff can choose at the end of a publication to suggest another content of the site.
```suggestion
    Staff members can choose at the end of a publication to suggest another content of the site.
```

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/views.py
> +    content proposals are then made.
```suggestion
    content proposals are then made, using the search engine through this view.
```

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/views.py
> +    def _add_a_negative_numerical_filter(self, field, values):
```suggestion
    def _add_negative_numerical_filter(self, field, values):
```

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/views.py
> +        Indeed, in 0.24.0, Typesense doesn't allow numerical negation
```suggestion
        Indeed, in its version 0.24.0, Typesense doesn't allow numerical negation
```

Ce n'est pas clair quel est le problème et qu'est-ce que vous voulez vraiment faire. En lisant sans trop réfléchir, j'avais compris que c'était pour filtrer suivant des nombres négatifs. En fait c'est pour exclure un nombre ? Utiliser le terme `exclude` serait sans doute alors plus parlant que `negation` (*exclude  a numerical value*).

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/views.py
> +        values : is a list of strings with value that we don't want for the field
Idem que plus haut concernant le format de ce commentaire pour générer une belle doc.

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/views.py
>              messages.warning(self.request, _("Impossible de se connecter à Elasticsearch"))
```suggestion
            messages.warning(self.request, _("Impossible de se connecter au moteur de recherche."))
```

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/views.py
> +            # Check if the conent must be validated
```suggestion
            # Check if the content must be validated
```

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/views.py
> +            # Check which collections needs to search
```suggestion
            # Check in which collections search is performed
```
c'est bien ce que vous voulez dire ?

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/views.py
> +            # Check which type of content is needed
```suggestion
            # Check which content types are searched
```

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/views.py
> +            # Typesense Search
Commentaire inutile, en plus ça rajoute une mention à TypeSense dans le code.

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/views.py
> +                    search_collections = ["publishedcontent", "topic", "chapter", "post"]
Ce `if` pourrait plutôt être au moment où vous définissez la première valeur de `search_collections` (ligne 208). Là on est à un endroit du code où on est sur le point de lancer la requête à TypeSense, ce n'est pas le meilleur endroit pour changer des choses !

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/views.py
> +            # filter += "content_type == [`TUTORIAL`, `ARTICLE`]"
Commentaire (et les suivants) à supprimer ?

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/views.py
> +        # filter = self._add_a_filter("forum_pk", self.authorized_forums, filter)
Il ne faut pas oublier de ne lister que les forums auxquels on a accès, donc à ne pas laisser en commentaires.

2023-04-02 18:21 UTC, philippemilink commented on zds/searchv2/views.py
> +    def _add_a_filter(self, field, value, current_filter):
```suggestion
    def _add_filter(self, field, value, current_filter):
```

2023-04-02 18:21 UTC, philippemilink commented on zds/settings/abstract_base/zds.py
> +                "protocol": "http",  # For Typesense Cloud use https
On s'en fout de Typesense Cloud :)

2023-04-02 18:21 UTC, philippemilink commented on zds/settings/abstract_base/zds.py
> +SEARCH_INDEX = {}
Cet objet semble inutile maintenant, non ?

2023-04-02 18:21 UTC, philippemilink commented on zds/settings/prod.py
> +SEARCH_INDEX["shards"] = config["elasticsearch"].get("shards", 3)
Inutile.

2023-04-06 19:38 UTC, victorlohezic commented on zds/searchv2/views.py
> +        Indeed, in 0.24.0, Typesense doesn't allow numerical negation
On voulait bien parler de l'exclusion d'un nombre. Je vais faire la modification.

2023-04-06 19:43 UTC, victorlohezic commented on zds/searchv2/views.py
> +            # Check which collections needs to search
Oui c'est bien ça, merci.

2023-04-07 15:24 UTC, philippemilink commented on zds/settings/prod.py
> -ES_SEARCH_INDEX["shards"] = config["elasticsearch"].get("shards", 3)
Ici il faudrait mettre : 
```py
SEARCH_CONNECTIONS["default"]["api_key"] = config["typesense"].get("api_key", "xyz")
```
Pour que lors du déploiement de Zeste de Savoir, la clé d'API soit récupérée d'un fichier de configuration externe au dépôt Git ([celui-là](https://github.com/zestedesavoir/ansible-zestedesavoir/blob/main/roles/app/templates/config.toml.j2)).

(et d'autres clés d'API si on utilise plusieurs clés avec des permissions différentes)

2023-04-07 15:27 UTC, philippemilink commented on scripts/define_variable.sh
> +    ZDS_TYPESENSE_VERSION="0.24.0"
On vient de  passer à 0.24.1 :)

2023-04-07 15:28 UTC, philippemilink commented on scripts/install_zds.sh
> +        ./$typesense_path/typesense-server --data-dir=$(pwd)/typesense-data --api-key=$ZDS_TYPESENSE_API_KEY --enable-cors
Puisqu'on n'interrogera pas TypeSense depuis des requêtes JavaScript, le paramètre `--enable-cors` ne semble pas nécessaire (cf la [doc](https://typesense.org/docs/0.24.1/api/server-configuration.html#using-command-line-arguments)).

2023-04-22 14:58 UTC, philippemilink commented on zds/searchv2/views.py
> +                    "query_by_weights": f"{settings.ZDS_APP['search']['boosts']['publishedcontent']['title']},{settings.ZDS_APP['search']['boosts']['publishedcontent']['description']},{settings.ZDS_A
C'est difficilement lisible, et je pense que ça ne plaira pas à `blake` parce que la ligne est bien trop longue (tente de lancer `make lint-black`).

Tu peux faire quelque chose du genre : 
```py
content_boosts = settings.ZDS_APP['search']['boosts']['publishedcontent']
# ...
"query_by_weights": "{},{},{},{}".format(
    content_boosts['title'],
    content_boosts['description'],
    # ...
)
```
(idem plus bas)

2023-04-22 19:55 UTC, victorlohezic commented on zds/searchv2/views.py
> +                    "query_by_weights": f"{settings.ZDS_APP['search']['boosts']['publishedcontent']['title']},{settings.ZDS_APP['search']['boosts']['publishedcontent']['description']},{settings.ZDS_A
C'est vrai que c'était pas top pour la lisibilité, j'ai apporté la modification (pour info make lint-back ne posait pas de problème).

2023-04-23 14:46 UTC, victorlohezic commented on zds/searchv2/views.py
> +        values : is a list of int with value that we want for the field
J'ai mis à jour les commentaires pour la documentation. Cependant par défaut Sphinx ne génère pas la documentation pour les méthodes privées. 
On peut ajouter cette ligne dans `doc/source/conf.py`  pour le faire :

```python
# -- Extension configuration -------------------------------------------------
autodoc_default_options = {'private-members': True}
```
Est-ce que je les rends publiques ou je modifie le fichier de configuration ?

2023-04-23 16:48 UTC, philippemilink commented on zds/searchv2/views.py
> +        values : is a list of int with value that we want for the field
> Est-ce que je les rends publiques ou je modifie le fichier de configuration ?

Je dirais aucun des deux. Ce n'est pas grave si elles n'apparaissent pas dans la documentation celles-ci.

2023-04-24 17:35 UTC, philippemilink commented
Sentry rapporte que l'erreur suivante a lieu lorsqu'on tente de chercher `*` : 
```
KeyError: 'text_match'
  File "django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "zds/searchv2/views.py", line 188, in get
    return super().get(request, *args, **kwargs)
  File "django/views/generic/list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "zds/searchv2/views.py", line 256, in get_queryset
    result = self.get_queryset_multisearch(search_requests, search_collections)
  File "zds/searchv2/views.py", line 273, in get_queryset_multisearch
    all_collection_result.sort(key=lambda result: result["text_match"], reverse=True)
  File "zds/searchv2/views.py", line 273, in <lambda>
    all_collection_result.sort(key=lambda result: result["text_match"], reverse=True)
```

Je viens de le reproduire sur le serveur bêta. Ça a pu être corrigé avec les derniers commits, mais je préfère le signaler.

2023-04-24 21:07 UTC, philippemilink commented on zds/searchv2/views.py
> +        if self.search_query != "*":
Je suis sceptique. J'allais dire que le bug se produit sans doute aussi avec d'autres caractères spéciaux, mais je n'ai pas réussi à en trouver. D'ailleurs, ça fonctionne si on peut un espace avant ou après l'astérisque. L'astérisque a une signification particulière pour TypeSense ? 

Une meilleure façon (à mon sens) de gérer ça serait plutôt de vérifier que `text_match` est bien présent. Qu'est-ce que ça veut dire s'il n'est pas présent ?

2023-04-27 16:15 UTC, victorlohezic commented on zds/searchv2/views.py
> +        if self.search_query != "*":
J'ai fait cette correction car d'après la documentation Typesense : 
> Use * as the search string to return all documents. 

Pour moi, c'était le seul cas où il y a un sens à ne pas avoir `text_match`. Je n'ai pas trouvé non plus d'autres caractères spéciaux que l'on peut mettre seul.
C'est vrai que s'il y a d'autres cas dont nous n'avons pas connaissance, vérifier que text_match est bien présent permet au moteur de recherche d'être plus robuste.

2023-04-29 13:57 UTC, philippemilink commented on zds/searchv2/views.py
> +        if self.search_query != "*":
Ok. Dans ce cas, il faudrait faire les choses suivantes : 
- ajouter un commentaire qui explique que `*` permet de retourner tous les documents avec TypeSense (et éventuellement mettre un lien vers la doc qui le dit)
- qu'est-ce qu'on fait si `*` est tout de même recherché ?  j'ai envie de dire de n'afficher aucun résultat (voire un message plus explicite comme `Recherche invalide.`)
- ajouter un test qui recherche `*`
- ce serait quand même bien de ne garder que les résultats qui ont un `text_match`, pour s'assurer que ce point ne nous pétera jamais à la figure. C'est faisable en conditionnant les deux lignes du `for` juste au-dessus par une condition `if 'text_match' in entry:`.

2023-04-29 14:10 UTC, philippemilink commented on zds/searchv2/views.py
> +        if self.search_query != "*":
Ah, je vois que vous vous servez dans les tests du fait que chercher `*` renvoie tout ce qui est indexé. Autant pour les tests, ça ne me gêne pas, autant en production la possibilité de demander à TypeSense de renvoyer tout ce qu'il a m'inquiète car c'est inutile et ça va utiliser beaucoup de ressource (bande passante, traitement des résultats, etc). À l'extrême on pourrait presque considérer comme une possible attaque par déni de service. Est-ce qu'il n'y a pas un autre moyen dans les tests de demander à TypeSense qu'il retourne tout ce qu'il a indexé ?

2023-04-30 16:57 UTC, philippemilink commented on templates/searchv2/search.html
> +                    Recherche invalide.
```suggestion
                    {% trans "Recherche invalide." %}
```
Et il faut aussi traduire la chaîne dans le test correspondant.

2024-07-30 16:41 UTC, artragis commented on zds/search/utils.py
> +                                objects_per_batch >>= 1  # use >> 1 instead of / 2 to keep an int
De ce fait pour que ça soit plus clair autant utiliser l'opérateur "division entière" : `objects_per_batch //= 2`

2024-09-24 20:05 UTC, philippemilink approved these changes

2024-09-25 19:37 UTC, merged