Ajout des claps sur les contenus
zestedesavoir/zds-site pull request #6499
Opened 2023-05-22 18:20 UTC by Migwel

Fix #6094 

Il s'agit de la fonctionnalité de base, j'ouvre déjà cette PR pour recevoir des retours sur l'implémentation actuelle, en particulier niveau front-end. Pour résumer ce qui est fait:
**Back-end:**
* Un nouveau endpoint est mis en place qui permet d'ajouter (POST), obtenir (GET) et supprimer (DELETE) des claps par contenu. Ceci n'est disponible qu'aux utilisateurs connectés, pour les contenus visibles (en beta ou publiés)
* Le nombre de claps pour un contenu est renvoyé dans la View qui permet de consulter les contenus

**Front-end:**
* Je débute en front et la façon dont j'ai implémenté ça est assez différente des autres fichiers js que j'ai vu dans le projet donc je suis curieux de ce que vous en pensez
* Ce que ça fait, c'est afficher les claps dans le contenu et permet d'ajouter ou retirer les claps en appuyant sur le bouton.
* Ici, j'ai mis les boutons en haut du contenu, un peu "à la va-vite" car j'aimerais savoir ce que vous pensez être le meilleure place où les afficher
* Pour le moment, j'ai réutilisé le symbole des likes (pouce gris et pouce vert) par facilité mais si on est d'accord d'utiliser l'emoji : clap:, je peux changer ça et introduire ce symbole.

**Points supplémentaires:**
* J'ai décidé d'uniquement autoriser les membres connectés à voter. Je trouve que c'est plus simple à gérer et ça a plus de sens à mon goût. Si on veut ouvrir les claps aux membres non-connectés, il sera toujours possible de modifier la fonctionnalité dans le futur
* De la même manière, je n'autorise chaque utilisateur à ne donner qu'un seul clap, une fois encore pas souci de simplicité

### Contrôle qualité
Avant toute chose, lancez `python manage.py migrate` pour créer la table Clap et chargez le jeu de données standards localement (`make generate-fixtures`) afin d'avoir des contenus

Lancez ZDS localement (make run-fast) et rendez-vous sur un contenu (tutoriel, article, billet) et voyez qu'un nouvel icône pour les claps est visible.

Pour tester la fonctionnalité, jouez un peu avec le nouveau bouton.  Cliquer sur le bouton devrait incrémenter le nombre de claps et rendre le pouce vert, cliquer à nouveau devrait décrémenter ce nombre et rendre le pouce gris.
Il serait bon aussi de se connecter avec un autre utilisateur et vérifier que le clap ajouté avec user1 est visible par user2.

2023-05-27 21:14 UTC, philippemilink requested changes
C'est un bon début !

J'ai fait pas mal de remarques sur le code, et pense à exécuter `make lint-front` et `make format-front` pour t'éviter les erreurs de style dans le JavaScript.

> Ici, j'ai mis les boutons en haut du contenu, un peu "à la va-vite" car j'aimerais savoir ce que vous pensez être le meilleure place où les afficher

Moi je le mettrais en bas du contenu, juste en-dessous de la conclusion : on a finit de lire le contenu, oh on peut mettre un clap, aller c'est un bon contenu, je mets un clap. Si c'est en haut du contenu, on ne va pas forcément penser à revenir mettre un clap une fois la lecture du contenu terminée.

Tu as vérifié comment ça s'affichait sur les tutoriels avec plusieurs pages (plusieurs parties / chapitres) ? Puisqu'on clappe un contenu entier (un tutoriel entier), il faudrait que les claps ne s'affichent que sur la page principale du tutoriel (celle qui affiche le sommaire) et pas sur les conteneurs (partie, chapitre). Ou alors on décide qu'on peut clapper des parties ou des chapitres, mais ça me semble être plus compliqué...

> De la même manière, je n'autorise chaque utilisateur à ne donner qu'un seul clap, une fois encore pas souci de simplicité

Ça me va, ce serait bien d'ajouter un test avec un utilisateur qui tente de clapper deux fois un contenu (il ne me semble pas avoir vu un tel test).

2023-05-27 21:14 UTC, philippemilink commented on assets/js/clap.js
> +    })
Il y a un objet `window.ajax` qui abstrait les requêtes ajax et qui évite à s'embêter avec tous ces paramètres. Il est défini [là](https://github.com/zestedesavoir/zds-site/blob/dev/assets/js/common/ajax.js) et est utilisé [là](https://github.com/zestedesavoir/zds-site/blob/dev/assets/js/button-toggle.js) par exemple.

(idem plus bas pour les autres utilisations de `fetch`)

2023-05-27 21:14 UTC, philippemilink commented on zds/tutorialv2/api/serializers.py
> +        return publication
À quoi sert cette méthode ? J'ai l'impression qu'elle n'est jamais appelée...

2023-05-27 21:14 UTC, philippemilink commented on zds/tutorialv2/api/urls.py
> +    path("publication/<int:publication_id>/claps", ClapView.as_view(), name="claps"),
J'ai du bien lire le contenu de `ClapView` pour comprendre que cette vue gérait seulement le clap de l'utilisateur connecté et que faire un simple GET sur cette URL ne renvoie pas le nombre total de claps pour un contenu. Je changerais donc l'URL en `"publication/<int:publication_id>/user-clap"` (et mettrais un commentaire expliquant tout ça au début de la classe `ClapView`).

2023-05-27 21:14 UTC, philippemilink commented on zds/tutorialv2/api/views.py
> +        clap = Clap.objects.filter(publication_id=self.kwargs["publication_id"]).filter(user=self.request.user).first()
```suggestion
        clap = Clap.objects.filter(publication_id=self.kwargs["publication_id"], user=self.request.user).first()
```
Tu l'as pourtant bien fait juste au-dessus :)

2023-05-27 21:14 UTC, philippemilink commented on zds/tutorialv2/api/views.py
> +        data = request.data.copy()
Tu es obligé de faire une copie de l'objet ici ?

2023-05-27 21:14 UTC, philippemilink commented on zds/tutorialv2/models/database.py
> +        verbose_name="Contenu",
```suggestion
        verbose_name=_("Contenu"),
```

2023-05-27 21:14 UTC, philippemilink commented on zds/tutorialv2/models/database.py
> +        verbose_name="Utilisateur",
```suggestion
        verbose_name=_("Utilisateur"),
```

2023-05-27 21:14 UTC, philippemilink commented on zds/tutorialv2/tests/test_claps.py
> +            self.fail("Exception")
Pas la peine de faire des try/except Exception dans les tests : si une exception se produit, le test sera marqué en erreur, c'est bien le comportement qu'on souhaite.

(idem pour les autres occurrences plus bas)

2023-05-27 21:14 UTC, philippemilink commented on zds/tutorialv2/tests/test_claps.py
> +        print(result.data)
```suggestion
```

2023-05-27 21:14 UTC, philippemilink commented on zds/tutorialv2/tests/test_claps.py
> +        self.assertNotEqual(None, result.data.get("publication"))
```suggestion
        self.assertIsNotNone(result.data.get("publication"))
```

2023-05-27 21:14 UTC, philippemilink commented on zds/tutorialv2/tests/test_claps.py
> +        print(result.data)
```suggestion
```

2023-05-27 21:14 UTC, philippemilink commented on zds/tutorialv2/tests/test_claps.py
> +        self.assertNotEqual(None, result.data.get("user"))
```suggestion
        self.assertIsNotNone(result.data.get("user"))
```

2023-05-27 21:14 UTC, philippemilink commented on zds/tutorialv2/tests/test_claps.py
> +        return tuto
On a `PublishedContentFactory` qui fait ça.

2023-05-27 21:14 UTC, philippemilink commented on zds/tutorialv2/views/display.py
> +        context["nb_claps"] = len(Clap.objects.filter(publication_id=self.object.id))
```suggestion
        context["nb_claps"] = Clap.objects.filter(publication_id=self.object.id).count()
```

2024-03-09 18:04 UTC, Arnaud-D commented
Salut,

Nous avons décidé pendant la réunion des dév de ne pas fusionner cette PR avec le concept actuel.

La proposition est trop éloignée de la vision initiale pour la fonctionnalité des "claps". Ça signifie que si on la fusionnait, on devrait quasiment tout changer pour évoluer vers la version finale et on pense que ça ne vaut pas le coup.

Je regrette qu'on ait mis du temps à décider ça, j'espère que tu n'es pas trop frustré par le temps que tu as mis là-dedans et qui n'a pas porté ses fruits.

2024-03-09 18:04 UTC, closed without merging