Update footer.html
zestedesavoir/zds-site pull request #6515
Opened 2023-07-01 12:00 UTC by qwertygc

Proposition de renommer « à propos » en « crédits techniques » pour éviter la confusion avec une page de présentation du site/asso

### Contrôle qualité

2023-07-01 14:12 UTC, philippemilink requested changes

2023-07-01 14:12 UTC, philippemilink commented on templates/footer.html
> -            <li><a href="{% url "pages-about" %}">{% trans "À propos" %}</a></li>
Pour rester cohérent, tu peux aussi renommer la route et le template associé : remplacer `about` par quelque chose comme `technologies` (y a sans doute mieux comme terme).

2023-07-01 16:40 UTC, qwertygc commented on templates/footer.html
> -            <li><a href="{% url "pages-about" %}">{% trans "À propos" %}</a></li>
technologies me semble bien (faute de mieux)

2023-08-26 13:36 UTC, Arnaud-D commented on templates/footer.html
> -            <li><a href="{% url "pages-about" %}">{% trans "À propos" %}</a></li>
J'ai pris en compte le commentaire.

2023-08-26 13:36 UTC, Arnaud-D commented
J'ai fait la modification manquante. J'ai aussi modifié un autre endroit du code où apparaît le lien, mais je ne suis pas sûr que ça soit jamais affiché.

2023-09-03 13:28 UTC, philippemilink requested changes
Il faudrait aussi renommer le template `templates/pages/about.html` en `technologies.html` (par exemple). Dans ce template, il faut aussi renommer toutes les occurrences de "À propos" (le titre, le fil d'Ariane, ...) par "Crédits techniques". 

En y réfléchissant, ça me dérange un peu que la colonne "Droits" (crédits des images) soit sur une page "Crédits techniques" : les images ne sont pas des technologies... Mais je suis peut-être un peu trop tatillons...

2023-09-03 13:28 UTC, philippemilink commented on zds/pages/urls.py
> +    path("apropos/", about, name="pages-technologies"),
```suggestion
    path("technologies/", about, name="pages-technologies"),
```
Pour être cohérent. Ça ne pose pas de problème, je dirais qu'on s'en fout du référencement pour cette page.

2023-09-03 13:30 UTC, philippemilink commented
> J'ai aussi modifié un autre endroit du code où apparaît le lien, mais je ne suis pas sûr que ça soit jamais affiché.

Si, c'est la page qui est affichée lorsque tu vas sur cette page "Crédits techniques" et que tu cliques sur le lien "Pages" dans le fil d'Ariane :)

2023-09-29 16:42 UTC, Arnaud-D commented on zds/pages/urls.py
> +    path("apropos/", about, name="pages-technologies"),
C'est fait.

2023-09-29 16:44 UTC, Arnaud-D commented
> En y réfléchissant, ça me dérange un peu que la colonne "Droits" (crédits des images) soit sur une page "Crédits techniques" : les images ne sont pas des technologies... Mais je suis peut-être un peu trop tatillons...
Ça ne me dérange pas plus que ça, c'est pas le genre de page centrale de toute façon. :)

J'en ai profité pour retirer la version obsolète de jQuery qui était mentionnée.

2023-10-08 21:01 UTC, philippemilink approved these changes
**QA OK** :heavy_check_mark:

2023-10-08 21:09 UTC, merged