Remplace la méthode obsolète request.is_ajax (préparation pour Django 4)
zestedesavoir/zds-site pull request #6536
Opened 2023-10-01 14:11 UTC by Arnaud-D

Cette PR fait partie de modifications nécessaires pour passer à Django 4.

On utilise régulièrement `request.is_ajax()` pour savoir si la requête provient du frontend de manière asynchrone, etc. Django a décidé que la méthode de détection était trop spécifique à JQuery et a décidé de supprimer la méthode dans Django 4. Une correction simple est de créer sa propre focntion qui reprend la même logique, ce que j'ai fait. C'est aussi une des solutions recommandées.

J'ai corrigé une coquille dans un truc qui n'a rien à voir au passage. **Ne pas squasher au merge**, ça sera mieux pour ne pas tout mélanger.

### Contrôle qualité

- CI
- lancer le site et utiliser les pages qui font des requêtes asynchrones (la preview des messages, les champs avec autocomplétion, etc. ; on peut regarder le code si on veut exercer manuellement tous les chemins d'exécution)

2023-10-01 14:14 UTC, Situphen requested changes, later dismissed

2023-10-01 14:14 UTC, Situphen commented on zds/mp/views.py
> +from ..utils.misc import is_ajax
```suggestion
from zds.utils.misc import is_ajax
```

2023-10-01 14:17 UTC, Arnaud-D commented on zds/mp/views.py
> +from ..utils.misc import is_ajax
Corrigé.

2023-10-01 18:14 UTC, artragis commented on zds/utils/misc.py
> +def is_ajax(request):
serait-il possible d'ajouter une docstring où on explique clairement le besoin de cette méthode, pourquoi elle a été créée et pourquoi ça continue de fonctionner même si on utilise de plus en plus fetch à la place de jquery?

2023-10-08 16:36 UTC, Arnaud-D commented on zds/utils/misc.py
> +def is_ajax(request):
C'est fait.

2023-10-08 20:53 UTC, philippemilink approved these changes
**QA OK** :heavy_check_mark: 

Testé en citant un post de forum.

2023-10-08 20:54 UTC, merged