Retire les usages d'une méthode obsolète de Factory Boy
zestedesavoir/zds-site pull request #6541
Opened 2023-10-09 06:39 UTC by Arnaud-D

Dans le cadre de la préparation pour Django 4, j'analyse les logs d'obsoléscence à la recherche de DeprecationWarning et autres choses du genre. Un des problème est qu'une méthode remplit plus 10000 lignes de logs (plus de la moitié), ce qui complique le reste.

Cette méthode est une de Factory Boy :  `_after_postgeneration`.

Cette PR :

* remplace _after_postgeneration par une méthode custom
* conserve le comportement important pour notre code
* anticipe le prochain changement de version majeur (il n'y aura pas ça à faire)
* facilite la lecture des logs d'obsolescence en évitant plus de 10,000 lignes liées à cette méthode

### Contrôle qualité

Comme c'est une méthode utilisée seulement dans les tests, la CI devrait suffire.

2023-10-09 20:45 UTC, philippemilink commented
Comment est-ce que tu actives les DeprecationWarning ? J'essaie de reproduire et comprendre le problème que tu rencontres.

2023-10-09 21:56 UTC, Arnaud-D commented
Oui, j'ai oublié de préciser. C'est la sortie de cette commande qui m'aide à inspecter les avertissements :
 ```
python -Wa manage.py test 2> log_err.txt 1> log_std.txt
```

On passe tous les tests avec un paramètre pour avoir tous les warnings et je transfère le tout vers un fichier pour lire ça tranquillement ensuite.

En regardant la doc, je vois qu'on peut faire moins de warning avec quelque chose du genre :
 ```
python -Wd manage.py test 2> log_err.txt 1> log_std.txt
```

mais ça ne change rien au fait que ce que je change dans cette PR soit obsolète.

2023-10-12 19:42 UTC, philippemilink requested changes
Une petite reformulation du commentaire et c'est bon.

2023-10-12 19:42 UTC, philippemilink commented on zds/member/tests/factories.py
> +        scheduled to be removed in the next major release.
```suggestion
        Save the instance again after the post generation operations. Needed to save
        the password which is set in a post generation method call.

        Skip the save when the object was ‘built’ and not ‘created’. See the Factory Boy
        documentation for details on those build strategies.

        This method replaces the deprecated method from DjangoModelFactory which is
        scheduled to be removed in the next major release (see factory_boy's changelog
        entry for version 3.3.0).
```

En lisant le commentaire original, j'avais du mal à comprendre pourquoi il y en avait besoin et d'où ça venait. Donc je propose cette reformulation (c'est surtout un changement d'ordre des phrases et quelques précisions).

(attention, si tu acceptes la proposition de modification depuis l'interface de GitHub, je suspecte que black ne soit ensuite pas content, parce que j'ai l'impression que ça a fait un peu n'importe quoi avec l'indentation du commentaire...)

2023-10-12 20:21 UTC, Arnaud-D commented on zds/member/tests/factories.py
> +        scheduled to be removed in the next major release.
C'est fait. J'ai repris ton texte sans passer par GitHub pour éviter les surprises.

2023-10-13 20:39 UTC, philippemilink approved these changes
**QA OK** :heavy_check_mark:

2023-10-13 20:39 UTC, merged