Change le type de champ pour la date de publication des unes
zestedesavoir/zds-site pull request #6544
Opened 2023-10-14 21:31 UTC by philippemilink

Fix #6524

### Contrôle qualité

- Se connecter en tant qu'`admin`
- Créer une nouvelle une (par exemple en allant sur un contenu publié et cliquer sur *Ajouter en une*
- Le navigateur propose un datepicker pour le champ *Date de publication* (si le navigateur le supporte)
- Valider le formulaire : tout fonctionne.

2023-10-15 19:35 UTC, Arnaud-D requested changes
En plus de ce que tu as fait, j'ai quelques remarques et questions :

- je mettrai à jour le label, pour faire disparaître la mention du format avec le T dans les exemples
- voir si les input_formats sont toujours nécessaires ?
- le placeholder n'est pas affiché chez moi, donc peut-être l'enlever aussi ?
- est-ce que le format pour le widget est nécessaire si on a déjà un datetime-local ?

2023-10-17 20:27 UTC, philippemilink commented
> * je mettrai à jour le label, pour faire disparaître la mention du format avec le T dans les exemples

C'est fait.
 
> * voir si les input_formats sont toujours nécessaires ?
> 
> * le placeholder n'est pas affiché chez moi, donc peut-être l'enlever aussi ?
> 
> * est-ce que le format pour le widget est nécessaire si on a déjà un datetime-local ?

J'y ai pensé, mais comme c'est dit sur [la doc de Mozilla](https://developer.mozilla.org/fr/docs/Web/HTML/Element/input/datetime-local#g%C3%A9rer_la_prise_en_charge_des_navigateurs) : "Les navigateurs qui n'implémentent pas cette fonctionnalité afficheront un contrôle de saisie textuelle.". Donc si jamais ce n'est pas implémenté, c'est comme si on avait un `<input type="text">`, donc autant tout garder comme si c'était du texte.

Bon, après, tu pourras me rétorquer qu'en fait c'est [déjà supporté partout](https://caniuse.com/mdn-html_elements_input_type_datetime-local)...

2023-10-23 08:10 UTC, Arnaud-D commented
Pour moi, c'est supporté par toute les versions récentes, et en particulier celles utilisées par l'équipe avec les droits pour cette page. Après si tu veux le laisser ou pas, je te laisse décider, ça ne change pas la face du monde. ^^ Les deux me vont.

2023-11-01 16:59 UTC, philippemilink commented
C'est vrai que c'est sur une page qui n'est consultée que par une poignée de membres... J'ai enlevé tout ce qui n'était plus nécessaire.

2023-12-09 18:01 UTC, Arnaud-D approved these changes
QA OK :heavy_check_mark:

2023-12-09 18:09 UTC, merged