Améliore la page qui liste les membres utilisant la même IP
zestedesavoir/zds-site pull request #6545
Opened 2023-10-15 13:28 UTC by philippemilink

* Affichage à côté de l'adresse IP la localisation rapportée par GeoIP (comme ce qu'on peut voir sur la page de profil)
* Utilisation d'un tableau pour liste les membres qui ont utilisé cette adresse IP, pour pouvoir facilement indiquer aussi la date d'inscription de ces membres
* Affichage de *Jamais* si un membre a créé son compte avec cette adresse IP, mais ne s'est jamais connecté ensuite (jusqu'alors au lieu d'avoir une date, on n'avait rien, ce qui pouvait être un peu perturbant)
* Création d'une fonction qui donne la localisation à partir d'une adresse IP, pour éviter de dupliquer ce code
* Amélioration de l'ordre de certains `import`
* Ajout de `{% blocktrans %}` autour d'un texte

### Contrôle qualité

Il faut être membre de l'équipe de modération ou administrateur pour pouvoir QA cette PR.

Pour avoir les données GeoIP, le plus simple sera de la faire sur la bêta. Je vais déployer la PR sur la bêta, je mettrai à jour les instructions de QA ensuite.

* Aller sur la page de profil d'un membre : la localisation doit bien s'afficher à côté de l'IP
* Aller sur la page de l'adresse IP : un tableau de membres s'affiche, indiquant leur date d'inscription et de dernière connexion. S'il n'y a pas eu de de connexion depuis l'inscription, *Jamais* est affiché.
* Avec une IPv6, on a la même chose, mais en plus pour tous les membres connectés avec l'adresse IP/64.

2023-10-15 19:52 UTC, Arnaud-D requested changes, later dismissed
Petit commentaire mineur.

Sinon ça fonctionne bien d'après mes tests.

2023-10-15 19:52 UTC, Arnaud-D commented on zds/member/views/moderation.py
> +    members_and_ip = {
Tu pourrais en profiter pour renommer `members_and_ip` en `context_data`. Le nom correspondrait au rôle plutôt qu'au contenu (ce qui me semble mieux dans le cas présent), et en plus, le contenu n'est pas super bien décrit, vu qu'il manque plein d'autres choses qu'on met là-dedans.

2023-10-16 21:57 UTC, philippemilink commented on zds/member/views/moderation.py
> +    members_and_ip = {
C'est fait.

2023-10-16 21:57 UTC, philippemilink commented
J'ai déployé sur la bêta, corrigé un bug au passage, pris en compte ta suggestion et mis à jour les instructions de QA avec les liens pour tester sur la bêta.

2023-10-17 12:52 UTC, Arnaud-D commented
Je n'ai pas les droits pour QA sur la bêta. On me le rajoute, on trouve un autre dév qui les a ou on demande à un staff de la faire ?

2023-10-17 13:50 UTC, philippemilink commented
Je viens de te rajouter les droits modération et staff, ça devrait être suffisant je pense.

2023-10-22 06:41 UTC, Arnaud-D submitted a review, later dismissed
QA OK, avec un commentaire très mineur.

2023-10-22 06:41 UTC, Arnaud-D commented on templates/member/admin/memberip.html
> +            Liste des membres dont la dernière IP connue est <code>{{ ip }}</code>{{ city }}
La donnée apparaît bien sur la page.

Par contre, l'espace dans la balise ici est bouffé. Il doit y avoir moyen de régler ça dans le template, le CSS ou avec le HTML. En tout cas, il y des explications détaillées de comment HTML gère les espaces sur cette [page de MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace).

Ce n'est pas bloquant, surtout pour une page d'administration. On peut fusionner comme ça.

2023-10-22 15:16 UTC, philippemilink commented on templates/member/admin/memberip.html
> +            Liste des membres dont la dernière IP connue est <code>{{ ip }}</code>{{ city }}
J'ai corrigé le problème en ajoutant un espace insécable : 
```
{% captureas city %}{% if ip_location %}&nbsp;({{ ip_location }}){% endif %}{% endcaptureas %}
```

J'ai mis à jour la bêta, si tu veux regarder.

Si ça te va, je te laisser merger.

2023-10-23 08:04 UTC, Arnaud-D approved these changes
QA OK ✔️ 

C'est impeccable comme ça

2023-10-23 08:04 UTC, Arnaud-D commented on templates/member/admin/memberip.html
> +            Liste des membres dont la dernière IP connue est <code>{{ ip }}</code>{{ city }}
Ouais ça me va comme ça.

2023-10-23 08:04 UTC, merged