Permet la gestion de contributeurs sur les billets
zestedesavoir/zds-site pull request #6551
Opened 2023-10-28 21:18 UTC by Arnaud-D

Permet la gestion (ajout, suppression) des contributeurs sur les billets. Encore une partie du découpage de #6441.

On voit que la refactorisation des templates de publication porte ses fruits. La partie template a pu être gérée en modifiant une seule ligne de configuration.

### Contrôle qualité

Créer des billets et jouer avec les contributeurs.
Constater qu'ils sont bien ajoutés, supprimés.
Constater qu'ils sont bien affichés comme sur les autres contenus.

2023-11-01 17:14 UTC, philippemilink requested changes
Pas encore testé, mais déjà deux petits retours sur le code.

2023-11-01 17:14 UTC, philippemilink commented on zds/tutorialv2/tests/tests_views/tests_addcontributor.py
> +            self.assertRedirects(response, self.content_url)
```suggestion
        for type in CONTENT_TYPE_LIST:
            with self.subTest(type):
                self.content.type = type
                self.content.save()
                response = self.client.post(self.form_url, self.form_data)
                self.assertRedirects(response, self.content_url)
```
En rajoutant
```py
from zds.tutorialv2.models import CONTENT_TYPE_LIST
```
Comme ça, le jour où on rajoute un autre type de contenu, ce sera transparent. Le `subTest` permet de voir plus facilement quel cas fait planter le test.

2023-11-01 17:14 UTC, philippemilink commented on zds/tutorialv2/tests/tests_views/tests_removecontributor.py
> +        self.assertRedirects(response, self.content_url)
Tu peux factoriser cette fonctions avec les deux précédentes comme tu l'as fait dans le fichier zds/tutorialv2/tests/tests_views/tests_addcontributor.py.

2023-12-09 18:18 UTC, Arnaud-D commented on zds/tutorialv2/tests/tests_views/tests_addcontributor.py
> +            self.assertRedirects(response, self.content_url)
Bonne idée, c'est fait;

2023-12-09 18:22 UTC, Arnaud-D commented on zds/tutorialv2/tests/tests_views/tests_removecontributor.py
> +        self.assertRedirects(response, self.content_url)
Non, dans ce test-là ça n'est pas possible, parce qu'il faut relancer le test depuis le début avec le setUp pour avoir la bonne situation initiale.

J'y avais pensé et je suis revenu en arrière. C'est plus simple de laisser tel quel.

2024-04-28 14:02 UTC, philippemilink approved these changes
**QA OK** ✔️

2024-04-28 14:02 UTC, merged