Tente de créer un raccourcis pour que les modo puissent supprimer les mauvais domaines
zestedesavoir/zds-site pull request #6552
Opened 2023-10-29 19:36 UTC by artragis

Je fais une petite PR pour faciliter le ban des domaines de fournisseurs de membres qui ne se connectent que pou spam.
Aujourd'hui une fois le ban fait, il faut aller sur la page des fournisseur, vérifier que le membre qu'on a banni n'est pas en haut de la liste et bannir si c'est nécessaire.

L'ambition (petite) de cette PR est d'ajouter le bouton directement dans l'interface de profile une fois le membre banni.
Mon environnement étant dans les choux, je n'ai pas pu tester, d'où le brouillon, cependant le code devrait être prêt à être reviewé.

2023-10-29 20:03 UTC, Arnaud-D commented on templates/member/profile.html
> +                                {% if profile.user | has_new_provider and can_ban_provider %}
Je pense que ça serait mieux de remonter cette logique dans le code et pas dans le template. Dans le template, on aurait juste quelque chose du genre `{% if show_ban_provider_button %}`.

2023-10-29 20:03 UTC, Arnaud-D commented on templates/member/profile.html
> +                                    <form method="post" action="{% url 'check-new-email-provider' user|get_new_provider_pk %}">
Il y a vraiment besoin d'un filtre ? Des fois qu'il y aurait une méthode (éventuellement à créer), on pourrait faire `profile.get_new_provider` ou quelque chose du genre. Ça nécessiterait d'utiliser le profil à la place du `user` par contre.

2024-10-13 18:33 UTC, Arnaud-D commented on templates/member/profile.html
> +                                        {% trans "Bannir le fournisseur email " %} {{ provider.provider }} ?
Cela devrait être un blocktrans pour être propre niveau traductibiblité. Mais pas bloquant parce qu'on n'a pas prévu de traduire de si tôt...

2024-10-16 05:50 UTC, Arnaud-D commented
À part ma remarque mineure ci-dessous, c'est bon.

2024-10-16 21:02 UTC, philippemilink commented on templates/member/profile.html
> +                                        {% trans "Bannir le fournisseur email " %} {{ provider.provider }} ?
C'est corrigé.

2024-10-16 21:04 UTC, philippemilink commented
Instructions pour la QA : 
1. inscrire un nouvel utilisateur avec un nom de domaine pour l'email pas encore connu du site
2. activer le compte en utilisant l'adresse envoyée par mail, visible dans la console
3. se connecter en tant qu'admin, bannir définitivement le membre qui vient de s'inscrire
4. tester que la popup pour bannir le fournisseur d'email fonctionne bien

2024-10-17 05:54 UTC, Arnaud-D submitted a review, later dismissed
QA OK :heavy_check_mark:

2024-10-17 06:03 UTC, Arnaud-D requested changes
QA NOK

En fait, j'ai une réserve sur l'affichage. On ne peut pas tester facilement en local avec des droits réalistes. Tous les staff sont admin ou presque sur l'environnement de dév. Je pense que ça s'affiche pour tous les staff, alors que les modérateurs en général n'ont pas la gestion des emails (je ne l'avais pas à l'époque où j'étais staff, de mémoire).

C'est pas bloquant, juste des staff qui auront un bouton qui ne marche pas.

2024-10-17 18:34 UTC, philippemilink commented
Euh non, puisque `provider_to_ban` n'est défini que si on le droit de gérer les mails. Si on n'a pas le droit, `provider_to_ban` est évalué à `None`/`False` dans le template, et le bouton ne s'affiche pas.

2024-10-17 20:22 UTC, Arnaud-D approved these changes

2024-10-17 20:23 UTC, merged