Corrige une erreur si la durée d'une sanction temporaire est manquante
zestedesavoir/zds-site pull request #6564
Opened 2023-12-25 21:29 UTC by philippemilink

Sentry nous rapporte que l'erreur suivante : 
```
TypeError: exceptions must derive from BaseException
[...]
  File "zds/member/views/moderation.py", line 167, in modify_profile
    raise HttpResponseBadRequest
```
est levée lorsqu'on applique une sanction temporaire à un membre, mais que la durée de la sanction n'est pas précisée.

Cette PR corrige le problème en capturant les exceptions possibles s'il manque la durée. En plus, j'ajoute un teste et je rends obligatoire le champ de la durée dans le formulaire pour ajouter une sanction temporaire

### Contrôle qualité

Se connecter en tant qu'`admin` et, depuis la page de profil d'un membre, appliquer des sanctions temporaires (banissement et lecture seule) et s'assurer que tout fonctionne toujours comme attendu. On ne peut pas valider le formulaire sans préciser une durée de sanction.

2023-12-29 13:51 UTC, Arnaud-D requested changes
Quelques petits commentaires, mai sinon c'est OK.

Cette partie de la base de code n'est pas folichone de toute façon et la refondre n'est pas l'objectif de la PR. ^^

2023-12-29 13:51 UTC, Arnaud-D commented on zds/member/views/moderation.py
> +        messages.error(request, _("Une erreur est survenue lors de la récupération de la sanction."))
`raise HttpResponseBadRequest` était un bout de code erroné, vu le message que Sentry a remonté. C'est un objet à retourner et pas à `raise`. En conséquence, je pense que ce n'est pas nécessaire de mettre un `TypeError` dans le except du dessous, ce type d'erreur n'est pas censé arriver.

Je n'ai pas réussi à identifier d'où viendrait la ValueError. Probablement pas directement de notre code, ce qui est complique encore plus la recherche.

Aussi, faudrait supprimer l'import HttpBadRequest en haut du fichier aussi, il est désormais inutile.

2024-02-10 21:09 UTC, philippemilink commented
> En conséquence, je pense que ce n'est pas nécessaire de mettre un `TypeError` dans le except du dessous, ce type d'erreur n'est pas censé arriver.

En effet, sans doute un reste de mes essais pour corriger le bug.

> Je n'ai pas réussi à identifier d'où viendrait la ValueError. Probablement pas directement de notre code, ce qui est complique encore plus la recherche.

J'ai mis un commentaire pour l'expliquer. En gros, si les paramètres passés en POST sont invalides (ou absents), ça finit par planter lorsqu'on cherche à accéder à ces paramètres dans `state.apply_sanction()`.

> Aussi, faudrait supprimer l'import HttpBadRequest en haut du fichier aussi, il est désormais inutile.

Bien vu !

2024-02-11 14:58 UTC, Arnaud-D approved these changes
QA OK :heavy_check_mark:

2024-02-11 15:05 UTC, merged