5795 edition intro conclu
zestedesavoir/zds-site pull request #6565
Opened 2023-12-29 12:44 UTC by Vayel

Ajoute des boutons d'édition de l'introduction et de la conclusion des contenus.

![image](https://github.com/zestedesavoir/zds-site/assets/6124369/1e0a324b-b373-448e-a374-4bf2a88cae46)

### Contrôle qualité

2023-12-29 13:07 UTC, Arnaud-D requested changes
En plus des modifications ci-dessous, j'aimerais bien que cette PR aille plus loin en créant des formulaires indépendants pour la modification de l'introduction et de la conclusion. Actuellement, c'est mis en vrac dans un gros formulaire, mais ce n'est pas ce qu'on souhaite garder à l'avenir.

D'ailleurs, cette PR ne résout pas complètement le ticket que tu cites vu que dans celui-ci, il y a une grosse partie _front_ : l'idée était d'avoir le formulaire apparaître sur la même page à la place du rendu de l'intro/conclusion.

2023-12-29 13:07 UTC, Arnaud-D commented on templates/tutorialv2/view/content.html
> +            {{ content }}
À enlever, ça n'a rien à faire là.

2023-12-29 13:07 UTC, Arnaud-D commented on templates/tutorialv2/includes/content/content.part.html
>  {% if content.conclusion and content.get_conclusion != "" %}
Ce n'est pas un moyen convenable de gérer l'affichage. Là, c'est affiché aussi ailleurs que sur les pages d'édition. Inspire-toi de ce qui est fait ailleurs. Tu peux probablement réexploiter le flag `dispay_config.draft_actions.enable_edit` pour gérer l'affichage sans trop d'efforts.

2023-12-29 13:07 UTC, Arnaud-D commented on templates/tutorialv2/view/container.html
>          {% if container.introduction and container.get_introduction %}
Pareil que pour la conclusion, regarde le flag approprié pour gérer l'affichage.

2023-12-31 15:19 UTC, Vayel commented
Merci pour les retours.

Pour le moment je laisse comme ça, peut-être que je ferai évoluer avec des formulaires dédiés.

2024-03-02 17:54 UTC, Arnaud-D approved these changes
QA OK :heavy_check_mark: 

Il reste du travail pour aller au bout du sujet, mais c'est déjà un bon pas en avant. :+1:

2024-03-02 18:01 UTC, merged