Intègre le code de django_munin à notre dépôt
zestedesavoir/zds-site pull request #6578
Opened 2024-01-20 19:11 UTC by Arnaud-D

Cette PR intègre le code de django_munin au sein de notre dépôt. C'est la solution qui a été décidée collégialement par l'équipe de développement plutôt que de reprendre le rôle de mainteneurs du paquet. Gérer un paquet nécessite plus de cérémonie dans le process de mise à jour et on est les derniers utilisateurs connus de ce paquet.

Techniquement :
- le code de `django_munin` est en BSD 3 clauses, ce qui permet bien de l'intégrer à notre produit GPL en conservant la notice de copyright et le texte de la licence ;
- l'intégration se fait sous forme d'app Django,
- j'en ai profité pour exprimer plus claurement les routes associées,
- il y a une subtilité avec la migration, voir ci-dessous.

# Mise en prod

La subtilité avec la migration est qu'en dev, la table utilisée par django_munin pour faire les tests de performance de la base de donnée n'existent pas (en tout cas, pas chez moi). Cela signifie que les migrations inclusent dans le paquet font leur job et créent la table qui va bien.

Cependant, cette table existe bel et bien en prod et sur la bêta (vu que la fonctionnalité marche). Son contenu ne semble pas critique, mais mieux vaut faire ça proprement. Je pense qu'il faudra faire un `python manage.py migrate --fake-initial` pour éviter des soucis. Voir la [doc associée de Django](https://docs.djangoproject.com/en/5.0/ref/django-admin/#cmdoption-migrate-fake-initial).

C'est un WIP. Reste à faire :
- [ ] écrire des tests, au moins grossiers

**Questions**

- Est-ce qu'on se sert du fichier dans `django_munin/plugins` ? C'est un fichier auxiliaire pour interfacer avec munin. Je l'ai converti vers Python 3, mais je ne sais pas si on s'en sert tel que c'est décrit dans la doc de `django_munin`.
- Est-ce qu'on clarifie quelque part que la licence GPL ne s'applique pas à tout, mais seulement à ce qui est n'est pas indiqué autrement ? Parce que j'y pense pour le code de django_munin, mais on n'a d'autres petits bouts avec des licences différentes (les smileys, de mémoire).

### Contrôle qualité

Tester les différentes routes munin (voir urls.py pour savoir lesquelles).

Ça vaudra aussi le coup de tester sur un déploiement bêta je pense, pour voir si ça colle toujours avec le serveur munin.

2024-02-10 19:17 UTC, philippemilink requested changes
### Migration bizarre
Oui, [j'avais déjà remarqué](https://github.com/philippemilink/ansible-zestedesavoir/blob/44b39d3d03c771bba60d57bf0adf914df515ca61/roles/munin/tasks/main.yml#L123-L128) qu'il y avait un truc pas net...

### Fichier `django_munin/plugins/django.py`
Je l'avais [déjà intégré dans le dépôt ansible-zestedesavoir](https://github.com/philippemilink/ansible-zestedesavoir/blob/c460ed5bb961e328563d035d49f9dfa960c433cc/roles/munin/files/plugins/django.py) en le convertissant à Python 3 quand j'ai déployé Munin, en [notant qu'il faudrait le copier depuis zds-site quand il y sera](https://github.com/philippemilink/ansible-zestedesavoir/blob/44b39d3d03c771bba60d57bf0adf914df515ca61/roles/munin/tasks/main.yml#L66-L70). Donc oui, tu peux le laisser là, vérifie juste qu'il n'y a pas (trop) de différence entre ta version et la mienne.

### Préciser la licence quelque part

Tu peux ajouter un paragraphe au fichier `LICENSE` à la racine du dépôt. Et ouvrir un ticket pour qu'on pense un jour à y ajouter les licenses des autres ressources que tu mentionnes.

2024-02-10 19:17 UTC, philippemilink commented on zds/munin/tests.py
> +            "base:db-performance",
Ces routes sont définies dans le module `django_munin`, donc il faudrait qu'elles y soient testées également. Il faudrait donc avoir le même genre de fichier dans `django_munin/` qui ne teste que les routes `base` et garder ce fichier de test dans `zds` pour tester les routes spécifiques à ZdS.

2024-02-10 19:17 UTC, philippemilink commented on zds/settings/abstract_base/django.py
> +    "django_munin.munin",
Je me demandais pourquoi `.munin`... Peut-être que tu peux remonter tout le contenu de `django_munin/munin/` directement dans `django_munin/` ? (et ainsi éviter le `.munin`...)

2024-02-17 18:49 UTC, Arnaud-D commented on zds/munin/tests.py
> +            "base:db-performance",
Pas sûr de l'intérêt de ça.

C'est l'app `zds` qui intégre ces routes-là à toutes les autres routes du site. Les routes ne sont pas testées dans le code du paquet django_munin original, et rien que de les ajouter ici augmente déjà la couverture des tests en s'assurant que ces routes sont joignables. S'il y avait quelque chose à tester dans l'app munin, ça serait plutôt les vues ; les routes sont arbitraires.

Tester les vues django_munin originales, c'est possible, mais c'est du zèle : on ne les testait pas avant et on ne les aurait pas testées si le paquet était resté séparé.

Aussi, si tu décidais qu'on doit tester les _routes_ prédéfinie par django-munin séparément, sache que je ne sais actuellement pas le faire proprement et je n'ai pas envie d'apprendre à le faire pour le moment.

2024-02-17 18:52 UTC, Arnaud-D commented on zds/settings/abstract_base/django.py
> +    "django_munin.munin",
Je n'ai pas envie de faire ça, parce que la structure actuelle est bien rangée. Le dossier `plugins` n'a rien à faire dans le dossier `munin`. Dans plugins, tu as un fichier destiné à un système tiers, et dans `munin`, tu as du code Django. Ce n'est pas très différent de tous les `django.contrib.<blabla>`.

2024-02-17 18:57 UTC, Arnaud-D commented
> ### Fichier `django_munin/plugins/django.py`
> [...] Donc oui, tu peux le laisser là, vérifie juste qu'il n'y a pas (trop) de différence entre ta version et la mienne.

Il y a quelques menues différences. Beaucoup dans "l'en-tête" que je ne comprends pas vraiment et dont je ne peux pas juger l'impact. Il y en a deux autres avec des encode/decode différents d'un côté et de l'autre (pour celles-ci, l'impact me semble faible).

> ### Préciser la licence quelque part
> 
> Tu peux ajouter un paragraphe au fichier `LICENSE` à la racine du dépôt. Et ouvrir un ticket pour qu'on pense un jour à y ajouter les licenses des autres ressources que tu mentionnes.

C'est fait.

Sinon, j'ai répondu aux commentaires plus haut.

2024-02-21 21:54 UTC, philippemilink commented on django_munin/munin/migrations/0002_test.py
> +        migrations.CreateModel(
Je viens de tester la migration, et en effet, en l'état actuel de la PR, elle ne passe pas parce que la table existe déjà. En ajoutant l'opération `RunSQL` suivante, ça fonctionne. Tu peux l'ajouter, stp ?
```suggestion
        migrations.RunSQL("DROP TABLE IF EXISTS munin_test"),
        migrations.CreateModel(
```

2024-02-24 07:14 UTC, Arnaud-D commented on django_munin/munin/migrations/0002_test.py
> +        migrations.CreateModel(
J'ai fait la modif

2024-02-24 15:47 UTC, philippemilink commented on django_munin/plugins/django.py
Désolé, j'aurais pu le dire lors de ma revue de code initiale. Est-ce que tu peux remplacer ce fichier, par celui qui est dans le dépôt ansible-zestedesavoir : https://github.com/zestedesavoir/ansible-zestedesavoir/blob/main/roles/munin/files/plugins/django.py, stp ? Puisque c'est celui qui est déjà utilisé en production, on est sûr qu'il fonctionnera correctement (j'ai regardé un peu les différences, je ne suis pas sûr que la version du fichier actuellement dans la PR fonctionnement exactement comme la version dans ansible-zestedesavoir).

Dès que c'est fait, je fusionne.

2024-02-24 17:48 UTC, Arnaud-D commented on django_munin/plugins/django.py
C'est fait.

2024-02-24 18:24 UTC, philippemilink approved these changes

2024-02-24 18:24 UTC, merged