Ajoute la modification du titre et du sous-titre d'une publication depuis une modale
zestedesavoir/zds-site pull request #6590
Opened 2024-03-06 07:23 UTC by Arnaud-D

Fix #5796.

C'est une reprise sous une forme différente d'une ancienne PR pour résoudre ce ticket.

* Change l'agencement de la ligne de titre et sous-titre pour accomoder deux boutons d'ouverture des modales
* Déplace au passage la licence avec les autres métainformations (sa place n'avait pas de logique particulière en vérité)
* Ajoute le code nécessaire pour traiter ces deux nouveaux formulaires dans les modales
* Modifie le formulaire "éditer" d'un contenu pour enlever la modification du titre et sous-titre qui s'y trouvaient jusqu'à présent
* Le formulaire de création de contenu ne change pas pour le moment (on garde la possibilité d'y saisir titre et sous-titre.

![image](https://github.com/zestedesavoir/zds-site/assets/35631001/0a747abe-b1df-4493-8ef7-b3a673fb141d)

# À faire

Ajouter des tests

### Contrôle qualité

Tester la modification du titre et sous-titre sur la page de brouillon.

Voir si l'affichage des boutons est absent depuis la page en ligne, celle de validation et celle de bêta.

Vérifier que le formulaire "éditer" fonctionne toujours bien.

2024-03-30 17:00 UTC, philippemilink requested changes
Ça fonctionne, juste une petite question/suggestion dans le code.

2024-03-30 17:00 UTC, philippemilink commented on zds/tutorialv2/forms.py
> +        self.helper.layout.append(StrictButton("Valider", type="submit"))
Pourquoi pas ça :
```suggestion
        Field("msg_commit"),
        StrictButton("Valider", type="submit"),
        )
```
 ? Je vois que c'est pareil dans `ContentForm`, mais puisque c'est du nouveau code, autant faire directement quelque chose de propre :)

2024-03-30 21:27 UTC, Arnaud-D commented on zds/tutorialv2/forms.py
> +        self.helper.layout.append(StrictButton("Valider", type="submit"))
C'est fait. C'est effectivement mieux de faire comme tu suggères.

Cette série de formulaire a plein d'avertissements dans mon IDE, mais c'est une tâche annexe qui peut être faite séparément ou au fur et à mesure.

2024-03-31 16:43 UTC, philippemilink approved these changes
**QA OK** :heavy_check_mark:

2024-03-31 16:43 UTC, merged