Teste et corrige l'affiche de quelques éléments de la sidebar des contenus
zestedesavoir/zds-site pull request #6599
Opened 2024-03-31 17:20 UTC by philippemilink

Fix #6596 

Cette PR fait plusieurs choses : 
- ajout de tests pour vérifier que les éléments à afficher dans la barre latérale des contenus sont bien affichés uniquement sur les bonnes pages
- correction de l'affichage *La version X est identique à cette version*
- affichage de *Exports du contenu* sur la page publique des contenus
- amélioration du code dans `display/config.py`

### Contrôle qualité

Faire manuellement ce que fait le test ajouté. 

Jouer avec les différents états possibles d'un contenu, afficher les différentes pages et s'assurer qu'il n'y a pas d'éléments incohérents dans la barre latérale (je ne dis pas que cette PR règle tous ces problèmes, ne pas hésiter à rapporter les éventuelles incohérences observées).

2024-04-06 20:36 UTC, Arnaud-D requested changes
Ça marche, mais je préfèrerais qu'on change quelques trucs niveau positionnement des éléments.

Et des suggestions sur le code aussi. ^^

2024-04-06 20:36 UTC, Arnaud-D commented on templates/tutorialv2/includes/sidebar/public_actions.part.html
> +                        {{ public_actions.messages|get_item:"draft_is_more_recent" }}
Je pense que cette mention devrait être tout en haut,  avec "Voir la version brouillon". Comme ça pointe vers la même page, il faudrait peut-être transformer ça juste en note d'information (grisée).

C'est peut être aussi le signe qu'il faudrait une section "Version brouillon", comme on a "Version publique".

Je pense qu'être un peu ordonné à ce niveau-là peut améliorer la navigation et la compréhension de l'éditeur.

Faudra ranger la logique d'affichage en Python du bon côté aussi.

2024-04-06 20:36 UTC, Arnaud-D commented on zds/tutorialv2/tests/tests_views/tests_display.py
> +        self.assertNotContains(validation_page, ValidationActions.messages["validation_is_same"])
Pas fan de ce test. J'ai été confronté à d'autres tests avec une séquence longue de ce type (il y en a plein dans le module `tutorialv2`). Je les ai trouvé dur à faire évoluer.

Je préfère qu'on teste chaque route/vue indépendamment, quitte à faire des fonctions auxilaires pour atteindre les états cibles (par exemple avoir un tuto en validation, avoir un tuto publié avec une version brouillon plus récente, etc.), tester si nécessaire des préconditions pour vérifier qu'on est bien dans l'état souhaité avant le test, puis tester ensuite ce qu'on veut effectivement tester unitairement.

Ici, ça voudrait dire tester séparément la page brouillon, la page publique, etc, éventuellement avec différents sous cas. Il y a un embryon dans ce fichier : `tests_contentvalidationview.py`. Le contenu d'une page n'est qu'un test particulier parmi d'autres pour la vue de validation.

Malheureusement, le reste des tests du module ne semble pas structuré dans ce sens, mais on devrait tendre vers ça à mon avis.

2024-04-06 20:36 UTC, Arnaud-D commented on zds/tutorialv2/tests/utils.py
> +    content.save()
Pour info, je n'avais pas osé mettre cette fonction utilitaire en dehors du fichier de test spécifique où elle a été écrite, parce que je ne suis pas sûr que la manière d'émuler une validation soit suffisante dans d'autres tests que ceux que j'avais considéré à l'époque.

2024-06-23 13:59 UTC, philippemilink commented on templates/tutorialv2/includes/sidebar/public_actions.part.html
> +                        {{ public_actions.messages|get_item:"draft_is_more_recent" }}
J'ai un peu regardé comment faire ça, et j'ai l'impression que ça va demander plus de travail que tout ce qui est déjà fait dans cette PR. Je suis d'accord sur le principe avec toi, mais je pense que ça peut être fait une autre PR.

2024-06-23 14:00 UTC, philippemilink commented on zds/tutorialv2/tests/tests_views/tests_display.py
> +        self.assertNotContains(validation_page, ValidationActions.messages["validation_is_same"])
J'ai restructuré les tests et, en effet, ça les rend bien plus lisibles.

2024-06-23 14:00 UTC, philippemilink commented on zds/tutorialv2/tests/utils.py
> +    content.save()
On verra comment ça évolue avec le temps, si on a besoin que cette fonction en fasse plus ou pas.

2024-07-20 13:33 UTC, Arnaud-D approved these changes

2024-07-20 13:40 UTC, merged