Ajoute un formulaire pour modifier les catégories d'une publication
zestedesavoir/zds-site pull request #6603
Opened 2024-04-06 21:38 UTC by Arnaud-D

Actuellement, la modification des catégories est dans un formulaire fourre-tout. Cette PR déplace ce choix dans un formulaire dédié. On y accède par un bouton, comme pour les formulaires de licence.

![image](https://github.com/zestedesavoir/zds-site/assets/35631001/c634e28a-44c4-4f5a-9c27-d5bd5e44d8b4)

![image](https://github.com/zestedesavoir/zds-site/assets/35631001/031f523e-dff6-4122-8302-1f072826e363)

Fix #5908

# À faire

Écrire des tests unitaires pour la nouvelle vue.

### Contrôle qualité

- Créer des contenus.
- Assigner des catégories, en supprimer.
- Demander la validation avec des catégories, sans catégories.

2024-04-24 17:38 UTC, philippemilink requested changes
Une petite ligne à supprimer, un rebase est on est bon

2024-04-24 17:38 UTC, philippemilink commented on templates/tutorialv2/edit/categories.html
> +{% load feminize %}
```suggestion
```
Cette ligne ne fournit aucun tag utilisé.

2024-04-24 19:49 UTC, Arnaud-D commented
Changements pris en compte.

2024-04-25 18:49 UTC, philippemilink requested changes
En fait il y a encore deux lignes inutiles (désolé de ne pas l'avoir remarqué lors de ma première revue).

2024-04-25 18:49 UTC, philippemilink commented on templates/tutorialv2/edit/categories.html
> +{% load thumbnail %}
```suggestion
```

2024-04-25 18:49 UTC, philippemilink commented on templates/tutorialv2/includes/headline/categories.part.html
>  {% load pluralize_fr %}
```suggestion
```

2024-04-26 10:48 UTC, philippemilink approved these changes
**QA OK** ✔️

2024-04-26 10:50 UTC, merged