Ajoute une commande pour supprimer les vieilles adresses IP
zestedesavoir/zds-site pull request #6608
Opened 2024-04-19 23:04 UTC by Situphen

PR liée au [sujet sur le forum concernant l'intégration des sources externes](https://zestedesavoir.com/forums/sujet/17409/le-site-zestedesavoircom-et-le-rgpd/)

Pour le moment, supprime simplement les adresses IP des messages du forum, messages privés et commentaires datant de plus d'un an.

**QA :** Test unitaire + Test en bêta ?

2024-04-20 13:42 UTC, philippemilink commented
Je vois que ce n'est qu'en brouillon pour l'instant, mais déjà quelques suggestions : 
- Ajouter un paramètre pour définir le délai à partir duquel anonymiser (par défaut on peut mettre 1 an bien-sûr ; ça demande de renommer la commande)
- Dans le test, essaie aussi d'afficher une page qui contient un des commentaires dont tu viens d'effacer l'adresser IP (affichage en tant que membre qui a le droit de voir les adresses IPs des commentaires)
- Y a un truc que j'ai peut-être mal saisi dans la discussion sur le forum : on supprime les IPs de tous les messages plus vieux d'un an ? J'avais compris qu'il fallait supprimer les IPs des commentaires postés par les membres qui ne se sont pas connectés depuis un an.
- C'est peut-être l'occasion d'ajouter une page dans la documentation qui explique tous les mécanismes qu'on a en place pour respecter le RGPD

2024-04-20 15:23 UTC, Situphen commented
Je vais répondre à tes différents points dans un ordre différent car c'est plus simple pour moi : 

> Y a un truc que j'ai peut-être mal saisi dans la discussion sur le forum : on supprime les IPs de tous les messages plus vieux d'un an ? J'avais compris qu'il fallait supprimer les IPs des commentaires postés par les membres qui ne se sont pas connectés depuis un an.

En fait on stocke des adresses IP à 4 endroits différents : 
- on stocke l'adresse IP de l'auteur de chaque message (messages du forum, messages privés et commentaires des contenus) car il y a une obligation légale de garder l'adresse IP des auteurs de contenus publics sur Internet
  - je ne suis pas sûr qu'on doive le stocker pour les messages privés
  - on le stocke bien trop longtemps
  - heureusement, ce n'est pas facilement accessible (il faut accès au serveur ou à l'interface admin)
- on stocke l'adresse IP utilisé par chaque membre lors de sa dernière visite à minima pour des besoins de modération et peut-être car la même obligation s'applique aussi là ?
  - on le stocke probablement trop longtemps (par rapport aux besoins de modérations)
  - trop de personnes y ont accès (tous les membres du Staff alors qu'il faudrait restreindre aux modérateurs)
- depuis l'ajout de la page de gestion des sessions, on stocke l'adresse IP associée à chaque session de l'utilisateur pour lui permettre de sécuriser son compte
  - on le stock seulement la durée de la session, c'est-à-dire [un mois selon les paramètres actuels](https://github.com/zestedesavoir/zds-site/blob/a92df8073aba18b1ae33f4e311eb99275003a1bb/zds/settings/prod.py#L60)
  - à part le membre, seuls les admins serveurs peuvent y avoir accès techniquement
- enfin, dans les logs nginx on garde les adresses IP de chaque requête, là aussi par obligation légale il me semble
  - on le stocke exactement la bonne durée, à condition que le paramétrage pour ne garder qu'un an de logs fonctionne correctement
  - seuls les admins serveurs peuvent y avoir accès techniquement

> C'est peut-être l'occasion d'ajouter une page dans la documentation qui explique tous les mécanismes qu'on a en place pour respecter le RGPD

Bonne idée en effet ! Ce serait aussi l'occasion de vérifier quelles sont nos obligations légales en 2024 pour s'assurer de les respecter, et ce sans faire de zèle.

> Ajouter un paramètre pour définir le délai à partir duquel anonymiser (par défaut on peut mettre 1 an bien-sûr ; ça demande de renommer la commande)

Étant donné que la durée de conservation est issue d'une obligation légale (pour ce point-ci en tous cas), j'ai du mal à voir l'intérêt de le mettre en paramètres de la commande.

> Dans le test, essaie aussi d'afficher une page qui contient un des commentaires dont tu viens d'effacer l'adresser IP (affichage en tant que membre qui a le droit de voir les adresses IPs des commentaires)

Il n'y a pas de vue qui permette de voir les adresses IP des commentaires à ma connaissance ? Donc je comprends pas vraiment ce que tu veux dire là.

2024-04-21 10:42 UTC, philippemilink commented
> > Ajouter un paramètre pour définir le délai à partir duquel anonymiser (par défaut on peut mettre 1 an bien-sûr ; ça demande de renommer la commande)
> 
> Étant donné que la durée de conservation est issue d'une obligation légale (pour ce point-ci en tous cas), j'ai du mal à voir l'intérêt de le mettre en paramètres de la commande.

On pourrait imaginer que la loi évolue, par exemple. Ce qui m'embête surtout c'est le `one_year` dans le nom de la commande : je trouve que ça rallonge le nom de la commande et que ça donne trop de détails inutilement. Mais bon, je ne vais pas non plus faire un blocage sur ce point :)


> > Dans le test, essaie aussi d'afficher une page qui contient un des commentaires dont tu viens d'effacer l'adresser IP (affichage en tant que membre qui a le droit de voir les adresses IPs des commentaires)
> 
> Il n'y a pas de vue qui permette de voir les adresses IP des commentaires à ma connaissance ? Donc je comprends pas vraiment ce que tu veux dire là.

Ah oui, oups (j'ai du confondre avec un autre forum...). Oublie cette remarque. (mais elle est valide quand on supprimera les IPs de connexion des membres pas connectés depuis un an, il faudra tester si l'affichage de la page de profil en tant que staff fonctionne bien).

2024-09-26 19:09 UTC, philippemilink requested changes
Un petit bout du code à changer, un rebase et je pense qu'on sera bon.

2024-09-26 19:09 UTC, philippemilink commented on zds/utils/management/commands/remove_one_year_old_ip_addresses.py
> +        Comment.objects.filter(pubdate__lte=one_year_ago).update(ip_address="")
```suggestion
        Comment.objects.filter(pubdate__lte=one_year_ago,~Q(ip_address="")).update(ip_address="")
```
Parce que sinon ça va tout le temps faire une requête `UPDATE` énorme, alors qu'il n'y a pas besoin de traiter à nouveau les commentaires plus vieux d'un an qui ont déjà été traité la veille.

2024-09-26 19:29 UTC, Situphen commented
J'ai rebasé et modifié le code comme demandé (en utilisant `exclude` plutôt que l'objet `Q` mais j'ai vérifié et ça génère la même requête SQL) !

2024-10-02 20:34 UTC, philippemilink approved these changes
**QA OK** :heavy_check_mark: 

J'ai testé sur la bêta et c'est bon.

2024-10-02 20:34 UTC, merged

2025-10-10 05:58 UTC, Situphen commented
@philippemilink Je viens de retomber sur cette PR, il faudrait paramétrer un cronjob sur la prod si ce n'est pas déjà le cas ;)

2025-10-10 11:27 UTC, philippemilink commented
C'est en place sur la prod, mais c'est un timer Systemd pour que ce soit plus facile à déployer avec Ansible : https://github.com/zestedesavoir/ansible-zestedesavoir/blob/11e2836ce56fc1c104b76f52ee50a2050813fc89/roles/app/templates/zds-remove-old-ips.timer.j2