Déplace la modification de la miniature dans un formulaire dédié
zestedesavoir/zds-site pull request #6613
Opened 2024-05-08 20:17 UTC by Arnaud-D

Je mets le bout de formulaire qui permet de choisir une miniature/logo pour une publication dans un formulaire dédié. Ce formulaire est accessible en cliquant sur la miniature dans l'en-tête de la publication.

Fix #5797

### À faire

Ajouter des tests pour le nouveau code

### Contrôle qualité

Tester la création de contenus

Tester l'édition de contenus (le formulaire fourre-tout "éditer")

Tester les nouvelles vues de modification de la miniature

Regarder ce qu'il se passe sur les pages de chapitres et de parties.

2024-05-12 20:58 UTC, Arnaud-D commented
Je me rends compte que j'ai oublié d'ajouter un enregistrement au journal d'événement pour cette action. Faut que je m'occupe de ça avant que ça soit prêt pour la revue

2024-07-20 13:26 UTC, Arnaud-D commented
Voilà, j'ai pu rajouter ce que je voulais.

2024-09-08 18:51 UTC, philippemilink requested changes
Pas vraiment testé, et puis il faudra rebase quand #6550 sera mergée.

2024-09-08 18:51 UTC, philippemilink commented on zds/tutorialv2/forms.py
> -            Field("description"),
Pourquoi ce champ est enlevé ?

Ah, je vois qu'il y a un lien "Ajoutez un sous-titre" dans la page de brouillon, donc je suppose que tu as oublié de l'enlever dans une précédente PR...

2024-09-08 18:51 UTC, philippemilink commented on assets/scss/layout/_content.scss
> +
Ce qui m'embête avec ce CSS, c'est que tant qu'on n'a pas passé la souris sur l'image, on ne sait pas comment modifier la miniature du contenu.

Je viens de passer 1h pour trouver le CSS qui affiche toujours le petit crayon par-dessus la miniature et qui fait varier la taille du fond transparent du crayon quand on passe la souris dessus pour recouvrir toute la miniature : 
```suggestion
                >.edit-thumbnail {
                    display: block;
                    width: $length-32;
                    height: $length-32;
                    margin-top: calc($length-64/2 - $length-32/2);
                    margin-left: calc($length-64/2 - $length-32/2);

                    border-radius: $radius-round;
                    background-color: rgba($grey-200, 0.7);

                    &.with-thumbnail {
                        position: relative;
                        top: -$length-64;
                    }

                    &.with-placeholder{
                        position: relative;
                        top: 0;
                    }

                    &::after {
                        content: " ";

                        display: block;
                        width: $length-16;
                        height: $length-16;

                        position: relative;
                        top: calc($length-32/2 - $length-16/2);
                        left: calc($length-32/2 - $length-16/2);

                        @include sprite;
                        @include sprite-position($edit-blue);
                        background-repeat: no-repeat;

                    }

                    transition: border-radius .005s ease-in-out;

                    &:hover {
                        border-radius: 0;
                        width: 100%;
                        height: 100%;
                        margin: 0;

                        &::after {
                            top: calc($length-64/2 - $length-16/2);
                            left: calc($length-64/2 - $length-16/2);
                        }
                    }
                }
```

2024-09-09 17:10 UTC, Arnaud-D commented on zds/tutorialv2/forms.py
> -            Field("description"),
Oui, c'est un oubli d'une précédente PR. 

En fait, il y a deux formulaires : celui pour un nouveau contenu et celui auquel on accède avec le bouton "Éditer" (qui en hérite en pratique). J'avais oublié d'enlever le champ du formulaire de création de contenu.

2024-09-10 20:58 UTC, Arnaud-D commented on assets/scss/layout/_content.scss
> +
J'ai testé, ça me va.

2024-09-14 17:13 UTC, philippemilink requested changes
Le commentaire à propos des images transparentes, mais sinon QA OK.

2024-09-14 17:13 UTC, philippemilink commented on templates/tutorialv2/includes/headline/title.part.html
> +        <div class="content-thumbnail-group {{ content.type|lower }}-illu">
Si on upload une image avec un fond transparent, on voit l'image par défaut du contenu qui reste affichée derrière l'image transparente.

J'ai corrigé le problème avec ce changement :

```suggestion
        <div class="content-thumbnail-group {% if not content.image %}{{ content.type|lower }}-illu{% endif %}">
```

Je ne sais pas si le problème provient de cette PR ou pas, donc je te laisse choisir si tu corriges le problème dans cette PR ou dans une autre.

2024-09-15 06:02 UTC, Arnaud-D commented on templates/tutorialv2/includes/headline/title.part.html
> +        <div class="content-thumbnail-group {{ content.type|lower }}-illu">
Je vais corriger dans celle-là.

(Après, avoir des images avec un fond transparent pour cet usage est plutôt une mauvaise idée, notamment pour des histoires de thème sombre. Quand j'écris pour Zeste de Savoir, je m'arrange pour que le fond soit uni avec la page, mais pas transparent).

2024-09-15 18:03 UTC, Arnaud-D commented on templates/tutorialv2/includes/headline/title.part.html
> +        <div class="content-thumbnail-group {{ content.type|lower }}-illu">
C'est fait.

2024-09-15 18:57 UTC, philippemilink approved these changes

2024-09-15 18:58 UTC, merged