Ajout de la raison du bannissement à la connexion
zestedesavoir/zds-site pull request #6630
Opened 2024-08-05 14:46 UTC by leroivi

### Contrôle qualité

 - Bannir un membre
 - Fournir une raison au bannissement (à noter quelque part pour vérification)
 - Tenter de se connecter à la place de l'utilisateur banni
 - Vérifier que le bandeau présente bien la raison du bannissement fourni précédemment
 - Enlever le bannissement de l'utilisateur
 - Le bannir à nouveau avec une raison différente
 - Tenter de se connecter à nouveau à sa place
 - Vérifier que la raison présentée est la seconde

2024-08-11 14:15 UTC, Arnaud-D requested changes
Ça fonctionne, mais il y a quelques améliorations qu'on peut faire sur le code. Ce sont des petites choses, mais c'est important pour nous, parce qu'on a peu de ressources et ça allège la maintenance sur le long terme.

Tu as des tests qui ne passent pas non plus. Pour tester en local et voir d'où ça vient plus précisément qu'avec les logs de la CI : https://docs.zestedesavoir.com/guides/backend-tests.html

2024-08-11 14:15 UTC, Arnaud-D commented on zds/member/forms.py
> +        ),
```suggestion
        "banned": _(
            "Vous n’êtes pas autorisé à vous connecter sur le site. Vous avez été banni par un modérateur pour la raison suivante : « {} »."
        ),
```

J'ajoute un espace réservé pour insérer la raison, c'est plus propre (notamment si on rechange la phrase un jour).

Faire deux phrases est plus lisible et un peu de ponctuation/typographie (espaces insécables notamment) pour faire un peu propre à pas cher.

2024-08-11 14:15 UTC, Arnaud-D commented on zds/member/forms.py
> +                self.error_messages["banned"] + ban_rationale,
```suggestion
                self.error_messages["banned"].format(ban_rationale),
```

2024-08-11 14:15 UTC, Arnaud-D commented on zds/member/forms.py
>          elif not user.profile.is_banned():
Cette ligne est un contresens, mais ce n'est pas de ta faute, c'est quand j'ai crée is_banned que j'ai introduit la bizarrerie : la fonction renvoie la négation de ce qu'elle est censé renvoyer...

Si tu le souhaites, tu peux corriger la fonction is_banned dans models.py>Profile pour être :

```py
    def is_banned(self):
        """Return True if the user is permanently or temporarily banned."""
        if self.end_ban_read:
            return not self.can_read and (self.end_ban_read >= datetime.now())
        return not self.can_read
```

2024-08-11 14:15 UTC, Arnaud-D commented on zds/member/forms.py
> +            ban_rationale = Ban.objects.filter(user=user).order_by("-pubdate")[0].note
Plus adéquat :
```suggestion
            ban_rationale = Ban.objects.filter(user=user).order_by("-pubdate").first().note
```

L'ORM de Django est mieux utilisé comme ça, parce qu'il peut optimiser la requête.

2024-08-13 20:57 UTC, Arnaud-D commented on zds/member/forms.py
>          elif not user.profile.is_banned():
Il faudra faire gaffe à adapter tous les usages de `is_banned`. Il y en avait qu'un seul à ma connaissance, mais on vient d'en rajouter un dans une autre PR.

2024-08-15 12:11 UTC, leroivi commented
J'ai regardé un peu et j'ai bloqué sur la génération des fixtures du test pour generer le ban. Malheureusement, je ne serais pas disponible jusqu'au 27 août, le sujet va donc être en stand by d'ici là. J'y reviendrai si personne ne l'a achevé entre-temps.

2024-08-15 14:19 UTC, Arnaud-D commented
Le test devrait ressembler à quelque chose du genre : 

```py
    def test_banned_user(self):
        """
        Error case: correct username, activated user, correct password, but banned user.
        Expected: cannot log in, error associated with the ban.
        """

        # Simulate a banned user
        self.profile.can_read = False
        self.profile.save()
        note = "Raison du ban"
        Ban.object.create(user=self.profile.user, note=note, [...])  # à compléter, je ne sais pas quels champs sont obligatoires.

        result = self.client.post(
            self.login_url,
            {
                "username": self.correct_username,
                "password": self.correct_password,
                "remember": "remember",
            },
            follow=False,
        )
        self.assertContains(result, escape(LoginForm.error_messages["banned"].format(note))
```

Je n'ai pas testé, c'est pour montrer l'idée. Le code qu'on teste va chercher la raison du ban dans un objet Ban, sauf que le test actuel n'en crée pas.

On peut attendre quelques jours ton retour, on n'est pas pressés ici. ^^

2024-09-07 06:50 UTC, Arnaud-D approved these changes

2024-09-07 06:50 UTC, Arnaud-D commented
QA OK :heavy_check_mark:

2024-09-07 06:50 UTC, merged