Formulaires intro et conclusion
zestedesavoir/zds-site pull request #6642
Opened 2024-09-15 19:31 UTC by Arnaud-D

Fix #5795.

* Simplifie le formulaire de création de publication
* Crée un formulaire dédié à l'introduction d'une publication
* Crée un formulaire dédié à la conclusion d'une publication
* Supprime la fonctionnalité "Une nouvelle version a été postée avant que vous ne validiez." qui est buguée.

Le bug en question est qu'on perd totalement le contenu qu'on était en train de rédiger. C'est pire que tout, parce que si on écrase la version du serveur, on peut encore la récupérer dans l'historique, alors que la version en cours d'édition dans le navigateur, ce n'est pas le cas. J'ai crée un ticket pour suivre ce sujet : #.

### TODO

* ajouter des tests unitaires sur l'aperçu de l'introduction et l'aperçu de la conclusion 
* réecrire les tests pour la création de contenu
* modifier ceux qui faisaient appel à la vue "content:edit"

### Contrôle qualité

* Créer un contenu
* Modifier l'intro, tester l'aperçu et l'enregistrement
* Modifier la conclusion, tester l'aperçu et l'enregistrement

2024-09-22 17:19 UTC, philippemilink requested changes
Ça fonctionne bien, mais j'ai deux suggestions :

1. ajouter une ligne séparatrice (cf ma suggestion de modification)
2. dans les formulaires pour modifier / ajouter une introduction ou une conclusion, avoir un champ pour préciser le message de suivi (quite à ce qu'il soit pré-rempli par `Modification de l('intro|a conclusion)`). Ça permet de préciser quelle a été la modif :)

2024-09-22 17:19 UTC, philippemilink commented on templates/tutorialv2/includes/content/content.part.html
>      </div>
```suggestion
    </div>
    
    <hr>
```

Il y a une séparation entre le bandeau pour ajouter une section ou partie et le bandeau pour ajouter une conclusion. Je trouve ça mieux d'en mettre une aussi pour séparer le bandeau pour ajouter une introduction. Uniquement lorsque le bandeau est affiché, car sinon ça fera bizarre entre l'introduction et le sommaire.

2024-09-23 20:52 UTC, Arnaud-D commented on templates/tutorialv2/includes/content/content.part.html
>      </div>
C'est fait.

2024-09-23 20:53 UTC, Arnaud-D commented
J'ai ajouté tes suggestions. 

Je ne teste pas le message de commit dans les tests unitaires. C'est pas que c'est inutile, mais je n'ai pas vu d'exemple ailleurs, et développer un bout de code propre pour ça est une tâche à part entière. En particulier pour taper directement sur le dépôt, et ne pas utiliser la vue qui liste les commits (ce qui créerait un couplage entre vues que je veux éviter).

2024-09-24 19:43 UTC, philippemilink approved these changes
**QA OK** :heavy_check_mark:

2024-09-24 19:56 UTC, merged