Amélioration de l'autocomplétion
zestedesavoir/zds-site pull request #6645
Opened 2024-09-18 22:10 UTC by Situphen

Fixes #6460 

**QA :**
- `source zdsenv/bin/activate && make update && make zmd-start && make run-back`
- Vérifier le bon fonctionnement de l'autocomplétion dans les MP (ajout d'un destinataire)
- Vérifier le bon fonctionnement de l'autocomplétion dans les contenus (ajout d'un auteur ou d'un contributeur)

Idéalement, il faudrait mettre cette PR sur la bêta pour tester avec des vrais noms d'utilisateurs, mais en local on voit clairement une amélioration par rapport à avant je trouve.

2024-09-19 11:44 UTC, philippemilink commented
Est-ce que tu pourrais ajouter / compléter des tests, stp ? (tu peux me dire que tu n'as pas envie de le faire, je pourrais le faire dans ce cas)

2024-09-21 20:24 UTC, Situphen commented
J'ai ajouté un petit test pour vérifier que les résultats retournés sont dans le bon ordre, qui est le suivant : 
1. "Est égal"
2. "Est égal" insensible à la casse
3. "Commence par"
4. "Commence par" insensible à la casse
5. "Contient"
6. "Contient" insensible à la casse

Le test vérifie aussi que : 
- les pseudos qui contiennent les lettres du mot ("a", "n", "d" et "r") mais pas le mot recherché ("andr") ne sont pas retournés ;
- les pseudos qui contiennent des lettres accentuées peuvent être retournés.

2024-09-22 16:40 UTC, philippemilink requested changes
Les commentaires à ajouter et je fusionne.

J'ai testé en local, ça fonctionne bien ; et j'ai déployé le patch sur la bêta (par-dessus la PR Typesense) et en effet, ça fonctionne mieux.

2024-09-22 16:40 UTC, philippemilink commented on assets/js/autocompletion.js
> +      const alreadyChosenWords = self.extractWords(this.$input.val()).slice(0, -1)
```suggestion
      // Exclude already selected items but the last one (it's the prefix of the item we are looking for):
      const alreadyChosenWords = self.extractWords(this.$input.val()).slice(0, -1)
```

2024-09-22 16:40 UTC, philippemilink commented on zds/member/api/tests.py
> +        verifies that the list of usernames returned is in the right order.
```suggestion
        verifies that the list of usernames returned is in the right order, which is:
        1. "is equal" case sensitive
        2. "is equal" ignoring the case
        3. "starts with" case sensitive
        4. "starts with" ignoring the case
        5. "contains" case sensitive
        6. "contains" ignoring the case
        
        The test also checks that:
        - pseudos containing letters of the searched word (here: 'a', 'n', 'd' and 'r'), but NOT the searched word ("andr") are not returned
        - pseudos containing non-ascii letters (eg with accents) can be returned as well
```

2024-09-22 17:53 UTC, philippemilink approved these changes

2024-09-22 17:59 UTC, merged