Rend générique en fonction du type la vue "RemoveAuthorFromContent"
zestedesavoir/zds-site pull request #6668
Opened 2024-10-19 06:49 UTC by Arnaud-D

Dans le cadre de la nouvelle organisation des contenus

* supprime la distinction de type de publication
* préfère le terme "publication" à "contenu"
* renomme les vues pour adopter la convention de Django
* refactorise pour améliorer la lisibilité
* interdit les méthodes HTTP autres que POST

### Contrôle qualité

Ajouter et supprimer des auteurs. Regarder les MP correspondants.

Supprimer aussi des contenus, vu que j'ai touché une bricole à ce niveau-là.

2025-06-26 20:50 UTC, Situphen requested changes
J'ai testé en local et ça a l'air de bien fonctionner ! Il y a seulement un petit changement puis tu peux fusionner.

À noter que le code gère le retrait de plusieurs auteurs en une requête mais, depuis qu'on a modifié dans l'interface la façon de retirer un auteur, ce n'est plus possible. Il y aurait donc moyen de simplifier le code à ce niveau-là aussi ! (Dans une autre PR, cela dit.)

2025-06-26 20:50 UTC, Situphen commented on zds/tutorialv2/models/database.py
> +                gallery.delete()
Pour ce soit clair à la lecture du code qu'on n'est pas en train de supprimer la galerie
```suggestion
            usergallery = UserGallery.objects.filter(user__pk=user.pk, gallery__pk=self.gallery.pk).first()
            if usergallery:
                usergallery.delete()
```

2025-06-28 15:33 UTC, Arnaud-D commented
J'ai fait la modif.

2025-06-29 19:02 UTC, Situphen approved these changes

2025-06-29 19:05 UTC, merged