Rend générique en fonction du type la vue "WarnTypo"
zestedesavoir/zds-site pull request #6669
Opened 2024-10-19 07:17 UTC by Arnaud-D

Dans le cadre de la nouvelle organisation des contenus

* supprime la distinction de type de publication
* préfère le terme "publication" à "contenu"
* renomme les vues pour adopter la convention de Django
* déplace le formulaire à côté de la vue

### Contrôle qualité

Tester le formulaire de signalement de faute sur les différents types de contenu, regarder les MP correspondants.

2025-01-22 15:02 UTC, firm1 commented
# Rapport de QA

**QA OK** 👍

2025-01-25 22:20 UTC, philippemilink requested changes

2025-01-25 22:20 UTC, philippemilink commented on zds/tutorialv2/views/misc.py
> +            pm_title = _("J'ai trouvé une faute dans « {} ».").format(form.content.title)
`pm_title` est défini dans https://github.com/zestedesavoir/zds-site/pull/6669/files#diff-4b06fa578d536b8bff461bfdd2196ac3afa8179198ec0fe96319d859d9b947d3R103-R106, donc l'une des deux définitions est redondante.

2025-01-25 22:20 UTC, philippemilink commented on zds/tutorialv2/views/misc.py
> +        else:  # Send correction
```suggestion
        else:  # Send PM
```

2025-01-25 22:20 UTC, philippemilink commented on zds/tutorialv2/views/misc.py
> +
```suggestion
```

2025-01-25 22:20 UTC, philippemilink commented on zds/tutorialv2/views/misc.py
> +            version = content.sha_public
On peut sans doute factoriser cette portion du code avec la définition plus haut de `self.previous_page_url` (il y a le même `if public`).

2025-01-25 22:20 UTC, philippemilink commented on zds/tutorialv2/views/misc.py
> +        for index, user in enumerate(content.authors.all()):
Il faudrait récupérer uniquement les membres contactables (cf https://github.com/zestedesavoir/zds-site/pull/6669/files#diff-4b06fa578d536b8bff461bfdd2196ac3afa8179198ec0fe96319d859d9b947d3R185). Ça me fait donc penser qu'on pourrait ajouter une méthode qui récupère les auteurs contactables dans la classe `PublishableContent` ?

Dans tous les cas, je pense qu'il est possible de factoriser ce code avec ce qu'il y a dans la vue.

2025-01-25 22:20 UTC, philippemilink commented on zds/tutorialv2/views/display/content.py
> +from zds.tutorialv2.views.misc import WarnTypoForm
En regardant dans ce fichier pourquoi on avait besoin de cet import, je me rends compte que cette ligne : https://github.com/zestedesavoir/zds-site/blob/4d9a460bd4eb5bef1694dbf2c14bd535b5ddc3f5/zds/tutorialv2/views/display/content.py#L91 est dupliquée dix lignes plus loin sans raison apparente : https://github.com/zestedesavoir/zds-site/blob/4d9a460bd4eb5bef1694dbf2c14bd535b5ddc3f5/zds/tutorialv2/views/display/content.py#L104

On peut sans doute profiter de cette PR pour corriger ça.

2025-02-02 08:41 UTC, Arnaud-D commented on zds/tutorialv2/views/misc.py
> +        else:  # Send correction
J'ai refactorisé différemment et ça rend ce commentaire superflu.

2025-02-02 08:41 UTC, Arnaud-D commented on zds/tutorialv2/views/misc.py
> +            pm_title = _("J'ai trouvé une faute dans « {} ».").format(form.content.title)
Les deux ne sont pas tout à fait pareil et je n'ai pas le courage de d'harmoniser sans risquer de casser quelque chose.

2025-02-02 08:41 UTC, Arnaud-D commented on zds/tutorialv2/views/misc.py
> +
Fait.

2025-02-02 08:41 UTC, Arnaud-D commented on zds/tutorialv2/views/misc.py
> +            version = content.sha_public
Fait.

2025-02-02 08:43 UTC, Arnaud-D commented on zds/tutorialv2/views/misc.py
> +        for index, user in enumerate(content.authors.all()):
J'ai préféré prendre la notion de "reachable" présente dans les MP. Il y a aussi des histoires de "contactable" ailleurs dans le code, mais c'est un peu le chaos. Harmoniser les deux notions est un ticket à part entière (#5696).

2025-02-02 08:44 UTC, Arnaud-D commented on zds/tutorialv2/views/display/content.py
> +from zds.tutorialv2.views.misc import WarnTypoForm
J'ai corrigé ça.

2025-09-28 12:33 UTC, philippemilink reviewed
**QA OK** :heavy_check_mark:

2025-09-28 12:33 UTC, philippemilink approved these changes

2025-09-28 12:34 UTC, merged