Ensemble d'améliorations sur la page listant les alertes
zestedesavoir/zds-site pull request #6671
Opened 2024-10-20 14:08 UTC by philippemilink

Avant tout, cette PR corrige un bug menant à une erreur 500, rapporté par Sentry : un billet peut être dépublié puis supprimé par son auteurice, mais si ce billet avait des commentaires avec des alertes, ces alertes n'étaient pas supprimées, ce qui levait une exception lorsqu'on allait sur la page des alertes, car pour générer le lien du commentaire signalé, on avait besoin du lien du billet... supprimé. On supprime maintenant les alertes lorsque l'élément qu'elles concernent est supprimé (`on_delete=CASCADE`).

Ensuite, plusieurs améliorations d'ergonomie et de cohérence : 
- amélioration de la gestion des alertes dans la zone d'admin
- on précise sur la page des alertes sur quel type de contenu portent les commentaires signalés, et si le contenu est dépublié
- si l'alerte concerne un commentaire sur un contenu dépublié, ne pas afficher de lien vers le commentaire (le lien affiché jusqu'alors était buggué)
- en cherchant la cause du bug rapporté par Sentry, je me suis rendu compte que dans le base de données de production, on a encore différents formats de scope pour les alertes, j'ai ajouté une migration pour uniformiser tout ça.

### Contrôle qualité

- Refaire ce que fait le test que j'ai ajouté
- Jouer avec les alertes : 
  + signaler tout ce qu'il est possible de signaler
  + résoudre des alertes (ou pas)
  + supprimer les éléments signalés et voir ce qu'il se passe pour les alertes

2024-10-22 18:44 UTC, Arnaud-D requested changes
J'ai pas fini de regarder le reste encore, mais j'ai déjà vu ces petites coquilles.

2024-10-22 18:44 UTC, Arnaud-D commented on templates/pages/alerts.html
> +                                {# This an alert about a comment on something (any kind of content or forum post) #}
This **is** an alert

2024-10-22 18:44 UTC, Arnaud-D commented on templates/pages/alerts.html
> +                                {# This an alert about a comment on something (any kind of content or forum post) #}
This **is** an alert

2024-10-22 18:59 UTC, Arnaud-D commented on zds/utils/migrations/0029_normalize_alert_scopes.py
> +"""
Tu veux laisser en français ici ?

2024-10-22 19:02 UTC, Arnaud-D requested changes
À part mes commentaires, ça marche !

2024-10-22 21:11 UTC, philippemilink commented
Tout est corrigé !

2024-10-23 06:08 UTC, Arnaud-D approved these changes

2024-10-23 06:09 UTC, merged