Ajoute une page « Accessibilité »
zestedesavoir/zds-site pull request #6673
Opened 2024-10-21 02:09 UTC by jpbelval

Ajoute une page de déclaration d'accessibilité pour ZdS avec un lien en pied de page.

### Contrôle qualité

- Voir pied de page -> Voir lien au nom de "Accessiblité : non conforme" .
- Valider que la page contient les informations décrites dans l'issue #6657

2024-10-21 07:59 UTC, AmauryCarrade requested changes
Un petit détail suite à réflexion (divergeant du ticket initial) et une question que je me pose, mais sinon, sounds good

2024-10-21 07:59 UTC, AmauryCarrade commented on templates/pages/accessibilite.html
> +    </ul>
```suggestion
```

Après discussion et réflexion avec des personnes du milieu, il n'est pas nécessaire de garder cette partie — elle est destinée aux voies de recours si on est obligés de faire quelque chose mais qu'on ne fait rien, or, nous n’avons aucune obligation (cette page n’est qu’une déclaration d’intention). Donc même si quelqu’un voulait contacter le Défenseur des Droits, iel ne pourrait rien faire.

2024-10-21 07:59 UTC, AmauryCarrade commented on templates/pages/accessibilite.html
> +        <li>Contacter l’équipe de développement de Zeste de Savoir <a href="https://github.com/zestedesavoir/zds-site/issues/new">sur GitHub</a>.</li>
Ajouter `technique+accessibilite@zestedesavoir.com` pour celleux n’ayant pas de compte GitHub ?

2024-10-21 07:59 UTC, AmauryCarrade commented on templates/footer.html
> +            <li><a href="{% url "pages-accessibilite" %}">{% trans "Accessiblité : non conforme" %}</a></li>
Vu qu’on a aucune obligation légale, si on veut éviter le côté péjoratif alors même qu'on a des bons retours de personnes concernées, on a le droit de juste mettre “Accessibilité” (sans le “non-conforme”), si on le désire. Je n’ai pas d’opinion tranchée.

2024-10-21 08:14 UTC, AmauryCarrade commented on templates/pages/accessibilite.html
> +        <li>Contacter l’équipe de développement de Zeste de Savoir <a href="https://github.com/zestedesavoir/zds-site/issues/new">sur GitHub</a>.</li>
```suggestion
        <li>Contacter le Conseil d’Administration de l’association Zeste de Savoir, à l’adresse <a href="mailto:association+accessibilite@zestedesavoir.com">association+accessibilite@zestedesavoir.com</a> ;</li>
        <li>Contacter l’équipe de développement de Zeste de Savoir <a href="https://github.com/zestedesavoir/zds-site/issues/new">sur GitHub</a> ou par courriel à l’adresse <a href="mailto:technique+accessibilite@zestedesavoir.com">technique+accessibilite@zestedesavoir.com</a>.</li>
```

Une proposition, pour aller plus vite (mais ça vaut ce que ça vaut)

2024-10-21 17:28 UTC, Situphen commented on templates/footer.html
> +            <li><a href="{% url "pages-accessibilite" %}">{% trans "Accessiblité : non conforme" %}</a></li>
Je suis aussi pour simplement mettre "Accessibilité" sans le "non-conforme"

2024-10-21 17:31 UTC, Situphen commented on templates/pages/accessibilite.html
> +        <li>Contacter l’équipe de développement de Zeste de Savoir <a href="https://github.com/zestedesavoir/zds-site/issues/new">sur GitHub</a>.</li>
J'ai du mal à voir l'intérêt de mettre un contact par courriel à la fois vers l'équipe technique et le conseil d'administration de l'association. De mon point de vue, ça concerne principalement l'équipe technique donc je propose une formulation du type "Contacter l'équipe technique : - par courriel - sur Github"

2024-10-21 18:12 UTC, philippemilink commented on templates/footer.html
> +            <li><a href="{% url "pages-accessibilite" %}">{% trans "Accessiblité : non conforme" %}</a></li>
Je suis d'accord avec vous, pas la peine d'enfoncer le clou à indiquer sur la page d'accueil qu'on n'est pas suffisamment accessible.

2024-10-21 18:18 UTC, philippemilink commented on templates/pages/accessibilite.html
Ce serait bien d'utiliser les valeurs définies dans les paramètres, par exemple au lieu de `Zeste de Savoir`, utiliser `{{ app.site.literal_name }}` (cf [les valeurs définies dans les paramètres](https://github.com/zestedesavoir/zds-site/blob/4fb6d1471119ce0891a3f18b16dac12091e3ffb7/zds/settings/abstract_base/zds.py#L60)). Les autres informations à remplacer que je vois sont le nom de domaine et les adresses mails de contact.

Pour les informations de contact, je me demande si ce n'est pas plus simple de mettre un lien vers la page de contact ? D'un point de vue accessibilité je ne sais pas ce que ça vaut, mais ça évite de dupliquer l'information (et donc dupliquer les endroits où on oubliera de mettre à jour lors d'un changement).

Aussi, dans l'idéal, ce serait bien d'utiliser les blocs de traductions, mais puisque ça parle surtout de législation française, je ne sais pas si ça a vraiment un intérêt...

2024-10-21 23:03 UTC, AmauryCarrade commented on templates/pages/accessibilite.html
> +        <li>Contacter l’équipe de développement de Zeste de Savoir <a href="https://github.com/zestedesavoir/zds-site/issues/new">sur GitHub</a>.</li>
J'y vois une différence : l'équipe technique pour les questions techniques, et le CA pour les questions d'intention ou de responsabilité. Mais peut-être vais-je chercher trop loin ?

Il est d'usage de laisser un contact vers læ responsable ou l'équipe responsable. Il est en réalité plus rare de donner un contact vers l'équipe technique (mais c'est lié à l'organisation usuelle en entreprise où cette dernière n'est souvent pas autonome dans ses décisions…).

2024-10-22 02:43 UTC, jpbelval commented on templates/pages/accessibilite.html
J'ai utilisé les valeurs dans les paramètres pour Zeste de Savoir, le DNS, le Github et les adresses mails. J'ai ajouté les blocs de traductions. Resolved.

2024-10-22 02:44 UTC, jpbelval commented on templates/pages/accessibilite.html
> +        <li>Contacter l’équipe de développement de Zeste de Savoir <a href="https://github.com/zestedesavoir/zds-site/issues/new">sur GitHub</a>.</li>
Ajouté!

2024-10-22 02:44 UTC, jpbelval commented on templates/footer.html
> +            <li><a href="{% url "pages-accessibilite" %}">{% trans "Accessiblité : non conforme" %}</a></li>
Retiré!

2024-10-22 02:44 UTC, jpbelval commented on templates/pages/accessibilite.html
> +        <li>Contacter l’équipe de développement de Zeste de Savoir <a href="https://github.com/zestedesavoir/zds-site/issues/new">sur GitHub</a>.</li>
Ajouté

2024-10-22 02:44 UTC, jpbelval commented on templates/pages/accessibilite.html
> +    </ul>
Retiré

2024-10-22 02:46 UTC, jpbelval commented
Je crois avoir ajouté les suggestions, n'hésitez pas si il manque quoi que ce soit.

2024-10-22 13:37 UTC, AmauryCarrade commented on zds/settings/abstract_base/zds.py
> +        "email_tech_access": "technique+accessibilite@zestedesavoir.com",
Si j’étais tatillon, je dirais que l’abbréviation usuelle pour _accessibilité_ est `a11y`, et donc qu’il serait plus pertinent de nommer ces variables `email_{asso,tech}_a11y`

2024-10-22 13:38 UTC, AmauryCarrade submitted a review, later dismissed
**Je n’ai pas fait de QA sur un navigateur**, mais en lisant le code, tout me semble bon !

2024-10-22 18:30 UTC, Arnaud-D requested changes
Faudrait au moins corriger la faute d'orthographe dans la première phrase de la page.

Le reste, je n'en mourrais pas. :)

2024-10-22 18:30 UTC, Arnaud-D commented on templates/pages/accessibilite.html
> +    <p>L’association {{asso_name}} s’engage à rendre son site internet accessibles conformément à
accessibles => accessible

2024-10-22 18:30 UTC, Arnaud-D commented on templates/pages/accessibilite.html
> +        {% blocktrans %}Cependant, un audit de conformité est prévu, bien qu’aucune date ne soit connue aujourd’hui. {% endblocktrans %}
> Cependant, un audit de conformité est prévu, bien qu’aucune date ne soit connue aujourd’hui. 

Je dirais plutôt "un audit de conformité est envisagé, sans que l'échéance n'ait été encore définie". Parce dans ma tête, si c'est prévu sans date, c'est "prévu" ou alors c'est prévu, mais on a oublié de demander la date à la personne qui sait. :D

2024-10-22 18:30 UTC, Arnaud-D commented on zds/settings/abstract_base/zds.py
> +        "email_tech_access": "technique+accessibilite@zestedesavoir.com",
Ou même "accessibility" en entier ?

2024-10-22 18:30 UTC, Arnaud-D commented on zds/pages/views.py
> +    return render(request, "pages/accessibilite.html")
Peut-être renommer ça "accessibility.html". Les noms dans le code sont en anglais.

2024-10-22 18:30 UTC, Arnaud-D commented on zds/pages/views.py
> +    """Display accessibility's page"""
Ça c'est de l'anglais bizarre, mieux vaudrait changer pour "Display the page about accessibility".

2024-10-23 09:10 UTC, AmauryCarrade commented on templates/pages/accessibilite.html
> +        {% blocktrans %}Cependant, un audit de conformité est prévu, bien qu’aucune date ne soit connue aujourd’hui. {% endblocktrans %}
C’était ma formulation, mais j’admets que la tienne est un peu meilleure.

2024-10-23 09:10 UTC, AmauryCarrade commented on templates/pages/accessibilite.html
> +    <p>L’association {{asso_name}} s’engage à rendre son site internet accessibles conformément à
Bien vu

2024-10-23 19:39 UTC, Situphen requested changes, later dismissed
Merci pour cette contribution ! J'ai juste quelques remarques supplémentaires, rien de bien méchant :)

2024-10-23 19:39 UTC, Situphen commented on templates/footer.html
> +            <li><a href="{% url "pages-accessibilite" %}">{% trans "Accessiblité" %}</a></li>
```suggestion
            <li><a href="{% url "pages-accessibilite" %}">{% trans "Accessibilité" %}</a></li>
```

2024-10-23 19:39 UTC, Situphen commented on zds/pages/views.py
> +def accessibilite(request):
Notre projet fonctionne un peu bizarrement : 
- le code doit être en anglais (y compris les commentaires) ;
- tous les éléments affichés aux utilisateurs doivent être en français (principalement dans le code HTML mais aussi les messages d'erreur dans le code Python et les chaînes de caractères dans le code JS)  ;
- les noms de commits peuvent être en français ou en anglais ;
- les discussions (tickets, PR, Discord) sont en français (sauf en cas de contributeur non francophone).

Donc pour une question de cohérence du code il faudrait faire ce changement : 
```suggestion
def accessibility(request):
```

2024-10-23 19:39 UTC, Situphen commented on zds/pages/urls.py
> +    path("accessibilite", accessibilite, name="pages-accessibilite"),
Toutes nos URL doivent se terminer par une barre oblique
```suggestion
    path("accessibilite/", accessibilite, name="pages-accessibilite"),
```

2024-10-24 08:29 UTC, AmauryCarrade commented
```
ImportError: cannot import name 'accessibilite' from 'zds.pages.views' (/home/runner/work/zds-site/zds-site/zds/pages/views.py)
```

Il semblerait que tu aies renommé la vue `accessibilite` en `accessibility` sans renommer ses usages 😛 rien de bien méchant à corriger a priori (désolé pour les nombreux allers-retours !)

2024-10-24 08:41 UTC, AmauryCarrade commented
Comme tu as autorisé les modifications par les mainteneurices, je me suis permis de corriger directement ce petit oubli tout simple (attention de mettre à jour ton dépôt local, @jpbelval)

2024-11-01 18:20 UTC, Arnaud-D approved these changes
QA OK :heavy_check_mark:

2024-11-01 18:44 UTC, merged