Utilise la version 27.1 de Typesense
zestedesavoir/zds-site pull request #6676
Opened 2024-10-27 16:57 UTC by philippemilink

C'est la version qu'on (va) utilise(r) en production.

### Contrôle qualité

La CI passe.

2024-10-27 17:05 UTC, Situphen approved these changes, later dismissed

2024-10-27 17:09 UTC, Situphen commented
Approuvé sur le principe mais malheureusement la CI ne passe pas :/

2025-05-08 19:38 UTC, philippemilink commented
J'ai mis à jour la PR pour passer à la version 28 de Typesense, en corrigeant la CI qui plantait, le détail est dans les commentaires du code.

Il y a un commit en plus, ce serait bien de ne pas squasher les commits au moment de la fusion de la PR.

2025-05-08 21:40 UTC, Situphen requested changes

2025-05-08 21:40 UTC, Situphen commented on zds/search/tests/tests_utils.py
> +        # self.assertEqual(str(f), "(forum_pk:!=[6,7])")
Oubli ?
```suggestion
```

2025-05-08 21:40 UTC, Situphen commented on zds/search/utils.py
> +        # Content can be not found in tests or, for instance, we move a
Je trouve difficile de comprendre "Content can be not found in tests" en première lecture. Peut-être ajouter des guillemets autour de "not found" ou utiliser un synonyme (unfound, missing...) ?

2025-05-08 21:40 UTC, Situphen commented on zds/search/utils.py
> +        # print("deleting", doc_type, self.engine.collections.retrieve(), doc_type in self.engine.collections.retrieve())
Oubli ?
```suggestion
```

2025-05-08 21:40 UTC, Situphen commented on zds/search/utils.py
> +        # self._add_filter(f"{field}:!= [" + ", ".join(map(str, values)) + "]")
Oubli ?
```suggestion
```

2025-05-09 09:44 UTC, philippemilink commented on zds/search/tests/tests_utils.py
> +        # self.assertEqual(str(f), "(forum_pk:!=[6,7])")
Non, je ne veux pas l'enlever, parce que ce sera la version à utiliser lorsque le bug de Typesense sera corrigé. J'ai mis à jour le commentaire (et déplacé la ligne) pour que ce soit plus clair.

2025-05-09 09:44 UTC, philippemilink commented on zds/search/utils.py
> +        # Content can be not found in tests or, for instance, we move a
Commentaire mis à jour.

2025-05-09 09:44 UTC, philippemilink commented on zds/search/utils.py
> +        # print("deleting", doc_type, self.engine.collections.retrieve(), doc_type in self.engine.collections.retrieve())
En effet, c'est corrigé.

2025-05-09 09:45 UTC, philippemilink commented on zds/search/utils.py
> +        # self._add_filter(f"{field}:!= [" + ", ".join(map(str, values)) + "]")
Même réponse que pour ta première remarque, j'ai aussi mis à jour le commentaire.

2025-06-26 17:46 UTC, Situphen submitted a review, later dismissed
C'est bon pour moi ! Je te laisse résoudre les conflits liés à la fusion de la PR de mise à jour des dépendances et fusionner ensuite.

2025-06-28 18:51 UTC, merged