Met à jour les poids de recherche
zestedesavoir/zds-site pull request #6685
Opened 2024-11-06 21:58 UTC by Arnaud-D

Fix #6680

* distingue principalement validé ou non
* distingue les multipages de manière unifiée pour les contenus validés (identique pour article ou tuto)
* garde la distinction choisi/non choisi pour les billets

### Contrôle qualité

La CI devrait faire l'essentiel.

Tester également ce qui déclenche l'indexation/réindexaction (publication de contenus ?) pour des articles/tuto/billets.

Je connais mal le module de recherche, il y a peut-être d'autres choses à regarder.

2024-11-07 10:41 UTC, philippemilink requested changes

2024-11-07 10:41 UTC, philippemilink commented on doc/source/back-end/search.rst
> +                "if_validated_and_multipage": 2.5, # s'il s'agit d'une publication validée sur plusieurs page (medium ou big-tuto)
```suggestion
                "if_validated_and_multipage": 2.5, # s'il s'agit d'une publication validée sur plusieurs pages (medium ou big-tuto)
```

2025-01-25 21:53 UTC, philippemilink requested changes
Les deux petites modifs et on est bon.

2025-01-25 21:53 UTC, philippemilink commented on doc/source/back-end/search.rst
> +                "if_validated_and_multipage": 2.5, # s'il s'agit d'une publication validée sur plusieurs page (medium ou big-tuto)
Heu non, ça n'est pas résolu, la typo est toujours là :)

Et en relisant, je me rends compte que je proposerais même : 
```suggestion
                "if_validated_and_multipage": 2.5, # s'il s'agit d'une publication validée sur plusieurs pages (medium ou big)
```
(sinon ça peut laisser penser que ça ne concerne toujours que les tutoriels)

2025-01-25 21:53 UTC, philippemilink commented on zds/tutorialv2/models/database.py
> +    def _get_search_weight(self, is_multipage: bool):
Je n'ai rien contre renommer cette fonction, mais dans ce cas, par cohérence, il faut également renommer les autres occurrences de cette fonction (`git grep -Irn _compute_s`).

2025-02-02 08:55 UTC, Arnaud-D commented on zds/tutorialv2/models/database.py
> +    def _get_search_weight(self, is_multipage: bool):
Fait.

2025-02-02 19:02 UTC, philippemilink approved these changes
**QA OK**  :heavy_check_mark:

2025-02-02 19:03 UTC, merged