Fixes #6690: Configure le bon chemin pour les extensions MathJax
zestedesavoir/zds-site pull request #6691
Opened 2024-12-05 20:46 UTC by Situphen

Depuis le passage de MathJax via CDN à MathJax en local (#6606), le script `MathJax.js` n'arrive pas à charger les fichiers complémentaires. Normalement, la détection de la racine devrait se faire automatiquement : le script est `/static/js/MathJax.js` donc les extensions se trouvent aussi dans `/static/js`. ([Citation de la documentation](https://docs.mathjax.org/en/v2.7-latest/advanced/startup.html) : "MathJax locates the <script> tag that loaded the MathJax.js file, and sets the MathJax.Hub.config.root value to reflect the location of the MathJax root directory.") Ça ne fonctionne pas en production car le nom du script est hashé : `MathJax.e380311aa78d.js` au lieu de `MathJax.js`. Cela se corrige facilement, il suffit de définir explicitement le chemin dans la configuration comme le fait cette PR.

**QA :** Mettre cette PR sur la bêta et vérifier que les requêtes vers les fichiers complémentaires n'échouent pas.

2024-12-06 20:16 UTC, philippemilink requested changes
Ça ne fonctionne pas, il essaie toujours de charger `https://beta.zestedesavoir.com/extensions/MathMenu.js?V=2.7.1`.

C'est déployé sur la bêta.

2024-12-07 23:15 UTC, Situphen commented
C'est étonnant, ça fonctionne bien sur la bêta pour moi pourtant !
![image](https://github.com/user-attachments/assets/e13d31df-f1cc-429b-97df-5f0ef1631a82)

2024-12-08 14:59 UTC, philippemilink commented
Je ne comprends pas : une fois sur deux sur cette page https://beta.zestedesavoir.com/tutoriels/244/comment-rediger-des-maths-sur-zeste-de-savoir/ les deux scripts de MatJax sont en 404... J'ai testé différents trucs, mais maintenant je suis juste paumé entre ce qui fonctionne et ce qui ne fonctionne pas...

2024-12-08 18:51 UTC, Situphen commented
Ça fonctionnait correctement avec Firefox chez moi mais pas avec Google Chrome. C'était probablement dû à une différence dans l'ordre de chargement des scripts JS (le script MathJax était avant la configuration MathJax dans le code HTML mais avec un `async`). Normalement avec mon dernier commit ça corrige bien le soucis. Je te laisse mettre à jour la bêta et vérifier ! ;)

2024-12-15 18:55 UTC, philippemilink requested changes
Ça a l'air bon maintenant.

Par contre puisque le fichier `mathjax_config.html` est utilisé uniquement pour être inclus dans `templates/mathjax.html`, autant mettre son contenu directement là où il est inclus, non ? Ça évite de lire un fichier supplémentaire sur le disque, ça soulage (très peu) le travail du moteur de templates.

2024-12-15 19:34 UTC, Situphen commented
C'est modifié !

2024-12-15 19:42 UTC, philippemilink approved these changes
**QA OK** :heavy_check_mark:

2024-12-15 19:42 UTC, merged