Met à jour la page d'accueil
zestedesavoir/zds-site pull request #6696
Opened 2024-12-30 10:37 UTC by Arnaud-D

Cette PR mets à jour la page d'accueil.

* fait correspondre la structure de la page d'accueil à la future organisation "validé/libre" pour les publications
* rend la page plus joueuse avec des "call to actions"
* regroupe les paramètres de configuration dans leur propre section
* refactorise les fonctions de récupération de données pour qu'elles ne dépendent plus directement de certaines configurations

C'est dans le cadre de la refonte du parcours de validation. J'aimerais découper ça en morceaux digestes pour le développement et la QA. Je pense que cette partie es autoporteuse.

### Contrôle qualité

Vérifier que le bloc "pépites de l'équipe" contient bien à la fois les tutos et les articles.

Vérifier que les liens fonctionnent

Vérifier les différentes tailles d'écran et que ça reste lisible

Vérifier que j'ai pas cassé la page de profil en refactorisant les paramètres de configuration

2025-01-22 14:22 UTC, firm1 commented
## Rapport de QA

J'ai pu tester pas mal de point même ceux qui ne sont pas mentionnés dans les conseil QA (par exemple publier plusieurs contenu en majeurs/mineures pour vérifier que l'ordre d'affichage est bien correct).


### Cohérence du ton

le ton/style des boutons "Montre-les moi !" et "Fais voir !" dénote un peu avec le bouton "Commencer à rédiger". Il faudrait harmoniser le ton des boutons.

### La place du bouton "Commencer a rédiger"

Vu la place du bouton "Commencer a rédiger" qui maintenant sous le titre "Dernières publications de la communauté", on pourrait supposer que dans le bloc, lorsqu'on lit "Il y a X publications sur Zeste de Savoir. Pourquoi pas la vôtre ?".

Le X devrait correspondre aux publications de la communauté "non validés par l'équipe". Mais actuellement le X fais référence à l'ensemble des contenus publiés (validés ou non) sur le site. Cela peut prêter à confusion.

Je dis cela, mais je n'ai pas réfléchi à la bonne façon de traiter le point. je vois au moins 2 options possibles : 
- Avoir 2 blocs "commercer à rédiger" (pour les pépites validées et les publication de la communauté) => ça peut alourdir la page
- Avoir un bloc "commercer à rédiger" mais qui se détache clairement de l'une des 2 catégories (validées et non validées)  => besoin de compétence d'UX/design pour que ce soit bien intégré

### Certains boutons n'ont pas besoin d'affichage sur mobile.

Aujourd'hui (en prod) le bouton "Commencer à rédiger" n'est pas affiché lorsqu'on est sur la version mobile du site.

Cette PR affiche ce bouton alors qu'il y a très peu de chance qu'il soit utile sur mobile.

2025-02-02 09:17 UTC, Arnaud-D commented
> Aujourd'hui (en prod) le bouton "Commencer à rédiger" n'est pas affiché lorsqu'on est sur la version mobile du site.
>
> Cette PR affiche ce bouton alors qu'il y a très peu de chance qu'il soit utile sur mobile.

Je comprends l'idée, mais je pense qu'il vaut mieux l'afficher. On ne sait pas d'où les gens arrivent pour la première fois sur le site et on leur cacherait des choses utiles à savoir, même si ils ne vont pas s'en servir.

> La place du bouton "Commencer a rédiger"

Ouais, je vois bien le problème. J'ai carrément changé le concept. Voir la capture ci-dessous.

![image](https://github.com/user-attachments/assets/faa5aac3-58b0-40d2-b06b-39a46b051b24)

L'idée de base est vraiment d'apporter une amélioration graduelle de la page d'accueil, même imparfaite. Si on se met à discuter longuement des détails, ce ne serait plus l'esprit avec lequel j'ai fait cette proposition.

2025-02-13 17:01 UTC, firm1 commented
> L'idée de base est vraiment d'apporter une amélioration graduelle de la page d'accueil, même imparfaite. Si on se met à discuter longuement des détails, ce ne serait plus l'esprit avec lequel j'ai fait cette proposition.

Je comprends mieux la philosophie. Et du coup ta dernière maquette me semble plutot OK. 
Tu peux pousser le commit ? Je ne vois pas de commit associé.

2025-02-13 20:13 UTC, Arnaud-D commented
Effectivement, j'avais oublié de pousser le commit.

2025-06-26 21:05 UTC, Situphen requested changes
Je n'ai pas encore testé mais voici déjà mes commentaires sur le backend.

2025-06-26 21:05 UTC, Situphen commented on zds/forum/managers.py
> +import django.db.models
On importe déjà `from django.db import models`
```suggestion
```

2025-06-26 21:05 UTC, Situphen commented on zds/forum/managers.py
> +    def get_last_topics(self, count) -> django.db.models.QuerySet:
À modifier comme ceci (ou à supprimer car j'ai l'impression que c'est un ajout automatique de ton éditeur)
```suggestion
    def get_last_topics(self, count) -> models.QuerySet:
```

2025-06-26 21:05 UTC, Situphen commented on zds/pages/views.py
> +    context["quote"] = random.choice(QUOTES).replace("\n", "")
Peut-être le remonter ligne 35 dans `context = { ... }` ?

2025-06-28 15:37 UTC, Arnaud-D commented on zds/forum/managers.py
> +import django.db.models
Ouaip, j'ai viré la ligne.

2025-06-28 15:38 UTC, Arnaud-D commented on zds/forum/managers.py
> +    def get_last_topics(self, count) -> django.db.models.QuerySet:
Je modifie l'import, mais je le garde l'annotation.

En fait, je trouve que c'est utile de savoir que la méthode renvoie un QuerySet, parce que ce n'est pas le cas partout dans notre code. Parfois, ce sont des listes et ça change un peu la manière de s'en servir.

2025-06-28 15:41 UTC, Arnaud-D commented on zds/pages/views.py
> +    context["quote"] = random.choice(QUOTES).replace("\n", "")
Oui, bonne idée.

2025-09-21 14:42 UTC, Situphen commented
Je viens de tester en local (désolé pour le délai) et voici quelques remarques (rapides à traiter je pense) : 

- J'ai peur que le titre "Dernières publications de la communauté" induise en erreur sur l'absence de validation. "Derniers billets de la communauté" ou "Dernières publications libres de la communauté" me semblent plus clairs.
- Dans le *call to action* "Tout le monde peut publier sur Zeste de Savoir. Pourquoi pas vous ?", le bouton "Je rédige !" pointe vers la rédaction de tutoriel alors qu'on est dans la liste des billets. Pointer vers la création de billets me semble plus logique.
- Je supprimerais le *call to action* "Des centaines d’autres publications vous attendent…" pour afficher un billet de plus, ou alors j'afficherai deux billets de plus étant donné la quantité de billets postés chaque année.

2025-09-21 18:59 UTC, Arnaud-D commented
> J'ai peur que le titre "Dernières publications de la communauté" induise en erreur sur l'absence de validation. "Derniers billets de la communauté" ou "Dernières publications libres de la communauté" me semblent plus clairs.

Je ne suis pas convaincu que ça crée de la confusion sur la validation. On a littéralement les derniers contenus validés au dessus. Peut-être quelque chose du genre "Les autres publications de la communauté ?"

Mais sinon "Publications libres", c'est jargonnant, donc je veux éviter. "Derniers billets", ça marchera tant que ce sont effectivement des billets (mais actuellement on peut faire un billet au format tuto déjà, donc...).

> Dans le _call to action_ "Tout le monde peut publier sur Zeste de Savoir. Pourquoi pas vous ?", le bouton "Je rédige !" pointe vers la rédaction de tutoriel alors qu'on est dans la liste des billets. Pointer vers la création de billets me semble plus logique.

En effet, je vais corriger ça.

> Je supprimerais le _call to action_ "Des centaines d’autres publications vous attendent…" pour afficher un billet de plus, ou alors j'afficherai deux billets de plus étant donné la quantité de billets postés chaque année.

Je pense que je vais ajouter une ligne de plus. Ce n'est pas gênant une ligne de plus, fondamentalement.

2025-09-22 16:13 UTC, Situphen approved these changes, later dismissed

2025-09-22 16:14 UTC, Situphen commented
OK, ça me va comme ça.

@philippemilink OK pour toi pour fusionner ?

2025-09-28 10:59 UTC, philippemilink reviewed
J'ai parcouru rapidement le code et testé rapidement en local, globalement tout me va.

Je suis gêné par les boutons "Montre-les moi !" / "Je rédige" / ... qui change d'apparence lorsqu'on passe la souris sur tout le bandeau, pas que le bouton. Ça donne l'impression que tout le bandeau est un lien, alors que non. J'ai corrigé ça en local avec le patch suivant : 
```diff
diff --git a/assets/scss/components/_content-item.scss b/assets/scss/components/_content-item.scss
index 43e3f01f1..2dfc3aa0c 100644
--- a/assets/scss/components/_content-item.scss
+++ b/assets/scss/components/_content-item.scss
@@ -336,12 +336,6 @@ $content-item-padding-vertical: $length-14;
 
     color: $grey-000;
 
-    &:hover {
-        .btn-call-to-action {
-            background-color: $true-white;
-            transform: scale(1.05);
-        }
-    }
 
     .call-to-action-text {
         flex: 1;
@@ -372,6 +366,10 @@ $content-item-padding-vertical: $length-14;
         transition: color $transition-duration ease-in-out,
                     background-color $transition-duration ease-in-out,
                     transform $transition-duration ease-in-out;
+        &:hover {
+            background-color: $true-white;
+            transform: scale(1.05);
+        }
     }
 }
```

Et sinon, je trouve que maintenant ça manque sur la page d'accueil d'une explication de ce que sont les différents contenus, qu'est-ce que ça veut dire "être validé par la communauté", etc. Mais je suis d'accord que ça peut venir dans une PR distincte.

2025-10-04 20:54 UTC, philippemilink approved these changes
**QA OK** :heavy_check_mark:

2025-10-04 20:54 UTC, merged